### ISSUE TITLE
provision fails on double-quote in apache custom_fragment

### ISSUE THREAD

**Issue by livewyer** [puphpet/puphpet#1024]
I added some Alias and <Location> directives into the Custom Directives field on https://puphpet.com/#webserver, which wrapped all of them in double-quotes in the generated config.yaml.  I ran vagrant provision and it said:

> There was an error loading a Vagrantfile. The file being loaded
> and the error message are shown below. This is usually caused by
> a syntax error.
> 
> Path: /var/www/ala/git/Vagrantfile
> Message: (/var/www/ala/git/puphpet/config.yaml): found unknown escape character while parsing a > quoted scalar at line 109 column 30

Which corresponds to the beginning of the custom_fragment value:

vhosts:
        2bKAp3KU0v5F:
            servername: test.local
            serveraliases:
                - www.test.local
            docroot: /var/www/drupal-7
            port: '80'
            setenv:
                - 'APP_ENV dev'
                - 'db_type  mysql'
                - 'db_name  db_name'
                - 'db_user  db_user'
                - 'db_passwd xxxxxxxx'
                - 'db_host localhost'
                - 'db_port  3306'
            override:
                - All
            options:
                - Indexes
                - FollowSymLinks
                - MultiViews
            custom_fragment: "Alias /alcts /var/www/drupal-7\r\nAlias /alcts/ano /var/www/drupal-7\r\n\r\n<Location '/alcts'>\r\n  SetEnv db_type  mysql\r\n  SetEnv db_name  dev2_testalcts\r\n  SetEnv db_user  testalcts\r\n  SetEnv db_passwd  xxxxxxx\r\n  SetEnv db_host  db_host\r\n  SetEnv db_port  3306\r\nRewriteEngine on\r\nRewriteRule (^|/)\. - [F]\r\nRewriteCond %{REQUEST_FILENAME} !-f\r\nRewriteCond %{REQUEST_FILENAME} !-d\r\nRewriteCond %{REQUEST_URI} !=/favicon.ico\r\nRewriteRule ^ index.php [L]\r\n</Location>\r\n\r\n<Location '/alcts/ano'>\r\n  SetEnv db_type  mysql\r\n  SetEnv db_name  dev2_testalctsano\r\n  SetEnv db_user  testalctsano\r\n  SetEnv db_passwd  xxxxxxxx\r\n  SetEnv db_host  db_host\r\n  SetEnv db_port  3306\r\nRewriteEngine on\r\nRewriteRule (^|/)\. - [F]\r\nRewriteCond %{REQUEST_FILENAME} !-f\r\nRewriteCond %{REQUEST_FILENAME} !-d\r\nRewriteCond %{REQUEST_URI} !=/favicon.ico\r\nRewriteRule ^ index.php [L]\r\n</Location>"
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''

If I change them to single quotes, and change the single quotes inside the <Location> elements to double-quotes, then the parser puts the "\r\n" directly into the vhost config instead of interpreting them as new lines.  This prevents Apache from starting.  

I'm actively working through various possible solutions.  In the end I need to add 60 - 80 Aliases and Location directives like this into a single vhost config.  

Thanks!

**Comment by nathanjosiah** [comment]
Is there a timeline for this being fixed? I have been trying very hard to work around this bug. The Puppet Apache module loaded in PuPHPet does not contain the [`apache::custom_config`](https://forge.puppetlabs.com/puppetlabs/apache#defined-type-apachecustom_config) class which makes this nearly impossible to work around in a sane way.

**Comment by a5e** [comment]
Got the same exact issue but it was just some ```\``` not being properly escaped like so ```\\``` in RewriteCond.

**Comment by faustot** [comment]
i'm seeing this as well in Rewrite Rules, it's removing variables defined by {} as a result.
The workaround has been to make the modifications directly via vagrant ssh after each provision which is annoying.

**Comment by chrisatomix** [comment]
Same issue, but I was able to work around it by escaping all backslashes inside the custom fragment (otherwise it was invalid YAML). I was setting up rewrite rules.

Before (not working):
```yaml
RewriteCond %{HTTP_HOST} ^www\.([^\.]+)\.([^\.]+)\.local\.dev$
```
After (working):
```yaml
RewriteCond %{HTTP_HOST} ^www\\.([^\\.]+)\\.([^\\.]+)\\.local\\.dev$
```

**Comment by jtreminio** [comment]
Apache has been completely refactored via 8525b77986f7b971c4992b249b2706cc4f0e8fde

Note: `mod_php` support has been completely dropped, but your configs are now infinitely more customizable.
