### ISSUE TITLE
Vagrant HostManager Plugin Server Alias Support

### ISSUE THREAD

**Issue by jallits** [puphpet/puphpet#1065]
Is not reading in the `serveraliases` or `server_aliases` array, respective of the flavor of Web Server chosen.

**Comment by shivapoudel** [comment]
@jallits `www.awesome.dev` for nginx it's working because it's correct but for apache you have `REDACTED1` so it's not working.

@jtreminio This is no more an issue xD

**Comment by shivapoudel** [comment]
@jtreminio this can be closed :)
