### ISSUE TITLE
PHP-Config for PHP-FPM not written to /etc/php5/fpm/pool.d/*.conf

### ISSUE THREAD

**Issue by MTon** [puphpet/puphpet#1072]
If I'm setting PHP-configuration values for the cli,  or apache vhosts  (e.g. `sendmail_path = /usr/bin/env catchmaiil -f some@address.com`), they are only written to the `php.ini` even when apache uses PHP-FPM.

But what I realy want in this case, as I'm using PHP-FPM, is these settings written to the `/etc/php5/fpm/pool.d/www.conf` or to the corresponding file for my vhosts.

I also would like to set some stuff like `php_value incluce_path /some/include/path`, but it's obviously not working as PHP-FPM expects these settings under `/etc/php5/fpm/pool.d/my.vhosts.conf

regards

**Comment by jtreminio** [comment]
Closed in #1544
