### ISSUE TITLE
Recommendation to not check mod_php makes Drupal install fail

### ISSUE THREAD

**Issue by gkatsanos** [puphpet/puphpet#1078]
That's not an issue per-se but maybe its confusing. (or I am doing something wrong?)
Trying to install a Drupal website, but I didn't have mod_php (as advised by the docu.), so the install failed.
Can we put something more clear about mod_php and PHP-FPM in the website?

also, is there a "library" of configurations for specific setups that we can peak and get inspired? (to avoid reinventing the wheel)

thank you, puphpet and vagrant are awesome

**Comment by jtreminio** [comment]
Apache has been completely refactored via 8525b77986f7b971c4992b249b2706cc4f0e8fde

Note: `mod_php` support has been completely dropped, but your configs are now infinitely more customizable.
