### ISSUE TITLE
Ubuntu 14.04 + Nginx + HHVM = No Error Logging

### ISSUE THREAD

**Issue by jimlind** [puphpet/puphpet#1099]
On initial build of my virtual box both of the services need to be restarted to get errors to log properly.
```
sudo service hhvm restart
sudo service nginx restart
sudo service hhvm restart
```
It appears that all configs are written correctly as everything works as expected afterwards.
If I've got time I'll take a look and make a PR but I thought I'd get this documented.

```
tail -f /var/log/hhvm/error.log
```

**Comment by jtreminio** [comment]
Closing in favor of #1424
