### ISSUE TITLE
Shared Folders Permissions

### ISSUE THREAD

**Issue by pfuhrmann** [puphpet/puphpet#1105]
From my research I understand that virtualbox synced folders have permissions setted up during the mounting process. Later, I am unable to change it therefore permissions for the whole synced folder MUST be same for every single file/folder in the share folder without option of changing it.

How this can work with for example Symfony where there are several different permissions for different files/folders? (i.e. app/console needs execute rights for the user of commands).

How do you people cope with this? What are yours permissions setups?

**Comment by jtreminio** [comment]
Recent changes have probably helped with this, as ssh user on `$ vagrant ssh` has group permissions to `/var/www`.

Apart from that, configuring specific parts of the project that require special permissions is something best done via exec-once files.
