### ISSUE TITLE
It's not possible to override nginx.vhosts.try_files in config.yaml

### ISSUE THREAD

**Issue by sgasser** [puphpet/puphpet#1114]
In the config.yaml it's not possible to override completely the try_files of nginx.vhosts.
I want to override it to "$uri /app.php$is_args$args;" for using [symfony](http://symfony.com/doc/current/cookbook/configuration/web_server_configuration.html#nginx).

But in the nginx.pp it's hardcoded:
```pp
  if $engine == 'php' {
    $try_files               = "${try_files_prepend} /index.php\$is_args\$args"
```

**Comment by jtreminio** [comment]
Fixed by 8d695f1c2bd4dc4440648a0a0e493a80c562db82
