### ISSUE TITLE
it's not DNS resolving?

### ISSUE THREAD

**Issue by agarzon** [puphpet/puphpet#1120]
Well, try to run this in a simple PHP script in your vagrant:

```php
var_dump(dns_get_record('google.com', DNS_NS));
```

And it will return a empty array.

Now, run the same script outside vagrant and it will work. 

any thoughts? :eyes:

**Comment by inctor** [comment]
Raising the dead here.
I'm having the exact same issue. 
Haven't been able to locate the fault, as i can ping, trace and wget without any problems.

But not dns_get_record() at all.
