### ISSUE TITLE
are exec scripts working as should be?

### ISSUE THREAD

**Issue by agarzon** [puphpet/puphpet#1121]
I've created a simple script called script.sh and put it in **exec-always**, **exec-once**, **startup-always** and startup-once folders.

test.sh
```
#!/bin/bash
sudo touch /home/vagrant/hi
sudo touch /tmp/hi
```

Then **vagrant up** and nothing happens :hear_no_evil: not matter if is the first setup or not, it never work.

**vagrant provision** ? the same, the script doesn't do what should do.

Am I missing something it is not in the documentation?

**Comment by jtreminio** [comment]
As @ogizanagi mentioned, shell scripts are run *only* if puppet executes successfully (only if you get elephants at end)

**Comment by jtreminio** [comment]
These issues seem to no longer be valid after recent changes.
