### ISSUE TITLE
Vagrant up fails early with "read operation not permitted" on /tmp data

### ISSUE THREAD

**Issue by bobdye** [puphpet/puphpet#1123]
Trying to recreate a VirtualBox VM I had created successfully earlier, I get the following error:

/usr/local/rvm/gems/ruby-1.9.3-p547@global/gems/puppet-3.4.3/lib/puppet/module.rb:60:in `read': Operation not permitted - /tmp/vagrant-puppet-4/mod
ules-0/apache/metadata.json (Errno::EPERM)

The complete log is:

$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'puphpet/centos65-x64' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Loading metadata for box 'puphpet/centos65-x64'
    default: URL: https://vagrantcloud.com/puphpet/centos65-x64
==> default: Adding box 'puphpet/centos65-x64' (v1.2) for provider: virtualbox
    default: Downloading: https://vagrantcloud.com/puphpet/boxes/centos65-x64/versions/4/providers/virtualbox.box
    default: Progress: 100% (Rate: 1615k/s, Estimated time remaining: --:--:--)
==> default: Successfully added box 'puphpet/centos65-x64' (v1.2) for 'virtualbox'!
==> default: Importing base box 'puphpet/centos65-x64'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'puphpet/centos65-x64' is up to date...
==> default: Setting the name of the VM: vmadrone_default_1411776690303_95045
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 22 => 5309 (adapter 1)
    default: 22 => 2222 (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Connection timeout. Retrying...
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
==> default: Setting hostname...
==> default: Configuring and enabling network interfaces...
==> default: Mounting shared folders...
    default: /vagrant => D:/Dropbox/Dev/vmadrone
    default: /var/www/html => D:/Dropbox/Dev/vmadrone
    default: /tmp/vagrant-puppet-4/manifests => D:/Dropbox/Dev/vmadrone/puphpet/puppet
    default: /tmp/vagrant-puppet-4/modules-0 => D:/Dropbox/Dev/vmadrone/puphpet/puppet/modules
==> default: Running provisioner: shell...
    default: Running: C:/Users/BobAdmin/AppData/Local/Temp/vagrant-shell20140926-4856-1vawod9.sh
==> default:
==> default:          ____        ____  _   _ ____      _      generated using
==> default:         |  _ \ _   _|  _ \| | | |  _ \ ___| |_   ___ ___  _ __ ___
==> default:         | |_) | | | | |_) | |_| | |_) / _ \ __| / __/ _ \| '_ ` _ \
==> default:         |  __/| |_| |  __/|  _  |  __/  __/ |_ | (_| (_) | | | | | |
==> default:         |_|    \__,_|_|   |_| |_|_|   \___|\__(_)___\___/|_| |_| |_|
==> default: Running provisioner: shell...
    default: Running: C:/Users/BobAdmin/AppData/Local/Temp/vagrant-shell20140926-4856-8gz3ci.sh
==> default: Pre-existing private key found at 'puphpet/files/dot/ssh/root_id_rsa'
==> default: Pre-existing private key found at 'puphpet/files/dot/ssh/id_rsa'
==> default: Adding generated key to /root/.ssh/id_rsa
==> default: Adding generated key to /root/.ssh/id_rsa.pub
==> default: Adding generated key to /root/.ssh/authorized_keys
==> default: Adding generated key to /home/vagrant/.ssh/id_rsa
==> default: Adding generated key to /home/vagrant/.ssh/id_rsa.pub
==> default: Adding generated key to /home/vagrant/.ssh/authorized_keys
==> default: Running provisioner: shell...
    default: Running: C:/Users/BobAdmin/AppData/Local/Temp/vagrant-shell20140926-4856-sj8yi6.sh
==> default: Downloading http://yum.puppetlabs.com/el/6/products/x86_64/puppet-3.4.3-1.el6.noarch.rpm
==> default: Error: Package: puppet-3.4.3-1.el6.noarch (/puppet-3.4.3-1.el6.noarch)
==> default:            Requires: ruby-rgen >= 0.6.5
==> default: Finished downloading http://yum.puppetlabs.com/el/6/products/x86_64/puppet-3.4.3-1.el6.noarch.rpm
==> default: Installing/Updating Puppet to version 3.4.x
==> default: Loaded plugins: presto, security, versionlock
==> default: Adding versionlock on: 0:puppet-2.7.25-2.el6
==> default: versionlock added: 1
==> default: Finished installing/updating puppet to version: Puppet v3.4.3
==> default: Running provisioner: puppet...
==> default: Running Puppet with manifest.pp...
==> default: /usr/local/rvm/gems/ruby-1.9.3-p547@global/gems/puppet-3.4.3/lib/puppet/module.rb:60:in `read': Operation not permitted - /tmp/vagrant-puppet-4/mod
ules-0/apache/metadata.json (Errno::EPERM)
==> default:    from /usr/local/rvm/gems/ruby-1.9.3-p547@global/gems/puppet-3.4.3/lib/puppet/module.rb:60:in `has_metadata?'
==> default:    from /usr/local/rvm/gems/ruby-1.9.3-p547@global/gems/puppet-3.4.3/lib/puppet/module.rb:47:in `initialize'
==> default:    from /usr/local/rvm/gems/ruby-1.9.3-p547@global/gems/puppet-3.4.3/lib/puppet/node/environment.rb:277:in `new'
==> default:    from /usr/local/rvm/gems/ruby-1.9.3-p547@global/gems/puppet-3.4.3/lib/puppet/node/environment.rb:277:in `block (2 levels) in <class:Environment>
'
==> default:    from /usr/local/rvm/gems/ruby-1.9.3-p547@global/gems/puppet-3.4.3/lib/puppet/node/environment.rb:275:in `collect'
==> default:    from /usr/local/rvm/gems/ruby-1.9.3-p547@global/gems/puppet-3.4.3/lib/puppet/node/environment.rb:275:in `block in <class:Environment>'
==> default:    from /usr/local/rvm/gems/ruby-1.9.3-p547@global/gems/puppet-3.4.3/lib/puppet/util/cacher.rb:55:in `cached_value'
==> default:    from /usr/local/rvm/gems/ruby-1.9.3-p547@global/gems/puppet-3.4.3/lib/puppet/util/cacher.rb:29:in `block in cached_attr'
==> default:    from /usr/local/rvm/gems/ruby-1.9.3-p547@global/gems/puppet-3.4.3/lib/puppet/node/environment.rb:203:in `each_plugin_directory'
==> default:    from /usr/local/rvm/gems/ruby-1.9.3-p547@global/gems/puppet-3.4.3/lib/puppet/util/command_line.rb:129:in `run'
==> default:    from /usr/local/rvm/gems/ruby-1.9.3-p547@global/gems/puppet-3.4.3/lib/puppet/util/command_line.rb:91:in `execute'
==> default:    from /usr/local/rvm/gems/ruby-1.9.3-p547@global/gems/puppet-3.4.3/bin/puppet:4:in `<top (required)>'
==> default:    from /usr/local/rvm/rubies/ruby-1.9.3-p547/bin/puppet:23:in `load'
==> default:    from /usr/local/rvm/rubies/ruby-1.9.3-p547/bin/puppet:23:in `<main>'
==> default:    from /usr/local/rvm/gems/ruby-1.9.3-p547@global/bin/ruby_executable_hooks:15:in `eval'
==> default:    from /usr/local/rvm/gems/ruby-1.9.3-p547@global/bin/ruby_executable_hooks:15:in `<main>'
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

**Comment by jtreminio** [comment]
Sorry about this delay. Paste your `config.yaml` for me.
