### ISSUE TITLE
CentOS image freshness

### ISSUE THREAD

**Issue by markushausammann** [puphpet/puphpet#1133]
What's your policy regarding the state of images. If `yum upgrade` after vagrant up leads to 75 packages with upgrades, is that acceptable?

**Comment by jtreminio** [comment]
Unfortunately there's not much I can do in this regard. I would suggest you apply security fixes, of course, but things like upgrading a puphpet-installed package would be at your own risk.

I wouldn't be able to even begin to keep up with all changes from an upgrade :(
