### ISSUE TITLE
Some errors / warnings during installation of Centos 6.5 / PHP 5.4 with modules on OS X Mavericks

### ISSUE THREAD

**Issue by sleicester** [puphpet/puphpet#1136]
First off, thanks for the amazing tool and flexible configuration, very cool!

[config.yaml](https://gist.github.com/77d5077e576bb9d9140f)

I've had some errors mainly related to PHP and as a result am receiving 503 errors. Namely around the following:

    ==> default: Warning: Could not retrieve fact fqdn
    ==> default: Error: Could not find package php-sqlite
    ==> default: Error: /Stage[main]/Main/Php_mod[sqlite]/Puphpet::Php::Module[sqlite]/Php::Module[sqlite]/Package[PhpModule_sqlite]/ensure: change from absent to present failed: Could not find package php-sqlite
    ==> default: Error: Could not find package php-xsl
    ==> default: 
    ==> default: Error: /Stage[main]/Main/Php_mod[xsl]/Puphpet::Php::Module[xsl]/Php::Module[xsl]/Package[PhpModule_xsl]/ensure: change from absent to present failed: Could not find package php-xsl
    ==> default: Error: Could not find package php-curl
    ==> default: Error: /Stage[main]/Main/Php_mod[curl]/Puphpet::Php::Module[curl]/Php::Module[curl]/Package[PhpModule_curl]/ensure: change from absent to present failed: Could not find package php-curl
    ==> default: Warning: /Stage[main]/Main/Php_pear_mod[SOAP]/Puphpet::Php::Pear[SOAP]/Php::Pear::Module[SOAP]/Exec[pear-SOAP]: Skipping because of failed dependencies
    ==> default: Warning: /Stage[main]/Main/Php_pecl_mod[pecl_http]/Puphpet::Php::Pecl[pecl_http]/Php::Pecl::Module[pecl_http]/Exec[pecl-pecl_http]: Skipping because of failed dependencies
    ==> default: Warning: /Stage[main]/Main/Php_pecl_mod[zip]/Puphpet::Php::Pecl[zip]/Php::Pecl::Module[zip]/Exec[pecl-zip]: Skipping because of failed dependencies
    ==> default: Warning: /Stage[main]/Main/Php_pecl_mod[xmlwriter]/Puphpet::Php::Pecl[xmlwriter]/Php::Pecl::Module[xmlwriter]/Exec[pecl-xmlwriter]: Skipping because of failed dependencies
    ==> default: Warning: /Stage[main]/Main/Php_pecl_mod[PDO_MYSQL]/Puphpet::Php::Pecl[PDO_MYSQL]/Php::Pecl::Module[PDO_MYSQL]/Exec[pecl-PDO_MYSQL]: Skipping because of failed dependencies
    ==> default: Warning: /Stage[main]/Main/Php_pecl_mod[xmlReader]/Puphpet::Php::Pecl[xmlReader]/Php::Pecl::Module[xmlReader]/Exec[pecl-xmlReader]: Skipping because of failed dependencies
    ==> default: Warning: /Stage[main]/Main/Php_pecl_mod[domxml]/Puphpet::Php::Pecl[domxml]/Php::Pecl::Module[domxml]/Exec[pecl-domxml]: Skipping because of failed dependencies
    ==> default: Warning: /Stage[main]/Main/Service[php-fpm]: Skipping because of failed dependencies

Here is the [full output from the terminal](https://gist.github.com/4b6e04bcfe8f41179d04).

**Comment by creativelifeform** [comment]
@bickerstoff thanks for this! For some reason php-fpm got a failed dependencies message for me on the initial vagrant up but after starting it manually it seemed to work

**Comment by jtreminio** [comment]
All these have been fixed.
