### ISSUE TITLE
Synced Folder Error when using puphet with parallels provider

### ISSUE THREAD

**Issue by neilneyman** [puphpet/puphpet#1139]
I used puphet to generate a centos box using the parallels provider.  I believe the generated Vagrantfile contained a bug. On vagrant up I got the following error once Parallels tools was up-to-date.  Using  Parallels Desktop 10.

```shell
Failed to mount folders in Linux guest. You've specified mount options
which are not supported by "prl_fs" file system.

Invalid mount options: ["dmode=775", "fmode=764"]
```

Editing the Vagrantfile to remove the dmode & fmode options filxed the issue.

**Comment by jtreminio** [comment]
fixed by

      elsif data['vm']['chosen_provider'] == 'parallels'
        config.vm.synced_folder "#{folder['source']}", "#{folder['target']}", id: "#{i}",
          group: sync_group, owner: sync_owner, mount_options: ['share']
