### ISSUE TITLE
MySQL bind address

### ISSUE THREAD

**Issue by aequasi** [puphpet/puphpet#1149]
I'd love to be able to edit the bind address on mysql. We are given the option on both mongo and redis (possibly others too).

**Comment by aequasi** [comment]
bump

**Comment by delboy1978uk** [comment]
wait, having seen thomaspicquet's post, don't we just put bind-address: '0.0.0.0' directly into override_options: {  } in the yaml? i see that there under mysql. will give it a try when i'm next playing with it.

**Comment by delboy1978uk** [comment]
OK guys, this issue can be closed! As per this pull request https://github.com/puphpet/puphpet/issues/1035
Here's how you do it!

mysql:
    install: '1'
    override_options:  
        mysqld:
            bind-address : '0.0.0.0'
    etc...
    etc....

provision/reload and thats it! Job Done!

**Comment by delboy1978uk** [comment]
argh the formatting is lost, mysqld: is 4 spaces in from override_options:, and bind-address: is four spaces in from mysqld:

**Comment by jtreminio** [comment]
Done in #1303
