### ISSUE TITLE
Postgre hba configuration

### ISSUE THREAD

**Issue by charlieWasp** [puphpet/puphpet#1150]
Hello! First of all thank you for the great project!

I ran into one issue with PostgreSQL installation. I can't login with `psql` after installation because *peer authentication is failed*. I look at pg_hba.conf file, and see that:

```
# Rule Name: local access as postgres user
# Description: none
# Order: 001
local   all     postgres     ident
```

I suppose there must be 'md5' instead of 'ident', am I wrong? I change it, and now all work. But I'll need to do it after every `vagrant up`. 

Am I missing some parameter in configuration?

**Comment by jtreminio** [comment]
Fixed by 90f4b73
