### ISSUE TITLE
nslookup on box not returning, even when host is

### ISSUE THREAD

**Issue by toby-griffiths** [puphpet/puphpet#1173]
I am trying to use the gethostbyname() PHP DNS lookup function, however its not working.

I tried doing an `dig` while ssh-ed into the vagrant box, and it can't find the DNS entry for the domain (will work OK for 'google.com' as an example).

If I do a `dig` on the host machine it can see the new domain A record without any problems.

Does anyone know why the host would be able to see the new domain, but the VM wouldn't?

Also, the nslookup doesn't work on either host or VM.  I'm assuming this is due to propagation, but how come `dig` works OK, but `nslookup` doesn't?

**Comment by jtreminio** [comment]
You can add the option here:

    ---
    vagrantfile-local:
        vm:
            box: puphpet/debian75-x64
            box_url: puphpet/debian75-x64
            hostname: ''
            memory: '512'
            cpus: '1'
            chosen_provider: virtualbox
            network:
                private_network: 192.168.56.176
                forwarded_port:
                    KuCtD2gG32Ri:
                        host: '9323'
                        guest: '22'
            post_up_message: ''
            provider:
                virtualbox:
                    modifyvm:
                        natdnshostresolver1: on
                        natdnsproxy1: on

**Comment by head82** [comment]
natdnsproxy expects 'on' or 'off'. Without quotes it will be casted to true and didn't work.

            provider:
            virtualbox:
                modifyvm:
                    natdnshostresolver1: on
                    natdnsproxy1: 'on'
