### ISSUE TITLE
Vagrant Puphpet Import Large Sql ~ 4gb

### ISSUE THREAD

**Issue by ghost** [puphpet/puphpet#1176]
Hey there,

I try to import a large sql file on vagrant up. But I always get an timeout  error on that step. I tried to modifiy the file \puphpet\puppet\modules\mysql\manifests\db.pp to increase the timeout time.

if $sql_file {
      exec{ "${dbname}-import":
        command     => "/usr/bin/mysql ${dbname} < ${sql_file}",
    timeout     => '0',
        logoutput   => true,
        environment => "HOME=${::root_home}",
        refreshonly => false,
        refresh     => false,
        require     => Mysql_grant["${user}@${host}/${table}"],
        subscribe   => Mysql_database[$dbname],
      }
    }

Same error. Could anybody help me out?

**Comment by NoelDavies** [comment]
@jtreminio is there no actual fix for this no? Just providing a work-around doesn't help especially with that puppet is trying to achieve (Varying config's etc)

**Comment by jtreminio** [comment]
@NoelDavies per https://docs.puppetlabs.com/references/latest/type.html#exec-attribute-timeout the `timeout => '0',` should prevent this.

If it's not I'm assuming it's something else in the mysql module that I have been unable to figure out.

The best fix is simply to do it outside of Puppet and run it in a bash script.
