### ISSUE TITLE
AWS EC2 Instance Types

### ISSUE THREAD

**Issue by vacquah** [puphpet/puphpet#1177]
I am generating an error when using the m1.small instance type. It installs ok, but a few hours after doing a vagrant halt, when trying to bring it back up, I get an aws error saying the instance is not available in my region anymore ( useast ). The aws documentation shows this is a legacy instance. I tried using the t2.small instance ( from current gen instance list - had to add a VPC subnet id to the config.yaml and vagrantfile) .  I am now getting error messages relating to the AMI - None of the ones available via the puphpet GUI support the new t2 instances.  Is there an AMI with puphpet support that works with any of the current gen instances? ( for either Unbuntu 12 or 14 )

**Comment by jtreminio** [comment]
I do not believe `vagrant halt` and `vagrant suspend` are supported by the vagrant-aws plugin. The concepts make no sense to these types of servers, I think?

This is not a puphpet issue, though. You should ask https://github.com/mitchellh/vagrant-aws
