### ISSUE TITLE
Ok to add Documentation?

### ISSUE THREAD

**Issue by mediadoneright** [puphpet/puphpet#1178]
I feel puphpet would benefit from some additional documentation.  I've been playing with Puphpet for the last two days, and ran into various questions / roadblocks ... It'd be nice to have had documentation to help a begginer understand what to expect, what some of the requirements/limitations are.

I'd like to _volunteer to write more documentation_ ... either:

1. a series of __text.md__ files that live in the puphpet repo, or 
2. alternatively the __github wiki__

However, I don't want to spend time on something that won't be committed or isn't the direction you'd like.  Let me know

**Comment by morsok** [comment]
:+1: 
I'd also like to help on that :)
