### ISSUE TITLE
RVM 1.26.0 - Introduces signed releases and automated check of signatures - Fails vagrant up

### ISSUE THREAD

**Issue by joeykrim** [puphpet/puphpet#1181]
The 'vagrant up' command fails due to forced signature checking on newest RVM 1.26.0 packages (https://github.com/wayneeseguin/rvm/releases/tag/1.26.0) and the keys aren't loaded prior to installing RVM 1.26.0. 
Logging into the server as root and running: "gpg --keyserver hkp://keys.gnupg.net --recv-keys D39DC0E3" and then running vagrant provision finishes the original vagrant up command.

Details below:
==> default: Warning, RVM 1.26.0 introduces signed releases and automated check of signatures when GPG software found.
==> default: Assuming you trust Michal Papis import the mpapis public key (downloading the signatures).
==> default: GPG signature verification failed for '/usr/local/rvm/archives/rvm-1.26.0.tgz' - 'https://github.com/wayneeseguin/rvm/releases/download/1.26.0/1.26.0.tar.gz.asc'!
==> default: try downloading the signatures:
==> default:     gpg --keyserver hkp://keys.gnupg.net --recv-keys D39DC0E3
==> default: they can be compared with:
==> default:     https://rvm.io/mpapis.asc
==> default:     https://keybase.io/mpapis
...
==> default: /tmp/vagrant-shell: line 54: /usr/bin/gem: No such file or directory
==> default: Finished installing Puppet requirements
==> default: Installing Puppet 3.4.3
==> default: /tmp/vagrant-shell: line 58: /usr/bin/gem: No such file or directory
==> default: Finished installing Puppet 3.4.3
==> default: Running provisioner: puppet...
The `puppet` binary appears not to be in the PATH of the guest. This
could be because the PATH is not properly setup or perhaps Puppet is not
installed on this guest. Puppet provisioning can not continue without
Puppet properly installed.
_Exits to terminal prompt_
j@j:~/vagrant/dk32lk/puphet$

**Comment by yellow1912** [comment]
This is driving me nuts with Google Cloud Engine.

I used vagrant ssh to login, then manually ran:

```
gpg --keyserver hkp://keys.gnupg.net --recv-keys D39DC0E3

gpg: requesting key D39DC0E3 from hkp server keys.gnupg.net
gpg: key D39DC0E3: "Michal Papis (RVM signing) <mpapis@gmail.com>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
```


However, I still encounter the exact same error when I try vagrant provision.

```
==> default: Installing Ruby 1.9.3 using RVM
==> default: Turning on quiet curl mode.
==> default: Downloading https://github.com/wayneeseguin/rvm/archive/1.26.8.tar.gz
==> default: Downloading https://github.com/wayneeseguin/rvm/releases/download/1.26.8/1.26.8.tar.gz.asc
==> default: gpg: Signature made Sun 04 Jan 2015 11:47:58 PM UTC using RSA key ID BF04FF17
==> default: gpg: Can't check signature: public key not found
==> default: Warning, RVM 1.26.0 introduces signed releases and automated check of signatures when GPG software found.
==> default: Assuming you trust Michal Papis import the mpapis public key (downloading the signatures).
==> default:
==> default: GPG signature verification failed for '/usr/local/rvm/archives/rvm-1.26.8.tgz' - 'https://github.com/wayneeseguin/rvm/releases/download/1.26.8/1.26.8.tar.gz.asc'!
==> default: try downloading the signatures:
==> default:
==> default:     sudo gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
==> default:
==> default: or if it fails:
==> default:
==> default:     command curl -sSL https://rvm.io/mpapis.asc | sudo gpg --import -
==> default:
==> default: the key can be compared with:
==> default:
==> default:     https://rvm.io/mpapis.asc
==> default:     https://keybase.io/mpapis
==> default: /tmp/vagrant-shell: line 66: /usr/local/rvm/scripts/rvm: No such file or directory
==> default: /tmp/vagrant-shell: line 82: /usr/local/rvm/bin/rvm: No such file or directory
==> default: /tmp/vagrant-shell: line 84: /usr/bin/gem: No such file or directory
==> default: Finished install Ruby 1.9.3 using RVM
```
