### ISSUE TITLE
Add custom module for Puppetfile

### ISSUE THREAD

**Issue by kororo** [puphpet/puphpet#1235]
Hi there,

I wonder, how to add more Puppet module from forge? Lets say, I added this line in the Puppetfile

```
mod 'svn', :git => 'https://github.com/example42/puppet-svn.git'
```

Could you please let me know how to automatically download the module folder?

Thanks

**Comment by nmeirik** [comment]
I too am interested in this use case, specifically for installing https://github.com/saz/puppet-sudo. When you mention installing librarian-puppet and running librarian-puppet install, is this done on the host machine or on the VM. And if on the VM, is this best placed somewhere in the existing shell provisioners? Or is this better handled as a one time thing?

**Comment by jtreminio** [comment]
librarian-puppet can be installed on existing VM or on your host machine, since it doesn't actually run any Puppet code, it just downloads requirements.
