### ISSUE TITLE
Add authentication to Solr dashboard

### ISSUE THREAD

**Issue by jtreminio** [puphpet/puphpet#1237]
Currently the Solr dashboard is open if you know the port.

There's ways to add authentication: http://wiki.apache.org/solr/SolrSecurity#Path_Based_Authentication

Should implement something within the gui

**Comment by jtreminio** [comment]
Solr support dropped :(

**Comment by mkindred** [comment]
Oh, that's unfortunate. What caused this? I guess I'll have to post-install script for Solr.
