### ISSUE TITLE
PHP5.6 not provisioned

### ISSUE THREAD

**Issue by woudwijk84** [puphpet/puphpet#1240]
hi, i wanted to use PHP5.6 in my vagrant machine but i get errors when provisioning the machine. I get this error in my command prompt:
 `==> default: Error: Could not set 'present' on ensure: No such file or directory - /etc/php5/mods-available/zzzz_custom.ini at 243:/tmp/vagrant-puppet-3/modules
-0/puphpet/manifests/php/ini.pp ==> default: Error: Could not set 'present' on ensure: No such file or directory - /etc/php5/mods-available/zzzz_custom.ini at 243:/tmp/vagrant-puppet-3/modules
-0/puphpet/manifests/php/ini.pp ==> default: Wrapped exception: ==> default: No such file or directory - /etc/php5/mods-available/zzzz_custom.ini ==> default: Error: Stage[main]/Main/Puphpet::Php::Ini[cgi.fix_pathinfo]/File[/etc/php5/mods-available/zzzz_custom.ini]/ensure: change from absent to present failed: Could not set 'present' on ensure: No such file or directory - /etc/php5/mods-available/zzzz_custom.ini at 243:/tmp/vagrant-puppet-3/modules-0/puphpet/manifests/php/ini.pp`

Here is my [config.yaml](https://github.com/woudwijk84/divelog/blob/master/vagrant/puphpet/config.yaml).

How can i resolve this problem?

Thanks in advance.

**Comment by zorji** [comment]
I am having the same issue. puphpet.com does not have Ubuntu 14 for AWS. Is it supported?
