### ISSUE TITLE
How do I update puphpet (Vagrant?) to the latest version?

### ISSUE THREAD

**Issue by gplusdotgr** [puphpet/puphpet#1247]
How do I update puphpet (Vagrant?) to the latest version?

**Comment by Ardakilic** [comment]
Late bump: How do I know that a new version is available so I need to drag-drop my `config.yaml` file and re-download it ?

As far as I can tell [the releases page](https://github.com/puphpet/puphpet/releases) isn't that much updated, unlike the commits.

Any idea would be appreciated.
