### ISSUE TITLE
Vagrant ssh keep asking for password

### ISSUE THREAD

**Issue by wcalderipe** [puphpet/puphpet#1253]
I don't know why but vagrant still asking for ssh password I did about three clean installs of vagrant with different configuration of puphuet I also restart my computer and VirtualBox.

$ vagrant ssh
vagrant@127.0.0.1's password:

How can I fix it?

**Comment by dannyvaughton** [comment]
I'm also getting this issue - I'm on Mac OSX Mavericks. Anyone else solved this? Using the latest puphpet config off website.

**Comment by jtreminio** [comment]
This commit should have fixed the issue: 84db23ed730be1ec901f8d35747e3b6f179dae52

@dannyvaughton Can you paste your `Vagrantfile`? Did you generated it within the last 12 hours?

**Comment by hackeron** [comment]
I'm having this issue on Mac Yosemite with Ubuntu Trusty 64:

VirtualBox is 4.3.20, Vagrant is 1.7.2

```ruby
$ cat Vagrantfile | egrep -v "^  #|^#|^\s*$"
Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.ssh.username = "deployer"
  config.ssh.insert_key = true
end
```

```
$  vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'ubuntu/trusty64'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'ubuntu/trusty64' is up to date...
==> default: Setting the name of the VM: vagrant_default_1422908718801_63182
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 22 => 2222 (adapter 1)
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: deployer
    default: SSH auth method: private key
    default: Warning: Connection timeout. Retrying...
    default: Warning: Authentication failure. Retrying...
Text will be echoed in the clear. Please install the HighLine or Termios libraries to suppress echoed text.
deployer@127.0.0.1's password:
```

Why is it asking for a password? :( - Any ideas how to fix?

**Comment by jtreminio** [comment]
@hackeron can you paste the result of `$ vagrant box list`?

**Comment by hackeron** [comment]
Sure:

```
$ vagrant box list
ubuntu/trusty64                (virtualbox, 14.04)
ubuntu/ubuntu-core-devel-amd64 (virtualbox, 15.04)
```

**Comment by jtreminio** [comment]
Sorry, those aren't puphpet boxes. While any random box *should* work, due to the sh files bootstrapping everything from scratch, I can't offer support for anything but the boxes I maintain.

**Comment by Anyoks** [comment]
For anyone who gets this problem. it took me ages to fix. (Yet the fix is easy!!) So, According to Vagrant documentation there is a default password for 'vagrant' user which is 'vagrant' without the single quotes. you can read more on the same on their [Official website] (http://docs.vagrantup.com/v2/boxes/base.html)

**Comment by kenju254** [comment]
@Anyoks this was a saviour..

**Comment by boomshadow** [comment]
Super cool props to @Anyoks . That was totally what I needed! Thanks!!!!

**Comment by Anyoks** [comment]
@kenju254   and @boomshadow  I'm Glad you found this Helpful!

**Comment by craigglennie** [comment]
If you want to avoid the password, the easiest way is to use the SSH config file output by vagrant. The trick is to login as `vagrant@default`not `vagrant@127.0.0.1` or `vagrant@localhost`. This is because the config output by ssh-config is for a host called `default`.

```bash
# Write the ssh config to a file
vagrant ssh-config > ssh.config
# Tell ssh to use this config file instead of your user config file (if it exists)
ssh -F ssh.config vagrant@default
```

You could also copy this into your user-level ssh config, if you wanted, then you wouldn't need to use the -F argument when you SSH.

**Comment by spekary** [comment]
The default password is not working for me.

**Comment by maces** [comment]
When even the default password is not working shutdown the VM via Virtualbox GUI/VMWare/ect.. Then start it via the Virtualbox GUI. Now you should have a login promt, in Virtualbox new Window for the VM. There insert user: "vagrant" (no password needed). When logged in, type "passwd" and give yourself the password "vagrant" again. Now Login via SSH (with password) should be possible again, so you can restore SSH-keys.

**Comment by Xample** [comment]
Some possible issues:
1. You are connecting to the wrong port, specify it using the -p option
```ssh vagrant@127.0.0.1 -p 2200```
default password is ```vagrant```
2. Otherwise bypass the password providing the private_key path 
```ssh vagrant@127.0.0.1 -p 2200 -i /Users/example/kubernetes/.vagrant/machines/minion-1/virtualbox/private_key```

To get the port nb and IdentityFile path (private_key path) using:

```vagrant ssh-config```

Host minion-1
  HostName 127.0.0.1
  User vagrant
  Port **2200**
  UserKnownHostsFile /dev/null
  StrictHostKeyChecking no
  PasswordAuthentication no
  IdentityFile **/Users/example/kubernetes/.vagrant/machines/minion-1/virtualbox/private_key**
  IdentitiesOnly yes
  LogLevel FATAL

**Comment by SultanICQ** [comment]
I solved this issue deleting the line corresponding to the 127.0.0.1:2222 server inside my .ssh/know_hosts.

When I tried to ssh directly I received this warning:

    @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
    @    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @
    @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
    IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!
    Someone could be eavesdropping on you right now (man-in-the-middle attack)!
    It is also possible that a host key has just been changed.
    The fingerprint for the RSA key sent by the remote host is
    86:97:76:81:eb:fc:22:7f:2e:8a:79:4d:7f:8e:8b:a8.
    Please contact your system administrator.
    Add correct host key in /Users/username/.ssh/known_hosts to get rid of this message.
    Offending RSA key in /Users/username/.ssh/known_hosts:343
    RSA host key for [127.0.0.1]:2222 has changed and you have requested strict checking.
    Host key verification failed.

This happens because I use a couple of vagrant machines with the same ip:port and had strict checking in my ssh configuration.

Once I deleted the line 343 the process worked fine.

**Comment by 573** [comment]
Had [this](https://github.com/puphpet/puphpet/issues/1253#issuecomment-72531100) issue too:

My vagrant box started to prompt for clear text password input on each up/halt etc.

Finally `ssh-config` told me it was ${vagrant_vm_folder}\.vagrant\machines\default\virtualbox\insecure_private_key causing it, so I removed that in favour of my private key or alternatively ${userprofile}/.vagrant.d/insecure_private_key.

**Comment by Gerst20051** [comment]
:+1: adding ```config.ssh.insert_key = false``` to the Vagrantfile and removing the vm private key automatically updated ```vagrant ssh-config``` with the correct private key ```~/.vagrant.d/insecure_private_key```. The last thing I had to do was update the authorized keys file on the vm. ```curl https://raw.githubusercontent.com/mitchellh/vagrant/master/keys/vagrant.pub > ~/.ssh/authorized_keys```

**Comment by rodrigorrch** [comment]
I put password 'vagrant' and passed

**Comment by mvggit** [comment]
>> Why is it asking for a password? :( - Any ideas how to fix?

I thing ssh-keygen compleate with pasword. Try compile ssh key with option without password -P "" (ssh-keygen -t rsa -C "rsa_key" -q -P "").

**Comment by bblaette** [comment]
I had this problem in combination with non-stop "Warning: Authentication failure.".

I used to do the workaround from [dylanschoenmakers and mtchavez](https://github.com/mitchellh/vagrant/issues/5186#issuecomment-77681605). You basically ssh into the box (like [Anyoks](https://github.com/puphpet/puphpet/issues/1253#issuecomment-73663015) or [maces](https://github.com/puphpet/puphpet/issues/1253#issuecomment-105419048)) and add vagrant's insecure public key to ``.ssh/authorized_keys``. You can wget it (see thread) or find it in your vagrant install, e.g. on my host it's at 
``cat /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/keys/vagrant.pub``.

However, vagrant kept removing the insecure key upon reload. So I did something similar to [Gerst20051](https://github.com/puphpet/puphpet/issues/1253#issuecomment-116874912) (thank you!) and let puphpet regenerate its own keys (not the insecure one). Removing the ``id_rsa*`` and ``root_id_rsa*`` keys from ``puphpet/files/dot/ssh`` (backup your files first), then ``vagrant reload --provision`` recreated the keys. To prevent vagrant from inserting new keys, I also added ``config.ssh.insert_key = false`` to my ``puphpet/vagrant/Vagrantfile-local`` file, or rather 

    if !data['ssh']['insert_key'].nil?
      config.ssh.insert_key = data['ssh']['insert_key']
    end

after``vagrantKey = ...`` to have it configurable in config.yaml.

**Comment by sespinosa** [comment]
for some dumb people like me, do not use /home/vagrant as your shared folder (in your vm), because the .ssh files are not accesible.

**Comment by byteshiva** [comment]
I too faced the similar issue, as  @sespinosa pointed out, don't share on vagrant it will overwrite .ssh directory.

**Comment by WangWenchao** [comment]
https://docs.vagrantup.com/v2/vagrantfile/ssh_settings.html   
config the ssh username and password and insert_key to be true  could resolve your problem

**Comment by oioki** [comment]
I had this problem too, on OpenSSH 7.1:
```
# ssh -v default
...
debug1: Skipping ssh-rsa key /home/oioki/.vagrant.d/insecure_private_key for not in PubkeyAcceptedKeyTypes
debug1: No more authentication methods to try.
Permission denied (publickey,password).
```

Adding this to ~/.ssh/config helps:
```
PubkeyAcceptedKeyTypes ssh-dss,ssh-rsa
```

**Comment by maxfenton** [comment]
If it's any help to anyone, I was running into a similar problem. When I tried to `ssh vagrant@[served IP address]` I got a clear error that there was already a line in my `~/.ssh/known_hosts` file for that address and it was different. The connection was being dropped as a security measure. By removing that one line in `known_hosts` my id_rsa key and the password 'vagrant' worked again.

This was after doing a `vagrant destroy` and provisioning to the same project directory with a different puphpet configuration.

**Comment by Aigelov** [comment]
@maces thanks, it helped me!

**Comment by forgetso** [comment]
Rather than log in with ssh user@vagrantbox just type vagrant ssh

**Comment by rustamagasanov** [comment]
One more possible situation is when you link any host's directory to `/home/vagrant` which replaces everything inside, so your `/home/vagrant/.ssh` disappears

**Comment by vindexins** [comment]
I got this situations after cleaning ~/.ssh in the guest machine.
And found a solution.

1. add to Vagrantfile:
config.ssh.password = 'YOUR PASSWORD'
config.ssh.forward_agent = true
config.ssh.private_key_path = 'PATH TO NEW KEY'

2. vagrant reload

2. vagrant ssh-config

3. vagrant ssh
you can sign in by password
check that vagrant put into guest machine new authorized_keys into ~/.ssh

4. clean Vagrantfile:
remove options from step one

5. vagrant reload

It's work for me.

**Comment by dwenzel** [comment]
I had a similar issue after upgrading VirtualBox from 4.3.x to  5.0.24. 
```
[machineDirector]y$ vagrant ssh
```
still worked, but establishing a tunnel via 
```
[machineDirector]$  ssh -L 8080:127.0.0.1:80 vagrant@127.0.0.1 -p 2222 -i ~/.vagrant.d/insecure_private_key
```
failed with 
```
vagrant@127.0.0.1's password: 
Permission denied, please try again.
```
I just copied the insecure privat key from the machine directory to my home directory:
```
[machineDirector]$ mv ~/.vagrant.d/insecure_private_key ~/.vagrant.d/insecure_private_key.2016-07-22.back
[machineDirector]$ cp .vagrant/machines/default/virtualbox/private_key ~/.vagrant.d/insecure_private_key
```

**Comment by devtosystems** [comment]
But..


```bash
$ vagrant reload
Ignoring ruby-libvirt-0.7.0 because its extensions are not built.  Try: gem pristine ruby-libvirt --version 0.7.0
tosystems@localhost's password: 
==> default: Halting domain...
==> default: Starting domain.
==> default: Waiting for domain to get an IP address...
==> default: Waiting for SSH to become available...
@localhost's password: @localhost's password: 
Permission denied, please try again.
@localhost's password: 
Permission denied, please try again.
@localhost's password: 
Permission denied, please try again.
@localhost's password: 
```

:(

**Comment by mkallango** [comment]
Do you know if your base box is configured with vagrant user? Because mine was not.
I've downloaded a Windows Box official from Microsoft and had the same issue. But I figured out that the user and pass was incorrect, so I've updated the Vagrantfile with the following config:

    config.ssh.username = "IEUser"  
    config.ssh.password = "Passw0rd!"      
    config.ssh.insert_key = false  

and now it works fine:

```shell
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: IEUser
    default: SSH auth method: password
==> default: Machine booted and ready!
```

**Comment by kays-kays** [comment]
issue resolved for me too

**Comment by RoyalFlush24** [comment]
username: vagrant
password: vagrant
this worked for me hopefully this help

**Comment by logicbox** [comment]
Previously I just used the default keys generated by Vagrant for my dev boxes, however after upgrading Vagrant and Virtual Box I was prompted for a password for my virtual machines.
 
Copying the insecure key from 

`C:\Users\{user}\.vagrant.d\insecure_private_key`

Over the existing key in

`{dir}\.vagrant\machines\default\virtualbox\private_key`

Caused Vagrant to detect insecure key and generate a new private key. vagrant ssh now works without a password, hope this helps some people!

(post note: You probably need to do a `vagrant reload` and enter the default generated key once to get this working - i.e. from `C:\Users\{user}\.vagrant.d\boxes\{boxname}\{version}\virtualbox\Vagrantfile` )

**Comment by TheComputerM** [comment]
Try password as vagrant. It worked for me.

**Comment by metalsapien** [comment]
> Anyone already pass thru this?

The default password for windows environment is 'vagrant'
