### ISSUE TITLE
Premature end of script headers

### ISSUE THREAD

**Issue by nleroy** [puphpet/puphpet#1269]
Hi

I have a puphpet box with apache2 and mod_proxy_fcgi. When running my web application, I get this error in the logs: "Premature end of script headers"
Any idea what the problem could be? Is it a memory problem? What conf or parameter to change/add?

Thanks for your input!

**Comment by jtreminio** [comment]
Apache has been completely refactored via 8525b77986f7b971c4992b249b2706cc4f0e8fde

Note: `mod_php` support has been completely dropped, but your configs are now infinitely more customizable.
