### ISSUE TITLE
More settings for the RabbitMQ

### ISSUE THREAD

**Issue by thiagotalma** [puphpet/puphpet#1270]
The default configuration of RabbitQM is not safe.

In addition to the port other configurations could be made significant.
For example, remove the default user and create a username and password for the administrator.

**Comment by craig-davis** [comment]
+1

**Comment by kuddl** [comment]
+1 
That would be great. I just started with vagrant/puppet/puphpet and it is a great help! Never been so easy to set up a DEV Box. 
And adding Users to Rabbit MQ is something I would love to see! 
Unfortunately I can't send a PR .. since I just started with it ... I hope someone can help here!
