### ISSUE TITLE
Error 0307A071 setting up puPhpet box 

### ISSUE THREAD

**Issue by kmseverin** [puphpet/puphpet#1292]
I am having an issue with the puphpet. The error message is telling me that the box cannot be found. See attached file.
![capture](https://cloud.githubusercontent.com/assets/7805656/5559916/cf34030e-8d27-11e4-985a-065373da11c8.PNG)

**Comment by jtreminio** [comment]
Hi, I'm sorry but this isn't a puphpet issue.

Make sure your Vagrant is up to date and try again.
