### ISSUE TITLE
Error: Invalid parameter proxy_enabled on node localhost

### ISSUE THREAD

**Issue by OddenCreative** [puphpet/puphpet#1295]
I have gotten this issue. Can you point to where this might need to be fixed? I am on Mavericks.

I am pasting a gist because it won't paste as an attachement...

https://gist.github.com/OddenCreative/ef4343fd415dea0872ab

**Comment by hyperized** [comment]
The issue can be temporarely solved by commenting out the line in your config.yaml for each vhost.

**Comment by hyperized** [comment]
It seems that #1285 is also dealing with this issue.

I'm not sure, but shouldnt proxy_enabled simply be proxy? puphet/puppet/modules/nginx/resource/vhost.pp seems to only define proxy, and no proxy_enabled.
