### ISSUE TITLE
Add DHCP option to ease network configuration

### ISSUE THREAD

**Issue by Rvanlaak** [puphpet/puphpet#1296]
The part with the `Local VM Details` has a couple of fields to set the Local IP address. It is quite easy to let Vagrant configure DHCP.

https://docs.vagrantup.com/v2/networking/public_network.html

Can you add an option to 
1. Let the VM use DHCP to get an IP address
2. Output the obtained IP address in the vagrant output

**Comment by Rvanlaak** [comment]
ping @jtreminio 

Some extra options for the "Local VM IP Address" would be awesome. Maybe configure the DHCP gateway directly?

**Comment by jtreminio** [comment]
I'm a little out of my depth here, and I want to make sure I get it right.

Can you provide examples and documentation of what you want?

**Comment by Rvanlaak** [comment]
Well, I'd like the VM to get its own IP from the network DHCP server. Currently the only option is appointing a fixed IP, but by using the following configuration the VM will get its own IP.

```
Vagrant.configure("2") do |config|
  config.vm.network "public_network"
end
```
Big advantage of this is that others within the network can also reach the VM directly after that :+1:

**Comment by kanariezwart** [comment]
:+1:

**Comment by jtreminio** [comment]
This was recently added:

https://github.com/puphpet/puphpet/blob/master/archive/puphpet/vagrant/Vagrantfile-local#L16

**Comment by Rvanlaak** [comment]
How does it work in the GUI? The IP address field still is filled by default with `192.168.56.101`. I'd actually expect `use DHCP` as an option over there :+1:
