### ISSUE TITLE
why loads yaml directly in *.pp under nodes directory?

### ISSUE THREAD

**Issue by xjchengo** [puphpet/puphpet#1297]
hello, everyone. i am studying the puphpet source now. i am curious about why to use loadyaml function to get configuration in *.pp under nodes directory when Hiera is used?

**Comment by jtreminio** [comment]
It would be alot easier if I used hiera directly with the puppet modules, but this is impossible with the puphpet tool because of all the extra configuration and checks that need to run to ensure a successful provision.
