### ISSUE TITLE
Apache Alias in config.yaml

### ISSUE THREAD

**Issue by dasper** [puphpet/puphpet#1304]
I am trying to add an Alias and Directory entry into the confic.yaml file but everything seems to be a shot in the dark. I am under the impression it is possible to do because if this in the documentation:

https://github.com/puppetlabs/puppetlabs-apache#aliases

I took a shot in the dark and attempted to add it myself in three different attempts but with no avail. Now I am reaching out to see if there is something I am missing or to see if anyone else has done this before and will save me a bunch of time. 

If there is any other information you need from me, please let me know. Thank you for reading this.

Here is my last attempt:

    vhosts:
        8llolymfltqz:
            servername: api.mysite.com
            serveraliases:
                - api.mysite.com
            docroot: /var/www/code/api/webroot
            port: '80'
            setenv:
                - 'APP_ENV dev'
            directories:
                nmz9jmwkbjj6:
                    provider: directory
                    path: /var/www/code/api/webroot
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - all
                        - granted
                    rewrite_cond:
                        - '%{REQUEST_FILENAME} !-f'
                        - '%{REQUEST_FILENAME} !-d'
                    rewrite_rule: '^(.*)$ index.php/$1 [L]'
                    custom_fragment: ''
            engine: php
            custom_fragment: ''
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
        8lfuaymfltqz:
            servername: local.mysite.com
            serveraliases:
                - local.mysite.com
            docroot: /var/www/code/front/app/webroot
            port: '80'
            setenv:
                - 'APP_ENV dev'
            aliases:
                zzz9jmwkbjj6:
                    alias: /api
                    path: /var/www/code/api/webroot
            directories:
                zzz9jmwkbjj7:
                    provider: directory
                    path: /var/www/code/api/webroot
                    rewrite_cond:
                        - '%{REQUEST_FILENAME} !-f'
                        - '%{REQUEST_FILENAME} !-d'
                    rewrite_rule: '^(.*)$ index.php/$1 [L]'
                nmz9jmwkbjj6:
                    provider: directory
                    path: /var/www/code/front/app/webroot
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - all
                        - granted
                    rewrite_cond:
                        - '%{REQUEST_FILENAME} !-f'
                        - '%{REQUEST_FILENAME} !-d'
                    rewrite_rule: '^(.*)$ index.php/$1 [L]'
                    custom_fragment: ''
            engine: php
            custom_fragment: ''
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''

**Comment by althe3rd** [comment]
Are you creating your config.yaml manually or using the puphpet GUI?  I ask because I believe there is an active issue where any virtual hosts created beyond the first one aren't configured correctly.

When I create two virtual hosts in puphpet and then examine the sites-enabled conf files after doing a vagrant up I notice that the first virtual host conf file is correct but the second one is missing nearly all of its configuration in formation.

If you are generating your config in puphpet I could see this being part of the problem.

**Comment by dasper** [comment]
I was using the GUI. I will try this again later. As of right now I just got everything working directly in puppet but I would like to look at puphpet again in the future and perhaps contribute to it if time permits.

Thank you for your response.

**Comment by steefaan** [comment]
@dasper @althe3rd Where I can place the alias configuration in my `config.yml` file? If I load my current config file on `puphpet.com` I see no option to set an alias.

**Comment by jtreminio** [comment]
@steefaan Please us the `custom_fragment` parameter.

**Comment by tomasdev** [comment]
@jtreminio why is `aliases` not working? I see it uses https://github.com/puppetlabs/puppetlabs-apache.git and that has it working :|

**Comment by tomasdev** [comment]
FYI, the following worked fine for me:

```yaml
vhosts:
        av_7p1v7cbidpbp:
            servername: website.dev
            docroot: /var/www/drupal
            port: '80'
            setenv:
                - 'APP_ENV dev'
            setenvif:
                - 'Authorization "(.*)" HTTP_AUTHORIZATION=$1'
            aliases:
                - alias: /siteAdmin
                  path: /var/www/site/app
```
