### ISSUE TITLE
Vagrant up fails because of nginx error

### ISSUE THREAD

**Issue by kalvisbuls** [puphpet/puphpet#1308]
I'm having trouble getting Vagrant box to run. Every time I use `vagrant up`, it fails with this error message: 

    Warning: Could not retrieve fact fqdn
    Error: /Stage[main]/Nginx::Service/Service[nginx]: Failed to call refresh: Could
     not restart Service[nginx]: Execution of '/etc/init.d/nginx restart' returned 1
    :
    Error: /Stage[main]/Nginx::Service/Service[nginx]: Could not restart Service[ngi
    nx]: Execution of '/etc/init.d/nginx restart' returned 1:`
    
Here's my `config.yaml` file:

    ---
    vagrantfile-local:
        vm:
            box: puphpet/ubuntu1404-x64
            box_url: puphpet/ubuntu1404-x64
            hostname: ''
            memory: '1024'
            cpus: '1'
            chosen_provider: virtualbox
            network:
                private_network: 192.168.56.101
                forwarded_port:
                    jdPbZHEYYl0n:
                        host: '5494'
                        guest: '22'
            post_up_message: ''
            provider:
                virtualbox:
                    modifyvm:
                        natdnshostresolver1: on
                vmware:
                    numvcpus: 1
                parallels:
                    cpus: 1
            provision:
                puppet:
                    manifests_path: puphpet/puppet
                    manifest_file: site.pp
                    module_path: puphpet/puppet/modules
                    options:
                        - '--verbose'
                        - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
                        - '--parser future'
            synced_folder:
                pItCURCzgQrH:
                    owner: www-data
                    group: www-data
                    source: 'g:/Projects/Enlighten'
                    target: /var/www/Enlighten
                    sync_type: default
                    rsync:
                        args:
                            - '--verbose'
                            - '--archive'
                            - '-z'
                        exclude:
                            - .vagrant/
                        auto: 'false'
            usable_port_range:
                start: 10200
                stop: 10500
        ssh:
            host: null
            port: null
            private_key_path: null
            username: vagrant
            guest_port: null
            keep_alive: true
            forward_agent: false
            forward_x11: false
            shell: 'bash -l'
        vagrant:
            host: detect
    server:
        install: '1'
        packages:
            - git
            - git-flow
    users_groups:
        install: '1'
        groups: {  }
        users: {  }
    cron:
        install: '1'
        jobs: {  }
    firewall:
        install: '1'
        rules: null
    apache:
        install: '0'
        settings:
            user: www-data
            group: www-data
            default_vhost: true
            manage_user: false
            manage_group: false
            sendfile: 0
        modules: {  }
        vhosts: {  }
        mod_pagespeed: 0
    nginx:
        install: '1'
        settings:
            default_vhost: 1
            proxy_buffer_size: 128k
            proxy_buffers: '4 256k'
        upstreams: {  }
        vhosts:
            4z7uxxdkitl2:
                proxy: ''
                server_name: enlighten.dev
                www_root: /var/www/Enlighten/public
                listen_port: '443'
                location: \.php$
                index_files:
                    - index.html
                    - index.htm
                    - index.php
                envvars:
                    - 'APP_ENV dev'
                engine: php
                client_max_body_size: 1m
                ssl: '1'
                ssl_cert: ''
                ssl_key: ''
                rewrite_to_https: '1'
                spdy: '1'
    php:
        install: '1'
        version: '56'
        composer: '1'
        composer_home: ''
        modules:
            php:
                - cli
                - intl
                - mcrypt
            pear: {  }
            pecl:
                - pecl_http
        ini:
            display_errors: On
            error_reporting: '-1'
            session.save_path: /var/lib/php/session
        timezone: Europe/Riga
        mod_php: 0
    hhvm:
        install: '0'
        nightly: 0
        composer: '1'
        composer_home: ''
        settings:
            host: 127.0.0.1
            port: '9000'
        ini:
            display_errors: On
            error_reporting: '-1'
        timezone: null
    xdebug:
        install: '1'
        settings:
            xdebug.default_enable: '1'
            xdebug.remote_autostart: '0'
            xdebug.remote_connect_back: '1'
            xdebug.remote_enable: '1'
            xdebug.remote_handler: dbgp
            xdebug.remote_port: '9000'
    xhprof:
        install: '0'
    wpcli:
        install: '0'
        version: v0.17.1
    drush:
        install: '0'
        version: 6.3.0
    ruby:
        install: '1'
        versions:
            h7Ukpm4HUNkT:
                default: '1'
                version: 2.1.2
                gems:
                    - sass
                    - bourbon
                    - neat
                    - bitters
    nodejs:
        install: '1'
        npm_packages:
            - gulp
            - bower
            - phantomjs
    python:
        install: '1'
        packages: {  }
        versions:
            L7PomObCt5u3:
                version: ''
    mysql:
        install: '0'
        override_options: {  }
        root_password: ''
        adminer: 0
        databases: {  }
    postgresql:
        install: '0'
        settings:
            root_password: ''
            user_group: postgres
            encoding: UTF8
            version: '9.3'
        databases: {  }
        adminer: 0
    mariadb:
        install: '1'
        override_options: {  }
        root_password: foobar
        adminer: '1'
        databases:
            JTa3PyBfWsby:
                grant:
                    - ALL
                name: enlighten
                host: localhost
                user: kalvisbuls
                password: foobar
                sql_file: ''
        version: '10.0'
    sqlite:
        install: '1'
        adminer: 0
        databases: {  }
    mongodb:
        install: '0'
        settings:
            auth: 1
            port: '27017'
        databases: {  }
    redis:
        install: '1'
        settings:
            conf_port: '6379'
    mailcatcher:
        install: '1'
        settings:
            smtp_ip: 0.0.0.0
            smtp_port: 1025
            http_ip: 0.0.0.0
            http_port: '1080'
            mailcatcher_path: /usr/local/rvm/wrappers/default
            from_email_method: headers
    beanstalkd:
        install: '1'
        settings:
            listenaddress: 0.0.0.0
            listenport: '13000'
            maxjobsize: '65535'
            maxconnections: '1024'
            binlogdir: /var/lib/beanstalkd/binlog
            binlogfsync: null
            binlogsize: '10485760'
        beanstalk_console: '1'
        binlogdir: /var/lib/beanstalkd/binlog
    rabbitmq:
        install: '0'
        settings:
            port: '5672'
    elastic_search:
        install: '0'
        settings:
            version: 1.4.1
            java_install: true
    solr:
        install: '0'
        settings:
            version: 4.10.2
            port: '8984'

**Comment by ljcl** [comment]
I know this isn't a true solution, but you can usually get it going by running `vagrant provision` again if that error occurs.

**Comment by jtreminio** [comment]
Closing.

Completely refactored how nginx is handled, please try again.
