### ISSUE TITLE
mongodb.conf file sets auth=0/1 instead of auth=true/false

### ISSUE THREAD

**Issue by JoshWhiting** [puphpet/puphpet#1310]
I wasn't able to login with my IDE to the vagrant host mongodb instance after "vagrant up".  After trying various things i noticed the /etc/mongodb.conf file has auth set to 1 instead of false.  It doesn't matter if you try 0 or 1, it always gives you an "unauthorized".  I change it to auth=false and was able to log in just fine.

**Comment by jtreminio** [comment]
Sorry, puphpet doesn't (yet) support that feature, and it sounds like it may be a module issue (puppet-mongodb).
