### ISSUE TITLE
allow installation of blackfire.io

### ISSUE THREAD

**Issue by brpaz** [puphpet/puphpet#1313]
Hi. 
Puphpet already allows you to install xdebug and xhprof. It would be great to be able to install [blackfire.io](https://blackfire.io/) also.

**Comment by notrix** [comment]
:+1:

**Comment by atukai** [comment]
It would be great

**Comment by mimopo** [comment]
:+1:

**Comment by bretrzaun** [comment]
👍

**Comment by JohnByrne** [comment]
+1

**Comment by WolfieZero** [comment]
:+1:

**Comment by aderuwe** [comment]
:+1:

**Comment by bretrzaun** [comment]
Maybe this Puppet module will be helpful for integration of Blackfire.io: https://forge.puppetlabs.com/s12v/blackfire

**Comment by jtreminio** [comment]
@bretrzaun perfect, thanks.
