### ISSUE TITLE
How to start using puphpet?

### ISSUE THREAD

**Issue by eiger3970** [puphpet/puphpet#1314]
Hello, installed puphpet and seemed user friendly to download and install. I'm now in $ vagrant ssh. How do I test my website on this desktop. I can't find any instructions for this. My website is on another server in this same building.

Yes, I read the instructions after the install on Terminal.
Here's the config.yaml contents. All default, no changes made.

---
vagrantfile-local:
    vm:
        box: puphpet/debian75-x64
        box_url: puphpet/debian75-x64
        hostname: ''
        memory: '512'
        cpus: '1'
        chosen_provider: virtualbox
        network:
            private_network: 192.168.56.101
            forwarded_port:
                tdO2JE57zkQE:
                    host: '6912'
                    guest: '22'
        post_up_message: ''
        provider:
            virtualbox:
                modifyvm:
                    natdnshostresolver1: on
            vmware:
                numvcpus: 1
            parallels:
                cpus: 1
        provision:
            puppet:
                manifests_path: puphpet/puppet
                manifest_file: site.pp
                module_path: puphpet/puppet/modules
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
                    - '--parser future'
        synced_folder:
            dvQq2O18H2NA:
                owner: www-data
                group: www-data
                source: ./
                target: /var/www
                sync_type: default
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    exclude:
                        - .vagrant/
                    auto: 'false'
        usable_port_range:
            start: 10200
            stop: 10500
    ssh:
        host: null
        port: null
        private_key_path: null
        username: vagrant
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'
    vagrant:
        host: detect
server:
    install: '1'
    packages: {  }
users_groups:
    install: '1'
    groups: {  }
    users: {  }
cron:
    install: '1'
    jobs: {  }
firewall:
    install: '1'
    rules: null
apache:
    install: '1'
    settings:
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - rewrite
    vhosts:
        gjefxsew2jfx:
            servername: awesome.dev
            serveraliases:
                - www.awesome.dev
            docroot: /var/www/awesome
            port: '80'
            setenv:
                - 'APP_ENV dev'
            directories:
                ewuccgndprob:
                    provider: directory
                    path: /var/www/awesome
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - all
                        - granted
                    custom_fragment: ''
            engine: php
            custom_fragment: ''
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
    mod_pagespeed: 0
nginx:
    install: '0'
    settings:
        default_vhost: 1
        proxy_buffer_size: 128k
        proxy_buffers: '4 256k'
    upstreams: {  }
    vhosts:
        xzhqjytvmwfr:
            proxy: ''
            server_name: awesome.dev
            server_aliases:
                - www.awesome.dev
            www_root: /var/www/awesome
            listen_port: '80'
            location: \.php$
            index_files:
                - index.html
                - index.htm
                - index.php
            envvars:
                - 'APP_ENV dev'
            engine: php
            client_max_body_size: 1m
            ssl_cert: ''
            ssl_key: ''
php:
    install: '1'
    version: '56'
    composer: '1'
    composer_home: ''
    modules:
        php:
            - cli
            - intl
            - mcrypt
        pear: {  }
        pecl:
            - pecl_http
    ini:
        display_errors: On
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
    timezone: America/Chicago
    mod_php: 0
hhvm:
    install: '0'
    nightly: 0
    composer: '1'
    composer_home: ''
    settings:
        host: 127.0.0.1
        port: '9000'
    ini:
        display_errors: On
        error_reporting: '-1'
    timezone: null
xdebug:
    install: '0'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
xhprof:
    install: '0'
wpcli:
    install: '0'
    version: v0.17.1
drush:
    install: '0'
    version: 6.3.0
ruby:
    install: '1'
    versions:
        IZ78ohNyI3Nd:
            version: ''
nodejs:
    install: '0'
    npm_packages: {  }
python:
    install: '1'
    packages: {  }
   versions:
        VQE5TZPz1v07:
            version: ''
mysql:
    install: '1'
    override_options: {  }
    root_password: '123'
    adminer: 0
    databases:
        GU68SLcMUWlP:
            grant:
                - ALL
            name: dbname
            host: localhost
            user: dbuser
            password: '123'
            sql_file: ''
postgresql:
    install: '0'
    settings:
        root_password: '123'
        user_group: postgres
        encoding: UTF8
        version: '9.3'
    databases: {  }
    adminer: 0
mariadb:
    install: '0'
    override_options: {  }
    root_password: '123'
    adminer: 0
    databases: {  }
    version: '10.0'
sqlite:
    install: '0'
    adminer: 0
    databases: {  }
mongodb:
    install: '0'
    settings:
       auth: 1
        port: '27017'
    databases: {  }
redis:
    install: '0'
    settings:
        conf_port: '6379'
mailcatcher:
    install: '0'
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '1080'
        mailcatcher_path: /usr/local/rvm/wrappers/default
        from_email_method: inline
beanstalkd:
    install: '0'
    settings:
        listenaddress: 0.0.0.0
        listenport: '13000'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: 0
    binlogdir: /var/lib/beanstalkd/binlog
rabbitmq:
    install: '0'
    settings:
        port: '5672'
elastic_search:
    install: '0'
    settings:
        version: 1.4.1
        java_install: true
solr:
    install: '0'
    settings:
        version: 4.10.2
        port: '8984'

**Comment by jtreminio** [comment]
> My website is on another server in this same building.

The purpose of a VM is to have what you need inside the VM, not in another server.

You should probably start by cloning the project inside your VM.

**Comment by eiger3970** [comment]
Thank you. 
I just 'googled' how to clone a project inside a vm and no useful results: https://www.google.com.au/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=how%20to%20clone%20project%20inside%20vm

My website is live, so my understanding is I know have to copy all website files over to some VM which I have no idea where it is.
Are there any instructions on www.puphpet.com to walkthrough this part of the setup?

**Comment by eiger3970** [comment]
So, just tried all this from some instructions found on Vagrant, but still not working.

linuxmint@linuxmint ~/Downloads/WHWWQu/puphpet $ vim config.yaml
linuxmint@linuxmint ~/Downloads/WHWWQu/puphpet $ mkdir vagrant_getting_started
linuxmint@linuxmint ~/Downloads/WHWWQu/puphpet $ cd vagrant_getting_started/
linuxmint@linuxmint ~/Downloads/WHWWQu/puphpet/vagrant_getting_started $ vagrant init
A `Vagrantfile` has been placed in this directory. You are now
ready to `vagrant up` your first virtual environment! Please read
the comments in the Vagrantfile as well as documentation on
`vagrantup.com` for more information on using Vagrant.
linuxmint@linuxmint ~/Downloads/WHWWQu/puphpet/vagrant_getting_started $ vagrant box add hashicorp/precise32
==> box: Loading metadata for box 'hashicorp/precise32'
    box: URL: https://atlas.hashicorp.com/hashicorp/precise32
==> box: Adding box 'hashicorp/precise32' (v1.0.0) for provider: virtualbox
    box: Downloading: https://atlas.hashicorp.com/hashicorp/boxes/precise32/versions/1.0.0/providers/virtualbox.box
==> box: Successfully added box 'hashicorp/precise32' (v1.0.0) for 'virtualbox'!
linuxmint@linuxmint ~/Downloads/WHWWQu/puphpet/vagrant_getting_started $ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'base' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Adding box 'base' (v0) for provider: virtualbox
    default: Downloading: base
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

Couldn't open file /home/linuxmint/Downloads/WHWWQu/puphpet/vagrant_getting_started/base
linuxmint@linuxmint ~/Downloads/WHWWQu/puphpet/vagrant_getting_started $ vagrant ssh
VM must be created before running this command. Run `vagrant up` first.
linuxmint@linuxmint ~/Downloads/WHWWQu/puphpet/vagrant_getting_started $ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'base' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Adding box 'base' (v0) for provider: virtualbox
    default: Downloading: base
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

Couldn't open file /home/linuxmint/Downloads/WHWWQu/puphpet/vagrant_getting_started/base

**Comment by eiger3970** [comment]
Well I received the next error:

NewYoursAPIHelp
1.5 KB, Plain text     Soft wrap Raw text Duplicate Delete Change expiry
 1
 2
 3
 4
 5
 6
 7
 8
 9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
linuxmint Puppet # vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'puphpet/debian75-x64' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Loading metadata for box 'puphpet/debian75-x64'
    default: URL: https://atlas.hashicorp.com/puphpet/debian75-x64
==> default: Adding box 'puphpet/debian75-x64' (v1.2) for provider: virtualbox
    default: Downloading: https://atlas.hashicorp.com/puphpet/boxes/debian75-x64/versions/1.2/providers/virtualbox.box
==> default: Successfully added box 'puphpet/debian75-x64' (v1.2) for 'virtualbox'!
==> default: Importing base box 'puphpet/debian75-x64'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'puphpet/debian75-x64' is up to date...
==> default: Setting the name of the VM: Puppet_default_1421036232428_71144
Vagrant cannot forward the specified ports on this VM, since they
would collide with some other application that is already listening
on these ports. The forwarded port to 6912 is already in use
on the host machine.

To fix this, modify your current projects Vagrantfile to use another
port. Example, where '1234' would be replaced by a unique host port:

  config.vm.network :forwarded_port, guest: 22, host: 1234

Sometimes, Vagrant will attempt to auto-correct this for you. In this
case, Vagrant was unable to. This is usually because the guest machine
is in a state which doesn't allow modifying port forwarding.
Pasted now — Expires in 7 days
About dpaste.com

**Comment by eiger3970** [comment]
I tried: linuxmint Puppet # grep config.vm.network, but computer does nothing?

**Comment by eiger3970** [comment]
I tried in browser: awesome.dev, but error: File not found. I have copied all my live website files to /Downloads/Puppet/awesome. What else do I need to do to make puppet work?

**Comment by eiger3970** [comment]
So, how do I run my live website on the local Desktop using this Vagrant/Puphpet thing? I copied the live website to ~/Downloads/Puppet/awesome. I go to /awesome and in Termianl run $ vagrant up, then in browser aswesome.dev, but error: File not found?

**Comment by eiger3970** [comment]
Can't find an English tutorial on puphpet or vagrant?

**Comment by beporter** [comment]
It sounds like there are a lot of concepts you need to learn about here. You may have better luck finding people to help you through all of this on [the puphpet IRC channel](https://kiwiirc.com/client/chat.freenode.net/#puphpet). This issue tracker probably isn't the best place for this kind of support request.

**Comment by jtreminio** [comment]
You should read this https://jtreminio.com/2013/05/introduction_to_vagrant_puppet_and_introducing_puphpet_a_simple_to_use_vagrant_puppet_gui_configurator/

Then this https://jtreminio.com/2013/06/make_vagrant_up_yours/

As @beporter mentioned this issue tracker isn't the best place to learn the basic concepts.

The VM should be considered a completely separate machine that just so happens to share some folders with the host and some resources, but you should think of it as just another box in another room.
