### ISSUE TITLE
How to add nginx modules to hiera manifest?

### ISSUE THREAD

**Issue by tonymontana** [puphpet/puphpet#1315]
I need to install Nginx with some modules on my virtual machine (Debian 7 x64). I use Vagrant and one recipe from Puphpet. By default in puphpet/config.yaml I have nginx section:

nginx:
    install: '1'
    settings:
        default_vhost: 1
        proxy_buffer_size: 128k
        proxy_buffers: '4 256k'
    upstreams: { }
    vhosts:
       ....

I need Nginx image_filter ans xslt modules, so where could I place the correspond information in this config?

**Comment by jtreminio** [comment]
As far as I know, if you want to add modules to Nginx you need to compile it with the modules enabled.

Sorry, this is out of scope of puphpet - maybe try throwing it into an exec-once?
