### ISSUE TITLE
Install PHPUnit

### ISSUE THREAD

**Issue by ctaylo21** [puphpet/puphpet#1317]
I don't see a place to include PHPUnit as a module in Puphpet. Is there a way to do this so it's globally available on the guest machine after vagrant up? I have composer installed so I can ssh into the machine and run this command to install:
```
composer global require "phpunit/phpunit=4.4.*"
export PATH=$PATH:~/.composer/vendor/bin/
```

If it's not available as a module what would be the best way to run that command somewhere during provisioning?

**Comment by rlweb** [comment]
Have you tried placing the script above in the run-once folder?

**Comment by jtreminio** [comment]
Since phpunit is being removed from pear, the best solution to this would be creating a simple run-once script.
