### ISSUE TITLE
Customized php.ini settings not used on CLI

### ISSUE THREAD

**Issue by weyandch** [puphpet/puphpet#1323]
I've ran into a problem, where my functional tests require a higher xdebug.max_nesting_level value than the default 100 in xdebug.ini.
All the customizations in config.yaml won't be loaded by CLI, just the server (nginx) loades them. 

Any hint how to solve this in a best-practice style? Command to create a symbolic link on first start of the box?

**Comment by jtreminio** [comment]
AFAIK they all share the same directory.

Can you paste your config.yaml?
