### ISSUE TITLE
Alter MySQL configuration

### ISSUE THREAD

**Issue by NeilANand** [puphpet/puphpet#1326]
Hello,

I was wondering how would I make alterations to the MySQL configuration file? I need to increase the execution time and some of the resource limits but I'm not sure how to do it with Puppet.

Thanks for any help,
Neil.

**Comment by rodsouto** [comment]
you can use override_options, see https://github.com/puphpet/puphpet/pull/1153 :)

**Comment by NeilANand** [comment]
Sounds like awesome stuff! Thanks for the link, I'll give it ago tomorrow.

**Comment by NeilANand** [comment]
Awesome, it's working great for me!
