### ISSUE TITLE
Deploy to Any cloud server

### ISSUE THREAD

**Issue by pjebs** [puphpet/puphpet#1328]
I've been using Puphpet to create my local virtual machine with my customisations.
How would I now upload my customisations onto any cloud server instance (i.e. Vultr - which is like digital ocean but slightly cheaper)?

Or am I missing what vagrant is for. Is vagrant ONLY for creating virtual machines (which ideally should match the cloud server you wish to use as opposed to making the cloud server instance match the virtual machine (even if possible to do so)) If later is the case, then I don't quite undestand how AWS, GCP, Linode etc is supported by Puphet out of the box.

**Comment by jtreminio** [comment]
You can use this plugin: https://github.com/tknerr/vagrant-managed-servers

**Comment by pjebs** [comment]
if there is no plug-in for vultr, does that mean i can't use use Vagrant with it?

Also, what is the advantage of using vagrant with cloud server providers? I thought it was only for creating local virtual machines.
