### ISSUE TITLE
Support for ubuntu/trusty64

### ISSUE THREAD

**Issue by eberon** [puphpet/puphpet#1329]
Is there a compelling reason for using the base box the configurator wants to use? Is it just some pre-installed dependencies?

Things seem fine using ubuntu/trusty64 and I'd rather just save the disk space on my SSD.

**Comment by jtreminio** [comment]
The puphpet boxes come with a bunch of things preinstalled, you can see everything here: https://github.com/puphpet/packer-templates/tree/master/ubuntu-14.04-x86_64

If you're constantly spinning up and destroying VMs, then it's worth the disk space to use them. If you're certain you won't be doing it repeatedly, sure, you can use vanilla boxes.
