### ISSUE TITLE
Error: Unknown function loadyaml at /tmp/vagrant-puppet-3/manifests/nodes/Apache.pp:1

### ISSUE THREAD

**Issue by HMAZonderland** [puphpet/puphpet#1330]
Loaded an old configuration into the browser. Made some changes. Typed `vagrant up`. Processed the booting/setup process and when trying to execute the manifest it came up with this error:

``` cmd
Error: Unknown function loadyaml at /tmp/vagrant-puppet-3/manifests/nodes/Apache.pp:1 on node
```

After this error occurred and I was set back to the command line I typed `vagrant provision` which does seem to work.

**Comment by jpswade** [comment]
Also able to replicate this error.

```
==> default: Error: Unknown function loadyaml at /tmp/vagrant-puppet/manifests-8
93fcda21077f5a583c2dbbba8515c0a/nodes/Apache.pp:1 on node localhost
==> default: Error: Unknown function loadyaml at /tmp/vagrant-puppet/manifests-8
93fcda21077f5a583c2dbbba8515c0a/nodes/Apache.pp:1 on node localhost
```

**Comment by enkay83** [comment]
Hey there,

have the same issue. Does someone have a solution?

**Comment by jtreminio** [comment]
Hi all,

Can you guys try with a fresh archive? Sounds like you may be copying from a new archive into an old, existing one.

`loadyaml` comes with the puppet-stdlib library which is included in the `puphpet/puppet/modules` directory.

**Comment by enkay83** [comment]
Hi @jtreminio,

i try it out with a fresh one and this did the trick for me.

Thank you!
