### ISSUE TITLE
GeoIP functionality missing when installed as PECL module "geoip"

### ISSUE THREAD

**Issue by ph55** [puphpet/puphpet#1332]
Related to closed: https://github.com/puphpet/puphpet/issues/877

After installing geoip as PECL module only following files included:

```
[/usr/share/GeoIP] 
-rw-r--r-- 1 root root 827301 Apr 7 2014 GeoIP.dat
-rw-r--r-- 1 root root 3105495 Apr 7 2014 GeoIPv6.dat
```

GeoIPCity.dat missing.

As result there is some functions that are missing and leads errors:

```
geoip_record_by_name(): Required database not available at /usr/share/GeoIP/GeoIPCity.dat
```

**Comment by jtreminio** [comment]
Hi!

Closing this for same reason as last issue. This isn't a puphpet problem. The extension is installed using the `pecl` command. Solution in other ticket is installing module from source, not pecl. You may have to go that route.
