### ISSUE TITLE
Setting apache environmental variables

### ISSUE THREAD

**Issue by NeilANand** [puphpet/puphpet#1336]
Hello,

Thanks for all the great work on this project, I've got it working and have been using it for a short while and think this is amazing!

I do have a question though, for a site I'm currently working on I need to set some environmental variables in Apache which are read by PHP. Currently I've had to SSH into the vagrant box then add them to /etc/apache2/envvars & /etc/apache2/apache2.conf manually but adding to a file so it's all setup during the provisioning would be great.

Thanks for any help,
Neil.

**Comment by jtreminio** [comment]
You want Environment Variables field:

![image](https://cloud.githubusercontent.com/assets/589398/5867274/8257de96-a25f-11e4-959e-b95289471413.png)

**Comment by NeilANand** [comment]
Thanks! I feel like a fool for missing that.
