### ISSUE TITLE
Nginx multiple locations on the same host

### ISSUE THREAD

**Issue by mkroeders** [puphpet/puphpet#1338]
Hello I am trying to achieve the following nginx host config;

    location ~ ^/data/.* {
     root  /var/www/data/public;
     try_files $uri $uri/ /index.php /index.php$is_args$args$is_args$args;
     index  index.html index.htm index.php;
     fastcgi_index index.php;
     fastcgi_param SCRIPT_FILENAME $request_filename;
     fastcgi_pass 127.0.0.1:9000;
     fastcgi_split_path_info ^(.+\.php)(/.*)$;
     include fastcgi_params;
    }

    location ~ ^/accounts/.* {
     root  /var/www/accounts/public;
     try_files $uri $uri/ /index.php /index.php$is_args$args$is_args$args;
     index  index.html index.htm index.php;
     fastcgi_index index.php;
     fastcgi_param SCRIPT_FILENAME $request_filename;
     fastcgi_pass 127.0.0.1:9000;
     fastcgi_split_path_info ^(.+\.php)(/.*)$;
     include fastcgi_params;
    }

I have figured out how to create a single location, using

    4cdockrhw9wx:
            proxy: ''
            server_name: domain.dev
            www_root: /var/www/accounts/public
            listen_port: '80'
            location: ^/accounts/.*
            index_files:
                - index.php
            engine: php
            client_max_body_size: 1m
            ssl: '1'
            ssl_cert: ''
            ssl_key: ''
            rewrite_to_https: '1'

But when I add a second one

    bgjczmn5lyj9:
            proxy: ''
            server_name: api.wugly.dev
            www_root: /var/www/data/public
            listen_port: '80'
            location: ^/data/.*
            index_files:
                - index.php
            engine: php
            client_max_body_size: 1m
            ssl: '1'
            ssl_cert: ''
            ssl_key: ''
            rewrite_to_https: '1'

I get the following error;

    Error: Duplicate declaration: Nginx::Resource::Vhost[domain.dev] is already declared in file /tmp/vagrant-puppet-3/manifests/nodes/Nginx.pp:231; cannot redeclare at /tmp/vagrant-puppet-3/manifests/nodes/Nginx.pp:231 on node packer-virtualbox-iso.vagrantup.com
    Error: Duplicate declaration: Nginx::Resource::Vhost[domain.dev] is already declared in file /tmp/vagrant-puppet-3/manifests/nodes/Nginx.pp:231; cannot redeclare at /tmp/vagrant-puppet-3/manifests/nodes/Nginx.pp:231 on node packer-virtualbox-iso.vagrantup.com

So is there a way to declare multiple locations, with different routs?

**Comment by jtreminio** [comment]
Fixed by 8d695f1c2bd4dc4440648a0a0e493a80c562db82
