### ISSUE TITLE
"Local VM CPU's" option

### ISSUE THREAD

**Issue by Mark-L6n** [puphpet/puphpet#1339]
I'd like to provide/get some help on choosing a number for the "Local VM CPU's" option. Below I'll list info I've found from web searches.  Please clarify or correct any information needed!
1)  The number of "Local VM CPU's" is the number of CPUs on your physical machine that you are allowing the virtual machine to use.
2) The CPUs refer to physical CPUs (or # cores), not logical CPUs (or # of threads).  For example, a 2.5 ghz intel core i7 chip has 4 physical CPUs (cores) and 8 logical CPUs (threads).  At least on Mac, you can find these values on the command line with:  `sysctl hw.physicalcpu` or `sysctl hw.logicalcpu`.  Of course you can just perform a search for your chip specifications, too.
3) How many of your CPUs can/should you allot?  There seems to be a little confusion on this, but it appears that this setting is the # of CPUs *available* to the VM, but *only used when needed*.  The best explanations I found are [here](http://superuser.com/questions/297697/are-there-any-real-advantages-to-assigning-more-cores-to-virtualbox#answer-297727) and [in VMWare docs](https://pubs.vmware.com/fusion-7/index.jsp?topic=%2Fcom.vmware.fusion.help.doc%2FGUID-4EABCE73-69AB-4665-A5BB-B34C5B736CC7.html).  Generally:
* Don't allocate all CPUs.  The Virtualbox forums often mention a rule-of-thumb of a max limit of all but one processor.  The VMWare link above explains that at least one processor should be left to process host OS tasks.
* Look at the type and importance of apps in your virtual box.  The VMWare link above suggests: 1 processor for desktop applications, 2 for server operating systems, and 4 for video encoding, modeling, and scientific programs

**Comment by jtreminio** [comment]
Sorry, I don't believe this is a proper question for puphpet. Maybe ask in Vagrant's github tracker?
