### ISSUE TITLE
Mariadb not installed on ubuntu 14.04

### ISSUE THREAD

**Issue by Ekstazi** [puphpet/puphpet#1341]
On ubuntu 14.0 both 10.0 and 5.5 version of Mariadb not installed with error:
`/Stage[main]/Puphpet::Mariadb/Apt::Source[mariadb]/Exec[Required packages: 'debian-keyring debian-archive-keyring' for mariadb]: Failed to call refresh: Command exceeded timeout`
But then i try to run vagrant provision after vagrant up it installed succesfully. Seems to be a bug.

**Comment by jtreminio** [comment]
Sometimes repo servers don't respond in time, or your connection drops. This is what happened in this case. Just try again, not a puphpet bug.

**Comment by Ekstazi** [comment]
This error always happen then i provision my box first time. On second time
provision proccess runs without errors

2015-02-18 23:14 GMT+02:00 Juan Treminio <notifications@github.com>:
