### ISSUE TITLE
Add warning for PHP 5.6 on Ubuntu 12.04

### ISSUE THREAD

**Issue by robojamison** [puphpet/puphpet#1346]
After struggling greatly with getting PuPHPet to work on a Ubuntu 12.04 x64 box with PHP 5.6 and having no luck, I finally learned that Ubuntu 12.04 x64 does not support PHP 5.6 (see the last comment of [this thread](https://github.com/puphpet/puphpet/issues/1240) by jtreminio). Using a PuPHPet-generated config with Ubuntu 12.04 x64 and PHP 5.5 or lower works like a charm.

If possible, it would be nice to have a warning in PuPHPet to let the user know that the box they selected (if Ubuntu 12.04 x64) does not support the language they chose (PHP 5.6) since this is not commonly-known information or to have the PHP 5.6 option greyed out on the Languages tab if that particular box is selected.

**Comment by jtreminio** [comment]
There is a warning, though:

![image](https://cloud.githubusercontent.com/assets/589398/5986732/01b4192a-a8cd-11e4-88b0-e841d4679120.png)

**Comment by robojamison** [comment]
Oh, okay. Hmm. I guess that is sort of a warning...but it seems more like a passive warning than an active warning. I would recommend/request that 5.6 have some red text next to it or something on the Languages page, or perhaps be hidden/disabled altogether. Then it's much more obvious that it's something to avoid, at least for now.

Still, since your fix technically fixes the problem, I'll close the issue. Thanks.
