### ISSUE TITLE
How/where to put a drush alias file

### ISSUE THREAD

**Issue by dvanactka** [puphpet/puphpet#1351]
After checking the box for drush, it installed just fine.  However, I need to create an alias file, and can't figure out how/where to place it so that drush can find it.  Places that `aliases.drushrc.php` could go are:
* the drush installation folder  (here, `/usr/share/drush` )
* `/etc/drush`
* `$HOME/.drush` (here, `/home/vagrant/.drush` )
* a path set in the file `drushrc.php`, which would be in one of the above 3 locations

However, none of those locations are accessible through the synced folder, as far as I can tell.
It is possible to use a command-line argument to get around this, e.g.:
   `drush --alias-path=/var/www/[path] @alias status`  
However, I'd rather not have to type in that argument.  Any advice on where to place `aliases.drushrc.php` so that it would automatically be recognized?

**Comment by morsok** [comment]
Under `puphpet/files/dot` create a `.drush` folder with an `aliases.drushrc.php` file in it. It should automaticly be copied to `/home/vagrant/.drush`

**Comment by jtreminio** [comment]
Edit the included `.bash_aliases` with your changes, or create an `exec-once` file to copy the php file to a bin directory.
