### ISSUE TITLE
Where do I put additions, and what is the syntax?

### ISSUE THREAD

**Issue by OsakaWebbie** [puphpet/puphpet#1352]
The instructions that appear at the end of "vagrant up" say that I should edit `config.yaml`, but https://puphpet.com/help says I should edit `puppet/hieradata/common.yaml`, which doesn't even exist. As for `config.yaml`, I have been looking around for examples of how to do the syntax (for example, to add a package). There are lots of examples on the web of Puppet syntax, but config.yaml appears to be completely different, and I haven't found any tutorials yet that resemble it.

For example, I would like to add Phalcon, and https://github.com/phalcon/puppet gives example usage, but its curly-brace syntax looks nothing like the colons of `config.yaml`. I know this is probably a dumb question, but can someone enlighten me as to how I would add something like this?

As you require, here is my config.yaml:
```---
vagrantfile-local:
    vm:
        box: puphpet/centos65-x64
        box_url: puphpet/centos65-x64
        hostname: ''
        memory: '512'
        cpus: '1'
        chosen_provider: virtualbox
        network:
            private_network: 192.168.56.102
            forwarded_port:
                j4SJKvkVKudW:
                    host: '8081'
                    guest: '80'
        post_up_message: ''
        provider:
            virtualbox:
                modifyvm:
                    natdnshostresolver1: on
            vmware:
                numvcpus: 1
            parallels:
                cpus: 1
        provision:
            puppet:
                manifests_path: puphpet/puppet
                manifest_file: site.pp
                module_path: puphpet/puppet/modules
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
                    - '--parser future'
        synced_folder:
            zEyRZyFvzCFu:
                owner: ''
                group: ''
                source: 'c:/dev/webroot'
                target: /var/www
                sync_type: default
                rsync:
                    auto: 'false'
        usable_port_range:
            start: 10200
            stop: 10500
    ssh:
        host: null
        port: null
        private_key_path: null
        username: vagrant
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'
    vagrant:
        host: detect
server:
    install: '1'
    packages:
        - vim-common
        - postfix
        - dovecot
users_groups:
    install: '1'
    groups: {  }
    users: {  }
cron:
    install: '1'
    jobs: {  }
firewall:
    install: '1'
    rules: null
apache:
    install: '0'
    settings:
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules: {  }
    vhosts: {  }
    mod_pagespeed: 0
nginx:
    install: '1'
    settings:
        default_vhost: 1
        proxy_buffer_size: 128k
        proxy_buffers: '4 256k'
    upstreams: {  }
    vhosts:
        ovbvfftcbjik:
            proxy: ''
            server_name: '*.kizunadb.dev'
            www_root: /var/www/kizunadb/codebase
            listen_port: '80'
            location: .php$
            index_files:
                - index.php
                - index.html
                - index.htm
            envvars:
                - 'APP_ENV dev'
            engine: ''
            client_max_body_size: 1m
            ssl_cert: ''
            ssl_key: ''
        hj4g788eqbuv:
            proxy: ''
            server_name: l4jp.dev
            www_root: /var/www/l4jp
            listen_port: '80'
            location: .php$
            index_files:
                - index.html
                - index.htm
                - index.php
            engine: ''
            client_max_body_size: 1m
            ssl_cert: ''
            ssl_key: ''
php:
    install: '0'
    version: '55'
    composer: '1'
    composer_home: ''
    modules:
        php:
            - cli
            - gd
            - intl
            - mbstring
            - mcrypt
        pear: {  }
        pecl:
            - pecl_http
    ini:
        display_errors: On
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
    timezone: Asia/Tokyo
    mod_php: 0
hhvm:
    install: '0'
    nightly: 0
    composer: '1'
    composer_home: ''
    settings:
        host: '0'
        port: '0'
    ini: {  }
    timezone: null
xdebug:
    install: '1'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
xhprof:
    install: '0'
wpcli:
    install: '0'
    version: ''
drush:
    install: '0'
    version: ''
ruby:
    install: '1'
    versions: {  }
nodejs:
    install: '0'
    npm_packages: {  }
python:
    install: '1'
    packages: {  }
    versions: {  }
mysql:
    install: '1'
    override_options: {  }
    root_password: '#1PhalconServer!'
    adminer: 0
    databases:
        WR3kFrkYBxgQ:
            grant:
                - DELETE
                - INSERT
                - SELECT
                - UPDATE
            name: kizuna_dev
            host: localhost
            user: dev
            password: '#1PhalconServer!'
            sql_file: ''
postgresql:
    install: '0'
    settings:
        root_password: '123'
        user_group: postgres
        encoding: UTF8
        version: '9.3'
    databases: {  }
    adminer: 0
mariadb:
    install: '0'
    override_options: {  }
    root_password: '123'
    adminer: 0
    databases: {  }
sqlite:
    install: '0'
    adminer: 0
    databases: {  }
mongodb:
    install: '0'
    settings:
        auth: 1
        port: '27017'
    databases: {  }
redis:
    install: '0'
    settings:
        conf_port: '6379'
mailcatcher:
    install: '0'
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '1080'
        mailcatcher_path: /usr/local/rvm/wrappers/default
        from_email_method: inline
beanstalkd:
    install: '0'
    settings:
        listenaddress: 0.0.0.0
        listenport: '13000'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: 0
    binlogdir: /var/lib/beanstalkd/binlog
rabbitmq:
    install: '0'
    settings:
        port: '5672'
elastic_search:
    install: '0'
    settings:
        version: ''
        java_install: true
solr:
    install: '0'
    settings:
        version: ''
        port: ''```

**Comment by OsakaWebbie** [comment]
Okay, while waiting for a reply, I've figured out that the Puppet manifest files that have examples and tutorials all over the web are in Ruby syntax, while `config.yaml` is in YAML (duh!). But I still can't find any examples at all of what one would put in `config.yaml` to add more packages. I tried adding the following to the end of the file, choosing a really simple one first before tackling more complex ones like Phalcon:

    tree:
        install: '1'

Then I did `vagrant up` and `vagrant provision`. Tree did not appear, and I didn't notice any new messages (like "hey, you asked me to install tree, but I can't do it because...").

**Comment by jtreminio** [comment]
The config file is strictly for configuring Puppet code that already exists, you can't create new sections and have it take effect until you sit down and write Puppet code.

**Comment by OsakaWebbie** [comment]
Closed? I was in the middle of writing my next post gradually, while trying various things and making notes of the results. Sorry I'm so slow - it takes me a long time to research and experiment enough that I feel that I can ask more here. (And of course I can't work on this full-time.) Can I continue?

**Comment by jtreminio** [comment]
@OsakaWebbie I'm sorry, but puphpet isn't the place to actually learn Puppet. If it doesn't involve the GUI or the existing code, I can offer simple tips like above but would prefer my extremely large issue tracker not be full of non-puphpet related issues - there's enough on my plate as is!

A simple rundown:

1. Vagrant spins up a VM using the Vagrantfile and some of the values from config.yaml,
2. Vagrant hands control to Puppet,
3. Puppet runs through all the code in puphpet/puppet/nodes, using the values from config.yaml,
4. Control is handed back to Vagrant which executes .sh files

You want to step into number 3.

**Comment by OsakaWebbie** [comment]
I wasn't trying to ask you Puppet questions per se, but about the PuPHPet structure. PuPHPet generates what seems to me a labyrinth of files (compared to the simplistic examples in Puppet tutorials), and I don't know which files are the best to modify so that if I ever drag my config.yaml file onto your GUI and create a newer labyrinth, I can most easily re-integrate my customizations into the new one. (And I guess it was also feedback about a problem with your Help page, which tells users to customize a Hiera file that doesn't exist.)

From my newbie point of view, I see six places to customize:

1. puphpet/puppet/nodes - this is where I successfully added a file for tree.
1. puphpet/puppet/modules - this is where I tried to put the contents of https://github.com/andschwa/puppet-latex, but that is either not enough or not the right method.
1. puphpet/shell - this is where I added the two files from https://github.com/slogsdon/vagrant-phalcon/tree/master/provision/shell (I haven't done any more work on Phalcon setup because of a bigger issue - see below).
1. puphpet/files - all I've done in this area is add a favorite .bashrc to puphpet/files/dot/, but I get the feeling that the other four subdirectories here will be useful somehow. But I have no examples to know what is supposed to go where.
1. Vagrantfile - this is the place where a variety of webpages say to put things, but that doesn't sound right to me, because I want the same stuff on my production server someday, which will not be started with Vagrant.
1. Puppetfile - I added a couple lines here for puppet-latex (to get it straight from github), but all it seems to do is download it to /tmp/vagrant-puppet/ and unpack it.

Now for the bigger issue I mentioned - while trying to set up Phalcon, I figured out that PHP doesn't appear to be running! I thought I must have done something to mess it up, but just now I unpacked the ZIP file to a fresh directory, changed only the IP address and port (so things wouldn't conflict), and did `vagrant up`. Same problem. Nginx just serves PHP files unprocessed, as if they were something to be downloaded. Am I missing some critical step?

**Comment by OsakaWebbie** [comment]
Sorry, I probably should have started a separate ticket for the PHP issue - I think it got missed in the midst of way too much verbage. I'll do that now.

**Comment by jtreminio** [comment]
1. Yes, `puphpet/puppet/nodes` is where all Puppet code should reside.
2. `puphpet/puppet/modules` is where all 3rd party modules should be. I'm not sure what, if anything, happened with puppet-latex. All I can say is be sure the folder is named as `latex` within the `puphpet/puppet/modules` - it should not be `puppet-latex`
3. `puphpet/shell` is mostly for internal use.  You can see how scripts in that directory are called from a `Vagrantfile` [here] (https://github.com/puphpet/puphpet/blob/master/src/Puphpet/Extension/VagrantfileLocalBundle/Resources/views/Vagrantfile.rb.twig#L200). Unless you manually add lines to your `Vagrantfile` calling your custom shell script, nothing will be done with it. 
4. `puphpet/files` *is* where you must add custom bash files that you want to run automatically, without having to edit the `Vagrantfile`, per the documentation here: 
[here](https://cloud.githubusercontent.com/assets/589398/6397463/7463910c-bdaa-11e4-9ee8-5d34a1afd7f6.png)
5. `Vagrantfile` can be edited as other blogs may say, but if you do then you'll need to re-edit it every time you updated your puphpet archive. I've tried to make puphpet as extensible as possible so that you don't actually have to edit it. If you want to run custom shell scripts, refer to 4 above; If you want to do something else with Vagrant itself, then this is the proper place - although I've tried to cover as many potential scenarios as possible.
6. `Puppetfile` is not called by puphpet, actually. It used to be, but then I started seeing problems with timeouts that would upset users, so I went with including everything into the generated zip archive. `Puppetfile` *is* useful if you a) Don't want to include all the modules inside `puphpet/puppet/modules` in your, and b) You have `librarian-puppet` installed on your build system. Otherwise, part of Vagrant's process is copying everything from the local Vagrant directory to the target VM.

Your missing critical step is probably related to 3/4 above.
