### ISSUE TITLE
Too many errors on vagrant up (No such file or directory?)

### ISSUE THREAD

**Issue by dbd5** [puphpet/puphpet#1363]
ENVIRONMENT
=============
MAC OS X 10.9.5
Virtual Machine Software - Parallels Desktop 10.1.2

ACTION
======
Configured settings for Vagrant on https://puphpet.com/, extracted zip file and ran Vagrant up from Terminal

ERROR OUTPUT
==============
mac-4a70:vagrant_root Amak$ vagrant up
/opt/vagrant/bin/../embedded/gems/gems/vagrant-1.7.2/lib/vagrant/pre-rubygems.rb:31: warning: Insecure world writable dir /usr in PATH, mode 040777
/opt/vagrant/embedded/gems/gems/bundler-1.7.11/lib/bundler/runtime.rb:222: warning: Insecure world writable dir /usr in PATH, mode 040777
Bringing machine 'default' up with 'parallels' provider...
==> default: Importing base box 'puphpet/ubuntu1404-x32'...
==> default: Checking if box 'puphpet/ubuntu1404-x32' is up to date...
==> default: Setting the name of the VM: vagrant_parallels_default_1423324769664_41461
==> default: Preparing network interfaces based on configuration...
    default: Adapter 0: shared
    default: Adapter 1: hostonly
==> default: Clearing any previously set network interfaces...
==> default: Forwarding ports...
    default: 22 => 7373
==> default: Setting power consumption mode: "Longer battery life"
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 10.211.55.13:22
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Connection refused. Retrying...
    default: 
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default: 
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if its present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
==> default: Machine booted and ready!
==> default: Checking for Parallels Tools installed on the VM...
==> default: Parallels Tools installed on this VM are outdated! In most cases
==> default: this is fine but in rare cases it can cause things such as shared
==> default: folders to not work properly. If you see shared folder errors,
==> default: please update Parallels Tools within the virtual machine and 
==> default: reload your VM.
==> default: Configuring and enabling network interfaces...
==> default: Installing NFS client...
==> default: Exporting NFS shared folders...
==> default: Preparing to edit /etc/exports. Administrator privileges will be required...
Password:
==> default: Mounting NFS shared folders...
==> default: Mounting shared folders...
    default: /vagrant => /Users/Amak/vagrant_parallels
    default: /tmp/vagrant-puppet/modules-407b6ea604644653f113f9909de16417 => /Users/Amak/vagrant_parallels/puphpet/puppet/modules
    default: /tmp/vagrant-puppet/manifests-893fcda21077f5a583c2dbbba8515c0a => /Users/Amak/vagrant_parallels/puphpet/puppet
==> default: Creating bind mounts for selected devices
==> default: Creating bind mount from /mnt/vagrant-8SorzLID2nNj to /var/www
==> default: Running provisioner: shell...
    default: Running: /var/folders/ph/pw3mw1mn4rd1m3ry_j1j9r640000gn/T/vagrant-shell20150207-16165-14bnox4.sh
==> default: stdin: is not a tty
==> default: /bin/bash: /vagrant/puphpet/shell/os-detect.sh: No such file or directory
==> default: /bin/bash: /vagrant/puphpet/shell/os-detect.sh: No such file or directory
==> default: /bin/bash: /vagrant/puphpet/shell/os-detect.sh: No such file or directory
==> default: cat: /vagrant/puphpet/shell/ascii-art/self-promotion.txt
==> default: : No such file or directory
==> default: 
==> default: Running provisioner: shell...
    default: Running: /var/folders/ph/pw3mw1mn4rd1m3ry_j1j9r640000gn/T/vagrant-shell20150207-16165-1t5a08p.sh
==> default: stdin: is not a tty
==> default: /bin/bash: /vagrant/puphpet/shell/os-detect.sh: No such file or directory
==> default: open /vagrant/puphpet/files/dot/ssh/root_id_rsa failed: No such file or directory.
==> default: Generating public/private rsa key pair.
==> default: Saving the key failed: /vagrant/puphpet/files/dot/ssh/root_id_rsa.
==> default: /tmp/vagrant-shell: line 22: puttygen: command not found
==> default: Your private key for SSH-based authentication has been saved to 'puphpet/files/dot/ssh/root_id_rsa'!
==> default: open /vagrant/puphpet/files/dot/ssh/id_rsa failed: No such file or directory.
==> default: Generating public/private rsa key pair.
==> default: Saving the key failed: /vagrant/puphpet/files/dot/ssh/id_rsa.
==> default: /tmp/vagrant-shell: line 22: puttygen: command not found
==> default: Your private key for SSH-based authentication has been saved to 'puphpet/files/dot/ssh/id_rsa'!
==> default: cat: /vagrant/puphpet/files/dot/ssh/id_rsa.pub
==> default: : No such file or directory
==> default: Adding generated key to /root/.ssh/id_rsa
==> default: Adding generated key to /root/.ssh/id_rsa.pub
==> default: Adding generated key to /root/.ssh/authorized_keys
==> default: cp: cannot stat ‘/vagrant/puphpet/files/dot/ssh/id_rsa’: No such file or directory
==> default: cp: cannot stat ‘/vagrant/puphpet/files/dot/ssh/id_rsa.pub’: No such file or directory
==> default: cat: /vagrant/puphpet/files/dot/ssh/id_rsa.pub
==> default: : No such file or directory
==> default: chmod: cannot access ‘/root/.ssh/id_rsa.pub’: No such file or directory
==> default: chmod: cannot access ‘/root/.ssh/id_rsa’: No such file or directory
==> default: Adding generated key to /home/vagrant/.ssh/id_rsa
==> default: Adding generated key to /home/vagrant/.ssh/id_rsa.pub
==> default: Adding generated key to /home/vagrant/.ssh/authorized_keys
==> default: cp: cannot stat ‘/vagrant/puphpet/files/dot/ssh/id_rsa’: No such file or directory
==> default: cp: cannot stat ‘/vagrant/puphpet/files/dot/ssh/id_rsa.pub’: No such file or directory
==> default: chmod: cannot access ‘/home/vagrant/.ssh/id_rsa.pub’: No such file or directory
==> default: chmod: cannot access ‘/home/vagrant/.ssh/id_rsa’: No such file or directory
==> default: Running provisioner: shell...
    default: Running: /var/folders/ph/pw3mw1mn4rd1m3ry_j1j9r640000gn/T/vagrant-shell20150207-16165-r7fyyv.sh
==> default: stdin: is not a tty
==> default: /bin/bash: /vagrant/puphpet/shell/os-detect.sh: No such file or directory
==> default: /bin/bash: /vagrant/puphpet/shell/os-detect.sh: No such file or directory
==> default: /bin/bash: /vagrant/puphpet/shell/os-detect.sh: No such file or directory
==> default: Running provisioner: shell...
    default: Running: /var/folders/ph/pw3mw1mn4rd1m3ry_j1j9r640000gn/T/vagrant-shell20150207-16165-4guodp.sh
==> default: stdin: is not a tty
==> default: /bin/bash: /vagrant/puphpet/shell/os-detect.sh: No such file or directory
==> default: /bin/bash: /vagrant/puphpet/shell/os-detect.sh: No such file or directory
==> default: /bin/bash: /vagrant/puphpet/shell/os-detect.sh: No such file or directory
==> default: Running provisioner: puppet...
==> default: Running Puppet with site.pp...
==> default: stdin: is not a tty
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-407b6ea604644653f113f9909de16417/composer/lib/facter/composer_home.rb
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-407b6ea604644653f113f9909de16417/concat/lib/facter/concat_basedir.rb
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-407b6ea604644653f113f9909de16417/firewall/lib/facter/ip6tables_version.rb
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-407b6ea604644653f113f9909de16417/firewall/lib/facter/iptables_persistent_version.rb
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-407b6ea604644653f113f9909de16417/firewall/lib/facter/iptables_version.rb
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-407b6ea604644653f113f9909de16417/git/lib/facter/git_exec_path.rb
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-407b6ea604644653f113f9909de16417/git/lib/facter/git_version.rb
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-407b6ea604644653f113f9909de16417/php/lib/facter/php_fact_extension_dir.rb
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-407b6ea604644653f113f9909de16417/php/lib/facter/php_fact_version.rb
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-407b6ea604644653f113f9909de16417/puppi/lib/facter/last_run.rb
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-407b6ea604644653f113f9909de16417/puppi/lib/facter/puppi_projects.rb
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-407b6ea604644653f113f9909de16417/puppi/lib/facter/windows_common_appdata.rb
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-407b6ea604644653f113f9909de16417/rabbitmq/lib/facter/rabbitmq_erlang_cookie.rb
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-407b6ea604644653f113f9909de16417/rvm/lib/facter/rvm_installed.rb
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-407b6ea604644653f113f9909de16417/rvm/lib/facter/rvm_version.rb
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-407b6ea604644653f113f9909de16417/staging/lib/facter/staging_http_get.rb
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-407b6ea604644653f113f9909de16417/staging/lib/facter/staging_windir.rb
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-407b6ea604644653f113f9909de16417/stdlib/lib/facter/facter_dot_d.rb
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-407b6ea604644653f113f9909de16417/stdlib/lib/facter/pe_version.rb
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-407b6ea604644653f113f9909de16417/stdlib/lib/facter/puppet_vardir.rb
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-407b6ea604644653f113f9909de16417/stdlib/lib/facter/root_home.rb
==> default: Error: No such file or directory - /vagrant/puphpet/config.yaml at /tmp/vagrant-puppet/manifests-893fcda21077f5a583c2dbbba8515c0a/nodes/Apache.pp:1 on node packer-parallels-iso.localdomain
==> default: Wrapped exception:
==> default: No such file or directory - /vagrant/puphpet/config.yaml
==> default: Error: No such file or directory - /vagrant/puphpet/config.yaml at /tmp/vagrant-puppet/manifests-893fcda21077f5a583c2dbbba8515c0a/nodes/Apache.pp:1 on node packer-parallels-iso.localdomain
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

config.yaml CONTENTS
===================
---
vagrantfile-local:
    vm:
        box: puphpet/ubuntu1404-x32
        box_url: puphpet/ubuntu1404-x32
        hostname: ''
        memory: '1024'
        cpus: '2'
        chosen_provider: parallels
        network:
            private_network: 10.211.55.11
            forwarded_port:
                DFxU9AIPyhcM:
                    host: '7373'
                    guest: '22'
        post_up_message: ''
        provider:
            virtualbox:
                modifyvm:
                    natdnshostresolver1: on
            vmware:
                numvcpus: 1
            parallels:
                cpus: 1
        provision:
            puppet:
                manifests_path: puphpet/puppet
                manifest_file: site.pp
                module_path: puphpet/puppet/modules
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
                    - '--parser future'
        synced_folder:
            8SorzLID2nNj:
                owner: www-data
                group: www-data
                source: ./
                target: /var/www
                sync_type: nfs
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    exclude:
                        - .vagrant/
                    auto: 'false'
        usable_port_range:
            start: 10200
            stop: 10500
    ssh:
        host: null
        port: null
        private_key_path: null
        username: vagrant
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'
    vagrant:
        host: detect
server:
    install: '1'
    packages:
        - vim
users_groups:
    install: '1'
    groups: {  }
    users: {  }
cron:
    install: '1'
    jobs: {  }
firewall:
    install: '1'
    rules: null
apache:
    install: '1'
    settings:
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - rewrite
    vhosts:
        hhjayxxprpjf:
            servername: awesome.dev
            serveraliases:
                - www.awesome.dev
            docroot: /var/www/awesome
            port: '80'
            setenv:
                - 'APP_ENV dev'
            directories:
                11ln0eq0hpzj:
                    provider: directory
                    path: /var/www/awesome
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - all
                        - granted
                    custom_fragment: ''
            engine: php
            custom_fragment: ''
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
    mod_pagespeed: 0
nginx:
    install: '0'
    settings:
        default_vhost: 1
        proxy_buffer_size: 128k
        proxy_buffers: '4 256k'
    upstreams: {  }
    vhosts:
        9rmbybvorbas:
            proxy: ''
            server_name: awesome.dev
            server_aliases:
                - www.awesome.dev
            www_root: /var/www/awesome
            listen_port: '80'
            location: \.php$
            index_files:
                - index.html
                - index.htm
                - index.php
            envvars:
                - 'APP_ENV dev'
            engine: php
            client_max_body_size: 1m
            ssl_cert: ''
            ssl_key: ''
php:
    install: '1'
    version: '56'
    composer: '1'
    composer_home: ''
    modules:
        php:
            - cli
            - intl
            - mcrypt
        pear: {  }
        pecl:
            - pecl_http
    ini:
        display_errors: On
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
    timezone: Africa/Lagos
    mod_php: '0'
hhvm:
    install: '0'
    nightly: 0
    composer: '1'
    composer_home: ''
    settings:
        host: 127.0.0.1
        port: '9000'
    ini:
        display_errors: On
        error_reporting: '-1'
    timezone: null
xdebug:
    install: '0'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
xhprof:
    install: '0'
wpcli:
    install: '0'
    version: v0.17.1
drush:
    install: '0'
    version: 6.3.0
ruby:
    install: '1'
    versions:
        4ZXy16pCjWF6:
            version: ''
nodejs:
    install: '0'
    npm_packages: {  }
python:
    install: '1'
    packages: {  }
    versions:
        nRqAGJx0ysBg:
            version: ''
mysql:
    install: '1'
    override_options: {  }
    root_password: '123'
    adminer: 0
    databases:
        m50fh8JDf6hm:
            grant:
                - ALL
            name: dbtest
            host: localhost
            user: dbuser
            password: '123'
            sql_file: ''
postgresql:
    install: '0'
    settings:
        root_password: '123'
        user_group: postgres
        encoding: UTF8
        version: '9.3'
    databases: {  }
    adminer: 0
mariadb:
    install: '0'
    override_options: {  }
    root_password: '123'
    adminer: 0
    databases: {  }
    version: '10.0'
sqlite:
    install: '0'
    adminer: 0
    databases: {  }
mongodb:
    install: '0'
    settings:
        auth: 1
        port: '27017'
    databases: {  }
redis:
    install: '0'
    settings:
        conf_port: '6379'
mailcatcher:
    install: '0'
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '1080'
        mailcatcher_path: /usr/local/rvm/wrappers/default
        from_email_method: inline
beanstalkd:
    install: '0'
    settings:
        listenaddress: 0.0.0.0
        listenport: '13000'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: 0
    binlogdir: /var/lib/beanstalkd/binlog
rabbitmq:
    install: '0'
    settings:
        port: '5672'
elastic_search:
    install: '0'
    settings:
        version: 1.4.1
        java_install: true
solr:
    install: '0'
    settings:
        version: 4.10.2
        port: '8984'

**Comment by jtreminio** [comment]
The problems start here: `==> default: /bin/bash: /vagrant/puphpet/shell/os-detect.sh: No such file or directory`.

Not sure what's going on with your system. I'll run it locally and see if I can't replicate.

**Comment by dbd5** [comment]
Thanks Bro!

Glad to get an update if you find anything

Regards

**Comment by davehubler** [comment]
I ran into this error on Mac running Homestead. The following worked for me... 

`chmod go-w /usr/local/opt`

**Comment by jtreminio** [comment]
@davehubler is correct: http://stackoverflow.com/questions/3952243/warning-insecure-world-writable-dir-usr-local-bin-in-path-mode-040777

**Comment by dbd5** [comment]
Thanks
