### ISSUE TITLE
PHP not running on new VM

### ISSUE THREAD

**Issue by OsakaWebbie** [puphpet/puphpet#1364]
I recently put an old config.yaml file back into the PuPHPet GUI, did a couple minor changes, and generated a new ZIP. The only changes I made to the new config.yaml after downloading were incrementing the IP address (from 102 to 103) and the host port (from 8080 to 8082) to deconflict with the old VM. Everything else below is "stock" from the GUI. Nginx serves HTML files okay, but PHP files are passed through - apparently PHP is not running. Did I miss some critical step in the process?

There is one spot during the `vagrant up` when I get a warning - it doesn't appear fatal, but perhaps something is being skipped. This is the warning with one line of context before and after it:

    ==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-7136c87de78e559e19a480f599238264/stdlib/lib/facter/root_home.rb
    ==> default: Warning: Could not retrieve fact fqdn
    ==> default: Notice: Compiled catalog for localhost in environment production in 83.13 seconds

I don't know what fact it is failing to find, or if it's related to lack of PHP or not, but it's the only thing I noticed. Sorry that I can't give more troubleshooting info (I'm a programmer, not a sysadmin), but because it's PuPHPet, anyone should be able to take the file below and reproduce the problem.

```---
vagrantfile-local:
    vm:
        box: puphpet/centos65-x64
        box_url: puphpet/centos65-x64
        hostname: ''
        memory: '512'
        cpus: '1'
        chosen_provider: virtualbox
        network:
            private_network: 192.168.56.103
            forwarded_port:
                j4SJKvkVKudW:
                    host: '8082'
                    guest: '80'
        post_up_message: ''
        provider:
            virtualbox:
                modifyvm:
                    natdnshostresolver1: on
            vmware:
                numvcpus: 1
            parallels:
                cpus: 1
        provision:
            puppet:
                manifests_path: puphpet/puppet
                manifest_file: site.pp
                module_path: puphpet/puppet/modules
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
                    - '--parser future'
        synced_folder:
            zEyRZyFvzCFu:
                owner: ''
                group: ''
                source: 'c:/dev/webroot'
                target: /var/www
                sync_type: default
                rsync:
                    auto: 'false'
        usable_port_range:
            start: 10200
            stop: 10500
    ssh:
        host: null
        port: null
        private_key_path: null
        username: vagrant
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'
    vagrant:
        host: detect
server:
    install: '1'
    packages:
        - vim-common
        - postfix
        - dovecot
users_groups:
    install: '1'
    groups: {  }
    users: {  }
cron:
    install: '1'
    jobs: {  }
firewall:
    install: '1'
    rules: null
apache:
    install: '0'
    settings:
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules: {  }
    vhosts: {  }
    mod_pagespeed: 0
nginx:
    install: '1'
    settings:
        default_vhost: 1
        proxy_buffer_size: 128k
        proxy_buffers: '4 256k'
    upstreams: {  }
    vhosts:
        ovbvfftcbjik:
            proxy: ''
            server_name: '*.kizunadb.dev'
            www_root: /var/www/kizunadb/codebase
            listen_port: '80'
            location: .php$
            index_files:
                - index.php
                - index.html
                - index.htm
            envvars:
                - 'APP_ENV dev'
            engine: ''
            client_max_body_size: 1m
            ssl_cert: ''
            ssl_key: ''
        vj6cmpzfx5wk:
            proxy: ''
            server_name: client2.kizunadb.dev
            www_root: /var/www/codebase
            listen_port: '80'
            location: .php$
            index_files:
                - index.html
                - index.htm
                - index.php
            envvars:
                - 'APP_ENV dev'
            engine: ''
            client_max_body_size: 1m
            ssl_cert: ''
            ssl_key: ''
        hj4g788eqbuv:
            proxy: ''
            server_name: l4jp.dev
            www_root: /var/www/l4jp
            listen_port: '80'
            location: .php$
            index_files:
                - index.html
                - index.htm
                - index.php
            engine: ''
            client_max_body_size: 1m
            ssl_cert: ''
            ssl_key: ''
php:
    install: '0'
    version: '55'
    composer: '1'
    composer_home: ''
    modules:
        php:
            - cli
            - gd
            - intl
            - mbstring
            - mcrypt
        pear: {  }
        pecl:
            - pecl_http
    ini:
        display_errors: On
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
    timezone: Asia/Tokyo
    mod_php: 0
hhvm:
    install: '0'
    nightly: 0
    composer: '1'
    composer_home: ''
    settings:
        host: '0'
        port: '0'
    ini: {  }
    timezone: null
xdebug:
    install: '1'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
xhprof:
    install: '0'
wpcli:
    install: '0'
    version: ''
drush:
    install: '0'
    version: ''
ruby:
    install: '1'
    versions: {  }
nodejs:
    install: '0'
    npm_packages: {  }
python:
    install: '1'
    packages: {  }
    versions: {  }
mysql:
    install: '1'
    override_options: {  }
    root_password: '#1PhalconServer!'
    adminer: 0
    databases:
        WR3kFrkYBxgQ:
            grant:
                - DELETE
                - INSERT
                - SELECT
                - UPDATE
            name: kizuna_dev
            host: localhost
            user: dev
            password: '#1PhalconServer!'
            sql_file: ''
postgresql:
    install: '0'
    settings:
        root_password: '123'
        user_group: postgres
        encoding: UTF8
        version: '9.3'
    databases: {  }
    adminer: 0
mariadb:
    install: '0'
    override_options: {  }
    root_password: '123'
    adminer: 0
    databases: {  }
sqlite:
    install: '0'
    adminer: 0
    databases: {  }
mongodb:
    install: '0'
    settings:
        auth: 1
        port: '27017'
    databases: {  }
redis:
    install: '0'
    settings:
        conf_port: '6379'
mailcatcher:
    install: '0'
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '1080'
        mailcatcher_path: /usr/local/rvm/wrappers/default
        from_email_method: inline
beanstalkd:
    install: '0'
    settings:
        listenaddress: 0.0.0.0
        listenport: '13000'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: 0
    binlogdir: /var/lib/beanstalkd/binlog
rabbitmq:
    install: '0'
    settings:
        port: '5672'
elastic_search:
    install: '0'
    settings:
        version: ''
        java_install: true
solr:
    install: '0'
    settings:
        version: ''
        port: ''

**Comment by jtreminio** [comment]
Change this:

````php:
    install: '0'
````

to this:

````php:
    install: '1'
````

Older versions of puphpet.com installed php by default, so there wasn't a flag.

**Comment by OsakaWebbie** [comment]
Duh, I didn't even notice the `install: '0'`, because I assumed that PuPHPet without PHP wasn't even possible. [blush!]

However, it's still not working - I'm sure that changed things, but PHP files are still not being processed. Here is the output of `vagrant provision` in case that helps:

==> default: Running provisioner: shell...
    default: Running: C:/Users/Karen/AppData/Local/Temp/vagrant-shell20150208-2464-1uckfz6.sh
==> default: 
(ASCII art omitted after Markdown mangled it)
==> default: 
==> default: Running provisioner: shell...
    default: Running: C:/Users/Karen/AppData/Local/Temp/vagrant-shell20150208-2464-hn7jnu.sh
==> default: Pre-existing private key found at 'puphpet/files/dot/ssh/root_id_rsa'
==> default: Pre-existing private key found at 'puphpet/files/dot/ssh/id_rsa'
==> default: Adding generated key to /root/.ssh/id_rsa
==> default: Adding generated key to /root/.ssh/id_rsa.pub
==> default: Adding generated key to /root/.ssh/authorized_keys
==> default: Adding generated key to /home/vagrant/.ssh/id_rsa
==> default: Adding generated key to /home/vagrant/.ssh/id_rsa.pub
==> default: Adding generated key to /home/vagrant/.ssh/authorized_keys
==> default: Running provisioner: shell...
    default: Running: C:/Users/Karen/AppData/Local/Temp/vagrant-shell20150208-2464-1ih8igu.sh
==> default: Running provisioner: shell...
    default: Running: C:/Users/Karen/AppData/Local/Temp/vagrant-shell20150208-2464-1y17kbg.sh
==> default: Running provisioner: puppet...
==> default: Running Puppet with site.pp...
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-7136c87de78e559e19a480f599238264/composer/lib/facter/composer_home.rb
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-7136c87de78e559e19a480f599238264/concat/lib/facter/concat_basedir.rb
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-7136c87de78e559e19a480f599238264/firewall/lib/facter/ip6tables_version.rb
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-7136c87de78e559e19a480f599238264/firewall/lib/facter/iptables_persistent_version.rb
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-7136c87de78e559e19a480f599238264/firewall/lib/facter/iptables_version.rb
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-7136c87de78e559e19a480f599238264/git/lib/facter/git_exec_path.rb
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-7136c87de78e559e19a480f599238264/git/lib/facter/git_version.rb
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-7136c87de78e559e19a480f599238264/php/lib/facter/php_fact_extension_dir.rb
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-7136c87de78e559e19a480f599238264/php/lib/facter/php_fact_version.rb
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-7136c87de78e559e19a480f599238264/puppi/lib/facter/last_run.rb
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-7136c87de78e559e19a480f599238264/puppi/lib/facter/puppi_projects.rb
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-7136c87de78e559e19a480f599238264/puppi/lib/facter/windows_common_appdata.rb
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-7136c87de78e559e19a480f599238264/rabbitmq/lib/facter/rabbitmq_erlang_cookie.rb
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-7136c87de78e559e19a480f599238264/rvm/lib/facter/rvm_installed.rb
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-7136c87de78e559e19a480f599238264/rvm/lib/facter/rvm_version.rb
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-7136c87de78e559e19a480f599238264/staging/lib/facter/staging_http_get.rb
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-7136c87de78e559e19a480f599238264/staging/lib/facter/staging_windir.rb
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-7136c87de78e559e19a480f599238264/stdlib/lib/facter/facter_dot_d.rb
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-7136c87de78e559e19a480f599238264/stdlib/lib/facter/pe_version.rb
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-7136c87de78e559e19a480f599238264/stdlib/lib/facter/puppet_vardir.rb
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-7136c87de78e559e19a480f599238264/stdlib/lib/facter/root_home.rb
==> default: Warning: Could not retrieve fact fqdn
==> default: Notice: Compiled catalog for localhost in environment production in 138.90 seconds
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-7136c87de78e559e19a480f599238264/composer/lib/facter/composer_home.rb
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-7136c87de78e559e19a480f599238264/concat/lib/facter/concat_basedir.rb
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-7136c87de78e559e19a480f599238264/firewall/lib/facter/ip6tables_version.rb
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-7136c87de78e559e19a480f599238264/firewall/lib/facter/iptables_persistent_version.rb
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-7136c87de78e559e19a480f599238264/firewall/lib/facter/iptables_version.rb
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-7136c87de78e559e19a480f599238264/git/lib/facter/git_exec_path.rb
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-7136c87de78e559e19a480f599238264/git/lib/facter/git_version.rb
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-7136c87de78e559e19a480f599238264/php/lib/facter/php_fact_extension_dir.rb
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-7136c87de78e559e19a480f599238264/php/lib/facter/php_fact_version.rb
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-7136c87de78e559e19a480f599238264/puppi/lib/facter/last_run.rb
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-7136c87de78e559e19a480f599238264/puppi/lib/facter/puppi_projects.rb
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-7136c87de78e559e19a480f599238264/puppi/lib/facter/windows_common_appdata.rb
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-7136c87de78e559e19a480f599238264/rabbitmq/lib/facter/rabbitmq_erlang_cookie.rb
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-7136c87de78e559e19a480f599238264/rvm/lib/facter/rvm_installed.rb
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-7136c87de78e559e19a480f599238264/rvm/lib/facter/rvm_version.rb
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-7136c87de78e559e19a480f599238264/staging/lib/facter/staging_http_get.rb
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-7136c87de78e559e19a480f599238264/staging/lib/facter/staging_windir.rb
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-7136c87de78e559e19a480f599238264/stdlib/lib/facter/facter_dot_d.rb
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-7136c87de78e559e19a480f599238264/stdlib/lib/facter/pe_version.rb
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-7136c87de78e559e19a480f599238264/stdlib/lib/facter/puppet_vardir.rb
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-7136c87de78e559e19a480f599238264/stdlib/lib/facter/root_home.rb
==> default: Info: Applying configuration version '1423443074'
==> default: Notice: /Stage[main]/Main/File[/var/lib/php/session]/owner: owner changed 'root' to 'www-data'
==> default: Notice: /Stage[main]/Main/File[/var/lib/php/session]/group: group changed 'apache' to 'www-data'
==> default: Notice: /Stage[main]/Main/File[/var/lib/php/session]/mode: mode changed '0770' to '0775'
==> default: Notice: /Stage[main]/Main/Exec[dotfiles]/returns: executed successfully
==> default: Notice: /Stage[main]/Main/Php_pecl_mod[pecl_http]/Puphpet::Php::Pecl[pecl_http]/Php::Pecl::Module[pecl_http]/Exec[pecl-pecl_http]/returns: executed successfully
==> default: Notice: /Stage[main]/Pyenv/Vcsrepo[/usr/local/pyenv]/revision: revision changed '3cde540ca00208fbfd0a5e7708c3053bc8cca9f5' to 'v0.4.0-20140404'
==> default: Notice: Finished catalog run in 239.28 seconds
==> default: Running provisioner: shell...
    default: Running: C:/Users/Karen/AppData/Local/Temp/vagrant-shell20150208-2464-1l4fzth.sh
==> default: Running files in files/exec-once
==> default: Finished running files in files/exec-once
==> default: To run again, delete hashes you want rerun in /.puphpet-stuff/exec-once-ran or the whole file to rerun all
==> default: Running files in files/exec-always
==> default: Finished running files in files/exec-always
==> default: Running provisioner: shell...
    default: Running: C:/Users/Karen/AppData/Local/Temp/vagrant-shell20150208-2464-1bbyvkp.sh
==> default: Running files in files/startup-once
==> default: Finished running files in files/startup-once
==> default: To run again, delete hashes you want rerun in /.puphpet-stuff/startup-once-ran or the whole file to rerun all
==> default: Running files in files/startup-always
==> default: Finished running files in files/startup-always
==> default: Running provisioner: shell...
    default: Running: C:/Users/Karen/AppData/Local/Temp/vagrant-shell20150208-2464-1d7b7fz.sh

**Comment by kevinsmith** [comment]
I ran into the same issue @OsakaWebbie, and it was because I also imported an old ``config.yaml`` file as a starting point, too. Apparently something changed between then and now, but whatever the reason, here's the fix. In ``config.yaml``, look for the ``engine`` key under ``apache`` > ``vhosts`` > random string of characters. Make sure it looks like this:

``engine: 'php'``

**Comment by OsakaWebbie** [comment]
Thanks, Kevin! In my case I'm using nginx, not apache, but doing the equivalent in the nginx section did the trick.

**Comment by kevinsmith** [comment]
Glad I could help!
