### ISSUE TITLE
How to I prevent the sudo password prompt for the NFS bind on each reload?

### ISSUE THREAD

**Issue by toby-griffiths** [puphpet/puphpet#1366]
Can anyone help me with the entry I'd been to put in my sudoers file to prevent being prompted for my password every time my VM reloads, because I'm using NFS shares?

**Comment by svycka** [comment]
+1

**Comment by beporter** [comment]
There are instructions and examples for this on vagrant's website here: https://docs.vagrantup.com/v2/synced-folders/nfs.html

Are those not sufficient? Perhaps posting the specific problem you're seeing on StackOverflow would yield results in that case?

**Comment by jtreminio** [comment]
@beporter is correct, this is not a puphpet issue and I would have no idea how to help you. Ask the Vagrant project itself - they may have an idea on this.

In reality it sounds like a OSX/Linux question. In Linux, adding yourself to the sudoers file and setting nopasswd should work, but I'm guessing you'd need to call vagrant using `sudo` every time.

**Comment by toby-griffiths** [comment]
For anyone interested, I found this... https://gist.github.com/GUI/2864683

The important bit is adding the following to your `/etc/sudoers` file using `visudo`...

```
# Allow passwordless startup of Vagrant when using NFS.
Cmnd_Alias VAGRANT_EXPORTS_ADD = /usr/bin/su root -c echo '*' >> /etc/exports
Cmnd_Alias VAGRANT_NFSD = /sbin/nfsd restart
Cmnd_Alias VAGRANT_EXPORTS_REMOVE = /usr/bin/sed -e /*/ d -ibak /etc/exports
%staff ALL=(root) NOPASSWD: VAGRANT_EXPORTS_ADD, VAGRANT_NFSD, VAGRANT_EXPORTS_REMOVE
```

**Comment by beporter** [comment]
Just to be clear for anyone else that ends up here; here is how [the Vagrant docs themselves](https://docs.vagrantup.com/v2/synced-folders/nfs.html) recommend setting up your `sudoers` files for OS X:

```shell
Cmnd_Alias VAGRANT_EXPORTS_ADD = /usr/bin/tee -a /etc/exports
Cmnd_Alias VAGRANT_NFSD = /sbin/nfsd restart
Cmnd_Alias VAGRANT_EXPORTS_REMOVE = /usr/bin/sed -E -e /*/ d -ibak /etc/exports
%admin ALL=(root) NOPASSWD: VAGRANT_EXPORTS_ADD, VAGRANT_NFSD, VAGRANT_EXPORTS_REMOVE
```
