### ISSUE TITLE
Server Timezone Setting

### ISSUE THREAD

**Issue by Richtermeister** [puphpet/puphpet#1367]
Since php has a timezone, and you allow setting cron tasks, it would be nice to also specify the server timezone somewhere (or have a global timezone config which affects php as well).

**Comment by shivapoudel** [comment]
Ref: #1526

**Comment by Jarlskov** [comment]
:+1:

**Comment by NReilingh** [comment]
+1 -- a time zone setting for the entire instance would also be useful when looking at locally-deployed server log files for errors.

**Comment by alexbusu** [comment]
![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png)
