### ISSUE TITLE
Custom Server Directives?

### ISSUE THREAD

**Issue by dtirer** [puphpet/puphpet#1369]
Beyond the basic setup available in the GUI, how can I (for example) go about adding custom basic_auth   locations to an nginx conf file, or or add custom features to an apache file?  How about setting up cron jobs?

**Comment by jtreminio** [comment]
These are unfortunately not natively supported yet.

You *can* create an `exec-always` file that edits your target vhosts, but take note that the apache and nginx modules will overwrite any changes they did not make on provision.
