### ISSUE TITLE
Local Overrides

### ISSUE THREAD

**Issue by CWSpear** [puphpet/puphpet#1370]
#1347 solves my immediate issue, and the provider is the definitely biggest single item I'd love to override, but I'd like to be able to override *any* value on a local basis. 

i.e. maybe you have tons of memory and want to through extra memory or CPUs at it than the default, maybe you need to override the ports cuz you have other services uses the ports in the default config. It probably wouldn't (shouldn't??) be anything outside of `varantfile-local.vm`.

I would be willing to do a PR on this, but wanted to vet the idea first.

**Comment by jtreminio** [comment]
`Vagrantfile` is Ruby code, so it would be as simple as checking if a `config-custom.yaml` exists and including it, after including `config.yaml`

The problem I've run into is that I've not been able to find a Ruby equivalent of PHP's `array_merge_recursive()`.

Say you have the following:

````vagrantfile-local:
    vm:
        box: puphpet/centos65-x64
        box_url: 'puphpet/centos65-x64'
        hostname: null
        provider:
            virtualbox:
                modifyvm:
                    natdnshostresolver1: on
                    memory: '512'
````

If you wanted to only change the `vagrantfile-local.vm.provider.virtualbox.modifyvm.memory` value, you'd need to copy/paste the whole thing, you can't simply do

````vagrantfile-local:
    vm:
        provider:
            virtualbox:
                modifyvm:
                    memory: '512'
````

because this discards all the other values within those keys.

If you have a good solution in Ruby that can mimic `array_merge_recursive()` I'll def. implement it.

**Comment by CWSpear** [comment]
```ruby
class ::Hash
    def deep_merge(second)
        merger = proc { |key, v1, v2| Hash === v1 && Hash === v2 ? v1.merge(v2, &merger) : v2 }
        self.merge(second, &merger)
    end
end
```

```ruby
dir = File.dirname(File.expand_path(__FILE__))

configValues = YAML.load_file("#{dir}/puphpet/config.yaml")

if File.exists?("#{dir}/puphpet/overrides.yaml")
    overrides = YAML.load_file("#{dir}/puphpet/overrides.yaml")
    configValues = configValues.deep_merge(overrides)
end

data = configValues['vagrantfile-local']
```

I'm not a Ruby dev, and this was piece together (but works) with stuff I found on the interwebs. I didn't know how to make `deep_merge!` work for h4x0r level shortcutting, but it works as is.

**Comment by CWSpear** [comment]
I tested this with provider and memory at least. I didn't go super deep.

And again, maybe we should only allow overriding that `vm` key, cuz that's stuff that could relatively safely change between boxes without losing the spirit of Vagrant (i.e., what's the point of it all if I overrode MariaDB to use postgres??)

**Comment by beporter** [comment]
Being able to optionally load a second "local" config file that would selectively overwrite values in the regular `config.yaml` file would go a **long** way towards alleviating one of the problems described in #1320 too.

**Comment by CWSpear** [comment]
I wanted to reiterate the need to have it only override certain values... such as memory and provider and *maybe* the ports (*generally* speaking, code shouldn't rely on the host port, so it shouldn't normally be a problem, but *could*). I think if we allow people to start changing what gets installed or not, it would defeat part of the purpose and spirit of Vagrant.

**Comment by beporter** [comment]
If the secondary config file is still getting committed to source control, I don't think the file diverging between devs would be much of an issue, but I see your point. 

It'd add a lot more complexity to somehow maintain a list of "override allowed" values though, wouldn't it? We're already lacking a _canonical_ list of the available settings and their allowed values anywhere. All we have is the limited subset the generator at puphpet.com is able to produce.

**Comment by CWSpear** [comment]
I would argue that the override config is *not* something you put into source control. It's meant to just override your local config from the default. It would defeat the purpose if you put it in source control (why not just edit the regular config?).

As part of that, it would be wise to add it to `.gitignore`, etc in the puphpet build.

As for things allowed to override, you do have a good point. I think all that would really be needed is:

* `vm.memory`
* `vm.cpus`
* `vm.chosen_provider`
* `vm.network`

**Comment by beporter** [comment]
In my case, the answer to "why not edit the default config?" is that it is a vendor file supplied by composer, not stored in the project repo at all. We are probably working towards different goals, which is fine, but I don't want to hijack your thread any further off course then. :sweat_smile:

**Comment by CWSpear** [comment]
The main purpose here, is we put our Vagrant config (and all the puphpet files) in our repo and new devs just need to run `vagrant up` and (30 minutes later...) they're off and running!

The issue here, is I spent the money to get VMware Fusion and the Vagrant plugin, which a couple other devs I know have done, but most still use Virtualbox. If I put vmware in the config, then it doesn't work for them, and if I put virtualbox in the config, I don't get all those benefits I paid for.

#1347 fixes that immediate issue; I was just proposing, when it comes to the boxes the individual uses, maybe we could override a few other things, and outlined reasons why that might be useful (i.e. I have 4x as much memory as another dev, so I have more to spare, but don't want to put that as the default; or I have a service I can't really turn off that uses the IP in the config... in that case, we probably could change it, but then that maybe messes up with another dev's local settings/bookmarks, etc).

**Comment by beporter** [comment]
Indeed, the things that represent the "border" between the guest and the host should be flexible in order to accommodate changes in the **hosts'** environments, such has having more system RAM or an 8-core i7 instead of a Core 2 Duo. (Although a compelling counter-argument could be made for targeting a uniform lowest-common-denominator too so that all devs work in a uniform environment.)
