### ISSUE TITLE
File changes made on host not reflecting file in /vagrant

### ISSUE THREAD

**Issue by welly** [puphpet/puphpet#1371]
I'm having an issue with editing a file on my host in that when I make a change, I'm finding that change isn't showing up on the guest vagrant machine. If I edit the same file on the guest machine, the file is updated on the host, however.

Is there any reason why this would occur?

Thanks

**Comment by jtreminio** [comment]
You should treat the files in `/vagrant` as read only. As far as I am aware, they are only updated on `vagrant provision`.

If you want to edit files on host and see them reflected on VM, you should set up a separate shared folder.

**Comment by welly** [comment]
Just for anyone who experiences similar problems, check atomic saving if your editor supports this. In Sublime Text 3, setting "atomic_save": false resolves this problem.
