### ISSUE TITLE
Error running 'requirements_debian_libs_install gawk libreadline6-dev zlib1g-dev libssl-dev libyaml-dev libsqlite3-dev sqlite3 autoconf libgdbm-dev libncurses5-dev automake libtool bison pkg-config libffi-dev',

### ISSUE THREAD

**Issue by AgnesBLumatao** [puphpet/puphpet#1372]
The required packages can't be installed. This is the error message:

In case of problems: http://rvm.io/help and https://twitter.com/rvm_io
rvm 1.26.10 (latest) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]
Searching for binary rubies, this might take some time.
Found remote file https://rvm_io.global.ssl.fastly.net/binaries/debian/7/x86_64/ruby-1.9.3-p551.tar.bz2
Checking requirements for debian.
Installing requirements for debian.
Updating system....
Installing required packages: gawk, libreadline6-dev, zlib1g-dev, libssl-dev, libyaml-dev, libsqlite3-dev, sqlite3, autoconf, libgdbm-dev, libncurses5-dev, automake, libtool, bison, pkg-config, libffi-dev....
Error running 'requirements_debian_libs_install gawk libreadline6-dev zlib1g-dev libssl-dev libyaml-dev libsqlite3-dev sqlite3 autoconf libgdbm-dev libncurses5-dev automake libtool bison pkg-config libffi-dev',
showing last 15 lines of /usr/local/rvm/log/1424056767_ruby-1.9.3-p551/package_install_gawk_libreadline6-dev_zlib1g-dev_libssl-dev_libyaml-dev_libsqlite3-dev_sqlite3_autoconf_libgdbm-dev_libncurses5-dev_automake_libtool_bison_pkg-config_libffi-dev.log
The following NEW packages will be installed:
  autoconf automake autotools-dev bison gawk libbison-dev libffi-dev
  libgdbm-dev libglib2.0-0 libncurses5-dev libreadline6-dev libsigsegv2
  libsqlite3-dev libssl-dev libtinfo-dev libtool libyaml-dev pkg-config
  sqlite3 zlib1g-dev
The following packages will be upgraded:
  libssl1.0.0 libyaml-0-2
2 upgraded, 20 newly installed, 0 to remove and 90 not upgraded.
Need to get 10.5 MB of archives.
After this operation, 25.0 MB of additional disk space will be used.
WARNING: The following packages cannot be authenticated!
  libssl1.0.0 libssl-dev
E: There are problems and -y was used without --force-yes
++ /scripts/functions/utility : __rvm_try_sudo()  381 > return 100
++ /scripts/functions/requirements/debian : requirements_debian_libs_install()  36 > return 100
Requirements installation failed with status: 100.
Cleaning up rvm archives
Cleaning up rvm repos
Cleaning up rvm src
Cleaning up rvm log
Cleaning up rvm tmp
Cleaning up rvm gemsets
Cleaning up rvm links
Cleanup done.
/usr/local/rvm/scripts/override_gem: line 19: gem: command not found
Finished installing RVM and Ruby 1.9.3

**Comment by jtreminio** [comment]
Paste your config.yaml.

**Comment by AgnesBLumatao** [comment]
---
vagrantfile-local:
    vm:
        box: debian-73-x64-virtualbox-puppet.box
        box_url: 'http://puppet-vagrant-boxes.puppetlabs.com/debian-73-x64-virtualbox-puppet.box'
        hostname: ''
        memory: '512'
        cpus: '1'
        chosen_provider: virtualbox
        network:
            private_network: 192.168.78.102
            forwarded_port:
                3Nv5kNf8lmdS:
                    host: '6984'
                    guest: '22'
        provider:
            virtualbox:
                modifyvm:
                    natdnshostresolver1: on
            vmware:
                numvcpus: 1
            parallels:
                cpus: 1
        provision:
            puppet:
                manifests_path: puphpet/puppet
                manifest_file: site.pp
                module_path: puphpet/puppet/modules
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
                    - '--parser future'
        synced_folder:
            IZmhNI1jWE1W:
                owner: www-data
                group: www-data
                source: ./mgr
                target: /var/www/teaser_site/mgr
                sync_type: nfs
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    exclude:
                        - .vagrant/
                    auto: 'false'
            Hb5mAX4VNnEV:
                owner: www-data
                group: www-data
                source: ./service
                target: /var/www/teaser_site/web
                sync_type: nfs
                rsync:
                    auto: 'false'
        usable_port_range: 10200..10500
    ssh:
        host: null
        port: null
        private_key_path: null
        username: vagrant
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'
    vagrant:
        host: detect
server:
    install: '1'
    packages:
        - vim
users_groups:
    install: '1'
    groups:
        - vagrant
    users:
        - vagrant
cron:
    install: '1'
    jobs: {  }
firewall:
    install: '1'
    rules: null
apache:
    install: '1'
    settings:
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - rewrite
        - deflate
        - headers
    vhosts:
        0x2fuk7gsoep:
            servername: teasersite.mgr.local.dev.com
            serveraliases:
                - teasersite.mgr.local.dev.com
            docroot: /var/www/teaser_site/mgr/app/webroot
            port: '80'
            setenv:
                - 'APP_ENV dev'
            directories:
                j1i8zpsutc5r:
                    provider: directory
                    path: /var/www/teaser_site/mgr/app/webroot
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - all
                        - granted
                    custom_fragment: ''
            engine: php
            custom_fragment: ''
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
        3mayjfaesyfm:
            servername: teasersite.local.dev.com
            serveraliases:
                - teasersite.local.dev.com
            docroot: /var/www/teaser_site/web/app/webroot
            port: '80'
            setenv:
                - 'APP_ENV dev'
            directories:
                p7lispxmf6m0:
                    provider: directory
                    path: ''
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - all
                        - granted
                    custom_fragment: ''
            engine: php
            custom_fragment: ''
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
    mod_pagespeed: '0'
nginx:
    install: '0'
    settings:
        default_vhost: 1
        proxy_buffer_size: 128k
        proxy_buffers: '4 256k'
    upstreams: {  }
    vhosts:
        l6s33zpmismr:
            proxy: ''
            server_name: awesome.dev
            server_aliases:
                - www.awesome.dev
            www_root: /var/www/awesome
            listen_port: '80'
            location: \.php$
            index_files:
                - index.html
                - index.htm
                - index.php
            envvars:
                - 'APP_ENV dev'
            engine: php
            client_max_body_size: 1m
            ssl_cert: ''
            ssl_key: ''
php:
    install: '1'
    version: '54'
    composer: '1'
    composer_home: ''
    modules:
        php:
            - cli
            - intl
            - mcrypt
            - mysql
            - curl
            - cgi
            - memcache
            - memcached
        pear: {  }
        pecl:
            - pecl_http
            - APC
            - memcache
            - memcached
    ini:
        display_errors: On
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
    timezone: Asia/Tokyo
    mod_php: 0
hhvm:
    install: '0'
    nightly: 0
    composer: '1'
    composer_home: ''
    settings:
        host: 127.0.0.1
        port: '9000'
    ini:
        display_errors: On
        error_reporting: '-1'
    timezone: null
xdebug:
    install: '1'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
xhprof:
    install: '0'
wpcli:
    install: '0'
    version: v0.17.1
drush:
    install: '0'
    version: 6.3.0
ruby:
    install: '1'
    versions:
        bDdUPGaCDHWW:
            version: ''
nodejs:
    install: '0'
    npm_packages: {  }
python:
    install: '1'
    packages: {  }
    versions:
        C8DglIq6WmBq:
            version: ''
mysql:
    install: '1'
    override_options: {  }
    root_password: password
    adminer: 0
    databases:
        VQbfjPSVcdcF:
            grant:
                - ALL
            name: teaser_site
            host: localhost
            user: teaser_site
            password: password
            sql_file: ''
        6WN60Kr3GF8F:
            grant:
                - ALL
            name: mail
            host: localhost
            user: teaser_site
            password: password
            sql_file: ''
postgresql:
    install: '0'
    settings:
        root_password: '123'
        user_group: postgres
        encoding: UTF8
        version: '9.3'
    databases: {  }
    adminer: 0
mariadb:
    install: '0'
    override_options: {  }
    root_password: '123'
    adminer: 0
    databases: {  }
    version: '10.0'
sqlite:
    install: '0'
    adminer: 0
    databases: {  }
mongodb:
    install: '0'
    settings:
        auth: 1
        port: '27017'
    databases: {  }
redis:
    install: '0'
    settings:
        conf_port: '6379'
mailcatcher:
    install: '0'
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '1080'
        mailcatcher_path: /usr/local/rvm/wrappers/default
        from_email_method: inline
beanstalkd:
    install: '0'
    settings:
        listenaddress: 0.0.0.0
        listenport: '13000'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: 0
    binlogdir: /var/lib/beanstalkd/binlog
rabbitmq:
    install: '0'
    settings:
        port: '5672'
elastic_search:
    install: '0'
    settings:
        version: 1.4.1
        java_install: true
solr:
    install: '0'
    settings:
        version: 4.10.2
        port: '8984'

**Comment by jtreminio** [comment]
Please try again. Sometimes repo servers have issues with packages:

`WARNING: The following packages cannot be authenticated!
libssl1.0.0 libssl-dev`
