### ISSUE TITLE
keyserver.ubuntu.com might not work if firewall rules do not allow

### ISSUE THREAD

**Issue by exuperok** [puphpet/puphpet#1373]
Hello i was setting up a new vagrant box at work and the vagrant up process kept failing when the puppet provisioning tried to execute "sudo apt-key adv --keyserver keyserver.ubuntu.com --recv 7F0CEB10" command  prior to installing mongodb. 

After analysing the issue with a very patient ops (networking and system engineer) at my place of work, it came to the conclusion that, our corporate networking conf did not allow the sudo apt-key adv --keyserver keyserver.ubuntu.com --recv 7F0CEB10. 

We tried the same command by appending 'keyserver.ubuntu.com' with ':80' and it worked to go around the corporate firewall.

Since in most puppet files keyserver is always referenced as 'keyserver.ubuntu.com:80', imho it should be ok to make it a standard in all putpet files.

**Comment by jtreminio** [comment]
Paste your output of where you saw this issue - I've updated it everyone that I know of!

**Comment by exuperok** [comment]
i do not have the issue anymore since i made this modification on my machine. The only line have saved of the output that i did save is this one.
==> default: Error: apt-key adv --keyserver 'keyserver.ubuntu.com'  --recv-keys '9ECBEC467F0CEB10' returned 2 instead of one of [0]

**Comment by exuperok** [comment]
whenever needed i replaced keyserver.ubuntu.com by hkp://keyserver.ubuntu.com:80 and it works fine!
