### ISSUE TITLE
Large base box option?

### ISSUE THREAD

**Issue by stevenmusumeche** [puphpet/puphpet#1375]
I'm trying to use Puphpet (AWESOME tool) to setup my development environment using the CentOS box.  However, it only has 20GB of storage, and I need more than that for my database, etc.  Is there a way to use Puphpet with a different base box?  I tried using a basic puppetlabs CentOS box but got errors about guest additions not being available on it.

**Comment by jtreminio** [comment]
Sure you can make your own box here: https://github.com/puphpet/packer-templates

**Comment by stevenmusumeche** [comment]
Thank you sir.  I'm not sure if this is the best place to post this, but I was able to get this going and see the VM installing CentOS, but got the following error: Error waiting for SSH: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none password], no supported methods remain

**Comment by stevenmusumeche** [comment]
ping @jtreminio
