### ISSUE TITLE
apache2 fails to start with smb shared folder

### ISSUE THREAD

**Issue by csiewert** [puphpet/puphpet#1376]
Hi,

I'm trying to get vagrant running. On Windows Host it fails, if I use "smb" shared folder mechanism. Under mac/linux we are using nfs with the same config and its working fine. On windows hosts the "default" share mechanism is working fine, but if we use smb we get an error:

`==> default: Notice: /Stage[main]/Apache::Default_mods/Apache::Mod[authz_user]/File[authz_user.load symlink]/target: target changed '../mods-available/authz_user.load' to '/etc/apache2/mods-available/authz_user.load'
==> default: Info: /Stage[main]/Apache::Default_mods/Apache::Mod[authz_user]/File[authz_user.load symlink]: Scheduling refresh of Service[httpd]
==> default: Notice: /Stage[main]/Apache/File[/etc/apache2/mods-enabled/mpm_event.conf]/ensure: removed
==> default: Notice: /Stage[main]/Apache/File[/etc/apache2/mods-enabled/status.load]/ensure: removed
==> default: Notice: /Stage[main]/Apache/File[/etc/apache2/mods-enabled/status.conf]/ensure: removed
==> default: Notice: /Stage[main]/Apache/File[/etc/apache2/mods-enabled/mpm_event.load]/ensure: removed
==> default: Info: /etc/apache2/mods-enabled: Scheduling refresh of Class[Apache::Service]
==> default: Info: Class[Apache::Service]: Scheduling refresh of Service[httpd]
==> default: Notice: /Stage[main]/Main/File[/var/run/apache2/ssl_mutex]: Dependency File[/var/www] has failures: true
==> default: Warning: /Stage[main]/Main/File[/var/run/apache2/ssl_mutex]: Skipping because of failed dependencies
==> default: Notice: /Stage[main]/Puphpet::Ssl_cert/Package[ssl-cert]: Dependency File[/var/www] has failures: true
==> default: Warning: /Stage[main]/Puphpet::Ssl_cert/Package[ssl-cert]: Skipping because of failed dependencies
==> default: Notice: /Stage[main]/Puphpet::Ssl_cert/Exec[make-ssl-cert generate-default-snakeoil --force-overwrite]: Dependency File[/var/www] has failures: true
==> default: Warning: /Stage[main]/Puphpet::Ssl_cert/Exec[make-ssl-cert generate-default-snakeoil --force-overwrite]: Skipping because of failed dependencies
==> default: Notice: /Stage[main]/Apache::Service/Service[httpd]: Dependency File[/var/www] has failures: true
==> default: Warning: /Stage[main]/Apache::Service/Service[httpd]: Skipping because of failed dependencies
==> default: Error: /Stage[main]/Apache::Service/Service[httpd]: Failed to call refresh: Could not start Service[httpd]: Execution of '/etc/init.d/apache2 start' returned 1:
==> default: Error: /Stage[main]/Apache::Service/Service[httpd]: Could not start Service[httpd]: Execution of '/etc/init.d/apache2 start' returned 1:
==> default: Info: Creating state file /var/lib/puppet/state/state.yaml
==> default: Notice: Finished catalog run in 702.75 seconds
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.`

If I ssh into the machine and start apache2 manually it says:

`[09:49 AM]-[vagrant@packer-virtualbox-iso-1422588891]-[~] B
B$ sudo /etc/init.d/apache2 start
[FAIL] Starting web server: apache2 failed!
[warn] The apache2 configtest failed. ... (warning).
Output of config test was:
apache2: Syntax error on line 46 of /etc/apache2/apache2.conf: No matches for the wildcard '*' in '/etc/apache2/sites-enabled', failing (use IncludeOptional if required)
Action 'configtest' failed.
The Apache error log may have more information.`

`/etc/apache/sites-enabled` is an empty directory btw, but we configured vhosts on puphpet.

Can you please help us? :'( I'll try with nginx now and see what happens...

**Update:** With nginx, its working like a charm.

**Comment by jtreminio** [comment]
If you still need help, I need your config.yaml. Open a new ticket if you'd like me to take a look.
