### ISSUE TITLE
Apache should run as "vagrant" user

### ISSUE THREAD

**Issue by fain182** [puphpet/puphpet#138]
Actually all the files mounted are owned by the user vagrant, so if I need to upload some files in a directory or manage a cache of files Apache can't do it.

I think the best workaround to this problem is to run apache as user "vagrant".

**Comment by pboethig** [comment]
In Case, that you dont see any cookie named "frontend" or "adminhtml", wenn you reload the page, the magento cookie wasnt set. In my case I have a wrong cookie_domain. I used "null" instead of "NULL".

As I set my cookie_domain to NULL in core_config_data, the problem was solved
