### ISSUE TITLE
xdebug php ini not symlinked properly

### ISSUE THREAD

**Issue by smichaelsen** [puphpet/puphpet#1381]
My xdebug ini settings are not applied. Here is a snippet from the output of the provisioning process:

    ==> default: Info: Php::Augeas[CUSTOM/error_reporting--1]: Scheduling refresh of Service[php5-fpm]
    ==> default: Error: Could not set 'link' on ensure: No such file or directory - /etc/php5/conf.d at 206:/tmp/vagrant-puppet-4/modules-0/puphpet/manifests/php/ini.pp
    ==> default: Error: Could not set 'link' on ensure: No such file or directory - /etc/php5/conf.d at 206:/tmp/vagrant-puppet-4/modules-0/puphpet/manifests/php/ini.pp
    ==> default: Wrapped exception:
    ==> default: No such file or directory - /etc/php5/conf.d
    ==> default: Error: /Stage[main]/Main/Puphpet::Php::Ini[cgi.fix_pathinfo]/File[/etc/php5/conf.d/zzzz_custom.ini]/ensure: change from absent to link failed: Could not set 'link' on ensure: No such file or directory - /etc/php5/conf.d at 206:/tmp/vagrant-puppet-4/modules-0/puphpet/manifests/php/ini.pp

`config.yaml`

    ---
    vagrantfile-local:
        vm:
            box: puphpet/ubuntu1404-x64
            box_url: puphpet/ubuntu1404-x64
            hostname: ''
            memory: '512'
            cpus: '1'
            chosen_provider: parallels
            network:
                private_network: 192.168.58.101
                forwarded_port:
                    SxNOG1Ll2AXs:
                        host: '6260'
                        guest: '22'
            post_up_message: ''
            provider:
                virtualbox:
                    modifyvm:
                        natdnshostresolver1: on
                vmware:
                    numvcpus: 1
                parallels:
                    cpus: 1
            provision:
                puppet:
                    manifests_path: puphpet/puppet
                    manifest_file: site.pp
                    module_path: puphpet/puppet/modules
                    options:
                        - '--verbose'
                        - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
                        - '--parser future'
            synced_folder:
                rfkbuaJMGbxH:
                    owner: www-data
                    group: www-data
                    source: ./
                    target: /var/www
                    sync_type: nfs
                    rsync:
                        args:
                            - '--verbose'
                            - '--archive'
                            - '-z'
                        exclude:
                            - .vagrant/
                        auto: 'false'
            usable_port_range:
                start: 10200
                stop: 10500
        ssh:
            host: null
            port: null
            private_key_path: null
            username: vagrant
            guest_port: null
            keep_alive: true
            forward_agent: false
            forward_x11: false
            shell: 'bash -l'
        vagrant:
            host: detect
    server:
        install: '1'
        packages:
            - vim
            - imagemagick
    users_groups:
        install: '1'
        groups: {  }
        users: {  }
    cron:
        install: '1'
        jobs: {  }
    firewall:
        install: '1'
        rules: null
    apache:
        install: '1'
        settings:
            user: www-data
            group: www-data
            default_vhost: true
            manage_user: false
            manage_group: false
            sendfile: 0
        modules:
            - rewrite
        vhosts:
            h3xphr4nyzgo:
                servername: test.dev
                docroot: /var/www/test
                port: '80'
                setenv:
                    - 'APP_ENV dev'
                directories:
                    l9n4soayxvhz:
                        provider: directory
                        path: /var/www/projects/test
                        options:
                            - Indexes
                            - FollowSymlinks
                            - MultiViews
                        allow_override:
                            - All
                        require:
                            - all
                            - granted
                        custom_fragment: ''
                engine: php
                custom_fragment: ''
                ssl_cert: ''
                ssl_key: ''
                ssl_chain: ''
                ssl_certs_dir: ''
        mod_pagespeed: 0
    nginx:
        install: '0'
        settings:
            default_vhost: 1
            proxy_buffer_size: 128k
            proxy_buffers: '4 256k'
        upstreams: {  }
        vhosts:
            mv91gpsy6kuy:
                proxy: ''
                server_name: awesome.dev
                server_aliases:
                    - www.awesome.dev
                www_root: /var/www/awesome
                listen_port: '80'
                location: \.php$
                index_files:
                    - index.html
                    - index.htm
                    - index.php
                envvars:
                    - 'APP_ENV dev'
                engine: php
                client_max_body_size: 1m
                ssl_cert: ''
                ssl_key: ''
    php:
        install: '1'
        version: '54'
        composer: '1'
        composer_home: ''
        modules:
            php:
                - cli
                - curl
                - gd
                - intl
                - mcrypt
            pear: {  }
            pecl:
                - pecl_http
        ini:
            display_errors: On
            error_reporting: '-1'
            session.save_path: /var/lib/php/session
            upload_max_filesize: 64M
            post_max_size: 64M
            max_execution_time: '240'
        timezone: Europe/Berlin
        mod_php: 0
    hhvm:
        install: '0'
        nightly: 0
        composer: '1'
        composer_home: ''
        settings:
            host: 127.0.0.1
            port: '9000'
        ini:
            display_errors: On
            error_reporting: '-1'
        timezone: null
    xdebug:
        install: '1'
        settings:
            xdebug.default_enable: '1'
            xdebug.remote_autostart: '0'
            xdebug.remote_connect_back: '1'
            xdebug.remote_enable: '1'
            xdebug.remote_handler: dbgp
            xdebug.remote_port: '9000'
            xdebug.max_nesting_level: '400'
    xhprof:
        install: '0'
    wpcli:
        install: '0'
        version: v0.17.1
    drush:
        install: '0'
        version: 6.3.0
    ruby:
        install: '1'
        versions:
            Rd2D2BaEzv4M:
                version: 1.9.3
                gems:
                    - compass
                    - zurb-foundation
    nodejs:
        install: '1'
        npm_packages:
            - less
            - grunt-cli
    python:
        install: '1'
        packages: {  }
        versions:
            C3wTjaXSMvab:
                version: ''
    mysql:
        install: '1'
        override_options: {  }
        root_password: '123'
        adminer: 0
        databases:
            jgMK5OYouMwS:
                grant:
                    - ALL
                name: test
                host: localhost
                user: test
                password: '123'
                sql_file: /var/www/files/sqlDumps/test.sql
    postgresql:
        install: '0'
        settings:
            root_password: '123'
            user_group: postgres
            encoding: UTF8
            version: '9.3'
        databases: {  }
        adminer: 0
    mariadb:
        install: '0'
        override_options: {  }
        root_password: '123'
        adminer: 0
        databases: {  }
        version: '10.0'
    sqlite:
        install: '0'
        adminer: 0
        databases: {  }
    mongodb:
        install: '0'
        settings:
            auth: 1
            port: '27017'
        databases: {  }
    redis:
        install: '0'
        settings:
            conf_port: '6379'
    mailcatcher:
        install: '1'
        settings:
            smtp_ip: 0.0.0.0
            smtp_port: 1025
            http_ip: 0.0.0.0
            http_port: '1080'
            mailcatcher_path: /usr/local/rvm/wrappers/default
            from_email_method: inline
    beanstalkd:
        install: '0'
        settings:
            listenaddress: 0.0.0.0
            listenport: '13000'
            maxjobsize: '65535'
            maxconnections: '1024'
            binlogdir: /var/lib/beanstalkd/binlog
            binlogfsync: null
            binlogsize: '10485760'
        beanstalk_console: 0
        binlogdir: /var/lib/beanstalkd/binlog
    rabbitmq:
        install: '0'
        settings:
            port: '5672'
    elastic_search:
        install: '0'
        settings:
            version: 1.4.1
            java_install: true
    solr:
        install: '0'
        settings:
            version: 4.10.2
            port: '8984'

Any help is appreciated

**Comment by smichaelsen** [comment]
It fails to set the symlink for the custom php ini file. This is a quick fix you can execute in the machine after provisioning:

    $ cd /etc/php5/fpm/conf.d/
    $ sudo ln -s ../../mods-available/zzzz_custom.ini 90-zzzz-custom.ini

**Comment by rfanjul** [comment]
I have the same issue, but still not working for me

**Comment by smichaelsen** [comment]
do you have the file `/etc/php5/mods-available/zzzz_custom.ini` available in your VM?

**Comment by rfanjul** [comment]
Yes I have it 
```
$ ls -la /etc/php5/mods-available/zzzz_custom.ini 
-rw-r--r-- 1 root root 418 Feb 21 09:00 /etc/php5/mods-available/zzzz_custom.ini
```

**Comment by jtreminio** [comment]
Ubuntu 14.04 does not support PHP 5.4
