### ISSUE TITLE
Languages section should not propose php 5.4 when the distribution does not support it

### ISSUE THREAD

**Issue by redgluten** [puphpet/puphpet#1385]
I encountered an issue when modifying an old config.yaml to use PHP 5.4: the previous config used Ubuntu 14 + PHP and 5.6 the one I was trying to make had to be on 5.4 so I just jumped to the Languages section and chose 5.4. But after a `vagrant up` I discovered that PHP 5.5 had been installed because the distribution was still Ubuntu 14.

Ideally there should be a warning explaining that 5.4 isn’t available with the current distribution choice.

**Comment by jtreminio** [comment]
No longer applicable. All supposed distros support all PHP versions.
