### ISSUE TITLE
System Ruby is overwritten

### ISSUE THREAD

**Issue by ikari7789** [puphpet/puphpet#1389]
I'm currently using Puphpet with CentOS and it appears to overwrite the system ruby when it installs RVM. This is not a desired situation. If you switch back to system ruby, it is no longer able to be found.

To fix this, I needed to switch back to system ruby, remove it from yum, then reinstall it.
```rvm use system && sudo yum remove -y ruby && sudo yum install -y ruby facter```

I'm not sure if this is the desired action (to overwrite system ruby), but it is not advised as it can break other system tools. I'm also not sure if this is a problem due to RVM or not.

**Comment by jtreminio** [comment]
Hi,

This is by design. CentOS ships with Ruby 1.8.3 (iirc), Debian and Ubuntu with others. I needed a way to standardize all the boxes so it would be easier to maintain them.

Have you encountered any issues?

**Comment by ikari7789** [comment]
I was encountering errors while trying to use Ansible and accessing the VM. It's unable to run facter properly. I understand the need to standardized the installed Ruby, but wouldn't it be appropriate to have RVM handle the switching rather than overwriting the system default? Otherwise, if you are overwriting Ruby temporarily in order to install RVM, perhaps installing it first to /opt (or some other isolated location) and then deleting it after installation could be a viable option.

**Comment by jtreminio** [comment]
Mind giving me more details so I can attempt to replicate?

Ansible should be using the RVM-provided ruby, maybe something's up that I can fix.
