### ISSUE TITLE
How to install and enable "libapache2-mod-php5"?

### ISSUE THREAD

**Issue by pjcvijay** [puphpet/puphpet#1398]
I have been trying to figure out to install and enable the module "libapache2-mod-php5", it looks like puphpet.com does not list the module to choose from. Can please guide me to fix it?

**Comment by jtreminio** [comment]
![image](https://cloud.githubusercontent.com/assets/589398/6463910/0e867356-c17c-11e4-895b-1a3a40be51fa.png)

**Comment by pjcvijay** [comment]
Thanks for the quick response!
