### ISSUE TITLE
The SSH command responded with a non-zero exit status.

### ISSUE THREAD

**Issue by tovletoglou** [puphpet/puphpet#1399]
The SSH command responded with a non-zero exit status. Vagrant assumes that this means the command failed.

Without synced folder `synced_folder: {  }` it shows me this error,
but when I add synced folder it works fine

    synced_folder:
            vMUHZLZeS7Sl:
                owner: www-data
                group: www-data
                source: ./
                target: /var/www
                sync_type: default
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    exclude:
                        - .vagrant/
                    auto: 'false'

part of config.yaml

    ---
    vagrantfile-local:
        vm:
            box: puphpet/centos65-x64
            box_url: puphpet/centos65-x64
            hostname: ''
            memory: '2048'
            cpus: '2'
            chosen_provider: virtualbox
            network:
                private_network: 192.168.56.101
                forwarded_port:
                    AcfkKqTKrZg5:
                        host: '5601'
                        guest: '22'
            post_up_message: ''
            provider:
                virtualbox:
                    modifyvm:
                        natdnshostresolver1: on
                vmware:
                    numvcpus: 1
                parallels:
                    cpus: 1
            provision:
                puppet:
                    manifests_path: puphpet/puppet
                    manifest_file: site.pp
                    module_path: puphpet/puppet/modules
                    options:
                        - '--verbose'
                        - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
                        - '--parser future'
            synced_folder:
                vMUHZLZeS7Sl:
                    owner: www-data
                    group: www-data
                    source: ./
                    target: /var/www
                    sync_type: default
                    rsync:
                        args:
                            - '--verbose'
                            - '--archive'
                            - '-z'
                        exclude:
                            - .vagrant/
                        auto: 'false'
            usable_port_range:
                start: 10200
                stop: 10500
        ssh:
            host: null
            port: null
            private_key_path: null
            username: vagrant
            guest_port: null
            keep_alive: true
            forward_agent: false
            forward_x11: false
            shell: 'bash -l'
        vagrant:
            host: detect
    server:
        install: '1'
        packages:
            - vim-common
            - htop
            - git
    users_groups:
        install: '1'
        groups: {  }
        users: {  }
    cron:
        install: '1'
        jobs: {  }
    firewall:
        install: '1'
        rules: {  }

**Comment by jtreminio** [comment]
Can you run `$ vagrant up --debug` and paste output?

**Comment by tovletoglou** [comment]
Log file `$ vagrant up --debug`: https://dl.dropboxusercontent.com/u/16546647/vagrant.log

**Comment by jtreminio** [comment]
DEBUG ssh: Sending SSH keep-alive...
    DEBUG ssh: stderr: Error: Could not find package php-curl
    Error: /Stage[main]/Main/Php_mod[curl]/Puphpet::Php::Module[curl]/Php::Module[curl]/Package[PhpModule_curl]/ensure: change from absent to present failed: Could not find package php-curl

php-curl is already present and enabled by default in the repo PHPs.
