### ISSUE TITLE
Composer error if only HHVM installed on CentOS

### ISSUE THREAD

**Issue by jensschulze** [puphpet/puphpet#1401]
Upping a CentOS box with HHVM and composer raises the following error:
"Error: curl -s http://getcomposer.org/installer | php returned 1 instead of one of [0]"
The puppet files in puphpet/puppet/modules/composer only take in account the OSes, maybe you should also check if HHVM or PHP is installed.

I’m using the most recent CentOS box and a newly generated puphpet configuration, didn’t test on other OSes.

**Comment by jtreminio** [comment]
It's not a composer problem, it seems to be with HHVM:

    [01:20 AM]-[vagrant@localhost]-[~]
    $ hhvm --version
    HipHop VM 3.2.0 (rel)
    Compiler: tags/HHVM-3.2.0-0-g01228273b8cf709aacbd3df1c51b1e690ecebac8
    Repo schema: c52ba40f4a246d35a88f1dfc1daf959851ced8aa
    
    [01:20 AM]-[vagrant@localhost]-[~]
    $ curl -s http://getcomposer.org/installer | php
    All settings correct for using Composer
    Downloading...
    Download failed: Failed to open https://getcomposer.org/composer.phar (Unknown cipher in list: ALL)
    Downloading...
    Download failed: Failed to open https://getcomposer.org/composer.phar (Unknown cipher in list: ALL)
    Downloading...
    Download failed: Failed to open https://getcomposer.org/composer.phar (Unknown cipher in list: ALL)
    The download failed repeatedly, aborting.
    
    [01:20 AM]-[vagrant@localhost]-[~]
    $ php -r 'readfile("https://www.google.co.uk/");'
    
    Warning: Failed to open https://www.google.co.uk/ (Unknown cipher in list: ALL) in /tmp/php-wrap-sfCjf0 on line 2
