### ISSUE TITLE
MySQL override_options in config.yaml

### ISSUE THREAD

**Issue by rockitdev** [puphpet/puphpet#1404]
Trying to understand how to override options in my config.yaml file.

Based on puppet/modules/mysql/README.md

```puppet
$override_options = {
  'section' => {
    'item'             => 'thing',
  }
}
```

For items that you would traditionally represent as:

<pre>
[section]
thing = X
</pre>

You can just make an entry like `thing => true`, `thing => value`, or `thing => "` in the hash. You can also pass an array `thing => ['value', 'value2']` or even list each `thing => value` separately on separate lines. MySQL doesn't care if 'thing' is alone or set to a value; it'll happily accept both.  To keep an option out of the my.cnf file, e.g. when using override_options to revert to a default value, you can pass thing => undef.

So, in my config.yaml

I tried the following:

mysql:
    install: '1'
    override_options: {  
		'mysqld' => {
			'max_binlog_size' => '101M',
		}
	}
....

Just to see how i can adjust my.cnf settings. Keep getting the error 

Path: D:/Web/commons.dev/Vagrantfile
Message: (D:/Web/commons.dev/puphpet/config.yaml): did not find expected ',' or
'}' while parsing a flow mapping at line 213 column 23

For reference, line 213 column 23 is the position following: override_options: {

Is this feature supported? i would ideally like to enable the slow query log in my config.

**Comment by pascal-larocque** [comment]
This is the correct Syntax

mysql:
    install: '1'
        override_options: 
            mysqld:
                max_binlog_size: 101M

**Comment by marcosgdf** [comment]
But they won't work. See bug #1303

**Comment by jtreminio** [comment]
You can create an exec-always bash script to run after every `$ vagrant up` and `$ vagrant provision`.
