### ISSUE TITLE
VHost shows `^M` and how do I get rid of it?

### ISSUE THREAD

**Issue by eswarams** [puphpet/puphpet#1407]
Hi,
I created a new puphpet file with Alias setup on "Custome Device (outside <directory> block)" section under Webservers tab and Installed VM in my machine. Configured the VM with puphpet file and gave vagrant up and I couldn't run the site via browser in my VM. Ex: http://example.dev

I found the unknown character "^M" is there vhost conf file at the end of Alias line from /etc/apache2/sites-enabled directory.

How to get rid of it? Please check the attached images for your review.

Thanks!

![puphpet](https://cloud.githubusercontent.com/assets/154304/6525613/85915bc4-c42d-11e4-8d31-295182b2cea6.png)
![config-yaml](https://cloud.githubusercontent.com/assets/154304/6525614/8591e788-c42d-11e4-998f-ae1f1cc854c9.png)
![vhost-conf](https://cloud.githubusercontent.com/assets/154304/6525612/858e91aa-c42d-11e4-92c4-c02d2d98b294.png)

**Comment by eswarams** [comment]
Hi Juan,
I reviewed your fixed for #1407. But, I don't have that mentioned puphpet directory in my VM. How can I add it?

And, I manually removed the "\r" character in config.yaml file and it works for me.

**Comment by jtreminio** [comment]
`puphpet/puppet/modules/puphpet`

**Comment by eswarams** [comment]
I don't have any php files on mentioned directory. Please explain, how to fix that character issue?
