### ISSUE TITLE
 $ puppet agent -t =>  Error: Could not request certificate: getaddrinfo: Name or service not known

### ISSUE THREAD

**Issue by fvdb06** [puphpet/puphpet#1408]
After I mad-up a new PuPHPet instance I get the Error: Could not request certificate: getaddrinfo: Name or service not known after the command puppet agent -t
what's going wrong?

**Comment by jtreminio** [comment]
PuPHPet manifests need extra flags to be run manually without Vagrant.

Something like this:

FACTER_ssh_username='vagrant' FACTER_provisioner_type='virtualbox' \
    FACTER_vm_target_key='vagrantfile-local' puppet apply --verbose \
    --hiera_config /etc/puppet/hiera.yaml --parser future \
    --modulepath '/etc/puppet/modules' \
    --detailed-exitcodes /etc/puppet/site.pp \

However, I will not provide support for this method.

**Comment by fvdb06** [comment]
Thanks for the solution. Indeed, I made a full clone and started the new VM directly without Vagrant.

**Comment by garcsl** [comment]
Run **puppet agent -t** using elevated privileges
