### ISSUE TITLE
HHVM: Use ini files

### ISSUE THREAD

**Issue by jtreminio** [puphpet/puphpet#1424]
The command HHVM service uses is

    /usr/bin/hhvm --config /etc/hhvm/php.ini --config /etc/hhvm/server.ini --user www-data --mode daemon -vPidFile=/var/run/hhvm/pid

supervisord uses

    hhvm --mode server -vServer.Type=fastcgi -vServer.Port=9000

Should adopt how HHVM normally does this.

Augeas is pretty bad, though, and I haven't been able to use it to parse HHVM's ini files. May be worth it to use an outside Ruby gem like https://rubygems.org/gems/iniparse

**Comment by fizz** [comment]
Hi @jtreminio, it was pretty tricky but I got php.ini working with Augeas. Here's what I did, I hope it helps:

```puppet
augeas { '/etc/hhvm/server.ini':
    require => Package['hhvm'],
    lens    => 'PHP.lns',
    incl    => '/etc/hhvm/server.ini',
    context => '/files/etc/hhvm/server.ini/.anon',
    changes => [
      'set include_path /var/www/blabla:/var/www/something',
      'set display_errors Off',
      'set error_reporting -1',
      'set short_open_tag On',
      'set expose_php Off',
      'set date.timezone US/Central',
    ],
    notify => Service['hhvm'],
}
```

**Comment by fizz** [comment]
- `.anon` in the context is important, it stops augeas from adding pointless section headings to the file.
- I don't remember if I had to install anything cuz it took me a while messing around and I installed quite a few things , but the lens "PHP.lns" may have required me to install augeas-lenses (Debian package).

**Comment by jtreminio** [comment]
Thanks @fizz I'll incorporate that

**Comment by fizz** [comment]
7e19e75 made my day :+1:
