### ISSUE TITLE
Server works for a few minutes then apache/MySQL stop responding

### ISSUE THREAD

**Issue by whistletutor** [puphpet/puphpet#1427]
I've created a server which starts up fine and I can browse to the web server and access MySQL through Adminer -- for a few minutes. Then I get connection time-out errors and am forced to <em>vagrant halt</em> and <em>vagrant up</em> again. This server was working great until, for some reason, I started getting session errors which caused me to <em>vagrant destroy</em> and rebuild. 

Curiously, I can still ping the domain name (which I've mapped locally using my hosts file) and I can also <em>vagrant ssh</em> into the box as needed. Furthermore, I can access the /var/www/html/index.html page by browsing to the IP address, indicating that Apache is actually running properly.

Here's my config.yaml:

    ---
    vagrantfile-local:
        vm:
            box: puphpet/centos65-x64
            box_url: puphpet/centos65-x64
            hostname: ''
            memory: '1024'
            cpus: '1'
            chosen_provider: vmware_fusion
            network:
                private_network: 172.16.44.130
                forwarded_port:
                    NGb9G9AKiieA:
                        host: '7105'
                        guest: '22'
            post_up_message: ''
            provider:
                virtualbox:
                    modifyvm:
                        natdnshostresolver1: on
                vmware:
                    numvcpus: 1
                parallels:
                    cpus: 1
            provision:
                puppet:
                    manifests_path: puphpet/puppet
                    manifest_file: site.pp
                    module_path: puphpet/puppet/modules
                    options:
                        - '--verbose'
                        - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
                        - '--parser future'
            synced_folder:
                OLYbzo4krRFL:
                    owner: www-data
                    group: www-data
                    source: '/Users/Sean/Documents/Websites/RE Lynx Git'
                    target: /var/www/relynx.dev/public_html
                    sync_type: default
                    rsync:
                        args:
                            - '--verbose'
                            - '--archive'
                            - '-z'
                        exclude:
                            - .vagrant/
                        auto: 'false'
                v2MPTOQwLJ9t:
                    owner: www-data
                    group: www-data
                    source: '/Users/Sean/Documents/Websites/Trouble Ticket v3'
                    target: /var/www/troubleticket.dev/public_html
                    sync_type: default
                    rsync:
                        auto: 'false'
            usable_port_range:
                start: 10200
                stop: 10500
        ssh:
            host: null
            port: null
            private_key_path: null
            username: vagrant
            guest_port: null
            keep_alive: true
            forward_agent: false
            forward_x11: false
            shell: 'bash -l'
        vagrant:
            host: detect
    server:
        install: '1'
        packages: {  }
    users_groups:
        install: '1'
        groups: {  }
        users: {  }
    cron:
        install: '1'
        jobs: {  }
    firewall:
        install: '1'
        rules: {  }
    apache:
        install: '1'
        settings:
            user: www-data
            group: www-data
            default_vhost: true
            manage_user: false
            manage_group: false
            sendfile: 0
        modules:
            - rewrite
        vhosts:
            imc73bzqik3f:
                servername: relynx.dev
                serveraliases:
                    - www.relynx.dev
                docroot: /var/www/relynx.dev/public_html
                port: '80'
                setenv:
                    - 'APP_ENV dev'
                directories:
                    1qhlbhns5682:
                        provider: directory
                        path: /var/www/relynx.dev/public_html
                        options:
                            - Indexes
                            - FollowSymlinks
                            - MultiViews
                        allow_override:
                            - All
                        require:
                            - all
                            - granted
                        custom_fragment: ''
                engine: php
                custom_fragment: ''
                ssl_cert: ''
                ssl_key: ''
                ssl_chain: ''
                ssl_certs_dir: ''
            iawfvimtqhj3:
                servername: troubleticket.dev
                serveraliases:
                    - www.troubleticket.dev
                docroot: /var/www/troubleticket.dev/public_html
                port: '80'
                directories:
                    nzkzsjt6eeuh:
                        provider: directory
                        path: ''
                        options:
                            - Indexes
                            - FollowSymlinks
                            - MultiViews
                        allow_override:
                            - All
                        require:
                            - all
                            - granted
                        custom_fragment: ''
                engine: php
                custom_fragment: ''
                ssl_cert: ''
                ssl_key: ''
                ssl_chain: ''
                ssl_certs_dir: ''
        mod_pagespeed: 0
    nginx:
        install: '0'
        settings:
            default_vhost: 1
            proxy_buffer_size: 128k
            proxy_buffers: '4 256k'
        upstreams: {  }
        vhosts:
            risjadwc5osq:
                proxy: ''
                server_name: awesome.dev
                server_aliases:
                    - www.awesome.dev
                www_root: /var/www/awesome
                listen_port: '80'
                location: \.php$
                index_files:
                    - index.html
                    - index.htm
                    - index.php
                envvars:
                    - 'APP_ENV dev'
                engine: php
                client_max_body_size: 1m
                ssl_cert: ''
                ssl_key: ''
    php:
        install: '1'
        version: '56'
        composer: '1'
        composer_home: ''
        modules:
            php:
                - cli
                - intl
                - mcrypt
            pear: {  }
            pecl:
                - pecl_http
        ini:
            display_errors: On
            error_reporting: '-1'
            session.save_path: /var/lib/php/session
        timezone: America/Chicago
        mod_php: 0
    hhvm:
        install: '0'
        nightly: 0
        composer: '1'
        composer_home: ''
        settings:
            host: 127.0.0.1
            port: '9000'
        ini:
            display_errors: On
            error_reporting: '-1'
        timezone: null
    xdebug:
        install: '0'
        settings:
            xdebug.default_enable: '1'
            xdebug.remote_autostart: '0'
            xdebug.remote_connect_back: '1'
            xdebug.remote_enable: '1'
            xdebug.remote_handler: dbgp
            xdebug.remote_port: '9000'
    xhprof:
        install: '0'
    wpcli:
        install: '0'
        version: v0.17.1
    drush:
        install: '0'
        version: 6.3.0
    ruby:
        install: '1'
        versions: {  }
    nodejs:
        install: '0'
        npm_packages: {  }
    python:
        install: '1'
        packages: {  }
        versions: {  }
    mysql:
        install: '1'
        settings:
            override_options: {  }
            root_password: **REMOVED**
        adminer: '1'
        databases:
            9pj8tSwHkENO:
                grant:
                    - ALL
                name: **REMOVED**
                host: localhost
                user: **REMOVED**
                password: '**REMOVED**'
                sql_file: /var/www/relynx.dev/public_html/rladmin_rladmin_2.sql
            BHfYQJD10FjP:
                grant:
                    - ALL
                name: **REMOVED**
                host: localhost
                user: **REMOVED**
                password: '**REMOVED**'
                sql_file: /var/www/relynx.dev/public_html/rladmin_rlhpsi_2.sql
    postgresql:
        install: '0'
        settings:
            root_password: '123'
            user_group: postgres
            encoding: UTF8
            version: '9.3'
        databases: {  }
        adminer: 0
    mariadb:
        install: '0'
        settings:
            override_options: {  }
            root_password: '123'
            version: '10.0'
        adminer: 0
        databases: {  }
    sqlite:
        install: '0'
        adminer: 0
        databases: {  }
    mongodb:
        install: '0'
        settings:
            auth: 1
            port: '27017'
        databases: {  }
    redis:
        install: '0'
        settings:
            conf_port: '6379'
    mailcatcher:
        install: '0'
        settings:
            smtp_ip: 0.0.0.0
            smtp_port: 1025
            http_ip: 0.0.0.0
            http_port: '1080'
            mailcatcher_path: /usr/local/rvm/wrappers/default
            from_email_method: inline
    beanstalkd:
        install: '0'
        settings:
            listenaddress: 0.0.0.0
            listenport: '13000'
            maxjobsize: '65535'
            maxconnections: '1024'
            binlogdir: /var/lib/beanstalkd/binlog
            binlogfsync: null
            binlogsize: '10485760'
        beanstalk_console: 0
        binlogdir: /var/lib/beanstalkd/binlog
    rabbitmq:
        install: '0'
        settings:
            port: '5672'
    elastic_search:
        install: '0'
        settings:
            version: 1.4.1
            java_install: true
    solr:
        install: '0'
        settings:
            version: 4.10.2
            port: '8984'

**Comment by jtreminio** [comment]
Check your error logs. I don't believe this is a puphpet issue.
