### ISSUE TITLE
value_true() error

### ISSUE THREAD

**Issue by sasos90** [puphpet/puphpet#1430]
Hy!

I am having an error on "vagrant up" that cancel my installation.
These are few last lines before the error and an error itself at the end:
Link to config.yaml: http://laravel.io/bin/yGYqD
vagrant -v: Vagrant 1.7.2

Do you know what could be the problem?

==> default: Pre-existing private key found at 'puphpet/files/dot/ssh/root_id_rsa'
==> default: Pre-existing private key found at 'puphpet/files/dot/ssh/id_rsa'
==> default: Adding generated key to /root/.ssh/id_rsa
==> default: Adding generated key to /root/.ssh/id_rsa.pub
==> default: Adding generated key to /root/.ssh/authorized_keys
==> default: Adding generated key to /home/vagrant/.ssh/id_rsa
==> default: Adding generated key to /home/vagrant/.ssh/id_rsa.pub
==> default: Adding generated key to /home/vagrant/.ssh/authorized_keys
==> default: Running provisioner: shell...
    default: Running: /tmp/vagrant-shell20150314-23944-1bf3o9n.sh
==> default: stdin: is not a tty
==> default: Running provisioner: shell...
    default: Running: /tmp/vagrant-shell20150314-23944-1rrxnug.sh
==> default: stdin: is not a tty
==> default: Running provisioner: puppet...
==> default: Running Puppet with site.pp...
==> default: stdin: is not a tty
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-245d15f576163932cfc0e7e8542538e0/stdlib/lib/facter/facter_dot_d.rb
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-245d15f576163932cfc0e7e8542538e0/stdlib/lib/facter/pe_version.rb
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-245d15f576163932cfc0e7e8542538e0/stdlib/lib/facter/puppet_vardir.rb
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-245d15f576163932cfc0e7e8542538e0/stdlib/lib/facter/root_home.rb
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-245d15f576163932cfc0e7e8542538e0/php/lib/facter/php_fact_version.rb
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-245d15f576163932cfc0e7e8542538e0/php/lib/facter/php_fact_extension_dir.rb
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-245d15f576163932cfc0e7e8542538e0/concat/lib/facter/concat_basedir.rb
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-245d15f576163932cfc0e7e8542538e0/puppi/lib/facter/windows_common_appdata.rb
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-245d15f576163932cfc0e7e8542538e0/puppi/lib/facter/last_run.rb
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-245d15f576163932cfc0e7e8542538e0/puppi/lib/facter/puppi_projects.rb
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-245d15f576163932cfc0e7e8542538e0/composer/lib/facter/composer_home.rb
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-245d15f576163932cfc0e7e8542538e0/rabbitmq/lib/facter/rabbitmq_erlang_cookie.rb
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-245d15f576163932cfc0e7e8542538e0/git/lib/facter/git_exec_path.rb
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-245d15f576163932cfc0e7e8542538e0/git/lib/facter/git_version.rb
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-245d15f576163932cfc0e7e8542538e0/firewall/lib/facter/ip6tables_version.rb
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-245d15f576163932cfc0e7e8542538e0/firewall/lib/facter/iptables_persistent_version.rb
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-245d15f576163932cfc0e7e8542538e0/firewall/lib/facter/iptables_version.rb
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-245d15f576163932cfc0e7e8542538e0/rvm/lib/facter/rvm_installed.rb
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-245d15f576163932cfc0e7e8542538e0/rvm/lib/facter/rvm_version.rb
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-245d15f576163932cfc0e7e8542538e0/staging/lib/facter/staging_http_get.rb
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-245d15f576163932cfc0e7e8542538e0/staging/lib/facter/staging_windir.rb
==> default: Error: value_true(): first value must be an array, passed String at /tmp/vagrant-puppet/manifests-893fcda21077f5a583c2dbbba8515c0a/nodes/Php.pp:164 on node packer-virtualbox-iso-1422588891.vagrantup.com
==> default: Error: value_true(): first value must be an array, passed String at /tmp/vagrant-puppet/manifests-893fcda21077f5a583c2dbbba8515c0a/nodes/Php.pp:164 on node packer-virtualbox-iso-1422588891.vagrantup.com
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

**Comment by jtreminio** [comment]
Hi, this was fixed in 4f644d97e6cabf14f62237bf7477c6e89ca8311f

Please regenerate your archive and try again.
