### ISSUE TITLE
Ability to install Apache w/o managing VHosts

### ISSUE THREAD

**Issue by nokios** [puphpet/puphpet#1434]
Would love the ability to have Puphpet install Apache w/o it maintaining vhosts.  I have applications that deploy these on their own, and puppet removes them if I re-provision the box.  should be a simple checkbox enable/disable option.

also, the option to say NO to default hosts in the UI would be nice. (it's configurable in the config.yaml file)

**Comment by jtreminio** [comment]
You want to add apache.settings.purge_configs = true:

    apache
        settings:
            purge_configs: true

Note: I can't provide support for when/if something breaks doing this.

**Comment by nokios** [comment]
Pardon my ignorance, but that seems to imply that it would clean up configs from the location.  Is there documentation on the options available? If so, I'll read up on them so I don't have to trouble you.

**Comment by jtreminio** [comment]
It's here:

https://github.com/puppetlabs/puppetlabs-apache#purge_vhost_configs

But there seems to be a bug where `purge_vhost_configs` is nowhere in their codebase. It only pays attention to `purge_configs`.

And yes, you need `purge_configs` to be false, not true. My bad.

**Comment by nokios** [comment]
Thanks for your reply!
