### ISSUE TITLE
phpmyadmin not reachable (by default)

### ISSUE THREAD

**Issue by panique** [puphpet/puphpet#144]
Puphpet says the following in the phpmyadmin section:

> If installed it will be available from http://phpmyadmin

What does this effectivly mean ? When accessing the vagrant box by `http://192.168.56.101` for example, phpmyadmin should be available at `http://192.168.56.101/phpmyadmin` (common style), but it's not. What does `http://phpmyadmin` mean ? Is this a mistake or intended ?

If intended, how to reach phpmyadmin in each box ?

**Comment by numediaweb** [comment]
None of the above solutions worked in Windows 10. Would be great that PHPmyAdmin works out of the box without any need of further configurations.

**Comment by jtreminio** [comment]
@numediaweb pma support was dropped over a year ago. It's a buggy piece of software that introduces security risks to your server.

You should seriously consider using a dedicated tool like Sequel Pro or Mysql Workbench instead.
