### ISSUE TITLE
MySQL Daemon failed to start

### ISSUE THREAD

**Issue by fvdb06** [puphpet/puphpet#1441]
I generate recently a new zip file, see below

There are problems with Mysql

MySQL Daemon failed to start.
Starting mysqld:                                           [FAILED]

---
vagrantfile-local:
    vm:
        box: puphpet/centos65-x64
        box_url: puphpet/centos65-x64
        hostname: ''
        memory: '8096'
        cpus: '4'
        chosen_provider: virtualbox
        network:
            private_network: 192.168.11.69
            forwarded_port:
                OrQrfDCN2MsX:
                    host: '80'
                    guest: '80'
                omKqvLQEdV50:
                    host: '443'
                    guest: '443'
                5ZjGLTc7XVeN:
                    host: '4200'
                    guest: '4200'
                krqoHIz9LwxM:
                    host: '10000'
                    guest: '10000'
                SgSEtlMrrBCs:
                    host: '3000'
                    guest: '3000'
                V24FX8xDDQaQ:
                    host: '8082'
                    guest: '8082'
        post_up_message: ''
        provider:
            virtualbox:
                modifyvm:
                    natdnshostresolver1: on
            vmware:
                numvcpus: 1
            parallels:
                cpus: 1
        provision:
            puppet:
                manifests_path: puphpet/puppet
                manifest_file: site.pp
                module_path: puphpet/puppet/modules
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
                    - '--parser future'
        synced_folder:
            8imN12OFWzaY:
                owner: www-data
                group: www-data
                source: ./
                target: /var/www
                sync_type: nfs
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    exclude:
                        - .vagrant/
                    auto: 'false'
        usable_port_range:
            start: 10200
            stop: 10500
    ssh:
        host: null
        port: null
        private_key_path: null
        username: vagrant
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'
    vagrant:
        host: detect
server:
    install: '1'
    packages:
        - vim-common
        - git
        - telnet
users_groups:
    install: '1'
    groups: {  }
    users: {  }
cron:
    install: '1'
    jobs: {  }
firewall:
    install: '1'
    rules:
        b2blnlVtmkN5:
            port:
                - '4200'
            priority: '100'
            proto: tcp
            action: accept
        4ImlMpgJWhIv:
            port:
                - '10000'
            priority: '100'
            proto: tcp
            action: accept
        zA8lnxh2YTqx:
            port:
                - '8082'
            priority: '100'
            proto: tcp
            action: accept
apache:
    install: '0'
    settings:
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - rewrite
    vhosts:
        3lk7untu8icr:
            servername: awesome.dev
            serveraliases:
                - www.awesome.dev
            docroot: /var/www/awesome
            port: '80'
            setenv:
                - 'APP_ENV dev'
            directories:
                xdombnnhykhv:
                    provider: directory
                    path: /var/www/awesome
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - all
                        - granted
                    custom_fragment: ''
            engine: php
            custom_fragment: ''
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
    mod_pagespeed: 0
nginx:
    install: '1'
    settings:
        default_vhost: 1
        proxy_buffer_size: 128k
        proxy_buffers: '8 256k'
    upstreams: {  }
    vhosts:
        pinkfaun.dev:
            proxy: ''
            server_name: pinkfaun.dev
            server_aliases:
                - www.pinkfaun.dev
            www_root: /var/www/pinkfaun
            listen_port: '80'
            index_files:
                - index.php
                - index.html
                - index.htm
            client_max_body_size: 1m
            locations:
                xeacamgs1qks:
                    location: /
                    try_files:
                        - $uri
                        - $uri/
                        - index.php
                    fastcgi: ''
                    fastcgi_index: ''
                    fastcgi_split_path: ''
                    fast_cgi_params_extra:
                        - 'proxy_connect_timeout       600s'
                        - 'proxy_send_timeout          600s'
                        - 'proxy_read_timeout          600s'
                        - 'send_timeout                600s'
                3aloa6w7wjdj:
                    location: '~ \.php$'
                    try_files:
                        - index.php
                        - /index.php$is_args$args
                        - 'try_files $uri =404'
                    fastcgi: '127.0.0.1:9000'
                    fastcgi_index: index.php
                    fastcgi_split_path: '^(.+\.php)(/.*)$'
                    fast_cgi_params_extra:
                        - 'SCRIPT_FILENAME $request_filename'
                        - 'APP_ENV dev'
            ssl: '1'
            ssl_cert: ''
            ssl_key: ''
            ssl_port: '443'
php:
    install: '1'
    version: '56'
    composer: '1'
    composer_home: ''
    modules:
        php:
            - cli
            - intl
            - mcrypt
            - memcache
            - memcached
            - pspell
            - tidy
            - sqlite
        pear: {  }
        pecl:
            - pecl_http
    ini:
        display_errors: On
        error_reporting: 'E_ALL & ~E_STRICT'
        session.save_path: /tmp
        date.timezone: UTC
        allow_url_fopen: '1'
        allow_url_include: '1'
        error_log: syslog
        file_uploads: '1'
        apc.enabled: '1'
    mod_php: '0'
    timezone: Europe/Amsterdam
hhvm:
    install: '0'
    nightly: 0
    composer: '1'
    composer_home: ''
    settings:
        host: 127.0.0.1
        port: '9000'
    ini:
        display_errors: On
        error_reporting: '-1'
    timezone: null
xdebug:
    install: '1'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
xhprof:
    install: '0'
wpcli:
    install: '0'
    version: v0.17.1
drush:
    install: '0'
    version: 6.3.0
ruby:
    install: '1'
    versions: {  }
nodejs:
    install: '0'
    npm_packages: {  }
python:
    install: '1'
    packages: {  }
    versions: {  }
mysql:
    install: '1'
    settings:
        override_options: {  }
        root_password: aviator666
    adminer: 0
    databases:
        c7QptB7FTPmF:
            grant:
                - ALL
            name: gavickpro_photo
            host: localhost
            user: fvdb06
            password: aviator666
            sql_file: /var/www/sql/gavickpro_photo.sql.zip
        x3k6hvgPuDgR:
            grant:
                - ALL
            name: triplem_prd
            host: localhost
            user: fvdb06
            password: aviator666
            sql_file: /var/www/sql/triplem_prd.sql
postgresql:
    install: '0'
    settings:
        root_password: '123'
        user_group: postgres
        encoding: UTF8
        version: '9.3'
    databases: {  }
    adminer: 0
mariadb:
    install: '0'
    settings:
        override_options: {  }
        root_password: '123'
        version: '10.0'
    adminer: 0
    databases: {  }
sqlite:
    install: '0'
    adminer: 0
    databases: {  }
mongodb:
    install: '0'
    settings:
        auth: 1
        port: '27017'
    databases: {  }
redis:
    install: '0'
    settings:
        conf_port: '6379'
mailcatcher:
    install: '0'
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '1080'
        mailcatcher_path: /usr/local/rvm/wrappers/default
        from_email_method: inline
beanstalkd:
    install: '0'
    settings:
        listenaddress: 0.0.0.0
        listenport: '13000'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: 0
    binlogdir: /var/lib/beanstalkd/binlog
rabbitmq:
    install: '0'
    settings:
        port: '5672'
    users: {  }
    vhosts: {  }
    plugins: {  }
elastic_search:
    install: '1'
    settings:
        version: 1.4.1
        java_install: true
solr:
    install: '0'
    settings:
        version: 4.10.2
        port: '8984'

**Comment by jtreminio** [comment]
Please repaste in code mode, or paste a link from http://pastie.org/

**Comment by fvdb06** [comment]
---
vagrantfile-local:
    vm:
        box: puphpet/centos65-x64
        box_url: puphpet/centos65-x64
        hostname: ''
        memory: '8096'
        cpus: '4'
        chosen_provider: virtualbox
        network:
            private_network: 192.168.11.69
            forwarded_port:
                OrQrfDCN2MsX:
                    host: '80'
                    guest: '80'
                omKqvLQEdV50:
                    host: '443'
                    guest: '443'
                5ZjGLTc7XVeN:
                    host: '4200'
                    guest: '4200'
                krqoHIz9LwxM:
                    host: '10000'
                    guest: '10000'
                SgSEtlMrrBCs:
                    host: '3000'
                    guest: '3000'
                V24FX8xDDQaQ:
                    host: '8082'
                    guest: '8082'
        post_up_message: ''
        provider:
            virtualbox:
                modifyvm:
                    natdnshostresolver1: on
            vmware:
                numvcpus: 1
            parallels:
                cpus: 1
        provision:
            puppet:
                manifests_path: puphpet/puppet
                manifest_file: site.pp
                module_path: puphpet/puppet/modules
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
                    - '--parser future'
        synced_folder:
            8imN12OFWzaY:
                owner: www-data
                group: www-data
                source: ./
                target: /var/www
                sync_type: nfs
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    exclude:
                        - .vagrant/
                    auto: 'false'
        usable_port_range:
            start: 10200
            stop: 10500
    ssh:
        host: null
        port: null
        private_key_path: null
        username: vagrant
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'
    vagrant:
        host: detect
server:
    install: '1'
    packages:
        - vim-common
        - git
        - telnet
users_groups:
    install: '1'
    groups: {  }
    users: {  }
cron:
    install: '1'
    jobs: {  }
firewall:
    install: '1'
    rules:
        b2blnlVtmkN5:
            port:
                - '4200'
            priority: '100'
            proto: tcp
            action: accept
        4ImlMpgJWhIv:
            port:
                - '10000'
            priority: '100'
            proto: tcp
            action: accept
        zA8lnxh2YTqx:
            port:
                - '8082'
            priority: '100'
            proto: tcp
            action: accept
apache:
    install: '0'
    settings:
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - rewrite
    vhosts:
        3lk7untu8icr:
            servername: awesome.dev
            serveraliases:
                - www.awesome.dev
            docroot: /var/www/awesome
            port: '80'
            setenv:
                - 'APP_ENV dev'
            directories:
                xdombnnhykhv:
                    provider: directory
                    path: /var/www/awesome
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - all
                        - granted
                    custom_fragment: ''
            engine: php
            custom_fragment: ''
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
    mod_pagespeed: 0
nginx:
    install: '1'
    settings:
        default_vhost: 1
        proxy_buffer_size: 128k
        proxy_buffers: '8 256k'
    upstreams: {  }
    vhosts:
        pinkfaun.dev:
            proxy: ''
            server_name: pinkfaun.dev
            server_aliases:
                - www.pinkfaun.dev
            www_root: /var/www/pinkfaun
            listen_port: '80'
            index_files:
                - index.php
                - index.html
                - index.htm
            client_max_body_size: 1m
            locations:
                xeacamgs1qks:
                    location: /
                    try_files:
                        - $uri
                        - $uri/
                        - index.php
                    fastcgi: ''
                    fastcgi_index: ''
                    fastcgi_split_path: ''
                    fast_cgi_params_extra:
                        - 'proxy_connect_timeout       600s'
                        - 'proxy_send_timeout          600s'
                        - 'proxy_read_timeout          600s'
                        - 'send_timeout                600s'
                3aloa6w7wjdj:
                    location: '~ \.php$'
                    try_files:
                        - index.php
                        - /index.php$is_args$args
                        - 'try_files $uri =404'
                    fastcgi: '127.0.0.1:9000'
                    fastcgi_index: index.php
                    fastcgi_split_path: '^(.+\.php)(/.*)$'
                    fast_cgi_params_extra:
                        - 'SCRIPT_FILENAME $request_filename'
                        - 'APP_ENV dev'
            ssl: '1'
            ssl_cert: ''
            ssl_key: ''
            ssl_port: '443'
php:
    install: '1'
    version: '56'
    composer: '1'
    composer_home: ''
    modules:
        php:
            - cli
            - intl
            - mcrypt
            - memcache
            - memcached
            - pspell
            - tidy
            - sqlite
        pear: {  }
        pecl:
            - pecl_http
    ini:
        display_errors: On
        error_reporting: 'E_ALL & ~E_STRICT'
        session.save_path: /tmp
        date.timezone: UTC
        allow_url_fopen: '1'
        allow_url_include: '1'
        error_log: syslog
        file_uploads: '1'
        apc.enabled: '1'
    mod_php: '0'
    timezone: Europe/Amsterdam
hhvm:
    install: '0'
    nightly: 0
    composer: '1'
    composer_home: ''
    settings:
        host: 127.0.0.1
        port: '9000'
    ini:
        display_errors: On
        error_reporting: '-1'
    timezone: null
xdebug:
    install: '1'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
xhprof:
    install: '0'
wpcli:
    install: '0'
    version: v0.17.1
drush:
    install: '0'
    version: 6.3.0
ruby:
    install: '1'
    versions: {  }
nodejs:
    install: '0'
    npm_packages: {  }
python:
    install: '1'
    packages: {  }
    versions: {  }
mysql:
    install: '1'
    settings:
        override_options: {  }
        root_password: aviator666
    adminer: 0
    databases:
        c7QptB7FTPmF:
            grant:
                - ALL
            name: gavickpro_photo
            host: localhost
            user: fvdb06
            password: aviator666
            sql_file: /var/www/sql/gavickpro_photo.sql.zip
        x3k6hvgPuDgR:
            grant:
                - ALL
            name: triplem_prd
            host: localhost
            user: fvdb06
            password: aviator666
            sql_file: /var/www/sql/triplem_prd.sql
postgresql:
    install: '0'
    settings:
        root_password: '123'
        user_group: postgres
        encoding: UTF8
        version: '9.3'
    databases: {  }
    adminer: 0
mariadb:
    install: '0'
    settings:
        override_options: {  }
        root_password: '123'
        version: '10.0'
    adminer: 0
    databases: {  }
sqlite:
    install: '0'
    adminer: 0
    databases: {  }
mongodb:
    install: '0'
    settings:
        auth: 1
        port: '27017'
    databases: {  }
redis:
    install: '0'
    settings:
        conf_port: '6379'
mailcatcher:
    install: '0'
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '1080'
        mailcatcher_path: /usr/local/rvm/wrappers/default
        from_email_method: inline
beanstalkd:
    install: '0'
    settings:
        listenaddress: 0.0.0.0
        listenport: '13000'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: 0
    binlogdir: /var/lib/beanstalkd/binlog
rabbitmq:
    install: '0'
    settings:
        port: '5672'
    users: {  }
    vhosts: {  }
    plugins: {  }
elastic_search:
    install: '1'
    settings:
        version: 1.4.1
        java_install: true
solr:
    install: '0'
    settings:
        version: 4.10.2
        port: '8984'

**Comment by fvdb06** [comment]
http://pastie.org/10033607

**Comment by jtreminio** [comment]
Fixed by f853b08

Note that you have a few PHP modules that won't install:

    Error: Could not find package php-memcache
    Error: Could not find package php-sqlite
    Error: Could not find package php-memcached
