### ISSUE TITLE
Old, incompatible config.yaml files should generate a warning when imported

### ISSUE THREAD

**Issue by markjaquith** [puphpet/puphpet#1444]
puphpet.com happily accepts old `config.yaml` files that it can't make sense of. The package it generates in these situations has serious operational issues. The solution is to completely start from scratch, but the user is never informed of this.

Maybe there should be some sort of sanity check on `config.yaml` when imported, and if it’s not good, the user should be told to start from scratch.

**Comment by jtreminio** [comment]
This one is a hard problem :(

How do I define incompatible? Some people add things to their `config.yaml` and add puppet code to their install. Would custom blocks trigger an incompatible warning?

You could argue that anything custom belongs in `config-custom.yaml` but the way I originally envisioned that file was to have custom values between team members, or have sensitive information you don't want checked in.

ie API keys or service passwords, etc.

I *try* to keep the config file backwards compatible at all times. Unfortunately, as I work my way through Puppet and learn more about it, I'm realizing that my original methods were insufficiently flexible.

Take the recent changes to nginx, for example.

Old style:

    nginx:
        install: '0'
        settings:
            default_vhost: 1
            proxy_buffer_size: 128k
            proxy_buffers: '4 256k'
        upstreams: {  }
        vhosts:
            IUNVQ09iKiUy:
                proxy: ''
                server_name: awesome.dev
                server_aliases:
                    - www.awesome.dev
                www_root: /var/www/awesome.dev
                listen_port: '80'
                location: .php$
                index_files:
                    - index.html
                    - index.htm
                    - index.php
                envvars:
                    - 'APP_ENV dev'
                engine: php
                client_max_body_size: 1m
                ssl_cert: ''
                ssl_key: ''

New style:

    nginx:
        install: '0'
        settings:
            default_vhost: 1
            proxy_buffer_size: 128k
            proxy_buffers: '4 256k'
        upstreams: {  }
        vhosts:
            cimjsx1tdkzj:
                proxy: ''
                server_name: awesome.dev
                server_aliases:
                    - www.awesome.dev
                www_root: /var/www/awesome
                listen_port: '80'
                index_files:
                    - index.html
                    - index.htm
                    - index.php
                client_max_body_size: 1m
                locations:
                    sx3fpcp46esj:
                        location: /
                        try_files:
                            - $uri
                            - $uri/
                            - index.php
                        fastcgi: ''
                        fastcgi_index: ''
                        fastcgi_split_path: ''
                    b5qjsigbjm7d:
                        location: '~ \.php$'
                        try_files:
                            - $uri
                            - $uri/
                            - index.php
                            - /index.php$is_args$args
                        fastcgi: '127.0.0.1:9000'
                        fastcgi_index: index.php
                        fastcgi_split_path: '^(.+\.php)(/.*)$'
                        fast_cgi_params_extra:
                            - 'SCRIPT_FILENAME $request_filename'
                            - 'APP_ENV dev'
                ssl_cert: ''
                ssl_key: ''
                ssl_port: '443'

The new style more closely matches what the nginx puppet module expects. It makes my Nginx.pp file cleaner and easier to understand, as well as handing more control over to an experienced Puppet user of PuPHPet.

IE with the newly introduced `merge_deep()` function I'm using internally, one can add sections to this nginx block that I haven't taken into account yet, and if the nginx module supports it, it will take effect.

The downside, of course, is that previous nginx config blocks aren't compatible with this new style.

Maybe the easiest solution would be to add warnings to the site everytime a block is made non BC?
