### ISSUE TITLE
Change adminer with phpmyadmin?

### ISSUE THREAD

**Issue by fvdb06** [puphpet/puphpet#1446]
mysql:
    install: '1'
    settings:
        override_options: {  }
    adminer: 1

Can I change adminer: 1 with phpmyadmin: 1
If yes, do I have to do anything else?

I tried his but without success.....

**Comment by jtreminio** [comment]
No, that won't work. You'll need to install phpmyadmin manually. I won't support it because it's a pain in the ass to work with.
