### ISSUE TITLE
Apache virtual host not working

### ISSUE THREAD

**Issue by rizkysyazuli** [puphpet/puphpet#1459]
I never manage to get a virtual host running. Can anyone check what's wrong with my settings?

Here's my [config.yaml](https://dl.dropboxusercontent.com/u/263704/Issues/config.yaml) and [hosts](https://dl.dropboxusercontent.com/u/263704/Issues/hosts) file.

Thx.

**Comment by jtreminio** [comment]
Apache has been completely refactored via 8525b77

Note: mod_php support has been completely dropped, but your configs are now infinitely more customizable.

**Comment by rizkysyazuli** [comment]
hi @jtreminio i'm not sure i understand what you mean. how does that relate to the vhost?

**Comment by jtreminio** [comment]
@rizkysyazuli Everything apache-related was refactored.

Just create a new config via the gui and try again.
