### ISSUE TITLE
CentOS - PHP 5.5 - Memcache not provisioning correctly 

### ISSUE THREAD

**Issue by phillipdaviesdeveloper** [puphpet/puphpet#1460]
I had a load of trouble using the online tool to configure a base centOS box with memcache support in PHP 5.5 so I thought I would open a issue for investigation. 

**Steps to replicate:** 

- Select the centOS box on https://puphpet.com as your OS
- Select Apache 2 with headers, rewrite, proxy_fcgi, deflate and mime_magic modules.
- Configure your virtual host
- Select PHP 5.5 and add memcache to the PHP modules list (in the drop down) 
- Generate your Puppet files, run vagrant up 

**Result:**

==> default: Error: Could not find package php-memcache
==> default: Error: /Stage[main]/Main/Puphpet::Php::Module[memcache]/Php::Module[memcache]/Package[PhpModule_memcache]/ensure: change from absent to present failed: Could not find package php-memcache

**Solution:** 

Instead of defining memcache in the PHP modules select memcache from the PECL modules list, destroy any previous instances and then up your new instance. 

This should provision without any errors, once provisioned check memcache is enabled using a phpinfo() file, if correctly installed you should have an a connection error (connection refused 111). 

This is because memcached does not seem to be running or included in the services list as 

**vagrant ssh -> service memcached start returns: memcached: unrecognized service** 
_(memcached is supposed to be included in the centOS box according to the online tool ? rollover)_

To resolve you can manually install memcached using the following:

**vagrant ssh -> yum install memcached -> service memcached start**

This should start memcached and your application / script should now be able to connect to memcache.

*So why the issue?*
This problem took me ages to sort out as I'm not much of a server guy, it seems that there is either a bug in how memcached is provisioned on the centOS box as it is not actually present as a service.

Additionally it is confusing that memcache can be selected as a PHP module in the online tool when it is unavailable so it might be really useful if there is a note or some sort of check for centOS selected boxes? 

Either way the tool is great (which is why I spent so long trying to fix the memcache issue!) so thanks for all the hard work :)

**Comment by jtreminio** [comment]
The problem with supporting multiple OSs is that some packages will exist on one but not the other.

I've tried to remedy this situation here:

https://github.com/puphpet/puppet-puphpet/blob/master/manifests/php/module.pp
https://github.com/puphpet/puppet-puphpet/blob/master/manifests/php/pecl.pp

However, your issue seems fairly simple to solve!

Add `memcached` to your `server.packages` array, as well as the `php.pecl` array and you should be good to go. No need to manually yum install.

**Comment by phillipdaviesdeveloper** [comment]
Awesome, that worked perfectly :+1: 

n.b. I added a run.sh to the puppet/files/startup-always/ folder which starts the memcace service on boot: 

#!/bin/bash
service memcached start
