### ISSUE TITLE
Bindfs error when trying to create a shared folder to anything but /var/?

### ISSUE THREAD

**Issue by peterjohnjoseph** [puphpet/puphpet#1462]
I'm getting this error when trying to create a shared folder to the /etc/nginx directory. The same thing happens when I try to create one to any /usr/ directory.  I've created shared folders to these directories in the past, so am I missing something, or did the last permissions change make this impossible? 
```
==> default: Creating bind mounts for selected devices
==> default: Creating bind mount from /mnt/vagrant-XKRInR2INJuN to /var/www
==> default: Creating bind mount from /mnt/vagrant-QvDxPF85hJ68 to /etc/nginx/
The bind command `bindfs --perms=u=rwX:g=rwX:o=rD --user=www-data --group=www-data /mnt/vagrant-QvDxPF85hJ68 /etc/nginx/` failed to run!

Please check options values and compatibility. For a complete documentation,
run `sudo bindfs --help` on the VM.

You can see it online at http://www.cs.helsinki.fi/u/partel/bindfs_docs/bindfs.1.html.
```
Same thing with the /usr/bin/ directory, or any other I've tried. 

```
==> default: Creating bind mounts for selected devices
==> default: Creating bind mount from /mnt/vagrant-XKRInR2INJuN to /var/www
==> default: Creating bind mount from /mnt/vagrant-QvDxPF85hJ68 to /usr/bin
The bind command `bindfs --perms=u=rwX:g=rwX:o=rD --user=www-data --group=www-data /mnt/vagrant-QvDxPF85hJ68 /usr/bin` failed to run!

Please check options values and compatibility. For a complete documentation,
run `sudo bindfs --help` on the VM.

You can see it online at http://www.cs.helsinki.fi/u/partel/bindfs_docs/bindfs.1.html.
````

The shared folders section of my config.yaml file looks like this- 
```
synced_folder:
            XKRInR2INJuN:
                owner: www-data
                group: www-data
                source: ./www
                target: /var/www
                sync_type: nfs
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    exclude:
                        - .vagrant/
                    auto: 'false'
            QvDxPF85hJ68:
                owner: www-data
                group: www-data
                source: ./usr/bin
                target: /usr/bin
                sync_type: nfs
                rsync:
                    auto: 'false'
```

Am I doing something wrong? Do I need to change the owners or group? Is it just not a good idea to share these folders in the first place? There is a good reason for me needing this particular folder shared, but if its not possible its not the biggest problem.

**Comment by abettermap** [comment]
@peterjohnjoseph - I'm not sure if the cause is the same, but I had the same error when trying to share certain directories in the Google Drive folders on my host machine. GDrive unfortunately puts those stupid "Iconr" files into any new folder, and I was able to fix it the error by removing them from the shared folder on my host machine. 

Doesn't sound like you're trying to share the same locations, but maybe have a look in yours for any strange system files like that...

**Comment by jtreminio** [comment]
I don't think NFS works like what you're attempting.

It basically maps the guest's directory with your host's directory - I'm not sure it can do this on existing directories within the guest?

Using bindfs to map to those directories you listed shows your error, but turning off bindfs returns this for `/usr/bin`:

    ==> default: Mounting NFS shared folders...
    The following SSH command responded with a non-zero exit status.
    Vagrant assumes that this means the command failed!

    /sbin/initctl emit --no-wait vagrant-mounted MOUNTPOINT=/usr/bin

    Stdout from the command:
    Stderr from the command:
    bash: sudo: command not found

Logging in:

    [10:12 PM]-[jtreminio@macbook]-[~/www/puphpet/temp/cs5JCc]
    $ vagrant ssh
    Welcome to Ubuntu 14.04.1 LTS (GNU/Linux 3.13.0-32-generic x86_64)

     * Documentation:  https://help.ubuntu.com/
    Welcome to your Vagrant-built virtual machine.
    Last login: Fri Jan 30 07:21:35 2015 from 10.0.2.2
    -bash: groups: command not found
    -bash: /usr/lib/command-not-found: /usr/bin/python3: bad interpreter: No such file or directory
    -bash: /usr/lib/command-not-found: /usr/bin/python3: bad interpreter: No such file or directory
    -bash: /usr/lib/command-not-found: /usr/bin/python3: bad interpreter: No such file or directory
    -bash: /usr/lib/command-not-found: /usr/bin/python3: bad interpreter: No such file or directory
    -bash: /usr/lib/command-not-found: /usr/bin/python3: bad interpreter: No such file or directory
    -bash: /usr/lib/command-not-found: /usr/bin/python3: bad interpreter: No such file or directory
    vagrant@local:~$ sudo su
    -bash: /usr/lib/command-not-found: /usr/bin/python3: bad interpreter: No such file or directory
    vagrant@local:~$ ls /usr/bin
    vagrant@local:~$

It basically overwrites what's in `/usr/bin` with what's in the host: nothing. It breaks the VM.

Let's try something within `/var`:

before sharing:

    vagrant@local:~$ ls -la /var/lib
    total 160
    drwxr-xr-x 40 root    root    4096 May  9 03:12 .
    drwxr-xr-x 11 root    root    4096 Jan 30 07:11 ..
    drwxr-xr-x  4 root    root    4096 Jan 30 07:13 AccountsService
    drwxr-xr-x  3 root    root    4096 Jan 30 07:13 apparmor
    drwxr-xr-x  6 root    root    4096 May  9 03:12 apt
    drwxr-xr-x  2 root    root    4096 Feb 18  2014 aptitude
    drwxr-xr-x  2 root    root    4096 Jan 30 07:14 belocs
    drwxr-xr-x  2 root    root    4096 Jan 30 07:14 dbus
    drwxr-xr-x  2 root    root    4096 Jan 30 07:21 dhcp
    drwxr-xr-x  7 root    root    4096 May  9 03:12 dpkg
    drwxr-xr-x  2 root    root    4096 Jan 13 19:47 git
    drwxr-xr-x  2 root    root    4096 Jan 30 07:11 initramfs-tools
    drwxr-xr-x  2 root    root    4096 Mar 13  2014 initscripts
    drwxr-xr-x  2 root    root    4096 Mar 13  2014 insserv
    drwxrwsr-x  2 libuuid libuuid 4096 Jul 22  2014 libuuid
    drwxr-xr-x  3 root    root    4096 Jan 30 07:11 locales
    drwxr-xr-x  2 root    root    4096 Jan 22  2014 logrotate
    drwxr-xr-x  2 root    root    4096 Apr 10  2014 misc
    drwxr-xr-x  2 root    root    4096 Jan 30 07:15 mlocate
    drwxr-xr-x  4 statd   nogroup 4096 May  9 03:12 nfs
    drwxr-xr-x  2 ntp     ntp     4096 Dec 20 11:47 ntp
    drwxr-xr-x  2 root    root    4096 Oct  9  2013 ntpdate
    drwxr-xr-x  2 root    root    4096 Jan 30 07:17 os-prober
    drwxr-xr-x  2 root    root    4096 Jan 30 07:14 pam
    drwxr-xr-x  2 root    root    4096 Jan 30 07:16 plymouth
    drwxr-xr-x  2 root    root    4096 Jan 30 07:13 python
    drwxr-xr-x  2 root    root    4096 Jan 30 07:14 sgml-base
    drwx------  3 root    root    4096 Jan 30 07:16 sudo
    drwxr-xr-x  3 root    root    4096 Jan 30 07:11 systemd
    drwxr-xr-x  2 root    root    4096 Jan 30 07:15 ubuntu-release-upgrader
    drwxr-xr-x  3 root    root    4096 May  9 03:12 ucf
    drwxr-xr-x  2 root    root    4096 Jan 30 07:16 update-manager
    drwxr-xr-x  2 root    root    4096 Apr 12  2014 update-notifier
    drwxr-xr-x  2 root    root    4096 May 18  2013 update-rc.d
    drwxr-xr-x  2 root    root    4096 Jan 30 07:15 urandom
    drwxr-xr-x  3 root    root    4096 May  9 03:12 ureadahead
    drwxr-xr-x  2 root    root    4096 Jan 30 07:12 usbutils
    drwxr-xr-x  2 root    root    4096 Jan 30 07:17 VBoxGuestAdditions
    drwxr-xr-x  3 root    root    4096 Jan 30 07:11 vim
    drwxr-xr-x  2 root    root    4096 Jan 30 07:14 xml-core
    vagrant@local:~$ exit

after sharing:

    vagrant@local:~$ ls -la /var/lib/
    total 12
    drwxr-xr-x  3  501 www-data  102 May  9 03:19 .
    drwxr-xr-x 11 root root     4096 Jan 30 07:11 ..
    vagrant@local:~$
