### ISSUE TITLE
PuPHPet SMB on Windows 8 not working

### ISSUE THREAD

**Issue by kitikonti** [puphpet/puphpet#1466]
So i could not get a running vm using phphpet with smb on windows 8 which i think is the recommended setup. I dont upload a config because the problem exists with the default settings, i only changed Shared Folder Type to SMB.
I download the package, extract the files. Open a Git for Windows Bash with Administration Priviliges. And run vagrant up. Somewhere in the middle of the provision process the error messages starts. It begins with permission errors where it trys to change to owner and the permissions of the /var/www folder or subfolders.
I think the following errors are all depending upon this.
So i dont think i am doing something wrong, but i am wondering because this is just the default config.

Things i found out while debugging/testing:
* I get no errors if i use the default shared folder type (but this is very slow on windows)
* I also get no errors if i dont install a webserver (apache or nginx), so the problem dont happens on the smb configuration itself
* I get the errors on installing with nginx or apache, so its not depending to just one webserver
* It seems that on the provision of the webserver part, it tries to chmod or chown of the /var/www or subfolders which ends with permission denied
* on the beginning of the provision i have to enter a host username/password for using smb. but i dont get a feedback if i have entered a working username/password. i have tried several combinations and never get a error? the reason why i tried this multiple times is because i was not 100% sure whats my username in windows8 because i use the microsoft (live) account to login, so i dont have a standalone local user

**Comment by jtreminio** [comment]
Same issue as #1540
