### ISSUE TITLE
 ==> default: Error: Apache::Vhost[kogbn9dhbdzz]: 'directories' must be either a Hash or an Array of Hashes at /tmp/vagrant-puppet-3/modules-0/apache/manifests/vhost.pp:410 on node localhost

### ISSUE THREAD

**Issue by Finsandb** [puphpet/puphpet#1468]
> ==> default: Error: Apache::Vhost[kogbn9dhbdzz]: 'directories' must be either a Hash or an Array of Hashes at /tmp/vagrant-puppet-3/modules-0/apache/manifests/vhost.pp:410 on node localhost

I keep getting the above error when running 'vagrant up'.
I've tried creating new manifests and uploading ones that currently work, (but change the domain IP and port number). 

The VM is running but Apache isn't. At one stage I did get it running by editing it's config file, but then PHP wasn't working!

I've also manually amended a working .yaml file, but that then generated the following: 

> ==> default: Error: Could not find template 'apache/vhost.conf.erb' at /tmp/vagrant-puppet-3/modules-0/apache/manifests/vhost.pp:541 on node localhost

I then copied vhost.conf.erb from an existing install, but that then resulted in the first error.

How do I fix the problem?
.yaml file below
>
---
vagrantfile-local:
    vm:
        box: puphpet/centos65-x64
        box_url: puphpet/centos65-x64
        hostname: ''
        memory: '512'
        cpus: '1'
        chosen_provider: virtualbox
        network:
            private_network: 192.168.56.126
            forwarded_port:
                1qzsGIGkL2h8:
                    host: '8726'
                    guest: '22'
        post_up_message: ''
        provider:
            virtualbox:
                modifyvm:
                    natdnshostresolver1: on
            vmware:
                numvcpus: 1
            parallels:
                cpus: 1
        provision:
            puppet:
                manifests_path: puphpet/puppet
                manifest_file: site.pp
                module_path: puphpet/puppet/modules
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
                    - '--parser future'
        synced_folder:
            xHD9qdCkL30r:
                owner: ''
                group: ''
                source: 'D:\\Dev\\www.mydomain.co.uk\\public_html'
                target: /home/mydomain/public_html
                sync_type: default
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    exclude:
                        - .vagrant/
                    auto: 'false'
        usable_port_range:
            start: 10200
            stop: 10500
    ssh:
        host: null
        port: null
        private_key_path: null
        username: vagrant
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'
    vagrant:
        host: detect
server:
    install: '1'
    packages:
        - vim-common
        - htop
users_groups:
    install: '1'
    groups: {  }
    users: {  }
cron:
    install: '1'
    jobs: {  }
firewall:
    install: '1'
    rules: {  }
apache:
    install: '1'
    settings:
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - rewrite
    vhosts:
        5mavhyxsvxl9:
            servername: vm.mydomain.co.uk
            serveraliases:
                - mydomain.co.uk
            docroot: /home/mydomain/public_html
            port: '80'
            setenv:
                - 'APP_ENV dev'
            custom_fragment: ''
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
nginx:
    install: '0'
    settings:
        default_vhost: 1
        proxy_buffer_size: 128k
        proxy_buffers: '4 256k'
    upstreams: {  }
    vhosts:
        qityphplje6p:
            proxy: ''
            server_name: awesome.dev
            server_aliases:
                - www.awesome.dev
            www_root: /var/www/awesome
            listen_port: '80'
            index_files:
                - index.html
                - index.htm
                - index.php
            client_max_body_size: 1m
            ssl_cert: ''
            ssl_key: ''
            ssl_port: ''
php:
    install: '1'
    settings:
        version: '56'
    fpm_settings:
        port: 9000
    composer: '1'
    composer_home: ''
    modules:
        php:
            - cli
            - gd
            - intl
            - mcrypt
            - mysqlnd
        pear: {  }
        pecl:
            - pecl_http
    ini:
        display_errors: On
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
hhvm:
    install: '0'
    nightly: 0
    composer: '1'
    composer_home: ''
    settings:
        host: 127.0.0.1
        port: '9000'
    ini:
        display_errors: On
        error_reporting: '-1'
    timezone: null
xdebug:
    install: '1'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
xhprof:
    install: '0'
wpcli:
    install: '0'
    version: ''
drush:
    install: '0'
    version: 6.3.0
ruby:
    install: '1'
    versions:
        DH4gM4OjSAI1:
            version: ''
nodejs:
    install: '0'
    npm_packages: {  }
python:
    install: '1'
    packages: {  }
    versions:
        sH3Qonz82qPQ:
            version: ''
mysql:
    install: '1'
    settings:
        version: '5.6'
        root_password: '123'
        override_options: {  }
    adminer: 0
    users: {  }
    databases: {  }
    grants: {  }
postgresql:
    install: '0'
    settings:
        global:
            encoding: UTF8
            version: '9.3'
        server:
            postgres_password: ''
    databases: {  }
    users: {  }
    grants: {  }
    adminer: 0
sqlite:
    install: '0'
    adminer: 0
    databases: {  }
mongodb:
    install: '0'
    settings:
        auth: 1
        bind_ip: 127.0.0.1
        port: '27017'
    databases: {  }
redis:
    install: '0'
    settings:
        conf_port: '6379'
mailcatcher:
    install: '1'
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '1080'
        mailcatcher_path: /usr/local/rvm/wrappers/default
        from_email_method: headers
beanstalkd:
    install: '0'
    settings:
        listenaddress: 0.0.0.0
        listenport: '13000'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: 0
    binlogdir: /var/lib/beanstalkd/binlog
rabbitmq:
    install: '0'
    settings:
        port: '5672'
    users: {  }
    vhosts: {  }
    plugins: {  }
elastic_search:
    install: '0'
    settings:
        version: null
        java_install: true
solr:
    install: '0'
    settings:
        version: ''
        port: ''

**Comment by jtreminio** [comment]
Unfortunately, recent changes to how Apache works means you need to manually recreate your config.

Sorry about that, there's a PR to show this warning.

**Comment by Finsandb** [comment]
PR?

**Comment by istvan-ujjmeszaros** [comment]
None of the configurations work now on `puphpet.com`, PHP is not working in any one of them (tried nginx and apache too with ubuntu 12.04 64bit). Something went really wrong.
And dropping support for mod_php was a really bad idea. Puphpet seems to be totally unusable now.

**Comment by marcosruiz** [comment]
This solution works for me: Change PHP version to an older one. I was in 7.1 version and gave me that error, and now in version 7 give me the same error but I can use the web server anyway.
