### ISSUE TITLE
Puppet error when there is no directory directive for Apache configuration

### ISSUE THREAD

**Issue by sylvainfilteau** [puphpet/puphpet#1474]
Sorry for the lack of details here...

When provisioning using a config.yaml that has no directories node for Apache configuration, the process fails.

I got this by reconfiguring an old config.yaml that, as I know of, didn't have any "directories" configuration.

**Comment by fain182** [comment]
I had the same problem

**Comment by pborreli** [comment]
Has the same problem, here is the error message : 
```
Error: Apache::Vhost[hmikd6zbffb1]: 'directories' must be either a Hash or an Array of Hashes at /tmp/vagrant-puppet-3/modules-0/apache/manifests/vhost.pp:410 on node packer-virtualbox-iso

**Comment by j0rdsta** [comment]
I'm also having the same problem with a pre-existing config.yaml file. I just went and generated a new config off the website, and I've noticed that the vhosts now have a `serveraliases:` configuration - adding this to the vhosts doesn't seem to have any effect, however.

**Comment by rlweb** [comment]
+1

**Comment by kjeldschumacher** [comment]
+1

**Comment by mczoska** [comment]
+1

**Comment by jacksonj04** [comment]
:+1:

**Comment by a-am** [comment]
I am experiencing same issue.
