### ISSUE TITLE
Allow for combined listen_port

### ISSUE THREAD

**Issue by psren** [puphpet/puphpet#1478]
In the vhosts config it would be nice to allow for combinded ports.

e.g.
```listen_port: '80'``` => ```*:80```

This is not possible
```listen_port: '*:80 *:443'``` => ```*:80 *:443```

**Comment by jtreminio** [comment]
This doesn't seem to be possible under puppetlabs-apache:

https://github.com/puppetlabs/puppetlabs-apache/blob/master/manifests/vhost.pp#L320

Recent refactorings of the GUI have attempted to bring the forms more inline with the actual modules themselves, so if I made something custom for this it would basically be going against my current trend.
