### ISSUE TITLE
How to setup separate boxes on the same host ?

### ISSUE THREAD

**Issue by schwipps** [puphpet/puphpet#1483]
Last days, I've been facing weird errors when deploying my boxes : NFS, local VM ip address...
I've finally achieved to get a stable environment and just don't want to fight with this one, 'till I really get what's wrong.

That said, I'd still like to test different options on new boxes.
I would go for readjusting my config.yaml through the website, generate a new archive, extract to a new folder, then vagrant up.
However, this method overwrites my orginal box.

What should I change to create a new separate box, so that nothing interfers with the safe one ?

Thanks

**Comment by jtreminio** [comment]
I'm not sure what's going on with your setup, but if I create separate folders then I get a new VM each and every time.

Are you maybe setting the hostname somewhere?

**Comment by schwipps** [comment]
Well, I gave it a new try and everything went well... I probably messed up somewhere.
Sorry for this. I'll come up with more informations if ever I face this problem again.

Thanks for the great work, by the way. Very useful tool !
