### ISSUE TITLE
Enable removing hosts on suspend for vagrant-hostmanager plugin

### ISSUE THREAD

**Issue by markjaquith** [puphpet/puphpet#1484]
When I suspend my PuPHPet VM (with vagrant-hostmanager plugin enabled), I get the message: `default: Removing hosts on suspend disabled`, and the line remains in my `/etc/hosts` file. As I map the public domain of sites I manage, this is absolutely not what I want... when I suspend the local VM, I want to regain access to the public site.

I think a better default is enabling "remove hosts on suspend".

**Comment by jtreminio** [comment]
Looks like you're using vagrant-hostupdater:

https://github.com/cogitatio/vagrant-hostsupdater/blob/master/lib/vagrant-hostsupdater/Action/RemoveHosts.rb

Not vagrant-hostmanager:

https://github.com/smdahlen/vagrant-hostmanager/search?utf8=%E2%9C%93&q=Removing+hosts+on+suspend+disabled

**Comment by markjaquith** [comment]
Bah. I was.

But...

Even with that remedied, the host entries remain after the VM is suspended. In fact, it’s even worse: entries aren't removed even after a `vagrant halt`. ಠ_ಠ It apparently takes a `vagrant destroy` to do that. Which is absurd.

So this feature is fairly useless for managing the host's `/etc/hosts`. **vagrant-hostsupdater** is the plugin that does this.

**Comment by osamana** [comment]
When I suspend the vagrant machine, hostmanager plugin doesn't update the hosts file 
i use private network with DHCP, after suspend/resume sometimes the IP changes and the host file doesn't update and refers to the previous IP ..Broken
