### ISSUE TITLE
Puppet fails when provisioning to Digital Ocean

### ISSUE THREAD

**Issue by webconsult** [puphpet/puphpet#1485]
I get an error while trying to provision to Digital Ocean:

```
==> default: Warning: Could not retrieve fact fqdn
==> default: Error: unsupported release utopic at /tmp/vagrant-puppet/modules-19dd7905bf29f5e5f0e766560997f5e8/java/manifests/params.pp:50 on node master
==> default: Error: unsupported release utopic at /tmp/vagrant-puppet/modules-19dd7905bf29f5e5f0e766560997f5e8/java/manifests/params.pp:50 on node master
```

What does it mean and how can I resolve it?

Here is the full error log:

https://gist.github.com/webconsult/af4b200e832f3faa0a6e

And here is my config file:

https://gist.github.com/webconsult/5af5df55ef9f389770dc

**Comment by jtreminio** [comment]
Sounds like digital ocean has removed some distros from their api... breaking their api *again*.

Getting a bit tired of having to keep up with their frequent changes.

**Comment by jtreminio** [comment]
Looks like an issue with the java module:


        'wheezy', 'precise','quantal','raring','saucy': {
          $java =  {
            'jdk' => {
              'package'          => 'openjdk-7-jdk',
              'alternative'      => "java-1.7.0-openjdk-${::architecture}",
              'alternative_path' => "/usr/lib/jvm/java-1.7.0-openjdk-${::architecture}/bin/java",
              'java_home'        => "/usr/lib/jvm/java-1.7.0-openjdk-${::architecture}/",
            },
            'jre' => {
              'package'          => 'openjdk-7-jre-headless',
              'alternative'      => "java-1.7.0-openjdk-${::architecture}",
              'alternative_path' => "/usr/lib/jvm/java-1.7.0-openjdk-${::architecture}/bin/java",
              'java_home'        => "/usr/lib/jvm/java-1.7.0-openjdk-${::architecture}/",
            },
            'oracle-jre' => {
              'package'          => 'oracle-j2re1.7',
              'alternative'      => 'j2re1.7-oracle',
              'alternative_path' => '/usr/lib/jvm/j2re1.7-oracle/bin/java',
              'java_home'        => '/usr/lib/jvm/j2re1.7-oracle/',
            },
            'oracle-jdk' => {
              'package'          => 'oracle-j2sdk1.7',
              'alternative'      => 'j2sdk1.7-oracle',
              'alternative_path' => '/usr/lib/jvm/j2sdk1.7-oracle/jre/bin/java',
              'java_home'        => '/usr/lib/jvm/j2sdk1.7-oracle/jre/',
            },
          }
        }

**Comment by jtreminio** [comment]
You can replace puphpet/puppet/modules/java with https://github.com/puppetlabs/puppetlabs-java/tree/1.3.0 and try again, or regenerate your archive from puphpet.com
