### ISSUE TITLE
'import' has been discontinued in favor of a manifest directory

### ISSUE THREAD

**Issue by brendan-roche** [puphpet/puphpet#1486]
Hi guys,

I'm just trying to `vagrant provision`, but receive the following error: 

```
==> default: Error: Evaluation Error: Use of 'import' has been discontinued in favor of a manifest directory. See http://links.puppetlabs.com/puppet-import-deprecation at /tmp/vagrant-puppet/manifests-893fcda21077f5a583c2dbbba8515c0a/site.pp:1:1 on node localhost

The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

Is there an update or fix for this issue?

**Comment by jtreminio** [comment]
Sounds like you have a new version of puppet installed than 3.4.3, which comes with the boxes.

What'd you do?

**Comment by elliotchance** [comment]
We didn't want to commit all those `puphpet/puppet/modules` files to our repo. So instead we are using:

```bash
cd puphpet/puppet
librarian-puppet install
```

Would this be an issue?

**Comment by jtreminio** [comment]
No, this is fine.

I need to know how you got puppet installed on your target VM.

**Comment by elliotchance** [comment]
Had a "Der!" moment. There was:

    gem 'puppet'

In our `Gemfile` which of course was installing the latest one after the box was built making `provision` fail the second time.

This is now resolved.

**Comment by arnab0** [comment]
So what is the new command to import??

**Comment by jtreminio** [comment]
@arnab0 this isn't a puphpet question.

**Comment by vamshi3489** [comment]
You can use require 
require "./nodes.pp"
