### ISSUE TITLE
Apache and php are not installed

### ISSUE THREAD

**Issue by helmet91** [puphpet/puphpet#1498]
Hi,

I created a new vagrant box with this puphpet configuration:
http://pastebin.com/4JJ9ARn9

My problem is, that it does not install apache and php packages, although my config.yaml clearly states that it should install them.

Certainly I did something wrong somewhere, but I could not find the source of this issue. Could you please take a look at my config file linked above?

**Comment by jtreminio** [comment]
Paste output from `$ vagrant up`

**Comment by helmet91** [comment]
Thank you for the quick reply!

Here is the output of `vagrant up`:
http://pastebin.com/7SUMjZTP

I also did a `vagrant destroy` and then a `vagrant up` again:
http://pastebin.com/uRNxuRQi

Is it possible, that these two last errors broke the execution of the script?

**Comment by jtreminio** [comment]
Problem is that you've declared user/group `www-data`.

I'll add a check to prevent dupe declaration.
