### ISSUE TITLE
Couldn't resolve host 'box.puphpet.com'

### ISSUE THREAD

**Issue by YugalXD** [puphpet/puphpet#1503]
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'puphpet/ubuntu1404-x32' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Loading metadata for box 'puphpet/ubuntu1404-x32'
    default: URL: https://atlas.hashicorp.com/puphpet/ubuntu1404-x32
==> default: Adding box 'puphpet/ubuntu1404-x32' (v2.0) for provider: virtualbox   
   default: Downloading: https://atlas.hashicorp.com/puphpet/boxes/ubuntu1404-x32/versions/2.0/providers/virtualbox.box

An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.
Couldn't resolve host 'box.puphpet.com'

**Comment by kusmierz** [comment]
try enter `ping box.puphpet.com` in you host (cmd/shell). What is the result?
