### ISSUE TITLE
Fails to create new Postgres user and DB

### ISSUE THREAD

**Issue by kyle-mccarthy** [puphpet/puphpet#1504]
It doesn't look like specified users and databases are created.  I am unable to log into the defined user/DB from the cli or adminer.   I can log in as the default postgres user with password '123' through adminer but not the cli.  

In adminer under select pg_user only user listed is posgres.  In adminer under select pg_database the following DBs are listed: template 0, template 1, postgres.

vagrant ssh:

    $ psql -h localhost -U ta_cs4320_user
    Password for user ta_cs4320_user: 
    psql: FATAL:  password authentication failed for user "ta_cs4320_user"
    FATAL:  password authentication failed for user "ta_cs4320_user"

config.yaml:

    ---
    vagrantfile-local:
        vm:
            box: puphpet/debian75-x64
            box_url: puphpet/debian75-x64
            hostname: ''
            memory: '512'
            cpus: '1'
            chosen_provider: virtualbox
            network:
                private_network: 192.168.56.104
                forwarded_port:
                    L9wZ5ssAuC3C:
                        host: '5029'
                        guest: '22'
            post_up_message: ''
            provider:
                virtualbox:
                    modifyvm:
                        natdnshostresolver1: on
                vmware:
                    numvcpus: 1
                parallels:
                    cpus: 1
            provision:
                puppet:
                    manifests_path: puphpet/puppet
                    manifest_file: site.pp
                    module_path: puphpet/puppet/modules
                    options:
                        - '--verbose'
                        - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
                        - '--parser future'
            synced_folder:
                cozbc9aCz1ex:
                    owner: www-data
                    group: www-data
                    source: ./
                    target: /var/www
                    sync_type: default
                    rsync:
                        args:
                            - '--verbose'
                            - '--archive'
                            - '-z'
                        exclude:
                            - .vagrant/
                        auto: 'false'
            usable_port_range:
                start: 10200
                stop: 10500
        ssh:
            host: null
            port: null
            private_key_path: null
            username: vagrant
            guest_port: null
            keep_alive: true
            forward_agent: false
            forward_x11: false
            shell: 'bash -l'
        vagrant:
            host: detect
    server:
        install: '1'
        packages:
            - vim
    users_groups:
        install: '1'
        groups: {  }
        users: {  }
    cron:
        install: '1'
        jobs: {  }
    firewall:
        install: '1'
        rules: {  }
    apache:
        install: '1'
        settings:
            user: www-data
            group: www-data
            default_vhost: true
            manage_user: false
            manage_group: false
            sendfile: 0
        modules:
            - rewrite
        vhosts:
            2prlgup9boup:
                servername: ta-cs4320.dev
                serveraliases:
                    - www.ta-cs4320.dev
                docroot: /var/www/ta-cs4320/public
                port: '80'
                setenv:
                    - 'APP_ENV dev'
                directories:
                    hyaz4axgggoz:
                        provider: directory
                        path: /var/www/ta-cs4320
                        options:
                            - Indexes
                            - FollowSymlinks
                            - MultiViews
                        allow_override:
                            - All
                        require:
                            - all
                            - granted
                        custom_fragment: ''
                engine: php
                custom_fragment: ''
                ssl_cert: ''
                ssl_key: ''
                ssl_chain: ''
                ssl_certs_dir: ''
        mod_pagespeed: 0
    nginx:
        install: '0'
        settings:
            default_vhost: 1
            proxy_buffer_size: 128k
            proxy_buffers: '4 256k'
        upstreams: {  }
        vhosts:
            rxv7xdh4wmog:
                proxy: ''
                server_name: awesome.dev
                server_aliases:
                    - www.awesome.dev
                www_root: /var/www/awesome
                listen_port: '80'
                location: \.php$
                index_files:
                    - index.html
                    - index.htm
                    - index.php
                envvars:
                    - 'APP_ENV dev'
                engine: php
                client_max_body_size: 1m
                ssl_cert: ''
                ssl_key: ''
    php:
        install: '1'
        version: '54'
        composer: '1'
        composer_home: ''
        modules:
            php:
                - cli
                - intl
                - mcrypt
                - mbstring
            pear: {  }
            pecl:
                - pecl_http
        ini:
            display_errors: On
            error_reporting: '-1'
            session.save_path: /var/lib/php/session
        timezone: America/Chicago
        mod_php: 0
    hhvm:
        install: '0'
        nightly: 0
        composer: '1'
        composer_home: ''
        settings:
            host: 127.0.0.1
            port: '9000'
        ini:
            display_errors: On
            error_reporting: '-1'
        timezone: null
    xdebug:
        install: '1'
        settings:
            xdebug.default_enable: '1'
            xdebug.remote_autostart: '0'
            xdebug.remote_connect_back: '1'
            xdebug.remote_enable: '1'
            xdebug.remote_handler: dbgp
            xdebug.remote_port: '9000'
    xhprof:
        install: '0'
    wpcli:
        install: '0'
        version: v0.17.1
    drush:
        install: '0'
        version: 6.3.0
    ruby:
        install: '1'
        versions: {  }
    nodejs:
        install: '0'
        npm_packages: {  }
    python:
        install: '1'
        packages: {  }
        versions: {  }
    mysql:
        install: '0'
        override_options: {  }
        root_password: '123'
        adminer: 0
        databases:
            abZQzhUd3T3u:
                grant:
                    - ALL
                name: dbname
                host: localhost
                user: dbuser
                password: '123'
                sql_file: ''
    postgresql:
        install: '1'
        settings:
            global:
                encoding: UTF8
                version: '9.3'
            server:
                postgres_password: '123'
        databases:
            iaqPQiNnhyAW:
                dbname: ta_cs4320_db
                owner: ta_cs4320_user
        users:
            ELiqJsAatP8n:
                username: ta_cs4320_user
                password: '123'
        grants: {  }
        adminer: 1
    mariadb:
        install: '0'
        override_options: {  }
        root_password: '123'
        adminer: 0
        databases: {  }
        version: '10.0'
    sqlite:
        install: '0'
        adminer: 0
        databases: {  }
    mongodb:
        install: '0'
        settings:
            auth: 1
            port: '27017'
        databases: {  }
    redis:
        install: '0'
        settings:
            conf_port: '6379'
    mailcatcher:
        install: '0'
        settings:
            smtp_ip: 0.0.0.0
            smtp_port: 1025
            http_ip: 0.0.0.0
            http_port: '1080'
            mailcatcher_path: /usr/local/rvm/wrappers/default
            from_email_method: inline
    beanstalkd:
        install: '0'
        settings:
            listenaddress: 0.0.0.0
            listenport: '13000'
            maxjobsize: '65535'
            maxconnections: '1024'
            binlogdir: /var/lib/beanstalkd/binlog
            binlogfsync: null
            binlogsize: '10485760'
        beanstalk_console: 0
        binlogdir: /var/lib/beanstalkd/binlog
    rabbitmq:
        install: '0'
        settings:
            port: '5672'
    elastic_search:
        install: '0'
        settings:
            version: 1.4.1
            java_install: true
    solr:
        install: '0'
        settings:
            version: 4.10.2
            port: '8984'

**Comment by techdaddies-kevin** [comment]
I'm seeing this behavior, too. However, in my case, it appears that the user and database are both being created. If I log in to psql with the 'postgres' user and attempt to create my user specified in my config.yaml file, psql complains that the user already exists. I know that my database exists, as I can connect using the postgres / 123 combination. The problem, at least in my case, is that I cannot connect using the username that I specified via the web interface...

**Comment by jtreminio** [comment]
Please try this again, as it works fine for me:

    [03:54 AM]-[vagrant@local]-[~]
    $ psql jtreminio -h 127.0.0.1 -d dbname
    Password for user jtreminio:
    psql (9.3.6)
    SSL connection (cipher: DHE-RSA-AES256-GCM-SHA384, bits: 256)
    Type "help" for help.
    
    dbname=>

Note that this is different from yours:

    $ psql -h localhost -U ta_cs4320_user

results in

    [03:56 AM]-[vagrant@local]-[~]
    $ psql -h localhost -U jtreminio
    Password for user jtreminio:
    psql: FATAL:  database "jtreminio" does not exist
