### ISSUE TITLE
"PHP is a toy language..."

### ISSUE THREAD

**Issue by GRMule** [puphpet/puphpet#1509]
Suggested improvement: would prefer not to be berated by a cargo cult fanboy for using the language that is running half the internet. kthx.

edit: I'm being a dick. But really... ought not the tool tips be short and to the point? I get sick of elitists neckbearding about languages; I'm trying to work.

**Comment by jtreminio** [comment]
What are you talking about, have you seen my other repos? It's all PHP.

It's a joke, calm down budy.
