### ISSUE TITLE
Possible to double-add mod_ssl

### ISSUE THREAD

**Issue by GRMule** [puphpet/puphpet#1510]
In the list of Apache mods, I manually added mod_ssl by choosing it from the auto-completed list of available mods. This was my first time using this tool, and I did not at that stage realize that I would explicitly be adding SSL later.

Lower on the same step, I am asked if I would like to enable SSL. I checked the appropriate box, and left the fields blank as indicated for defaults.

After running vagrant up against the generated config, I got the following error:

==> default: Error: Duplicate declaration: Apache::Mod[ssl] is already declared
in file /tmp/vagrant-puppet/manifests-893fcda21077f5a583c2dbbba8515c0a/nodes/Apa
che.pp:204; cannot redeclare at /tmp/vagrant-puppet/modules-7c60dd26eb963e13dc1b
58262bc84986/apache/manifests/mod/ssl.pp:45 on node localhost
==> default: Error: Duplicate declaration: Apache::Mod[ssl] is already declared
in file /tmp/vagrant-puppet/manifests-893fcda21077f5a583c2dbbba8515c0a/nodes/Apa
che.pp:204; cannot redeclare at /tmp/vagrant-puppet/modules-7c60dd26eb963e13dc1b
58262bc84986/apache/manifests/mod/ssl.pp:45 on node localhost

... and then it bails out.

It occurred to me that checking the "Enable SSL" box may have cued the config generator to include mod_ssl for Apache without regard to my selection to manually include the module. I loaded my config back into the website and removed mod_ssl from the modules list, downloaded & replaced my config file, now vagrant up works as expected.

It seems to me that this possible mix-up could be prevented by one of two changes:

a) remove mod_ssl from the manually-addable list of Apache modules (only way to get it is to complete the "Enable SSL" substep)

or if possible, b) have the config generator check if mod_ssl has already been added from the modules list before including it in reaction to the "Enable SSL" option

Not a major problem, but it was a stumbling block that was pretty easy to trip over. Thanks!

First config file is with both mod_ssl manually added AND "Enable SSL" checked (this one failed): http://pastebin.com/deqGfVHS

Second config file is after I removed mod_ssl (this one worked): http://pastebin.com/EM8KaCvV

**Comment by leek** [comment]
This just happened to me as well. :+1:

**Comment by stefgosselin** [comment]
Same issue here.
