### ISSUE TITLE
Errors with new configurations if there were an old config upload before

### ISSUE THREAD

**Issue by istvan-ujjmeszaros** [puphpet/puphpet#1511]
Please reopen #1469 as not even the newly generated configs are working now.
Just try Ubuntu, any version, with Nginx or Apache, and `vagrant up` will fail.

**Comment by istvan-ujjmeszaros** [comment]
Hey, I have spent the whole day trying to make it work, with no success, but finally had the idea to make the configuration in Crome's incognito mode, as there may be some session related config issues due to the config file I have uploaded before.
It works fine now.

So, there is an issue with starting a new configuration if there were an upload before.

**Comment by istvan-ujjmeszaros** [comment]
FYI, I have re-uploaded the working config file in the same incognito window where I have created it, then added some vhost to it, and now I get the `'directories' must be either a Hash or an Array of Hashes` error when doing a `vagrant up` (in a new, empty folder) with the updated config.

**Comment by istvan-ujjmeszaros** [comment]
Solved the `Hash or an Array of Hashes` error by using the `Add another Apache vhost directory` option, but PHP still didn't work in the vhosts with that config file, so I had to add the `files_match` definitions to the config file by hand, as there were no button for it in the vhost configurator section. Finally everything seems to work.

**Comment by erdemece** [comment]
when you use old config.yml with the website it gives back wrong permission variable for apache which is

                    require:
                        - all 
                        - granted


it should be:

                    require:
                        - all granted

**Comment by jtreminio** [comment]
Need to add notifications to this, but wrote a blog post!

http://blog.puphpet.com/blog/2015/04/18/drag-drop-bc-break/
