### ISSUE TITLE
Support Elasticsearch 1.5.*

### ISSUE THREAD

**Issue by carvefx** [puphpet/puphpet#1516]
Is it possible to support elasticsearch 1.5.\* in puphpet? I'd be happy to make the required changes.
From what I can gather:
1.) enabling a new version in the UI would be done here: https://github.com/puphpet/puphpet/blob/master/src/Puphpet/Extension/ElasticSearchBundle/Resources/config/available.yml

2.) Would I need to do anything in https://github.com/puphpet/puppet-elasticsearch or the respective elasticsearch node in /archive ?

https://github.com/puphpet/puphpet/blob/master/archive/puphpet/puppet/nodes/ElasticSearch.pp

As far as I can tell, just enabling the option in the UI would simply "work". Am I wrong?

**Comment by bretrzaun** [comment]
This would be helpful since current version of Kibana requires "Elasticsearch 1.4.4 or later" which is currently not available with Puphpet.

**Comment by jtreminio** [comment]
Hi!

Everything was recently changed around. The new yaml location is

https://github.com/puphpet/puphpet/blob/master/src/Puphpet/MainBundle/Resources/config/elastic-search/available.yml

I'm not sure if it'll work out of the gate. Give it a try!

**Comment by jtreminio** [comment]
Implemented.
