### ISSUE TITLE
Support another shells

### ISSUE THREAD

**Issue by meron1122** [puphpet/puphpet#1520]
Support another shells want be very proud.
For example zsh with grml  config.
In current  puppet says rvm not found if i change ssh shell.

**Comment by jtreminio** [comment]
Sorry, unless there's a PHP this is too much work to maintain. You can change shell via config.yaml as well.

**Comment by meron1122** [comment]
And vagrant provision stop working because zsh dont have special enviroment values...

**Comment by shivapoudel** [comment]
You can use git bash

**Comment by jtreminio** [comment]
To clarify, I meant to say "unless there's a PR"
