### ISSUE TITLE
Ease way to install PHPUnit and Apigen

### ISSUE THREAD

**Issue by shivapoudel** [puphpet/puphpet#1525]
@jtreminio can you help me with the ease way to install the PHPUnit and APIGen.

**Comment by shivapoudel** [comment]
@jtreminio Perhaps it would be interesting to use a some setting or something else for the global composer packages IMO. What do you think the composer package field should say though? I'm not really sure we need it, plus I am aware of PHPUnit which can be install via composer and is used mostly by all experienced programmer.

**Comment by jtreminio** [comment]
Global composer packages would probably be best handled via an exec-once bash file.
