### ISSUE TITLE
Unable to specify Apache Version

### ISSUE THREAD

**Issue by raptor65** [puphpet/puphpet#1531]
I have a requirement for a test machine that mirrors a live server environment. To this end, it needs to be able to provide webservices built on mod_mono running under Apache.

I am using the puphpet/debian75-x64 ( Debian GNU/Linux 7.8 (wheezy) ) on virtualbox and an up-to-date puphpet manifest, which installs Apache 2.4.10-6. This has been working like a charm. 

Unfortunately, mod_mono is not supported on Apache 2.4, so I now need to 'downgrade' my config to Apache 2.2, and no matter what I have tried, I simply can *not* get puphpet to install Apache 2.2.

I have read the previous (closed) thread (Is it possible to install apache in selected version #872) and I can confirm what others have reported - that setting the apache version in config.yaml as suggested:

````...
apache:
    install: '1'
    settings:
        apache_version: 2.2
        user: www-data
	...
````

or even

````
...
apache:
    install: '1'
    settings:
        apache_version: '2.2'
        user: www-data
	...
````

simply doesn't work - everything carries on exactly as normal, and when I run 

`dpkg-query -l | grep -i apache2`

I get:

````
10:ii  apache2             2.4.10-6~bpo70+1+SID          amd64        Apache HTTP Server
11:ii  apache2-bin         2.4.10-6~bpo70+1+SID          amd64        Apache HTTP Server (modules and other binary files)
12:ii  apache2-data        2.4.10-6~bpo70+1+SID          all          Apache HTTP Server (common files)
13:ii  apache2-utils       2.4.10-6~bpo70+1+SID          amd64        Apache HTTP Server (utility programs for web servers)
````

I am now fresh out of ideas! Can someone please advise how to get Apache 2.2 to install as the webserver?

Thanks in anticipation...

**Comment by jtreminio** [comment]
Sorry, I dropped Apache 2.2 support a few weeks back as it was like supporting 3 webservers with 2.4.10 and Nginx.

You can regain this ability by cloning the puphpet repo and checking out the `pre-php-fpm` tag.

**Comment by raptor65** [comment]
Thanks for the quick response - I'll do as you suggest.

It might help others future if you were able to put a note clarifying that on the Apache server selection page :-)

**Comment by raptor65** [comment]
@jtreminio Are there any installation/setup instructions? I must be missing something because I just can't get this to work properly.

I've successfully managed to get the tag you suggested up and running in a VM and I think I've worked out most of the dependencies (zip, librarian-puppet etc), but I must be missing *something*.

The page fires up OK and I can import an existing config file OK, I can run through and make changes and "Go ahead and make" a puphpet file, which duly sends a zip file as expected. But when I  extract the contents of the zip file, there is no modules directory at puphpet\puppet\modules although everything else seems to be all present and correct and the config.yaml corectly shows the options I have set.

What am I missing? I'm sure I'll kick myself when I find out!

**Comment by jtreminio** [comment]
Sorry! Composer *should* have run it, but you must run `bin/librarian` to get all modules installed. Run it from your project base directory

**Comment by raptor65** [comment]
@jtreminio 

Awesome! Thank you so much  for that and a big thumbs up for taking the time to help. 

After some more poking around, it boiled down to permissions problems creating the directories on a synced folder on the VM under Windows, compounded by error-suppression in the librarian scripts: Composer was running through the install, but was failing silently.

Once I shifted it to a "real" directory on the VM and re-installed, everything ran perfectly and I now have a VM up an running with Apache 2.2.
