### ISSUE TITLE
Unable to access beanstalkd-console (or adminer)

### ISSUE THREAD

**Issue by Braunson** [puphpet/puphpet#1532]
Enabled benastalkd, beanstalkd-console, run vagrant up but cannot access it from http://vagrantip.com/beanstalkd-console/public

- I did change the location of my synced files (i.e. /var/www/mysite/)
- I do see where the beanstalkd-console files are located ( /var/www/default/beanstalk_console along with adminer/ which is also not accessible)

Maybe me changing the default location of my files messed things up?

One solution I'm going to run right now is to create a vhost to that folder.

**Comment by jtreminio** [comment]
> /var/www/default/beanstalk_console

You may have an older archive, since it was changed several months ago to use `/var/www/html`. Please regenerate your zip file and try again.
