### ISSUE TITLE
Support for own repository

### ISSUE THREAD

**Issue by zeleznypa** [puphpet/puphpet#1533]
Please add support for adding own deb/rpm repositories.

For example, when you want to install oci8 module into the PHP, it requires oracle_client package to be installed, but It is not available in the standard repositories.

https://help.ubuntu.com/community/Oracle

**Comment by stuba** [comment]
I think this could be done using some puppeting. Dirty fix is to use for example  puphpet run-once script..

**Comment by rafaelrp** [comment]
I'm having trouble with this too, i select php Pecl modules on puphpet.com like OCI8 and PDO_OCI, but when i up my vm, the oracle module still not installed and active in phpInfo().

**Comment by rvoortman** [comment]
also have problems with this. Can't seem to figure out how to install it.

**Comment by jtreminio** [comment]
I've added support for `puphpet/files/exec-preprovision` shell files.

You can do everything you need to in there.

Adding custom repo support is a bit harder than it sounds from the GUI ... this is an effective middle ground solution, though.
