### ISSUE TITLE
On local VMs, some users error on writing to default vhost index file

### ISSUE THREAD

**Issue by jtreminio** [puphpet/puphpet#1540]
Apache/Nginx both.

Some user's permissions are too restrictive on their host machine.

For example, sharing local directory `~/foo/bar` into VM's `/var/www`, puphpet creates and edits the contents of the webserver's default vhost file: `/var/www/html/index.html`.

If user's host's directory permissions are too restrictive, Vagrant will not be able to write to this file, erroring the provisioning process.

**Comment by jkenneydaniel** [comment]
Per #1512 - this is an issue with host permissions on the source directory, but I have mine set to be owned by macuser:staff with 0777 permissions and it still doesn't work? Googling for proper permissions for a Vagrant source dir says that Vagrant can't actually modify permissions for folders/files in its /vagrant directory?

**Comment by jkenneydaniel** [comment]
It seems specifying the shared folder being mounted with NFS resolves these issues?
