### ISSUE TITLE
Module Database:Mysql: Cant't add user

### ISSUE THREAD

**Issue by Bravehartk2** [puphpet/puphpet#1542]
I see an error 500 in Firebug when trying to add another database user, grant, or database:
Failed to load resource: the server responded with a status of 500 (Internal Server Error)
https://puphpet.com/extension/mysql/add-grant?_=1429468800223 Failed to load resource: the server responded with a status of 500 (Internal Server Error)

**Comment by jtreminio** [comment]
Fixed by 7340982
