### ISSUE TITLE
mysql import always fails

### ISSUE THREAD

**Issue by colby-swandale** [puphpet/puphpet#155]
``` bash
Error: /Stage[main]//Mysql::Db[startupsmart]/Exec[startupsmart-import]: Failed to call refresh: /usr/bin/mysql startupsmart < /var/www/startupsmart.sql returned 1 instead of one of [0]
Error: /Stage[main]//Mysql::Db[startupsmart]/Exec[startupsmart-import]: /usr/bin/mysql startupsmart < /var/www/startupsmart.sql returned 1 instead of one of [0]
```

one of the options allows you import sql from a file but when puppet tries to import the file it will always fail due to permissions.

``` bash
$ /usr/bin/mysql <database> < /var/www/<import file>
```

Obviously from the command this is due to the fact the the anonymous user doesn't have access to the database.

| user | host | db |
| :-: | :-: | :-: |
|  | % | test |
|  | % | test_% |
| user | localhost | database |

**Comment by loostro** [comment]
Same here. Getting `ERROR 1045 (28000): Access denied for user 'vagrant'@'localhost' (using password: YES)`. I can log in as root and I see `vagrant` user on `%` host is created. Why can't I log in?
