### ISSUE TITLE
DigitalOcean: Add new FRA1 data center

### ISSUE THREAD

**Issue by IT-Cru** [puphpet/puphpet#1552]
From DigitalOcean newsletter e-mail:

The new German region is open for business!

We’re thrilled to announce the opening of our new FRA1 facility, located in Frankfurt, Germany.

This region also serves Germany’s neighboring countries with unparalleled connectivity and speed, due to its placement on the German Commercial Internet Exchange (DE-CIX) – the largest Internet exchange point worldwide by peak traffic.

FRA1 features our fastest-ever SSDs, 40GbE networking on each hypervisor and the full range of DigitalOcean features including Metadata, CoreOS, and IPv6.

You can deploy a server to our Frankfurt region now from the Droplet create page.

**Comment by bountin** [comment]
@jtreminio / @IT-Cru #1580 got merged, so this is also done :-)
