### ISSUE TITLE
PostgreSQL >= 9.4 support

### ISSUE THREAD

**Issue by arogachev** [puphpet/puphpet#1553]
What about adding PosgreSQL >= 9.4 version?

**Comment by bountin** [comment]
I've just changed postgresql.settings.global.version to '9.4' in my puphpet/config.yaml and everything still works as the used puppet module already supports 9.4. 

What I don't know is whether it is enough to add '9.4' to https://github.com/puphpet/puphpet/blob/master/src/Puphpet/MainBundle/Resources/config/postgresql/available.yml or if more work is required. Sadly I don't have time to test this at the moment but may in the future (or somebody else does this).

**Comment by arogachev** [comment]
Yes, I changed it like that too. 9.4 was installed, but 9.3 was also stiil active. So I have to do:

```
sudo service postgresql stop
sudo apt-get purge postgresql-9.3
```

and then restart.

It's better to have it out of the box without some extra manual actions.
