### ISSUE TITLE
An oddball ssh connection issue (pre-php-fpm tag - modified)

### ISSUE THREAD

**Issue by raptor65** [puphpet/puphpet#1562]
@jtreminio 

First things first: Thanks for your recent help. I have now got a VM running Apache 2.2 with mod_mono up and running sucessfully and repeatably from the pre-php-fpm tag.

Now that I have got this far, I want to make the standard base box available to others, with the ability to make minor individual configuration changes to meet specific development needs. To this end, I have tried making some changes to the standard Vagrantfile as per the changes in later puphpet versions, to enable the use of an additional, optional config-custom.yaml file.

i.e.

````ruby
    require "#{dir}/puphpet/ruby/deep_merge.rb"

    configValues = YAML.load_file("#{dir}/puphpet/config.yaml")

    if File.file?("#{dir}/puphpet/config-custom.yaml")
      custom = YAML.load_file("#{dir}/puphpet/config-custom.yaml")
      configValues.deep_merge!(custom)
    end
````

This is giving me some very peculiar results and I am rather hoping that you might have experienced the same issues putting this together in the first place and therefore be able to offer a solution easily.

If I make the relevant changes and then add a custom-config.yaml file (or even if I merely create an empty custom config file), everything seems to run OK, I can ssh in etc *while the vm is building*, but as soon as the build completes (and before the execution of any exec-once or exec-always files) it is no longer possible to ssh into the VM. If I already have an ssh session open before the main buidl completes, that (usually) reamins accessible.

If I dump the deep merged config file to the console [ ``puts YAML::dump(configValues)`` ] paste that into config.yaml and delete the custom-config.yaml (i.e. the resulting configValues hash is identical in each case), everything works perfectly and I can log in to the guest machine on completion without difficulty.

It is as if the mere process of importing and merging a second yaml file on the host is causing some kind of connection issue. This makes absolutely no sense to me and I cam completely lost for ideas!

**Comment by jtreminio** [comment]
It's the firewall. It blocks *all* ports except the ones defined. Have you changed anything within the firewall.pp file?

**Comment by raptor65** [comment]
Apologies - I did mean to get back to you regarding this. I've verified that it's *not* a firewall issue, but due to other pressures on time and as I can get a VM up and running by manually merging the config files, I was going to suggest closing this anyway. Will feedback what (if anything) I find when I have time to look into it deeper.
Thanks for your help.

**Comment by raptor65** [comment]
Just an update, which might prove helpful to others: Further investigation revealed that it was indeed a VM firewall issue (apologies for questioning that!). After some modifications to hiera,yaml and the firewall and server node puppet files to ensure that the firewall rules were being properly read and re-written after the rule reset in firewall.pp, I got this working; With some additional tweaking of the Vagrantfile and other node files, it now seems to be working reliably :-)
Many thanks for all your great efforts.
