### ISSUE TITLE
Standard archive fails provisioning

### ISSUE THREAD

**Issue by lachieh** [puphpet/puphpet#1579]
If I download the standard config from the site, I get this error

```bash
==> default: Notice: Finished catalog run in 317.07 seconds
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

The only error is `==> default: Error: /Stage[main]/Composer/File[/usr/local/bin/composer]: Could not evaluate: Could not retrieve information from environment production source(s) file:/tmp/composer.phar`

If I disable the composer install, the provision works fine.

**Comment by jtreminio** [comment]
This was fixed in bac142d853a262cd2d30e69edc27b239c1a9430f
