### ISSUE TITLE
apache not starting

### ISSUE THREAD

**Issue by digitaf** [puphpet/puphpet#1581]
Hi,

Apache not starting here is what i got from the log
==> default: Error: Could not start Service[httpd]: Execution of '/sbin/service httpd start' returned 1: 
==> default: Error: /Stage[main]/Apache::Service/Service[httpd]/ensure: change from stopped to running failed: Could not start Service[httpd]: Execution of '/sbin/service httpd start' returned 1: 

and my config.yaml file

vagrantfile:
    target: local
    vm:
        box: puphpet/centos65-x64
        box_url: puphpet/centos65-x64
        hostname: ''
        memory: '512'
        cpus: '1'
        chosen_provider: virtualbox
        network:
            private_network: 192.168.56.101
            forwarded_port:
                vflnp_b6hblf8eum8k:
                    host: '5310'
                    guest: '22'
        post_up_message: ''
        provider:
            virtualbox:
                modifyvm:
                    natdnshostresolver1: on
            vmware:
                numvcpus: 1
            parallels:
                cpus: 1
        provision:
            puppet:
                manifests_path: puphpet/puppet
                manifest_file: site.pp
                module_path: puphpet/puppet/modules
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
                    - '--parser future'
        synced_folder:
            vflsf_77qofzcq561l:
                source: ~/Documents/Sites/
                target: /var/www/local.dev
                sync_type: default
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    exclude:
                        - .vagrant/
                        - .git/
                    auto: 'true'
                owner: www-data
                group: www-data
            vflsf_u6pzrjccyqx0:
                source: ~/Dropbox/
                target: /var/www/local.dev/dropbox
                sync_type: default
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    exclude:
                        - .vagrant/
                        - .git/
                    auto: 'true'
                owner: www-data
                group: www-data
        usable_port_range:
            start: 10200
            stop: 10500
    ssh:
        host: null
        port: null
        private_key_path: null
        username: vagrant
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'
    vagrant:
        host: detect
server:
    install: '1'
    packages:
        - vim-common
        - htop
users_groups:
    install: '1'
    groups: {  }
    users: {  }
firewall:
    install: '1'
    rules: {  }
cron:
    install: '1'
    jobs: {  }
nginx:
    install: '0'
    settings:
        default_vhost: 1
        proxy_buffer_size: 128k
        proxy_buffers: '4 256k'
    upstreams: {  }
    vhosts:
        nxv_f6xmqirqiqdl:
            server_name: awesome.dev
            server_aliases:
                - www.awesome.dev
            www_root: /var/www/awesome
            listen_port: '80'
            index_files:
                - index.html
                - index.htm
                - index.php
            client_max_body_size: 1m
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_port: '443'
            rewrite_to_https: '1'
            spdy: '1'
            locations:
                nxvl_2xahy4jud9r7:
                    location: /
                    autoindex: off
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
                    fastcgi: ''
                    fastcgi_index: ''
                    fastcgi_split_path: ''
                nxvl_pwwcdrqqex85:
                    location: '~ \.php$'
                    autoindex: off
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
                    fastcgi: '127.0.0.1:9000'
                    fastcgi_index: index.php
                    fastcgi_split_path: '^(.+\.php)(/.*)$'
                    fast_cgi_params_extra:
                        - 'SCRIPT_FILENAME $request_filename'
                        - 'APP_ENV dev'
    proxies: {  }
apache:
    install: '1'
    settings:
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - proxy_fcgi
        - rewrite
    vhosts:
        av_qwzdhs9fkxex:
            servername: local.dev
            serveraliases:
                - www.local.dev
                - local.dev
            docroot: /var/www/local.dev
            port: '80'
            setenv:
                - 'APP_ENV dev'
            custom_fragment: ''
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            directories:
                avd_83jppuqtw0ar:
                    path: /var/www/local.dev
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - 'all granted'
                    custom_fragment: ''
                    files_match:
                        avdfm_9idavhlrhjbw:
                            path: \.php$
                            sethandler: 'proxy:fcgi://127.0.0.1:9000'
                            custom_fragment: ''
                            provider: filesmatch
                    provider: directory
php:
    install: '1'
    settings:
        version: '56'
    modules:
        php:
            - cli
            - intl
            - mcrypt
        pear: {  }
        pecl:
            - pecl_http
    ini:
        display_errors: On
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
        date.timezone: UTC
    fpm_ini:
        error_log: /var/log/php-fpm.log
    fpm_pools:
        phpfp_a3lan7p4cwov:
            ini:
                prefix: www
                listen: '127.0.0.1:9000'
                security.limit_extensions: .php
                user: www-user
                group: www-data
    composer: '1'
    composer_home: ''
xdebug:
    install: '1'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
xhprof:
    install: '0'
wpcli:
    install: '0'
    version: v0.17.1
drush:
    install: '0'
    version: 6.3.0
ruby:
    install: '1'
    versions: {  }
python:
    install: '1'
    packages: {  }
    versions: {  }
nodejs:
    install: '1'
    npm_packages: {  }
hhvm:
    install: '0'
    nightly: 0
    composer: '1'
    composer_home: ''
    settings: {  }
    server_ini:
        hhvm.server.host: 127.0.0.1
        hhvm.server.port: '9000'
        hhvm.log.use_log_file: '1'
        hhvm.log.file: /var/log/hhvm/error.log
    php_ini:
        display_errors: On
        error_reporting: '-1'
        date.timezone: UTC
mysql:
    install: '1'
    settings:
        version: '5.6'
        root_password: root
        override_options: {  }
    adminer: 0
    users:
        mysqlnu_jm3qzcu5c4vc:
            name: dbuser
            password: '123'
    databases:
        mysqlnd_mkdcv9eoxhx1:
            name: dbname
            sql: ''
    grants:
        mysqlng_d55d90gh2b4w:
            user: dbuser
            table: '*.*'
            privileges:
                - ALL
postgresql:
    install: '0'
    settings:
        global:
            encoding: UTF8
            version: '9.3'
        server:
            postgres_password: '123'
    databases: {  }
    users: {  }
    grants: {  }
    adminer: 0
mongodb:
    install: '0'
    settings:
        auth: 1
        bind_ip: 127.0.0.1
        port: '27017'
    databases: {  }
redis:
    install: '0'
    settings:
        conf_port: '6379'
sqlite:
    install: '0'
    adminer: 0
    databases: {  }
mailcatcher:
    install: '1'
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '1080'
        mailcatcher_path: /usr/local/rvm/wrappers/default
        from_email_method: inline
beanstalkd:
    install: '0'
    settings:
        listenaddress: 0.0.0.0
        listenport: '13000'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: 0
    binlogdir: /var/lib/beanstalkd/binlog
rabbitmq:
    install: '0'
    settings:
        port: '5672'
    users: {  }
    vhosts: {  }
    plugins: {  }
elastic_search:
    install: '0'
    settings:
        version: 1.4.1
        java_install: true
solr:
    install: '0'
    settings:
        version: 4.10.2
        port: '8984'

**Comment by it-scripter** [comment]
Here the same

**Comment by maces** [comment]
Same here (Ubuntu 10.04).
When login in via SSH and starting apache2 manually I get the following error:
```
root@packer-virtualbox-iso:/home/vagrant# /etc/init.d/apache2 start
[FAIL] Starting web server: apache2 failed!
[warn] The apache2 configtest failed. ... (warning).
Output of config test was:
AH00526: Syntax error on line 6 of /etc/apache2/apache2.conf:
The port number "#<Object:0x00000102af6ee8>" is outside the appropriate range (i.e., 1..65535).
Action 'configtest' failed.
The Apache error log may have more information.
```
changing the line to my ServerName ("awesome.dev") and manually starting apache worked.
Reprovisioning results in failing again however.

**Comment by maces** [comment]
A very similiar config from yesterday worked (also today), so I had a look at the diff of both puphpet directorys.
Comment line 209 in puphpet/vagrant/Vagrantfile-local:
```
#'fqdn'             => "#{config.vm.hostname}",
```
A 'vagrant provision' and apache started again 
I'm Going to detroy and build from scratch now.

**Comment by Kryniol** [comment]
Same here (Ubuntu 14.04 x64). Temporary solution is to set vagrantfile.vm.hostname in config.yaml to anything non-empty and run vagrant provision.

**Comment by BEEware** [comment]
Same here:

```
Starting httpd: AH00526: Syntax error on line 6 of /etc/httpd/conf/httpd.conf:
The port number "#<Object:0x00000101ae2818>" is outside the appropriate range (i.e., 1..65535).
```

**Comment by jtreminio** [comment]
Can one of you paste your config.yaml with proper formatting?

**Comment by hollsk** [comment]
Here's a formatted pastebin from Debian Wheezy: http://pastebin.com/F35cpKCL

**Comment by jtreminio** [comment]
@hollsk 

    vhosts:
        av_i2oqpfy139pe:
            servername: '*'
            serveraliases:
                - www.awesome.dev
            docroot: /var/www/%2

`servername` can't be `*`. Only `serveraliases` can contain that. Also, your `docroot` is invalid.

**Comment by hollsk** [comment]
Yep, that's not what's causing it to fail to start, though - it's the SSL block it's unhappy about (dealt with by commenting the whole SSL block out in sites-enabled). 

I do also have to comment out this from local-vagrant to even get that far:

    #'fqdn'             => "#{config.vm.hostname}",

**Comment by jtreminio** [comment]
@hollsk are you running this config on a new archive? There's code to check if the ssl key is defined and `1` or `'1'`:

    vhosts:
        av_i2oqpfy139pe:
            servername: '*'
            serveraliases:
                - www.awesome.dev
            docroot: /var/www/%2
            port: '80'
            setenv:
                - 'APP_ENV dev'
            custom_fragment: ''
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''

**Comment by hollsk** [comment]
Yes, it is a new archive - do I need to do something in particular when creating it? I've left the "Enable SSL" box unticked in the builder, but perhaps there's something else I should be doing?

(In any case it seems this is different issue to the one logged here originally, sorry for the accidental derail)

**Comment by jtreminio** [comment]
@hollsk Please open a new ticket with your issue.

Everyone else, closing as I've received no response. Open a new ticket if you're still experiencing this issue **with a new config**, and make sure to paste your config code formatted.
