### ISSUE TITLE
vagrant privision failed, but vagrant up at first time is ok. Could not start Service[php-fpm]

### ISSUE THREAD

**Issue by parotikov** [puphpet/puphpet#1589]
Hi. here is my config.yaml:
http://pastebin.com/Bv7g4VrP
I make a new puphpet box, succesfully install it, but when I make vagrant provision I get this errors:
Error: Could not start Service[php-fpm]: Execution of '/sbin/service php-fpm start' returned 1:
==> default: Error: /Stage[main]/Main/Service[php-fpm]/ensure: change from stopped to running failed: Could not start Service[php-fpm]: Execution of '/sbin/service php-fpm start' returned 1:

**Comment by ngandemer** [comment]
Hi, i have the same issue and i find a workaround that should be debug in source.

On centos 6.*, in file /etc/init.d/php-fpm pid file is expected to be at location :
/var/run/php-fpm/php-fpm.pid
as seen in line 111, 
pidfile=${PIDFILE-/var/run/php-fpm/php-fpm.pid}

However, in puppet manifests "vagrant\puphpet\puppet\modules\puphpet\manifests\php\fpm/ini.pp", i have found that :
$pid_file = $::osfamily ? {
      'debian' => '/run/php-fpm.pid',
      'redhat' => '/var/run/php-fpm.pid',
    }

and i replace it by :
$pid_file = $::osfamily ? {
      'debian' => '/run/php-fpm.pid',
      'redhat' => '/var/run/php-fpm/php-fpm.pid', // like seen in init.d/php-fpm file
    }

after that i provision and reload again and evrything is ok for me !!!!

First test from ssh : 
# service php-fpm status
php-fpm (pid  3989) is running...

**Comment by tnory56** [comment]
This seems to be cropping up again on newest code base. Under params.pp line 77. Vagrant up works fine just when provisioning I would receive the same error as above.

**Comment by kevin-barrientos** [comment]
Another work around is just to run `sudo killall php-fpm` before you provision.
