### ISSUE TITLE
Update the `puppetlabs/rabbitmq` module

### ISSUE THREAD

**Issue by thiagotalma** [puphpet/puphpet#1594]
Hello Juan,

 I have faced enough problems trying to install RabbitMQ through Puphpet, as you may already know given the issues that I have created.

Today, trying to better understand the problem, I realized that you use a version of `puppetlabs/rabbitmq` released in July 2014.

I tested with the most current version and all the problems that I face are resolved.

I wonder if there is any reason for you to use such an old version of `puppetlabs/rabbitmq`. There is a problem that I could not identify?

**Comment by jtreminio** [comment]
No reason, I update them as I realize things are broken. I'll take a look at updating.
