### ISSUE TITLE
Add MailHog support

### ISSUE THREAD

**Issue by jtreminio** [puphpet/puphpet#1596]
Possibly to replace MailCatcher? https://github.com/mailhog/MailHog

**Comment by ptt-homme** [comment]
[MailDev](http://djfarrelly.github.io/MailDev/) is a good option too, really nice project!

**Comment by ProPheT777** [comment]
:+1: for MailDev

**Comment by jtreminio** [comment]
The reason I like mailhog over mailcatcher and maildev is it's in Go: it has no dependencies other than its binary.

Mailcatcher requires ruby, and maildev requires npm.

**Comment by Danielss89** [comment]
+1 for MailHog ;)

**Comment by thiagotalma** [comment]
+1 for MailHog
Without hesitating.
