### ISSUE TITLE
E_FAIL during vagrant up

### ISSUE THREAD

**Issue by funderburkjim** [puphpet/puphpet#1598]
This is my first time trying puphpet to provision a vagrant machine.  Unfortunately, vagrant up  bombed after downloading the box.
 I am running this on Windows 7, with vagrant 1.6.3, and virtualbox 4.3.6.

The config.yaml and log file of 'vagrant up' session are [here](https://gist.github.com/funderburkjim/eba9380aa4ddecb4e2ae).

I was running this in the GitBash Shell.

The idea of puphpet is terrific, since it permits those of us who know very little about sysadmin stuff to make use of vagrant to construct good development environments.

Hope my problem is some dumb mistake that I made and that you will see at once.
Thanks for looking.

**Comment by jtreminio** [comment]
> vagrant 1.6.3

You should upgrade.

**Comment by funderburkjim** [comment]
I upgraded vagrant.  Then `vagrant up` hung at:
```
==> default: Clearing any previously set network interfaces...
```
Did `vagrant destroy` and 
Updated Virtutalbox.
Then `vagrant up` finished to completion -
  Now a functioning virtual machine is working fine.

Thanks for the help, and for the project!
