### ISSUE TITLE
Centos 7

### ISSUE THREAD

**Issue by kimlop** [puphpet/puphpet#1605]
when you planned to support Centos 7 ?

**Comment by filmjbrandon** [comment]
+1

**Comment by ncatanchin** [comment]
Any update on this ticket, can we expect support for CentOS 7 in the near future? Thanks

**Comment by markbucknellcc** [comment]
+1.
Another major problem with this appears to be that CentOS 7 no longer comes with Guest Additions preinstalled.

**Comment by jtreminio** [comment]
Done.
