### ISSUE TITLE
Vagrant up crash with custom (dot) files on Windows 

### ISSUE THREAD

**Issue by dredav** [puphpet/puphpet#1607]
> ==> default: Notice: /Stage[main]/Main/Exec[dotfiles]/returns: cp: target `\r' is not a directory
> ==> default: Notice: /Stage[main]/Main/Exec[dotfiles]/returns: sh: 2: Syntax error: "&&" unexpected
> ==> default: Error: cp -r /vagrant/puphpet/files/dot/.[a-zA-Z0-9]* /home/vagrant/ \
> 
> ==> default:               && chown -R vagrant /home/vagrant/.[a-zA-Z0-9]* \
> 
> ==> default:               && cp -r /vagrant/puphpet/files/dot/.[a-zA-Z0-9]* /root/ returned 2 instead of one of [0,1]
> ==> default: Error: /Stage[main]/Main/Exec[dotfiles]/returns: change from notrun to 0 1 failed: cp -r /vagrant/puphpet/files/dot/.[a-zA-Z0-9]* /home/vagrant/ \
> 
> ==> default:               && chown -R vagrant /home/vagrant/.[a-zA-Z0-9]* \
> 
> ==> default:               && cp -r /vagrant/puphpet/files/dot/.[a-zA-Z0-9]* /root/ returned 2 instead of one of [0,1]
> ==> default: Info: /Stage[main]/Main/Resolvconf::File[/etc/resolv.conf]/File[/etc/resolv.conf]: Filebucketed /etc/resolv.conf to puppet with sum 2a8dd35b454f121e0cd5a7776be2837a

**Comment by jtreminio** [comment]
Can you give me examples of the filenames you have?

**Comment by dredav** [comment]
> puphpet/files/dot/.bash_aliases
> puphpet/files/dot/.bash_git
> puphpet/files/dot/.vimrc
> puphpet/files/dot/ssh/id_rsa
> puphpet/files/dot/ssh/id_rsa.ppk
> puphpet/files/dot/ssh/id_rsa.pub
> puphpet/files/dot/ssh/insecure_private_key
> puphpet/files/dot/ssh/root_id_rsa
> puphpet/files/dot/ssh/root_id_rsa.ppk
> puphpet/files/dot/ssh/root_id_rsa.pub
> puphpet/files/exec-always/empty
> puphpet/files/exec-always-unprivileged/empty
> puphpet/files/exec-once/empty
> puphpet/files/exec-once/linux_compile_php.sh
> puphpet/files/exec-once/linux_compile_libs.sh
> puphpet/files/exec-once/setup_database.sh
> puphpet/files/exec-once-unprivileged/empty
> puphpet/files/startup-always/empty
> puphpet/files/startup-always-unprivileged/empty
> puphpet/files/startup-always-unprivileged/start_php_fpm.sh
> puphpet/files/startup-once/empty
> puphpet/files/startup-once-unprivileged/empty

All works fine on my os x and linux operating system, but it dont work on windows... The puphpet (on windows) is located under Y:\projectA\

**Comment by jtreminio** [comment]
==> default: Notice: /Stage[main]/Main/Exec[dotfiles]/returns: cp: target `\r' is not a directory

Windows is replacing your newlines `\n` with `\r\n`.

You'll need to use something like dos2unix: https://kb.iu.edu/d/acux
