### ISSUE TITLE
Still getting MySQL failure during 'vagrant up'

### ISSUE THREAD

**Issue by chetcuti** [puphpet/puphpet#1608]
I reported this problem via issue #1606, and it was marked as fixed, however I'm still having the same problem.

My config.yaml file: https://gist.github.com/chetcuti/c41e98d013d971e4d0e3

When I run 'vagrant up' for the first time on a new PuPHPet setup it seems as though MySQL is causing issues, and the output I get is:

"The SSH command responded with a non-zero exit status. Vagrant assumes that this means the command failed. The output for this command should be in the log above. Please read the output to determine what went wrong."

The information that's output to the screen that leads me to believe this is MySQL related is:

==> default: Notice: /Stage[main]/Mysql::Server::Service/File[/var/log/mysqld.log]: Dependency Exec[mysql_install_db] has failures: true
==> default: Warning: /Stage[main]/Mysql::Server::Service/File[/var/log/mysqld.log]: Skipping because of failed dependencies
==> default: Notice: /Stage[main]/Mysql::Server::Root_password/Mysql_user[root@localhost]: Dependency Exec[mysql_install_db] has failures: true
==> default: Notice: /Stage[main]/Mysql::Server::Root_password/File[/root/.my.cnf]: Dependency Exec[mysql_install_db] has failures: true
==> default: Error: Could not prefetch mysql_user provider 'mysql': Execution of '/usr/bin/mysql -NBe SELECT CONCAT(User, '@',Host) AS User FROM mysql.user' returned 1: ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)
==> default: Warning: /Stage[main]/Mysql::Server::Root_password/Mysql_user[root@localhost]: Skipping because of failed dependencies
==> default: Warning: /Stage[main]/Mysql::Server::Root_password/File[/root/.my.cnf]: Skipping because of failed dependencies
==> default: Notice: /Stage[main]/Main/Mysql_user[domainmod@localhost]: Dependency Exec[mysql_install_db] has failures: true
==> default: Warning: /Stage[main]/Main/Mysql_user[domainmod@localhost]: Skipping because of failed dependencies
==> default: Notice: /Stage[main]/Mysql::Server/Anchor[mysql::server::end]: Dependency Exec[mysql_install_db] has failures: true
==> default: Warning: /Stage[main]/Mysql::Server/Anchor[mysql::server::end]: Skipping because of failed dependencies
==> default: Notice: /Stage[main]/Main/Mysql_database[domainmod]: Dependency Exec[mysql_install_db] has failures: true
==> default: Error: Could not prefetch mysql_database provider 'mysql': Execution of '/usr/bin/mysql -NBe show databases' returned 1: ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)
==> default: Warning: /Stage[main]/Main/Mysql_database[domainmod]: Skipping because of failed dependencies
==> default: Error: Could not prefetch mysql_grant provider 'mysql': Execution of '/usr/bin/mysql -NBe SELECT CONCAT(User, '@',Host) AS User FROM mysql.user' returned 1: ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)
==> default: Notice: /Stage[main]/Main/Mysql_grant[domainmod@localhost/*.*]: Dependency Exec[mysql_install_db] has failures: true
==> default: Warning: /Stage[main]/Main/Mysql_grant[domainmod@localhost/*.*]: Skipping because of failed dependencies

**Comment by jtreminio** [comment]
You applied the changes, right?

Can you print out your whole output from `$ vagrant up`? Also your config.yaml

**Comment by jtreminio** [comment]
Another fix in 746e759

Also note: MySQL module comes packaged with PHP and there is no need to include it under php modules. In fact, it will fail. You should remove it.

**Comment by chetcuti** [comment]
Success! Between your updates and removing the mysql module, everything's working now! Well, everything installs properly, at least, I'm now having  permissions issues on /var/lib/php/session/, but I'm going to submit that in a separate issue.

Thanks for your help on this one! And thanks for PuPHPet in general! It's such an incredibly easy way to test multiple environments.
