### ISSUE TITLE
DNS (not) resolving

### ISSUE THREAD

**Issue by rianorie** [puphpet/puphpet#1612]
I recently switched from virtualbox to vmware (workstation, on linux) much to my own happiness. Got me a license from vagrant to be able to to use them together and I figure, happiness shall ensue! Sadly, no.

No matter what configuration I tried, I was unable to get my newly created puphpet vagrant instances to provision properly. After reading the log info it came down to DNS issues. If I sshed into the box and ran `sudo service resolvconf restart` it would start working on the server itself, but during provisioning not so much. Turns out, recently there was a new addition to the config files. A configuration that added google nameservers to the resolv.conf file, generally a good idea, I use them on occasion as well.. But on the nodes on my machine, not so much. I commented out the lines below and instant happiness, kinda. There was another issue but I'll create a separate issue for that.

file: puphpet/puppet/nodes/Server.pp

    resolvconf::file { $resolve_conf_file:
       header     => 'This file is managed by Puppet, do not edit',
       nameserver => [ '8.8.8.8', '8.8.4.4' ],
     }

with those commented everything works again.

Config: https://gist.github.com/rianorie/7f4cb934713453cc7da8

Mind, the config was not a factor in this. I think I tried as much as 7 different configs including a debian version.

**Comment by jtreminio** [comment]
Weird! I wonder what could be causing this issue? I hadn't tried this out on VMWare, only Virtualbox, didn't think they'd have differences like this.
