### ISSUE TITLE
Setting ownership

### ISSUE THREAD

**Issue by rianorie** [puphpet/puphpet#1613]
==> default: Error: Failed to set owner to '0': Operation not permitted - /var/www
    ==> default: Error: /Stage[main]/Main/File[/var/www]/owner: change from www-data to root failed: Failed to set owner to '0': Operation not permitted - /var/www

After this the world ends, pretty much. The whole log from there-on-out consists of errors like:

    ==> default: Notice: /Stage[main]/Main/Exec[exec mkdir -p /var/www/html @ key _]: Dependency File[/var/www] has failures: true
    ==> default: Warning: /Stage[main]/Main/Exec[exec mkdir -p /var/www/html @ key _]: Skipping because of failed dependencies

Where `Skipping because of failed depdendencies` is the main identifier.

Config file: https://gist.github.com/rianorie/7f4cb934713453cc7da8

**Comment by jtreminio** [comment]
Can you try using nfs instead of default for shared folder types? This has been a thorn in puphpet's side since it started, and it all usually boils down to each user's permissions on host machine.
