### ISSUE TITLE
nginx config in yaml??

### ISSUE THREAD

**Issue by designermonkey** [puphpet/puphpet#1628]
This is not a good idea.

I have spent two days trying to wrangle puphpet to let me use our customised nginx vhosts to no avail. No matter what I do, I can't do it. I've tried changing the locations, changing the servers, I've even tried making a script to just add my custom config in using `exec-always` but even that never runs!

Why is it not built to allow us to point to a folder in our project, and load nginx server configs from there? Why would anyone obfuscate something as customisable and complicated as nginx config into yaml of all things?

Here's the suggestion... As with `synced_folder` allow nginx (and others like apache for example) to load configs from a folder on the host machine.

We use `.vhosts` in our projects.

**Comment by royFromIT** [comment]
Have you tried turning it off and on again?

**Comment by thiagotalma** [comment]
I solved this problem by creating a synchronized folder and running a script that create a synlink in /etc/nginx/conf.d/mysites.conf

Painless.

**Comment by designermonkey** [comment]
I can't get any scripts to run. ever.

**Comment by jtreminio** [comment]
The whole point is to get as much configuration done within config.yaml as possible.

There are some exceptions, like Apache custom_fragments, and Nginx will be getting this as well.

Loading configs wholesale from a directory is not in the spirit of puphpet.
