### ISSUE TITLE
Upload config and get generated zip right back.

### ISSUE THREAD

**Issue by RickJensen** [puphpet/puphpet#1629]
Add the possibility to upload config and get zip-file right back?
Just an alternative way of getting the generated Vagrant file with folders. Could then be easily used in a script to automate the download / unpacking.

I keep the generated puphpet folders inside a git repo (together with the project), this way I can share the vagrant machine with others. Adding said functionality could reduce this to just the config.yaml and a script to get the latest version from puphpet without having to upload file and download via browser.

**Comment by ddinchev** [comment]
:+1: I want this as well. After committing puphpet files, I end up having like "10% PHP" in my project statistics, rest is puphpet files. It's like commiting composer dependencies together with composer.json file...

**Comment by jtreminio** [comment]
As of f72f57db339a62949748646cf657f513d178fe99 you can omit the whole of the `puphpet/puppet/modules` directory contents (but not the directory itself) and puphpet will automatically download the modules for you.

Note that this does not yet implement versioning, so you will always get the latest versions of all modules... which may not be !00% stable.

**Comment by RickJensen** [comment]
Cool Juan. didn't know that one! Still not quite the same as the feature requested as it will leave quite a lot of files/folders in the repo. My suggestion was about setting up a single api request, eg: puphpet.com/generate where we can post the configuration and get the zip right back (instead of using the ui).

**Comment by ddinchev** [comment]
@RickJensen what you describe is actually a really good solution but I guess would result in costlier service. @jtreminio maybe speak to digital ocean, they do provide free server resources for open projects.
