### ISSUE TITLE
'vagrant up' cannot start a VM instance

### ISSUE THREAD

**Issue by stepansib** [puphpet/puphpet#1634]
Im trying to launch VM via vagrant with config made by puphpet.com

Host machine: Windows 7 64
VirtualBox: 4.3.10
Vagrant: 1.7.2

The process freezes at stage: "Setting up VM name..."
If i open system process list i dont see any VBoxHeadless process

Here you can see "vagrant up --debug" log, last 30 lines:

    DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 32000
    DEBUG subprocess: Exit status: 0
     INFO warden: Calling IN action: #<Vagrant::Action::Builtin::HandleForwardedPortCollisions:0x26d1ad0>
    DEBUG environment: Attempting to acquire process-lock: fpcollision
    DEBUG environment: Attempting to acquire process-lock: dotlock
     INFO environment: Acquired process lock: dotlock
     INFO environment: Released process lock: dotlock
     INFO environment: Acquired process lock: fpcollision
     INFO handle_port_collisions: Detecting any forwarded port collisions...
    DEBUG handle_port_collisions: Extra in use: []
    DEBUG handle_port_collisions: Remap: {}
    DEBUG handle_port_collisions: Repair: true
     INFO warden: Calling IN action: #<VagrantPlugins::ProviderVirtualBox::Action::PrepareNFSValidIds:0x29cd228>
     INFO subprocess: Starting process: ["C:\\Program Files\\Oracle\\VirtualBox\\VBoxManage.exe", "list", "vms"]
    DEBUG subprocess: Selecting on IO
    DEBUG subprocess: stdout: "vagrant_default_1431586560599_21228" {2ec4ab69-2eab-456e-80e3-c655a907b58f}
    DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 32000
    DEBUG subprocess: Exit status: 0
     INFO warden: Calling IN action: #<VagrantPlugins::SyncedFolderNFS::ActionCleanup:0x2a566d0>
    DEBUG host: Searching for cap: nfs_prune
    DEBUG host: Checking in: windows
     INFO nfs: Host doesn't support pruning NFS. Skipping.
     INFO warden: Calling IN action: #<Vagrant::Action::Builtin::SyncedFolderCleanup:0x332dcc0>
     INFO subprocess: Starting process: ["C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\/powershell.EXE", "-NoProfile", "-ExecutionPolicy", "Bypass", "$PSVersionTable.PSVersion.Major"]
    DEBUG subprocess: Selecting on IO
    DEBUG subprocess: stdout: 2
And here is my puphpet config.yaml: 

    vagrantfile:
        target: local
        vm:
            box: puphpet/ubuntu1404-x64
            box_url: puphpet/ubuntu1404-x64
            hostname: local.puphpet
            memory: '512'
            cpus: '1'
            chosen_provider: virtualbox
            network:
                private_network: 192.168.56.101
                forwarded_port:
                    vflnp_puvoa8hbnwzi:
                        host: '7062'
                        guest: '22'
            post_up_message: ''
            provider:
                virtualbox:
                    modifyvm:
                        natdnshostresolver1: on
                vmware:
                    numvcpus: 1
                parallels:
                    cpus: 1
            provision:
                puppet:
                    manifests_path: puphpet/puppet
                    manifest_file: site.pp
                    module_path: puphpet/puppet/modules
                    options:
                        - '--verbose'
                        - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
                        - '--parser future'
            synced_folder:
                vflsf_csg6i60dtv02:
                    source: ./
                    target: /var/www
                    sync_type: smb
                    rsync:
                        args:
                            - '--verbose'
                            - '--archive'
                            - '-z'
                        exclude:
                            - .vagrant/
                            - .git/
                        auto: 'true'
                    owner: www-data
                    group: www-data
            usable_port_range:
                start: 10200
                stop: 10500
        ssh:
            host: null
            port: null
            private_key_path: null
            username: vagrant
            guest_port: null
            keep_alive: true
            forward_agent: false
            forward_x11: false
            shell: 'bash -l'
        vagrant:
            host: detect
    server:
        install: '1'
        packages: {  }
    users_groups:
        install: '1'
        groups: {  }
        users: {  }
    firewall:
        install: '1'
        rules: {  }
    cron:
        install: '1'
        jobs: {  }
    nginx:
        install: '0'
        settings:
            default_vhost: 1
            proxy_buffer_size: 128k
            proxy_buffers: '4 256k'
        upstreams: {  }
        vhosts:
            nxv_vqzc8icojox0:
                server_name: awesome.dev
                server_aliases:
                    - www.awesome.dev
                www_root: /var/www/awesome
                listen_port: '80'
                index_files:
                    - index.html
                    - index.htm
                    - index.php
                client_max_body_size: 1m
                ssl: '0'
                ssl_cert: ''
                ssl_key: ''
                ssl_port: '443'
                ssl_protocols: ''
                ssl_ciphers: ''
                rewrite_to_https: '1'
                spdy: '1'
                locations:
                    nxvl_wx3akqxepnjx:
                        location: /
                        autoindex: off
                        try_files:
                            - $uri
                            - $uri/
                            - /index.php$is_args$args
                        fastcgi: ''
                        fastcgi_index: ''
                        fastcgi_split_path: ''
                    nxvl_qcl7gavnzbv4:
                        location: '~ \.php$'
                        autoindex: off
                        try_files:
                            - $uri
                            - $uri/
                            - /index.php$is_args$args
                        fastcgi: '127.0.0.1:9000'
                        fastcgi_index: index.php
                        fastcgi_split_path: '^(.+\.php)(/.*)$'
                        fast_cgi_params_extra:
                            - 'SCRIPT_FILENAME $request_filename'
                            - 'APP_ENV dev'
        proxies: {  }
    apache:
        install: '1'
        settings:
            user: www-data
            group: www-data
            default_vhost: true
            manage_user: false
            manage_group: false
            sendfile: 0
        modules:
            - proxy_fcgi
            - rewrite
        vhosts:
            av_kzc1192dm2tv:
                servername: awesome.dev
                serveraliases:
                    - www.awesome.dev
                docroot: /var/www/awesome
                port: '80'
                setenv:
                    - 'APP_ENV dev'
                custom_fragment: ''
                ssl: '0'
                ssl_cert: ''
                ssl_key: ''
                ssl_chain: ''
                ssl_certs_dir: ''
                ssl_protocol: ''
                ssl_cipher: ''
                directories:
                    avd_vvnbqa0dpd04:
                        path: /var/www/awesome
                        options:
                            - Indexes
                            - FollowSymlinks
                            - MultiViews
                        allow_override:
                            - All
                        require:
                            - 'all granted'
                        custom_fragment: ''
                        files_match:
                            avdfm_ib4g5nhsksoy:
                                path: \.php$
                                sethandler: 'proxy:fcgi://127.0.0.1:9000'
                                custom_fragment: ''
                                provider: filesmatch
                        provider: directory
    php:
        install: '1'
        settings:
            version: '56'
        modules:
            php:
                - cli
                - intl
                - mcrypt
            pear: {  }
            pecl:
                - pecl_http
        ini:
            display_errors: On
            error_reporting: '-1'
            session.save_path: /var/lib/php/session
            date.timezone: UTC
        fpm_ini:
            error_log: /var/log/php-fpm.log
        fpm_pools:
            phpfp_am94c5xm3dgq:
                ini:
                    prefix: www
                    listen: '127.0.0.1:9000'
                    security.limit_extensions: .php
                    user: www-user
                    group: www-data
        composer: '1'
        composer_home: ''
    xdebug:
        install: '0'
        settings:
            xdebug.default_enable: '1'
            xdebug.remote_autostart: '0'
            xdebug.remote_connect_back: '1'
            xdebug.remote_enable: '1'
            xdebug.remote_handler: dbgp
            xdebug.remote_port: '9000'
    blackfire:
        install: '0'
        settings:
            server_id: ''
            server_token: ''
            agent:
                http_proxy: ''
                https_proxy: ''
                log_file: stderr
                log_level: '1'
            php:
                agent_timeout: '0.25'
                log_file: ''
                log_level: '1'
    xhprof:
        install: '0'
    wpcli:
        install: '0'
        version: v0.19.0
    drush:
        install: '0'
        version: 6.3.0
    ruby:
        install: '1'
        versions: {  }
    python:
        install: '1'
        packages: {  }
        versions: {  }
    nodejs:
        install: '1'
        npm_packages:
            - bower
    hhvm:
        install: '0'
        nightly: 0
        composer: '1'
        composer_home: ''
        settings: {  }
        server_ini:
            hhvm.server.host: 127.0.0.1
            hhvm.server.port: '9000'
            hhvm.log.use_log_file: '1'
            hhvm.log.file: /var/log/hhvm/error.log
        php_ini:
            display_errors: On
            error_reporting: '-1'
            date.timezone: UTC
    mysql:
        install: '1'
        settings:
            version: '5.6'
            root_password: '123'
            override_options: {  }
        adminer: 0
        users: {  }
        databases: {  }
        grants: {  }
    postgresql:
        install: '0'
        settings:
            global:
                encoding: UTF8
                version: '9.3'
            server:
                postgres_password: '123'
        databases: {  }
        users: {  }
        grants: {  }
        adminer: 0
    mongodb:
        install: '0'
        settings:
            auth: 1
            bind_ip: 127.0.0.1
            port: '27017'
        databases: {  }
    redis:
        install: '0'
        settings:
            conf_port: '6379'
    sqlite:
        install: '0'
        adminer: 0
        databases: {  }
    mailcatcher:
        install: '1'
        settings:
            smtp_ip: 0.0.0.0
            smtp_port: 1025
            http_ip: 0.0.0.0
            http_port: '1080'
            mailcatcher_path: /usr/local/rvm/wrappers/default
            from_email_method: inline
    beanstalkd:
        install: '0'
        settings:
            listenaddress: 0.0.0.0
            listenport: '13000'
            maxjobsize: '65535'
            maxconnections: '1024'
            binlogdir: /var/lib/beanstalkd/binlog
            binlogfsync: null
            binlogsize: '10485760'
        beanstalk_console: 0
        binlogdir: /var/lib/beanstalkd/binlog
    rabbitmq:
        install: '1'
        settings:
            port: '5672'
        users: {  }
        vhosts: {  }
        plugins: {  }
    elastic_search:
        install: '0'
        settings:
            version: 1.4.1
            java_install: true
    solr:
        install: '0'
        settings:
            version: 4.10.2
            port: '8984'

**Comment by isaacbacon1** [comment]
Samething for me!

**Comment by jtreminio** [comment]
Sorry guys, this is a vagrant issue. Please ask them - puphpet never actually kicks off until the box is spun up.
