### ISSUE TITLE
PHP ini Settings are not setted

### ISSUE THREAD

**Issue by csiewert** [puphpet/puphpet#1642]
If you set ini settings for php in puphpet (e.g.: short_open_tag = On), the settings will not be filled in the php.ini for the fpm manager.

What can we do?

**Comment by thiagotalma** [comment]
What testing have you done?

If you have looked at the file, be aware that the php.ini file remains intact, Puphpet settings are inserted into another file.

**Comment by csiewert** [comment]
Oh ok...I'll try again. Thanks for this information.

**Comment by csiewert** [comment]
You're right. Thanks for responding.

**Comment by csiewert** [comment]
I'm sorry, but something is weird here. If I set "short_open_tag" to "On" in puphpet config, the cli seems to be working

    <? 
        echo "foo";

    php info.php // foo

If I run the same script in browser via the fpm manager, the script is not interpreted (I get a blank page). If I use <?php instead of <?, its working like a charm.

Pls help :'(

**Comment by thiagotalma** [comment]
Okay. So let's do it right.

First of all, send your complete configuration file.

**Comment by zogs** [comment]
Reminds me an error i've got when i mispelled a parameter in zzzz_custom.ini (ommit the "M" in memory_limit=128M) , and then all following parameters were not read correctly... Not affecting CLI because memory_limit set to -1. 
Maybe this will help

**Comment by csiewert** [comment]
zogs, I already checked this, but thank you anyway.

@thiagotalma I'll dump my config below:

    vagrantfile:
        target: local
        vm:
            box: puphpet/debian75-x64
            box_url: puphpet/debian75-x64
            hostname: foo.dev
            memory: '2048'
            cpus: '4'
            chosen_provider: virtualbox
            network:
                private_network: 192.168.56.101
                forwarded_port:
                    vflnp_gbo35yto5wl2:
                        host: '6554'
                        guest: '22'
            post_up_message: ''
            provider:
                virtualbox:
                    modifyvm:
                        natdnshostresolver1: on
                vmware:
                    numvcpus: 1
                parallels:
                    cpus: 1
            provision:
                puppet:
                    manifests_path: puphpet/puppet
                    manifest_file: site.pp
                    module_path: puphpet/puppet/modules
                    options:
                        - '--verbose'
                        - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
                        - '--parser future'
            synced_folder:
                vflsf_n0pbmiatuul3:
                    source: 'c:\\foo.dev\\projects'
                    target: /var/www/foo
                    sync_type: default
                    rsync:
                        args:
                            - '--verbose'
                            - '--archive'
                            - '-z'
                        exclude:
                            - .vagrant/
                            - .git/
                        auto: 'true'
                    owner: www-data
                    group: www-data
                vflsf_qkdvn2p4rot4:
                    source: 'c:\\foo.dev\\vm'
                    target: /var/www/vm
                    sync_type: default
                    rsync:
                        args:
                            - '--verbose'
                            - '--archive'
                            - '-z'
                        exclude:
                            - .vagrant/
                            - .git/
                        auto: 'true'
                    owner: www-data
                    group: www-data
            usable_port_range:
                start: 10200
                stop: 10500
        ssh:
            host: null
            port: null
            private_key_path: null
            username: vagrant
            guest_port: null
            keep_alive: true
            forward_agent: false
            forward_x11: false
            shell: 'bash -l'
        vagrant:
            host: detect
    server:
        install: '1'
        packages:
            - vim
            - build-essential
            - mc
            - htop
            - strace
            - ntpdate
            - node-less
            - nodejs
            - nodejs-legacy
            - memcached
            - phpmyadmin
    users_groups:
        install: '1'
        groups: {  }
        users: {  }
    firewall:
        install: '1'
        rules: {  }
    cron:
        install: '1'
        jobs: {  }
    nginx:
        install: '0'
        settings:
            default_vhost: 1
            proxy_buffer_size: 128k
            proxy_buffers: '4 256k'
        upstreams: {  }
        vhosts:
            nxv_305ogv505m8q:
                server_name: foo.dev
                server_aliases:
                    - www.foo.dev
                www_root: /var/www/foo.dev
                listen_port: '80'
                index_files:
                    - index.html
                    - index.htm
                    - index.php
                client_max_body_size: 1m
                ssl: '0'
                ssl_cert: ''
                ssl_key: ''
                ssl_port: '443'
                ssl_protocols: ''
                ssl_ciphers: ''
                rewrite_to_https: '1'
                spdy: '1'
                locations:
                    nxvl_8lpacz1u60qt:
                        location: /
                        autoindex: off
                        try_files:
                            - $uri
                            - $uri/
                            - /index.php$is_args$args
                        fastcgi: ''
                        fastcgi_index: ''
                        fastcgi_split_path: ''
                    nxvl_6p2h15v6n2nv:
                        location: '~ \.php$'
                        autoindex: off
                        try_files:
                            - $uri
                            - $uri/
                            - /index.php$is_args$args
                        fastcgi: '127.0.0.1:9000'
                        fastcgi_index: index.php
                        fastcgi_split_path: '^(.+\.php)(/.*)$'
                        fast_cgi_params_extra:
                            - 'SCRIPT_FILENAME $request_filename'
                            - 'APP_ENV dev'
            nxv_z61vbkqylt5k:
                server_name: catalog.foo.dev
                server_aliases:
                    - www.catalog.foo.dev
                www_root: /var/www/foo.dev/catalog/public
                listen_port: '80'
                index_files:
                    - index.php
                client_max_body_size: 1m
                ssl: '0'
                ssl_cert: ''
                ssl_key: ''
                ssl_port: '443'
                ssl_protocols: ''
                ssl_ciphers: ''
                rewrite_to_https: '1'
                spdy: '1'
        proxies: {  }
    apache:
        install: '1'
        settings:
            user: www-data
            group: www-data
            default_vhost: true
            manage_user: false
            manage_group: false
            sendfile: 0
        modules:
            - proxy_fcgi
            - rewrite
        vhosts:
            av_pk50w4v142yl:
                servername: catalog.foo.dev
                serveraliases:
                    - www.catalog.foo.dev
                docroot: /var/www/foo/catalog/public
                port: '80'
                setenv:
                    - 'APP_ENV dev'
                    - 'APPLICATION_ENV development'
                custom_fragment: /var/www/vm/catalog-custom-directives.txt
                ssl: '0'
                ssl_cert: ''
                ssl_key: ''
                ssl_chain: ''
                ssl_certs_dir: ''
                ssl_protocol: ''
                ssl_cipher: ''
                directories:
                    avd_da9geh9e2a0m:
                        path: /var/www/foo/catalog/public
                        options:
                            - Indexes
                            - FollowSymlinks
                            - MultiViews
                        allow_override:
                            - All
                        require:
                            - 'all granted'
                        custom_fragment: ''
                        files_match:
                            avdfm_y621jyuyqzv7:
                                path: \.php$
                                sethandler: 'proxy:fcgi://127.0.0.1:9000'
                                custom_fragment: ''
                                provider: filesmatch
                        provider: directory
            av_69cwvm8sa3pp:
                servername: foo.dev
                serveraliases:
                    - www.foo.dev
                docroot: /var/www/foo
                port: '80'
                setenv:
                    - 'APPLICATION_ENV development'
                    - 'APP_ENV dev'
                custom_fragment: /var/www/vm/foo-custom-directives.txt
                ssl: '0'
                ssl_cert: ''
                ssl_key: ''
                ssl_chain: ''
                ssl_certs_dir: ''
                ssl_protocol: ''
                ssl_cipher: ''
                directories:
                    avd_sojrqw82cjuf:
                        path: /var/www/foo
                        options:
                            - Indexes
                            - FollowSymlinks
                            - MultiViews
                        allow_override:
                            - All
                        require:
                            - 'all granted'
                        custom_fragment: ''
                        files_match:
                            avdfm_2f4y6g1qh48x:
                                path: \.php$
                                sethandler: 'proxy:fcgi://127.0.0.1:9000'
                                custom_fragment: ''
                                provider: filesmatch
                        provider: directory
                    avd_4i2qq7pi2fx1:
                        path: /usr/share/phpmyadmin
                        options:
                            - Indexes
                            - FollowSymlinks
                            - MultiViews
                        allow_override:
                            - All
                        require:
                            - 'all granted'
                        custom_fragment: ''
                        files_match:
                            avdfm_7b8ub7aclwdi:
                                path: \.php$
                                sethandler: 'proxy:fcgi://127.0.0.1:9000'
                                custom_fragment: ''
                                provider: filesmatch
                        provider: directory
    php:
        install: '1'
        settings:
            version: '55'
        modules:
            php:
                - cli
                - intl
                - mcrypt
                - gd
                - geoip
                - imagick
                - memcached
                - tidy
                - memcache
            pear: {  }
            pecl:
                - pecl_http
        ini:
            session.save_path: /var/lib/php/session
            date.timezone: Europe/Berlin
            post_max_size: 64M
            upload_max_filesize: 64M
            short_open_tag: On
            display_errors: On
        fpm_ini:
            error_log: /var/log/php-fpm.log
        fpm_pools:
            phpfp_x7qzty0l5y7c:
                ini:
                    prefix: www
                    listen: '127.0.0.1:9000'
                    security.limit_extensions: .php
                    user: www-user
                    group: www-data
        composer: '1'
        composer_home: ''
    xdebug:
        install: '1'
        settings:
            xdebug.default_enable: '1'
            xdebug.remote_autostart: '0'
            xdebug.remote_connect_back: '1'
            xdebug.remote_enable: '1'
            xdebug.remote_handler: dbgp
            xdebug.remote_port: '9000'
    blackfire:
        install: '0'
        settings:
            server_id: ''
            server_token: ''
            agent:
                http_proxy: ''
                https_proxy: ''
                log_file: stderr
                log_level: '1'
            php:
                agent_timeout: '0.25'
                log_file: ''
                log_level: '1'
    xhprof:
        install: '1'
    wpcli:
        install: '0'
        version: v0.19.0
    drush:
        install: '0'
        version: 6.3.0
    ruby:
        install: '1'
        versions: {  }
    python:
        install: '1'
        packages: {  }
        versions: {  }
    nodejs:
        install: '0'
        npm_packages: {  }
    hhvm:
        install: '0'
        nightly: 0
        composer: '1'
        composer_home: ''
        settings: {  }
        server_ini:
            hhvm.server.host: 127.0.0.1
            hhvm.server.port: '9000'
            hhvm.log.use_log_file: '1'
            hhvm.log.file: /var/log/hhvm/error.log
        php_ini:
            display_errors: On
            error_reporting: '-1'
            date.timezone: UTC
    mysql:
        install: '1'
        settings:
            version: '5.6'
            root_password: foo
            override_options: {  }
        adminer: 0
        users: {  }
        databases: {  }
        grants: {  }
    postgresql:
        install: '0'
        settings:
            global:
                encoding: UTF8
                version: '9.3'
            server:
                postgres_password: '123'
        databases: {  }
        users: {  }
        grants: {  }
        adminer: 0
    mongodb:
        install: '0'
        settings:
            auth: 1
            bind_ip: 127.0.0.1
            port: '27017'
        databases: {  }
    redis:
        install: '0'
        settings:
            conf_port: '6379'
    sqlite:
        install: '0'
        adminer: 0
        databases: {  }
    mailcatcher:
        install: '1'
        settings:
            smtp_ip: 0.0.0.0
            smtp_port: 1025
            http_ip: 0.0.0.0
            http_port: '1080'
            mailcatcher_path: /usr/local/rvm/wrappers/default
            from_email_method: inline
    beanstalkd:
        install: '0'
        settings:
            listenaddress: 0.0.0.0
            listenport: '13000'
            maxjobsize: '65535'
            maxconnections: '1024'
            binlogdir: /var/lib/beanstalkd/binlog
            binlogfsync: null
            binlogsize: '10485760'
        beanstalk_console: 0
        binlogdir: /var/lib/beanstalkd/binlog
    rabbitmq:
        install: '0'
        settings:
            port: '5672'
        users: {  }
        vhosts: {  }
        plugins: {  }
    elastic_search:
        install: '1'
        settings:
            version: 1.4.1
            java_install: true
    solr:
        install: '1'
        settings:
            version: 4.10.2
            port: '8984'

**Comment by csiewert** [comment]
Sorry, I found the right file. 

Problem solved.
