### ISSUE TITLE
How to edit an existing configuration file in your GUI?

### ISSUE THREAD

**Issue by meglio** [puphpet/puphpet#1648]
It would be very useful if we could edit existing configuration files in your GUI, is it possible? Sorry, I haven't found any "upload" button.

**Comment by maces** [comment]
just drag&drop the puphpet/config.yaml onto the GUI

**Comment by meglio** [comment]
OMG - thanks, I haven't thought about such a possibility!

**Comment by nickcorrieri** [comment]
Dang that is super helpful :) 

Thanks!

:+1:

**Comment by stiffroy** [comment]
Cool... I was also searching for this possibility... (Y)
