### ISSUE TITLE
Cannot use symlinks

### ISSUE THREAD

**Issue by donaldallen** [puphpet/puphpet#1649]
I created the symlink with the following command:

```ln -s ~/Dropbox/Websites/mywebsite.dev ~/Websites/mywebsite.dev```

I'm getting the following errors when I ```vagrant up --provision```:

```
==> default: Notice: /Stage[main]/Main/Exec[exec mkdir -p /var/www/mywebsite.dev @ key nxv_k17e1mw65u7e]/returns: mkdir: cannot create directory â/var/www/mywebsite.devâ: File exists
==> default: Error: mkdir -p /var/www/mywebsite.dev returned 1 instead of one of [0]
==> default: Error: /Stage[main]/Main/Exec[exec mkdir -p /var/www/mywebsite.dev @ key nxv_k17e1mw65u7e]/returns: change from notrun to 0 failed: mkdir -p /var/www/mywebsite.dev returned 1 instead of one of [0]
==> default: Notice: /Stage[main]/Main/File[/var/www/mywebsite.dev]: Dependency Exec[exec mkdir -p /var/www/mywebsite.dev @ key nxv_k17e1mw65u7e] has failures: true
==> default: Warning: /Stage[main]/Main/File[/var/www/mywebsite.dev]: Skipping because of failed dependencies
```

I'm using VM Fusion and the vagrant-vmware-fusion plugin. I added these to my ```config.yaml``` file:

```yaml
        sharedFolder0.followSymlinks: TRUE
        sharedFolder1.followSymlinks: TRUE
        sharedFolder2.followSymlinks: TRUE
```

Is it possible [this issue](https://github.com/mitchellh/vagrant/issues/5474) is the reason why it's failing?

**Comment by maces** [comment]
If you did this on the host, this may be due to security constraints of virtualbox/vmware/...

**Comment by jtreminio** [comment]
Don't use symlinks, I don't think this is a puphpet issue but a fusion issue (or possible vagrant?).

Sorry, I can't do anything :(
