### ISSUE TITLE
Clone private repo

### ISSUE THREAD

**Issue by franz-josef-kaiser** [puphpet/puphpet#1656]
I'm currently thinking about a way to clone private repos (from GitHub) during provisioning. So far I've tried to use a bash script from within `puphpet/files/exec-once/git-clone.sh` during provisioning (moved to `startup-always` . As I couldn't find any ideas or concepts floating in the issues: Are there any?

_label: question_

**Comment by jtreminio** [comment]
This is currently the only way...

The reason being that there'd be no real way for users to define *when* a git repo should be cloned:

Before installing Apache/Nginx? After? Before $x? There's no real way to tie it in, other than having Puppet do it in its own semi-random fashion.

Best bet is to continue using exec file.

**Comment by franz-josef-kaiser** [comment]
Ok, got it - thanks! How would you handle authentification? Fake user and adding private keys to the (shared) stack?
