### ISSUE TITLE
PHP not executed on vHost

### ISSUE THREAD

**Issue by djumaka** [puphpet/puphpet#1660]
After several days of attempts I downloaded a default config for a machine with the awesome.dev php5.6 (fcgi) on apache with https (ubu14.04) and php was displayed, rather then executed on the server. Have no experiecne with fcgi but the php5-fcgi service was up and running. Read a lot of complains around the internet about this problem but no real solution so far.

**Comment by jtreminio** [comment]
Non-SSL:

![image](https://cloud.githubusercontent.com/assets/589398/7800180/2c6eba12-02d7-11e5-90d6-1a188ca77708.png)

SSL:

![image](https://cloud.githubusercontent.com/assets/589398/7800181/32e0ba1c-02d7-11e5-9fdd-415efd1578ed.png)

Instructions:

![image](https://cloud.githubusercontent.com/assets/589398/7800182/3d2ff3f2-02d7-11e5-9737-04f5216006e9.png)
