### ISSUE TITLE
Where do you store multiple projects on a single puphpet instance?

### ISSUE THREAD

**Issue by ChMat** [puphpet/puphpet#1665]
Hi,

I am a developer working in parallel on several Symfony projects. I chose to have a single puphpet VM hosting all projects in dev mode.

But every time I try to upgrade my puphpet configuration, it's a pain playing trial and error to choose the right location for my projects.

I work on a Windows host with Virtualbox and the puphpet guest is a Ubuntu 14.04 with Apache.

Usually, I put my projects inside `/home/vagrant/[project_name]` and the docroot of each virtual host sits in the `web` folder inside these folders. 

But every time I `vagrant up` a new instance, I get loads of errors as `/home/vagrant` is owned by `vagrant:vagrant` and the setup scripts does not look to run as root.

What do you advise in such a situation?

Thanks!

**Comment by maces** [comment]
Why not "/var/www/[project_name]/" and "/var/www/[project_name]/web"? This setup works here.

**Comment by ChMat** [comment]
`/var/www` is synced with the puphpet folder. I'm not sure if it's good practice to disable that synchronization.

And synchronization is pretty slow in conjunction with symfony projects (or you have tips to solve that too :-) ).

**Comment by maces** [comment]
I assumed sync is wanted. How do you sync your files between host and guest at all?
We use NFS but on a Windows host this is not supported afaik.
You could try Rsync with this plugin: https://github.com/smerrill/vagrant-gatling-rsync
You could also consider VMWare, as their synced folder is faster. (The Virtualbox ones are not intended for that kind of use according to it's dev)

**Comment by ChMat** [comment]
I have always used sftp upload (there is an automated upload on save in phpStorm). It works pretty well.

**Comment by maces** [comment]
Interesting.
You could of course simply configure a VM without synced "/var/www" folders and provision it in the background and see if it works for you. 
Folders needed directly by vagrant are available as "/vagrant/" inside the VM and puPHPet creates "/.puphpet-stuff/". Additionally I used VMs with no (user-defined) synced folders at all (but nothing in /var/www either) and they worked.

**Comment by jtreminio** [comment]
You shouldn't use `/home/vagrant` as that is a specific user's home directory, and as you can see may cause issues with other system users.

> And synchronization is pretty slow in conjunction with symfony projects (or you have tips to solve that too 

You can always change the cache directory to be outside of shared folder. This + nfs + nginx + php 5.6 has brought my SF2 load times to ~200-400ms.
