### ISSUE TITLE
Can't create array item in php.ini

### ISSUE THREAD

**Issue by spekary** [puphpet/puphpet#1674]
I am trying to get this to appear in the hhvm php.ini file:
```
hhvm.php_file.extensions[html]=application/x-hhvm-php
```
This permits files that end with .html to be process by hhvm. I tried the following in config.yaml:
```
server_ini:
        hhvm.php_file.extensions:
            html: application/x-hhvm-php
```
But it produces:
```
hhvm.php_file.extensions={'html'=>'application/x-hhvm-php'}
```
Which is ruby syntax for an array, and not the correct syntax for a php.ini array.

I have reverted to using an exec-once script to append this to the file, but the problem with this approach is the php.ini file is appended after hhvm is started and the change is not read. When I reload the vm, it then gives me a 503 error. I have to ssh and ```/etc/init.d/hhvm restart ``` to make this work.

I realize the problem might be in a puppet tool, so I am wondering if its even possible to do what I want.

**Comment by jtreminio** [comment]
Seems like this should work:

    server_ini:
        'hhvm.php_file.extensions[html]': application/x-hhvm-php

**Comment by spekary** [comment]
That did not work. It produces the following:
```
hhvm.php_file.extensions=application/x-hhvm-php
```

Which is missing the ```[html]``` part to make it an array. The same is true without the quotes.
