### ISSUE TITLE
Update boxes

### ISSUE THREAD

**Issue by thiagotalma** [puphpet/puphpet#1677]
Hello Juan,

It's time to update the boxes?
There are some important PRs waiting for you.

**Comment by thiagotalma** [comment]
@jtreminio Please give an opinion on that matter.
Can we expect a new updated box to be created?

**Comment by jtreminio** [comment]
@thiagotalma Thanks for all the PRs.

Yes, all boxes will be updated - working on some personal stuff right now, though.

**Comment by thiagotalma** [comment]
Ok Juan. I'm with you. Count on me.

**Comment by jtreminio** [comment]
All boxes except CentOS updated. That's coming tomorrow.
