### ISSUE TITLE
apt-get Error provisioning on digital ocean

### ISSUE THREAD

**Issue by EwanValentine** [puphpet/puphpet#1678]
==> default: Error: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install mysql-server-5.6' returned 100: Reading package lists...

**Comment by jtreminio** [comment]
SSH into the server and command manually, see what happens.

This isn't exactly a puphpet issue though.

**Comment by EwanValentine** [comment]
Apologies. Fixed it now, I was using a non existent database user! My bad!
