### ISSUE TITLE
Help popups hiding dropdowns

### ISSUE THREAD

**Issue by Schrank** [puphpet/puphpet#1679]
The newly added popups are great, but unfortunately they hiding all the dropdowns.
![bildschirmfoto 2015-05-29 um 10 17 22](https://cloud.githubusercontent.com/assets/379680/7878954/fcfa01e8-05eb-11e5-842d-07474975f6d0.png)

**Comment by jtreminio** [comment]
Move your mouse out of the field, it has a timeout.
