### ISSUE TITLE
Installing ZeroMQ

### ISSUE THREAD

**Issue by maxHartanovich** [puphpet/puphpet#1683]
I try to install zeromq and has this error

[08:50 PM]-[vagrant@local]-[~/php-zmq]-[git master] 
$ sudo phpize && ./configure
Configuring for:
PHP Api Version:         20131106
Zend Module Api No:      20131226
Zend Extension Api No:   220131226
./configure: line 1813: config.log: Permission denied
./configure: line 1823: config.log: Permission denied

sync folder type is nfs, on default type is work nice

how i can fix this issue ?

ps sorry for my poor english

**Comment by jtreminio** [comment]
puphpet doesn't have a zeromq option. I can't provide support for this.

However, try using sudo.
