### ISSUE TITLE
Pop ups obscure dropdowns

### ISSUE THREAD

**Issue by MrPhilbert** [puphpet/puphpet#1685]
Could you please timeout the popups. They cover up the options in the dropdowns and make them unreadable.

Otherwise great job and great utility.

Thanks

**Comment by jtreminio** [comment]
Some popups require more time to read. Not sure if automatically timing them out is the best solution?

Can you mouse over another element?

Maybe implementing a timeout that stops if moused over box?

**Comment by MrPhilbert** [comment]
Man you are attentive!
Maybe add a ? mark over box for mouseover?

**Comment by thiagotalma** [comment]
Excuse me, but I did not understand the problem.

In Chrome browser popups disappear when the mouse leaves the element.

**Comment by MrPhilbert** [comment]
If the popup is on the drop-down itself, then it can obscure objects in the drop-down. So, while hovering over the element that triggers the drop-down, the drop-down will remain.

**Comment by s992** [comment]
Screenshot of the issue: 

![popovers](http://i.imgur.com/oM07uqV.png)

Maybe you could direct it up instead of down?

**Comment by mahngiel** [comment]
+1 This is a usability problem and it's frustrating. Recommend relocating the tooltips.

**Comment by mahngiel** [comment]
> jtreminio closed this in #1692 15 hours ago

This is still a problem

![puphpet-v2](https://cloud.githubusercontent.com/assets/1322045/8366507/b831efd6-1b52-11e5-90c6-9cb5b3628dc6.gif)

**Comment by jtreminio** [comment]
@mahngiel thank you for the great image examples :)

I may have to find another popover library to allows click-throughs.
