### ISSUE TITLE
facter is broken

### ISSUE THREAD

**Issue by markushausammann** [puphpet/puphpet#1686]
I'm pretty sure this isn't the right repo to post this error but you'll help me to find the right one.

With different ubuntu packages from puPHPet I keep getting the following error when trying to provision with ansible:

    GATHERING FACTS *************************************************************
    failed: [192.168.56.101] => {"cmd": "/usr/bin/facter --puppet --json", "failed": true, "rc": 2}
    msg: [Errno 2] No such file or directory

This can (at the moment) be fixed with `ln -sf /usr/bin/ruby1.9.1 /usr/bin/ruby`. It should already be distributed in that state.

**Comment by jtreminio** [comment]
I can't replicate this ... and have never seen this issue in any of my boxes.

Can you paste your config.yaml if you're still experiencing this?

**Comment by markushausammann** [comment]
I'm not using puphpet anymore, switched to laravel homestead.
