### ISSUE TITLE
Use puppet librarian to avoid including puppet modules in our projects

### ISSUE THREAD

**Issue by bburnichon** [puphpet/puphpet#1689]
When using puphpet to bootstrap a dev vm, it comes with way too many files.

Librarian would help reduce the size to only the real configuration, as using a composer.lock files to fix dependencies (with a librarian.lock).

In my case, I saw that if you gitignore `puphpet/puppet/modules/*`, missing modules gets downloaded from `https://puphpet.com/download-puppet-modules`. The only issue I can see is that these dependencies are not versioned and are not guarantee to work with my committed version.

It would be nice to include something like suggested [here](http://www.wimpyprogrammer.com/managing-puppet-modules-on-vagrant-with-librarian-puppet/)

**Comment by jtreminio** [comment]
Already included for power users: https://github.com/puphpet/puphpet/blob/master/archive/puphpet/puppet/Puppetfile

It's not automatic, though. It used to be, but found it was far too slow for most people, and would often time out.
