### ISSUE TITLE
Browsersync with puphet

### ISSUE THREAD

**Issue by codecowboy** [puphpet/puphpet#1693]
When using Browsersync in a project on a puPHPet vagrant box the browsersync server binds to an IP 10.0.2.15 rather than the IP which is exposed to the host (in the 192.168.56 range)

```
[BS] Proxying: http://local.mydev
[BS] Access URLs:
 ----------------------------------
       Local: http://localhost:3000
    External: http://10.0.2.15:3000
 ----------------------------------
          UI: http://localhost:3001
 UI External: http://10.0.2.15:3001
 ----------------------------------
```

I am using puPHPet Ubuntu vagrant box on an OSX Yosemite host. I think the issue might be that puPHPet creates a private network by default. I tried changing it to a public network in config.yaml (this has been replaced in newer versions of puPHPet by the looks of things) but this disables the NFS shares and I've also tried changing the browsersync config with the ```host``` option, setting it to the 192.168.56 address.

How can I forward port 3000 to 10.0.2.15 using config files and then re-provisioning?

**Comment by jtreminio** [comment]
I've added proxy support to Nginx today. You can use that!
