### ISSUE TITLE
Bug?: Rsync with VirtualBox and Windows 7

### ISSUE THREAD

**Issue by darnold** [puphpet/puphpet#1696]
I can't seem to get the rsync folders to work on either of my windows 7 machines. I get the following error:

Host path: /x/MindWarp/Simple Lineup/Website/
Guest path: /var/www
Command: rsync --chmod=ug=rwX,o=rxX --verbose --archive -z --no-owner --no-group --rsync-path sudo rsync -e ssh -p 2222 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i 'X:/MindWarp/Simple Lineup/Website/.vagrant/machines/default/virtualbox/private_key' --exclude .vagrant/ --exclude .git/ --exclude .idea/ /x/MindWarp/Simple Lineup/Website/ vagrant@127.0.0.1:/var/www
Error: Could not create directory '/home/Davy/.ssh'.

My config file:
http://pastie.org/10227616

I'm using the standard cygwin install of rsync (3.1.1) and ssh. I've tested it on multiple machines with the same results.

My last note is that the virtual machine works fine (albeit slow) with the default sync_type.

Does anyone have any ideas on this or see anything i'm just completely missing? Or could this just be an incorrect setting in the rsync command? Thanks!

**Comment by darnold** [comment]
I figured out what was going on and i'll leave the fix here to hopefully help someone else!

So basically in the newer versions of cygwin are set up so that instead of just using cd /C/ to access your C:\ drive you have to use a prefix and it would look like this /cygdrive/C/.  Puphpet/Vagrant is not using the prefix which i'm sure works fine on Mac but dies on windows. I'm sure there are a bunch of ways to approach this but once I realized what was actually causing the error I did the following:

THE FIX
In your C:\cygwin\etc folder look for fstab and edit it. Comment out this line **none /cygdrive cygdrive binary,posix=0,user 0 0** and add in **none / cygdrive binary 0 0**

This will take out the prefix and allow rsync to run like normal with puphpet/vagrant :)

**Comment by viktym** [comment]
Thank you, men! I've spent two days two days of my life trying to get to work rsync with vagrant
