### ISSUE TITLE
UI tooltip overlays on top of dropdown

### ISSUE THREAD

**Issue by withremote** [puphpet/puphpet#1699]
![Tool tip](http://i.imgur.com/YxwlVef.png) I just noticed this today when setting a up a new config. It's hard to see options with the tooltip box positioned to the bottom of the select box. Perhaps positioning the tooltip to the left of the select?

**Comment by thiagotalma** [comment]
Duplicate: #1679 #1685

**Comment by jtreminio** [comment]
Closed by #1746
