### ISSUE TITLE
Allow user to define symlinks in config.yaml

### ISSUE THREAD

**Issue by evanpetersen** [puphpet/puphpet#1701]
I've found it particularly helpful to have puppet create symlinks to various places such as /home/vagrant/public_html -> /var/www/html/.  I think it would be nice to allow the user to define symlinks right after shared folders on any of the deploy target pages.

To accomplish this, I've added the following to config.yaml:

    symlinks:
        install: '1'
        links:
            '/home/vagrant/public_html': '/var/www/html/'

And the following to puphpet/puppet/site.pp

    if array_true($symlinks, 'install') {
      $symlinks['links'].each |$source, $target| {
        file { "$source":
          ensure => link,
          target => "$target",
        }
      }
    }

**Comment by thiagotalma** [comment]
Make a PR  :+1:

**Comment by evanpetersen** [comment]
Is there a vagrant box that's configured to work on the project?

**Comment by jtreminio** [comment]
This is difficult to add to the GUI.

What if someone attempts to create a symlink to a non-existent directory?

For example,

    '/home/vagrant/public_html': '/var/www/html/'

Is dependent on `/var/www/html` existing, which gets created on Apache or Nginx installation and setup. Adding this would pose too many potential issues.

Easiest solution is best solution: create an exec-once file.

**Comment by evanpetersen** [comment]
I struggle to see the difference between this and synced folders.  Synced folders relies on the "Folder Source" just like my proposed feature would rely on the target.

I believe this feature would be best placed beneath Shared Folders with the exact same style (less the shared folder options, obviously).

Is there a puphpet.com vagrant box that I can pull down to work on this feature?

**Comment by jtreminio** [comment]
@evanpetersen all boxes are generated using packer. Here are the templates: https://github.com/puphpet/packer-templates
