### ISSUE TITLE
Can't connect to vagrant box using Sequel Pro

### ISSUE THREAD

**Issue by ixudra** [puphpet/puphpet#1702]
I'm sure you're heard this a million times, but I can't connect to my box using Sequel Pro. I tried connecting using the username/password (vagrant/vagrant) and using the insecure key, neither seems to work. No matter what I do, I am always asked to enter the password. No matter what I enter (even vagrant), it does not work.

- OSX Yosemite
- Vagrant 1.7.2
- VMware Fusion Pro 7
- Ubuntu 14 x64 box

My current config is the following:

![screen shot 2015-06-09 at 12 05 48](https://cloud.githubusercontent.com/assets/6200278/8055440/e62f885e-0e9f-11e5-918d-0506b10c360d.png)

I followd instructions on various websites, including the following: http://stackoverflow.com/questions/28836246/how-do-i-sequel-pro-with-puphpet

But the problem seems to persist. No matter what I do, Sequel Pro always asks me for the password and no matter what I enter, it does not work. 

![screen shot 2015-06-09 at 12 09 38](https://cloud.githubusercontent.com/assets/6200278/8055537/820ad990-0ea0-11e5-9b40-d7596576d0ac.png)

Any help is appreciated, since this problem is really hindering my work in ways you can't imagine...

**Comment by Schrank** [comment]
don't use the insecure key, use the other one, `id_rsa` and user vagrant
then you are on the machine with the domain as host
and then just use the mysql credentials you have

**Comment by ixudra** [comment]
Thanks for the assist!
