### ISSUE TITLE
Nameserver configuration and initial-setup.sh behind authenticated corporate proxy

### ISSUE THREAD

**Issue by raptor65** [puphpet/puphpet#1705]
Have just spent a most frustrating day trying to get a CentOs based LAMP VM up and running in Virtualbox behind a password-authenticated corporate proxy (never a happy scenario). I simply could not get the box to provision at all. I tried all the usual suspects, as I was convinced the proxy authentication/negotiation was the issue, but to no avail.

I eventually managed to trace the cause back to the initial-setup.sh script, which overrides the default nameserver entry of 10.0.2.3 in /etc/resolv.conf and instead populates it with the Google primary and fallback DNS servers of 8.8.8.8 and 8.8.4.4. Unfortunately, access to these is restricted by our proxy, so although it appeared that proxy connection/negotiation was failing, it was all working perfectly well until it came to making any kind of request that relied on DNS, which the proxy was then explicitly refusing to handle (I'm sure some will query our sysadmin's reasons for setting things up this way: all I can say is don't go there!).

Anyway, I am posting this:

1. by way of a heads up to anyone else who might hit this or a similar problem and 
2. to suggest that this might better be implemented as a configurable option, or that the very least have the initial-setup.sh echo out a useful message when it overwrites the default resolver.conf file during provisioning, so that the user is made aware of the changes being made and the possible implications.

**Comment by driehle** [comment]
Seems to be the same problem as in #1850, please see discussion there.

**Comment by jtreminio** [comment]
Closed by 25eff2b.

Needs boxes rebuilt to reset them. Sorry guys :)
