### ISSUE TITLE
How do I set environment variables in config.yaml

### ISSUE THREAD

**Issue by alex-barylski** [puphpet/puphpet#1710]
More specifically, I need the variable PATH_INFO set of which NGINX does not support -- the work around is to set the variable inside the fastcgi_params (usually) like so:

http://stackoverflow.com/questions/20848899/nginx-phpfpm-path-info-always-empty

set $path_info $fastcgi_path_info;
fastcgi_param PATH_INFO $path_info;

How do I express this in config.yaml?

Where or what would I modify to force this requirement?

**Comment by HumanWorks** [comment]
I think you can't but you can create a .sh file in /puphet/files/startup-always with variables stated like this:

```
#!/bin/sh

echo export MY_VAR="value" >> /etc/environment
```
