### ISSUE TITLE
Could not find dependency Package[php] for File[/var/www/html/adminer

### ISSUE THREAD

**Issue by pietrondo** [puphpet/puphpet#1712]
<blockquote>==> default: Error: Could not find dependency Package[php] for File[/var/www/html/adminer] at /tmp/vagrant-puppet/modules-34aff7f4512a0beb38f43a180abe530a/puphpet/manifests/adminer.pp:8
</blockquote>

Problem with adminer:
ubuntu x64 -nginx->

**Comment by jtreminio** [comment]
Show me your config.yaml...

**Comment by palpalani** [comment]
I am also get same error. I am selected mariadb with adminer.

So edited adminer: '1' to adminer: '0' under mariadb settings. in config.yaml file.
