### ISSUE TITLE
Error: Files must be fully qualified at /tmp/vagrant-puppet/manifests-.../nodes/Apache.pp:176 on node local. puphpet

### ISSUE THREAD

**Issue by jezmck** [puphpet/puphpet#1717]
When running `vagrant up` I get the following errors
```
...
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-dab3580fd4654d87def1d907265fa5fc/stdlib/lib/facter/puppet_vardir.rb
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-dab3580fd4654d87def1d907265fa5fc/stdlib/lib/facter/root_home.rb
==> default: Error: Files must be fully qualified at /tmp/vagrant-puppet/manifests-893fcda21077f5a583c2dbbba8515c0a/nodes/Apache.pp:176 on node local.puphpet
==> default: Error: Files must be fully qualified at /tmp/vagrant-puppet/manifests-893fcda21077f5a583c2dbbba8515c0a/nodes/Apache.pp:176 on node local.puphpet
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

My VM is then accessible via SSH, but it's not running apache and didn't have `htop` installed (and probably various other customisations.

Windows 8.1, latest VirtualBox and Vagrant (downloaded today).

**Comment by jtreminio** [comment]
Apache vhost custom fragments must point to a file you share with the VM. Don't put code in that field, put that path to a file.

**Comment by malutanpetronel** [comment]
yaml allows long sequences of text directly
custom_fragment: | 
                  DirectoryIndex app_dev.php
                  <Directory /vagrant>
...

**Comment by jtreminio** [comment]
@malutanpetronel yes, but then hiera breaks when it sees some specific characters, and it breaks when it sees `\n`
