### ISSUE TITLE
Puphet & packer integration

### ISSUE THREAD

**Issue by geoHeil** [puphpet/puphpet#1722]
Hi I have issues integrating puphet with packer: http://stackoverflow.com/questions/30902257/puphet-puppet-packer
for example one of the error's I get is: 

Error: Could not parse for environment production: Could not match |$key, at /tmp/packer-puppet-masterless/manifests/nodes/Cron.pp:5 on node ubuntu-1404.vagrantup.com

**Comment by jtreminio** [comment]
Puphpet already uses packer: https://github.com/puphpet/packer-templates

Clone that and add your specific stuff!

**Comment by geoHeil** [comment]
sorry for commenting here - but the issues section in the packer-templates project seems to be disabled.

There is a problem with the installation of RVM:

/usr/bin/puppet: line 3: rvm  command not found

Provisioning with Puppet...
    parallels-iso: Creating Puppet staging directory...
    parallels-iso: Uploading hiera configuration...
    parallels-iso: Uploading manifest directory from: puphpet/puppet
    parallels-iso: Uploading local modules from: puphpet/puppet/nodes_own
    parallels-iso: Uploading local modules from: puphpet/puppet/modules
    parallels-iso: Uploading manifests...
    parallels-iso: Running Puppet:   sudo -E puppet apply --verbose --modulepath='/tmp/packer-puppet-masterless/module-0:/tmp/packer-puppet-masterless/module-1' --hiera_config='/tmp/packer-puppet-masterless/hiera.yaml' --manifestdir='/tmp/packer-puppet-masterless/manifests' --detailed-exitcodes /tmp/packer-puppet-masterless/manifests/site.pp
    parallels-iso: /usr/bin/puppet: line 3: rvm: command not found
