### ISSUE TITLE
OS X, Adminer mkdir failed permission denied.

### ISSUE THREAD

**Issue by chrisRidgers** [puphpet/puphpet#1729]
On two separate builds I've run into an issue where vagrant up fails.

The exact error is:

```
==> default: Notice: /Stage[main]/Puphpet_apache/Exec[exec mkdir -p /var/www/html/adminer @ key av_25nh1hek8155]/returns: mkdir: cannot create directory `/var/www/html/adminer': Permission denied
==> default: Error: mkdir -m 775 -p /var/www/html/adminer returned 1 instead of one of [0]
==> default: Error: /Stage[main]/Puphpet_apache/Exec[exec mkdir -p /var/www/html/adminer @ key av_25nh1hek8155]/returns: change from notrun to 0 failed: mkdir -m 775 -p /var/www/html/adminer returned 1 instead of one of [0]
```

Which is understandably making me very sad.

This only seems to affect my OS X machine, the same build (or one of) provisioned fine on my linux machine in work.

As you might guess:  /var/www/html is owned by root:root on the mac.

Other info that might help: Building an ubuntu 12.04 box.

**Comment by chrisRidgers** [comment]
Just had a colleague run attempt to vagrant up the same box on his machine (OS X again) and he ran into the same issue.

**Comment by chrisRidgers** [comment]
config.yaml in case it helps:

    vagrantfile:
        target: local
        vm:
            box: puphpet/ubuntu1204-x64
            box_url: puphpet/ubuntu1204-x64
            hostname: nugentcare.mb
            memory: '2048'
            cpus: '1'
            chosen_provider: virtualbox
            network:
                private_network: 192.168.56.101
                forwarded_port:
                    vflnp_v7hiav7pdbq0:
                        host: '6162'
                        guest: '22'
            post_up_message: ''
            provider:
                virtualbox:
                    modifyvm:
                        natdnshostresolver1: on
                    showgui: '0'
                vmware:
                    numvcpus: 1
                parallels:
                    cpus: 1
            provision:
                puppet:
                    manifests_path: puphpet/puppet
                    manifest_file: site.pp
                    module_path: puphpet/puppet/modules
                    options:
                        - '--verbose'
                        - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
                        - '--parser future'
            synced_folder:
                vflsf_57koiihalytt:
                    source: ./
                    target: /var/www/project
                    sync_type: nfs
                    smb:
                        smb_host: ''
                        smb_username: ''
                        smb_password: ''
                    rsync:
                        args:
                            - '--verbose'
                            - '--archive'
                            - '-z'
                        exclude:
                            - .vagrant/
                            - .git/
                        auto: 'true'
                    owner: www-data
                    group: www-data
            usable_port_range:
                start: 10200
                stop: 10500
        ssh:
            host: null
            port: null
            private_key_path: null
            username: vagrant
            guest_port: null
            keep_alive: true
            forward_agent: false
            forward_x11: false
            shell: 'bash -l'
        vagrant:
            host: detect
    server:
        install: '1'
        packages:
            - vim
    users_groups:
        install: '1'
        groups: {  }
        users: {  }
    firewall:
        install: '1'
        rules: {  }
    cron:
        install: '1'
        jobs: {  }
    nginx:
        install: '0'
        settings:
            default_vhost: 1
            proxy_buffer_size: 128k
            proxy_buffers: '4 256k'
        upstreams: {  }
        vhosts:
            nxv_fn4tnhvpj2t3:
                server_name: awesome.dev
                server_aliases:
                    - www.awesome.dev
                www_root: /var/www/awesome
                listen_port: '80'
                index_files:
                    - index.html
                    - index.htm
                    - index.php
                client_max_body_size: 1m
                ssl: '0'
                ssl_cert: ''
                ssl_key: ''
                ssl_port: '443'
                ssl_protocols: ''
                ssl_ciphers: ''
                rewrite_to_https: '1'
                spdy: '1'
                locations:
                    nxvl_rjtij2be1jfr:
                        location: /
                        autoindex: off
                        try_files:
                            - $uri
                            - $uri/
                            - /index.php$is_args$args
                        fastcgi: ''
                        fastcgi_index: ''
                        fastcgi_split_path: ''
                    nxvl_qxi4mcbmatw2:
                        location: '~ \.php$'
                        autoindex: off
                        try_files:
                            - $uri
                            - $uri/
                            - /index.php$is_args$args
                        fastcgi: '127.0.0.1:9000'
                        fastcgi_index: index.php
                        fastcgi_split_path: '^(.+\.php)(/.*)$'
                        fast_cgi_params_extra:
                            - 'SCRIPT_FILENAME $request_filename'
                            - 'APP_ENV dev'
        proxies: {  }
    apache:
        install: '1'
        settings:
            user: www-data
            group: www-data
            default_vhost: true
            manage_user: false
            manage_group: false
            sendfile: 0
        modules:
            - proxy_fcgi
            - rewrite
        vhosts:
            av_a6u33mmlpsig:
                servername: nugentcare.mb
                serveraliases:
                    - nugentcare-website.dev
                    - www.nugentcare-website.dev
                    - '*.vagrantshare.com'
                docroot: /var/www/project/htdocs/build
                port: '80'
                setenv:
                    - 'APP_ENV dev'
                custom_fragment: ''
                ssl: '0'
                ssl_cert: ''
                ssl_key: ''
                ssl_chain: ''
                ssl_certs_dir: ''
                ssl_protocol: ''
                ssl_cipher: ''
                directories:
                    avd_lhpoej7gi14a:
                        path: /var/www/project/htdocs/build
                        options:
                            - Indexes
                            - FollowSymlinks
                            - MultiViews
                        allow_override:
                            - All
                        require:
                            - 'all granted'
                        custom_fragment: ''
                        files_match:
                            avdfm_irhvpqjvc118:
                                path: \.php$
                                sethandler: 'proxy:fcgi://127.0.0.1:9000'
                                custom_fragment: ''
                                provider: filesmatch
                        provider: directory
            av_t6n1vlsvtluo:
                servername: nugentcare.mb
                serveraliases:
                    - nugentcare-adminer.dev
                docroot: /var/www/html/adminer
                port: '80'
                custom_fragment: ''
                ssl: '0'
                ssl_cert: ''
                ssl_key: ''
                ssl_chain: ''
                ssl_certs_dir: ''
                ssl_protocol: ''
                ssl_cipher: ''
                directories:
                    avd_5peyflsagz87:
                        path: /var/www/html/adminer
                        options:
                            - Indexes
                            - FollowSymlinks
                            - MultiViews
                        allow_override:
                            - All
                        require:
                            - 'all granted'
                        custom_fragment: ''
                        files_match:
                            avdfm_ec5j6z33l0bu:
                                path: \.php$
                                sethandler: 'proxy:fcgi://127.0.0.1:9000'
                                custom_fragment: ''
                                provider: filesmatch
                        provider: directory
    php:
        install: '1'
        settings:
            version: '55'
        modules:
            php:
                - cli
                - intl
                - mcrypt
                - fpm
            pear: {  }
            pecl: {  }
        ini:
            display_errors: On
            error_reporting: '-1'
            session.save_path: /var/lib/php/session
            date.timezone: UTC
        fpm_settings:
            port: 9000
        fpm_ini:
            error_log: /var/log/php-fpm.log
        fpm_pools:
            phpfp_97kp6p9fgoy9:
                ini:
                    listen: '127.0.0.1:9000'
                    prefix: phpfp_97kp6p9fgoy9
                    security.limit_extensions: .php
                    user: www-user
                    group: www-data
                    pm: ondemand
                    pm.max_children: 5
        composer: '1'
        composer_home: ''
    xdebug:
        install: '0'
        settings:
            xdebug.default_enable: '1'
            xdebug.remote_autostart: '0'
            xdebug.remote_connect_back: '1'
            xdebug.remote_enable: '1'
            xdebug.remote_handler: dbgp
            xdebug.remote_port: '9000'
    blackfire:
        install: '0'
        settings:
            server_id: ''
            server_token: ''
            agent:
                http_proxy: ''
                https_proxy: ''
                log_file: stderr
                log_level: '1'
            php:
                agent_timeout: '0.25'
                log_file: ''
                log_level: '1'
    xhprof:
        install: '0'
    wpcli:
        install: '0'
        version: v0.19.0
    drush:
        install: '0'
        version: 6.3.0
    ruby:
        install: '1'
        versions: {  }
    python:
        install: '1'
        packages: {  }
        versions: {  }
    nodejs:
        install: '0'
        npm_packages: {  }
    hhvm:
        install: '0'
        nightly: 0
        composer: '1'
        composer_home: ''
        settings: {  }
        server_ini:
            hhvm.server.host: 127.0.0.1
            hhvm.server.port: '9000'
            hhvm.log.use_log_file: '1'
            hhvm.log.file: /var/log/hhvm/error.log
        php_ini:
            display_errors: On
            error_reporting: '-1'
            date.timezone: UTC
    mysql:
        install: '1'
        settings:
            version: '5.5'
            root_password: '123'
            override_options: {  }
        adminer: '1'
        users:
            mysqlnu_8ahp8u5nc0jw:
                name: nugent_care
                password: password
        databases:
            mysqlnd_2ew0dg8yt666:
                name: nugent_care
                sql: ''
        grants:
            mysqlng_5cw3b9cwdtxj:
                user: nugent_care
                table: 'nugent_care.*'
                privileges:
                    - ALL
    postgresql:
        install: '0'
        settings:
            global:
                encoding: UTF8
                version: '9.3'
            server:
                postgres_password: '123'
        databases: {  }
        users: {  }
        grants: {  }
        adminer: 0
    mongodb:
        install: '0'
        settings:
            auth: 1
            bind_ip: 127.0.0.1
            port: '27017'
        databases: {  }
    redis:
        install: '0'
        settings:
            conf_port: '6379'
    sqlite:
        install: '0'
        adminer: 0
        databases: {  }
    mailcatcher:
        install: '0'
        settings:
            smtp_ip: 0.0.0.0
            smtp_port: 1025
            http_ip: 0.0.0.0
            http_port: '1080'
            mailcatcher_path: /usr/local/rvm/wrappers/default
            from_email_method: inline
    beanstalkd:
        install: '0'
        settings:
            listenaddress: 0.0.0.0
            listenport: '13000'
            maxjobsize: '65535'
            maxconnections: '1024'
            binlogdir: /var/lib/beanstalkd/binlog
            binlogfsync: null
            binlogsize: '10485760'
        beanstalk_console: 0
    rabbitmq:
        install: '0'
        settings:
            port: '5672'
        users: {  }
        vhosts: {  }
        plugins: {  }
    elastic_search:
        install: '0'
        settings:
            version: 1.4.1
            java_install: true
    solr:
        install: '0'
        settings:
            version: 4.10.2
            port: '8984'

**Comment by chrisRidgers** [comment]
As an update on this one, 

I've tried today again on my Linux machine, and the box that was previously working is now broke.  Same error with adminer.

So two fresh boxes from puphpet later, the machine built.  Copied the resources to my project directory.  Machine built.

>2hours later, ran vagrant destroy, then vagrant up, and the machine ran into the same problem.

**Comment by chrisRidgers** [comment]
Having played around with this I've found the cause of the issue to be apache vhost set up for adminer.

Defining a docroot of /var/www/html/adminer results in the permission error on the initial vagrant up.

Altering it to point somewhere else creates the directory but installs it at /var/www/html/adminer regardless.  (if you then alter docroot back to that, and run vagrant provision, it is successful and the alias works.)

Attempting to leave the docroot out of the vhost configuration results in a different error, despite the fact that adminer will / will have installed there regardless.

**Comment by stevieg83** [comment]
definitely looks like a lot of permissions problems on these newer box builds :(

**Comment by chrisRidgers** [comment]
By not defining a vhost for adminer in config.yam it avoids the problem completely, but that isn't ideal because I then have to separately configure the alias inside my machine.

I'm not sure exactly what order / how this has been configured in puphpet, but the ideal solution for me would be to either place adminer wherever I want, with a  vhost / alias setup in config.yaml, or be syntactically allowed by puhphet to configure a docroot for adminer of /var/www/html/adminer without it breaking on the mkdir (which may be caused by adminer installing before apache creates /var/www/html, or the folder /var/www/html/adminer being created before mkdir attempts to create it, has happens when defining a docroot.  You can test it by giving it a docroot like: /var/www/adminer.  It get's created but adminer gets installed at /var/www/html/adminer).

**Comment by jtreminio** [comment]
Adminer support dropped; please add a vhost manually and install it yourself.
