### ISSUE TITLE
Could not locate the pip command

### ISSUE THREAD

**Issue by realshadow** [puphpet/puphpet#1743]
Hey,

I get this particular error on every python package I try to install

`Error: /Stage[main]/Puphpet_python/Package[celery]/ensure: change from absent to present failed: Could not set 'present' on ensure: Could not locate the pip command. at 30:/tmp/vagrant-puppet/manifests-893fcda21077f5a583c2dbbba8515c0a/nodes/Python.pp`

I am using 64 bit Ubuntu 14.04 box. I have seen this issue reference few times in different contexts during my googling period, but none of the suggested workarounds worked for me.

Here is my config

python:
    install: '1'
    packages:
        - argparse
        - fabric
        - celery
    versions:
        pyenv_iyq3pthajsir:
            version: 2.6.9
            virtualenv: '1'
        pyenv_pn3aa3l359pj:
            version: 3.3.5
            virtualenv: '1'

Is there any way to fix this issue? Its the last thing holding me from using vagrant to the fullest...

**Comment by Braunson** [comment]
@realshadow what was your solution (assuming you found one)?
