### ISSUE TITLE
for what create two private keys

### ISSUE THREAD

**Issue by SonkoDmitry** [puphpet/puphpet#1744]
after complete vagrant up we have two private keys (and theirs public keys and other):
puphpet/files/dot/ssh/id_rsa
puphpet/files/dot/ssh/root_id_rsa

puphpet/files/dot/ssh/id_rsa copied to .vagrant/machines/default/virtualbox/private_key and we can auth by ssh in root and vagrant users with this key. for what we need puphpet/files/dot/ssh/root_id_rsa?

**Comment by SonkoDmitry** [comment]
```
cat /root/.ssh/id_rsa.pub && cat /home/vagrant/.ssh/id_rsa.pub
``` 
are identical

**Comment by jtreminio** [comment]
Good catch, thanks!
