### ISSUE TITLE
Symbolic links and synced folders in puphpet. 

### ISSUE THREAD

**Issue by PrakashThapa** [puphpet/puphpet#1745]
when try to create symlink in shared folder
```
ln: failed to create symbolic link ‘/var/www/html.............’: Protocol error
```
```
ERROR: Unable to create symlink 
```
How to implement 
```
config.vm.provider "virtualbox" do |v|
    v.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root", "1"]
end
```
found [here in stackoverflow](http://stackoverflow.com/questions/24200333/symbolic-links-and-synced-folders-in-vagrant)

I am using latest version of puphpet

**Comment by jtreminio** [comment]
http://blog.puphpet.com/blog/2015/06/25/windows-symlinks/

What code are you using?

**Comment by PrakashThapa** [comment]
It's working Thank you
