### ISSUE TITLE
Debian wheezy phpmyadmin not executing

### ISSUE THREAD

**Issue by tthau2010** [puphpet/puphpet#1747]
I installed phpmyadmin with apt-get install phpmyadmin command, after go through the installation, i tried to open phpmyadmin in the browser with "tracker.jaavi.dev/phpmyadmin", my browser display php code which it means the php is not executing. My php is executing when i run tracker.jaavi.dev. Here is my phpmyadmin apache,conf

```
 /e/p/apache.conf
     AuthType Basic
     AuthName "phpMyAdmin Setup"
     AuthUserFile /etc/phpmyadmin/htpasswd.setup
     </IfModule>
     Require valid-user
 </Directory>

 # Disallow web access to directories that don't need it
 <Directory /usr/share/phpmyadmin/libraries>
     Order Deny,Allow
     Deny from All
 </Directory>
 <Directory /usr/share/phpmyadmin/setup/lib>
     Order Deny,Allow
     Deny from All
 /etc/phpmyadmin/apache.conf   CWD: /home/vagrant   Line: 36
"/etc/phpmyadmin/apache.conf" 48L, 1225C
```

**Comment by jtreminio** [comment]
Sorry, puphpet does not offer support for third party libraries.

You'll want to create a virtual host and set up phpmyadmin as any other project.
