### ISSUE TITLE
Website user experience - hints on dropdowns

### ISSUE THREAD

**Issue by jgrAlex** [puphpet/puphpet#1749]
The hints on the drop downs are covering the drop down options. You can not see what you select until you select something. Feels very annoying. I always run this in the console when using the website:
 $(".webui-popover").css("color", "transparent"); 
 $(".webui-popover").css("background-color", "transparent"); 

What if the hints came up above the drop downs, and not over them?

**Comment by thiagotalma** [comment]
https://github.com/puphpet/puphpet/pull/1746
