### ISSUE TITLE
Add ability to change the hdd size of the vagrant machine

### ISSUE THREAD

**Issue by aequasi** [puphpet/puphpet#1750]
As a user, it would be awesome to be able to specify the size of the virtual machine for all providers.

**Comment by jtreminio** [comment]
I do not think this is possible via Vagrant. This is a built-in thing with Virtualbox that can't be controlled outside of some archaic tools.

If you *really* need to use more space, I recommend building your own boxes using the puphpet templates: https://github.com/puphpet/packer-templates
