### ISSUE TITLE
nodejs modules install issues

### ISSUE THREAD

**Issue by Amparose** [puphpet/puphpet#1755]
My [config.yaml](https://gist.github.com/Amparose/2c1587fff00100aa1d5f) has the following nodejs modules:

- express
- pm2
- sequelize
- pg
- mongoose
- csurf

But I don't see where they are installed. `npm list -g --depth=0` lists only npm.

`npm config get prefix` prints `/usr/local` but I see no trace of anything node in there. Only thing I can find is `/usr/local/lib/node_modules/npm` and nothing else. pm2 and the modules seem to work though...

Am I missing something and is there a way to control where puphpet installs them?

**Comment by Amparose** [comment]
Ok, I'm not sure wtf is going as some nodejs modules are not being installed by Puphpet

`var express = require('express');` produces a `rror: Cannot find module 'express'`.

So any idea what I am missing? I would like to have a set of default node modules installed rather than everything in the projects package.json.

**Comment by Amparose** [comment]
Ok correction: Puphpet is installing them to: `/usr/lib/node_modules` and if I add that path to my .bash_aliases file then CLI `express` works but running a js file that requires express is still not finding the node_modules. So puphpet isn't setting the env paths correctly for node?

**Comment by spras** [comment]
hello, i was asking me the same questions.

thank's to you, i found the modules installed in  ```/usr/lib/node_modules```

but i don't see them by ```npm list -g``` and then when i made ```npm link``` in the directory of my project it install all modules localy ... 

has i missed something ?

**Comment by Amparose** [comment]
Yeah I haven't been able to fix this and I believe it is an issue with puphpet's configuration of node. We just installed modules locally for current project. Far from ideal but haven't had time to investigate what is going on.

**Comment by geoff-winner** [comment]
Anyone ever figure anything out on this topic?

**Comment by jtreminio** [comment]
This has been resolved.
