### ISSUE TITLE
Error: Files must be fully qualified at problem with custom_fragment

### ISSUE THREAD

**Issue by erdemece** [puphpet/puphpet#1757]
I I'm trying to add custom_fragment for symfony but I get this error

     Error: Files must be fully qualified at /tmp/vagrant-puppet/manifests-893fcda21077f5a583c2dbbba8515c0a/nodes/Apache.pp:176 on node symfony.local

here is my config: 

I have tried 
    custom_fragment: 'DirectoryIndex app_dev.php'
    custom_fragment: 'app_dev.php'
    custom_fragment: '/var/www/symfony/app_dev.php' this includes actual file into vhost config file anywasy.

what's wrong?

        symfony:
            servername: symfony.dev
            serveraliases:
                - www.symfony.dev
            docroot: /var/www/symfony/web
            port: '80'
            setenv:
                - 'APP_ENV dev'
            custom_fragment: 'DirectoryIndex /var/www/symfony/app_dev.php'
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            ssl_protocol: ''
            ssl_cipher: ''
            directories:
                avd_symfony:
                    path: /var/www/symfony/web
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                        - FileInfo
                    require:
                        - 'all granted'
                    custom_fragment: ''
                    files_match:
                        avdfm_symfony:
                            path: \.php$
                            sethandler: 'proxy:fcgi://127.0.0.1:9000'
                            custom_fragment: ''
                            provider: filesmatch
                    provider: directory

**Comment by jtreminio** [comment]
![image](https://cloud.githubusercontent.com/assets/589398/8602476/20920c74-2638-11e5-9cc6-0830629aa082.png)

Has to be a file that contains directives.

**Comment by ph55** [comment]
@jtreminio , I don't get it. How file could exist on vagrant up if it's only added to /var/www directory by this command.

So if I wan't to add this alias:
'Alias /PublicFilesAlias/ /var/www/project/master/public_html/'

I need to do 2 steps? Vagrant up without 'custom_fragmant' and provision with it?

Can you please help me to understand Juan?
