### ISSUE TITLE
php-fpm fails to start after provision?

### ISSUE THREAD

**Issue by georaldc** [puphpet/puphpet#1763]
Lately, I've been having trouble trying to get a centos + apache + php setup working right. For some reason, I always end up with the following warning/error at the end of the provision process:

    Warning: /Stage[main]/Puphpet_php/Service[php-fpm]: Skipping because of failed dependencies
    Error: Could not find a suitable provider for augeas

and I'm guessing this is what causes php-fpm to not start up? Manually starting it after the fact seems to work just fine.

**Comment by catalinux** [comment]
same here. destroy up goes well, but after provision, no php-fpm service

**Comment by theskillwithin** [comment]
same here

**Comment by illepic** [comment]
Wondering if this is related to:

https://github.com/mayflower/puppet-php/issues/79

Essentially non-ASCII characters in a conf file for php-fpm causes puppet to fail.

Do you happen to see this error on provision:

```
==> default: Info: Puphpet::Php::Pecl[pecl_http]: Scheduling refresh of Service[php5-fpm]
==> default: Error: /Stage[main]/Puphpet_php/Service[php5-fpm]: Could not evaluate: invalid byte sequence in US-ASCII
==> default: Notice: /Stage[main]/Puphpet_php/Service[php5-fpm]: Triggered 'refresh' from 1 events
```

**Comment by illepic** [comment]
Following up here: I rebuilt my config from scratch using the puphpet website - instead of starting from my existing config.yml and it looks like everything is working fine now. Basically, I must have had an error in my old config.yml that I was reintroducing each time I'd drag it into the puphpet website to auto-parse.
