### ISSUE TITLE
bash: line 5: /home/root/.ssh/authorized_keys: No such file or directory

### ISSUE THREAD

**Issue by PhilETaylor** [puphpet/puphpet#1766]
This was mentioned in #372 but that issue went off on a tangent.

I'm on a mac so the windows help for digital ocean is no good.

I do a vagrant up using this config:
https://gist.github.com/a892d9afa9ff0d0f879d

and then I get the following error. Note that the path to the roots home should be /root and not /home/root

![screen shot 2015-07-09 at 18 38 06](https://cloud.githubusercontent.com/assets/400092/8602330/b2f3716c-2669-11e5-956e-df386cce11d0.png)

**Comment by jtreminio** [comment]
I think this is a digital ocean plugin bug. Ask them.

Also, you should regenerate your key unless you're ok with your public key being ... public.

**Comment by PhilETaylor** [comment]
Its a throwaway ssh key :) so no worries there. 

When you say "digital ocean plugin" ... do you mean at the Vagrant level?

**Comment by jtreminio** [comment]
https://github.com/smdahlen/vagrant-digitalocean

**Comment by PhilETaylor** [comment]
Ok so I followed this rabbit hole and for completness I'm coming back to you to document this incase others also have this issue.

At the moment puphet creates a config with a setting of root for the config.ssh.username

If this is set then the vagrant-digitalocean plugin will attempt to create that root user - and obviously fails! 

- `provider.ssh_key_name` - A string representing the name to use when creating
  a Digital Ocean SSH key for droplet authentication. It defaults to `Vagrant`.
- `provider.setup` - A boolean flag indicating whether to setup a new user
  account and modify sudo to disable tty requirement. It defaults to `true`.
  If you are using a tool like [packer](https://packer.io) to create
  reusable snapshots with user accounts already provisioned, set to `false`.

The provider will create a new user account with the specified SSH key for
authorization if `config.ssh.username` is set and the `provider.setup`
attribute is `true`.

I'm fixing this in puphet code and will produce a pull request shortly... At the moment you are not allowing provider.setup to be set to false in the Vagrantfile-digitalocean or the config.yaml
