### ISSUE TITLE
Mailcatcher not running

### ISSUE THREAD

**Issue by chrisRidgers** [puphpet/puphpet#1770]
Think I've found an issue with Mailcatchers config.  Unable to connect to mailcatcher at target port.

Netstat shows its not running.  Think it's because supervisor.d is looking in the wrong place for the mailcatcher app.

Config.yaml:

    vagrantfile:
        target: local
        vm:
            box: puphpet/ubuntu1404-x64
            box_url: puphpet/ubuntu1404-x64
            hostname: nuin.mb
            memory: '1024'
            cpus: '1'
            chosen_provider: virtualbox
            network:
                private_network: 192.168.56.151
                forwarded_port:
                    vflnp_q7e6yg0fdk8b:
                        host: '8846'
                        guest: '22'
            post_up_message: ''
            provider:
                virtualbox:
                    modifyvm:
                        natdnshostresolver1: on
                    showgui: '0'
                vmware:
                    numvcpus: 1
                parallels:
                    cpus: 1
            provision:
                puppet:
                    manifests_path: puphpet/puppet
                    manifest_file: site.pp
                    module_path: puphpet/puppet/modules
                    options:
                        - '--verbose'
                        - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
                        - '--parser future'
            synced_folder:
                vflsf_w2zi4nbfwyfy:
                    source: ./
                    target: /var/www/project
                    sync_type: nfs
                    smb:
                        smb_host: ''
                        smb_username: ''
                        smb_password: ''
                    rsync:
                        args:
                            - '--verbose'
                            - '--archive'
                            - '-z'
                        exclude:
                            - .vagrant/
                            - .git/
                        auto: 'true'
                    owner: www-data
                    group: www-data
            usable_port_range:
                start: 10200
                stop: 10500
        ssh:
            host: null
            port: null
            private_key_path: null
            username: vagrant
            guest_port: null
            keep_alive: true
            forward_agent: false
            forward_x11: false
            shell: 'bash -l'
        vagrant:
            host: detect
    server:
        install: '1'
        packages:
            - htop
            - acl
    users_groups:
        install: '1'
        groups: {  }
        users: {  }
    firewall:
        install: '1'
        rules: {  }
    cron:
        install: '1'
        jobs: {  }
    nginx:
        install: '0'
        settings:
            default_vhost: 1
            proxy_buffer_size: 128k
            proxy_buffers: '4 256k'
        upstreams: {  }
        vhosts:
            nxv_ndf7dwrlpext:
                server_name: awesome.dev
                server_aliases:
                    - www.awesome.dev
                www_root: /var/www/awesome
                listen_port: '80'
                index_files:
                    - index.html
                    - index.htm
                    - index.php
                client_max_body_size: 1m
                ssl: '0'
                ssl_cert: ''
                ssl_key: ''
                ssl_port: '443'
                ssl_protocols: ''
                ssl_ciphers: ''
                rewrite_to_https: '1'
                spdy: '1'
                locations:
                    nxvl_xgnw8itvbdz0:
                        location: /
                        autoindex: off
                        try_files:
                            - $uri
                            - $uri/
                            - /index.php$is_args$args
                        fastcgi: ''
                        fastcgi_index: ''
                        fastcgi_split_path: ''
                    nxvl_dfv6hqg6h6w7:
                        location: '~ \.php$'
                        autoindex: off
                        try_files:
                            - $uri
                            - $uri/
                            - /index.php$is_args$args
                        fastcgi: '127.0.0.1:9000'
                        fastcgi_index: index.php
                        fastcgi_split_path: '^(.+\.php)(/.*)$'
                        fast_cgi_params_extra:
                            - 'SCRIPT_FILENAME $request_filename'
                            - 'APP_ENV dev'
        proxies: {  }
    apache:
        install: '1'
        settings:
            user: www-data
            group: www-data
            default_vhost: true
            manage_user: false
            manage_group: false
            sendfile: 0
        modules:
            - proxy_fcgi
            - rewrite
        vhosts:
            av_p5y9z6v857ck:
                servername: events.nu-ingredient.dev
                serveraliases:
                    - events.nu-ingredient.dev
                    - '*.vagrantshare.com'
                docroot: /var/www/project/web
                port: '80'
                setenv:
                    - 'APPLICATION_ENV development'
                    - 'SYSTEM_ENVIRONMENT development'
                custom_fragment: ''
                ssl: '0'
                ssl_cert: ''
                ssl_key: ''
                ssl_chain: ''
                ssl_certs_dir: ''
                ssl_protocol: ''
                ssl_cipher: ''
                directories:
                    avd_0hyzqvz29ob3:
                        path: /var/www/project/web
                        options:
                            - Indexes
                            - FollowSymlinks
                            - MultiViews
                        allow_override:
                            - All
                        require:
                            - 'all granted'
                        custom_fragment: ''
                        files_match:
                            avdfm_dw0ohpcwcnz7:
                                path: \.php$
                                sethandler: 'proxy:fcgi://127.0.0.1:9000'
                                custom_fragment: ''
                                provider: filesmatch
                        provider: directory
    php:
        install: '1'
        settings:
            version: '56'
        modules:
            php:
                - cli
                - intl
                - mcrypt
                - fpm
                - curl
                - gd
                - imagick
            pear: {  }
            pecl: {  }
        ini:
            display_errors: On
            error_reporting: '-1'
            session.save_path: /var/lib/php/session
            date.timezone: UTC
        fpm_ini:
            error_log: /var/log/php-fpm.log
        fpm_pools:
            phpfp_gkhklawojujq:
                ini:
                    prefix: www
                    listen: '127.0.0.1:9000'
                    security.limit_extensions: .php
                    user: www-user
                    group: www-data
        composer: '1'
        composer_home: ''
    xdebug:
        install: '0'
        settings:
            xdebug.default_enable: '1'
            xdebug.remote_autostart: '0'
            xdebug.remote_connect_back: '1'
            xdebug.remote_enable: '1'
            xdebug.remote_handler: dbgp
            xdebug.remote_port: '9000'
    blackfire:
        install: '0'
        settings:
            server_id: ''
            server_token: ''
            agent:
                http_proxy: ''
                https_proxy: ''
                log_file: stderr
                log_level: '1'
            php:
                agent_timeout: '0.25'
                log_file: ''
                log_level: '1'
    xhprof:
        install: '0'
    wpcli:
        install: '0'
        version: v0.19.0
    drush:
        install: '0'
        version: 6.3.0
    ruby:
        install: '1'
        versions:
            rv_mryrpx9pt4z2:
                default: '1'
                bundler: '1'
                version: 2.1.2
    python:
        install: '1'
        packages: {  }
        versions: {  }
    nodejs:
        install: '0'
        npm_packages: {  }
    hhvm:
        install: '0'
        nightly: 0
        composer: '1'
        composer_home: ''
        settings: {  }
        server_ini:
            hhvm.server.host: 127.0.0.1
            hhvm.server.port: '9000'
            hhvm.log.use_log_file: '1'
            hhvm.log.file: /var/log/hhvm/error.log
        php_ini:
            display_errors: On
            error_reporting: '-1'
            date.timezone: UTC
    mysql:
        install: '1'
        settings:
            version: '5.6'
            root_password: '123'
            override_options: {  }
        adminer: '1'
        users:
            mysqlnu_ua2mevjbbbcy:
                name: nuingredient
                password: password
        databases:
            mysqlnd_ap4kmkds0xw3:
                name: nu_ingredient
                sql: ''
        grants:
            mysqlng_3wvmaiv5fy6e:
                user: nuingredient
                table: '*.*'
                privileges:
                    - ALL
    postgresql:
        install: '0'
        settings:
            global:
                encoding: UTF8
                version: '9.3'
            server:
                postgres_password: '123'
        databases: {  }
        users: {  }
        grants: {  }
        adminer: 0
    mongodb:
        install: '0'
        settings:
            auth: 1
            bind_ip: 127.0.0.1
            port: '27017'
        databases: {  }
    redis:
        install: '0'
        settings:
            conf_port: '6379'
    sqlite:
        install: '0'
        adminer: 0
        databases: {  }
    mailcatcher:
        install: '1'
        settings:
            smtp_ip: 0.0.0.0
            smtp_port: 1025
            http_ip: 0.0.0.0
            http_port: '1080'
            mailcatcher_path: /usr/local/rvm/wrappers/default
            from_email_method: inline
    beanstalkd:
        install: '0'
        settings:
            listenaddress: 0.0.0.0
            listenport: '13000'
            maxjobsize: '65535'
            maxconnections: '1024'
            binlogdir: /var/lib/beanstalkd/binlog
            binlogfsync: null
            binlogsize: '10485760'
        beanstalk_console: 0
    rabbitmq:
        install: '0'
        settings:
            port: '5672'
        users: {  }
        vhosts: {  }
        plugins: {  }
    elastic_search:
        install: '0'
        settings:
            version: 1.4.1
            java_install: true
    solr:
        install: '0'
        settings:
            version: 4.10.2
            port: '8984'

While /etc/supervisor.d/program_mailcatcher.conf states:

    [program:mailcatcher]
    command=/usr/local/rvm/wrappers/default/mailcatcher  --http-ip 0.0.0.0 --http-port 1080 --smtp-ip 0.0.0.0 --smtp-port 1025 -f
    priority=100
    autostart=true
    autorestart=true
    user=mailcatcher
    stdout_logfile=/var/log/supervisor/program_mailcatcher.log
    stderr_logfile=/var/log/supervisor/program_mailcatcher.error
    environment=PATH='/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/rvm/wrappers/default'

However tha mailcatcher command is actually found at:

/usr/local/rvm/wrappers/ruby-1.9.3-p551/

Which isn't particularly ideal because I've installed 2.1.2 and set it to default.  I'm guessing this is what's causing my issue?

**Comment by chrisRidgers** [comment]
Sure enough updating the program_mailcatcher.conf to point at the mailcatcher command restarting my vagrant box was enough to get a connection at port 1080.

Not sure what the implications are of running that gem(?) with my system wide 2.1.2 version is but there you go.  Hopefully that's enough for you to go on to sort out a solution?

**Comment by chrisRidgers** [comment]
And sure enough sshing into the vagrant box and running

   gem install mailcatcher

And reloading the supervisor was successful as well.  I'm guessing the issue is that the mailcatcher gem installs prior to the default version of ruby being set to whatever you have configured in the ruby setup.

**Comment by marcelorl** [comment]
I have installed mailcatcher to my homestead applications (not a puphpet script at all)...I had some issues with that (more related with understanding), maybe it could be yours:

`$ sudo apt-get install ruby1.9.1-dev libsqlite3-dev`
`$ sudo gem install mailcatcher`
`$ mailcatcher --ip 192.168.50.10`

You can now access MailCatcher in your browser at http://192.168.50.10:1080.



My mail config file would look like this:

```
<?php
return [
  'driver'     => 'smtp',
  'host'       => '192.168.50.10',
  'port'       => 1025,
  'from'       => array('address' => 'test@example.com', 'name' => 'Test Email Sender'),
  'encryption' => false,
  'username'   => null,
  'password'   => null,
];
```

I have no idea if it can help you, but this is the final solution for me. haha

Bye.

**Comment by jtreminio** [comment]
Sorry, I can't offer support for other projects that are not puphpet.

**Comment by chrisRidgers** [comment]
This is a puphpet issue though: the configuration of the machine dictates when / where mailcatcher get's installed.  Currently, it installs within the system default version of ruby (currently 1.9.3 i think).  This happens regardless of the user setting the default version of Ruby to a more recent version (as you can using the Puphpet interface).

I'm fairly sure I've identified the problem: that puppet installs mailcatcher before configuring the default Ruby version.  I'm just not experienced in Puppets config files/ not the best person to implement a fix.

**Comment by wunc** [comment]
I have the same issue (mailcatcher fails to start) when specifying a different version of ruby as default:

```yaml
ruby:
    install: '1'
    versions:
        rv_uxtw6okyf5q2:
            default: '1'
            version: 2.2.3
```

If you don't want to mess with your guest VM settings or the puppet config, it worked for me by manually including mailcatcher in `config.yaml` as a gem for the specified ruby (along with libgmp-dev for gem compilation)

```yaml
server:
    install: '1'
    packages:
        - libgmp-dev
ruby:
    install: '1'
    versions:
        rv_uxtw6okyf5q2:
            default: '1'
            version: 2.2.3
            gems:
                - mailcatcher
mailcatcher:
    install: '1'
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '1080'
        mailcatcher_path: /usr/local/rvm/wrappers/default
        from_email_method: headers
```

Then provision, halt, and up the vagrant box, and mailcatcher works again for me.

However, @chrisRidgers is correct, in that mailcatcher is by default getting installed under ruby version 1.9.3, but not the specified default ruby version in `config.yaml`. So, it ends up not being in `/usr/local/rvm/wrappers/default` and fails to start. I also don't know enough about Puppet to figure out how to have mailcatcher install _after_ rvm installs and sets the default ruby, which would probably be the better overall solution.

**Comment by chrisRidgers** [comment]
@jtreminio I know you've already responded once on here but I really think this a Puphpet centric issue:

There's now myself and @wunc confirming the same behaviour and likely cause: misconfiguration of the installation order of mailcatcher / ruby versions.

If the problem isn't specific to mailcatcher (ie, other software has the same installation configuration) then any other software installing at the same stage as mailcatcher is going to run into the same issue.

**Comment by fnagel** [comment]
Same issue here (use another ruby version as default -> mailcatcher won't work) and @wunc workaround works for me. Thanks a lot!

**Comment by jtreminio** [comment]
Mailcatcher replaced by MailHog in 88e85be533e66a8fba94653a4d4672c1d6f5beb0
