### ISSUE TITLE
nginx rewrites

### ISSUE THREAD

**Issue by entr** [puphpet/puphpet#1771]
How do I set nginx rewrites using config.yaml?

I saw some examples provided by puppet-nginx and it looks like rewrites are supported using: 

``` yaml
{
  location_cfg_append => { 'rewrite' => '^ https://$server_name$request_uri? permanent' },
}
```

There's also `vhost_cfg_append`. Not sure how to test those efficiently without having to do `vagrant destroy && vagrant up`.

What i am trying to do right now is to be able to set rewrites at `server { }` block level.

**Comment by jtreminio** [comment]
Implemented.
