### ISSUE TITLE
Wrong pathname for apt-get managing into initial-setup.sh

### ISSUE THREAD

**Issue by tsyr2ko** [puphpet/puphpet#1777]
First, we check for a file
https://github.com/puphpet/puphpet/blob/master/archive/puphpet/shell/initial-setup.sh#L27
and if not, you create ... *another* file
https://github.com/puphpet/puphpet/blob/master/archive/puphpet/shell/initial-setup.sh#L34

Very fast to solve :)

**Comment by jtreminio** [comment]
Fixed by 22a7055ada897feb0ed999aa0e0f5807ac115d2f
