### ISSUE TITLE
Virtualbox 5 - Guest Additions Problems for mounting shares

### ISSUE THREAD

**Issue by mdemori** [puphpet/puphpet#1782]
Hi, 
I've just update Virtualbox to new 5.0 version, now when i try to vagrant up i receive a warning about wrong VirtualBox Guest Additions version and all share folder doesn't work.

So, i try to update it manually with below procedure:

    1 - ssh to vagrant host
    2 - mkdir /tmp_vbox
    3 - cd /tmp_vbox
    4 - sudo wget -c \
         http://download.virtualbox.org/virtualbox/5.0.0/VBoxGuestAdditions_5.0.0.iso  -O \ 
         VBoxGuestAdditions_5.0.0.iso
    5 - sudo mount VBoxGuestAdditions_5.0.0.iso -o loop /mnt
    6 - cd /mnt
    7 - sudo sh VBoxLinuxAdditions.run --nox11
    8 - sudo umount /mnt 
    9 - sudo rm -rf /tmp_vbox
    
     exit
     vagrat halt
     vagrant up 

now i receive below error:

    ==> default: Mounting shared folders...
           default: /var/www => C:/Users/user01/Desktop/puphpet/test_dir
           The following SSH command responded with a non-zero exit status.
           Vagrant assumes that this means the command failed!

          chown `id -u www-data`:`id -g www-data` /var/www

there is something that I've miss? how can i fix this problem?

thank you

**Comment by jtreminio** [comment]
vagrant, and puphpet, do not yet support virtualbox 5.

Consider downgrading.
