### ISSUE TITLE
Apache ports.conf

### ISSUE THREAD

**Issue by YanshuoH** [puphpet/puphpet#1791]
Hello,

I have a dummy question when I tried to install Varnish in the VM. I wonder if it is possible to modify Apache2's ports.conf somewhere in the config.yaml, to make it only listen to port 8080 (anything else but not 80).

Thanks.

**Comment by stevenmusumeche** [comment]
I'm also wondering the same thing. It sets listen on ports 80 and 443 by default and causes conflicts with other items on my system. I have no virtualhosts that listen on either 80 or 443.

**Comment by jtreminio** [comment]
Make sure `apache.default_vhost` is `false`

What's going on is that when adding a vhost, `$add_listen` is `true`, and it adds it to the ports config file.

The default vhost adds this :)
