### ISSUE TITLE
Copy files from host

### ISSUE THREAD

**Issue by bezruki** [puphpet/puphpet#1800]
I'm trying to configure the provisioning to copy a few files (virtual hosts and some shell profile stuff) to the vagrant box. I've tried modifying the `Vagrantfile` using this: http://docs.vagrantup.com/v2/provisioning/file.html

but that didn't work - guessing because that's not the correct way. Any ideas on how to do this via the `config.yaml`?

Thank you!

**Comment by MarshallOfSound** [comment]
+1 would like to do this aswell

**Comment by bezruki** [comment]
I found a way around this. In the folder 'puphpet/files' there are subfolders where you can put scripts that will execute after certain actions. I added a shell script that copies my files in 'startup-always', so when I start the machine, it does the job.
