### ISSUE TITLE
192.168.100.1 awesome.dev www.awesome.dev doesn't work due to wrong IP address

### ISSUE THREAD

**Issue by dsteplight** [puphpet/puphpet#1802]
When you go to http://192.168.56.101/ the instructions say to add "192.168.100.1 awesome.dev www.awesome.dev" to your /etc/hosts file , but that won't work because the real IP address you need to add is "192.168.56.101".  This small but importance difference had me restarting apache and re-provisioning my Vagrant instance like a mad man before I slowed down and thought about what could be wrong.

**Comment by jtreminio** [comment]
It's an example. The page is completely HTML, no PHP. I put that there as an example.
