### ISSUE TITLE
Support for Nginx Internal Location

### ISSUE THREAD

**Issue by ReservedDeveloper** [puphpet/puphpet#1820]
It would be great to see support for [nginx internal locations](http://nginx.org/en/docs/http/ngx_http_core_module.html#internal). This would allow users to fully implement [Symfony's recommend configuration for nginx hosts](http://symfony.com/doc/2.7/cookbook/configuration/web_server_configuration.html#nginx).

**Comment by jtreminio** [comment]
Thanks for the PR!
