### ISSUE TITLE
PuPHPet Truck Factor

### ISSUE THREAD

**Issue by gavelino** [puphpet/puphpet#1823]
As part of my PhD research on code authorship, we calculated the Truck Factor (TF) of some popular GitHub repositories.

As you probably know, the [Truck (or Bus) Factor](https://en.wikipedia.org/wiki/Bus_factor) designates the minimal number of developers that have to be hit by a truck (or quit) before a project is incapacitated. In our work, we consider that a system is in trouble if more than 50% of its files become orphan (i.e., without a main author).

More details on our work in this preprint: https://peerj.com/preprints/1233

We calculated the TF for **PuPHPet** and obtained a value of **1**.

The developer responsible for this TF is:

Juan Treminio - author of 92% of the files 

To validate our results, we would like to ask **PuPHPet** developers the following three brief questions:

(a) Do you agree that the listed developer is the main developer of **PuPHPet**?

(b) Do you agree that **PuPHPet** will be in trouble if the listed developer leave the project (e.g., if he wins in the lottery, to be less morbid)?

(c) Does **PuPHPet** have some characteristics that would attenuate the loss of the listed developer (e.g., detailed documentation)?

Thanks in advance for your collaboration,

Guilherme Avelino
PhD Student
Applied Software Engineering Group (ASERG)
UFMG, Brazil
http://aserg.labsoft.dcc.ufmg.br/

**Comment by jtreminio** [comment]
* Yes
* No, there's several projects that have began as forks of puphpet, or been "inspired by". If I died, this project in particular may be in trouble since no one else can push to it, but all in all the legacy would continue.
* Hoping "it's not that hard to figure it out" is a valid characteristic
