### ISSUE TITLE
apache custom fragment error

### ISSUE THREAD

**Issue by stevenmusumeche** [puphpet/puphpet#1825]
adding this custom fragment to apache vhost causes the following error:

```
custom_fragment: 'SetEnvIfNoCase ^Authorization$ "(.+)" HTTP_AUTHORIZATION=$1'
```

```
Error: Files must be fully qualified at /tmp/vagrant-puppet/manifests/............../nodes.Apache.pp:176
```

I looked at that file, and the error occurs here:

```
    $vhost_custom_fragment = array_true($vhost, 'custom_fragment') ? {
      true    => file($vhost['custom_fragment']), //error occurs on this line
      default => '',
    }
```

If I remove the custom_fragment, everything works fine (but that fragment doesn't get inserted, which is what I'm after).

**Comment by jtreminio** [comment]
`custom_fragment` must point to a file. This was the only way around non-trivial code users wanted to insert.

**Comment by stevenmusumeche** [comment]
Thanks. A file on the vhost?

**Comment by Artistan** [comment]
if the file is in your puphpet folder you can use

    /vagrant/custom-directives.txt
