### ISSUE TITLE
version on mongodb

### ISSUE THREAD

**Issue by sid606** [puphpet/puphpet#1828]
Hi

Is there option to set what version on mongodb will be installed on provision?

Because there is a big difference in 2.4, 2.6 and 3. Now it install version 2.4 
Thanks

**Comment by maxxon15** [comment]
:+1: I need this too. Preferably 3.0 one on my debian VM.

**Comment by thadkiss** [comment]
+1

**Comment by jtreminio** [comment]
Closed by 1cf2b5a
