### ISSUE TITLE
SSH tunnel Valentina Studio

### ISSUE THREAD

**Issue by Neabfi** [puphpet/puphpet#1832]
Hello,

I can't connect to Mysql via Valentina Studio.

<img width="561" alt="a" src="https://cloud.githubusercontent.com/assets/8831940/9155149/b36495ba-3eae-11e5-982c-a505de60e916.png">
<img width="647" alt="b" src="https://cloud.githubusercontent.com/assets/8831940/9155150/b741ff38-3eae-11e5-9031-4160e32e53c6.png">
I didn't do anything special.
I can not solve the problem.

**Comment by thiagotalma** [comment]
Dear, this is not a Puphpet issue.
Use gitter for help.

By the way, this is not the correct form to connect to mysql.

Use port forwarding or tunnelling.

**Comment by Neabfi** [comment]
Sorry ! But it's tunnelling no ?

**Comment by TheRojam** [comment]
why dont you use sequel pro under mac?
