### ISSUE TITLE
Synced folder: Invalid parameter (hostpath)

### ISSUE THREAD

**Issue by frops** [puphpet/puphpet#1836]
##### CMD log
> E:\vm\server1>vagrant up
> Bringing machine 'default' up with 'virtualbox' provider...
> There was an error while executing `VBoxManage`, a CLI used by Vagrant
> for controlling VirtualBox. The command and stderr is shown below.
> 
> Command: ["sharedfolder", "add", "c6d8c983-05e7-43d7-a790-e3d2c137a388", "--name", "", "--hostpath", "E:/vm/server1"]
> 
> Stderr: Oracle VM VirtualBox Command Line Management Interface Version 5.0.0
> (C) 2005-2015 Oracle Corporation
> All rights reserved.
> 
> Usage:
> 
> VBoxManage sharedfolder     add <uuid|vmname>
>                             --name <name> --hostpath <hostpath>
>                             [--transient] [--readonly] [--automount]
> 
> 
> Syntax error: **Invalid parameter 'E:/vm/server1'**

##### config.yaml
> synced_folder:
>   9OoRaUVi6iap:
>                source: ./
>                target: /var/www
>                nfs: 'false'

##### Info
- Windows 7;
- Vagrant 1.7.4;
- Puphpet generated on https://puphpet.com;
- VirtualBox 5.0.0;

Whats is problem, anybody know?

**Comment by jtreminio** [comment]
Vbox 5.0 is causing problems:

![image](https://cloud.githubusercontent.com/assets/589398/9571926/f5db9858-4f6b-11e5-865e-bc63768086e0.png)
