### ISSUE TITLE
vagrant up failes because of DNS issues

### ISSUE THREAD

**Issue by driehle** [puphpet/puphpet#1850]
Hi,

first of all, I am not sure if this is an issue of PuPHPet, Vagrant or probably VirtualBox, but maybe you folks have a hint, so let's give it a try.

Here is my config.yaml: http://pastebin.com/YMPwxcuR

I have a Windows 8.1 system, where `vagrant up` runs just fine and the PHP application is available via http://localhost:8080/. However, I also have a Windows 7 system, where `vagrant up` brings the following error:

```
==> default: ERROR:  Could not find a valid gem 'deep_merge' (>= 0), here is why
:
==> default:           Unable to download data from https://rubygems.org/ - no s
uch name (https://rubygems.org/specs.4.8.gz)
==> default: ERROR:  Could not find a valid gem 'activesupport' (>= 0), here is
why:
==> default:           Unable to download data from https://rubygems.org/ - no s
uch name (https://rubygems.org/specs.4.8.gz)
```

So obviously (and I verified that by accessing the root shell of the VM and using `dig`) the VM is not able to resolve hostnames, as DNS is not working. And that causes some parts to be missing and the whole thing to crash later on.

The only difference between my two system that I am aware of so far is that the Windows 8.1 system (workin) has direct and unfiltered internet access, while the Windows 7 system (not working) is behind a firewall that blocks outgoing DNS traffic. Therefore the VM cannot access the Google DNS Servers (8.8.8.8 and 8.8.4.4) which are in `/etc/resolv.conf`.

But shouldn't that be handled by `virtualbox.modifyvm.natdnshostresolver1: 'on'` which I have in my `config.yaml`? Is that configuration probably not applied to the VM correctly?

Here is the output of `VBoxManage showvminfo dev-local`: http://pastebin.com/dQ0JBDLU.

Thanks!

**Comment by huebschi** [comment]
I got the same Errors

My VBoxInfo: http://pastebin.com/PgJVjuk1
My Config: http://pastebin.com/R7jwDFt0

Thanks!

**Comment by joshdaws** [comment]
I'm experiencing the same error. Either of you have any luck?

**Comment by Hopiu** [comment]
I had the same problem on my machines. The problem was the lacking internet connection during the setup process of the vm.
I got around it by changing the DNS in config.yaml to use the ones of my company instead of the Google DNS.

**Comment by webconsult** [comment]
I have the same error and it seems to be related to my puphpet configuration as I have other VM boxes that runs successfully.

I discovered that my VM can't access the internet - so it is probably a DNS issue. I'm at work at the moment, so I first suspected a firewall issue, but then I tried provisioning using the internet connection off my phone, which is not behind firewall and the problem persisted.

How, specifically, do I change the DNS settings in config.yaml? Can you show me how you set it up?

I downloaded the latest ubuntu box and downloaded a fresh puphpet configuration right before trying to provision this site. It is an old configuration which has been working fine in the past, but I could not provision when I tried today (did not notice if I got the same error), so I just went straight to puphpet.com and re-imported the config.yaml because that's what has been working out in the past.

Here is my config.yaml:

http://pastebin.com/VjCcfs3A

**Comment by driehle** [comment]
It is a network issue, or more specifically a DNS issue. I checked it once again, an my network blockes outgoing DNS traffic, therefore PuPHPet can not contact the Google DNS Servers. Within my network only the DNS servers provided via DHCP can be used - which the host systems knows, but PuPHPet does not know them...

**Comment by cooperaj** [comment]
If you comment out lines 54 and 55 of ```shell/initial-setup.sh``` then you skip the bit where it sets the Google DNS entries. Everything works fine after this.

I've got no idea why this needs to be in there.

**Comment by driehle** [comment]
I can confirm that @cooperaj's suggestion does the trick.

The Google DNS servers have been introducted in fa774e4 to fix #1120 with a resolveconf module and have been moved into the setup shell scripts with bdc979c to fix #1612. The removal of the resolveconf module is also discussed in #1735.

Maybe @jtreminio knows why the Google DNS servers are used in PuPHPet?

**Comment by mslabko** [comment]
I can confirm @cooperaj too
Issue has occurred on Mac 10.10.5.

**Comment by jtreminio** [comment]
Needs boxes rebuilt to reset them. Sorry guys :)

**Comment by Braunson** [comment]
Still having this issue using the latest Virtual Box, Vagrant and PuPHPET Configuration..

**Comment by renegaed** [comment]
yep this is google DNS issue. I fixed it by changing my DNS settings from my router (which was the default) to point to google DNS servers 8.8.8.8 and 8.8.4.4 and it worked fine after that.

**Comment by Artistan** [comment]
Happened for me when there was no id_rsa key??? seems odd, but now it works.
Centos 6.5 + Apache + Php7

**Comment by junkystu** [comment]
[This](http://pastebin.com/cjW6GtPW) fixed it for me.

**Comment by deleed** [comment]
thank you @junkystu !

**Comment by fzoccara** [comment]
thank you @junkystu !

**Comment by grshane** [comment]
@junkystu This worked for me as well

**Comment by gryphonmyers** [comment]
@junkystu very helpful. thanks

**Comment by rakelot** [comment]
@junkystu thank you, This works.
