### ISSUE TITLE
The root password input field under the database sections have placeholder="/path/to/your/web/files".

### ISSUE THREAD

**Issue by jasuess** [puphpet/puphpet#1854]
As this is meant for a password and not path to a file the placeholder attribute seems to have an incorrect value?

Example:

```html
<input type="text" id="mariadb-settings-root_password" name="mariadb[settings][root_password]" placeholder="/path/to/your/web/files" class="form-control" value="123">
```

**Comment by jasuess** [comment]
Problem seems to affect only MySQL, MariaDB and Postgres sections.

**Comment by jasuess** [comment]
The database section under MySQL and MariaDB also has a misleading placeholder attribute for "Import Database From File". It shows "123" instead of a /path/to/file text.

**Comment by jtreminio** [comment]
Fixed by 1855
