### ISSUE TITLE
FreeBSD 10.1 Support

### ISSUE THREAD

**Issue by killua99** [puphpet/puphpet#1857]
Hi,

before I ask about that, to support FreeBSD and I get a reply (twitter) that you need first the packer thing.

So I did a work to add the FreeBSD option, you can take a look at this branch

https://github.com/killua99/packer-templates/tree/freebsd-10.1-x86_64/freebsd-10.1-x86_64

I'll like to know when you'll like to review this branch to handle a pull request.

**Comment by jtreminio** [comment]
Hi,

Sorry but adding FreeBSD would be far too much work. Not only are base boxes needed to be created, but every software currently available in the GUI would also need to be added for FreeBSD, tracking down all repos.

Most of the packages do not have a FreeBSD version available, making this a fairly limited box.
