### ISSUE TITLE
Debian Wheezy 7 x64 - php5.4 - xdebug

### ISSUE THREAD

**Issue by maltyxx** [puphpet/puphpet#1865]
==> default: Error: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install php5-xdebug' returned 100: Reading package lists...
==> default: Building dependency tree...
==> default: Reading state information...
==> default: Some packages could not be installed. This may mean that you have
==> default: requested an impossible situation or if you are using the unstable
==> default: distribution that some required packages have not yet been created
==> default: or been moved out of Incoming.
==> default: The following information may help to resolve the situation:
==> default: 
==> default: The following packages have unmet dependencies:
==> default:  php5-xdebug : Depends: php5-common (= 5.4.43-1~dotdeb+7.1) but 5.4.44-0+deb7u1 is to be installed
==> default: E: Unable to correct problems, you have held broken packages.
==> default: 
==> default: Error: /Stage[main]/Puphpet::Php::Xdebug/Package[xdebug]/ensure: change from purged to present failed: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install php5-xdebug' returned 100: Reading package lists...
==> default: Building dependency tree...
==> default: Reading state information...
==> default: Some packages could not be installed. This may mean that you have
==> default: requested an impossible situation or if you are using the unstable
==> default: distribution that some required packages have not yet been created
==> default: or been moved out of Incoming.
==> default: The following information may help to resolve the situation:
==> default: 
==> default: The following packages have unmet dependencies:
==> default:  php5-xdebug : Depends: php5-common (= 5.4.43-1~dotdeb+7.1) but 5.4.44-0+deb7u1 is to be installed
==> default: E: Unable to correct problems, you have held broken packages.
==> default:

**Comment by maltyxx** [comment]
- php5-xdebug
- php5-imagick
- php5-memcached
- php5-zendopcache

**Comment by maltyxx** [comment]
$ sudo apt-cache show php5-xdebug
Package: php5-xdebug                                                                                                                                                                                                                         
Version: 5.4.43-1~dotdeb+7.1
Architecture: amd64
Maintainer: Guillaume Plessis <gui@dotdeb.org>
Installed-Size: 284
Pre-Depends: dpkg (>= 1.15.7.2~) | dpkg-maintscript-helper
Depends: libc6 (>= 2.4), phpapi-20100525, php5-common (= 5.4.43-1~dotdeb+7.1)
Filename: dists/wheezy/php5-pecl/binary-amd64/php5-xdebug_5.4.43-1~dotdeb+7.1_amd64.deb
Size: 103016
MD5sum: f70e2fc565338e0a7949ac4234350ff2
SHA1: c549534d207238266492be147710ac11c4e5741a
SHA256: 39f2096532bfe74b21f0aa23103263f857a3c6b7375f7a9e71846331d6021435
Section: php
Priority: optional
Description: xdebug module for php5
 This package provides a module for xdebug functions in PHP scripts.
 .
 PHP5 is a widely-used general-purpose scripting language that is
 especially suited for Web development and can be embedded into HTML.
 The goal of the language is to allow web developers to write
 dynamically generated pages quickly.

Package: php5-xdebug
Source: xdebug
Version: 2.2.1-2
Installed-Size: 736
Maintainer: Martin Meredith <mez@debian.org>
Architecture: amd64
Depends: ucf, libc6 (>= 2.3), phpapi-20100525
Description-en: Xdebug Module for PHP 5
 The Xdebug extension helps you debugging your script by providing a lot of
 valuable debug information. The debug information that Xdebug can provide
 includes the following:
 .
    * stack traces and function traces in error messages with:
       - full parameter display for user defined functions
       - function name, file name and line indications
       - support for member functions
    * memory allocation
    * protection for infinite recursions
 .
 Xdebug also provides:
 .
    * profiling information for PHP scripts
    * script execution analysis
    * capabilities to debug your scripts interactively with a debug client
Homepage: http://xdebug.org/
Description-md5: f290606f41907c43167040fbfc0ecc1c
Tag: devel::debugger, devel::lang:php, devel::testing-qa, implemented-in::c,
 interface::daemon, role::program, scope::application, use::analysing,
 use::checking, use::monitor
Section: php
Priority: optional
Filename: pool/main/x/xdebug/php5-xdebug_2.2.1-2_amd64.deb
Size: 269450
MD5sum: bd46ac3046b20df4900c2b052b9ab3a5
SHA1: ef206e113a69cb0ea88b27dddddf84cbff859ad2
SHA256: bac369541ef4dc297bd8567640fd5be402701c9f7b28279c9f97624897093f9b

**Comment by jtreminio** [comment]
Show me your config.yaml...
