### ISSUE TITLE
'up' causes other vagrants to give 'Forbidden, you don't have acce...'

### ISSUE THREAD

**Issue by Danielss89** [puphpet/puphpet#1868]
I have many different vagrant running at once. But something weird has begun happening, can't say exactly when. The error is as follows:

Whenever i up a new vagrant, all my other running vagrants starts saying "Forbidden, You don't have permission to access xxxx on this server." in the browser. Then i have to halt the vagrant i want to work, and up it again. That makes that single vagrant work, but now the other vagrant gives the "Forbidden" message :S

Any clues as to why this happens?

**Comment by jtreminio** [comment]
Do all your VMs have different IP addresses?

**Comment by Danielss89** [comment]
Yes, all have their own IP.
