### ISSUE TITLE
FilesMatch block isn't added in the config.yaml.

### ISSUE THREAD

**Issue by janzenz** [puphpet/puphpet#1872]
My `php` files aren't parsing. I noticed that the `FilesMatch` block  isn't added in the config.yaml file. So I had to add it in manually.

I got this from the configurator:

        av_s4zfpb2muecx:
            servername: sandbox.dev
            serveraliases:
                - www.sandbox.dev
            docroot: /var/www
            port: '80'
            setenv:
                - 'APP_ENV dev'
            custom_fragment: ''
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            ssl_protocol: ''
            ssl_cipher: ''
            directories:
                avd_e84h116m6dg3:
                    path: /var/www
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - 'all granted'
                    custom_fragment: ''
                    provider: directory

Notice the files_match block isn't there.

**Comment by jtreminio** [comment]
Looks like you might have accidentally deleted the block while creating your config in the GUI:

![image](https://cloud.githubusercontent.com/assets/589398/11455859/bb427dde-9637-11e5-9b09-8c78618e1ea1.png)
