### ISSUE TITLE
SMB mount issue and restrictive file permissions

### ISSUE THREAD

**Issue by alvinpascoe** [puphpet/puphpet#1874]
I am using 
- Windows 8.1 host machine
- Vagrant 1.7.4
- VirtualBox 4.3.28
- puphpet/ubuntu1404-x64 guest box.

I have experienced two issues, which I've subsequently fixed but wanted to create an issue to help others in the same situation (until the updates are committed).

1) The SMB drive would not mount. 
I followed step 2 in the following comment in issue [#1845](https://github.com/puphpet/puphpet/issues/1845#issuecomment-135941152). 
This involved removing the quotes from the smb settings in the `puphpet/config.yaml` file.

The settings should now look as follows (notice the lack of quotes following `smb_host`, `smb_username`, `smb_password`):

```
synced_folder:
        vflsf_viofro49rfje5:
            source: ./
            target: /var/www
            sync_type: smb
            smb:
                smb_host:
                smb_username:
                smb_password:
```

This now allowed Vagrant to prompt me for my Windows username and password during `vagrant up` (remember to use a terminal with administrator privileges).

2) Once mounted, all files in the document root `/var/www/html` were read only from the guest ssh session. The VM could not update these files. This had not been an issue before switching to SMB from the `default` sync type.

On closer inspection, I noticed that document root files didn't have group write privileges when mounted via SMB. 

I was put on the right track by referencing a vagrant specific issue from last year [#3237](https://github.com/mitchellh/vagrant/issues/3237#issuecomment-37907996)

Since I'm using puphpet, I opened `puphpet/vagrant/Vagrantfile-local` and added the following `mount options` (the new code has been added to the last line...and don't forget the comma at the end of the line above it):

```
elsif folder['sync_type'] == 'smb'
    smb__host     = !folder['smb']['smb_host'].nil? ? folder['smb']['smb_host'] : nil
    smb__username = !folder['smb']['smb_username'].nil? ? folder['smb']['smb_username'] : nil
    smb__password = !folder['smb']['smb_password'].nil? ? folder['smb']['smb_password'] : nil

    config.vm.synced_folder "#{folder['source']}", "#{folder['target']}", id: "#{i}", type: 'smb',
      group: sync_group, owner: sync_owner, smb_host: smb__host, smb_username: smb__username, smb_password: smb__password,
      :mount_options => ["file_mode=0774", "dir_mode=0775"]
```

.
On looking through the file, it seems that the `default` sync type option included mount options but the SMB option does not and the 744 permissions that the SMB setup loaded by default were too restrictive.

After running `vagrant reload`, I was able to boot up using SMB and have complete access to the files within the Vagrant ssh session.

**Comment by Rvanlaak** [comment]
https://github.com/alehkot/druphpet seems to support SMB nicely
