### ISSUE TITLE
can't send mail

### ISSUE THREAD

**Issue by steros** [puphpet/puphpet#1875]
using the standard configuration I tried a simple mail command
<?php
 mail('test@test.com', 'test', 'test');

and get the following error:

`check_delivery_params': An SMTP From address is required to send a message. Set the message smtp_envelope_from, return_path, sender, or from address. (ArgumentError)

**Comment by emielmolenaar** [comment]
This has nothing to do with the puphpet box. Just read the error, or try the first hit on Google.
