### ISSUE TITLE
merge_yaml: cannot load such file -- active_support

### ISSUE THREAD

**Issue by SonkoDmitry** [puphpet/puphpet#1879]
Has error
```
Error: Could not autoload puppet/parser/functions/merge_yaml: cannot load such file -- active_support
```
CentOS based pack

**Comment by SonkoDmitry** [comment]
I need to resolve this problem, I can't to start vagrant

**Comment by mattsnowboard** [comment]
I hit the same error. Cygwin/Windows 8.1 host. Vagrant 1.7.4

My config.yaml:

    vagrantfile:
        target: local
        vm:
            box: puphpet/centos65-x64
            box_url: puphpet/centos65-x64
            hostname: movies.dev
            memory: '2048'
            cpus: '1'
            chosen_provider: virtualbox
            network:
                private_network: 192.168.56.102
                forwarded_port:
                    vflnp_g80qfsj69ldc:
                        host: '9417'
                        guest: '22'
            post_up_message: ''
            provider:
                virtualbox:
                    modifyvm:
                        natdnshostresolver1: 'on'
                    showgui: '0'
                vmware:
                    numvcpus: 1
                parallels:
                    cpus: 1
            provision:
                puppet:
                    manifests_path: puphpet/puppet
                    manifest_file: site.pp
                    module_path: puphpet/puppet/modules
                    options:
                        - '--verbose'
                        - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
                        - '--parser future'
            synced_folder:
                vflsf_ri2ns3l47n42:
                    source: ./
                    target: /var/project
                    sync_type: rsync
                    smb:
                        smb_host: ''
                        smb_username: ''
                        smb_password: ''
                    rsync:
                        args:
                            - '--verbose'
                            - '--archive'
                            - '-z'
                            - '--delete'
                        exclude:
                            - .vagrant/
                            - .git/
                            - nbproject/
                            - vendor/
                            - var/cache/
                            - var/logs/
                            - var/bootstrap.php.cache
                            - web/bundles
                            - web/css
                            - web/fonts
                            - web/js
                            - bin/
                        auto: 'true'
                    owner: www-data
                    group: www-data
            usable_port_range:
                start: 10200
                stop: 10500
        ssh:
            host: null
            port: null
            private_key_path: null
            username: vagrant
            guest_port: null
            keep_alive: true
            forward_agent: false
            forward_x11: false
            shell: 'bash -l'
        vagrant:
            host: detect
    server:
        install: '1'
        packages:
            - emacs
            - git
    users_groups:
        install: '1'
        groups: {  }
        users: {  }
    locale:
        install: '1'
        settings:
            default_locale: ''
            locales:
                - en_GB.UTF-8
                - en_US.UTF-8
    firewall:
        install: '1'
        rules: {  }
    cron:
        install: '1'
        jobs: {  }
    nginx:
        install: '0'
        settings:
            default_vhost: 1
            proxy_buffer_size: 128k
            proxy_buffers: '4 256k'
        upstreams: {  }
        vhosts:
            nxv_7a2omrl0c54m:
                server_name: awesome.dev
                server_aliases:
                    - www.awesome.dev
                www_root: /var/www/awesome
                listen_port: '80'
                index_files:
                    - index.html
                    - index.htm
                    - index.php
                client_max_body_size: 1m
                ssl: '0'
                ssl_cert: ''
                ssl_key: ''
                ssl_port: '443'
                ssl_protocols: ''
                ssl_ciphers: ''
                rewrite_to_https: '1'
                spdy: '1'
                locations:
                    nxvl_hs900mi2a7xk:
                        location: /
                        autoindex: 'off'
                        internal: 'off'
                        try_files:
                            - $uri
                            - $uri/
                            - /index.php$is_args$args
                        fastcgi: ''
                        fastcgi_index: ''
                        fastcgi_split_path: ''
                    nxvl_isk7yi58bqlr:
                        location: '~ \.php$'
                        autoindex: 'off'
                        internal: 'off'
                        try_files:
                            - $uri
                            - $uri/
                            - /index.php$is_args$args
                        fastcgi: '127.0.0.1:9000'
                        fastcgi_index: index.php
                        fastcgi_split_path: '^(.+\.php)(/.*)$'
                        fast_cgi_params_extra:
                            - 'SCRIPT_FILENAME $request_filename'
                            - 'APP_ENV dev'
        proxies: {  }
    apache:
        install: '1'
        settings:
            user: www-data
            group: www-data
            default_vhost: true
            manage_user: false
            manage_group: false
            sendfile: 0
        modules:
            - proxy_fcgi
            - rewrite
        vhosts:
            av_j5g0ozcbqt1i:
                servername: movies.dev
                serveraliases:
                    - www.awesome.dev
                docroot: /var/www/movies
                port: '80'
                custom_fragment: ''
                ssl: '0'
                ssl_cert: ''
                ssl_key: ''
                ssl_chain: ''
                ssl_certs_dir: ''
                ssl_protocol: ''
                ssl_cipher: ''
                directories:
                    avd_vm3wrbh8kdjr:
                        path: /var/www/movies
                        options:
                            - Indexes
                            - FollowSymlinks
                            - MultiViews
                        allow_override:
                            - All
                        require:
                            - 'all granted'
                        custom_fragment: ''
                        files_match:
                            avdfm_ii4rrcfbkixe:
                                path: \.php$
                                sethandler: 'proxy:fcgi://127.0.0.1:9000'
                                custom_fragment: ''
                                provider: filesmatch
                        provider: directory
    php:
        install: '1'
        settings:
            version: '56'
        modules:
            php:
                - cli
                - intl
                - mcrypt
                - gd
                - curl
            pear: {  }
            pecl: {  }
        ini:
            display_errors: 'On'
            error_reporting: '-1'
            session.save_path: /var/lib/php/session
            date.timezone: America/Los_Angeles
            memory_limit: 256M
            max_execution_time: '120'
        fpm_ini:
            error_log: /var/log/php-fpm.log
        fpm_pools:
            phpfp_p38rqzne9kwa:
                ini:
                    prefix: www
                    listen: '127.0.0.1:9000'
                    security.limit_extensions: .php
                    user: www-user
                    group: www-data
        composer: '1'
        composer_home: ''
    xdebug:
        install: '1'
        settings:
            xdebug.default_enable: '1'
            xdebug.remote_autostart: '0'
            xdebug.remote_connect_back: '1'
            xdebug.remote_enable: '1'
            xdebug.remote_handler: dbgp
            xdebug.remote_port: '9001'
            xdebug.max_nesting_level: '256'
            xdebug.idekey: netbeans-xdebug
            xdebug.remote_host: 10.0.2.2
    blackfire:
        install: '0'
        settings:
            server_id: ''
            server_token: ''
            agent:
                http_proxy: ''
                https_proxy: ''
                log_file: stderr
                log_level: '1'
            php:
                agent_timeout: '0.25'
                log_file: ''
                log_level: '1'
    xhprof:
        install: '0'
    wpcli:
        install: '0'
        version: v0.19.0
    drush:
        install: '0'
        version: 6.3.0
    ruby:
        install: '1'
        versions: {  }
    python:
        install: '1'
        packages: {  }
        versions: {  }
    nodejs:
        install: '1'
        npm_packages:
            - less
            - grunt-cli
            - gulp
            - bower
    hhvm:
        install: '0'
        nightly: 0
        composer: '1'
        composer_home: ''
        settings: {  }
        server_ini:
            hhvm.server.host: 127.0.0.1
            hhvm.server.port: '9000'
            hhvm.log.use_log_file: '1'
            hhvm.log.file: /var/log/hhvm/error.log
        php_ini:
            display_errors: 'On'
            error_reporting: '-1'
            date.timezone: UTC
    mysql:
        install: '1'
        settings:
            version: '5.6'
            root_password: secret1990
            override_options: {  }
        adminer: 0
        users:
            mysqlnu_c3dof0z8mfj7:
                name: app
                password: XLvZ9UQKFLLLuibyvHlcyCcxszG
        databases:
            mysqlnd_7waq954m9sgo:
                name: movies
                sql: ''
        grants:
            mysqlng_9spgx1specrz:
                user: app
                table: '*.*'
                privileges:
                    - ALL
    mariadb:
        install: '0'
        settings:
            version: '10.0'
            root_password: '123'
            override_options: {  }
        adminer: 0
        users:
            mariadbnu_ifgkroou2bmz:
                name: dbuser
                password: '123'
        databases:
            mariadbnd_c0pphsgb27g6:
                name: dbname
                sql: ''
        grants:
            mariadbng_4tc3s0zo4n39:
                user: dbuser
                table: '*.*'
                privileges:
                    - ALL
    postgresql:
        install: '0'
        settings:
            global:
                encoding: UTF8
                version: '9.3'
            server:
                postgres_password: '123'
        databases: {  }
        users: {  }
        grants: {  }
        adminer: 0
    mongodb:
        install: '0'
        settings:
            auth: 1
            bind_ip: 127.0.0.1
            port: '27017'
        databases: {  }
    redis:
        install: '0'
        settings:
            conf_port: '6379'
    sqlite:
        install: '1'
        adminer: 0
        databases: {  }
    mailcatcher:
        install: '0'
        settings:
            smtp_ip: 0.0.0.0
            smtp_port: 1025
            http_ip: 0.0.0.0
            http_port: '1080'
            mailcatcher_path: /usr/local/rvm/wrappers/default
            from_email_method: inline
    beanstalkd:
        install: '0'
        settings:
            listenaddress: 0.0.0.0
            listenport: '11300'
            maxjobsize: '65535'
            maxconnections: '1024'
            binlogdir: /var/lib/beanstalkd/binlog
            binlogfsync: null
            binlogsize: '10485760'
        beanstalk_console: 0
    rabbitmq:
        install: '0'
        settings:
            port: '5672'
        users: {  }
        vhosts: {  }
        plugins: {  }
    elastic_search:
        install: '0'
        settings:
            version: 1.4.1
            java_install: true
    solr:
        install: '0'
        settings:
            version: 4.10.2
            port: '8984'

**Comment by mattsnowboard** [comment]
Problem seemed to be caused by the VM hostname being *.dev. Changed it to vagrant.local and it worked. Apparently .dev is a TLD now so it causes DNS issues.

**Comment by jtreminio** [comment]
Yep, Google purchased the .dev TLD.
