### ISSUE TITLE
wrong option in nginx configuration

### ISSUE THREAD

**Issue by thrgl** [puphpet/puphpet#1881]
Hey, with a default configuration I'm getting:

Error: "off" is not a boolean.  It looks to be a String at /tmp/vagrant-puppet/modules-1f2d20ef901849e116c9fda2fa9b9511/nginx/manifests/resource/location.pp:198 on node local.puphpet

It's related to this part:
nginx->vhosts->VHOSTNAME->locations->LOCATIONNAME->
autoindex: 'off'
internal: 'off'

changing it to false/false resolves the problem.

**Comment by jtreminio** [comment]
Fixed by 36878e0
