### ISSUE TITLE
Cannot provision old files anymore

### ISSUE THREAD

**Issue by P3t3rT** [puphpet/puphpet#1885]
Reprovisioning existing config is not possible anymore.
It seems that /vagrant/puphpet/shell cannot be located. No idea why this doesn't work anymore.
(issue #1363 does not bring a solution)

config.yaml: gist:ca3a7ad351bd37839957
vagrant output: gist:cc7e4a7c29186c448861

Mac: 10.10.5
Parallels: 10.2.2
Vagrant: 1.7.2
 Any help is highly appreciated

**Comment by jtreminio** [comment]
Please update :) Many changes since!
