### ISSUE TITLE
Changes on the nodejs website breaks the node and npm intallation script

### ISSUE THREAD

**Issue by Remuwon** [puphpet/puphpet#1886]
Currently the install script

puphpet/puppet/modules/puphpet/templates/nodejs/install.erb

Points to http://nodejs.org/dist/latest/ which redirects to the nodejs blog so the download of the nodejs archive fails.

Currently the work around is to modify the script to point to https://nodejs.org/dist/latest/

**Comment by martinsteinorth** [comment]
The CURL request currently points to http://nodejs.org/dist/latest/SHASUMS.txt

Should be http://nodejs.org/dist/latest/SHASUMS256.txt instead.

Quickfix is to modify Line 11 from

`LATEST_NODE=$(curl 'http://nodejs.org/dist/latest/SHASUMS.txt' | grep "${FILENAME}" | awk '{ print $2 }')``

to

`LATEST_NODE=$(curl 'http://nodejs.org/dist/latest/SHASUMS256.txt' | grep "${FILENAME}" | awk '{ print $2 }')`

Works for me after monkeypatch.

**Comment by emmio-micke** [comment]
Thank you for this.

**Comment by emielmolenaar** [comment]
See #1895 also.

**Comment by jtreminio** [comment]
Merged.
