### ISSUE TITLE
Enable SSI for PHP files

### ISSUE THREAD

**Issue by cazzerson** [puphpet/puphpet#1889]
I ran into an issue when setting up an development environment for an existing PHP app because SSI is not enabled by default in Puphpet for PHP files. Adding `AddOutputFilter INCLUDES php` to the custom fragment, but I think that it may be worth setting this or something similar by default for a PHP development environment.

**Comment by Renkas** [comment]
Why should this be default for PHP? SSI has nothing to do with PHP and using PHP itself means that you most probably are not using SSI - as it's kind of pointless to use both technologies together.

I would have no problem to have it as just an option (default off). But enabling something that is extremely rarely used by default has no point. It just adds processing overhead to the request.

**Comment by cazzerson** [comment]
Fair enough. Since I would only use puphpet as a dev environment, I'm not
particularly concerned about the cost of processing includes. An option
would be nice, though.

**Comment by jtreminio** [comment]
The custom_fragment is the perfect place for this.
