### ISSUE TITLE
Using newer Xdebug version

### ISSUE THREAD

**Issue by Spriz** [puphpet/puphpet#1893]
Hey!

Any chance that the debug coming with puppet could be bumped? :smile: 

```
$ xdebug --version
PHP 5.6.12-1+deb.sury.org~trusty+1 (cli)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies
    with Xdebug v2.3.1, Copyright (c) 2002-2015, by Derick Rethans
```

Unfortunately there's issues with phpunit and Xdebug 2.3.1 - which are fixed in 2.3.2 (https://github.com/puphpet/puphpet/issues/1368)

config.yaml = https://gist.github.com/Spriz/173b7d5689dcb2dd58e9

**Comment by jadb** [comment]
:+1:

**Comment by Spriz** [comment]
??? :disappointed:
