### ISSUE TITLE
[New feature] Add pinba and pinboard 

### ISSUE THREAD

**Issue by oskarcalvo** [puphpet/puphpet#190]
PInba.org is a profiling service similar to newrelic, and pinboard  ( https://github.com/intaro/pinboard ) is the app to read the information.

It'll be great to be able to install it.

Oskar

**Comment by thiagotalma** [comment]
@jtreminio any decision on NewRelic?
It would be a good improvement.

**Comment by oskarcalvo** [comment]
What about this tickets.

We will see Pinba as an option in puphpet?

Thanks

Oskar
