### ISSUE TITLE
Install Issue

### ISSUE THREAD

**Issue by djeraseit** [puphpet/puphpet#1907]
So downloading this onto apache. Ran "composer install" then I get the following error:

Parse error: syntax error, unexpected '.', expecting ')' in /var/www/html/puphpet/src/Puphpet/MainBundle/Extension/Manager.php on line 20
Oops! An Error Occurred

The server returned a "500 Internal Server Error".

Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.

**Comment by jtreminio** [comment]
Use this: https://github.com/puphpet/production

And adjust to your needs to run it locally or remotely.
