### ISSUE TITLE
Drush install fails

### ISSUE THREAD

**Issue by robme** [puphpet/puphpet#1911]
My box worked fine, until I changed drush install to 1 in the config.yaml. Now when I run `vagrant up` I get this error:

```
==> default: Notice: /Stage[main]/Composer/Package[php-cli]/ensure: created
==> default: Notice: /Stage[main]/Composer/Exec[download_composer]/returns: executed successfully
==> default: Notice: /Stage[main]/Composer/File[/usr/local/bin/composer]/ensure: defined content as '{md5}a5aa9948d1e8efa96666efe3c90e5adf'
==> default: Notice: /Stage[main]/Puphpet::Php::Drush/Exec[first drush run]: Dependency Exec[composer_install_drush] has failures: true
==> default: Notice: /Stage[main]/Puphpet::Php::Drush/File[symlink drush]: Dependency Exec[composer_install_drush] has failures: true
==> default: Error: php /usr/local/bin/composer install --no-plugins --no-scripts --no-interaction --dev returned 2 instead of one of [0]
==> default: Error: /Stage[main]/Puphpet::Php::Drush/Composer::Exec[drush]/Exec[composer_install_drush]/returns: change from notrun to 0 failed: php /usr/local/bin/composer install --no-plugins --no-scripts --no-interaction --dev returned 2 instead of one of [0]
==> default: Warning: /Stage[main]/Puphpet::Php::Drush/Exec[first drush run]: Skipping because of failed dependencies
==> default: Warning: /Stage[main]/Puphpet::Php::Drush/File[symlink drush]: Skipping because of failed dependencies
```

I have no idea what this means. At first I thought the problem was composer, but it looks like it's failing when trying to fetch dependencies for Drush. It doesn't say in what way it failed though, so I don't know how to proceed. I tried with debug mode but it just says the same messages more times.

**Comment by matason** [comment]
I'm getting exactly the same with, I'll let you know if I discover a fix.

**Comment by matason** [comment]
I found if I ssh'd into the VM, cd'd to /usr/share/drush and issued php /usr/local/bin/composer install --no-plugins --no-scripts --no-interaction I got the following:

Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for phpunit/phpunit 4.0.17 -> satisfiable by phpunit/phpunit[4.0.17].
    - phpunit/phpunit 4.0.17 requires ext-dom * -> the requested PHP extension dom is missing from your system.

I initially thought the simple addition of the php-xml package (which would satisfy the ext-dom requirement) would solve the issue but it does not, a vagrant destroy followed by a vagrant up still results in the same errors.

**Comment by matason** [comment]
I had a gut feeling it might be a timeout issue but adding timeout = 0 to the following block

composer::exec { 'drush':
      cmd     => 'install',
      cwd     => $drush_location,
      require => Vcsrepo[$drush_location],
      timeout => 0,
} ->

in puppet/modules/puphpet/manifests/php/drush.pp did not resolve the issue. NOTE: My assumption is that disables the default timeout for the drush install operation.

Not a fix but I found that running vagrant provision after the initial errors seems complete the drush installation.

**Comment by robme** [comment]
Thanks it works great.

**Comment by marcelomg** [comment]
Hi,
The fixes listed above no longer work. Here is my drush.pp

```

# This depends on puppetlabs-vcsrepo: https://github.com/puppetlabs/puppetlabs-vcsrepo.git
# This depends on puppet-composer: https://github.com/tPl0ch/puppet-composer
# Installs drush system wide
class puphpet::php::drush(
  $version
) {

    $drush_github   = 'https://github.com/drush-ops/drush.git'
    $drush_location = '/usr/share/drush'

    exec { 'delete-drush-path-if-not-git-repo':
      command => "rm -rf ${drush_location}",
      onlyif  => "test ! -d ${drush_location}/.git",
      path    => [ '/bin/', '/sbin/', '/usr/bin/', '/usr/sbin/' ],
    } ->
    vcsrepo { $drush_location:
      ensure   => present,
      provider => git,
      source   => $drush_github,
      revision => $version,
    } ->
    composer::exec { 'drush':
      cmd     => 'install',
      cwd     => $drush_location,
      dev     => false,
      require => Vcsrepo[$drush_location],
    } ->
    exec { 'first drush run':
      command => 'drush cache-clear drush',
      path    => [
        '/bin/', '/sbin/', '/usr/bin/', '/usr/sbin/', $drush_location
      ],
    } ->
    file { 'symlink drush':
      ensure => link,
      path   => '/usr/bin/drush',
      target => "${drush_location}/drush",
    }

}
```


Any suggestions?

**Comment by lfmartin** [comment]
@marcelomg you need to check if you have all the needed PHP extensions. do a `vagrant ssh` and goto `cd /usr/share/drush`. Here you run `sudo composer install` - it will tell you if you are missing something and if not it will start downloading dependencies for drush. I myself where missing the **dom** PHP extension. So to sum up step-by-step,
- `vagrant up`
- `vagrant ssh`
- `cd /usr/share/drush`
- `sudo composer install`
- If any unmet dependencies, then goto `config.yaml` in the php -> modules -> php section and add any missing PHP extension dependencies.
- Do step 1-4 again
- Inside the box do the symlink for drush `ln -s /usr/share/drush/drush /usr/bin/drush`

And you should be good to go.

**Comment by vincenzo** [comment]
I am trying to install Drush 8.1.7. 
All works when I provision with PHP7; it stops working if I switch to PHP 5.6 and I get

```
Error: php /usr/local/bin/composer install --no-plugins --no-scripts --no-interaction returned 2 instead of one of [0]
/Stage[main]/Puphpet::Drush::Install/Composer::Exec[drush]/Exec[composer_install_drush]/returns: change from notrun to 0 failed: php /usr/local/bin/composer install --no-plugins --no-scripts --no-interaction returned 2 instead of one of [0]
```

Any idea @jtreminio @Ifmartin?

**Comment by vincenzo** [comment]
Must be said that if I ssh into the box after it failed, and I manually run `sudo composer install` from `/usr/share/drush`, it works.

**Comment by vincenzo** [comment]
@jtreminio This issue has reappeared for me, now on PHP7. See https://github.com/puphpet/puphpet/issues/2595.

**Comment by robme** [comment]
It's back for me as well. Weirdly, it worked OK in PHP7, but when I destroyed the box and changed it to PHP5.6 it failed.

To be honest I gave up on Puphphet a long time ago, I just thought I would give it another try for a project. But there's only so many times I can wait 20+ minutes for `vagrant up` only to have errors again.

**Comment by vincenzo** [comment]
@robme That was my original problem (worked on 7, failed on 5.6), which eventually went away without changing a thing. Now it's the reverse, and honestly, since it makes no sense, I disabled the installation of drush via the config, and used a shell provisioning script to install drush myself. Still annoying, though.
