### ISSUE TITLE
hhvm session directory permissions error, debian package

### ISSUE THREAD

**Issue by spekary** [puphpet/puphpet#1912]
Received ps_files_cleanup_dir: opendir(/var/lib/hhvm/sessions) failed: Permission denied (13) during PHP session_start

The debian package is preconfigured to point to /var/lib/hhvm/sessions for storing sessions for hhvm, but does not give enough permissions to allow session_start to scan the directory during garbage collection.

Possible solutions are to either add more permissions to whoever is specified as the http server user, or more likely, point the session directory to the the same place as the default PHP location,. which should already be configured correctly.

**Comment by blackseadev** [comment]
up
