### ISSUE TITLE
bindfs+nfs: --user and --group options are deprecated

### ISSUE THREAD

**Issue by akomm** [puphpet/puphpet#1920]
Initially I thought it was a `vagrant-bindfs` bug:

https://github.com/gael-ian/vagrant-bindfs/issues/35

But it is not. The error is located here:

[Vagrantfile-local#L91](https://github.com/puphpet/puphpet/blob/ff70d4b6664da18bba44d8254d6d7fe2e5eb1b59/archive/puphpet/vagrant/Vagrantfile-local#L91)

Its mapped to the options `--user` and `--group`, which are deprecated as of bindfs version 1.12.

Instead of:
```
owner: sync_owner, group: sync_group
```
It should be:
```
force_user: sync_owner, force_group: sync_group
```

I don't know if other deploy-targets are also affected. I'v only tested `local`.

**Comment by akomm** [comment]
Looks like #1929 also fixed this issue. If I'm wrong, correct me, otherwise this can be closed?

**Comment by jtreminio** [comment]
Yup! Thanks.
