### ISSUE TITLE
PHP7 problem

### ISSUE THREAD

**Issue by x2002uwh** [puphpet/puphpet#1923]
I was trying to build one PHP7 dev instance, it never works. No matter I choose Apahce2 or Nginx. 

For example, when I chosed Apache2,  I got 
"==> default: Error: php: error while loading shared libraries: libjpeg.so.62: cannot open shared object file: No such file or directory
==> default: curl: (23) Failed writing body (0 != 16133)
==> default: 
==> default: Error: /Stage[main]/Composer/Exec[download_composer]/returns: change from notrun to 0 failed: php: error while loading shared libraries: libjpeg.so.62: cannot open shared object file: No such file or directory
==> default: curl: (23) Failed writing body (0 != 16133)
==> default: 
==> default: Notice: /Stage[main]/Composer/File[/usr/local/bin/composer]: Dependency Exec[download_composer] has failures: true
==> default: Warning: /Stage[main]/Composer/File[/usr/local/bin/composer]: Skipping because of failed dependencies
"

But when I chose Nginx, it had another problem.

I would like to know if anyone get the PHP7 Instance work.

Thanks!

**Comment by sh0umik** [comment]
I am also having problem configuring php7 . It shows blank page . .php files are not executing

**Comment by lukaszwit** [comment]
Same for me. No matter what I choose - PHP7 always fails.

**Comment by calinpristavu** [comment]
#1831 gives hints on how to partialy solve the problem

**Comment by lukedanielson** [comment]
Anyone have any luck installing PHP7?

I've attempted the script addition to `initial-setup.sh` proposed in #1831 by @x2002uwh , but am still receiving the libjpeg error:

```
Error: php: error while loading shared libraries: libjpeg.so.62: 
cannot open shared object file: No such file or directory
```

**Comment by mmieluch** [comment]
@lukedanielson I succesfully (almost) installed PHP7 after adding `libjpeg62` to system packages.

From my config.yaml:

```
server:
    install: '1'
    packages:
        - vim
        - htop
        - libjpeg62
```

Give it a shot.

**Comment by jtreminio** [comment]
PHP installation changed via 88212277b4196c4faa898d7f96294478185e973e

Please regenerate archive. Note that it doesn't currently have a ton of modules.
