### ISSUE TITLE
vhost configuration error?

### ISSUE THREAD

**Issue by webconsult** [puphpet/puphpet#1927]
I had some issues with my existing setup, so I figured I'd solve it by importing config.yaml and downloading a new configuration from here. But apparently that created a new issue.

When I spin up a box, the provisioning finishes without errors, excepts for the `default: stdin: is not a tty` which is always there. But when I try to use the box, I realize apache won't run.

I tried debugging vhosts by running:
 
    $ apache2ctl -t
    AH00526: Syntax error on line 39 of /etc/apache2/sites-enabled/10-default_vhost_443.conf:
    SSLCertificateKeyFile: file '/etc/ssl/private/ssl-cert-snakeoil.key' does not exist or is empty
    Action '-t' failed.
    The Apache error log may have more information.

So I checked the apache error log:

    $ cat /var/log/apache2/error.log
    [Wed Sep 30 21:30:59.037462 2015] [mpm_event:notice] [pid 23570:tid 139952102680448] AH00489: Apache/2.4.16 (Ubuntu) configured -- resuming normal operations
    [Wed Sep 30 21:30:59.037858 2015] [core:notice] [pid 23570:tid 139952102680448] AH00094: Command line: '/usr/sbin/apache2'
    [Wed Sep 30 21:35:55.485655 2015] [mpm_event:notice] [pid 23570:tid 139952102680448] AH00491: caught SIGTERM, shutting down
    [Wed Sep 30 21:35:57.012964 2015] [mpm_worker:notice] [pid 9267:tid 139889041471360] AH00292: Apache/2.4.16 (Ubuntu) OpenSSL/1.0.1f configured -- resuming normal operations
    [Wed Sep 30 21:35:57.013048 2015] [core:notice] [pid 9267:tid 139889041471360] AH00094: Command line: '/usr/sbin/apache2'

I also tried changing permissions for /etc/ssl/private but it is set to root and I can't figure out how to fix that with the vagrant user and I assume there is something else wrong with the configuration anyways.

Here is my config.yaml: https://gist.github.com/webconsult/b533c14af534e76a6f7c

**Comment by jtreminio** [comment]
Please try again, I believe this was fixed a bit ago!

**Comment by rvoortman** [comment]
Is this the same as this ( #1690 )issue?
