### ISSUE TITLE
data-update change not reflected in config.yaml

### ISSUE THREAD

**Issue by PierrickI3** [puphpet/puphpet#1944]
Hi,

I have the older version of your site. At the time, you helped me with an issue I had to select a checkbox based on another checkbox being checked (for example, disabling nginx if apache is selected).

It's working fine on the web page itself however the resulting config.yaml does not reflect the change. For example, I have a checkbox (checkbox A) that, if checked, checks another checkbox (checkbox B). The web page shows that both checkboxes are checked. However, in the config.yaml, only the item for checkbox A value is set to "1".

I have debugged and added extra logging and found out that the data received in indexAction for MainBundle does not have the right data.

I am not sure where to go next. Could you give me some tips?

**Comment by jtreminio** [comment]
I believe you contacted me via email.

After having gone through your code, you're right in that it's older codebase.

It would probably be simplest to simply update to the newest codebase to get this working.

If that's not possible, I would copy these lines over to the javascript file you have: https://github.com/puphpet/puphpet/blob/master/web/assets/v5/js/custom.js#L134-L270

And here's how to use it:

```
                <input type="checkbox" name="apache[vhosts][{{ uniqid }}][ssl]"
                       class="invisible toggle-on-select
                              update-other-input-on-check update-other-input-on-uncheck"
                       {% if ssl %}checked{% endif %}
                       value="1"
                       data-vis-toggle-target="#apache-vhosts-{{ uniqid }}-ssl_options"
                       data-update-on-check-apache[vhosts][{{ uniqid }}][port]="443"
                       data-update-on-uncheck-apache[vhosts][{{ uniqid }}][port]="80" />```

**Comment by PierrickI3** [comment]
Thank you Juan. Updating to the newer codebase would be significant for me. You have probably noticed that I have made a lot of changes.

Your changes did not fix it my issue though. The issue that I have is not about getting the checkbox checked. That worked already. The issue is that the config.yaml does not reflect the correct value.

FYI, if I check it manually, the config.yaml has the correct value.

I have trouble understanding how the config.yaml is actually generated. After doing some troubleshooting and adding extra logging, I believe the issue lies somewhere in the createArchive() function in Manager.php or in the MainBundle's FrontController. 

Would you prefer if I created an issue in my repo instead of using puphpet's repo?

Thanks.
