### ISSUE TITLE
Digitalocean installs fail when a specified SSH key is already on an account

### ISSUE THREAD

**Issue by ameliaikeda** [puphpet/puphpet#1948]
When trying to add a box on digitalocean, the entire process seems to be revolved around a user who doesn't already have an account, or has literally just signed up for one.

I've already got several DO boxes going, and thought it'd be expected that someone would choose a key that already exists on their account.

Turns out, I was wrong. If the key you specify already exists in digitalocean (I have one key per machine), then you just flat-out can't use the digitalocean provider.

```
➜  ~/dev/puppet  vagrant up              
Bringing machine 'default' up with 'digital_ocean' provider...
==> default: Creating new SSH key: MacBook...
There was an issue with the request made to the DigitalOcean
API at:

Path: /v2/account/keys
URI Params: {:name=>"MacBook", :public_key=>"ssh-rsa ...\n"}

The response status from the API was:
å
Status: 422
Response: {"id"=>"unprocessable_entity", "message"=>"SSH Key is already in use on your account"}
```

Could this error be caught and skipped during the `vagrant up` process?

**Comment by jtreminio** [comment]
Sorry, this is a plugin issue, not puphpet. I can't help :(
