### ISSUE TITLE
Firewall config issue: is_string('21') returns false, breaks firewall config

### ISSUE THREAD

**Issue by Richtermeister** [puphpet/puphpet#1951]
The Firewall config executes an is_string check against the port, but specifying a port as string as such 
```port: '21'``` fails this check and consequently puphpet does not wrap it into an array and fails down the road.

See: https://github.com/puphpet/puphpet/blob/master/archive/puphpet/puppet/nodes/Firewall.pp#L14

Interestingly, the is_string function seems designed in such a way, which I find counter-intuitive as well, especially since there is also an is_numeric check which seems more suitable for this purpose.. 

See: https://github.com/puppetlabs/puppetlabs-stdlib/blob/master/spec/functions/is_string_spec.rb#L12

So, not sure if the stdlib is_string is at fault here and should be changed, or it we should just check for !is_array to get the same effect..

**Comment by jtreminio** [comment]
This is fixed.
