### ISSUE TITLE
[Feature request] Target Variant

### ISSUE THREAD

**Issue by vincenzo** [puphpet/puphpet#1952]
With this I am suggesting to have a new (optional) property in the `config.yaml` file. Something like `target-variant: whatever`.

This would allow (as I am using it now) to load to have this in the main `Vagrantfile`: 

```ruby
eval File.read("#{dir}/puphpet/vagrant/Vagrantfile-#{data['target']}-#{data['target-variant']}")
```

and therefore, to be able to have `puphpet/vagrant/Vagrantfile-local-whatever` if `target: local` and `target-variant: whatever`.

This would allow to manage some custom additions that one makes to config and Vagrantfiles more cleanly, as I see it.

**Comment by jtreminio** [comment]
Implemented in #1903
