### ISSUE TITLE
MySQL 5.7 support

### ISSUE THREAD

**Issue by cookiecavekeeper** [puphpet/puphpet#1954]
MySQL now has a 5.7 GA available [for download](http://dev.mysql.com/downloads/mysql/).

What is needed to add this as a supported version?

Just add it here https://github.com/puphpet/puphpet/blob/master/src/Puphpet/MainBundle/Resources/config/mysql/available.yml like in #1553 ?

**Comment by jtreminio** [comment]
Unfortunately puppetlabs-mysql does not support even 5.6, so 5.7 is out of the question until they catch up.

For now I would highly suggest going with MariaDB.
