### ISSUE TITLE
Provisioning fails when Nginx default_vhost is false

### ISSUE THREAD

**Issue by likeuntomurphy** [puphpet/puphpet#1957]
The following error occurs when trying to provision a new VM when Nginx:settings:default_vhost is set to 0:
```
Error: Could not find dependency File[/var/www/html] for Exec[Set /var/www/html/index.html contents] at /tmp/vagrant-puppet-3/manifests/nodes/Nginx.pp:336
```
I tried this with a standard config file, using only the defaults and changing nothing besides setting default_vhost to 0.

**Comment by jtreminio** [comment]
Fixed by #2082
