### ISSUE TITLE
Problem with xdebug

### ISSUE THREAD

**Issue by webconsult** [puphpet/puphpet#1972]
I don't really know if this is related to puphpet after all, but considering that I am running a mostly stock puphpet setup, I'm thinking that there is a good likelihood that others may have come across the same issue.

I am experiencing an issue where Xdebug will successfully break on breakpoints, but whenever I try to use step over, step into or in any other way interact with the code, I get a 503 error in the browser. When I check my syslog I see that I get a segfault whenever this happens.

I've tried upgrading xdebug with `pecl upgrade xdebug` without any luck. I also tried changing the remote port (I read somewhere about fpm also using port 9000). None of which helped.

I managed to turn on error logging for xdebug, but I don't really know what to make of the output:

    <- eval -i 27 -- JEdMT0JBTFNbJ0lERV9FVkFMX0NBQ0hFJ11bJzAzZjdiYWEzLWVlZDItNGM4OS1hNzY5LWU0ZjdjMDhjZjY3OCddPShpc3NldCgkbm9kZSwkbm9kZS0+Y29tcHV0ZWRfZmlsZV9leHRlbnNpb24pKT8oJG5vZGUtPmNvbXB1dGVkX2ZpbGVfZXh0ZW5zaW9uWyd1bmQnXSk6IklERV9FVkFMX0VSUiI=
    -> <response xmlns="urn:debugger_protocol_v1" xmlns:xdebug="http://xdebug.org/dbgp/xdebug" command="eval" transaction_id="27"><property address="140736383501456" type="string" size="12" encoding="base64"><![CDATA[SURFX0VWQUxfRVJS]]></property></response>

    <- step_over -i 28
    -> <response xmlns="urn:debugger_protocol_v1" xmlns:xdebug="http://xdebug.org/dbgp/xdebug" command="step_over" transaction_id="28" status="break" reason="ok"><xdebug:message filename="file:///var/www/checkouts/dev1/index.php" lineno="19"></xdebug:message></response>

    <- stack_get -i 29

Here is my puphpet configuration: https://gist.github.com/webconsult/dfa23f65ce2394624b0d

**Comment by jtreminio** [comment]
> I've tried upgrading xdebug with `pecl upgrade xdebug`

puphpet compiles xdebug from source, not pecl.

This may be either an xdebug issue or whatever debugger you're using.

Here's an example on a VM I just built:

![image](https://cloud.githubusercontent.com/assets/589398/11464229/191c4d9e-96f2-11e5-9dab-2679a129ad5b.png)


![image](https://cloud.githubusercontent.com/assets/589398/11464232/22190fa4-96f2-11e5-9529-403d0bde61fe.png)
