### ISSUE TITLE
MySQL requires choosing a root password. Please check your config.yaml file.

### ISSUE THREAD

**Issue by jpswade** [puphpet/puphpet#1973]
As far as I'm aware, MySQL will install with a blank/empty root password.

I appreciate that setting MySQL with a blank/empty root password may be a security issue for some, however this kind of security check seems outside of the scope of puphpet.

https://github.com/puphpet/puphpet/blob/master/archive/puphpet/puppet/nodes/Mysql.pp#L42

**Comment by ccapndave** [comment]
Or if this check is going to stay in then the web UI shouldn't validate an empty root password on the MySQL page (but I also agree with @jpswade that this check is outside the scope of puphpet)
