### ISSUE TITLE
Problems with current nodejs under CentOS 6.6

### ISSUE THREAD

**Issue by head82** [puphpet/puphpet#1978]
I ran into several problems with npm 3 (shipped with nodejs5).

No problems with nodejs 4.2.2 (npm 2.14.7). Just changed install.erb:

    LATEST_NODE=$(curl 'http://nodejs.org/dist/v4.2.2/SHASUMS256.txt' | grep "${FILENAME}" | awk '{ print $2 }')
    wget --quiet --tries=5 --connect-timeout=10 --no-check-certificate -O '/.puphpet-stuff/nodestable.tar.gz' "http://nodejs.org/dist/v4.2.2/${LATEST_NODE}"

This is only for testing, but perhaps a version selector for nodejs is required?

**Comment by jtreminio** [comment]
CentOS 6 cannot install nodejs > 0.12

**Comment by head82** [comment]
yes, and this is the problem because the current code is going to install the latest version or not?

```bash
LATEST_NODE=$(curl 'http://nodejs.org/dist/latest/SHASUMS256.txt' | grep "${FILENAME}" | awk '{ print $2 }')
wget --quiet --tries=5 --connect-timeout=10 --no-check-certificate -O '/.puphpet-stuff/nodestable.tar.gz' "http://nodejs.org/dist/latest/${LATEST_NODE}"
```
