### ISSUE TITLE
MySQLworckbench 

### ISSUE THREAD

**Issue by Jakub41** [puphpet/puphpet#1979]
Hello I would like to know how to use MySQLworckbench with Vagrant. I triying to set up but my connection is refused. Can you explain me with examples what I have to do for make it work please??

Thanks for help
Jakub

**Comment by Renkas** [comment]
You need to make an SSH tunnel.

Connection method: "Standard TCP/IP over SSH"
SSH hostname: your hostname
SSH username: vagrant
SSH key file: full path to puphpet/files/dot/ssh/id_rsa
MySQL hostname: 127.0.0.1
MySQL username and MySQL password: whatever you have set up

**Comment by Jakub41** [comment]
Thank you but I did in the same way and connection refuse :(

**Comment by Renkas** [comment]
Well it works for me ... Double check what your setup is

**Comment by Jakub41** [comment]
Ok I will try again

**Comment by robinbentley** [comment]
You could try setting the SSH Hostname to **127.0.0.1:2222** (replace 2222 if you have changed the forwarded ssh port)

I'm on ubuntu and find that I can't get a connection just using the vagrant IP

**Comment by Renkas** [comment]
I'm using my custom domain (xyz.dev) for the connection - not localhost or IP.

**Comment by Jakub41** [comment]
Ok I will set in the same way thanks

**Comment by webconsult** [comment]
First make sure that you are actually able to ssh to your box without using `vagrant ssh`. Try doing ` ssh vagrant@[box ip address] -i [path/to/your/project]/puphpet/files/dot/ssh/insecure_private_key´. I've set up vagrant with Sequel Pro many times and I've often run into problems. Usually an issue with known hosts or, like the last time, I discovered that my insecure_private_key had too open permissions.

**Comment by steros** [comment]
I have the same problem. Except I copied an older workbench connection config and used it with a new box.
I can connect to older boxes but a recently build one fails. It can't establish the ssh tunnel.
The server is up and running. I can do "vagrant ssh" just fine and locally I can connect to mysql.

**Comment by jtreminio** [comment]
@steros There is no password. You should use the id_rsa that's generated instead.

Here's what your connection settings should look like:

![image](https://cloud.githubusercontent.com/assets/589398/11464134/1028bdc2-96f1-11e5-9c24-783c61a05f8e.png)

**Comment by steros** [comment]
Ah I've used the insecure private key as mentioned above before. It seems that doesn't work anymore. It works with the id_rsa.
Thanks
