### ISSUE TITLE
Nginx Configuration?

### ISSUE THREAD

**Issue by jekelhart** [puphpet/puphpet#1980]
Hello,

i'm trying to setup my development vm with puphpet. I followed all steps and the vm is starting and everything seems to work well.
But when I try to open the website I get "Welcome to nginx! ... nginx configuration required. Please, could someone provide me some information how to setup the nginx with a default puphpet vm?

Thank you.
Best regards

**Comment by nicks451** [comment]
It sounds like you may have entered an incorrect document root for your site in the nginx configuration area. If you create a gist with your config.yaml file and link it here we can better help you solve the issue.

**Comment by jekelhart** [comment]
Here is my config.yaml:
https://gist.github.com/jekelhart/3b3ca37777a152028bf1

the default.conf in /etc/nginx/conf.d/ points to another root location. I thaught that puphpet will set the nginx configuration automatically?

**Comment by nicks451** [comment]
using the default document root isn't really a supported case with puphpet, you should be setting the values for the virtual host to work with your shared folder outside of the /var/www/html directory.

Just to give an example of how I setup my puphet configuration I setup my target folder to be in the /var/www directory but outside the html directory so I don't get any collision with the default virtual host
![puphet-shared-folders](https://cloud.githubusercontent.com/assets/459822/11086289/4a4a5e62-8804-11e5-91f5-4020fb084f19.png)

I then setup the virtual host document root to point to the public directory inside my target folder as this is where my index.php will live
![puphpet_-_nginx_-_virtual_host_setup](https://cloud.githubusercontent.com/assets/459822/11086288/4a482048-8804-11e5-8373-5dd88dc08c36.png)

if you have any other questions just let me know
