### ISSUE TITLE
hostname problem with existing boxes

### ISSUE THREAD

**Issue by steros** [puphpet/puphpet#1984]
After initial setup the hostname in the vagrant configuration is set to "hostname: local.puphpet" for me.
This raises the following error on Debian Wheezy with VirtualBox 5.0.10:

user@machine:~/vagrant/project$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'puphpet/debian75-x64'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'puphpet/debian75-x64' is up to date...
==> default: Setting the name of the VM: project_default_1447319633981_45655
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 22 => 7085 (adapter 1)
    default: 22 => 2222 (adapter 1)
==> default: Running 'pre-boot' VM customizations...
A customization command failed:

["modifyvm", :id, "--name", "local.puphpet"]

The following error was experienced:

#<Vagrant::Errors::VBoxManageError: There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["modifyvm", "a7d9b38d-2c2f-47f9-92d0-4710a6f0d5eb", "--name", "local.puphpet"]

Stderr: VBoxManage: error: Could not rename the directory '/VirtualBox VMs/project_default_1447319633981_45655' to '/VirtualBox VMs/local.puphpet' to save the settings file (VERR_ALREADY_EXISTS)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component SessionMachine, interface IMachine, callee nsISupports
VBoxManage: error: Context: "SaveSettings()" at line 3016 of file VBoxManageModifyVM.cpp
>

Please fix this customization and try again.

----------

Older configurations set the hostname just as an empty string like "hostname: ''". Trying this on the same box raises another error:

==> default: Error: /Stage[main]/Apache::Service/Service[httpd]: Failed to call refresh: Could not start Service[httpd]: Execution of '/etc/init.d/apache2 start' returned 1: 
==> default: Error: /Stage[main]/Apache::Service/Service[httpd]: Could not start Service[httpd]: Execution of '/etc/init.d/apache2 start' returned 1: 

Trying to start apache on the box manually reveals this:

$ sudo service apache2 start
[FAIL] Starting web server: apache2 failed!
[warn] The apache2 configtest failed. ... (warning).
Output of config test was:
AH00526: Syntax error on line 6 of /etc/apache2/apache2.conf:
The port number "#<Object:0x00000000fb0428>" is outside the appropriate range (i.e., 1..65535).
Action 'configtest' failed.
The Apache error log may have more information.

--------

What works is to set the hostname to the servername like "hostname: 'project.com'". But probably any string works? I suppose the problem is that the folder "local.puphpet" already exists due to a previous setup of another box. This problem didn't exist with the old setting of "hostname: ''".

**Comment by jtreminio** [comment]
You already have another VM with the same name - it must be unique across your host system.

This specific line explains it:

    Stderr: VBoxManage: error: Could not rename the directory '/VirtualBox VMs/project_default_1447319633981_45655' to '/VirtualBox VMs/local.puphpet' to save the settings file (VERR_ALREADY_EXISTS)

**Comment by steros** [comment]
Yes I thought so. But as said this wasn't the behavior previously.
I would suggest to name the vm like the servername, give it a random string or make the empty string work again so you don't hit this problem.
Otherwise the hostname field in the form should be more prominent and clearly state that you should change the name if you already have a vm like this.
