### ISSUE TITLE
Remember keys when uploading config file

### ISSUE THREAD

**Issue by Sazpaimon** [puphpet/puphpet#1985]
I have a PuPHPet setup where I have a config-custom.yaml that overrides some settings in config.yaml that aren't supported by the GUI (stuff like raw_prepend in Nginx vhosts). When I upload config.yaml to the GUI to get any fixes, the randomized keys are re-randomized, which requires that I update config-custom.yaml with the new keys. Ideally, if the GUI preserved the existing key names when uploading, I could simply unzip the archive on top of my existing data and not have to do anything else.

**Comment by jtreminio** [comment]
Implemented!
