### ISSUE TITLE
Unable to change default name

### ISSUE THREAD

**Issue by AntonioCS** [puphpet/puphpet#1988]
When I create a configuration, download and then run Vagrant up, the first thing I see is this:

> Bringing machine 'default' up with 'virtualbox' provider...

How do I change the 'default' to something else? I have done this in a normal vagrant config by doing:

>   config.vm.define "customname" do |customname|
>   end

I believe something like this should also be possible with puphpet

**Comment by jtreminio** [comment]
That's simply a Vagrant thing because you can have multiple servers configured in a single Vagrantfile.

The actual box name is lower:

```Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'puphpet/ubuntu1404-x64'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'puphpet/ubuntu1404-x64' is up to date...
==> default: Setting the name of the VM: 9Gwb9A_default_1448859278891_10614```

Then it gets changed again to whatever value you have for `vagrantfile.vm.hostname`
