### ISSUE TITLE
Cannot add headers via .htaccess for php files

### ISSUE THREAD

**Issue by brendan-roche** [puphpet/puphpet#1993]
PHP 5.6.15 (FPM/FastCGI)
Virtualbox 5.1.0
Vagrant 1.7.4
Librarian-Puppet v2.2.1
puppet 4.2.3
OSX 10.10.5

I'm using a Puphpet build on a vagrant box and I'm having some trouble adding basic headers via a .htaccess file for any php files. The headers are shown correctly when loading any html file though.

`Header set Content-Security-Policy " script-src 'self'"`

I have mod_headers enabled as an apache module. These response headers show up when accessing via a html file, but do not appear when loading any php file

I tried updating and re-installing to latest versions and no luck unfortunately...   

Any help would be much appreciated.

Thanks,
Brendan

**Comment by jtreminio** [comment]
PuPHPet uses PHP-FPM via fastcgi, which ignores all .htaccess files.

The proper way to do this is to set the values in the vhost config itself, using the proper custom directives field in the gui.
