### ISSUE TITLE
Support custom entries in /etc/hosts on the guest

### ISSUE THREAD

**Issue by pschulz** [puphpet/puphpet#1995]
The idea is, that not only the vhost aliases and hostnames become part of the /etc/hosts file on the guest, but also custom ones. 
vagrant-hostmanager doesn't help that much, as it only seem to provide support other host names, if they are defined in the same Vagrantfile as a so called multi-machine setup.

There seem to be some puppet modules available that support hiera and seem to do the job quite well. Unfortunately I cannot give you any advise, as I don't know any of these.

**Comment by jtreminio** [comment]
This seems like it's a specific-enough use case that it would make more sense to create a custom exec-once script to add it in.
