### ISSUE TITLE
Unable to connect to MySQL with Ubuntu Trusty 14.04 LTS x64

### ISSUE THREAD

**Issue by karstenk** [puphpet/puphpet#1997]
Revising this post from earlier.

With the puphpet/ubuntu1404-x64, I am not able to SSH tunnel to MySQL when using a client such as Sequel Pro or MySQL Workbench.

I am, however, able to connect multiple instances when using puphpet/debian75-x64.

The error I am receiving with Umbuntu is `SSH port forwarding failed, MySQL said: Lost connection to MySQL server at 'reading initial communication packet', system error: 0`

Specially, after the SSH connection is approved:

`debug1: Connection to port 63615 forwarding to 192.168.56.201 port 3306 requested.
debug1: channel 4: new [direct-tcpip]
channel 4: open failed: connect failed: Connection refused`

Seems there might be a `skip-networking` setting or alike on the Ubuntu box, however I am unable to locate.

Thanks. Puphpet is a great resource.

**Comment by junioressono** [comment]
Hello, I have the same problem with my box. Please can you help ?

this is my config.yml content and below i have posted a picture about this issue on my DB Client (HeidiSQL)

apache:
    install: '1'
    settings:
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - proxy_fcgi
        - rewrite
    vhosts:
        av_p4nrfyc4zc0u:
            custom_fragment: ''
            docroot: /var/www/chickdev.dev
            port: '80'
            serveraliases:
                - chickdev.dev
            servername: chickdev.dev
            setenv:
                - 'APP_ENV dev'
            ssl: '0'
            ssl_cert: ''
            ssl_certs_dir: ''
            ssl_chain: ''
            ssl_cipher: ''
            ssl_key: ''
            ssl_protocol: ''
beanstalkd:
    install: '0'
    settings:
        listenaddress: 0.0.0.0
        listenport: '11300'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: 0
blackfire:
    install: '0'
    settings:
        server_id: ''
        server_token: ''
        agent:
            http_proxy: ''
            https_proxy: ''
            log_file: stderr
            log_level: '1'
        php:
            agent_timeout: '0.25'
            log_file: ''
            log_level: '1'
cron:
    install: '1'
    jobs: {  }
drush:
    install: '1'
    version: 6.3.0
elastic_search:
    install: '1'
    settings:
        version: 1.4.1
        java_install: true
firewall:
    install: '1'
    rules: {  }
hhvm:
    install: '0'
    nightly: 0
    composer: '1'
    composer_home: ''
    settings: {  }
    server_ini:
        hhvm.log.file: /var/log/hhvm/error.log
        hhvm.log.use_log_file: '1'
        hhvm.server.host: 127.0.0.1
        hhvm.server.port: '9000'
    php_ini:
        date.timezone: UTC
        display_errors: 'On'
        error_reporting: '-1'
locale:
    install: '1'
    settings:
        default_locale: fr_FR.UTF-8
        locales:
            - en_GB.UTF-8
            - en_US.UTF-8
            - fr_FR.UTF-8
mailcatcher:
    install: '1'
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '1080'
        mailcatcher_path: /usr/local/rvm/wrappers/default
        from_email_method: inline
mariadb:
    install: '0'
    settings:
        version: '10.0'
        root_password: '123'
        override_options: {  }
    adminer: 0
    users:
        mariadbnu_llhhmdqnc0u3:
            name: dbuser
            password: '123'
    databases:
        mariadbnd_g463ay6xlmpw:
            name: dbname
            sql: ''
    grants:
        mariadbng_hhn8zgbxq6s7:
            privileges:
                - ALL
            table: '*.*'
            user: dbuser
mongodb:
    install: '1'
    settings:
        auth: 1
        bind_ip: 127.0.0.1
        port: '27017'
    databases: {  }
mysql:
    install: '1'
    settings:
        version: '5.6'
        root_password: root
        override_options: {  }
    adminer: 0
    users: {  }
    databases: {  }
    grants: {  }
nginx:
    install: '0'
    settings:
        default_vhost: 1
        proxy_buffer_size: 128k
        proxy_buffers: '4 256k'
    upstreams: {  }
    vhosts:
        nxv_sfltxs2w7ed8:
            client_max_body_size: 1m
            index_files:
                - index.html
                - index.htm
                - index.php
            listen_port: '80'
            locations:
                nxvl_b5kobytdt69e:
                    autoindex: 'off'
                    fastcgi: ''
                    fastcgi_index: ''
                    fastcgi_split_path: ''
                    internal: 'false'
                    location: /
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
                nxvl_we0uraf8egiv:
                    autoindex: 'off'
                    fast_cgi_params_extra:
                        - 'SCRIPT_FILENAME $request_filename'
                        - 'APP_ENV dev'
                    fastcgi: '127.0.0.1:9000'
                    fastcgi_index: index.php
                    fastcgi_split_path: '^(.+\.php)(/.*)$'
                    internal: 'false'
                    location: '~ \.php$'
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
            rewrite_to_https: '1'
            server_aliases:
                - www.awesome.dev
            server_name: awesome.dev
            spdy: '1'
            ssl: '0'
            ssl_cert: ''
            ssl_ciphers: ''
            ssl_key: ''
            ssl_port: '443'
            ssl_protocols: ''
            www_root: /var/www/awesome
    proxies: {  }
nodejs:
    install: '1'
    npm_packages:
        - express
php:
    install: '1'
    settings:
        version: '56'
    modules:
        php:
            - cli
            - intl
            - mcrypt
        pear: {  }
        pecl: {  }
    ini:
        date.timezone: UTC
        display_errors: 'On'
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
    fpm_ini:
        error_log: /var/log/php-fpm.log
    fpm_pools:
        phpfp_br0xl1kct3c0:
            ini:
                group: www-data
                listen: '127.0.0.1:9000'
                prefix: www
                security.limit_extensions: .php
                user: www-user
    composer: '1'
    composer_home: ''
postgresql:
    install: '0'
    settings:
        global:
            encoding: UTF8
            version: '9.3'
        server:
            postgres_password: '123'
    databases: {  }
    users: {  }
    grants: {  }
    adminer: 0
python:
    install: '1'
    packages: {  }
    versions: {  }
rabbitmq:
    install: '0'
    settings:
        port: '5672'
    users: {  }
    vhosts: {  }
    plugins: {  }
redis:
    install: '0'
    settings:
        conf_port: '6379'
ruby:
    install: '1'
    versions: {  }
server:
    install: '1'
    packages:
        - vim
        - vim-common
solr:
    install: '0'
    settings:
        version: 4.10.2
        port: '8984'
sqlite:
    install: '0'
    adminer: 0
    databases: {  }
users_groups:
    install: '1'
    groups: {  }
    users: {  }
vagrantfile:
    target: local
    vm:
        box: puphpet/ubuntu1404-x64
        box_url: puphpet/ubuntu1404-x64
        hostname: chickdev.dev
        memory: '512'
        cpus: '1'
        chosen_provider: virtualbox
        network:
            private_network: 192.168.56.101
            forwarded_port: {  }
        post_up_message: ''
        provider:
            virtualbox:
                modifyvm:
                    natdnshostresolver1: 'on'
                showgui: '0'
            vmware:
                numvcpus: 1
            parallels:
                cpus: 1
        provision:
            puppet:
                manifests_path: puphpet/puppet
                manifest_file: site.pp
                module_path: puphpet/puppet/modules
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
                    - '--parser future'
        synced_folder:
            vflsf_bzhw5g2tgodt:
                group: www-data
                owner: www-data
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    auto: 'true'
                    exclude:
                        - .vagrant/
                        - .git/
                smb:
                    smb_host: ''
                    smb_password: ''
                    smb_username: ''
                source: 'D:\CHICKDEV\PROJECTs\WEBSITES\sites'
                sync_type: default
                target: /var/www/chickdev.dev
        usable_port_range:
            start: 10200
            stop: 10500
    ssh:
        host: null
        port: null
        private_key_path: null
        username: vagrant
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'
    vagrant:
        host: detect
wpcli:
    install: '1'
    version: v0.19.0
xdebug:
    install: '1'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
xhprof:
    install: '0'



![capture](https://cloud.githubusercontent.com/assets/4427335/11447841/9890b610-954d-11e5-9fd7-81ae8eb14430.PNG)

**Comment by jtreminio** [comment]
Can you try with MySQL 5.5? 5.6 seems to be a bad release that's not working.

**Comment by jtreminio** [comment]
Please regenerate your archive and choose either mysql 5.5 or mariadb.
