### ISSUE TITLE
Support for Debian 8/Jessie as deploy target

### ISSUE THREAD

**Issue by marijnotte** [puphpet/puphpet#2000]
Debian 8 was released in April. Support to use it as deploy target would be great.

**Comment by jtreminio** [comment]
At this point I'm learning *very* heavily towards the camp of "If you want up to date, use Ubuntu".

There's simply so many changes from Deb7 -> Deb8, and CentOS6 -> CentOS7 that I do not have the time to maintain all these flavors.
