### ISSUE TITLE
Vagrant Share Virtual Hosts

### ISSUE THREAD

**Issue by jeeftor** [puphpet/puphpet#2005]
When i share my host with `vagrant share` I'm hitting the 

> Congratulations! You are pretty awesome.
> You are well on your way to a highly customized server.
> However, if you are seeing this page, it means you are using IP Address, not virtual host!

What is the best workaround for this issue?

Can I add `*.vagrantshare.com` to the alias for my virtual host? - it doesn't seem too happy about the "non alphanumeric" characters in the config file.

Or is there a better way of handling this?

**Comment by alibad** [comment]
I am hitting the same issue. Still exploring how to resolve. Would be nice if someone has already figured it out.

**Comment by alibad** [comment]
Found solution here: http://stackoverflow.com/questions/23752968/vagrant-share-accessing-virtual-hosts-and-accessing-those-that-are-not-in-the

Do a vagrant share with a specific name. 

Example: vagrant share --name ali-test

In your config.yaml file, search for server_aliases and serveraliases, and add ali-test.vagrantshare.com.

If your host name is awesome,.dev, it should look like this:

            server_name: awesome.dev
            server_aliases:
                - www.awesome.dev
                - ali-test.vagrantshare.com
            www_root: /var/www/awesome

            servername: awesome.dev
            serveraliases:
                - www.awesome.dev
                - ali-test.vagrantshare.com

In a new terminal window, run vagrant provision. Go back to the page.

If the share session expires, make sure you share again with the same name.

vagrant share --name ali-test
