### ISSUE TITLE
On vagrant up, error loading puppet facts - sqlite db.pp

### ISSUE THREAD

**Issue by mkdeddens** [puphpet/puphpet#2015]
When provisioning on a configuration that has sqlite activated but has no databases I get the following error:
`==> dev: Error: The parameter $name redefines a built in parameter in the 'define' expression at /tmp/vagrant-puppet/modules-b3627e7400bea6d73e6fbb252ecc5888/puphpet/manifests/sqlite/db.pp:4:3 on node <node_name>`

Seems this file `puphpet/puppet/modules/puphpet/manifests/sqlite/db.pp` has a variable `$name` defined. When renaming this to e.g. `$name2` throughout the file, provisioning works like a charm!

Configuration:
* Windows 10 / OpenSuse 13.2
* Virtualbox 5
* Vagrant 1.7.4
* Box: https://atlas.hashicorp.com/puphpet/boxes/ubuntu1404-x64/versions/20151201
* config.yaml sqlite section:
```
sqlite:
    install: '1'
    adminer: 0
    databases: {  }
```
Note: I know no official support for Windows 10, same thing happens on my OpenSuse 13.2 set-up.
Note2: Same thing happens in a similar config when deploying to AWS, so also not related to the box or version thereof.

**Comment by jtreminio** [comment]
Fixed in #2026
