### ISSUE TITLE
Error: Evaluation Error: Error while evaluating a Resource Statement, Duplicate declaration: Package[git] is already declared

### ISSUE THREAD

**Issue by steros** [puphpet/puphpet#2018]
I get the following error after updating "puphpet/debian75-x64" and trying a fresh puphpet installation:

>Error: Evaluation Error: Error while evaluating a Resource Statement, Duplicate declaration: Package[git] is already declared in file /tmp/vagrant-puppet/modules-35d40662c889b3915dc85a28fed9128c/puphpet/manifests/supervisord.pp:9; cannot redeclare at /tmp/vagrant-puppet/modules-35d40662c889b3915dc85a28fed9128c/git/manifests/init.pp:12 at /tmp/vagrant-puppet/modules-35d40662c889b3915dc85a28fed9128c/git/manifests/init.pp:12:3 on node foo

I changed `/puphpet/puppet/modules/git/manifests/init.pp` from
```
class git ($package_name = 'git') {
  package { $package_name:
    ensure => installed,
  }
}
```
to (just copied from supervisord.pp)
```
class git ($package_name = 'git') {
  if ! defined(Package['git']) {
    package { 'git':
      ensure  => present,
    }
  }
}
```
to get it working again. But is this really a solution or is the actual error in the installation order or something similar?

**Comment by webdepp** [comment]
Same error here.

**Comment by simonihmig** [comment]
Same here...

**Comment by Zae** [comment]
I fixed this by removing the git part from the supervisord.pp file, but I think this is a better permanent solution: #2025

**Comment by jtreminio** [comment]
Fixed. Librarian was pulling in the wrong git repo.

**Comment by jtreminio** [comment]
Please run

    rm -rf puphpet/puppet/modules/git
    git clone https://github.com/puphpet/puppetlabs-git.git puphpet/puppet/modules/git
    rm -rf puphpet/puppet/modules/git/.git*```
