### ISSUE TITLE
Error: Could not find resource 'Mysql::Db[]'

### ISSUE THREAD

**Issue by theproducer** [puphpet/puphpet#202]
Getting the following error when provisioning a vm:

Error: Could not find resource 'Mysql::Db[]' for relationship from 'Class[Mysql::Server::Root_password]' on node ubuntu-server-12042-x64-vbox4210
Error: Could not find resource 'Mysql::Db[]' for relationship from 'Class[Mysql::Server::Root_password]' on node ubuntu-server-12042-x64-vbox4210

Using Ubuntu Precise 12.04 x64 with all other options set as default from puphpet.com.  I've also tried adding a MySQL password of "root", with the same outcome.

Using Vagrant 1.3.4, Virtual Box 4.2.18, on OS X 10.8

Thanks!

**Comment by janzenz** [comment]
This happened to me as well. The UI didn't stop me from proceeding.
