### ISSUE TITLE
SSH issue - Windows

### ISSUE THREAD

**Issue by iomdesign** [puphpet/puphpet#2022]
How do.

Vagrant has stopped creating the SSH key pair on vagrant up on Windows after the first connection timeout. Not sure if this is an issue with [vagrant / virtualbox 5.0.10] or [puphpet / puppet] side. 

This is the cli output:

```
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:10200
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Connection timeout. Retrying...
==> default: Machine booted and ready!
```

As you can see, where previously provisioning a VM would trigger creation of a vagrant ssh key now it does not, thus no key pair in \puphpet\files\dot\ssh

this seems to be causing winnfsd an issue as it then just hangs. If I switch to default share puppet does generate a key pair for root and for vagrant later on when it finds no other keys.

As I say, struggling to debug for the cause and not certain if this is an issue for here or vagrant. If there is anything I can do assist resolving please let me know.

Cheers

**Comment by conradfr** [comment]
It seems I have the same problem, except it just loops at

default: Warning: Connection timeout. Retrying...

I just uninstalled / destroyed /updated everything and it's a config generated today.

**Comment by iomdesign** [comment]
FYI I noticed the change to the config files including insert_key: false - Simply changing this to true obviously lets puppet generate keys later on in the process however it still (would appear) to be preventing winnfsd from sharing files because at that point there is still no SSH keys for vagrant.
