### ISSUE TITLE
Error: The parameter $name redefines a built in parameter in the 'define' expression 

### ISSUE THREAD

**Issue by Zae** [puphpet/puphpet#2026]
at at /tmp/vagrant-puppet/modules-f60a01d874be3c1ce3b2b9ce0a1e62f2/puphpet/manifests/sqlite/db.pp:4:3 on node

I fixed this by replacing the $name reference with $param_name in the file.

**Comment by jtreminio** [comment]
good catch.

**Comment by raulianosiga** [comment]
cheers for this
