### ISSUE TITLE
Elastic Search won't install properly

### ISSUE THREAD

**Issue by vincenzo** [puphpet/puphpet#2040]
Hi. 

This is [my config](http://pastebin.com/JDzihCZf).
This is the [output of the provisioning](http://pastebin.com/HJJDHgQ4).

Elastic Search 1.4.5 is specified in the config. I can see in the output that it's being installed (whether completely or not, I do not know), but then it doesn't start as a service. The obvious thing I can see is that the init script is not there (`/etc/init.d/elasticsearch`). I can see this in the output in relation to that: 

```
==> default: Info: Computing checksum on file /etc/init.d/elasticsearch
==> default: Info: /Stage[main]/Elasticsearch::Config/File[/etc/init.d/elasticsearch]: Filebucketed /etc/init.d/elasticsearch to puppet with sum 54e8fb3292039ca25fb0b1aa14b89a81
==> default: Notice: /Stage[main]/Elasticsearch::Config/File[/etc/init.d/elasticsearch]/ensure: removed
```

It looks like it had been installed and then removed?

**Comment by vincenzo** [comment]
Ok. I have further details. 
I managed to start ES without the init script (sorry, it took a while, I am used to it just working out of the box). All my sites are working fine once it starts, so I can confirm the only thing missing is the init script (and quite possibly its symlinking at the right `rc` level). The output in the PR's description suggests that the script is first copied, then deleted. This seems to be confirmed by the fact that there are `.erb` files related to the init script in my generated archive: 

```
/vagrant/puphpet/puppet/modules/elasticsearch/templates/etc/init.d/elasticsearch.Debian.erb
/vagrant/puphpet/puppet/modules/elasticsearch/templates/etc/init.d/elasticsearch.RedHat.erb
/vagrant/puphpet/puppet/modules/elasticsearch/templates/etc/init.d/elasticsearch.systemd.erb
```

**Comment by vincenzo** [comment]
Ah, the other detail is that I've tried these versions of ES: 1.3.9, 1.4.5, 2.1.0 and for all of them I don't get the init script...

**Comment by vincenzo** [comment]
For the time being, I managed to work around this by running this: 

```sh
$ puppet filebucket --bucket /opt/puppetlabs/puppet/cache/clientbucket -l restore /etc/init.d/elasticsearch 54e8fb3292039ca25fb0b1aa14b89a81
```

The long checksum at the end of the command is the same as reported in the output during the provisioning.

**Comment by vincenzo** [comment]
Further to all this, I am now noticing quite a few "Filebucket" in my output, regarding Redis config, Nginx config, and other ES files... is this normal?

**Comment by vincenzo** [comment]
Since I kinda needed this fixed, this is my workaround at the moment: 

```bash
#!/usr/bin/env bash

PUPPET_BUCKET_LOCATION="/opt/puppetlabs/puppet/cache/clientbucket/"

find ${PUPPET_BUCKET_LOCATION} -iname "paths" |

while read FILEPATH; do
  FILE=$(cat ${FILEPATH})
  CHECKSUM=$(basename $(dirname ${FILEPATH}))
  puppet filebucket --bucket ${PUPPET_BUCKET_LOCATION} -l restore ${FILE} ${CHECKSUM}
done

chmod 755 /etc/init.d/elasticsearch
update-rc.d elasticsearch defaults 2
service elasticsearch start
```

I am running this as an `exec-once` script, to restore all "filebucketed" files, register elasticsearch as a service, and starting it up.

Hopefully, this will be recognised as an issue and fixed, @jtreminio?

**Comment by dameert** [comment]
Thanks for your workaround, I was having the same issue.
Works for me now!

**Comment by dameert** [comment]
Be aware that your workaround also restores apache config files. In my case they get overwritten by the puppet script so they become invalid again.

I modified your script to only have an impact on elastic search:

```bash
#!/usr/bin/env bash

echo "Repair elasticsearch"

PUPPET_BUCKET_LOCATION="/opt/puppetlabs/puppet/cache/clientbucket/"

find ${PUPPET_BUCKET_LOCATION} -iname "paths" |

while read FILEPATH; do
  FILE=$(cat ${FILEPATH})
  CHECKSUM=$(basename $(dirname ${FILEPATH}))
  if [[ ${FILE} == *elastic* ]]; then
  	sudo puppet filebucket --bucket ${PUPPET_BUCKET_LOCATION} -l restore ${FILE} ${CHECKSUM}
  	echo "Recovered file: ".${FILE}
  fi
done

chmod 755 /etc/init.d/elasticsearch
update-rc.d elasticsearch defaults 2
service elasticsearch start

echo "Finished repairing elastic search"
```

**Comment by vincenzo** [comment]
@dameert That was actually intentional. It could be that I didn't have any issues because I am using nginx instead? Anyway, if you look at my comments before I wrote that script, you'll see this: 

```
$ puppet filebucket --bucket /opt/puppetlabs/puppet/cache/clientbucket -l restore /etc/init.d/elasticsearch 54e8fb3292039ca25fb0b1aa14b89a81
```

I found that restoring that file alone was sufficient for ES. Of course, you still need this after it:

```
chmod 755 /etc/init.d/elasticsearch
update-rc.d elasticsearch defaults 2
service elasticsearch start
```

Anyway, I am sure you are happy with what you've got.

**Comment by vincenzo** [comment]
@jtreminio Have you had any thoughts about this one?

**Comment by vincenzo** [comment]
@jtreminio This hasn't fixed the issue for me. After the provisioning elastic is still not registered as a service, `/etc/elasticsearch/` is empty, and the init.d script isn't there either.

**Comment by vincenzo** [comment]
Hold on, just noticing that "instances" thing that wasn't there before?

**Comment by vincenzo** [comment]
Ok, it was my fault. Instances. Got it. Thanks.
