### ISSUE TITLE
/puphpet/ruby/puppet.rb:195:in `run_puppet_apply': undefined method `color?' for #<Vagrant::UI::Colored:0x00000001aede30> (NoMethodError)

### ISSUE THREAD

**Issue by parotikov** [puphpet/puphpet#2043]
i download generated archive, unzip it, make vagrant up, and after few time terminal says:
http://pastebin.com/zStCNsB2

my config.yaml
http://pastebin.com/Z1489i6L

**Comment by noahkoch** [comment]
Having the same issue

**Comment by iocron** [comment]
Having the same problem here. My Output: http://pastebin.com/Sjzk8PRN

**Comment by iocron** [comment]
After removing the lines 195-197 i do get a new error: 
.../puphpet/ruby/puppet.rb:226:in `join': can't convert Vagrant::Config::V2::DummyConfig to String (Vagrant::Config::V2::DummyConfig#to_str gives Vagrant::Config::V2::DummyConfig) (TypeError)

**Comment by andygagnon** [comment]
Same problem here.  Solution?

**Comment by andygagnon** [comment]
Tried both Debian Wheezy 7, and Ubuntu 14.04 as the distro.  Same ruby problem on either.

**Comment by andygagnon** [comment]
This is a FATAL error, stopping all new project development using vagrant.  Please fix.  Thanks for your time.

**Comment by vegardlarsen** [comment]
+1 Exact same error as above.

**Comment by jtreminio** [comment]
Interesting! This is from the Vagrant core. I'll take a look.

**Comment by jtreminio** [comment]
Are you all on the latest Vagrant version, 1.7.4?

**Comment by andygagnon** [comment]
1.7.2 here.   How does one update vagrant on Mac OSX.  Download?

**Comment by vegardlarsen** [comment]
I finally got this to work (on another machine), so these steps may be helpful to everyone else. I upgraded:

- Upgrading VirtualBox (to 5.0.11, found [here](https://www.virtualbox.org/wiki/Testbuilds)). Remember to reboot between uninstall and install.
- Upgrade the Vagrant box, `vagrant box update`
- Fixing [this issue](http://stackoverflow.com/questions/33725779/failed-to-open-create-the-internal-network-vagrant-on-windows10)
- Upgrade to Vagrant 1.7.4

**Comment by jtreminio** [comment]
@andygagnon https://www.vagrantup.com/downloads.html

**Comment by seisler** [comment]
Upgrading Vagrant and VBox to latest version will solve the issue.

**Comment by andygagnon** [comment]
Does anyone know if upgrading Vagrant, VBox break previous puphpet vagrant installs from weeks, months ago?  Can't stop development on older projects just to get new vagrant installs working.

**Comment by rcatlin** [comment]
Upgrading to Vagrant 1.7.4 resolved the issue for me. Thanks!
