### ISSUE TITLE
PHP 7 memcached

### ISSUE THREAD

**Issue by bensinclair** [puphpet/puphpet#2047]
When I try to install PHP 7 with the memcached extension I am getting the following error:

    ==> default: Error: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold 
        install php7.0-memcached' returned 100: Reading package lists...
    ==> default: Building dependency tree...
    ==> default: Reading state information...
    ==> default: E: Unable to locate package php7.0-memcached
    ==> default: E: Couldn't find any package by regex 'php7.0-memcached'
    ==> default: Error: /Stage[main]/Puphpet_php/Puphpet::Php::Module[memcached]/Php::
        Module[memcached]/Package[PhpModule_memcached]/ensure: change from purged
        to present failed: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold
        install php7.0-memcached' returned 100: Reading package lists...
    ==> default: Building dependency tree...
    ==> default: Reading state information...
    ==> default: E: Unable to locate package php7.0-memcached
    ==> default: E: Couldn't find any package by regex 'php7.0-memcached'

It appears to be looking for for a package called 'php7.0-memcached'. Excuse my ignorance (I do not know anything about installing PHP packages) but can it just look for the `php-memcached` package? I ran it manually and it seems to have found it just fine. Maybe they are consolidating the extension so you do not need to put the version in the package?

I am also getting the same issue with the `xsl` package.

Here's my config.yam if that helps. It errors both when I put the `memcached` package under 'php' and 'pecl'.

	vagrantfile:
	    target: local
	    vm:
	        box: puphpet/ubuntu1404-x64
	        box_url: puphpet/ubuntu1404-x64
	        hostname: .dev
	        memory: '1024'
	        cpus: '1'
	        chosen_provider: vmware_fusion
	        network:
	            private_network: 10.0.11.11
	            public_network:
	                en1: 'bridge'
	            forwarded_port:
	                vflnp_5qzms0k1b5fl:
	                    host: '2020'
	                    guest: '22'
	                vflnp_bj90w9qdp6cx:
	                    host: '8080'
	                    guest: '80'
	                vflnp_updkaa4xhcse:
	                    host: '33306'
	                    guest: '3306'
	        post_up_message: ''
	        provider:
	            virtualbox:
	                modifyvm:
	                    natdnshostresolver1: 'on'
	                showgui: '0'
	            vmware:
	                numvcpus: 1
	            parallels:
	                cpus: 1
	        provision:
	            puppet:
	                manifests_path: puphpet/puppet/manifests
	                module_path: puphpet/puppet/modules
	                options:
	                    - '--verbose'
	                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
	        synced_folder:
	            admin:
	                source: ./admin
	                target: /var/www/html
	                sync_type: default
	                smb:
	                    smb_host: ''
	                    smb_username: ''
	                    smb_password: ''
	                rsync:
	                    args:
	                        - '--verbose'
	                        - '--archive'
	                        - '-z'
	                    exclude:
	                        - .vagrant/
	                        - .git/
	                    auto: 'true'
	                owner: www-data
	                group: www-data
	        usable_port_range:
	            start: 10200
	            stop: 10500
	    ssh:
	        host: null
	        port: null
	        private_key_path: null
	        username: vagrant
	        guest_port: null
	        keep_alive: true
	        forward_agent: false
	        forward_x11: false
	        shell: 'bash -l'
	        insert_key: false
	    vagrant:
	        host: detect
	server:
	    install: '1'
	    packages: {  }
	users_groups:
	    install: '1'
	    groups: {  }
	    users: {  }
	locale:
	    install: '1'
	    settings:
	        default_locale: en_US.UTF-8
	        locales:
	            - en_GB.UTF-8
	            - en_US.UTF-8
	firewall:
	    install: '0'
	    rules: {  }
	cron:
	    install: '0'
	    jobs:
	        cj_ue8zywzrcrmd:
	            name: ''
	            user: ''
	            command: ''
	            minute: ''
	            hour: ''
	            weekday: ''
	            month: ''
	            monthday: ''
	nginx:
	    install: '0'
	    settings:
	        default_vhost: 1
	        proxy_buffer_size: 128k
	        proxy_buffers: '4 256k'
	        proxy_connect_timeout: 600s
	        proxy_send_timeout: 600s
	        proxy_read_timeout: 600s
	        names_hash_bucket_size: 128
	    upstreams: {  }
	    vhosts:
	        nxv_99t7feh4p6e9:
	            server_name: awesome.dev
	            server_aliases:
	                - www.awesome.dev
	            www_root: /var/www/awesome
	            listen_port: '80'
	            index_files:
	                - index.html
	                - index.htm
	                - index.php
	            client_max_body_size: 1m
	            ssl: '0'
	            ssl_cert: ''
	            ssl_key: ''
	            ssl_port: '443'
	            ssl_protocols: ''
	            ssl_ciphers: ''
	            rewrite_to_https: '1'
	            spdy: '1'
	            locations:
	                nxvl_e9kd9oykboi3:
	                    location: /
	                    autoindex: 'off'
	                    internal: 'false'
	                    try_files:
	                        - $uri
	                        - $uri/
	                        - /index.php$is_args$args
	                    fastcgi: ''
	                    fastcgi_index: ''
	                    fastcgi_split_path: ''
	                    proxy: ''
	                    proxy_redirect: ''
	                nxvl_m307kqt9z7lb:
	                    location: '~ \.php$'
	                    autoindex: 'off'
	                    internal: 'false'
	                    try_files:
	                        - $uri
	                        - $uri/
	                        - /index.php$is_args$args
	                    fastcgi: '127.0.0.1:9000'
	                    fastcgi_index: index.php
	                    fastcgi_split_path: '^(.+\.php)(/.*)$'
	                    fast_cgi_params_extra:
	                        - 'SCRIPT_FILENAME $request_filename'
	                        - 'APP_ENV dev'
	                    set:
	                        - '$path_info $fastcgi_path_info'
	                    proxy: ''
	                    proxy_redirect: ''
	    proxies: {  }
	apache:
	    install: '1'
	    settings:
	        user: www-data
	        group: www-data
	        default_vhost: true
	        manage_user: false
	        manage_group: false
	        sendfile: 0
	    modules:
	        - proxy_fcgi
	        - rewrite
	    vhosts:
	        admin_80:
	            servername: admin.dev
	            serveraliases:
	                - www.admin.dev
	            docroot: /var/www/html
	            port: '80'
	            setenv:
	                - 'APP_ENV dev'
	            setenvif:
	                - 'Authorization "(.*)" HTTP_AUTHORIZATION=$1'
	            custom_fragment: ''
	            ssl: '0'
	            ssl_cert: ''
	            ssl_key: ''
	            ssl_chain: ''
	            ssl_certs_dir: ''
	            ssl_protocol: ''
	            ssl_cipher: ''
	            directories:
	                avd_cdkxb66zxwb6:
	                    path: /var/www/html
	                    options:
	                        - Indexes
	                        - FollowSymlinks
	                    allow_override:
	                        - All
	                    require:
	                        - 'all granted'
	                    custom_fragment: ''
	                    files_match:
	                        avdfm_y9cby98th3cq:
	                            path: \.php$
	                            sethandler: 'proxy:fcgi://127.0.0.1:9000'
	                            custom_fragment: ''
	                            provider: filesmatch
	                    provider: directory
	        admin_443:
	            servername: admin.dev
	            serveraliases:
	                - www.admin.dev
	            docroot: /var/www/html
	            port: '443'
	            setenv:
	                - 'APP_ENV dev'
	            setenvif:
	                - 'Authorization "(.*)" HTTP_AUTHORIZATION=$1'
	            custom_fragment: ''
	            ssl: '1'
	            ssl_cert: ''
	            ssl_key: ''
	            ssl_chain: ''
	            ssl_certs_dir: ''
	            ssl_protocol: ''
	            ssl_cipher: ''
	            directories:
	                avd_cdkxb66zxwb6:
	                    path: /var/www/html
	                    options:
	                        - Indexes
	                        - FollowSymlinks
	                    allow_override:
	                        - All
	                    require:
	                        - 'all granted'
	                    custom_fragment: ''
	                    files_match:
	                        avdfm_y9cby98th3cq:
	                            path: \.php$
	                            sethandler: 'proxy:fcgi://127.0.0.1:9000'
	                            custom_fragment: ''
	                            provider: filesmatch
	                    provider: directory
	php:
	    install: '1'
	    settings:
	        version: '70'
	    modules:
	        php:
	            - cli
	            - intl
	            - mcrypt
	            - mysql
	            - curl
	            - gd
	            - memcached
	            - xsl
	        pear: {  }
	        pecl: {  }
	    ini:
	        display_errors: 'On'
	        error_reporting: '-1'
	        session.save_path: /var/lib/php/session
	        date.timezone: UTC
	    fpm_ini:
	        error_log: /var/log/php-fpm.log
	    fpm_pools:
	        phpfp_079ylu9409ji:
	            ini:
	                prefix: www
	                listen: '127.0.0.1:9000'
	                security.limit_extensions: .php
	                user: www-user
	                group: www-data
	    composer: '1'
	    composer_home: ''
	xdebug:
	    install: '1'
	    settings:
	        xdebug.default_enable: '1'
	        xdebug.remote_autostart: '0'
	        xdebug.remote_connect_back: '1'
	        xdebug.remote_enable: '1'
	        xdebug.remote_handler: dbgp
	        xdebug.remote_port: '9000'
	blackfire:
	    install: '0'
	    settings:
	        server_id: ''
	        server_token: ''
	        agent:
	            http_proxy: ''
	            https_proxy: ''
	            log_file: stderr
	            log_level: '1'
	        php:
	            agent_timeout: '0.25'
	            log_file: ''
	            log_level: '1'
	xhprof:
	    install: '0'
	wpcli:
	    install: '0'
	    version: v0.19.0
	drush:
	    install: '0'
	    version: 6.3.0
	ruby:
	    install: '1'
	    versions: {  }
	python:
	    install: '1'
	    packages: {  }
	    versions: {  }
	nodejs:
	    install: '0'
	    npm_packages: {  }
	hhvm:
	    install: '0'
	    nightly: 0
	    composer: '1'
	    composer_home: ''
	    settings: {  }
	    server_ini:
	        hhvm.server.host: 127.0.0.1
	        hhvm.server.port: '9000'
	        hhvm.log.use_log_file: '1'
	        hhvm.log.file: /var/log/hhvm/error.log
	    php_ini:
	        display_errors: 'On'
	        error_reporting: '-1'
	        date.timezone: UTC
	mariadb:
	    install: '0'
	    settings:
	        version: '10.1'
	        root_password: '123'
	        override_options: {  }
	    adminer: 0
	    users:
	        mariadbnu_59tdgwa60fke:
	            name: dbuser
	            password: '123'
	    databases:
	        mariadbnd_6xwvw6m83hij:
	            name: dbname
	            sql: ''
	    grants:
	        mariadbng_pzqckvdx7e7a:
	            user: dbuser
	            table: '*.*'
	            privileges:
	                - ALL
	mysql:
	    install: '1'
	    settings:
	        version: '5.5'
	        root_password: 'root'
	        override_options: {  }
	    adminer: 0
	    users:
	        mysqlnu_i0ugf2gsi60x:
	            name: dbuser
	            password: '123'
	    databases:
	        admin:
	            name: admin
	            sql: ''
	    grants:
	        mysqlng_i7nb7nq6p35f:
	            user: dbuser
	            table: '*.*'
	            privileges:
	                - ALL
	postgresql:
	    install: '0'
	    settings:
	        global:
	            encoding: UTF8
	            version: '9.4'
	        server:
	            postgres_password: '123'
	    databases: {  }
	    users: {  }
	    grants: {  }
	    adminer: 0
	mongodb:
	    install: '0'
	    settings:
	        auth: 1
	        bind_ip: 127.0.0.1
	        port: '27017'
	    globals:
	        version: 2.6.0
	    databases: {  }
	redis:
	    install: '0'
	    settings:
	        conf_port: '6379'
	sqlite:
	    install: '0'
	    adminer: 0
	    databases: {  }
	mailhog:
	    install: '0'
	    settings:
	        smtp_ip: 0.0.0.0
	        smtp_port: 1025
	        http_ip: 0.0.0.0
	        http_port: '8025'
	        path: /usr/local/bin/mailhog
	beanstalkd:
	    install: '0'
	    settings:
	        listenaddress: 0.0.0.0
	        listenport: '11300'
	        maxjobsize: '65535'
	        maxconnections: '1024'
	        binlogdir: /var/lib/beanstalkd/binlog
	        binlogfsync: null
	        binlogsize: '10485760'
	    beanstalk_console: 0
	rabbitmq:
	    install: '0'
	    settings:
	        port: '5672'
	    users: {  }
	    vhosts: {  }
	    plugins: {  }
	elastic_search:
	    install: '0'
	    settings:
	        version: 2.1.0
	        java_install: true
	solr:
	    install: '0'
	    settings:
	        version: 4.10.2
	        port: '8984'

**Comment by wilwade** [comment]
Note: https://launchpad.net/~ondrej/+archive/ubuntu/php-7.0 is the source of the PHP7 packages and he named it "php-memcached" instead of "php7.0-memcached".

You can manually install that or add it to your server packages and it will work for now.

**Comment by bensinclair** [comment]
Thanks @wilwade for confirming. I'll just run it in `exec-once` for now.

**Comment by oerdnj** [comment]
JFTR all phpX.Y-<ext> extensions have their php-<ext> counterparts built from src:php-defaults that depend on latest phpX.Y-<ext> version. Theoretically you should be able to use php-<anything> metapackages just to get the latest supported PHP version.
