### ISSUE TITLE
Can't run a second provision

### ISSUE THREAD

**Issue by dblencowe** [puphpet/puphpet#2049]
Once I have run my first successful provision I am unable to run a second as it always exits with this error:

```==> default: Error: Could not autoload puppet/parser/functions/array_true: cannot load such file -- active_support/core_ext/string
==> default: Error: Evaluation Error: Error while evaluating a Function Call, Could not autoload puppet/parser/functions/array_true: cannot load such file -- active_support/core_ext/string at /tmp/vagrant-puppet/manifests-75f35e3bc7e32744860c4bb229c88812/site.pp:40:4 on node local.puphpet```

**Comment by jtreminio** [comment]
When did you download the archive?

**Comment by dblencowe** [comment]
Earlier today

**Comment by realshadow** [comment]
I have the same issue. Archive downloaded 3 days ago.

However this happens only on the initial `vagrant up`, subsequent runs with `vagrant provision` and `vagrant reload --provision` run just fine.

I am trying to run a second provision after the initial puphpet one.

Any idea what is going on?
