### ISSUE TITLE
Allow remote MySQL Connections

### ISSUE THREAD

**Issue by phirschybar** [puphpet/puphpet#205]
This would be a great option. Right now I am simulating this by just adding exec mysql commands to my puppet manifest to set user privileges. But I don't know how this can be acheived another way via puppet. Any ideas?

**Comment by peterjohnjoseph** [comment]
Hey everyone, I figured it out via this link, so I thought I would share- https://slewsystems.wordpress.com/2014/01/01/connecting-to-a-puphpet-vagrant-ftp-and-mysql-servers/

The problem is that the SSH Host has to the be the IP of the VM you set up, with User being Vagrant. 

So for SequelPro I used-

Name:localhost
MySQL Host : 127.0.0.1
Username: (check your config.yaml)
Password: (check your config.yaml)
Database: (Optional, but if you set one up, throw the name in if you want to connect directly to it)
Port: 3306

SSH Host: (The IP on your VM)
SSH User: Vagrant
SSH Key: path to your id_rsa file
SSH Port: I left this blank

The details should be the same for MySQLWorkbench and others as described in that link.

**Comment by sendalot** [comment]
has anyone figured out how to achieve this remote access via puppet?

**Comment by jtreminio** [comment]
@sendalot read the rest of the ticket, particularly @peterjohnjoseph's response.

**Comment by sendalot** [comment]
So when I changed "my.cnf" as deizel recommended, workbench/remote access worked.
Just trying to see how to achieve that in automation. Peterjohnjoseph's didn't have sample pp in his website. Or am I missing something?

**Comment by deizel** [comment]
@sendalot FWIW, I ended up switching to SSH keys in the end, so that would be my recommendation.

If you still wish to automated this, this should do the trick (though there may be some missing steps):

```sh
#!/bin/bash

cat <<AUGEAS | augtool -s
set /files/etc/mysql/my.cnf/target[ . = 'mysqld']/bind-address *
rm /files/etc/mysql/my.cnf/target[ . = 'mysqld']/skip-external-locking
set /files/etc/mysql/my.cnf/target[ . = 'mysqld']/skip-grant-tables ""
AUGEAS

service mysql restart
```

Save as `/puphpet/files/exec-always/00-mysql-allow-remote-connections.sh` and run `vagrant provision`.

**Comment by sendalot** [comment]
Thank you for your time. Anyway to do this in puppet? within mysql module?

**Comment by deizel** [comment]
@sendalot To be honest, I prefer not to edit the files generated by PuPHPet directly so they can be easily replaced with newly generated ones at a later date. Are you using PuPHPet at all, or just Puppet manifests directly?

Anyway, the above script used Augeas to modify the configuration file. Some examples of using this from a manifest are here: http://projects.puppetlabs.com/projects/1/wiki/puppet_augeas#Working+Examples

For example, something like this should have the same results as the above script:

```puppet
augeas { "mysql allow remote connections":
  context => "/files/etc/mysql/my.cnf/target[ . = 'mysqld']",
  changes => [
    "set bind-address *",
    "rm skip-external-locking",
    "set skip-grant-tables ''",
  ],
  notify => Service["mysql"],
}
```

Alternatively, there are two approaches using the official Puppet Labs MySQL module:

1. Provide [`override_options`][1], such as:

    ```puppet
    $override_options = {
      'mysqld' => {
        'bind-address' => '*',
        'skip-external-locking' => undef,
        'skip-grant-tables' => '',
      }
    }
    ```

    If you're modifying the files directly, the earliest I can see that you could inject this is here:

    https://github.com/puphpet/puphpet/blob/master/archive/puphpet/puppet/nodes/Mysql.pp#L50-L54

2. Put a configuration file in [`includedir`][2].

    In which case, you would place an `ini`-style MySQL configuration in the configured directory (like my first post in this thread) and it would be copied to `/etc/mysql/conf.d/`.

    Again, if you are modifying these files, you could configure the `includedir` here:

    https://github.com/puphpet/puphpet/blob/master/archive/puphpet/puppet/nodes/Mysql.pp#L56-L61

I haven't tested any of this so YMMV, but it should at least point you in the right direction.

[1]: https://github.com/puppetlabs/puppetlabs-mysql#customizing-server-options
[2]: https://github.com/puppetlabs/puppetlabs-mysql#custom-configuration

**Comment by sendalot** [comment]
@deizel, hmm, that ends in mysqld not being able to start.
Did I mess up some bind address or hostname?

150522 08:14:57 mysqld_safe mysqld from pid file /var/run/mysqld/mysqld.pid ended
150522 08:20:50 mysqld_safe Starting mysqld daemon with databases from /var/lib/mysql
150522  8:20:50 [ERROR] Can't start server: cannot resolve hostname!: Resource temporarily unavailable
150522  8:20:50 [ERROR] Aborting

150522 08:20:50 mysqld_safe mysqld from pid file /var/run/mysqld/mysqld.pid ended
150522 08:22:42 mysqld_safe Starting mysqld daemon with databases from /var/lib/mysql
/usr/libexec/mysqld: Table 'mysql.plugin' doesn't exist
150522  8:22:42 [ERROR] Can't open the mysql.plugin table. Please run mysql_upgrade to create it.
150522  8:22:42  InnoDB: Initializing buffer pool, size = 8.0M
150522  8:22:42  InnoDB: Completed initialization of buffer pool
InnoDB: The first specified data file ./ibdata1 did not exist:
InnoDB: a new database to be created!
150522  8:22:42  InnoDB: Setting file ./ibdata1 size to 10 MB
InnoDB: Database physically writes the file full: wait...
150522  8:22:42  InnoDB: Log file ./ib_logfile0 did not exist: new to be created
InnoDB: Setting log file ./ib_logfile0 size to 5 MB
InnoDB: Database physically writes the file full: wait...
150522  8:22:42  InnoDB: Log file ./ib_logfile1 did not exist: new to be created
InnoDB: Setting log file ./ib_logfile1 size to 5 MB
InnoDB: Database physically writes the file full: wait...
InnoDB: Doublewrite buffer not found: creating new
InnoDB: Doublewrite buffer created
InnoDB: Creating foreign key constraint system tables
InnoDB: Foreign key constraint system tables created
150522  8:22:43  InnoDB: Started; log sequence number 0 0
150522  8:22:43 [Warning] Failed to setup SSL
150522  8:22:43 [Warning] SSL error: SSL_CTX_set_default_verify_paths failed
150522  8:22:43 [ERROR] Fatal error: Can't open and lock privilege tables: Table 'mysql.host' doesn't exist
150522 08:22:43 mysqld_safe mysqld from pid file /var/run/mysqld/mysqld.pid ended
150522 08:24:42 mysqld_safe Starting mysqld daemon with databases from /var/lib/mysql
150522  8:24:42 [ERROR] Can't start server: cannot resolve hostname!: Resource temporarily unavailable
150522  8:24:42 [ERROR] Aborting

150522 08:24:42 mysqld_safe mysqld from pid file /var/run/mysqld/mysqld.pid ended
150522 08:25:17 mysqld_safe Starting mysqld daemon with databases from /var/lib/mysql
150522  8:25:17 [ERROR] Can't start server: cannot resolve hostname!: Resource temporarily unavailable

Thank you very much for your time and kindness.

**Comment by sendalot** [comment]
changed ['bind-address' => '*',] to ['bind-address' => 'undef',] and seems to be working.
Thanks again for your time.

**Comment by gdsmith** [comment]
For anyone trying to get this to work here's the relevant sections of my yaml file which allows accessing mysql from the host on 127.0.0.1 (as we're port forwarding):

```yml
vagrantfile:
    vm:
        provider:
            local:
                machines:
                    vflm_ojqp5xo08nyw:
                        network:
                            forwarded_port:
                                vflmnfp_mc0jsulapesu:
                                    host: '3306'
                                    guest: '3306'
mariadb: # or mysql
    settings:
        override_options: {
            mysqld: {
              bind-address: '0.0.0.0',
              skip-name-resolve: true
            }
        }
    users:
        mariadbnu_9n8sn07i7izl:
            name: dbuser@%
            password: '123'
    grants:
        mariadbng_j023im5wbnyx:
            user: dbuser@%
            table: '*.*'
            privileges:
                - ALL
```
This allows the following from guest and host:
```bash
mysql -h 127.0.0.1 -u dbuser -p
```
