### ISSUE TITLE
migrate from ubuntu1404-x64 and virtualbox 4.3 to new puphpet 

### ISSUE THREAD

**Issue by SonkoDmitry** [puphpet/puphpet#2054]
I have two machines with box puphpet/ubuntu1404-x64 (virtualbox, 2.0) and virtualbox 4. How i can migrate it to virtualbox5, box puphpet/ubuntu1404-x64 (virtualbox, 20151201) and new puphpet config format.

**Comment by jtreminio** [comment]
You need to destroy. There's no way to keep the box alive.

You can, however, drag and drop your config.yaml into the gui and it'll populate with your previous choices. Just give it a quick sanity check and download the archive.

**Comment by SonkoDmitry** [comment]
Okey, thank you
