### ISSUE TITLE
ubuntu1404-x64 manpages are broken

### ISSUE THREAD

**Issue by NReilingh** [puphpet/puphpet#2061]
Well, this is... weird. I'm installing what I think is a totally vanilla virtualbox vm, and man is unable to find any of the core manpages. Everything (even `$ man man`) returns

    No manual entry for man
    See 'man 7 undocumented' for help when manual pages are not available.

I made sure to test without copying any dotfiles -- the attached config.yaml was downloaded directly, then unzipped and `vagrant up`'d. `$MANPATH` is blank, which I'm told is supposed to be the case by default, but populating it with `/usr/share/man` isn't helping either.

[config.yaml](https://github.com/puphpet/puphpet/files/68112/config.yaml.txt)

**Comment by NReilingh** [comment]
Hm, it looks like `man apachectl` works -- so perhaps this is related to creating an image using apache instead of nginx?

**Comment by jtreminio** [comment]
Seems like it's normal?

```[08:36 AM]-[vagrant@local]-[/usr/share/man/man7]
$ ls /usr/share/man/man7
debhelper.7.gz  gitcore-tutorial.7.gz  gitcvs-migration.7.gz  giteveryday.7.gz  gitnamespaces.7.gz  gittutorial-2.7.gz  gitworkflows.7.gz
gitcli.7.gz     gitcredentials.7.gz    gitdiffcore.7.gz       gitglossary.7.gz  gitrevisions.7.gz   gittutorial.7.gz    po-debconf.7.gz

[08:37 AM]-[vagrant@local]-[/usr/share/man/man7]
$ man gittutorial```

**Comment by Djuuu** [comment]
I'm sorry but how is it normal ? Shouldn't the core man pages already be included in the base boxes ? Or are the boxes deliberately stripped down ?
By the way, I have the same symptom with the _Debian Wheezy 7 x64_ box.
