### ISSUE TITLE
Separate /etc/php5/mods-available/ entry for xdebug

### ISSUE THREAD

**Issue by entr** [puphpet/puphpet#2063]
I need to be able to easily enable/disable mods for different SAPI. For example I need xdebug enabled for FPM but not for CLI. Currently xdebug config is in zzzz_custom.ini along with other stuff.

**Comment by jtreminio** [comment]
This is currently not possible with puphpet's configuration.

A PR would be welcome, though.

**Comment by jtreminio** [comment]
Fixed in latest release.
