### ISSUE TITLE
Puphpet failed with multiple directory blocks

### ISSUE THREAD

**Issue by pjcvijay** [puphpet/puphpet#2068]
I ran into below issue when using multiple directory blocks, this is was working without any issues in the past. Today I created new configuration which failed to create VM:

Here is my new config.yaml: 
https://dpaste.de/j4G1

Error: Evaluation Error: Error while evaluating a Function Call, Failed to parse template puphpet/apache/files_match.erb:
==> default:   Filepath: /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/parser/scope.rb
==> default:   Line: 636
==> default:   Detail: Cannot reassign variable '$_directories'
==> default:  at /tmp/vagrant-puppet/manifests-75f35e3bc7e32744860c4bb229c88812/Apache.pp:175:29 on node safegatherings.dev
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

Thanks,
Vijay

**Comment by pjcvijay** [comment]
I am using Vagrant 1.7.4 and Virtual Box 5.0.12 on Ubuntu 14.04.

`vagrant box list` command output:
puphpet/ubuntu1404-x64 (virtualbox, 20151201)

**Comment by pjcvijay** [comment]
Any idea about this issue?

**Comment by pjcvijay** [comment]
Anybody facing the same issue? Please help me resolve this.

**Comment by jtreminio** [comment]
Your config.yaml expired; link it to a site that doesn't expire or set expiration later.

I recall fixing a bug similar to this. Have you tried regenerating your archive?

**Comment by Enchiridion** [comment]
I was having the same issue and the commits fixed it for me.
