### ISSUE TITLE
timeout during server version negotiating

### ISSUE THREAD

**Issue by acedude** [puphpet/puphpet#2070]
My box starts normally after the first run, but when I try to restart it, here's what happens:

```
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'puphpet/ubuntu1404-x64' is up to date...
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 22 (guest) => 7859 (host) (adapter 1)
    default: 27017 (guest) => 28017 (host) (adapter 1)
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
==> default: Setting hostname...
An error occurred in the underlying SSH library that Vagrant uses.
The error message is shown below. In many cases, errors from this
library are caused by ssh-agent issues. Try disabling your SSH
agent or removing some keys and try again.

If the problem persists, please report a bug to the net-ssh project.

timeout during server version negotiating
```

I upgraded my vagrant and virtualbox just before setting up that VM. None of my old machines have this issue. Config file attached below.

[config.txt](https://github.com/puphpet/puphpet/files/73917/config.txt)

**Comment by onz123** [comment]
Same problem. I also upgraded my vagrant and virtual box just before setting up the VM.

**Comment by acedude** [comment]
Fun fact: you can "trick" the VM to start by using "Reset" function in Vagrant UI in proper moments, so the VM MIGHT start. But then Mongo won't start (no write access to the lock file). So there's something weird going on.

**Comment by Healthfundr** [comment]
Same problem.

**Comment by ziplizard** [comment]
Same problem.

**Comment by yhbyun** [comment]
same problem after upgraded virtual box and vagrant.

**Comment by gocanto** [comment]
Same problem here, any solution?

**Comment by schmitzoide** [comment]
Same here.

**Comment by rdeknijf** [comment]
Same here, on a newly installed Ubuntu 15.10 with Vagrant 1.8.1 and Virtualbox 5.0.12. 
(This machine is itself a Virtualbox guest on a Windows host.)

**Comment by jtreminio** [comment]
All, unfortunately I do not believe this is a puphpet issue.

At the point the error happens, nothing really puphpet-specific has kicked in yet.

Might want to ask over at the vagrant repo.

**Comment by gocanto** [comment]
I passed through the same issue and I fixed it doing this:

`https://laracasts.com/discuss/channels/laravel/homestead-up-problemas?page=0#reply-130684`

**Comment by acedude** [comment]
@gocanto but how is laravel homestead related to puphpet?

**Comment by gocanto** [comment]
@acedude they are not. But, I passed thru the same issue trying to figure out and found out that when you upgrade your box and don't follow this https://docs.vagrantup.com/v2/installation/uninstallation.html 

hope it helps you

**Comment by agungsijawir** [comment]
Same here.

But I found that, even after getting error message, I can connect to vbox via `vagrant ssh` command. But, really, the operation took very long time. Around 1 min or so.

After login to ssh, I could only run 1 command. Fortunately, I could see `ifconfig` output from vbox and only 2 interfaces shown, `eth0` and `lo0`. `eth0` assigned to ip `10.0.2.15`.

When trying to shutdown vbox via `vagrant halt`, vagrant trying to force shutdown instead gracefully like usual.

**Comment by deytao** [comment]
I have the same behavior as @agungsijawir and I really have no idea how to fix it.
I checked all the possible solutions (I think) I found.

Help please.

**Comment by AhmedSamy** [comment]
same here, I have El Capitan and 1.8.1

**Comment by deytao** [comment]
I fixed it by killing the `/usr/bin/ssh-agent` running process.

**Comment by bajax** [comment]
@deytao In the host or guest system?

**Comment by deytao** [comment]
On the host system.
I had it from the end December when I upgraded vagrant. It doesn't happen anymore

**Comment by jtreminio** [comment]
All, please take this to the Vagrant repo; I can't actually help, and I believe it to be an upstream issue.

Nothing I can do here. Sorry!

**Comment by valterhenrique** [comment]
I had this problem on Ubuntu 14. I have two different ssh keys for my projects, what solve the problem to me, was creating a symbolic link from my ssh key point out to ~/.ssh/id_rsa.
Also, ensure that you delete you key from your Digital Ocean account, because Vagrant will added it there.
