### ISSUE TITLE
elasticsearch not running/startup script is missing

### ISSUE THREAD

**Issue by bartrail** [puphpet/puphpet#2079]
elasticsearch is installed to `/usr/share/elasticsearch` 
but the script like `/etc/init.d/elasticsearch` is missing and I can't start it with `service elasticsearch start` because the _service elasticsearch is not recognized_  - 

besides that, the box is running fine..

this is my config.yaml http://pastebin.com/ZHvM6aHc

Any help is very appreciated :)

**Comment by vincenzo** [comment]
This is a duplicate of https://github.com/puphpet/puphpet/issues/2040
