### ISSUE TITLE
ForwardAgent doesn't work

### ISSUE THREAD

**Issue by Schrank** [puphpet/puphpet#2081]
I'm trying to clone a private git repo inside a VM like #675, but it doesn't work.

ForwardAgent is allowed and "working" (as debugging by github), but for some reason I'm not able to use the key on github.com:

    $ ssh -T github.com
    Permission denied (publickey).

    $ echo "$SSH_AUTH_SOCK"
    /tmp/ssh-h7O2vx84J5/agent.20188

Locally:
```
> % vagrant ssh-config
Host default
  HostName 127.0.0.1
  User vagrant
  Port 2222
  UserKnownHostsFile /dev/null
  StrictHostKeyChecking no
  PasswordAuthentication no
  IdentityFile /Volumes/Web/Projects/brera/test/puphpet/files/dot/ssh/id_rsa
  IdentityFile /Users/fabian/.vagrant.d/insecure_private_key
  IdentitiesOnly yes
  LogLevel FATAL
  ForwardAgent yes
```
Any ideas why this doesn't work?

**Comment by jtreminio** [comment]
http://wildlyinaccurate.com/using-ssh-agent-forwarding-with-vagrant/

**Comment by Schrank** [comment]
Sorry for not clising this one :-/ I was just too dumb to add the correct key to the agent on the local machine (not theVM)

**Comment by jtreminio** [comment]
No worries, it happens. Quite often to me.
