### ISSUE TITLE
php5-opcache package not found.

### ISSUE THREAD

**Issue by DaveYoungV9** [puphpet/puphpet#2085]
Since updating to the latest PuPHPet (4.3.x?) as of 1/3/2016 I am seeing an error during provisioning indicating the php5-opcache package could not be located:

==> default: Error: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install php5-opcache' returned 100: Reading package lists...
==> default: Building dependency tree...
==> default: Reading state information...
==> default: E: Unable to locate package php5-opcache
==> default: Error: /Stage[main]/Puphpet_php/Puphpet::Php::Module[opcache]/Php::Module[opcache]/Package[PhpModule_opcache]/ensure: change from purged to present failed: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install php5-opcache' returned 100: Reading package lists...
==> default: Building dependency tree...
==> default: Reading state information...
==> default: E: Unable to locate package php5-opcache

The config is as follows:
VirtualBox, Ubuntu Trusty 14.04 LTS x64, PHP 5.6

The opcache is available in the drop-down in the configuration wizard on the PHP screen. If I remove opcache from the config.yaml file and provision everything works as expected.

**Comment by jtreminio** [comment]
opcache comes bundled with 5.6, don't need to include it.

**Comment by DaveYoungV9** [comment]
I figured as much. May want to pull it from the select list if 5.6 is the chosen version. 

Thnks for making this awesome tool!!
