### ISSUE TITLE
Directory /etc/php5/conf.d not created for php version 5.4

### ISSUE THREAD

**Issue by marekk** [puphpet/puphpet#2090]
This results in error:

==> default: Error: Could not set 'link' on ensure: No such file or directory @ dir_chdir - /etc/php5/conf.d at 74:/tmp/vagrant-puppet/modules-7ab13cd02a1a0683508c1be64792a6d2/puphpet/manifests/php/ini.pp
==> default: Error: Could not set 'link' on ensure: No such file or directory @ dir_chdir - /etc/php5/conf.d at 74:/tmp/vagrant-puppet/modules-7ab13cd02a1a0683508c1be64792a6d2/puphpet/manifests/php/ini.pp
==> default: Wrapped exception:
==> default: No such file or directory @ dir_chdir - /etc/php5/conf.d
==> default: Error: /Stage[main]/Puphpet_php/Puphpet::Php::Ini[cgi.fix_pathinfo]/File[/etc/php5/conf.d/zzzz_custom.ini]/ensure: change from absent to link failed: Could not set 'link' on ensure: No such file or directory @ dir_chdir - /etc/php5/conf.d at 74:/tmp/vagrant-puppet/modules-7ab13cd02a1a0683508c1be64792a6d2/puphpet/manifests/php/ini.pp

Fixed by adding these lines to `puphpet/modules/puphpet/manifests/php/ini.pp` around line 70:

```php
$symlink_dir = "/etc/php5/conf.d"
		  
if ! defined(File[$symlink_dir]) {
  file { $symlink_dir:
      ensure => 'directory',
  }
}
```

**Comment by jtreminio** [comment]
Needs config.yaml

**Comment by jtreminio** [comment]
Closing this.

Make sure you're not trying to install PHP 5.4 on Ubuntu 14.04
