### ISSUE TITLE
Vagrant --provision fails after adding the virtualhost to nginx

### ISSUE THREAD

**Issue by sasos90** [puphpet/puphpet#2100]
Hi everyone!

I have a big issue! I wanted to add a new virtualhost after a long time without provisioning the virtualbox to config.yaml. Now I get the error while provisioning and it stop the execution of course. Actually the machine is running, the nginx is running, but because it changed my nginx configuration, the virtual hosts are not working anymore (it downloads the index.php instead of running it and so on). I believe there is something wrong with php5-fpm because I can't find it in netstat for port 9000 but I can find it with ps aux | grep fpm. So I am completely lost. I can't run the vagrant machine anymore.
- I updated the vagrant box
- I recreated the archive from puphpet
... but the error is still there. I doubt that if i reinstall vagrant and virtualbox, that the thing will work.

There are the pictures what went wrong while I ran "vagrant reload --provision":
https://www.dropbox.com/s/hnaw06ccsl8i76u/vagrant.png?dl=0

I really appreciate every answer I get!

Thank you in advance!

**Comment by refringe** [comment]
The first error is directly related to #2098; Composer is failing to install. The others may be related to Composer failing. It's hard to tell.

Ensure that puphpet is up to date by visiting puphpet.com and dragging your config.yaml onto the homepage. That should load your configuration into the site. Go page by page and confirm that the settings are correct. On the last page download the package and replace your local copy.

After that you may need to `vagrant destroy` and then `vagrant up`. You'll probably still get the Composer fail, but it may clear up some of the other issues.

In the future it may help if you post your config.yaml file in a Gist for others to see/test.

**Comment by sasos90** [comment]
Thank you for the answer.
I checked the issue you gave me, and I changed the config.yaml (remove the postgres install  and the composer.pp file as someone mentioned in that issue. But unfortunately it didn't solve the issue.. It still fails to finish the vagrant.. normally it fails at php5-fpm install or something like that.. actually it looks like it fails randomly.

Now I get this error:
*Error: printf "\n" | pecl -d preferred_state=stable install pecl_http && pecl info pecl_http returned 1 instead of one of [0]
==> default: Error: /Stage[main]/Puphpet_php/Puphpet::Php::Pecl[pecl_http]/Php::Pecl::Module[pecl_http]/Exec[pecl-pecl_http]/returns: change from notrun to 0 failed: printf "\n" | pecl -d preferred_state=stable install pecl_http && pecl info pecl_http returned 1 instead of one of [0]*

Why is this so unstable?

My config.yaml: http://laravel.io/bin/Dex4z

**Comment by BartoszBartniczak** [comment]
I have exactly the same issues. Here is my config file: http://pastebin.com/77buxCkn
There are errors during installation of php_memcached and pecl_http

**Comment by sasos90** [comment]
Ok the thing is. Since I runned the reload --provision, the provision obviously failed. But the VM was still working, so I manually made some fixes (php fpm, nginx, ...) and the VM is working for me. But I will not run provision again. So the issue can remain open, but I will not fix it anymore.

Thanks for help guys!

**Comment by jtreminio** [comment]
`pecl_http` was removed as a default module because of recent changes to it making it hard to install. You *probably* don't need it.

**Comment by jtreminio** [comment]
@sasos90 all your issues have been resolved, except for that postgresql one, but I think that's user error.

Regenerate your archive, try again!

**Comment by sasos90** [comment]
I will try on monday and give you the feedback. Thank you very much!
