### ISSUE TITLE
Make Zend opcache optional

### ISSUE THREAD

**Issue by nodren** [puphpet/puphpet#2107]
Currently on my VM, I run into some highly strange caching issues, to where certain files I have definitely changed, but may not have changed the length of, will have their old versions cached until some other larger change happens to the file.  I was able to resolve this issue by manually disabling opcache, but I found no option for this in the config.yaml or on puphpet.com

Can we make opcache optional, so when using puphpet for dev vms we can disable it?

**Comment by jtreminio** [comment]
Zend OPcache comes compiled by default into PHP 5.5+ from the repos PuPHPet uses.

There's no way to choose to not install it other than manually compiling PHP yourself, or finding a repo that does not have it compiled in.

**Comment by nodren** [comment]
I was able to disable it by simply deleting the symlink to opcache config in /etc/php/whatever/conf.d

could that not be made a configurable option?
