### ISSUE TITLE
Vagrant timeout on SSH auth method, but guest machine boots just fine

### ISSUE THREAD

**Issue by smagnaschi** [puphpet/puphpet#2108]
Puphpet machine configuration for both debian and ubuntu (the only ones I've tested) behave in the same way.
I vagrant up, they import the machine, try to boot and remain stuck on 
    
     local: SSH auth mehtod: private key.

I modified the vagrant up script to show the virtualbox gui of the guest machine and I can see that the machine boots without issues, but vagrant seems to  fail to acknowledge the succesful boot.

Vagrant version 1.81 Virtual Box 5.0.12 on Mac OsX El Capitan

Other vagrant machines load just fine.

This is the config.yaml

    vagrantfile:
        target: local
        vm:
            box: puphpet/ubuntu1404-x64
            box_url: puphpet/ubuntu1404-x64
            hostname: rockol.local
            memory: '1024'
            cpus: '2'
            chosen_provider: virtualbox
            box_version: ''
            network:
                private_network: 192.168.56.4
                forwarded_port:
                    vflnp_hbs1nz79xgfq:
                        host: '8463'
                        guest: '22'
            post_up_message: ''
            provider:
                virtualbox:
                    modifyvm:
                        natdnshostresolver1: 'on'
                    showgui: '0'
                vmware:
                    numvcpus: 1
                parallels:
                    use_linked_clone: '0'
                    check_guest_tools: '0'
                    update_guest_tools: '0'
            provision:
                puppet:
                    manifests_path: puphpet/puppet/manifests
                    module_path: puphpet/puppet/modules
                    options:
                        - '--verbose'
                        - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
            synced_folder:
                vflsf_yfly75hajro7:
                    source: ./
                    target: /var/www
                    sync_type: default
                    smb:
                        smb_host: ''
                        smb_username: ''
                        smb_password: ''
                    rsync:
                        args:
                            - '--verbose'
                            - '--archive'
                            - '-z'
                        exclude:
                            - .vagrant/
                            - .git/
                        auto: 'true'
                    owner: www-data
                    group: www-data
            usable_port_range:
                start: 10200
                stop: 10500
        ssh:
            host: null
            port: null
            private_key_path: null
            username: vagrant
            guest_port: null
            keep_alive: true
            forward_agent: false
            forward_x11: false
            shell: 'bash -l'
            insert_key: false
        vagrant:
            host: detect
        proxy:
            http: ''
            https: ''
            ftp: ''
            no_proxy: ''
            enabled: ''
    server:
        install: '1'
        packages:
            - htop
            - iftop
    users_groups:
        install: '1'
        groups: {  }
        users: {  }
    locale:
        install: '1'
        settings:
            default_locale: en_US.UTF-8
            locales:
                - en_GB.UTF-8
                - en_US.UTF-8
    firewall:
        install: '1'
        rules: {  }
    cron:
        install: '1'
        jobs: {  }
    nginx:
        install: '0'
        settings:
            default_vhost: 1
            proxy_buffer_size: 128k
            proxy_buffers: '4 256k'
            proxy_connect_timeout: 600s
            proxy_send_timeout: 600s
            proxy_read_timeout: 600s
            names_hash_bucket_size: 128
        upstreams: {  }
        vhosts:
            nxv_mix7nmy39cuw:
                server_name: awesome.dev
                server_aliases:
                    - www.awesome.dev
                www_root: /var/www/awesome
                listen_port: '80'
                index_files:
                    - index.html
                    - index.htm
                    - index.php
                client_max_body_size: 1m
                ssl: '0'
                ssl_cert: ''
                ssl_key: ''
                ssl_port: '443'
                ssl_protocols: ''
                ssl_ciphers: ''
                rewrite_to_https: '1'
                spdy: '1'
                locations:
                    nxvl_ncqauzq3n3cw:
                        location: /
                        autoindex: 'off'
                        internal: 'false'
                        try_files:
                            - $uri
                            - $uri/
                            - /index.php$is_args$args
                        fastcgi: ''
                        fastcgi_index: ''
                        fastcgi_split_path: ''
                        proxy: ''
                        proxy_redirect: ''
                    nxvl_6g9270bgwr5t:
                        location: '~ \.php$'
                        autoindex: 'off'
                        internal: 'false'
                        try_files:
                            - $uri
                            - $uri/
                            - /index.php$is_args$args
                        fastcgi: '127.0.0.1:9000'
                        fastcgi_index: index.php
                        fastcgi_split_path: '^(.+\.php)(/.*)$'
                        fast_cgi_params_extra:
                            - 'SCRIPT_FILENAME $request_filename'
                            - 'APP_ENV dev'
                        set:
                            - '$path_info $fastcgi_path_info'
                        proxy: ''
                        proxy_redirect: ''
        proxies: {  }
    apache:
        install: '1'
        settings:
            version: 2.4
            user: www-data
            group: www-data
            default_vhost: true
            manage_user: false
            manage_group: false
            sendfile: 0
        modules:
            - proxy_fcgi
            - rewrite
        vhosts:
            av_go28q22gepc5:
                servername: awesome.dev
                serveraliases:
                    - www.awesome.dev
                docroot: /var/www/awesome
                port: '80'
                setenv:
                    - 'APP_ENV dev'
                setenvif:
                    - 'Authorization "(.*)" HTTP_AUTHORIZATION=$1'
                custom_fragment: ''
                ssl: '0'
                ssl_cert: ''
                ssl_key: ''
                ssl_chain: ''
                ssl_certs_dir: ''
                ssl_protocol: ''
                ssl_cipher: ''
                directories:
                    avd_9jbv2sp5xec3:
                        path: /var/www/rockol.it
                        options:
                            - Indexes
                            - FollowSymlinks
                            - MultiViews
                        allow_override:
                            - All
                        require:
                            - 'all granted'
                        custom_fragment: ''
                        files_match:
                            avdfm_nswa0h8hghmy:
                                path: \.php$
                                sethandler: 'proxy:fcgi://127.0.0.1:9000'
                                custom_fragment: ''
                                provider: filesmatch
                        provider: directory
                    avd_6m3i7dlroee9:
                        path: /var/www/rockol.com
                        options:
                            - Indexes
                            - FollowSymlinks
                            - MultiViews
                        allow_override:
                            - All
                        require:
                            - 'all granted'
                        custom_fragment: ''
                        provider: directory
    php:
        install: '1'
        settings:
            version: '55'
        modules:
            php:
                - cli
                - intl
                - curl
                - fpm
                - gd
                - mbstring
                - opcache
            pear: {  }
            pecl: {  }
        ini:
            display_errors: 'On'
            error_reporting: '-1'
            session.save_path: /var/lib/php/session
            date.timezone: UTC
        fpm_ini:
            error_log: /var/log/php-fpm.log
        fpm_pools:
            phpfp_lgl2pjab267w:
                ini:
                    prefix: www
                    listen: '127.0.0.1:9000'
                    security.limit_extensions: .php
                    user: www-user
                    group: www-data
        composer: '1'
        composer_home: ''
    xdebug:
        install: '1'
        settings:
            xdebug.default_enable: '1'
            xdebug.remote_autostart: '0'
            xdebug.remote_connect_back: '1'
            xdebug.remote_enable: '1'
            xdebug.remote_handler: dbgp
            xdebug.remote_port: '9000'
    blackfire:
        install: '0'
        settings:
            server_id: ''
            server_token: ''
            agent:
                http_proxy: ''
                https_proxy: ''
                log_file: stderr
                log_level: '1'
            php:
                agent_timeout: '0.25'
                log_file: ''
                log_level: '1'
    xhprof:
        install: '0'
    wpcli:
        install: '0'
        version: v0.21.1
    drush:
        install: '0'
        version: 6.3.0
    ruby:
        install: '1'
        versions:
            rv_ol8if10lrr32:
                default: '1'
                bundler: '1'
                version: 1.9.3
    python:
        install: '1'
        packages: {  }
        versions: {  }
    nodejs:
        install: '0'
        settings:
            version: '5'
        npm_packages: {  }
    hhvm:
        install: '0'
        nightly: 0
        composer: '1'
        composer_home: ''
        settings: {  }
        server_ini:
            hhvm.server.host: 127.0.0.1
            hhvm.server.port: '9000'
            hhvm.log.use_log_file: '1'
            hhvm.log.file: /var/log/hhvm/error.log
        php_ini:
            display_errors: 'On'
            error_reporting: '-1'
            date.timezone: UTC
    mariadb:
        install: '1'
        settings:
            version: '10.0'
            root_password: '123'
            override_options: {  }
        adminer: '1'
        users:
            mariadbnu_4n1fewwbk7yl:
                name: dbuser
                password: '123'
        databases:
            mariadbnd_zt75xh49yzrs:
                name: rockol_it
                sql: ''
            mariadbnd_9s5yastgkv9a:
                name: ''
                sql: ''
        grants:
            mariadbng_qeu6r5kz5cge:
                user: dbuser
                table: '*.*'
                privileges:
                    - ALL
    mysql:
        install: '0'
        settings:
            version: '5.5'
            root_password: '123'
            override_options: {  }
        adminer: 0
        users:
            mysqlnu_7mphdgstczlx:
                name: dbuser
                password: '123'
        databases:
            mysqlnd_mkjn1b0e15j8:
                name: dbname
                sql: ''
        grants:
            mysqlng_ysp6820oy304:
                user: dbuser
                table: '*.*'
                privileges:
                    - ALL
    postgresql:
        install: '0'
        settings:
            global:
                encoding: UTF8
                version: '9.4'
            server:
                postgres_password: '123'
        databases: {  }
        users: {  }
        grants: {  }
        adminer: 0
    mongodb:
        install: '0'
        settings:
            auth: 1
            bind_ip: 127.0.0.1
            port: '27017'
        globals:
            version: 2.6.0
        databases: {  }
    redis:
        install: '1'
        settings:
            port: '6379'
    sqlite:
        install: '0'
        adminer: 0
        databases: {  }
    mailhog:
        install: '0'
        settings:
            smtp_ip: 0.0.0.0
            smtp_port: 1025
            http_ip: 0.0.0.0
            http_port: '8025'
            path: /usr/local/bin/mailhog
    beanstalkd:
        install: '0'
        settings:
            listenaddress: 0.0.0.0
            listenport: '11300'
            maxjobsize: '65535'
            maxconnections: '1024'
            binlogdir: /var/lib/beanstalkd/binlog
            binlogfsync: null
            binlogsize: '10485760'
        beanstalk_console: 0
    rabbitmq:
        install: '0'
        settings:
            port: '5672'
        users: {  }
        vhosts: {  }
        plugins: {  }
    elastic_search:
        install: '1'
        settings:
            version: 1.7.3
            java_install: true
        instances:
            esi_tepvyzpeh5pg:
                name: es-01
    solr:
        install: '0'
        settings:
            version: 4.10.2
            port: '8984'

**Comment by smagnaschi** [comment]
With 'other vagrant machines' I mean machines not created through Puphpet.

**Comment by alehkot** [comment]
@smagnaschi I suggest trying to disable natdnsresolved, e.g. 
```
provider:
            virtualbox:
                modifyvm:
                    natdnshostresolver1: false
                showgui: '0'
```
Please note the usage of _false_ instead of 'off'.

**Comment by smagnaschi** [comment]
Thanks @alehkot 
Yes, that solved the problem. Is it a bug? Do I need to manually change that on each puphpet package download?

**Comment by alehkot** [comment]
@smagnaschi It looks like a bug. Also it's related to #2086.

**Comment by jtreminio** [comment]
@alehkot should this be disabled by default?

**Comment by alehkot** [comment]
@jtreminio Yes, I suggest disabling this temporarily.
