### ISSUE TITLE
composer arguments are not used from hiera

### ISSUE THREAD

**Issue by sshilko** [puphpet/puphpet#2111]
```
//puppet/manifests/Php.pp

  if array_true($php, 'composer') and ! defined(Class['puphpet::php::composer']) {
    class { 'puphpet::php::composer':
      php_package   => $puphpet::php::settings::cli_package,
      composer_home => $php['composer_home'],
    }
  }
```

only composer_home and php_package are passed

**Comment by jtreminio** [comment]
What settings are you wanting to pass? Composer isn't configurable by default, hadn't really thought of allowing it.

**Comment by sshilko** [comment]
i had to install composer manually via

```
  class { 'composer':
    target_dir      => '/usr/local/bin',
    composer_file   => 'composer.phar',
    download_method => 'wget',
    logoutput       => false,
    tmp_path        => '/tmp',
    php_package     => 'php7.0-cli',
    curl_package    => 'curl',
    suhosin_enabled => false,
    php_bin         => 'php 2>/dev/null ',
    user            => 'root'
  }
```

othewise it says " returned code 255 instead of [0] " error.. so i wanted to pass "php_bin", download_method, composer_file.

already created issue on composer-package git. issue list about error code 255 instead of 0

**Comment by spfaffly** [comment]
I also had to change the download option to use wget instead of curl.

**Comment by jtreminio** [comment]
While not solving your title-issue, this commit will solve your actual issue: https://github.com/puphpet/puppet-puphpet/commit/659fc6d6548dd8158fdac7bb834111c769854a98
