### ISSUE TITLE
Harddisk filled up when installing puphpet/debian75-x64 box

### ISSUE THREAD

**Issue by smichaelsen** [puphpet/puphpet#2116]
I have been using my puphpet box for some time, but after I run the config file through the web interface it tries to install a new debian box. After the download I asume it is extracted, but then my harddrive runs completely full - no matter how much space I had before the installation. The maximum I tried was ~30GB. It shouldn't take so much disk space to install the box, should it?

What info can I provide to clear things up?
This is my config.yaml: https://gist.github.com/smichaelsen/e81c2ea6e3a682d67bb3

Console output looks like this:

    Bringing machine 'local' up with 'parallels' provider...
    ==> local: Box 'puphpet/debian75-x64' could not be found. Attempting to find and install...
        local: Box Provider: parallels
        local: Box Version: >= 0
    ==> local: Loading metadata for box 'puphpet/debian75-x64'
        local: URL: https://atlas.hashicorp.com/puphpet/debian75-x64
    ==> local: Adding box 'puphpet/debian75-x64' (v20151201) for provider: parallels
        local: Downloading: https://atlas.hashicorp.com/puphpet/boxes/debian75-x64/versions/20151201/providers/parallels.box
    The box failed to unpackage properly. Please verify that the box
    file you're trying to add is not corrupted and try again. The
    output from attempting to unpackage (if any):

    x Vagrantfile
    x debian79.pvm/VmInfo.pvi
    x debian79.pvm/config.pvs
    x debian79.pvm/harddisk1.hdd/DiskDescriptor.xml
    x debian79.pvm/harddisk1.hdd/harddisk1.hdd
    x debian79.pvm/harddisk1.hdd/harddisk1.hdd.0.{5fbaabe3-6958-40ff-92a7-860e329aab41}.hds: Write failed
    x debian79.pvm/harddisk1.hdd/harddisk1.hdd.drh: Write to restore size failed
    x metadata.json: Write to restore size failed
    bsdtar: Error exit delayed from previous errors.

**Comment by jtreminio** [comment]
The box files themselves are a hair over 600MB. It shouldn't fill up your 30GB at all.

This sounds like a vagrant core issue, not puphpet. Possibly Parallels. Please ask them - I have absolutely no way to provide support on this.

Good luck!
