### ISSUE TITLE
PHP extension install error for RabbitMQ in Ubuntu Trusty 14.04

### ISSUE THREAD

**Issue by stanislas-prime** [puphpet/puphpet#2117]
Hi, I'm trying to build virtual server with PHP 5.6 and RabbitMQ using puphpet.com

There is an error during the installation PHP extension for RabbitMQ. The thing is that system tries to install `librabbitmq 0.4.1-1`, which it too old for `php-amqp 1.6.1`. From [php-amqp Requirements](https://github.com/pdezwart/php-amqp#requirements):
> since php-amqp>=1.6.0 librabbitmq >= 0.5.2 required, >= 0.6.0 recommended

So... puppet model need to be updated to install latest librabbitmq-dev package.

Also there is a problem with accessign RabbitMQ management page in browser. I recognized that to solve the problem we need to add exception to `iptables` for port `15672`:
`iptables -I INPUT -p tcp --dport 15672 -j ACCEPT`

After that management page is accessible. Will be greate if all these things will be fixed. Thanks.

**Comment by jtreminio** [comment]
In your config.yaml change the rabbitmq section to:

    rabbitmq:
        install: '1'
        settings:
            port: '5672'
            manage_repos: '1'
        users: {  }
        vhosts: {  }
        plugins: {  }

However, attempting to install amqp via pecl doesn't work.

RabbitMQ:

    [04:33 AM]-[root@local]-[/etc/php5/conf.d]
    # rabbitmqctl status
    Status of node rabbit@local ...
    [{pid,18834},
     {running_applications,
         [{rabbitmq_management,"RabbitMQ Management Console","3.6.0"},
          {rabbitmq_web_dispatch,"RabbitMQ Web Dispatcher","3.6.0"},
          {webmachine,"webmachine","git"},
          {mochiweb,"MochiMedia Web Server","2.13.0"},
          {rabbitmq_management_agent,"RabbitMQ Management Agent","3.6.0"},
          {rabbit,"RabbitMQ","3.6.0"},
          {os_mon,"CPO  CXC 138 46","2.2.14"},
          {ssl,"Erlang/OTP SSL application","5.3.2"},
          {public_key,"Public key infrastructure","0.21"},
          {crypto,"CRYPTO version 2","3.2"},
          {amqp_client,"RabbitMQ AMQP Client","3.6.0"},
          {rabbit_common,[],"3.6.0"},
          {inets,"INETS  CXC 138 49","5.9.7"},
          {mnesia,"MNESIA  CXC 138 12","4.11"},
          {compiler,"ERTS  CXC 138 10","4.9.4"},
          {xmerl,"XML parser","1.3.5"},
          {syntax_tools,"Syntax tools","1.6.12"},
          {asn1,"The Erlang ASN1 compiler version 2.0.4","2.0.4"},
          {ranch,"Socket acceptor pool for TCP protocols.","1.2.1"},
          {sasl,"SASL  CXC 138 11","2.3.4"},
          {stdlib,"ERTS  CXC 138 10","1.19.4"},
          {kernel,"ERTS  CXC 138 10","2.16.4"}]},
     {os,{unix,linux}},
     {erlang_version,
         "Erlang R16B03 (erts-5.10.4) [source] [64-bit] [smp:2:2] [async-threads:64] [kernel-poll:true]\n"},
     {memory,
         [{total,55032832},
          {connection_readers,0},
          {connection_writers,0},
          {connection_channels,0},
          {connection_other,2704},
          {queue_procs,2704},
          {queue_slave_procs,0},
          {plugins,466152},
          {other_proc,18884952},
          {mnesia,60088},
          {mgmt_db,209832},
          {msg_index,52816},
          {other_ets,1342448},
          {binary,410800},
          {code,26652340},
          {atom,951441},
          {other_system,5996555}]},
     {alarms,[]},
     {listeners,[{clustering,25672,"::"},{amqp,5672,"::"}]},
     {vm_memory_high_watermark,0.4},
     {vm_memory_limit,416533708},
     {disk_free_limit,50000000},
     {disk_free,60550307840},
     {file_descriptors,
         [{total_limit,16284},
          {total_used,2},
          {sockets_limit,14653},
          {sockets_used,0}]},
     {processes,[{limit,1048576},{used,192}]},
     {run_queue,0},
     {uptime,1302},
     {kernel,{net_ticktime,60}}]

PHP:

    [04:32 AM]-[root@local]-[/etc/php5/conf.d]
    # php -v
    PHP 5.6.17-3+deb.sury.org~trusty+1 (cli)
    Copyright (c) 1997-2015 The PHP Group
    Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
        with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies

PECL:

    [04:32 AM]-[root@local]-[/etc/php5/conf.d]
    # pecl -d preferred_state=beta install amqp-1.7.0alpha2
    downloading amqp-1.7.0alpha2.tgz ...
    Starting to download amqp-1.7.0alpha2.tgz (77,809 bytes)
    ..................done: 77,809 bytes
    18 source files, building
    running: phpize
    Configuring for:
    PHP Api Version:         20131106
    Zend Module Api No:      20131226
    Zend Extension Api No:   220131226
    Set the path to librabbitmq install prefix [autodetect] :
    building in /tmp/pear/temp/pear-build-rootF0GxFf/amqp-1.7.0alpha2
    running: /tmp/pear/temp/amqp/configure --with-librabbitmq-dir
    checking for grep that handles long lines and -e... /bin/grep
    checking for egrep... /bin/grep -E
    checking for a sed that does not truncate output... /bin/sed
    checking for cc... cc
    checking whether the C compiler works... yes
    checking for C compiler default output file name... a.out
    checking for suffix of executables...
    checking whether we are cross compiling... no
    checking for suffix of object files... o
    checking whether we are using the GNU C compiler... yes
    checking whether cc accepts -g... yes
    checking for cc option to accept ISO C89... none needed
    checking how to run the C preprocessor... cc -E
    checking for icc... no
    checking for suncc... no
    checking whether cc understands -c and -o together... yes
    checking for system library directory... lib
    checking if compiler supports -R... no
    checking if compiler supports -Wl,-rpath,... yes
    checking build system type... x86_64-unknown-linux-gnu
    checking host system type... x86_64-unknown-linux-gnu
    checking target system type... x86_64-unknown-linux-gnu
    checking for PHP prefix... /usr
    checking for PHP includes... -I/usr/include/php5 -I/usr/include/php5/main -I/usr/include/php5/TSRM -I/usr/include/php5/Zend -I/usr/include/php5/ext -I/usr/include/php5/ext/date/lib
    checking for PHP extension directory... /usr/lib/php5/20131226
    checking for PHP installed headers prefix... /usr/include/php5
    checking if debug is enabled... no
    checking if zts is enabled... no
    checking for re2c... no
    configure: WARNING: You will need re2c 0.13.4 or later if you want to regenerate PHP parsers.
    checking for gawk... gawk
    checking for amqp support... yes, shared
    checking for amqp... yes, shared
    yes
    checking for amqp files in default path... found in /usr
    checking how to print strings... printf
    checking for a sed that does not truncate output... (cached) /bin/sed
    checking for fgrep... /bin/grep -F
    checking for ld used by cc... /usr/bin/ld
    checking if the linker (/usr/bin/ld) is GNU ld... yes
    checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
    checking the name lister (/usr/bin/nm -B) interface... BSD nm
    checking whether ln -s works... yes
    checking the maximum length of command line arguments... 1572864
    checking whether the shell understands some XSI constructs... yes
    checking whether the shell understands "+="... yes
    checking how to convert x86_64-unknown-linux-gnu file names to x86_64-unknown-linux-gnu format... func_convert_file_noop
    checking how to convert x86_64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
    checking for /usr/bin/ld option to reload object files... -r
    checking for objdump... objdump
    checking how to recognize dependent libraries... pass_all
    checking for dlltool... no
    checking how to associate runtime and link libraries... printf %s\n
    checking for ar... ar
    checking for archiver @FILE support... @
    checking for strip... strip
    checking for ranlib... ranlib
    checking for gawk... (cached) gawk
    checking command to parse /usr/bin/nm -B output from cc object... ok
    checking for sysroot... no
    checking for mt... mt
    checking if mt is a manifest tool... no
    checking for ANSI C header files... yes
    checking for sys/types.h... yes
    checking for sys/stat.h... yes
    checking for stdlib.h... yes
    checking for string.h... yes
    checking for memory.h... yes
    checking for strings.h... yes
    checking for inttypes.h... yes
    checking for stdint.h... yes
    checking for unistd.h... yes
    checking for dlfcn.h... yes
    checking for objdir... .libs
    checking if cc supports -fno-rtti -fno-exceptions... no
    checking for cc option to produce PIC... -fPIC -DPIC
    checking if cc PIC flag -fPIC -DPIC works... yes
    checking if cc static flag -static works... yes
    checking if cc supports -c -o file.o... yes
    checking if cc supports -c -o file.o... (cached) yes
    checking whether the cc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
    checking whether -lc should be explicitly linked in... no
    checking dynamic linker characteristics... GNU/Linux ld.so
    checking how to hardcode library paths into programs... immediate
    checking whether stripping libraries is possible... yes
    checking if libtool supports shared libraries... yes
    checking whether to build shared libraries... yes
    checking whether to build static libraries... no
    configure: creating ./config.status
    config.status: creating config.h
    config.status: executing libtool commands
    running: make
    /bin/bash /tmp/pear/temp/pear-build-rootF0GxFf/amqp-1.7.0alpha2/libtool --mode=compile cc  -I. -I/tmp/pear/temp/amqp -DPHP_ATOM_INC -I/tmp/pear/temp/pear-build-rootF0GxFf/amqp-1.7.0alpha2/include -I/tmp/pear/temp/pear-build-rootF0GxFf/amqp-1.7.0alpha2/main -I/tmp/pear/temp/amqp -I/usr/include/php5 -I/usr/include/php5/main -I/usr/include/php5/TSRM -I/usr/include/php5/Zend -I/usr/include/php5/ext -I/usr/include/php5/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /tmp/pear/temp/amqp/amqp.c -o amqp.lo
    libtool: compile:  cc -I. -I/tmp/pear/temp/amqp -DPHP_ATOM_INC -I/tmp/pear/temp/pear-build-rootF0GxFf/amqp-1.7.0alpha2/include -I/tmp/pear/temp/pear-build-rootF0GxFf/amqp-1.7.0alpha2/main -I/tmp/pear/temp/amqp -I/usr/include/php5 -I/usr/include/php5/main -I/usr/include/php5/TSRM -I/usr/include/php5/Zend -I/usr/include/php5/ext -I/usr/include/php5/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /tmp/pear/temp/amqp/amqp.c  -fPIC -DPIC -o .libs/amqp.o
    /bin/bash /tmp/pear/temp/pear-build-rootF0GxFf/amqp-1.7.0alpha2/libtool --mode=compile cc  -I. -I/tmp/pear/temp/amqp -DPHP_ATOM_INC -I/tmp/pear/temp/pear-build-rootF0GxFf/amqp-1.7.0alpha2/include -I/tmp/pear/temp/pear-build-rootF0GxFf/amqp-1.7.0alpha2/main -I/tmp/pear/temp/amqp -I/usr/include/php5 -I/usr/include/php5/main -I/usr/include/php5/TSRM -I/usr/include/php5/Zend -I/usr/include/php5/ext -I/usr/include/php5/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /tmp/pear/temp/amqp/amqp_exchange.c -o amqp_exchange.lo
    libtool: compile:  cc -I. -I/tmp/pear/temp/amqp -DPHP_ATOM_INC -I/tmp/pear/temp/pear-build-rootF0GxFf/amqp-1.7.0alpha2/include -I/tmp/pear/temp/pear-build-rootF0GxFf/amqp-1.7.0alpha2/main -I/tmp/pear/temp/amqp -I/usr/include/php5 -I/usr/include/php5/main -I/usr/include/php5/TSRM -I/usr/include/php5/Zend -I/usr/include/php5/ext -I/usr/include/php5/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /tmp/pear/temp/amqp/amqp_exchange.c  -fPIC -DPIC -o .libs/amqp_exchange.o
    /bin/bash /tmp/pear/temp/pear-build-rootF0GxFf/amqp-1.7.0alpha2/libtool --mode=compile cc  -I. -I/tmp/pear/temp/amqp -DPHP_ATOM_INC -I/tmp/pear/temp/pear-build-rootF0GxFf/amqp-1.7.0alpha2/include -I/tmp/pear/temp/pear-build-rootF0GxFf/amqp-1.7.0alpha2/main -I/tmp/pear/temp/amqp -I/usr/include/php5 -I/usr/include/php5/main -I/usr/include/php5/TSRM -I/usr/include/php5/Zend -I/usr/include/php5/ext -I/usr/include/php5/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /tmp/pear/temp/amqp/amqp_queue.c -o amqp_queue.lo
    libtool: compile:  cc -I. -I/tmp/pear/temp/amqp -DPHP_ATOM_INC -I/tmp/pear/temp/pear-build-rootF0GxFf/amqp-1.7.0alpha2/include -I/tmp/pear/temp/pear-build-rootF0GxFf/amqp-1.7.0alpha2/main -I/tmp/pear/temp/amqp -I/usr/include/php5 -I/usr/include/php5/main -I/usr/include/php5/TSRM -I/usr/include/php5/Zend -I/usr/include/php5/ext -I/usr/include/php5/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /tmp/pear/temp/amqp/amqp_queue.c  -fPIC -DPIC -o .libs/amqp_queue.o
    /bin/bash /tmp/pear/temp/pear-build-rootF0GxFf/amqp-1.7.0alpha2/libtool --mode=compile cc  -I. -I/tmp/pear/temp/amqp -DPHP_ATOM_INC -I/tmp/pear/temp/pear-build-rootF0GxFf/amqp-1.7.0alpha2/include -I/tmp/pear/temp/pear-build-rootF0GxFf/amqp-1.7.0alpha2/main -I/tmp/pear/temp/amqp -I/usr/include/php5 -I/usr/include/php5/main -I/usr/include/php5/TSRM -I/usr/include/php5/Zend -I/usr/include/php5/ext -I/usr/include/php5/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /tmp/pear/temp/amqp/amqp_connection.c -o amqp_connection.lo
    libtool: compile:  cc -I. -I/tmp/pear/temp/amqp -DPHP_ATOM_INC -I/tmp/pear/temp/pear-build-rootF0GxFf/amqp-1.7.0alpha2/include -I/tmp/pear/temp/pear-build-rootF0GxFf/amqp-1.7.0alpha2/main -I/tmp/pear/temp/amqp -I/usr/include/php5 -I/usr/include/php5/main -I/usr/include/php5/TSRM -I/usr/include/php5/Zend -I/usr/include/php5/ext -I/usr/include/php5/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /tmp/pear/temp/amqp/amqp_connection.c  -fPIC -DPIC -o .libs/amqp_connection.o
    /bin/bash /tmp/pear/temp/pear-build-rootF0GxFf/amqp-1.7.0alpha2/libtool --mode=compile cc  -I. -I/tmp/pear/temp/amqp -DPHP_ATOM_INC -I/tmp/pear/temp/pear-build-rootF0GxFf/amqp-1.7.0alpha2/include -I/tmp/pear/temp/pear-build-rootF0GxFf/amqp-1.7.0alpha2/main -I/tmp/pear/temp/amqp -I/usr/include/php5 -I/usr/include/php5/main -I/usr/include/php5/TSRM -I/usr/include/php5/Zend -I/usr/include/php5/ext -I/usr/include/php5/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /tmp/pear/temp/amqp/amqp_connection_resource.c -o amqp_connection_resource.lo
    libtool: compile:  cc -I. -I/tmp/pear/temp/amqp -DPHP_ATOM_INC -I/tmp/pear/temp/pear-build-rootF0GxFf/amqp-1.7.0alpha2/include -I/tmp/pear/temp/pear-build-rootF0GxFf/amqp-1.7.0alpha2/main -I/tmp/pear/temp/amqp -I/usr/include/php5 -I/usr/include/php5/main -I/usr/include/php5/TSRM -I/usr/include/php5/Zend -I/usr/include/php5/ext -I/usr/include/php5/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /tmp/pear/temp/amqp/amqp_connection_resource.c  -fPIC -DPIC -o .libs/amqp_connection_resource.o
    /bin/bash /tmp/pear/temp/pear-build-rootF0GxFf/amqp-1.7.0alpha2/libtool --mode=compile cc  -I. -I/tmp/pear/temp/amqp -DPHP_ATOM_INC -I/tmp/pear/temp/pear-build-rootF0GxFf/amqp-1.7.0alpha2/include -I/tmp/pear/temp/pear-build-rootF0GxFf/amqp-1.7.0alpha2/main -I/tmp/pear/temp/amqp -I/usr/include/php5 -I/usr/include/php5/main -I/usr/include/php5/TSRM -I/usr/include/php5/Zend -I/usr/include/php5/ext -I/usr/include/php5/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /tmp/pear/temp/amqp/amqp_channel.c -o amqp_channel.lo
    libtool: compile:  cc -I. -I/tmp/pear/temp/amqp -DPHP_ATOM_INC -I/tmp/pear/temp/pear-build-rootF0GxFf/amqp-1.7.0alpha2/include -I/tmp/pear/temp/pear-build-rootF0GxFf/amqp-1.7.0alpha2/main -I/tmp/pear/temp/amqp -I/usr/include/php5 -I/usr/include/php5/main -I/usr/include/php5/TSRM -I/usr/include/php5/Zend -I/usr/include/php5/ext -I/usr/include/php5/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /tmp/pear/temp/amqp/amqp_channel.c  -fPIC -DPIC -o .libs/amqp_channel.o
    /bin/bash /tmp/pear/temp/pear-build-rootF0GxFf/amqp-1.7.0alpha2/libtool --mode=compile cc  -I. -I/tmp/pear/temp/amqp -DPHP_ATOM_INC -I/tmp/pear/temp/pear-build-rootF0GxFf/amqp-1.7.0alpha2/include -I/tmp/pear/temp/pear-build-rootF0GxFf/amqp-1.7.0alpha2/main -I/tmp/pear/temp/amqp -I/usr/include/php5 -I/usr/include/php5/main -I/usr/include/php5/TSRM -I/usr/include/php5/Zend -I/usr/include/php5/ext -I/usr/include/php5/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /tmp/pear/temp/amqp/amqp_envelope.c -o amqp_envelope.lo
    libtool: compile:  cc -I. -I/tmp/pear/temp/amqp -DPHP_ATOM_INC -I/tmp/pear/temp/pear-build-rootF0GxFf/amqp-1.7.0alpha2/include -I/tmp/pear/temp/pear-build-rootF0GxFf/amqp-1.7.0alpha2/main -I/tmp/pear/temp/amqp -I/usr/include/php5 -I/usr/include/php5/main -I/usr/include/php5/TSRM -I/usr/include/php5/Zend -I/usr/include/php5/ext -I/usr/include/php5/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /tmp/pear/temp/amqp/amqp_envelope.c  -fPIC -DPIC -o .libs/amqp_envelope.o
    /tmp/pear/temp/amqp/amqp_envelope.c: In function 'convert_amqp_envelope_to_zval':
    /tmp/pear/temp/amqp/amqp_envelope.c:110:82: error: 'AMQP_DELIVERY_NONPERSISTENT' undeclared (first use in this function)
             zend_update_property_long(this_ce, envelope, ZEND_STRL("delivery_mode"), AMQP_DELIVERY_NONPERSISTENT TSRMLS_CC);
                                                                                      ^
    /tmp/pear/temp/amqp/amqp_envelope.c:110:82: note: each undeclared identifier is reported only once for each function it appears in
    /tmp/pear/temp/amqp/amqp_envelope.c: In function 'zim_amqp_envelope_class___construct':
    /tmp/pear/temp/amqp/amqp_envelope.c:200:79: error: 'AMQP_DELIVERY_NONPERSISTENT' undeclared (first use in this function)
         zend_update_property_long(this_ce, getThis(), ZEND_STRL("delivery_mode"), AMQP_DELIVERY_NONPERSISTENT TSRMLS_CC);
                                                                                   ^
    make: *** [amqp_envelope.lo] Error 1
    ERROR: `make' failed

**Comment by jtreminio** [comment]
Ok so, currently puphpet uses this repo for php 5.6: https://launchpad.net/~ondrej/+archive/ubuntu/php5-5.6

It does not have updated librabbitmq library, but this one does: https://launchpad.net/~ondrej/+archive/ubuntu/php

**Comment by jorgeandrescastro** [comment]
+1

**Comment by shembelcut** [comment]
+1
