### ISSUE TITLE
Nginx is not starting after vagrant up

### ISSUE THREAD

**Issue by Renkas** [puphpet/puphpet#2120]
For some time now I have had this problem on different setups that Nginx will not start on VM boot. There are no errors. manually running `sudo /etc/init.d/nginx start` starts nginx successfully. But I would like that Puphpet would configure this automatically - so that new developers that run the box would not have to deal with it.

I'm using latest Debian box (1-12-2015).
Vagrant 1.8.1
VirtualBox 5.0.10

Latest box config from puphpet.com

**Comment by jtreminio** [comment]
Show me your config.yaml

I've been spinning up boxes all day, they all work.

**Comment by Renkas** [comment]
Do they also work after halt/up?

I'll add conf when I'm on PC later

**Comment by Renkas** [comment]
I sent the configuration with some more info to your email address. I do not feel comfortable sharing the full conf here publicly and I could not water it down to basics just now. Hopefully you can see where the problem is now.

**Comment by vincenzo** [comment]
I am on the same config as you, @Renkas, in terms of distro, vagrant and vbox, and I am not experiencing the issue. Not sure if that may help @jtreminio in narrowing it down to a specific issue with your config, @Renkas. But I thought I'd share.

**Comment by Renkas** [comment]
I sent this already to Juan via email - but I'll add it here also so the thread is more informative.

* On first ’vagrant up’ everything works fine
* After halt and then up again – Nginx does not start.
 
It seems to me that the problem is in a synced folder. Nginx error.log contains a single row:
* 2016/01/23 12:14:52 [emerg] 1025#0: SSL_CTX_load_verify_locations("/var/www/cert/id.crt") failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/var/www/cert/id.crt','r') error:2006D080:BIO routines:BIO_new_file:no such file error:0B084002:x509 certificate routines:X509_load_cert_crl_file:system lib)

**Comment by Renkas** [comment]
Any idea for a fix? It is quite annoying ...

**Comment by PhilETaylor** [comment]
I have the same issue - my config.yaml tries to set up a SSL and nginx fails on startup, but can be manually started later over ssh. 

Error in nginx error log is:
`2016/06/14 19:12:02 [emerg] 5408#5408: BIO_new_file("/etc/nginx/nxv_2p9l0ezzfr2c.crt") failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/nginx/nxv_2p9l0ezzfr2c.crt','r') error:2006D080:BIO routines:BIO_new_file:no such file)`

example part of config.yaml is

` nxv_lbxprlvuv9a8:
            server_name: local-manage.myjoomla.com
            www_root: /var/www/public_html
            listen_port: '80'
            index_files:
                - index.php
            client_max_body_size: 1m
            ssl: '1'
            ssl_cert: /var/www/application/configs/ssl/2015-2016/wildcard.chained.crt
            ssl_key: /var/www/application/configs/ssl/2015-2016/wildcard.key
            ssl_port: '443'
            ssl_protocols: 'TLSv1 TLSv1.1 TLSv1.2'
            ssl_ciphers: 'ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:ECDH+3DES:DH+3DES:RSA+AESGCM:RSA+AES:RSA+3DES:!aNULL:!MD5:!DSS;'
            rewrite_to_https: '1'
            spdy: '1'
            locations:
                nxvl_pe2ud4ukjwnw:
                    location: /
                    try_files:
                        - $uri
                        - $uri/
                        - '/index.php?$query_string'
                    fastcgi: '127.0.0.1:9000'
                    fastcgi_index: index.php
                    fastcgi_split_path: '^(.+\.php)(/.*)$'
                    fast_cgi_params_extra:
                        - 'SCRIPT_FILENAME /var/www/public_html$fastcgi_script_name'
                        - 'APPLICATION_ENV development'
                        - 'QUERY_STRING $query_string'
                        - 'REQUEST_METHOD $request_method'
                        - 'CONTENT_TYPE $content_type'
                        - 'REMOTE_ADDR $remote_addr'
                        - 'MY_R_ADDR $http_x_forwarded_for'
                        - 'REAL-IP $remote_addr'
                        - 'FORWARDED-FOR $proxy_add_x_forwarded_for'
                    proxy: ''
                    proxy_redirect: ''
                nxvl_xljcgfomupt1:
                    location: '~.*\.(ttf|svg|eot|woff|woff2|3gp|gif|jpg|jpeg|png|ico|wmv|avi|asf|asx|mpg|mpeg|mp4|pls|mp3|mid|wav|swf|flv|html|htm|txt|js|css|exe|zip|tar|rar|gz|tgz|bz2|uha|7z|doc|docx|xls|xlsx|pdf|iso)$'
                    fastcgi: ''
                    fastcgi_index: ''
                    fastcgi_split_path: ''
                    proxy: ''
                    proxy_redirect: ''`

**Comment by jtreminio** [comment]
The issue is the nginx module creates a symlink to the location of the SSL key.

The easiest way around this is to create a simple exec-preprovision script that copies your SSL certs to the VM's `/etc/ssl/private/`, then the symlinks will never break.
