### ISSUE TITLE
Puphpet can't be used in China

### ISSUE THREAD

**Issue by Master-Xia** [puphpet/puphpet#2126]
I think because of the GFW.
Many softwares(such as ruby) can't be download.
How to solve this question?

error:
==> local: ERROR:  Could not find a valid gem 'deep_merge' (>= 0), here is why:
==> local:           Unable to download data from https://rubygems.org/ - SSL_connect SYSCALL returned=5 errno=0 state=S
SLv2/v3 read server hello A (https://rubygems.global.ssl.fastly.net/latest_specs.4.8.gz)
==> local: ERROR:  Could not find a valid gem 'activesupport' (>= 0), here is why:
==> local:           Unable to download data from https://rubygems.org/ - SSL_connect SYSCALL returned=5 errno=0 state=S
SLv2/v3 read server hello A (https://rubygems.global.ssl.fastly.net/latest_specs.4.8.gz)
==> local: ERROR:  Could not find a valid gem 'vine' (>= 0), here is why:
==> local:           Unable to download data from https://rubygems.org/ - SSL_connect SYSCALL returned=5 errno=0 state=S
SLv2/v3 read server hello A (https://rubygems.global.ssl.fastly.net/latest_specs.4.8.gz)

config.yaml:

    vagrantfile:
        target: local
        vm:
            box: puphpet/centos65-x64
            box_url: puphpet/centos65-x64
            hostname: drush
            memory: '1024'
            cpus: '1'
            chosen_provider: virtualbox
            box_version: ''
            network:
                private_network: 192.168.56.101
                forwarded_port:
                    vflnp_18bdh41ogfng:
                        host: '7158'
                        guest: '22'
            post_up_message: ''
            provider:
                virtualbox:
                    modifyvm:
                        natdnshostresolver1: false
                    showgui: '0'
                vmware:
                    numvcpus: 1
                parallels:
                    use_linked_clone: '0'
                    check_guest_tools: '0'
                    update_guest_tools: '0'
            provision:
                puppet:
                    manifests_path: puphpet/puppet/manifests
                    module_path: puphpet/puppet/modules
                    options:
                        - '--verbose'
                        - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
            synced_folder:
                vflsf_dxd7l2wp7r7l:
                    source: ./
                    target: /var/www
                    sync_type: default
                    smb:
                        smb_host: ''
                        smb_username: ''
                        smb_password: ''
                        mount_options:
                            dir_mode: '0775'
                            file_mode: '0664'
                    rsync:
                        args:
                            - '--verbose'
                            - '--archive'
                            - '-z'
                        exclude:
                            - .vagrant/
                            - .git/
                        auto: 'true'
                    owner: www-data
                    group: www-data
            usable_port_range:
                start: 10200
                stop: 10500
        ssh:
            host: null
            port: null
            private_key_path: null
            username: vagrant
            guest_port: null
            keep_alive: true
            forward_agent: false
            forward_x11: false
            shell: 'bash -l'
            insert_key: false
        vagrant:
            host: detect
        proxy:
            http: ''
            https: ''
            ftp: ''
            no_proxy: ''
            enabled: ''
    server:
        install: '1'
        packages:
            - vim-common
            - htop
    users_groups:
        install: '1'
        groups: {  }
        users: {  }
    locale:
        install: '1'
        settings:
            default_locale: zh_CN.UTF-8
            locales:
                - en_GB.UTF-8
                - en_US.UTF-8
                - zh_CN.UTF-8
            timezone: Asia/Shanghai
    firewall:
        install: '1'
        rules: {  }
    cron:
        install: '1'
        jobs: {  }
    nginx:
        install: '0'
        settings:
            default_vhost: 1
            proxy_buffer_size: 128k
            proxy_buffers: '4 256k'
            proxy_connect_timeout: 600s
            proxy_send_timeout: 600s
            proxy_read_timeout: 600s
            names_hash_bucket_size: 128
        upstreams: {  }
        vhosts:
            nxv_wrd5e1dedraf:
                server_name: awesome.dev
                server_aliases:
                    - www.awesome.dev
                www_root: /var/www/awesome
                listen_port: '80'
                index_files:
                    - index.html
                    - index.htm
                    - index.php
                client_max_body_size: 1m
                ssl: '0'
                ssl_cert: ''
                ssl_key: ''
                ssl_port: '443'
                ssl_protocols: ''
                ssl_ciphers: ''
                rewrite_to_https: '1'
                spdy: '1'
                locations:
                    nxvl_oce1bx0rq1e8:
                        location: /
                        autoindex: 'off'
                        internal: 'false'
                        try_files:
                            - $uri
                            - $uri/
                            - /index.php$is_args$args
                        fastcgi: ''
                        fastcgi_index: ''
                        fastcgi_split_path: ''
                        proxy: ''
                        proxy_redirect: ''
                    nxvl_q7hj0c5beide:
                        location: '~ \.php$'
                        autoindex: 'off'
                        internal: 'false'
                        try_files:
                            - $uri
                            - $uri/
                            - /index.php$is_args$args
                        fastcgi: '127.0.0.1:9000'
                        fastcgi_index: index.php
                        fastcgi_split_path: '^(.+\.php)(/.*)$'
                        fast_cgi_params_extra:
                            - 'SCRIPT_FILENAME $request_filename'
                            - 'APP_ENV dev'
                        set:
                            - '$path_info $fastcgi_path_info'
                        proxy: ''
                        proxy_redirect: ''
        proxies: {  }
    apache:
        install: '1'
        settings:
            version: 2.4
            user: www-data
            group: www-data
            default_vhost: true
            manage_user: false
            manage_group: false
            sendfile: 0
        modules:
            - proxy_fcgi
            - rewrite
        vhosts:
            av_puekm460nx2q:
                servername: drush.xiahonglong.com
                docroot: /var/www/drush
                port: '80'
                setenv:
                    - 'APP_ENV dev'
                setenvif:
                    - 'Authorization "(.*)" HTTP_AUTHORIZATION=$1'
                custom_fragment: ''
                ssl: '0'
                ssl_cert: ''
                ssl_key: ''
                ssl_chain: ''
                ssl_certs_dir: ''
                ssl_protocol: ''
                ssl_cipher: ''
                directories:
                    avd_zmedkzr2wmdk:
                        path: /var/www/drush
                        options:
                            - Indexes
                            - FollowSymlinks
                            - MultiViews
                        allow_override:
                            - All
                        require:
                            - 'all granted'
                        custom_fragment: ''
                        files_match:
                            avdfm_lsq4d6mjx4bo:
                                path: \.php$
                                sethandler: 'proxy:fcgi://127.0.0.1:9000'
                                custom_fragment: ''
                                provider: filesmatch
                        provider: directory
    php:
        install: '1'
        settings:
            version: '56'
        modules:
            php:
                - cli
                - intl
            pear: {  }
            pecl: {  }
        ini:
            display_errors: 'On'
            error_reporting: '-1'
            session.save_path: /var/lib/php/session
            date.timezone: UTC
        fpm_ini:
            error_log: /var/log/php-fpm.log
        fpm_pools:
            phpfp_qv0weuhnw8m7:
                ini:
                    prefix: www
                    listen: '127.0.0.1:9000'
                    security.limit_extensions: .php
                    user: www-user
                    group: www-data
        composer: '1'
        composer_home: ''
    xdebug:
        install: '0'
        settings:
            xdebug.default_enable: '1'
            xdebug.remote_autostart: '0'
            xdebug.remote_connect_back: '1'
            xdebug.remote_enable: '1'
            xdebug.remote_handler: dbgp
            xdebug.remote_port: '9000'
    blackfire:
        install: '0'
        settings:
            server_id: ''
            server_token: ''
            agent:
                http_proxy: ''
                https_proxy: ''
                log_file: stderr
                log_level: '1'
            php:
                agent_timeout: '0.25'
                log_file: ''
                log_level: '1'
    xhprof:
        install: '0'
    wpcli:
        install: '0'
        version: v0.21.1
    drush:
        install: '1'
        version: 6.3.0
    ruby:
        install: '1'
        versions:
            rv_dee97a1dnyf8:
                default: '1'
                bundler: '1'
                version: 1.9.3
    python:
        install: '1'
        packages: {  }
        versions: {  }
    nodejs:
        install: '0'
        settings:
            version: '5'
        npm_packages: {  }
    hhvm:
        install: '0'
        nightly: 0
        composer: '1'
        composer_home: ''
        settings: {  }
        server_ini:
            hhvm.server.host: 127.0.0.1
            hhvm.server.port: '9000'
            hhvm.log.use_log_file: '1'
            hhvm.log.file: /var/log/hhvm/error.log
        php_ini:
            display_errors: 'On'
            error_reporting: '-1'
            date.timezone: UTC
    mariadb:
        install: '1'
        settings:
            version: '10.1'
            root_password: fdSfe78df2
            override_options: {  }
        adminer: 0
        users:
            mariadbnu_z2xpoce7h56a:
                name: drush
                password: Sdl83tdlf3
        databases:
            mariadbnd_whjrq4jxd8kq:
                name: drush
                sql: ''
        grants:
            mariadbng_fd8qhtkjyfcj:
                user: drush
                table: 'drush.*'
                privileges:
                    - ALL
    mysql:
        install: '0'
        settings:
            version: '5.5'
            root_password: fdSfe78df2
            override_options: {  }
        adminer: 0
        users:
            mysqlnu_tjxous86gvkf:
                name: dbuser
                password: '123'
        databases:
            mysqlnd_fzn5fmd1hf6l:
                name: dbname
                sql: ''
        grants:
            mysqlng_4szpsipcv0u5:
                user: dbuser
                table: '*.*'
                privileges:
                    - ALL
    postgresql:
        install: '0'
        settings:
            global:
                encoding: UTF8
                version: '9.4'
            server:
                postgres_password: '123'
        databases: {  }
        users: {  }
        grants: {  }
        adminer: 0
    mongodb:
        install: '0'
        settings:
            auth: 1
            bind_ip: 127.0.0.1
            port: '27017'
        globals:
            version: 2.6.0
        databases: {  }
    redis:
        install: '0'
        settings:
            port: '6379'
    sqlite:
        install: '0'
        adminer: 0
        databases: {  }
    mailhog:
        install: '0'
        settings:
            smtp_ip: 0.0.0.0
            smtp_port: 1025
            http_ip: 0.0.0.0
            http_port: '8025'
            path: /usr/local/bin/mailhog
    beanstalkd:
        install: '0'
        settings:
            listenaddress: 0.0.0.0
            listenport: '11300'
            maxjobsize: '65535'
            maxconnections: '1024'
            binlogdir: /var/lib/beanstalkd/binlog
            binlogfsync: null
            binlogsize: '10485760'
        beanstalk_console: 0
    rabbitmq:
        install: '0'
        settings:
            port: '5672'
        users: {  }
        vhosts: {  }
        plugins: {  }
    elastic_search:
        install: '0'
        settings:
            version: 2.1.0
            java_install: true
        instances:
            esi_yoznajfr0xoz:
                name: es-01
    solr:
        install: '0'
        settings:
            version: 4.10.2
            port: '8984'

**Comment by lichnow** [comment]
我用这个开发symfony，很不错的，为什么会不能安装呢？

**Comment by Master-Xia** [comment]
你修改了ruby安装包的下载位置了吗，按照这个路径是下载不了的。

**Comment by jtreminio** [comment]
Use a proxy? Not really sure otherwise.

**Comment by jsbba** [comment]
我跟你一样，兄弟
