### ISSUE TITLE
Issues when running vagrant up

### ISSUE THREAD

**Issue by acid24** [puphpet/puphpet#213]
Hi,

First of all some info about my distro:

$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 12.04.3 LTS
Release:    12.04
Codename:   precise

$ dpkg -l | grep vagrant
ii  vagrant                                     1:1.3.5

$ dpkg -l | grep virtualbox
ii  virtualbox-4.2                              4.2.18-88780~Ubuntu~precise

I downloaded the zip file, extracted, cd to the extracted directory and ran vagrant up.

I encountered some errors related to paths not found which I don't know how to fix. The output of the vagrant up command below.

$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
[default] Importing base box 'squeeze64'...
[default] Matching MAC address for NAT networking...
[default] Setting the name of the VM...
[default] Clearing any previously set forwarded ports...
Pruning invalid NFS exports. Administrator privileges will be required...
[sudo] password for myusername: 
[default] Creating shared folders metadata...
[default] Clearing any previously set network interfaces...
[default] Preparing network interfaces based on configuration...
[default] Forwarding ports...
[default] -- 22 => 2222 (adapter 1)
[default] Running 'pre-boot' VM customizations...
[default] Booting VM...
[default] Waiting for machine to boot. This may take a few minutes...
[default] Machine booted and ready!
[default] Configuring and enabling network interfaces...
[default] Mounting shared folders...
[default] -- /tmp/vagrant-puppet/manifests
[default] Exporting NFS shared folders...
Preparing to edit /etc/exports. Administrator privileges will be required...
nfsd running
[default] Mounting NFS shared folders...
[default] Running provisioner: shell...
[default] Running: /tmp/vagrant-shell20131023-11644-mlv133
stdin: is not a tty
/bin/bash: /vagrant/shell/os-detect.sh: No such file or directory
/bin/bash: /vagrant/shell/os-detect.sh: No such file or directory
cat: /vagrant/shell/self-promotion.txt: No such file or directory
Created directory /.puphpet-stuff
[default] Running provisioner: shell...
[default] Running: /tmp/vagrant-shell20131023-11644-aelrvp
stdin: is not a tty
/bin/bash: /vagrant/shell/os-detect.sh: No such file or directory
/bin/bash: /vagrant/shell/os-detect.sh: No such file or directory
[default] Running provisioner: shell...
[default] Running: /tmp/vagrant-shell20131023-11644-jt0kzj
stdin: is not a tty
/bin/bash: /vagrant/shell/os-detect.sh: No such file or directory
/bin/bash: /vagrant/shell/os-detect.sh: No such file or directory
Installing git
Failed to fetch http://security.debian.org/pool/updates/main/c/curl/libcurl3-gnutls_7.21.0-2.1+squeeze2_amd64.deb  404  Not Found [IP: 195.20.242.89 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
Finished installing git
Created directory /etc/puppet/
cp: cannot stat `/vagrant/puppet/Puppetfile': No such file or directory
Copied Puppetfile
Installing librarian-puppet
Finished installing librarian-puppet
Running initial librarian-puppet
/usr/lib/ruby/1.8/pathname.rb:763:in`read': No such file or directory - /etc/puppet/Puppetfile (Errno::ENOENT)
    from /usr/lib/ruby/1.8/pathname.rb:763:in `read'
    from /usr/lib/ruby/gems/1.8/gems/librarian-puppet-0.9.10/vendor/librarian/lib/librarian/specfile.rb:14:in`read'
    from /usr/lib/ruby/gems/1.8/gems/librarian-puppet-0.9.10/vendor/librarian/lib/librarian/action/resolve.rb:12:in `run'
    from /usr/lib/ruby/gems/1.8/gems/librarian-puppet-0.9.10/vendor/librarian/lib/librarian/cli.rb:161:in`resolve!'
    from /usr/lib/ruby/gems/1.8/gems/librarian-puppet-0.9.10/lib/librarian/puppet/cli.rb:63:in `install'
    from /usr/lib/ruby/gems/1.8/gems/thor-0.18.1/lib/thor/command.rb:27:in`**send**'
    from /usr/lib/ruby/gems/1.8/gems/thor-0.18.1/lib/thor/command.rb:27:in `run'
    from /usr/lib/ruby/gems/1.8/gems/thor-0.18.1/lib/thor/invocation.rb:120:in`invoke_command'
    from /usr/lib/ruby/gems/1.8/gems/thor-0.18.1/lib/thor.rb:363:in `dispatch'
    from /usr/lib/ruby/gems/1.8/gems/thor-0.18.1/lib/thor/base.rb:439:in`start'
Finished running initial librarian-puppet
    from /usr/lib/ruby/gems/1.8/gems/librarian-puppet-0.9.10/vendor/librarian/lib/librarian/cli.rb:29:in `bin!'
    from /usr/lib/ruby/gems/1.8/gems/librarian-puppet-0.9.10/bin/librarian-puppet:9
    from /usr/bin/librarian-puppet:19:in`load'
    from /usr/bin/librarian-puppet:19
[default] Running provisioner: puppet...
Running Puppet with default.pp...
stdin: is not a tty
Error: Could not parse application options: invalid option: --parser
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

FACTER_ssh_username='vagrant' puppet apply --verbose --hiera_config /vagrant/hiera.yaml --parser future --manifestdir /tmp/vagrant-puppet/manifests --detailed-exitcodes /tmp/vagrant-puppet/manifests/default.pp || [ $? -eq 2 ]

Stdout from the command:

Stderr from the command:

stdin: is not a tty
Error: Could not parse application options: invalid option: --parser

Please help.

**Comment by dm-cracked-sean-knight** [comment]
https://github.com/Varying-Vagrant-Vagrants/VVV/issues/517 look for the comment from twisty7867.  You have to remove the "mesg n" from /root/.profile
