### ISSUE TITLE
i don't see my VM in VirtualBox

### ISSUE THREAD

**Issue by moumene23** [puphpet/puphpet#2132]
The " VM was generated successfully" but  they don't appear on Virtual box

<code>
$ vagrant up
Bringing machine 'local' up with 'virtualbox' provider...
==> local: Checking if box 'puphpet/ubuntu1404-x64' is up to date...
==> local: Clearing any previously set forwarded ports...
==> local: Fixed port collision for 22 => 2222. Now on port 10200.
==> local: Clearing any previously set network interfaces...
==> local: Preparing network interfaces based on configuration...
    local: Adapter 1: nat
    local: Adapter 2: hostonly
==> local: Forwarding ports...
    local: 22 (guest) => 6716 (host) (adapter 1)
    local: 22 (guest) => 10200 (host) (adapter 1)
==> local: Running 'pre-boot' VM customizations...
==> local: Booting VM...
==> local: Waiting for machine to boot. This may take a few minutes...
    local: SSH address: 127.0.0.1:10200
    local: SSH username: vagrant
    local: SSH auth method: private key
==> local: Machine booted and ready!
GuestAdditions seems to be installed (5.0.10) correctly, but not running.
==> local: Checking for guest additions in VM...
==> local: Checking for host entries
==> local: adding to (C:/WINDOWS/system32/drivers/etc/hosts) : 192.168.56.101   local.puphpet   # VAGRANT: xxxxxxxxxxxxxxxxxxxxxxxxxxxxx(local) / xxxxxxxxxxxxxxxxxxxxxxxxxxxxx
==> local: Setting hostname...
==> local: Configuring and enabling network interfaces...
==> local: Mounting shared folders...
    local: /var/www => D:/vagrant_box/my_app
    local: /vagrant => D:/vagrant_box/my_app
    local: /tmp/vagrant-puppet/modules-xxxxxxxxxxxxxxxxxxxxxxxxxxxxx => D:/vagrant_box/my_app/puphpet/puppet/modules
    local: /tmp/vagrant-puppet/manifests-xxxxxxxxxxxxxxxxxxxxxxxxxxxxx => D:/vagrant_box/my_app/puphpet/puppet/manifests
==> local: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> local: flag to force provisioning. Provisioners marked to run always will still run.
==> local: Running provisioner: shell...
    local: Running: C:/Users/me/AppData/Local/Temp/vagrant-shellxxxxxxxxxxxxxxxxxxxxxxxxxxxxx-jqxnt0.sh
==> local: Running files in files/startup-once
==> local: Finished running files in files/startup-once
==> local: To run again, delete hashes you want rerun in /.puphpet-stuff/startup-once-ran or the whole file to rerun all
==> local: Running files in files/startup-always
==> local: Finished running files in files/startup-always
==> local: Running provisioner: shell...
    local: Running: C:/Users/me/AppData/Local/Temp/vagrant-shellxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.sh
==> local: Running files in files/startup-once-unprivileged
==> local: Finished running files in files/startup-once-unprivileged
==> local: To run again, delete hashes you want rerun in /.puphpet-stuff/startup-once-unprivileged-ran or the whole file to rerun all
==> local: Running files in files/startup-always-unprivileged
==> local: Finished running files in files/startup-always-unprivileged
</code>

**Comment by jtreminio** [comment]
This wouldn't be a puphpet issue - it would be either vagrant or virtualbox.

Make sure you're all up to date and try again.

Or, `vagrant ssh` to get inside your VM without the GUI.

**Comment by moumene23** [comment]
waw a so  fast reply ...
ok i'll try without gui ...but why only this one don't apear ...i'll see

**Comment by moumene23** [comment]
look like good in with vagrant ssh
$ vagrant ssh
Welcome to Ubuntu 14.04.3 LTS (GNU/Linux 3.19.0-25-generic x86_64)

 * Documentation:  https://help.ubuntu.com/
----------------------------------------------------------------
  Ubuntu 14.04.3 LTS                          built 2015-12-01
----------------------------------------------------------------

[07:07 PM]-[vagrant@local]-[~]
