### ISSUE TITLE
Can't set a local drive other than C: on windows host since Vagrant 1.8

### ISSUE THREAD

**Issue by schwipps** [puphpet/puphpet#2136]
Hi,

I've jus upgraded to Vagrant 1.8.
As a test that everything's still fine, I tried to reload my VM... then faced the following error message : 

> There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["sharedfolder", "add", "4891......62", "--name", "bY33sdqfjGvO2", "--hostpath", "D:\\"]

Stderr: VBoxManage.exe: error: Shared folder path 'D:"' is not absolute
VBoxManage.exe: error: Details: code E_INVALIDARG (0x80070057), component SharedFolderWrap, interface ISharedFolder, callee IUnknown
VBoxManage.exe: error: Context: "CreateSharedFolder(Bstr(name).raw(), Bstr(hostpath).raw(), fWritable, fAutoMount)" at line 1020 of file VBoxManageMisc.cpp

I can't connect anymore any different local drive than C: from my Windows host. Let's say the drive I'd like to connect is D, I've tried many syntaxes combinations, with ou without ' or slashes and back slashes, before and after the drive letter... Without any luck yet.
As this problem appeared when I upgraded Vagrant, it's probably Vagrant related.
However, the syntax in the yaml file often seems quite different, so I rather try my luck here...

**Comment by jtreminio** [comment]
Hi, this isn't a puphpet issue. Please open a ticket with vagrant or virtualbox, I can't really help you at all.

**Comment by schwipps** [comment]
[Done](https://github.com/mitchellh/vagrant/issues/6947)
