### ISSUE TITLE
vagrant up stopping after php5-fpm refresh

### ISSUE THREAD

**Issue by jloosli** [puphpet/puphpet#2137]
I have a puphpet project that I haven't used for about 6 months. I dusted it off and ran into issues that looked like it was related to mysql 5.6. I switched the config.yaml file to mysql 5.5 and it seemed to run fairly well, but consistently dies after what looks to be the xdebug installation and the subsequent php5-fpm restart. 

In the attached dropbox link, I have my config.yaml file, the output from vagrant up, and the debug output from vagrant up --debug (only the last part that was remaining in my buffer), and the state.yaml file that vagrant-up log talked about as it exited. If you have any idea on what I'm missing or what needs to be tweaked, I'd appreciate any direction.

https://www.dropbox.com/sh/0t87fm7jn86zvu5/AAAo6BjI5N7KnyBDrycnXNRva?dl=0

**Comment by jtreminio** [comment]
Have you considered upgrading the archive? You can drag-drop your config.yaml into the website and it'll autofill all your previous settings.

Just double check to make sure everything looks sane.

Download the new archive and you should be good to go.
