### ISSUE TITLE
how to migrate to non-vagrant/non-virtual OS and run provisioner

### ISSUE THREAD

**Issue by flowjo-sethd** [puphpet/puphpet#2138]
I'd like to capture the components of puphpet minus any vagrant or vm files/configs so that I can run the same provisioner on test and production servers. Can you clarify what is needed to make this happen? I really enjoy using puphpet for dev and would like to not have to rewrite the provisioning components.

**Comment by jtreminio** [comment]
This works for me, customize it to your needs:

    FACTER_fqdn='local.puphpet' FACTER_ssh_username='vagrant' \
      FACTER_provisioner_type='virtualbox'  puppet apply --verbose \
      --hiera_config /vagrant/puphpet/puppet/hiera.yaml \
      --modulepath '/vagrant/puphpet/puppet/modules' \
      --detailed-exitcodes /vagrant/puphpet/puppet/manifests/
