### ISSUE TITLE
sed: can't read /vagrant/puphpet/shell/*.sh: No such file or director

### ISSUE THREAD

**Issue by padomu** [puphpet/puphpet#2139]
Edit 2: I think it was a vbox problem, I updated vbox again (I already had v5 something) - seems to work now. I'm now on http://download.virtualbox.org/virtualbox/5.0.14/VirtualBox-5.0.14-105127-Win.exe

I generated a Vagrant config file using www.puphpet.com, which usually works great, but now it's just not working at all.

Here's the config: http://pastebin.com/Mw1Nhq3s

```
    Bringing machine 'local' up with 'virtualbox' provider...
    ==> local: Importing base box 'puphpet/debian75-x64'...
    
    [KProgress: 10%
    [KProgress: 20%
    [KProgress: 30%
    [KProgress: 40%
    [KProgress: 50%
    [KProgress: 60%
    [KProgress: 70%
    [KProgress: 80%
    [KProgress: 90%
    [K==> local: Matching MAC address for NAT networking...
    ==> local: Checking if box 'puphpet/debian75-x64' is up to date...
    ==> local: Setting the name of the VM: puphpet_local_1454160881819_41383
    ==> local: Clearing any previously set network interfaces...
    ==> local: Preparing network interfaces based on configuration...
        local: Adapter 1: nat
        local: Adapter 2: hostonly
    ==> local: Forwarding ports...
        local: 22 (guest) => 5095 (host) (adapter 1)
        local: 22 (guest) => 2222 (host) (adapter 1)
    ==> local: Running 'pre-boot' VM customizations...
    ==> local: Booting VM...
    ==> local: Waiting for machine to boot. This may take a few minutes...
        local: SSH address: 127.0.0.1:2222
        local: SSH username: vagrant
        local: SSH auth method: private key
        local: Warning: Remote connection disconnect. Retrying...
        local: Warning: Remote connection disconnect. Retrying...
    ==> local: Machine booted and ready!
    ==> local: Checking for guest additions in VM...
    ==> local: Setting hostname...
    ==> local: Configuring and enabling network interfaces...
    ==> local: Mounting shared folders...
        local: /var/www => C:/Users/Foo/devserver

    The following SSH command responded with a non-zero exist status.
    Vagrant assumes that this means the command failed!
    
    chwon `id -u www-data`:`id -g www-data` /var/www
    
    Stdout from the command:
    
    Stderr from the command:
    stdin: is not a tty
    chown: changing ownership of `/var/www`:not a directory

    The following SSH command responded with a non-zero exist status.
    Vagrant assumes that this means the command failed!
    
    chwon `id -u www-data`:`id -g www-data` /var/www
    
    Stdout from the command:
    
    Stderr from the command:
    stdin: is not a tty
    chown: changing ownership of `/var/www`:not a directory
```

I have no idea where's the problem. Vagrant installs GuestAddition v5. Vbox is v5. I installed git and added it to the env vars so that vagrant ssh works. I was always able to connect via 127.0.0.1:2222 or 192.168.56.101:22 via ssh to the vbox.

Just the tools, LAMP etc. are missing and I have no idea why. I mena, I have no Idea why the installationprocess doesn't get started. :/

I'm on Win 8.1

Also:

```
    C:\path>vagrant provision
    ==> local: Running provisioner: shell...
        local: Running: inline script
    ==> local: stdin: is not a tty
    ==> local: sed: can't read /vagrant/puphpet/shell/*.sh: No such file or directory
    The SSH command responded with a non-zero exit status. Vagrant
    assumes that this means the command failed. The output for this command
    should be in the log above. Please read the output to determine what
    went wrong.
```

I already checked most of the issues here but I just can't find the problem :(

Edit: /home/vagrant is empty on the box - I always thought the path /vagrant/puphpet/shell is on the host but maybe it's a mounting problem?

**Comment by mattsnowboard** [comment]
I'm getting that error you mentioned in the title:

sed: can't read /vagrant/puphpet/shell/*.sh: No such file or directory

I have the same 5.0.14 VirtualBox version. I tried rebooting after the install. What other steps did you need to do? Should I repair the install?

I don't have a /vagrant directory on my guest, so something went wrong.

**Comment by padomu** [comment]
First I though it's an SSH problem. I thought, that vagrant wasn't able to SSH into my VM and thus nothing got installed. So I installed GIT and added GIT to the env var of windows. So that vagrant ssh worked. See http://blog.osteel.me/posts/2015/01/25/how-to-use-vagrant-on-windows.html

That didn't help. Because I deleted my VM's via the VBox GUI, I thought, maybe that was a bad idea and started googling how to clean up vagrant's info about my VM. I did: vagrant global-status to see what VM's are cached - I then updated the cache with vagrant global-status --prune

I also didn't rename the puphpet folder (still don't think that it does matter, but yeah, why take the risk :P)

Still same error. I then looked up what errors I get if I do vagrant provision (after the failed vagrant up) - that gave me an error, don't know which one anymore, hmm. But it wasn't something new. But I then thought: Maybe the problem is that the vagrant folders aren't mounted, which actually was the problem.

So I did mount if by hand with: sudo mount vboxsf vagrant /home/vagrant (the vagrant folder should be added to shared folders in vbox) - anyway, now, when doing vagrant provision, it gives you an ssh auth failure because the ssh keys aren't generated yet. I think you could generate them yourself and I guess you'd also have to set /home/vagrant to be i nthe group vagrant and user vagrant - that didn't work for me because it said there is no such user.

Anyway, I then thought: Ah, why not just update vbox... :P  Did that and it worked.

Your problem is, I guess, that the shared folders don't get mounted. Maybe check vbox, vagrant for updates and then rebuild your puphpet file.

**Comment by jtreminio** [comment]
> Ah, why not just update vbox... :P Did that and it worked.

Great!
