### ISSUE TITLE
Evaluation Error: Error while evaluating a Function Call, each(): wrong argument type

### ISSUE THREAD

**Issue by StudioMaX** [puphpet/puphpet#2142]
```
==> local: To run again, delete hashes you want rerun in /.puphpet-stuff/exec-preprovision-ran or the whole file to rerun all
==> local: Running files in files/
==> local: Finished running files in files/
==> local: Running provisioner: puppet...
==> local: Running Puppet with ...
==> local: Info: Loading facts
==> local: Info: Loading facts
==> local: Info: Loading facts
==> local: Info: Loading facts
==> local: Info: Loading facts
==> local: Info: Loading facts
==> local: Info: Loading facts
==> local: Info: Loading facts
==> local: Info: Loading facts
==> local: Info: Loading facts
==> local: Info: Loading facts
==> local: Info: Loading facts
==> local: Info: Loading facts
==> local: Error: Evaluation Error: Error while evaluating a Function Call, each(): wrong argument type (NilClass; must be something enumerable. at /tmp/vagrant-puppet/manifests-75f35e3bc7e32744860c4bb229c88812/Php.pp:100:3 on node local.puphpet
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

Process finished with exit code 1
```

To fix this change https://github.com/puphpet/puphpet/blob/master/archive/puphpet/puppet/manifests/Php.pp#L100 to
`each( $php['modules']['php'] ) |$name| {`

**Comment by Jomaanro** [comment]
That fixes the php error, but after that it fails on redis:

Error: Could not find dependency Class[Php::Devel] for Package[php5-redis]

**Comment by nicolasluishuber** [comment]
Same issue here!

**Comment by mkdeddens** [comment]
Same issue here but different package, fixed the error on Php.pp line 100, then got this:

`Error: Could not find dependency Class[Php::Devel] for Package[php5-sqlite] at /tmp/vagrant-puppet/modules-7b57fa934e6386efe98cf161889408f3/puphpet/manifests/php/pecl.pp:137`

**Comment by emiliomg** [comment]
Same issue here :(

**Comment by tinobreg** [comment]
Same problem here 

`vagrantfile:
    target: local
    vm:
        box: puphpet/ubuntu1404-x64
        box_url: puphpet/ubuntu1404-x64
        hostname: tinobreg.puphpet
        memory: '512'
        cpus: '1'
        chosen_provider: virtualbox
        box_version: ''
        network:
            private_network: 192.168.77.101
            forwarded_port:
                vflnp_y2cezgf90guj:
                    host: '7987'
                    guest: '22'
        post_up_message: ''
        provider:
            virtualbox:
                modifyvm:
                    natdnshostresolver1: false
                showgui: '0'
            vmware:
                numvcpus: 1
            parallels:
                use_linked_clone: '0'
                check_guest_tools: '0'
                update_guest_tools: '0'
        provision:
            puppet:
                manifests_path: puphpet/puppet/manifests
                module_path: puphpet/puppet/modules
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
        synced_folder:
            vflsf_45wpvktdbr88:
                source: ./
                target: /var/www
                sync_type: default
                smb:
                    smb_host: ''
                    smb_username: ''
                    smb_password: ''
                    mount_options:
                        dir_mode: '0775'
                        file_mode: '0664'
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    exclude:
                        - .vagrant/
                        - .git/
                    auto: 'true'
                owner: www-data
                group: www-data
        usable_port_range:
            start: 10200
            stop: 10500
    ssh:
        host: null
        port: null
        private_key_path: null
        username: vagrant
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'
        insert_key: false
    vagrant:
        host: detect
    proxy:
        http: ''
        https: ''
        ftp: ''
        no_proxy: ''
        enabled: ''
server:
    install: '1'
    packages:
        - vim
        - htop
users_groups:
    install: '1'
    groups: {  }
    users: {  }
locale:
    install: '1'
    settings:
        default_locale: en_US.UTF-8
        locales:
            - en_GB.UTF-8
            - en_US.UTF-8
        timezone: UTC
firewall:
    install: '1'
    rules: {  }
cron:
    install: '1'
    jobs: {  }
nginx:
    install: '1'
    settings:
        default_vhost: 1
        proxy_buffer_size: 128k
        proxy_buffers: '4 256k'
        proxy_connect_timeout: 600s
        proxy_send_timeout: 600s
        proxy_read_timeout: 600s
        names_hash_bucket_size: 128
    upstreams: {  }
    vhosts:
        nxv_sc80qwutmyhf:
            server_name: tinobreg.dev
            server_aliases:
                - www.tinobreg.dev
            www_root: /var/www/site
            listen_port: '80'
            index_files:
                - index.html
                - index.htm
                - index.php
            client_max_body_size: 1m
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_port: '443'
            ssl_protocols: ''
            ssl_ciphers: ''
            rewrite_to_https: '1'
            spdy: '1'
            locations:
                nxvl_pxm42lvhlxmk:
                    location: /
                    autoindex: 'off'
                    internal: false
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
                    fastcgi: ''
                    fastcgi_index: ''
                    fastcgi_split_path: ''
                    proxy: ''
                    proxy_redirect: ''
                nxvl_czlcadmpaq6t:
                    location: '~ \.php$'
                    autoindex: 'off'
                    internal: false
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
                    fastcgi: '127.0.0.1:9000'
                    fastcgi_index: index.php
                    fastcgi_split_path: '^(.+\.php)(/.*)$'
                    fast_cgi_params_extra:
                        - 'SCRIPT_FILENAME $request_filename'
                        - 'APP_ENV dev'
                    set:
                        - '$path_info $fastcgi_path_info'
                    proxy: ''
                    proxy_redirect: ''
    proxies: {  }
apache:
    install: '0'
    settings:
        version: 2.4
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - proxy_fcgi
        - rewrite
    vhosts:
        av_d34gx94vmpfg:
            servername: awesome.dev
            serveraliases:
                - www.awesome.dev
            docroot: /var/www/awesome
            port: '80'
            setenv:
                - 'APP_ENV dev'
            setenvif:
                - 'Authorization "(.*)" HTTP_AUTHORIZATION=$1'
            custom_fragment: ''
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            ssl_protocol: ''
            ssl_cipher: ''
            directories:
                avd_wh5bijteamqb:
                    path: /var/www/awesome
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - 'all granted'
                    custom_fragment: ''
                    files_match:
                        avdfm_uu67kbdwsplw:
                            path: \.php$
                            sethandler: 'proxy:fcgi://127.0.0.1:9000'
                            custom_fragment: ''
                            provider: filesmatch
                    provider: directory
php:
    install: '1'
    settings:
        version: '56'
    modules:
        php:
            - cli
            - intl
        pear: {  }
        pecl: {  }
    ini:
        display_errors: 'On'
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
        date.timezone: UTC
    fpm_ini:
        error_log: /var/log/php-fpm.log
    fpm_pools:
        phpfp_zd2b33uxzd9p:
            ini:
                prefix: www
                listen: '127.0.0.1:9000'
                security.limit_extensions: .php
                user: www-user
                group: www-data
    composer: '1'
    composer_home: ''
xdebug:
    install: '0'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
blackfire:
    install: '0'
    settings:
        server_id: ''
        server_token: ''
        agent:
            http_proxy: ''
            https_proxy: ''
            log_file: stderr
            log_level: '1'
        php:
            agent_timeout: '0.25'
            log_file: ''
            log_level: '1'
xhprof:
    install: '0'
wpcli:
    install: '0'
    version: v0.21.1
drush:
    install: '0'
    version: 6.3.0
ruby:
    install: '1'
    versions:
        rv_swu24yah0axo:
            default: '1'
            bundler: '1'
            version: 1.9.3
python:
    install: '1'
    packages: {  }
    versions: {  }
nodejs:
    install: '0'
    settings:
        version: '5'
    npm_packages: {  }
hhvm:
    install: '0'
    nightly: 0
    composer: '1'
    composer_home: ''
    settings: {  }
    server_ini:
        hhvm.server.host: 127.0.0.1
        hhvm.server.port: '9000'
        hhvm.log.use_log_file: '1'
        hhvm.log.file: /var/log/hhvm/error.log
    php_ini:
        display_errors: 'On'
        error_reporting: '-1'
        date.timezone: UTC
mariadb:
    install: '1'
    settings:
        version: '10.1'
        root_password: '123'
        override_options: {  }
    adminer: 0
    users:
        mariadbnu_x1kk0lkmmf0q:
            name: dbuser
            password: '123'
    databases:
        mariadbnd_ei96hq6jy0tz:
            name: dbname
            sql: ''
    grants:
        mariadbng_8d28s7raq97y:
            user: dbuser
            table: '*.*'
            privileges:
                - ALL
mysql:
    install: '0'
    settings:
        version: '5.5'
        root_password: '123'
        override_options: {  }
    adminer: 0
    users:
        mysqlnu_cioulo9nutkd:
            name: dbuser
            password: '123'
    databases:
        mysqlnd_3b34ybps0z1l:
            name: dbname
            sql: ''
    grants:
        mysqlng_eimqra0bcz8u:
            user: dbuser
            table: '*.*'
            privileges:
                - ALL
postgresql:
    install: '0'
    settings:
        global:
            encoding: UTF8
            version: '9.4'
        server:
            postgres_password: '123'
    databases: {  }
    users: {  }
    grants: {  }
    adminer: 0
mongodb:
    install: '0'
    settings:
        auth: 1
        bind_ip: 127.0.0.1
        port: '27017'
    globals:
        version: 2.6.0
    databases: {  }
redis:
    install: '0'
    settings:
        port: '6379'
sqlite:
    install: '0'
    adminer: 0
    databases: {  }
mailhog:
    install: '0'
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '8025'
        path: /usr/local/bin/mailhog
beanstalkd:
    install: '0'
    settings:
        listenaddress: 0.0.0.0
        listenport: '11300'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: 0
rabbitmq:
    install: '0'
    settings:
        port: '5672'
    users: {  }
    vhosts: {  }
    plugins: {  }
elastic_search:
    install: '0'
    settings:
        version: 2.1.0
        java_install: true
    instances:
        esi_cc8jf3h1o05y:
            name: es-01
solr:
    install: '0'
    settings:
        version: 4.10.2
        port: '8984'`

**Comment by mkdeddens** [comment]
Ref [this commit](https://github.com/puphpet/puppet-puphpet/commit/d2807439c9ff441843a02cf1ee73aea6aad9056f#diff-71d9ae6163e3256956ffb49b5e2a9e8dR35) on puppet-puphpet/manifests/php/xdebug.pp:35.

Seems changing [puppet-puphpet/manifests/php/pecl.pp:139](https://github.com/puphpet/puppet-puphpet/blob/master/manifests/php/pecl.pp#L139) to what's below does the trick:

`require  => Package[$puphpet::php::settings::package_devel]`

**Comment by spectravp** [comment]
Same issue here.

**Comment by JamesAten** [comment]
I had the same issue last night. The only thing that fixed the install was disabling php installation in the config.yaml, but that is not ideal.

**Comment by kamilgrzegorczyk** [comment]
In order to fix it in my situation I changed the line 100 in:
puphpet/puppet/manifests/php.pp

`  each( $php['modules']['php']  ) |$name| {

**Comment by alexandrecintra** [comment]
Same issue here! I fixed with @LeGfrey pull-request too. Thanks!!!
