### ISSUE TITLE
Vagrant up failing during provisioning

### ISSUE THREAD

**Issue by jloosli** [puphpet/puphpet#2149]
I filed #2137 and took the advice to upgrade the config.yaml by dropping it into the site and getting the latest version out. I was still having problems, so I figured I would try running a fresh install starting from scratch and just use the default configuration. Even with that, it keeps dying around the same spot, when it lists off a bunch of ruby gem information. I'm assuming it's something to do with my overall vagrant setup, but I'm running Vagrant 1.8. Any ideas?

config.yaml and vagrant up --debug log in dropbox below

https://www.dropbox.com/sh/8el2hgc60x9py7q/AACeF4PFfWtDenOzsuv7pcKYa?dl=0

**Comment by jloosli** [comment]
Seems to be running ok now. Not sure what's changed, but was able to vagrant up reliably 5-6 times.

**Comment by jtreminio** [comment]
Glad it worked out for you!
