### ISSUE TITLE
pecl_http returned 1 instead of one of [0]

### ISSUE THREAD

**Issue by konstantinsp** [puphpet/puphpet#2150]
hello,
im trying to install puphpet with pecl_http 
im im getting this error 

<pre>
==> local: Error: printf "\n" | pecl -d preferred_state=stable install pecl_http && pecl info pecl_http returned 1 instead of one of [0]
==> local: Error: /Stage[main]/Puphpet_php/Puphpet::Php::Pecl[pecl_http]/Php::Pecl::Module[pecl_http]/Exec[pecl-pecl_http]/returns: change from notrun to 0 failed: printf "\n" | pecl -d preferred_state=stable install pecl_http && pecl info pecl_http returned 1 instead of one of [0]
</pre>

i need a vagrant machine for this framework
https://bundles.kunstmaan.be/documentation/installation/system-requirements

i've copied their original config and updated to new puphpet config because old did not work at all.

how can i fix this pecl_http problem? 
maybe i could use old version somehow? 
p.s. im new to puphpet so it would be nice for more detailed fix guide) 

here is my config file

<pre>
vagrantfile:
    target: local
    vm:
        box: puphpet/ubuntu1404-x64
        box_url: puphpet/ubuntu1404-x64
        hostname: kunstmaan.cms
        memory: '1024'
        cpus: '2'
        chosen_provider: virtualbox
        box_version: ''
        network:
            private_network: 192.168.57.101
            forwarded_port:
                vflnp_5mt2vweg89hw:
                    host: '9598'
                    guest: '22'
        post_up_message: ''
        provider:
            virtualbox:
                modifyvm:
                    natdnshostresolver1: false
                showgui: '0'
            vmware:
                numvcpus: 1
            parallels:
                use_linked_clone: '0'
                check_guest_tools: '0'
                update_guest_tools: '0'
        provision:
            puppet:
                manifests_path: puphpet/puppet/manifests
                module_path: puphpet/puppet/modules
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
        synced_folder:
            vflsf_zs1kpz8z7ddz:
                source: ./
                target: /var/www
                sync_type: nfs
                smb:
                    smb_host: ''
                    smb_username: ''
                    smb_password: ''
                    mount_options:
                        dir_mode: '0775'
                        file_mode: '0664'
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    exclude:
                        - .vagrant/
                        - .git/
                    auto: 'true'
                owner: vagrant
                group: vagrant
        usable_port_range:
            start: 10200
            stop: 10500
    ssh:
        host: null
        port: null
        private_key_path: null
        username: vagrant
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'
        insert_key: false
    vagrant:
        host: detect
    proxy:
        http: ''
        https: ''
        ftp: ''
        no_proxy: ''
        enabled: ''
server:
    install: '1'
    packages:
        - vim
        - htop
        - memcached
        - libpng-dev
        - imagemagick
users_groups:
    install: '1'
    groups: {  }
    users: {  }
locale:
    install: '1'
    settings:
        default_locale: en_US.UTF-8
        locales:
            - en_GB.UTF-8
            - en_US.UTF-8
        timezone: UTC
firewall:
    install: '1'
    rules: {  }
cron:
    install: '1'
    jobs: {  }
nginx:
    install: '0'
    settings:
        default_vhost: 1
        proxy_buffer_size: 128k
        proxy_buffers: '4 256k'
        proxy_connect_timeout: 600s
        proxy_send_timeout: 600s
        proxy_read_timeout: 600s
        names_hash_bucket_size: 128
    upstreams: {  }
    vhosts:
        nxv_ufuxqgb7lux7:
            server_name: kunstmaan.cms
            server_aliases:
                - www.kunstmaan.cms
            www_root: /var/www/kunstmaancms/web
            listen_port: '80'
            index_files:
                - index.html
                - index.htm
                - index.php
            client_max_body_size: 1m
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_port: '443'
            ssl_protocols: ''
            ssl_ciphers: ''
            locations:
                nxvl_fd6siec1fmy8:
                    location: /
                    autoindex: 'off'
                    internal: 'false'
                    try_files:
                        - $uri
                        - $uri/
                        - index.php
                    fastcgi: ''
                    fastcgi_index: ''
                    fastcgi_split_path: ''
                    proxy: ''
                    proxy_redirect: ''
                nxvl_s6cl50q9c3r9:
                    location: '~ \.php$'
                    autoindex: 'off'
                    internal: 'false'
                    try_files:
                        - $uri
                        - $uri/
                        - index.php
                        - /index.php$is_args$args
                    fastcgi: '127.0.0.1:9000'
                    fastcgi_index: index.php
                    fastcgi_split_path: '^(.+\.php)(/.*)$'
                    fast_cgi_params_extra:
                        - 'SCRIPT_FILENAME $request_filename'
                        - 'APP_ENV dev'
                    proxy: ''
                    proxy_redirect: ''
    proxies: {  }
apache:
    install: '1'
    settings:
        version: 2.4
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - proxy_fcgi
        - rewrite
    vhosts:
        av_zcrnpn1fgjnx:
            servername: kunstmaan.cms
            serveraliases:
                - www.kunstmaan.cms
            docroot: /var/www/myprojectname/web
            port: '80'
            setenv:
                - 'APP_ENV dev'
            custom_fragment: ''
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            ssl_protocol: ''
            ssl_cipher: ''
            directories:
                avd_qy4nb4gumn21:
                    path: /var/www/web/web
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - 'all granted'
                    custom_fragment: ''
                    files_match:
                        avdfm_7edwfsgghmt6:
                            path: \.php$
                            sethandler: 'proxy:fcgi://127.0.0.1:9000'
                            custom_fragment: ''
                            provider: filesmatch
                    provider: directory
php:
    install: '1'
    settings:
        version: '55'
    modules:
        php:
            - cli
            - intl
            - mcrypt
            - curl
            - imagick
            - gd
            - memcached
        pear: {  }
        pecl:
            - pecl_http
            - apcu
    ini:
        display_errors: 'On'
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
        date.timezone: UTC
    fpm_ini:
        error_log: /var/log/php-fpm.log
    fpm_pools: {  }
    composer: '1'
    composer_home: ''
xdebug:
    install: '0'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
blackfire:
    install: '0'
    settings:
        server_id: ''
        server_token: ''
        agent:
            http_proxy: ''
            https_proxy: ''
            log_file: stderr
            log_level: '1'
        php:
            agent_timeout: '0.25'
            log_file: ''
            log_level: '1'
xhprof:
    install: '0'
wpcli:
    install: '0'
    version: v0.17.1
drush:
    install: '0'
    version: 6.3.0
ruby:
    install: '1'
    versions: {  }
python:
    install: '1'
    packages: {  }
    versions: {  }
nodejs:
    install: '1'
    settings:
        version: '5'
    npm_packages:
        - bower
        - gulp
        - uglify-js
        - uglifycss
hhvm:
    install: '0'
    nightly: 0
    composer: '1'
    composer_home: ''
    settings: {  }
    server_ini: {  }
    php_ini: {  }
mariadb:
    install: '0'
    settings:
        version: '10.0'
        root_password: '123'
        override_options: {  }
    adminer: 0
    users:
        mariadbnu_sd61tnhva4ne:
            name: dbuser
            password: '123'
    databases:
        mariadbnd_4h0itlgeevwr:
            name: dbname
            sql: ''
    grants:
        mariadbng_834m45houwik:
            user: dbuser
            table: '*.*'
            privileges:
                - ALL
mysql:
    install: '1'
    settings:
        version: '5.5'
        root_password: password
        override_options: {  }
    adminer: '1'
    users:
        mysqlnu_09ba05g8j8jc:
            name: mydbuser
            password: mydbpass
    databases:
        mysqlnd_td49jec38kre:
            name: mydbname
            sql: ''
    grants:
        mysqlng_jgegb4nj5m4j:
            user: mydbuser
            table: '*.*'
            privileges:
                - ALL
postgresql:
    install: '0'
    settings:
        global:
            encoding: UTF8
            version: '9.3'
        server:
            postgres_password: '123'
    databases: {  }
    users: {  }
    grants: {  }
    adminer: 0
mongodb:
    install: '0'
    settings:
        auth: 1
        bind_ip: 127.0.0.1
        port: '27017'
    globals:
        version: 2.6.0
    databases: {  }
redis:
    install: '0'
    settings:
        port: '6379'
sqlite:
    install: '0'
    adminer: 0
    databases: {  }
mailhog:
    install: '0'
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '8025'
        path: /usr/local/bin/mailhog
beanstalkd:
    install: '0'
    settings:
        listenaddress: 0.0.0.0
        listenport: '13000'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: 0
rabbitmq:
    install: '0'
    settings:
        port: '5672'
    users: {  }
    vhosts: {  }
    plugins: {  }
elastic_search:
    install: '1'
    settings:
        version: 1.4.1
        java_install: true
    instances: {  }
solr:
    install: '0'
    settings:
        version: 4.10.2
        port: '8984'
</pre>

**Comment by jtreminio** [comment]
https://pecl.php.net/package/pecl_http

Requires https://pecl.php.net/package/raphf

**Comment by konstantinsp** [comment]
raphf gives an error to 
<pre>
==> local: Notice: /Stage[main]/Puphpet_php/Puphpet::Php::Pecl[raphf]/Php::Pecl::Module[raphf]/Exec[pecl-raphf]/returns: install failed
==> local: Notice: /Stage[main]/Puphpet_php/Puphpet::Php::Pecl[raphf]/Puphpet::Php::Ini[raphf]/File[/etc/php5/mods-available/raphf.ini]/ensure: created
==> local: Notice: /Stage[main]/Puphpet_php/Puphpet::Php::Pecl[raphf]/Puphpet::Php::Ini[raphf]/File[/etc/php5/fpm/conf.d/raphf.ini]/ensure: created
==> local: Error: printf "\n" | pecl -d preferred_state=stable install raphf && pecl info raphf returned 1 instead of one of [0]
==> local: Error: /Stage[main]/Puphpet_php/Puphpet::Php::Pecl[raphf]/Php::Pecl::Module[raphf]/Exec[pecl-raphf]/returns: change from notrun to 0 failed: printf "\n" | pecl -d preferred_state=stable install raphf && pecl info raphf returned 1 instead of one of [0]

</pre>

**Comment by jeromegamez** [comment]
The reason is not that `pecl_http` requires `raphf`, but that since 2016-01-19, `pecl_http` 3.0 is being the stable version, which requires PHP 7.0 or newer. See https://pecl.php.net/package/pecl_http/3.0.0

**Comment by fnagel** [comment]
Installing pecl_http was no problem with older version of PHP. Really needed. Any advise?

**Comment by jeromegamez** [comment]
@fnagel Change `pecl_http` to `pecl_http-2.5.6` and it should work again.

**Comment by fnagel** [comment]
@jeromegamez Woaah, thanks for the fast respsonse!


Still have following issues when `vagrant up`:
````
==> felixnagel: Notice: /Stage[main]/Puphpet_php/Puphpet::Php::Pecl[pecl_http-2.5.6]/Php::Pecl::Module[pecl_http-2.5.6]/Exec[pecl-pecl_http-2.5.6]/returns: pecl/raphf requires PHP (version >= 5.3.0, version <= 7.0.0, excluded versions: 7.0.0), installed version is 7.0.4-6+deb.sury.org~trusty+3
==> felixnagel: Notice: /Stage[main]/Puphpet_php/Puphpet::Php::Pecl[pecl_http-2.5.6]/Php::Pecl::Module[pecl_http-2.5.6]/Exec[pecl-pecl_http-2.5.6]/returns: pecl/propro requires PHP (version >= 5.3.0, version <= 7.0.0, excluded versions: 7.0.0), installed version is 7.0.4-6+deb.sury.org~trusty+3
==> felixnagel: Notice: /Stage[main]/Puphpet_php/Puphpet::Php::Pecl[pecl_http-2.5.6]/Php::Pecl::Module[pecl_http-2.5.6]/Exec[pecl-pecl_http-2.5.6]/returns: No valid packages found
==> felixnagel: Notice: /Stage[main]/Puphpet_php/Puphpet::Php::Pecl[pecl_http-2.5.6]/Php::Pecl::Module[pecl_http-2.5.6]/Exec[pecl-pecl_http-2.5.6]/returns: install failed
==> felixnagel: Notice: /Stage[main]/Puphpet_php/Puphpet::Php::Pecl[pecl_http-2.5.6]/Puphpet::Php::Ini[pecl_http-2.5.6]/File[/etc/php/7.0/mods-available/pecl_http-2.5.6.ini]/ensure: created
==> felixnagel: Error: printf "\n" | pecl -d preferred_state=stable install pecl_http-2.5.6 && pecl info pecl_http-2.5.6 returned 1 instead of one of [0]
==> felixnagel: Error: /Stage[main]/Puphpet_php/Puphpet::Php::Pecl[pecl_http-2.5.6]/Php::Pecl::Module[pecl_http-2.5.6]/Exec[pecl-pecl_http-2.5.6]/returns: change from notrun to 0 failed: printf "\n" | pecl -d preferred_state=stable install pecl_http-2.5.6 && pecl info pecl_http-2.5.6 returned 1 instead of one of [0]
==> felixnagel: Notice: /Stage[main]/Puphpet_php/Puphpet::Php::Pecl[pecl_http-2.5.6]/Puphpet::Php::Ini[pecl_http-2.5.6]/File[/etc/php/7.0/fpm/conf.d/pecl_http-2.5.6.ini]/ensure: created
==> felixnagel: Notice: /Stage[main]/Puphpet_php/Puphpet::Php::Pecl[pecl_http-2.5.6]/Puphpet::Php::Ini[pecl_http-2.5.6]/File[/etc/php/7.0/cli/conf.d/pecl_http-2.5.6.ini]/ensure: created
==> felixnagel: Notice: /Stage[main]/Puphpet_php/Puphpet::Php::Pecl[pecl_http-2.5.6]/Puphpet::Php::Ini[pecl_http-2.5.6]/Augeas[MODULE/extension: pecl_http-2.5.6.so]/returns: executed successfully
==> felixnagel: Info: /Stage[main]/Puphpet_php/Puphpet::Php::Pecl[pecl_http-2.5.6]/Puphpet::Php::Ini[pecl_http-2.5.6]/Augeas[MODULE/extension: pecl_http-2.5.6.so]: Scheduling refresh of Service[php7.0-fpm]
==> felixnagel: Info: Puphpet::Php::Pecl[pecl_http-2.5.6]: Unscheduling all events on Puphpet::Php::Pecl[pecl_http-2.5.6]
````

Error in PHP:
````
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/pecl_http-2.5.6.so' - /usr/lib/php/20151012/pecl_http-2.5.6.so: cannot open shared object file: No such file or directory in Unknown on line 0
````

**Comment by jeromegamez** [comment]
Oh, from your logs it seems that you are using PHP 7, so the "normal" `pecl_http` should have worked in the first place - strange. Have you already tried destroying and re-upping you VM?

**Comment by fnagel** [comment]
Oh yes, I should have mentioned that I'm using PHP7.

Using `pecl_http` only just ends in some dependency issues (with raphf and propro) and similar PHP issues "unable to load ...".

**Comment by fnagel** [comment]
Tried another destroy and up with dependencies but without success
````
pecl:
     - pecl_raphf
     - pecl_propro
     - pecl_http
````

**Comment by fnagel** [comment]
Could this be related to #1406 ?

**Comment by piszczek** [comment]
@fnagel 
Did you resolve this problem?
