### ISSUE TITLE
dpkg-preconfigure: unable to re-open stdin

### ISSUE THREAD

**Issue by fourteenmeister** [puphpet/puphpet#2159]
It seems that this is not an error, but for some reason, is highlighted in red.

![image](https://cloud.githubusercontent.com/assets/3837141/12885001/2ec1f080-ce9d-11e5-98d1-b63edef89de0.png)

This is normal? It seems to be working, but still annoying me this error (?) In the log.

**Comment by jtreminio** [comment]
This is normal, it's a known Vagrant thing. Can't do anything about it :(
