### ISSUE TITLE
Error: Unable to locate package php5.6-imagick [mysqlnd]

### ISSUE THREAD

**Issue by esszett** [puphpet/puphpet#2163]
I 'm getting errors while trying to provision my box (puphpet/ubuntu1404-x64) with php (version 56) with additional modules imagick and mysqlnd.
"E: Unable to locate package php5.6-imagick
E: Couldn't find any package by regex 'php5.6-imagick'"

Is there something wrong with the regex, i found with apt-cache search the package is named "php5-imagick" - ImageMagick module for php5

Same error with module "mysqlnd", should load "php5-mysqlnd", error is 
"E: Unable to locate package php5.6-mysqlnd
E: Couldn't find any package by regex 'php5.6-mysqlnd'"

**Comment by pkalisz** [comment]
+1

**Comment by HnLn** [comment]
See also
https://github.com/puphpet/puphpet/issues/2162
https://github.com/puphpet/puphpet/issues/2145

**Comment by weilex** [comment]
Any news about this issue ?

**Comment by HnLn** [comment]
Did a fresh config today (28/02), still the same problem.

**Comment by marcosgdf** [comment]
Happening to me as well.
