### ISSUE TITLE
Add Drush 8 to the list of Drush versions

### ISSUE THREAD

**Issue by CTIGB** [puphpet/puphpet#2166]
Would it be possible to add in the ability to install Drush 8 globally something like this puppet module? https://forge.puppetlabs.com/previousnext/drush

**Comment by freality** [comment]
While the options are not in the website configurator, manually setting the version in your config.yaml works. You can find all packaged versions on https://packagist.org/packages/drush/drush.

**Comment by jtreminio** [comment]
Closed by dfcefff
