### ISSUE TITLE
which php.info has to be edited at puphpet/ubuntu1404-x64 with php 5.6

### ISSUE THREAD

**Issue by Slotty70** [puphpet/puphpet#2173]
hi,

i installed puphpet/ubuntu1404-x64 with php 5.6..but where can i change the php.ini settings..?

$ php --ini

Configuration File (php.ini) Path: /etc/php/5.6/cli
Loaded Configuration File:         /etc/php/5.6/cli/php.ini
Scan for additional .ini files in: /etc/php/5.6/cli/conf.d
Additional .ini files parsed:      /etc/php/5.6/cli/conf.d/10-opcache.ini,
/etc/php/5.6/cli/conf.d/20-gd.ini,
/etc/php/5.6/cli/conf.d/20-intl.ini,
/etc/php/5.6/cli/conf.d/20-json.ini,
/etc/php/5.6/cli/conf.d/20-mysqli.ini,
/etc/php/5.6/cli/conf.d/20-pdo_mysql.ini,
/etc/php/5.6/cli/conf.d/20-readline.ini,
/etc/php/5.6/cli/conf.d/zzzz_custom.ini

i tried it at
/etc/php/5.6/cli/php.ini

and 
/etc/php/5.6/fpm/php.ini

as my phpinfo files says 
Loaded Configuration File	/etc/php/5.6/fpm/php.ini

and the ssh command php --ini says 
Loaded Configuration File:         /etc/php/5.6/cli/php.ini

but after apache restart nothing changed...

default max_execution time etc...

any help would be appreciated

cheers 
slottty

**Comment by Slotty70** [comment]
i see also the zzz_custom.ini...can i add some config settings there or do i have to add them to the config.yaml and provision the box once more?

**Comment by andresnijder** [comment]
did you restart php-fpm as well? 
`sudo service php5.6-fpm restart`

**Comment by Slotty70** [comment]
ah ok  thx a lot, 

after 
sudo service php5.6-fpm restart

my phpinfo displayed the new value  ^^

so i don`t have to 

sudo service apache2 restart

after php init changes :)

but now i figured out how to add/edit actual php settings another way...you can also change the config.yaml ...and then run

vagrant reload --provision

after that your new settings will be written into the 

/etc/php/5.6/fpm/conf.d/zzzz_custom.ini

and will probably override all others


cheers
martin

**Comment by jtreminio** [comment]
Add it to the config.yaml.
