### ISSUE TITLE
Vagrant fails: A box must be specified.

### ISSUE THREAD

**Issue by joenivl** [puphpet/puphpet#2178]
Since "yesterday" (not really sure when this changed) the configuration of my PuPHPet scripts is changed when I download a config from https://puphpet.com.

When I try to vagrant up I get the following error: 

```
There are errors in the configuration of this machine. Please fix
the following errors and try again:

vm:
* A box must be specified.
```
"Old" boxes that I downloaded before are still working. 

I got the issue on a Macbook and Windows 10 with Vagrant 1.8.1 and Virtualbox  5.0.14 r105127. 

I have attached the config.yml.
[config.yaml.txt](https://github.com/puphpet/puphpet/files/135750/config.yaml.txt)

**Comment by ChMat** [comment]
Hi,

Same issue with me. I have noticed that Puphpet config form has changed. When I upload an old config.yml file, some of the required elements are missing, but Puphpet does not warn about that.

In my case, I had to add a machine in the Deploy Target > Locally tab.

@jtreminio Would it be an option to mark every native config.yml generated by Puphpet with a version tag? This way, it would be easier to warn users about breaking changes in the config.yml format when the file is uploaded back into the form.

**Comment by joenivl** [comment]
@ChMat thanks for the reply, when I add a machine it works again.

**Comment by darkdiesel** [comment]
Some advises.

Every time when i update or create new based on previous puphpet config i open site upload my config. Also i open second tab of browser and open default puphpet page. I compare my configuration with default site configuration on second tab. In case with machines i found this new changes and add to my config.

**Comment by yourithielen** [comment]
@ChMat This seems to be a BC break

@jtreminio I think it shouldn't be to difficult to make the old config.yaml file compatible when importing them?

**Comment by jtreminio** [comment]
Fixed.

http://blog.puphpet.com/blog/2016/03/04/multi-machine-support/

Info added to frontpage.

**Comment by erdemece** [comment]
this is not fixed. I used my old config file and uploaded to the website and then download it. this gives me same error.

**Comment by yourithielen** [comment]
It won't be fixed, see message on website abou BC.
