### ISSUE TITLE
Ubuntu 14.04: PHP 7 - simplexml no longer installed by default

### ISSUE THREAD

**Issue by Fender123** [puphpet/puphpet#2188]
Since 23.02.2016 there is a new php7.0-xml package for installing xml support for php7.

It is no longer installed by default (kind of strange, because php docs state that simplexml is included by default)

Running `sudo apt-get install php7.0-xml`
fixes missing xml support

System: Ubuntu Trusty 14.04 LTS x64
puphpet files downloaded on 23.02.2016

**Comment by jtreminio** [comment]
This isn't a puphpet issue, but upstream in ondrej's repo.
