### ISSUE TITLE
loading config.yaml back into puphpet.com fails to import machine data

### ISSUE THREAD

**Issue by guyradford** [puphpet/puphpet#2189]
Hi, 

I see you have date the site to now allow for multiple machines. The yaml format has also changed. When I drop my current config.yaml into the site to update the format it fails to load the machines. I have just spent several days updating to the previous config format, now I need to do the whole process again.

To solve this, add a config version in the config.yaml file and keep the old config import routines will allow people to easily reimport their old configs and download the new updated version.

Thank you

**Comment by jacksonj04** [comment]
Related, #2174, #2178

**Comment by fnagel** [comment]
Same issue here. Needed to create a new archive.

**Comment by jtreminio** [comment]
Fixed.

http://blog.puphpet.com/blog/2016/03/04/multi-machine-support/

Info added to frontpage.
