### ISSUE TITLE
Can't run puphpet locally

### ISSUE THREAD

**Issue by Skarlso** [puphpet/puphpet#2195]
Hello. 

First off, the total lack of documentation of how to start the project at all locally is a bit frustrating, especially, when someone comes along with no php, or symfony background. But that's okay.

However, I'm facing a problem. I installed everything with composer, yet when I start the server and go to http://127.0.0.1:8000 I find a blank page and that's it. Even if I start it in debug mode (./app/console -vvv server:run; also tried composer exec ./app/console server:run) there is no error message what so ever anywhere. So I have zero ideas what the problem might be here. Also the logs folder is empty.

Any help on how to start would be greatly appreciated. 

Thanks!
Gergely.

**Comment by fnagel** [comment]
Why 172.0.0.01:8000?

You should try opening the IP you added for the project in the GUI.

**Comment by Skarlso** [comment]
Hey. So I'll try to be clearer, sorry about that. :S 

I'm trying to contribute code. Learn the structure, in order to learn PHP better. I was trying to run the GUI locally in order to develop it. Not just to run the vagrant stuff, but to run Puphpet locally. 

So I see that it's a symfony app, I thought running ./app/console should do the trick and it does. Then on the IRC channel I got some help so I edited vhost to be puphpet/web. But still, all I get is a blank page without errors. 

I'm guessing, that I need a lot more in order to run it locally. Like, a database, some settings, whatever.

So I'm seeking help in that regard. I don't think just running the unit tests is enough when developing. I would also like to do system tests. So getting the whole thing up and running is the first step. 

Unless, I misunderstand something and the vagrant stuff is actually creating a Development environment for Puphpet?!

Thank you @fnagel!

**Comment by thedeedawg** [comment]
It's not. The archive/"vagrant stuff" that's included, is used to generate the result, not to run puphpet itself. Did you run ```composer install```?

**Comment by Skarlso** [comment]
@thedeedawg Yes.

**Comment by thedeedawg** [comment]
You haven't mentioned much about the environment you're running it on, so I'll just say what comes to mind. If you're running it on nginx, you will manually need to setup the rewrite rule, as the .htaccess won't do anything in that case - or just request ```app.php``` directly.

Have you checked your error logs for any useful information in regards to this?

**Comment by Skarlso** [comment]
@thedeedawg Well that's the problem. :) I have no idea how to set it up from zero, because there was no documentation for it, and I have very little experience with PHP + nginx in general. I was trying to use this to learn. 
So to answer your question, I have no environment what so ever, because I don't know what kind I need. :) 

I am experienced with web apps in general though. So I should be able to set one up if I could read at least a high level view of how this works. But I couldn't find any.

**Comment by thedeedawg** [comment]
Okay, although I'm not exactly sure then how you managed to configure a virtual host. But I guess the easiest way to setup a development environment for puphpet, is by generating one with puphpet.

If you want a premade configuration, you can use the one I've provided [here](https://github.com/puphpet/puphpet/issues/2202#issuecomment-191209362).
