### ISSUE TITLE
PHP Extension: XDebug, SQLLite and MongoDb not installed properly and does not complete in simple download from the site

### ISSUE THREAD

**Issue by starx** [puphpet/puphpet#2210]
I downloaded a simple configuration from the website. Has php  7 and other software (most of them are to default settings) and it does not finishes.

Full log of the install is [here](http://pastebin.com/eZf7HuFd)
My puphpet configuration is [zip](https://github.com/puphpet/puppet-puphpet/files/158489/ubuntu1404.puphpet.zip)

Xdebug error:

	==> dev.ubuntu.puphpet: Notice: /Stage[main]/Puphpet::Php::Xdebug/Exec[phpize && ./configure --enable-xdebug && make]/returns: In file included from /.puphpet-stuff/xdebug/xdebug.c:52:0:
	==> dev.ubuntu.puphpet: Notice: /Stage[main]/Puphpet::Php::Xdebug/Exec[phpize && ./configure --enable-xdebug && make]/returns: /.puphpet-stuff/xdebug/php_xdebug.h:23:27: warning: missing terminating " character [enabled by default]
	==> dev.ubuntu.puphpet: Notice: /Stage[main]/Puphpet::Php::Xdebug/Exec[phpize && ./configure --enable-xdebug && make]/returns:  #define XDEBUG_VERSION    "2.4.1-dev
	==> dev.ubuntu.puphpet: Notice: /Stage[main]/Puphpet::Php::Xdebug/Exec[phpize && ./configure --enable-xdebug && make]/returns:                            ^
	==> dev.ubuntu.puphpet: Notice: /Stage[main]/Puphpet::Php::Xdebug/Exec[phpize && ./configure --enable-xdebug && make]/returns: In file included from /.puphpet-stuff/xdebug/xdebug_handlers.h:22:0,
	==> dev.ubuntu.puphpet: Notice: /Stage[main]/Puphpet::Php::Xdebug/Exec[phpize && ./configure --enable-xdebug && make]/returns:                  from /.puphpet-stuff/xdebug/php_xdebug.h:33,
	==> dev.ubuntu.puphpet: Notice: /Stage[main]/Puphpet::Php::Xdebug/Exec[phpize && ./configure --enable-xdebug && make]/returns:                  from /.puphpet-stuff/xdebug/xdebug.c:52:
	==> dev.ubuntu.puphpet: Notice: /Stage[main]/Puphpet::Php::Xdebug/Exec[phpize && ./configure --enable-xdebug && make]/returns: /.puphpet-stuff/xdebug/php_xdebug.h:23:27: warning: missing terminating " character [enabled by default]
	==> dev.ubuntu.puphpet: Notice: /Stage[main]/Puphpet::Php::Xdebug/Exec[phpize && ./configure --enable-xdebug && make]/returns:  #define XDEBUG_VERSION    "2.4.1-dev
	==> dev.ubuntu.puphpet: Notice: /Stage[main]/Puphpet::Php::Xdebug/Exec[phpize && ./configure --enable-xdebug && make]/returns:                            ^
	==> dev.ubuntu.puphpet: Notice: /Stage[main]/Puphpet::Php::Xdebug/Exec[phpize && ./configure --enable-xdebug && make]/returns: /.puphpet-stuff/xdebug/xdebug.c:169:2: error: missing terminating " character
	==> dev.ubuntu.puphpet: Notice: /Stage[main]/Puphpet::Php::Xdebug/Exec[phpize && ./configure --enable-xdebug && make]/returns:   XDEBUG_VERSION,
	==> dev.ubuntu.puphpet: Notice: /Stage[main]/Puphpet::Php::Xdebug/Exec[phpize && ./configure --enable-xdebug && make]/returns:   ^
	==> dev.ubuntu.puphpet: Notice: /Stage[main]/Puphpet::Php::Xdebug/Exec[phpize && ./configure --enable-xdebug && make]/returns: /.puphpet-stuff/xdebug/xdebug.c:169:16: error: expected expression before ',' token
	==> dev.ubuntu.puphpet: Notice: /Stage[main]/Puphpet::Php::Xdebug/Exec[phpize && ./configure --enable-xdebug && make]/returns:   XDEBUG_VERSION,
	==> dev.ubuntu.puphpet: Notice: /Stage[main]/Puphpet::Php::Xdebug/Exec[phpize && ./configure --enable-xdebug && make]/returns:                 ^
	==> dev.ubuntu.puphpet: Notice: /Stage[main]/Puphpet::Php::Xdebug/Exec[phpize && ./configure --enable-xdebug && make]/returns: /.puphpet-stuff/xdebug/xdebug.c: In function 'zm_info_xdebug':
	==> dev.ubuntu.puphpet: Notice: /Stage[main]/Puphpet::Php::Xdebug/Exec[phpize && ./configure --enable-xdebug && make]/returns: /.puphpet-stuff/xdebug/xdebug.c:1339:2: error: missing terminating " character
	==> dev.ubuntu.puphpet: Notice: /Stage[main]/Puphpet::Php::Xdebug/Exec[phpize && ./configure --enable-xdebug && make]/returns:   php_info_print_table_row(2, "Version", XDEBUG_VERSION);
	==> dev.ubuntu.puphpet: Notice: /Stage[main]/Puphpet::Php::Xdebug/Exec[phpize && ./configure --enable-xdebug && make]/returns:   ^
	==> dev.ubuntu.puphpet: Notice: /Stage[main]/Puphpet::Php::Xdebug/Exec[phpize && ./configure --enable-xdebug && make]/returns: /.puphpet-stuff/xdebug/xdebug.c:1339:55: error: expected expression before ')' token
	==> dev.ubuntu.puphpet: Notice: /Stage[main]/Puphpet::Php::Xdebug/Exec[phpize && ./configure --enable-xdebug && make]/returns:   php_info_print_table_row(2, "Version", XDEBUG_VERSION);
	==> dev.ubuntu.puphpet: Notice: /Stage[main]/Puphpet::Php::Xdebug/Exec[phpize && ./configure --enable-xdebug && make]/returns:                                                        ^
	==> dev.ubuntu.puphpet: Notice: /Stage[main]/Puphpet::Php::Xdebug/Exec[phpize && ./configure --enable-xdebug && make]/returns: /.puphpet-stuff/xdebug/xdebug.c: At top level:
	==> dev.ubuntu.puphpet: Notice: /Stage[main]/Puphpet::Php::Xdebug/Exec[phpize && ./configure --enable-xdebug && make]/returns: /.puphpet-stuff/xdebug/xdebug.c:2712:2: error: missing terminating " character
	==> dev.ubuntu.puphpet: Notice: /Stage[main]/Puphpet::Php::Xdebug/Exec[phpize && ./configure --enable-xdebug && make]/returns:   XDEBUG_VERSION,
	==> dev.ubuntu.puphpet: Notice: /Stage[main]/Puphpet::Php::Xdebug/Exec[phpize && ./configure --enable-xdebug && make]/returns:   ^
	==> dev.ubuntu.puphpet: Notice: /Stage[main]/Puphpet::Php::Xdebug/Exec[phpize && ./configure --enable-xdebug && make]/returns: /.puphpet-stuff/xdebug/xdebug.c:2712:16: error: expected expression before ',' token
	==> dev.ubuntu.puphpet: Notice: /Stage[main]/Puphpet::Php::Xdebug/Exec[phpize && ./configure --enable-xdebug && make]/returns:   XDEBUG_VERSION,
	==> dev.ubuntu.puphpet: Notice: /Stage[main]/Puphpet::Php::Xdebug/Exec[phpize && ./configure --enable-xdebug && make]/returns:                 ^
	==> dev.ubuntu.puphpet: Notice: /Stage[main]/Puphpet::Php::Xdebug/Exec[phpize && ./configure --enable-xdebug && make]/returns: make: *** [xdebug.lo] Error 1
	==> dev.ubuntu.puphpet: Error: phpize && ./configure --enable-xdebug && make returned 2 instead of one of [0]
	==> dev.ubuntu.puphpet: Error: /Stage[main]/Puphpet::Php::Xdebug/Exec[phpize && ./configure --enable-xdebug && make]/returns: change from notrun to 0 failed: phpize && ./configure --enable-xdebug && make returned 2 instead of one of [0]
	==> dev.ubuntu.puphpet: Notice: /Stage[main]/Puphpet::Php::Xdebug/Exec[copy xdebug.so to modules dir]: Dependency Exec[phpize && ./configure --enable-xdebug && make] has failures: true
	==> dev.ubuntu.puphpet: Warning: /Stage[main]/Puphpet::Php::Xdebug/Exec[copy xdebug.so to modules dir]: Skipping because of failed dependencies
	==> dev.ubuntu.puphpet: Notice: /Stage[main]/Puphpet::Php::Xdebug/File[/usr/bin/xdebug]/ensure: defined content as '{md5}813de5ab3b902336754e83d0391e375d'

SQLlite Error:

	==> dev.ubuntu.puphpet: Notice: /Stage[main]/Supervisord::Reload/Exec[supervisorctl_update]: Triggered 'refresh' from 1 events
	==> dev.ubuntu.puphpet: Error: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install php-sqlite' returned 100: Reading package lists...
	==> dev.ubuntu.puphpet: Building dependency tree...
	==> dev.ubuntu.puphpet: Reading state information...
	==> dev.ubuntu.puphpet: E: Unable to locate package php-sqlite
	==> dev.ubuntu.puphpet: Error: /Stage[main]/Puphpet_sqlite/Puphpet::Php::Pecl[sqlite]/Package[php-sqlite]/ensure: change from purged to present failed: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install php-sqlite' returned 100: Reading package lists...
	==> dev.ubuntu.puphpet: Building dependency tree...
	==> dev.ubuntu.puphpet: Reading state information...
	==> dev.ubuntu.puphpet: E: Unable to locate package php-sqlite

I am guessing this is because there isn't any php7 specific extension of SQLlite. Same command with `php5-sqlite` runs

MongoDB Error:

	==> dev.ubuntu.puphpet: Notice: /Stage[main]/Puphpet_mongodb/Puphpet::Php::Pecl[mongo]/Php::Pecl::Module[mongodb]/Exec[pecl-mongodb]/returns: checking for pkg-config... no
	==> dev.ubuntu.puphpet: Notice: /Stage[main]/Puphpet_mongodb/Puphpet::Php::Pecl[mongo]/Php::Pecl::Module[mongodb]/Exec[pecl-mongodb]/returns: configure: error: Cannot find OpenSSL's libraries
	==> dev.ubuntu.puphpet: Notice: /Stage[main]/Puphpet_mongodb/Puphpet::Php::Pecl[mongo]/Php::Pecl::Module[mongodb]/Exec[pecl-mongodb]/returns: ERROR: `/tmp/pear/temp/mongodb/configure --with-php-config=/usr/bin/php-config' failed
	==> dev.ubuntu.puphpet: Notice: /Stage[main]/Puphpet_mongodb/Puphpet::Php::Pecl[mongo]/Php::Pecl::Module[mongodb]/Exec[pecl-mongodb]/returns: No information found for `mongodb'
	==> dev.ubuntu.puphpet: Error: printf "\n" | pecl -d preferred_state=stable install mongodb && pecl info mongodb returned 1 instead of one of [0]
	==> dev.ubuntu.puphpet: Error: /Stage[main]/Puphpet_mongodb/Puphpet::Php::Pecl[mongo]/Php::Pecl::Module[mongodb]/Exec[pecl-mongodb]/returns: change from notrun to 0 failed: printf "\n" | pecl -d preferred_state=stable install mongodb && pecl info mongodb returned 1 instead of one of [0]

Its complaining about `OpenSSL's libraries`

I wrote an issue [here](https://github.com/puphpet/puppet-puphpet/issues/38) which has more details, but this might be the right place for it.

**Comment by jtreminio** [comment]
First issue resolved in #2191

Second issue resolved in #2199

**Comment by starx** [comment]
@jtreminio Are these released on the site? and any progress on the MongoDB Issue?

**Comment by jtreminio** [comment]
All issues fixed as of latest release.
