### ISSUE TITLE
PHP 5.6 is missing dom extension

### ISSUE THREAD

**Issue by rowanparker** [puphpet/puphpet#2221]
Using a freshly created version box with PHP 5.6 gives me:

```
$ php -m
[PHP Modules]
calendar
Core
ctype
date
ereg
exif
fileinfo
filter
ftp
gettext
hash
iconv
intl
json
libxml
mbstring
mhash
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
Phar
posix
readline
Reflection
session
shmop
sockets
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
xdebug
Zend OPcache
zlib

[Zend Modules]
Xdebug
Zend OPcache
```

Running a composer install gives me

`phpunit/phpunit 4.8.18 requires ext-dom * -> the requested PHP extension dom is missing from your system.`

Which previously worked as late as two weeks on a box I built then.

**Comment by vzabaznov** [comment]
same for me, apt-get install doesnt help, looks like new php mods structure doesnt let to install all modules in "old way"

**Comment by gubler** [comment]
It looks like several modules (including xml) are being installed configured in `/etc/php/7.0/mods-available` but not in `/etc/php/5.6/mods-available` (and subsequently not sym-linked into the `cli/conf.d` and `fpm/conf.d` directories).

**Comment by gubler** [comment]
Looks like the PPA for PHP5.6 (`ondrej/php`) updated the php-5.6 package today and when I do a `apt-cache show php-xml` the version is 1:7.0+36+deb.sury.org~trusty+1 and the end of the description says:

> This package is a dependency package, which depends on Debian's default
 PHP version (currently 7.0).

I am guessing there was an update that references base Debian packages for some of the PHP5.6 modules, and since the Debian packages are set for 7.0, those modules are also set to 7.0 (I don't really know anything about this though, so I could be/probably am _completely_ wrong).

Pretty much this looks like a problem from the `ondrej/php` PPA, and I don't know enough about Debian/Ubuntu/PPAs/Puppet to figure out a fix.

**Comment by jtreminio** [comment]
Please open an issue at https://github.com/oerdnj/deb.sury.org/issues

**Comment by oerdnj** [comment]
Folks, don't pretend it's so hard to type `apt-cache search php dom` and skim through the list to find `php5.6-xml` package that contains all XML related extensions.

**Comment by hugopeek** [comment]
I ran into the same error with composer.. Managed to fix it with:

$ sudo apt-get update
$ sudo apt-get install php5.6-xml

**Comment by steros** [comment]
That temporarily fixes it manually. But the bug still exists.
I tried to find out where the package is set as it seems the name has to be changed from php-xml to php5.6-xml.
But I could not find this anywhere.

**Comment by hugopeek** [comment]
@steros A more permanent fix can be found here: https://github.com/puphpet/puphpet/issues/2207
Haven't tried it myself that way though..

**Comment by Setzu** [comment]
Thanks hugopeek, it's working for me

**Comment by radhouen** [comment]
sudo apt-get install php-mbstring 
sudo apt-get install php-dom

**Comment by dsteplight** [comment]
Using php5.6-xml worked for me when I had the same issue with Ansible.

**Comment by HefnySco** [comment]
I used 
sudo apt-get install php-mbstring
sudo apt-get install php-dom
but I needed to add those as well:
sudo apt-get install php5.6-gd php5.6-mysql php5.6-dom php5.6-cli php5.6-json php5.6-common php5.6-mbstring php5.6-opcache php5.6-readline

**Comment by glce** [comment]
work for me:
```
sudo apt-get install php7.1-dom
sudo apt-get install php7.1-mbstring
```

that's the way it is and not with "install php-dom" !!!

**Comment by gnovaro** [comment]
In ubuntu/debian add Ondřej Surý repository
sudo add-apt-repository ppa:ondrej/php
sudo apt-get update

And now you can install missing extensions.
