### ISSUE TITLE
vendor/bin in PATH?

### ISSUE THREAD

**Issue by delboy1978uk** [puphpet/puphpet#2223]
Hi @jtreminio :-D

I always end up finding myself typing: 
```
export PATH=$PATH:vendor/bin
```
Or, adding it to the shell scripts folder. 
It seems like it would be a good idea to have puPHPet do this for us by default. Your thoughts?

**Comment by jtreminio** [comment]
Developers will usually stick more than one project on a single VM, and adding to PATH is not something that is normally done on production servers.
