### ISSUE TITLE
CentOS 7 /opt/puppetlabs/puppet/bin/gem: No such file or directory

### ISSUE THREAD

**Issue by prazvan** [puphpet/puphpet#2234]
Hey :)

So after generating all the puppet scripts for a Digital Ocean Deploy, found an issue regarding puppet installation on the remove server. 

Basically in the install-puppet.sh
```
elif [[ "${OS}" == 'centos' ]]; then
    if [ "${RELEASE}" == 6 ]; then
        rpm -Uvh https://yum.puppetlabs.com/puppetlabs-release-pc1-el-6.noarch.rpm
        yum -y install puppet-agent
    fi
fi
```

As you can see you don't cover CentOS 7 :) so the provisioning fails at line 34 when it tries to execute 

```/opt/puppetlabs/puppet/bin/gem install deep_merge activesupport vine --no-ri --no-rdoc```

to fix the rest of the provisioning i just ssh into the vm and manually installed puppet.

I guess the fix should be something like so :)
```
if [ "${RELEASE}" == 6 ]; then
  rpm -Uvh https://yum.puppetlabs.com/puppetlabs-release-pc1-el-6.noarch.rpm
elif [ "${RELEASE}" == 7 ]; then
  rpm -Uvh https://yum.puppetlabs.com/puppetlabs-release-pc1-el-7.noarch.rpm
fi
yum -y install puppet-agent
```

Thanks,
Razvan

**Comment by jtreminio** [comment]
CentOS 7 is not currently supported. There's a ton more work that needs done besides just this.
