### ISSUE TITLE
Multiple Class not found errors with LAMP - Ubuntu 14

### ISSUE THREAD

**Issue by CTIGB** [puphpet/puphpet#2238]
I have a VM with multiple Apache V Hosts and needed to add a new one this morning so I added one and now all of my local dev sites are no longer working. Here is an example of the types of error I'm getting:

Fatal error: Class 'DOMDocument' not found
Fatal error: Class 'SimpleXmlIterator' not found

I've also started from scratch with a single V Host and that worked fine but then adding the rest of them brought up the same errors as above.

My config yams is below:

`vagrantfile:
    target: local
    vm:
        provider:
            local:
                box: puphpet/ubuntu1404-x64
                box_url: puphpet/ubuntu1404-x64
                box_version: '0'
                chosen_virtualizer: parallels
                virtualizers:
                    virtualbox:
                        modifyvm:
                            natdnshostresolver1: false
                        showgui: 0
                    vmware:
                        numvcpus: 1
                    parallels:
                        use_linked_clone: 0
                        check_guest_tools: 0
                        update_guest_tools: 0
                machines:
                    vflm_gd0fmkul06n9:
                        id: 'Apache Dev'
                        network:
                            private_network: 33.33.33.10
                            forwarded_port:
                                vflmnfp_a765isoo6cze:
                                    host: '8236'
                                    guest: '22'
                        hostname: puppet.local
                        memory: '4096'
                        cpus: '4'
        provision:
            puppet:
                manifests_path: puphpet/puppet/manifests
                module_path: puphpet/puppet/modules
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
        synced_folder:
            vflsf_7eggyhdbhih7:
                source: ./sites
                target: /var/www
                sync_type: nfs
                smb:
                    smb_host: ''
                    smb_username: ''
                    smb_password: ''
                    mount_options:
                        dir_mode: '0775'
                        file_mode: '0664'
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    exclude:
                        - .vagrant/
                        - .git/
                    auto: 'true'
                owner: www-data
                group: www-data
        usable_port_range:
            start: 10200
            stop: 10500
        post_up_message: ''
    ssh:
        host: 'false'
        port: 'false'
        private_key_path: 'false'
        username: vagrant
        guest_port: 'false'
        keep_alive: '1'
        forward_agent: 'false'
        forward_x11: 'false'
        shell: 'bash -l'
        insert_key: 'false'
    vagrant:
        host: detect
    proxy:
        http: ''
        https: ''
        ftp: ''
        no_proxy: ''
        enabled: ''
server:
    install: '1'
    packages:
        - htop
        - zip
        - unzip
        - nano
        - imagemagick
        - libpcre3-dev
users_groups:
    install: '1'
    groups: {  }
    users: {  }
locale:
    install: '1'
    settings:
        default_locale: en_US.UTF-8
        locales:
            - en_GB.UTF-8
            - en_US.UTF-8
        timezone: UTC
firewall:
    install: '1'
    rules:
        fr_pv1cvaornkrh:
            port:
                - '22'
            priority: '100'
            proto: tcp
            action: accept
        fr_2wk18monvh9p:
            port:
                - '80'
            priority: '100'
            proto: tcp
            action: accept
cron:
    install: '1'
    jobs: {  }
nginx:
    install: '0'
    settings:
        default_vhost: 1
        proxy_buffer_size: 128k
        proxy_buffers: '4 256k'
        proxy_connect_timeout: 600s
        proxy_send_timeout: 600s
        proxy_read_timeout: 600s
        names_hash_bucket_size: 128
    upstreams: {  }
    vhosts:
        nxv_eq8jnh7n29nu:
            server_name: awesome.dev
            server_aliases:
                - www.awesome.dev
            www_root: /var/www/awesome
            listen_port: '80'
            index_files:
                - index.html
                - index.htm
                - index.php
            client_max_body_size: 1m
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_port: '443'
            ssl_protocols: ''
            ssl_ciphers: ''
            rewrite_to_https: '1'
            spdy: '1'
            locations:
                nxvl_iaxno932jjif:
                    location: /
                    autoindex: 'off'
                    internal: 'false'
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
                    fastcgi: ''
                    fastcgi_index: ''
                    fastcgi_split_path: ''
                    proxy: ''
                    proxy_redirect: ''
                nxvl_y3rdtelf8zyb:
                    location: '~ \.php$'
                    autoindex: 'off'
                    internal: 'false'
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
                    fastcgi: '127.0.0.1:9000'
                    fastcgi_index: index.php
                    fastcgi_split_path: '^(.+\.php)(/.*)$'
                    fast_cgi_params_extra:
                        - 'SCRIPT_FILENAME $request_filename'
                        - 'APP_ENV dev'
                    set:
                        - '$path_info $fastcgi_path_info'
                    proxy: ''
                    proxy_redirect: ''
    proxies: {  }
apache:
    install: '1'
    settings:
        version: 2.4
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - deflate
        - proxy_fcgi
        - rewrite
    vhosts:
        av_9fcpwdurtq8v:
            servername: centrallibrarymcr.dev
            serveraliases:
                - thetownhallmcr.dev
            docroot: /var/www/mancentral/www
            port: '80'
            setenv:
                - 'APP_ENV dev'
            setenvif:
                - 'Authorization "(.*)" HTTP_AUTHORIZATION=$1'
            custom_fragment: ''
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            ssl_protocol: ''
            ssl_cipher: ''
            directories:
                avd_lug94yslbnj3:
                    path: /var/www/mancentral/www
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - 'all granted'
                    custom_fragment: ''
                    files_match:
                        avdfm_xqzter5qjyv5:
                            path: \.php$
                            sethandler: 'proxy:fcgi://127.0.0.1:9000'
                            custom_fragment: ''
                            provider: filesmatch
                    provider: directory
        av_po0gogwl5cti:
            servername: westway.dev
            serveraliases:
                - www.westway.dev
                - sports.westway.dev
                - futures.westway.dev
                - space.westway.dev
                - learning.westway.dev
                - presents.westway.dev
            docroot: /var/www/westway/drupal
            port: '80'
            custom_fragment: ''
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            ssl_protocol: ''
            ssl_cipher: ''
            directories:
                avd_lftcp567j9nj:
                    path: /var/www/westway/drupal
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - 'all granted'
                    custom_fragment: ''
                    files_match:
                        avdfm_8kpmjd9f1bl3:
                            path: \.php$
                            sethandler: 'proxy:fcgi://127.0.0.1:9000'
                            custom_fragment: ''
                            provider: filesmatch
                    provider: directory
        av_zsayfyvy0z9b:
            servername: drakecircus.dev
            serveraliases:
                - bliss.britishland.dev
            docroot: /var/www/britishland/site
            port: '80'
            custom_fragment: ''
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            ssl_protocol: ''
            ssl_cipher: ''
            directories:
                avd_awfjzdghbrne:
                    path: /var/www/britishland/site
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - 'all granted'
                    custom_fragment: ''
                    files_match:
                        avdfm_43rdvwuoxfas:
                            path: \.php$
                            sethandler: 'proxy:fcgi://127.0.0.1:9000'
                            custom_fragment: ''
                            provider: filesmatch
                    provider: directory
        av_21w78u11o2gx:
            servername: drupal8.dev
            docroot: /var/www/drupal8/drupal
            port: '80'
            custom_fragment: ''
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            ssl_protocol: ''
            ssl_cipher: ''
            directories:
                avd_lquvb4k9wkyq:
                    path: /var/www/drupal8/drupal
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - 'all granted'
                    custom_fragment: ''
                    files_match:
                        avdfm_2q73n241ptd5:
                            path: \.php$
                            sethandler: 'proxy:fcgi://127.0.0.1:9000'
                            custom_fragment: ''
                            provider: filesmatch
                    provider: directory
        av_652j3veh3u99:
            servername: sandbox.dev
            docroot: /var/www/sandbox/drupal
            port: '80'
            custom_fragment: ''
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            ssl_protocol: ''
            ssl_cipher: ''
            directories:
                avd_pfti73upsb2k:
                    path: /var/www/sandbox/drupal
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - 'all granted'
                    custom_fragment: ''
                    files_match:
                        avdfm_5okvkjc2c7q8:
                            path: \.php$
                            sethandler: 'proxy:fcgi://127.0.0.1:9000'
                            custom_fragment: ''
                            provider: filesmatch
                    provider: directory
        av_4xxlgw7ccgq8:
            servername: airenergi.dev
            docroot: /var/www/airenergi/drupal
            port: '80'
            custom_fragment: ''
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            ssl_protocol: ''
            ssl_cipher: ''
            directories:
                avd_3h1xtu4xetez:
                    path: /var/www/airenergi/drupal
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - 'all granted'
                    custom_fragment: ''
                    files_match:
                        avdfm_ne2z0okt2bw6:
                            path: \.php$
                            sethandler: 'proxy:fcgi://127.0.0.1:9000'
                            custom_fragment: ''
                            provider: filesmatch
                    provider: directory
        av_c7au4cscarxq:
            servername: theculturediary.dev
            serveraliases:
                - tcd.local
            docroot: /var/www/theculturediary/drupal
            port: '80'
            custom_fragment: ''
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            ssl_protocol: ''
            ssl_cipher: ''
            directories:
                avd_6e69euegxce6:
                    path: /var/www/theculturediary/drupal
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - 'all granted'
                    custom_fragment: ''
                    files_match:
                        avdfm_fu7fc6yg1lmn:
                            path: \.php$
                            sethandler: 'proxy:fcgi://127.0.0.1:9000'
                            custom_fragment: ''
                            provider: filesmatch
                    provider: directory
        av_ka57dbophm35:
            servername: audioswap.dev
            docroot: /var/www/audioswap/drupal
            port: '80'
            custom_fragment: ''
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            ssl_protocol: ''
            ssl_cipher: ''
            directories:
                avd_u37qvp0wtsyq:
                    path: /var/www/audioswap/drupal
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - 'all granted'
                    custom_fragment: ''
                    files_match:
                        avdfm_ef9pdiz402ey:
                            path: \.php$
                            sethandler: 'proxy:fcgi://127.0.0.1:9000'
                            custom_fragment: ''
                            provider: filesmatch
                    provider: directory
        av_kslsm01yboyr:
            servername: aesg.dev
            docroot: /var/www/aesg/drupal
            port: '80'
            custom_fragment: ''
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            ssl_protocol: ''
            ssl_cipher: ''
            directories:
                avd_c2d9qytvbcvi:
                    path: /var/www/aesg/drupal
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - 'all granted'
                    custom_fragment: ''
                    files_match:
                        avdfm_mtmyi1jhfskr:
                            path: \.php$
                            sethandler: 'proxy:fcgi://127.0.0.1:9000'
                            custom_fragment: ''
                            provider: filesmatch
                    provider: directory
php:
    install: '1'
    settings:
        version: '56'
    modules:
        php:
            - cli
            - intl
            - mbstring
            - mcrypt
            - curl
            - gd
            - xmlrpc
        pear: {  }
        pecl: {  }
    ini:
        display_errors: 'On'
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
        date.timezone: UTC
        memory_limit: 512M
        post_max_size: 16M
        upload_max_filesize: 16M
    fpm_ini:
        error_log: /var/log/php-fpm.log
    fpm_pools:
        phpfp_cls5gqjhjdlw:
            ini:
                prefix: www
                listen: '127.0.0.1:9000'
                security.limit_extensions: .php
                user: www-user
                group: www-data
    composer: '1'
    composer_home: ''
xdebug:
    install: '1'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
blackfire:
    install: '0'
    settings:
        server_id: ''
        server_token: ''
        agent:
            http_proxy: ''
            https_proxy: ''
            log_file: stderr
            log_level: '1'
        php:
            agent_timeout: '0.25'
            log_file: ''
            log_level: '1'
xhprof:
    install: '0'
wpcli:
    install: '0'
    version: v0.21.1
drush:
    install: '1'
    version: 8.0.3
ruby:
    install: '1'
    versions:
        rv_p445kiqb61kk:
            default: '1'
            bundler: '1'
            version: 1.9.3
            gems:
                - deep_merge
                - activesupport
                - vine
python:
    install: '1'
    packages: {  }
    versions: {  }
nodejs:
    install: '0'
    settings:
        version: '5'
    npm_packages: {  }
hhvm:
    install: '0'
    nightly: 0
    composer: '1'
    composer_home: ''
    settings: {  }
    server_ini:
        hhvm.server.host: 127.0.0.1
        hhvm.server.port: '9000'
        hhvm.log.use_log_file: '1'
        hhvm.log.file: /var/log/hhvm/error.log
    php_ini:
        display_errors: 'On'
        error_reporting: '-1'
        date.timezone: UTC
mariadb:
    install: '1'
    settings:
        version: '10.1'
        root_password: '123'
        override_options: {  }
    adminer: 0
    users:
        mariadbnu_0yrst7mpcvkh:
            name: mcr_library
            password: mcr_library
        mariadbnu_zjxfvta1886i:
            name: westway
            password: westway
        mariadbnu_3hhakt2em0j9:
            name: mcr_townhall
            password: mcr_townhall
        mariadbnu_9or4e0vnriwu:
            name: sandbox
            password: sandbox
        mariadbnu_g41eajhyb7ic:
            name: drupal8
            password: drupal8
        mariadbnu_hpxacle61kz8:
            name: drakecircus
            password: drakecircus
        mariadbnu_u2te9x4f8ess:
            name: blissbritishland
            password: blissbritishland
        mariadbnu_h0gw102yhlgs:
            name: tcd
            password: password
        mariadbnu_ummmblu06jld:
            name: airenergi
            password: airenergi
        mariadbnu_cajyglap6kdb:
            name: audioswap
            password: audioswap
        mariadbnu_v7v64uw3h66m:
            name: aesg
            password: aesg
    databases:
        mariadbnd_jtuvdhyk1xa6:
            name: mcr_library
            sql: ''
        mariadbnd_it303gwpveen:
            name: westway
            sql: ''
        mariadbnd_3h87a43tj8eg:
            name: mcr_townhall
            sql: ''
        mariadbnd_beg37f4ir9bf:
            name: sandbox
            sql: ''
        mariadbnd_e18vhvd02w9s:
            name: drupal8
            sql: ''
        mariadbnd_u3j4p8qou604:
            name: drakecircus
            sql: ''
        mariadbnd_ebaq29gltb67:
            name: blissbritishland
            sql: ''
        mariadbnd_m22oavvnatxb:
            name: tcd_drupal
            sql: ''
        mariadbnd_49ky0o86sd8i:
            name: airenergi
            sql: ''
        mariadbnd_8tmjdsd7or9f:
            name: audioswap
            sql: ''
        mariadbnd_naoditu0ci54:
            name: aesg
            sql: ''
    grants:
        mariadbng_afag2uss67ov:
            user: mcr_library
            table: '*.*'
            privileges:
                - ALL
        mariadbng_avnde0g7zurc:
            user: westway
            table: '*.*'
            privileges:
                - ALL
        mariadbng_g2ogipom24a2:
            user: mcr_townhall
            table: '*.*'
            privileges:
                - ALL
        mariadbng_2lz49lnwg504:
            user: sandbox
            table: '*.*'
            privileges:
                - ALL
        mariadbng_eet38dfw4mjj:
            user: drupal8
            table: '*.*'
            privileges:
                - ALL
        mariadbng_allwjtb362gu:
            user: drakecircus
            table: '*.*'
            privileges:
                - ALL
        mariadbng_779ix7tzoc4g:
            user: blissbritishland
            table: '*.*'
            privileges:
                - ALL
        mariadbng_1uj50we3ysui:
            user: tcd
            table: '*.*'
            privileges:
                - ALL
        mariadbng_z0tvsd8kp4no:
            user: airenergi
            table: '*.*'
            privileges:
                - ALL
        mariadbng_efa7gvicrqhb:
            user: audioswap
            table: '*.*'
            privileges:
                - ALL
        mariadbng_16b63dmptqbj:
            user: aesg
            table: '*.*'
            privileges:
                - ALL
mysql:
    install: '0'
    settings:
        version: '5.6'
        root_password: '123'
        override_options: {  }
    adminer: 0
    users:
        mysqlnu_5nt3hnc60l87:
            name: dbuser
            password: '123'
    databases:
        mysqlnd_x1h8572mqkim:
            name: dbname
            sql: ''
    grants:
        mysqlng_q2yhefce624x:
            user: dbuser
            table: '*.*'
            privileges:
                - ALL
postgresql:
    install: '0'
    settings:
        global:
            encoding: UTF8
            version: '9.4'
        server:
            postgres_password: '123'
    databases: {  }
    users: {  }
    grants: {  }
    adminer: 0
mongodb:
    install: '0'
    settings:
        bind_ip: 127.0.0.1
        port: '27017'
    globals:
        version: 2.6.0
    databases: {  }
redis:
    install: '0'
    settings:
        port: '6379'
sqlite:
    install: '0'
    adminer: 0
    databases: {  }
mailhog:
    install: '0'
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '8025'
        path: /usr/local/bin/mailhog
beanstalkd:
    install: '0'
    settings:
        listenaddress: 0.0.0.0
        listenport: '11300'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: 0
rabbitmq:
    install: '0'
    settings:
        port: '5672'
    users: {  }
    vhosts: {  }
    plugins: {  }
elastic_search:
    install: '0'
    settings:
        version: 2.1.0
        java_install: true
    instances:
        esi_iothzr97whlq:
            name: es-01
solr:
    install: '1'
    settings:
        version: 4.10.2
        port: '8984'

`

**Comment by catalinux** [comment]
I had to add in my config file these two lines:

            - xml
            - libxml


php:
    install: '1'
    settings:
        version: '56'
    modules:
        php:
            - cli
            - memcached
            - curl
            - intl
            - mcrypt
            - mongo
            - imagick
            - mbstring
            - sqlite
            - xml
            - libxml
        pear: {  }
        pecl: {  }

**Comment by Machiel** [comment]
Adding `- xml` fixed it for me :)! Thanks @catalinux.
