### ISSUE TITLE
vagrant with elasticsearch error

### ISSUE THREAD

**Issue by jrmessias** [puphpet/puphpet#2239]
I create a vagrant vm with puphpet, only with elasticsearch and have a error in vagrant up.. 

config.yaml
`
vagrantfile:
    target: local
    vm:
        provider:
            local:
                box: puphpet/centos65-x64
                box_url: puphpet/centos65-x64
                box_version: '0'
                chosen_virtualizer: virtualbox
                virtualizers:
                    virtualbox:
                        modifyvm:
                            natdnshostresolver1: false
                        showgui: 0
                    vmware:
                        numvcpus: 1
                    parallels:
                        use_linked_clone: 0
                        check_guest_tools: 0
                        update_guest_tools: 0
                machines:
                    vflm_fmypr0i2oic8:
                        id: ecsearch
                        network:
                            private_network: 192.168.1.82
                            forwarded_port:
                                vflmnfp_qoc0sfiz25ra:
                                    host: '5772'
                                    guest: '22'
                        hostname: ecsearch.dev
                        memory: '512'
                        cpus: '1'
        provision:
            puppet:
                manifests_path: puphpet/puppet/manifests
                module_path: puphpet/puppet/modules
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
        synced_folder:
            vflsf_cgfg4lkp2kpa:
                source: ./
                target: /var/www
                sync_type: default
                smb:
                    smb_host: ''
                    smb_username: ''
                    smb_password: ''
                    mount_options:
                        dir_mode: '0775'
                        file_mode: '0664'
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    exclude:
                        - .vagrant/
                        - .git/
                    auto: 'true'
                owner: www-data
                group: www-data
        usable_port_range:
            start: 10200
            stop: 10500
        post_up_message: ''
    ssh:
        host: 'false'
        port: 'false'
        private_key_path: 'false'
        username: vagrant
        guest_port: 'false'
        keep_alive: '1'
        forward_agent: 'false'
        forward_x11: 'false'
        shell: 'bash -l'
        insert_key: 'false'
    vagrant:
        host: detect
    proxy:
        http: ''
        https: ''
        ftp: ''
        no_proxy: ''
        enabled: ''
server:
    install: '1'
    packages: {  }
users_groups:
    install: '1'
    groups: {  }
    users: {  }
locale:
    install: '1'
    settings:
        default_locale: pt_BR.UTF-8
        locales:
            - en_GB.UTF-8
            - en_US.UTF-8
            - pt_BR.UTF-8
        timezone: America/Sao_Paulo
firewall:
    install: '1'
    rules: {  }
cron:
    install: '1'
    jobs: {  }
nginx:
    install: '0'
    settings:
        default_vhost: 1
        proxy_buffer_size: 128k
        proxy_buffers: '4 256k'
        proxy_connect_timeout: 600s
        proxy_send_timeout: 600s
        proxy_read_timeout: 600s
        names_hash_bucket_size: 128
    upstreams: {  }
    vhosts:
        nxv_wy6rnzzx0jdo:
            server_name: ecommerce.dev
            www_root: /var/www/
            listen_port: '80'
            index_files:
                - index.html
                - index.htm
                - index.php
            client_max_body_size: 1m
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_port: '443'
            ssl_protocols: ''
            ssl_ciphers: ''
            rewrite_to_https: '1'
            spdy: '1'
            locations:
                nxvl_g6rugtvwps8j:
                    location: /
                    autoindex: 'off'
                    internal: 'false'
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
                    fastcgi: ''
                    fastcgi_index: ''
                    fastcgi_split_path: ''
                    proxy: ''
                    proxy_redirect: ''
                nxvl_i1kg5tgdetib:
                    location: '~ \.php$'
                    autoindex: 'off'
                    internal: 'false'
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
                    fastcgi: '127.0.0.1:9000'
                    fastcgi_index: index.php
                    fastcgi_split_path: '^(.+\.php)(/.*)$'
                    fast_cgi_params_extra:
                        - 'SCRIPT_FILENAME $request_filename'
                        - 'APP_ENV dev'
                    set:
                        - '$path_info $fastcgi_path_info'
                    proxy: ''
                    proxy_redirect: ''
    proxies: {  }
apache:
    install: '0'
    settings:
        version: 2.4
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - proxy_fcgi
        - rewrite
    vhosts:
        av_1sif0rrr242d:
            servername: awesome.dev
            serveraliases:
                - www.awesome.dev
            docroot: /var/www/awesome
            port: '80'
            setenv:
                - 'APP_ENV dev'
            setenvif:
                - 'Authorization "(.*)" HTTP_AUTHORIZATION=$1'
            custom_fragment: ''
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            ssl_protocol: ''
            ssl_cipher: ''
            directories:
                avd_i9hjr6l83u2o:
                    path: /var/www/awesome
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - 'all granted'
                    custom_fragment: ''
                    files_match:
                        avdfm_n0vp1k0lo13p:
                            path: \.php$
                            sethandler: 'proxy:fcgi://127.0.0.1:9000'
                            custom_fragment: ''
                            provider: filesmatch
                    provider: directory
php:
    install: '0'
    settings:
        version: '56'
    modules:
        php:
            - cli
            - intl
        pear: {  }
        pecl: {  }
    ini:
        display_errors: 'On'
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
        date.timezone: UTC
    fpm_ini:
        error_log: /var/log/php-fpm.log
    fpm_pools:
        phpfp_p68rw9sh2495:
            ini:
                prefix: www
                listen: '127.0.0.1:9000'
                security.limit_extensions: .php
                user: www-user
                group: www-data
    composer: '1'
    composer_home: ''
xdebug:
    install: '0'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
blackfire:
    install: '0'
    settings:
        server_id: ''
        server_token: ''
        agent:
            http_proxy: ''
            https_proxy: ''
            log_file: stderr
            log_level: '1'
        php:
            agent_timeout: '0.25'
            log_file: ''
            log_level: '1'
xhprof:
    install: '0'
wpcli:
    install: '0'
    version: v0.21.1
drush:
    install: '0'
    version: 6.3.0
ruby:
    install: '1'
    versions: {  }
python:
    install: '1'
    packages: {  }
    versions: {  }
nodejs:
    install: '0'
    settings:
        version: '5'
    npm_packages: {  }
hhvm:
    install: '0'
    nightly: 0
    composer: '1'
    composer_home: ''
    settings: {  }
    server_ini:
        hhvm.server.host: 127.0.0.1
        hhvm.server.port: '9000'
        hhvm.log.use_log_file: '1'
        hhvm.log.file: /var/log/hhvm/error.log
    php_ini:
        display_errors: 'On'
        error_reporting: '-1'
        date.timezone: UTC
mariadb:
    install: '0'
    settings:
        version: '10.1'
        root_password: '123'
        override_options: {  }
    adminer: '1'
    users:
        mariadbnu_vwltpldjyzj9:
            name: dbuser
            password: '123'
    databases:
        mariadbnd_lc907u0hjkrc:
            name: dbname
            sql: ''
    grants:
        mariadbng_evzifwb6acya:
            user: dbuser
            table: '*.*'
            privileges:
                - ALL
mysql:
    install: '0'
    settings:
        version: '5.7'
        root_password: '123'
        override_options: {  }
    adminer: '1'
    users:
        mysqlnu_tjobwymz5n4n:
            name: dbuser
            password: '123'
    databases:
        mysqlnd_q48dbu2n7sat:
            name: dbname
            sql: ''
    grants:
        mysqlng_rpv8vt068em6:
            user: dbuser
            table: '*.*'
            privileges:
                - ALL
postgresql:
    install: '0'
    settings:
        global:
            encoding: UTF8
            version: '9.4'
        server:
            postgres_password: '123'
    databases: {  }
    users: {  }
    grants: {  }
    adminer: 0
mongodb:
    install: '0'
    settings:
        bind_ip: 127.0.0.1
        port: '27017'
    globals:
        version: 2.6.0
    databases: {  }
redis:
    install: '0'
    settings:
        port: '6379'
sqlite:
    install: '0'
    adminer: 0
    databases: {  }
mailhog:
    install: '0'
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '8025'
        path: /usr/local/bin/mailhog
beanstalkd:
    install: '0'
    settings:
        listenaddress: 0.0.0.0
        listenport: '11300'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: 0
rabbitmq:
    install: '0'
    settings:
        port: '5672'
    users: {  }
    vhosts: {  }
    plugins: {  }
elastic_search:
    install: '1'
    settings:
        version: 2.1.0
        java_install: true
    instances:
        esi_6vtz1wpbl0n9:
            name: es-ecsearch
solr:
    install: '0'
    settings:
        version: 4.10.2
        port: '8984'

`

errors:
`
==> ecsearch: Info: /Stage[main]/Timezone/File[/etc/localtime]: Filebucketed /etc/localtime to puppet with sum c79354b8dbee09e62bbc3fb544853283
==> ecsearch: Notice: /Stage[main]/Timezone/File[/etc/localtime]/ensure: ensure changed 'file' to 'link'
==> ecsearch: Notice: /Stage[main]/Puphpet_elasticsearch/Puphpet::Firewall::Port[9200]/Firewall[100 tcp/9200]/ensure: created
==> ecsearch: Notice: /Stage[main]/Puphpet_firewall/Puphpet::Firewall::Port[22]/Firewall[100 tcp/22]/ensure: created
==> ecsearch: Notice: /Stage[main]/Puphpet::Firewall::Post/Firewall[999 drop all]/ensure: created
==> ecsearch: Notice: /Stage[main]/Elasticsearch::Package/Exec[create_package_dir_elasticsearch]/returns: executed successfully
==> ecsearch: Notice: /Stage[main]/Elasticsearch::Package/File[/opt/elasticsearch/swdl]/seluser: seluser changed 'unconfined_u' to 'system_u'
==> ecsearch: Error: wget --no-check-certificate -O /opt/elasticsearch/swdl/elasticsearch-2.1.0.noarch.rpm https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-2.1.0.noarch.rpm 2> /dev/null returned 8 instead of one of [0]
==> ecsearch: Error: /Stage[main]/Elasticsearch::Package/Exec[download_package_elasticsearch]/returns: change from notrun to 0 failed: wget --no-check-certificate -O /opt/elasticsearch/swdl/elasticsearch-2.1.0.noarch.rpm https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-2.1.0.noarch.rpm 2> /dev/null returned 8 instead of one of [0]
==> ecsearch: Notice: /Stage[main]/Elasticsearch::Package/Package[elasticsearch]: Dependency Exec[download_package_elasticsearch] has failures: true
==> ecsearch: Warning: /Stage[main]/Elasticsearch::Package/Package[elasticsearch]: Skipping because of failed dependencies
==> ecsearch: Info: Class[Elasticsearch::Package]: Unscheduling all events on Class[Elasticsearch::Package]
`

can help me?

**Comment by poldekch** [comment]
I'm experiencing the same issue for CentOS.
Seems like elasticsearch download base url is not valid.

**Comment by poldekch** [comment]
I just managed to successful provision by making following changes to file ElasticSearch.pp
line 12:
$url_base = "https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/rpm/elasticsearch/${version}"

and line 19:
$url = "${url_base}/elasticsearch-${version}.rpm"

Not sure if this is in line with puphpet development guidelines and this was not extensively tested, so no pull request created.
