### ISSUE TITLE
vagrant up fails at postgres

### ISSUE THREAD

**Issue by zoranf** [puphpet/puphpet#2242]
I rearchived the confgi.yml with puphet and wanted to vagrant up but it stops at postgres, here is my problem: 

leshop: Error: /Stage[main]/Puphpet_postgresql/Postgresql::Server::Database[postgres@]/Exec[/usr/lib/postgresql/9.3/bin/createdb --port='5432' --owner='postgres' --template=template0 --encoding 'UTF8'  '']: Failed to call refresh: /usr/lib/postgresql/9.3/bin/createdb --port='5432' --owner='postgres' --template=template0 --encoding 'UTF8'  '' returned 1 instead of one of [0]
==> leshop: Error: /Stage[main]/Puphpet_postgresql/Postgresql::Server::Database[postgres@]/Exec[/usr/lib/postgresql/9.3/bin/createdb --port='5432' --owner='postgres' --template=template0 --encoding 'UTF8'  '']: /usr/lib/postgresql/9.3/bin/createdb --port='5432' --owner='postgres' --template=template0 --encoding 'UTF8'  '' returned 1 instead of one of [0]
==> leshop: Notice: /Stage[main]/Puphpet_postgresql/Postgresql::Server::Database[postgres@]/Postgresql_psql[UPDATE pg_database SET datistemplate = false WHERE datname = '']/command: command changed 'notrun' to 'UPDATE pg_database SET datistemplate = false WHERE datname = '''
==> leshop: Notice: /Stage[main]/Puphpet_postgresql/Puphpet::Php::Module[pgsql]/Php::Module[pgsql]/Package[PhpModule_pgsql]/ensure: created
==> leshop: Info: /Stage[main]/Puphpet_postgresql/Puphpet::Php::Module[pgsql]/Php::Module[pgsql]/Package[PhpModule_pgsql]: Scheduling refresh of Service[php5.6-fpm]
==> leshop: Notice: /Stage[main]/Puphpet_php/Service[php5.6-fpm]: Dependency Package[PhpModule_memcache] has failures: true
==> leshop: Notice: /Stage[main]/Puphpet_php/Service[php5.6-fpm]: Dependency Exec[pecl-pecl_http] has failures: true
==> leshop: Info: /Stage[main]/Puphpet_php/Service[php5.6-fpm]: Unscheduling all events on Service[php5.6-fpm]
==> leshop: Info: Class[Puphpet_php]: Unscheduling all events on Class[Puphpet_php]
==> leshop: Warning: /Stage[main]/Puphpet_php/Service[php5.6-fpm]: Skipping because of failed dependencies
==> leshop: Info: Stage[main]: Unscheduling all events on Stage[main]
==> leshop: Info: Creating state file /opt/puppetlabs/puppet/cache/state/state.yaml
==> leshop: Notice: Applied catalog in 509.49 seconds
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

**Comment by zoranf** [comment]
I also posted this probem on vagrant issues, and they said it's puphpet fault.

**Comment by rastafermo** [comment]
Hi guys. Any info about what they are going to do to solve it? Did they just say 'our fault'? Is there a temporary solution or hot fix?

Thank you

**Comment by jtreminio** [comment]
Need your config.yaml.

**Comment by zoranf** [comment]
Actualy i solved it already, the problem was with users for postgres. They weren't correctly set.
