### ISSUE TITLE
Ubuntu1404-x32 fails on vagrant up

### ISSUE THREAD

**Issue by deichbrise** [puphpet/puphpet#2247]
I build a new standard Vagrant Box with Puphpet. It works fine on my Mac OSX host, but fails on a Windows 10 machine. I got a boot_timeout when vagrant up is trying to connect per ssh to the vagrant box. I enable the gui and the startup screen saying:
  waiting for network configuration
followed by 
  waiting an additional 60 seconds for network configuration

Does somebody know how to fix this issue?

**Comment by jtreminio** [comment]
Disable your firewall, allow through your antivirus. Not really a puphpet issue, though

**Comment by intheweb** [comment]
I can confirm that Ubuntu 14.04 x32 is not booting correct with Virtualbox on a Windows 7 machine.
The instance is not receiving a network link from Virtualbox.

Maybe it is not Puphpet related, but it happens when I'm downloading the image which is provided by Puphpet.

**Comment by jtreminio** [comment]
Sounds like a network and/or vagrant issue.
