### ISSUE TITLE
Feature request: support for specifying owner on sync folders

### ISSUE THREAD

**Issue by rguerreiro** [puphpet/puphpet#2249]
In my scenario I'm syncing to a folder that will be created and I would like the user (e.g. `vagrant`) to take ownership. I cannot do this in the current GUI. It seems possible to implement, according to the vagrant docs (https://www.vagrantup.com/docs/synced-folders/basic_usage.html).

As we speak, the folder is created but the owner is `www-data` (running a ubuntu 14.04 VM).

Since this is not an issue I didn't posted my `config.yml`.

**Comment by rguerreiro** [comment]
It seems that already exists [link](https://github.com/puphpet/puphpet/blob/master/src/Puphpet/MainBundle/Resources/views/vagrantfile-local/sections/synced-folder.html.twig#L278).

Why hidden?

**Comment by jtreminio** [comment]
It's hidden for power users. You can set it yourself and then if you reupload your config.yaml to the gui it'll keep your settings!
