### ISSUE TITLE
PHP subversions are not supported (7.0.x), only major versions (7.0) via config.yaml

### ISSUE THREAD

**Issue by mike-source** [puphpet/puphpet#2254]
This came up for me when using PHP 7  (e.g. `version: '70'` in config.yaml). There doesn't seem to be any control over which sub-sub-version (the third decimal place) puphpet generated machines will use, so during a typical `vagrant provision`, its possible with these settings that PHP 7.0.4 will upgrade to PHP 7.0.5 without your control.

See: http://stackoverflow.com/questions/36359099/make-php-on-a-puphpet-vagrant-box-use-specific-sub-version-e-g-7-0-4-vs-7-0-5

@jtreminio replied:

> Unfortunately subversions are not supported (7.0.x), only major versions (7.0).
> 
> This is due to the absolutely insane way each distro and even each PHP version is so different to the other in regards to INI locations and module directories. It's ridiculous.
> 
> What could easily be added is support for ensure field to the YAML file that you could pass your specific version to. Mind opening a ticket on my github tracker to enable this?

**Comment by patkar** [comment]
That's the spirit of using a apt/yum!

**Comment by jtreminio** [comment]
Unfortunately I do not believe this is possible. Unless I am mistaken, the Ubuntu repo PuPHPet uses only keeps the latest version, removing previous: https://launchpad.net/~ondrej/+archive/ubuntu/php
