### ISSUE TITLE
Any plans for Debian 8?

### ISSUE THREAD

**Issue by rickmills** [puphpet/puphpet#2256]
Would be really helpful if Debian 8 (Jessie) were to be added. I was a little surprised that it's not already on the list given it's wide adoption over the last year.

**Comment by rlweb** [comment]
Also, Ubuntu which will have its LTS released this month!

**Comment by jtreminio** [comment]
"Not really".

I'm seriously considering dropping Debian support altogether. Stable is far too slow and it's a pain to keep matching its software versions with what I can grab for Ubuntu and CentOS.
