### ISSUE TITLE
Set pecl to specific version for PHP version compatibility

### ISSUE THREAD

**Issue by Mondane** [puphpet/puphpet#2258]
As jeromegamez commented: https://github.com/puphpet/puphpet/issues/1821#issuecomment-194347850 . The latest stable pecl requires PHP 7.0 or newer. This is a problem when you have a PuPHPet config with PHP 5.6.

How to set pecl to a specific version and can PuPHPet do this automatically?

**Comment by spekary** [comment]
The comment you refer to is saying that the latest pecl_http requires 7.0, not pecl itself.

**Comment by Mondane** [comment]
That's correct. Because the latest Pecl is used by PuPHPet, also the latest pecl_http is installed. If the pecl version could be set to a specific version, that would fix it. But, perhaps, it's only needed to specify the version of extensions to be installed, like explained here:

http://web.onassar.com/blog/2012/09/23/installing-a-specific-pecl-extension-version/
