### ISSUE TITLE
Error with RVM certificates on vagrant up

### ISSUE THREAD

**Issue by NoelDavies** [puphpet/puphpet#2259]
When I run a vagrant provision, I get the following error:

`=> local.dev: Notice: /Stage[main]/Apache::Service/Service[httpd]/ensure: ensure changed 'stopped' to 'running'
==> local.dev: Info: /Stage[main]/Apache::Service/Service[httpd]: Unscheduling refresh on Service[httpd]
==> local.dev: Notice: /Stage[main]/Puphpet_apache/Exec[Set /var/www/html/index.html contents]/returns: executed successfully
==> local.dev: Notice: /Stage[main]/Puphpet_mysql/Mysql_database[opal]/ensure: created
==> local.dev: Notice: /Stage[main]/Puphpet_ruby/Puphpet::Ruby::Install[rv_07nkqjdg45pi]/Rvm_system_ruby[1.9.3]/ensure: created
==> local.dev: Error: Execution of '/usr/local/rvm/bin/rvm 1.9.3 do gem install --no-rdoc --no-ri deep_merge' returned 1: ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
==> local.dev:     SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (https://your-dns-needs-immediate-attention.dev/quick/Marshal.4.8/deep_merge-1.0.1.gemspec.rz)
==> local.dev: Error: /Stage[main]/Puphpet_ruby/Puphpet::Ruby::Install[rv_07nkqjdg45pi]/Rvm_gem[deep_merge]/ensure: change from absent to present failed: Execution of '/usr/local/rvm/bin/rvm 1.9.3 do gem install --no-rdoc --no-ri deep_merge' returned 1: ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
==> local.dev:     SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (https://your-dns-needs-immediate-attention.dev/quick/Marshal.4.8/deep_merge-1.0.1.gemspec.rz)
==> local.dev: Error: Execution of '/usr/local/rvm/bin/rvm 1.9.3 do gem install --no-rdoc --no-ri activesupport' returned 1: ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
==> local.dev:     SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (https://your-dns-needs-immediate-attention.dev/quick/Marshal.4.8/activesupport-4.2.6.gemspec.rz)
==> local.dev: Error: /Stage[main]/Puphpet_ruby/Puphpet::Ruby::Install[rv_07nkqjdg45pi]/Rvm_gem[activesupport]/ensure: change from absent to present failed: Execution of '/usr/local/rvm/bin/rvm 1.9.3 do gem install --no-rdoc --no-ri activesupport' returned 1: ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
==> local.dev:     SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (https://your-dns-needs-immediate-attention.dev/quick/Marshal.4.8/activesupport-4.2.6.gemspec.rz)
==> local.dev: Error: Execution of '/usr/local/rvm/bin/rvm 1.9.3 do gem install --no-rdoc --no-ri vine' returned 1: ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
==> local.dev:     SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (https://your-dns-needs-immediate-attention.dev/quick/Marshal.4.8/vine-0.2.gemspec.rz)
==> local.dev: Error: /Stage[main]/Puphpet_ruby/Puphpet::Ruby::Install[rv_07nkqjdg45pi]/Rvm_gem[vine]/ensure: change from absent to present failed: Execution of '/usr/local/rvm/bin/rvm 1.9.3 do gem install --no-rdoc --no-ri vine' returned 1: ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
==> local.dev:     SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (https://your-dns-needs-immediate-attention.dev/quick/Marshal.4.8/vine-0.2.gemspec.rz)
==> local.dev: Info: Puphpet::Ruby::Install[rv_07nkqjdg45pi]: Unscheduling all events on Puphpet::Ruby::Install[rv_07nkqjdg45pi]`

I've tried:

- enabling natdnshostresolver1: true but to no avail
- I've tried upgrading ruby in the config.yml to 2.0.3, again, nothing. I've changed local DNS, and even talked to the Techs, but nobody can seem to work it out. This is all directly from the puphpet site.. I'm lost. It worked after a re-install yesterday.. not so much today.

**Comment by fnagel** [comment]
Same issue here. Build new VM yesterday and did multiple provisions without issues. Today provisioning fails with following error:

````
==> project: ERROR:  Could not find a valid gem 'deep_merge' (>= 0), here is why:
==> project:           Unable to download data from https://rubygems.org/ - no such name (https://rubygems.org/latest_specs.4.8.gz)
==> project: ERROR:  Could not find a valid gem 'activesupport' (>= 0), here is why:
==> project:           Unable to download data from https://rubygems.org/ - no such name (https://rubygems.org/latest_specs.4.8.gz)
==> project: ERROR:  Could not find a valid gem 'vine' (>= 0), here is why:
==> project:           Unable to download data from https://rubygems.org/ - no such name (https://rubygems.org/latest_specs.4.8.gz)
````

**Comment by steros** [comment]
I did:
- vagrant up
- vagrant ssh
- sudo apt-get update && sudo apt-get upgrade
- vagrant destroy
- vagrant up

fixed my rvm error, seems the key was outdated

**Comment by NoelDavies** [comment]
@steros I did the same, forgot to post on here, works fine now.

**Comment by loclac** [comment]
@steros The same for me. Thanks, apt-get update and apt-get upgrade on VM solved the problem

**Comment by Mark-Creeten** [comment]
confirmed, works fine. except for the "vagrant destroy" part, i omitted that part, just did a "vagrant up --provision"

**Comment by aurawindsurfing** [comment]
same here: sudo apt-get update && sudo apt-get upgrade did the trick!

**Comment by Bengolino** [comment]
Perfect, thanks. after the update, only need to "vagrant up --provision"
