### ISSUE TITLE
Allow root or another user from all IP's

### ISSUE THREAD

**Issue by malutanpetronel** [puphpet/puphpet#2261]
Hi all

I would like to be able to 

GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' IDENTIFIED BY '123'; 

in order to be able to run my phpunit tests from outside my vagrant machine

Can you please show me where in the config.yaml I can add the necesarily lines to run the above command ?

With kind regards

**Comment by catalinux** [comment]
mysql:
    install: '1'
    settings:
----------
    grants:
        mysqlng_klv6iniehw7x:
            user: dbuser
            table: '*.*'
            privileges:
                - ALL

**Comment by malutanpetronel** [comment]
Normally yes... I did tried that.

What we need for beeing allowed to connect from the host machine to the vagrant is a bind-address in the my.cnf file on etc/mysqld/my.cnf

bind-address: 0.0.0.0
where the default is 127.0.0.1

Can this be accomplished somehow ?
Thx

**Comment by catalinux** [comment]
Nope :( 

I was doing this (changing bind addresa) with a sed comand by hand ( i could not figure the way I could ad my custom scripts)

**Comment by jtreminio** [comment]
In your config.yaml:

    mysql:
        install: '1'
        settings:
            version: '5.7'
            root_password: '123'
            override_options:
                mysqld:
                    bind-address: 0.0.0.0
