### ISSUE TITLE
PgAdmin 3 error connecting to the server

### ISSUE THREAD

**Issue by lhavi** [puphpet/puphpet#2267]
I tried connect to centos on vagrant+puphet. But i see error connecting to the server server closed the connection unexpectedly
I use connecting via ssh tunnel as described in documentation :
Connect using SSH tunnel, username vagrant and SSH key generated at puphpet/files/dot/ssh/id_rsa. This key is generated after your initial $ vagrant up!

**Comment by jtreminio** [comment]
Needs far more detail. Open a new issue if you still have it.
