### ISSUE TITLE
PHP 5.x should come with simplexml

### ISSUE THREAD

**Issue by ionas** [puphpet/puphpet#2269]
When copying a configuration today I had missing SimpleXML issues *again*.
I think SimpleXML should be by default added to the list of php modules as it is a very common extension.

**Comment by spekary** [comment]
see #2280 

apt-get install php5.6-xml

**Comment by ionas** [comment]
@spekary yes I did add simplexml to config.yaml under php modules - you can also use the interface in puphpet.com - however it should come pre-installed at all times.

**Comment by spekary** [comment]
That didn't work for me. I got messages that simplexml was included in xml support. 

You are right that we shouldn't have to add anything. XML support and SimpleXML are supposed to be in PHP by default according to the PHP doc, unless you explicitly turn it off. I was just suggesting a way to make it work for now.

**Comment by ionas** [comment]
For me it is like this:
- sometimes it works without simplexml
- it seems to almost always work with simplexml
- afair sometimes I had to add dom and xml instead of just simplexml
@jtreminio explained to me on freenode that it is due to the parts of the build stack that are maintained by other parties. However in case adding simplexml ALL time works ALL times that's what should IMHO be done.

**Comment by jtreminio** [comment]
Closed by be54496
