### ISSUE TITLE
New Install with default SSL, no snakeoil file

### ISSUE THREAD

**Issue by spekary** [puphpet/puphpet#2284]
Ubuntu 64-bit, Mac OS Yosemite, latest versions of Vagrant and VirtualBox, PHP 5.6.

Installing webservers for both SSL and non-SSL. Leaving SSL blank as instructed to do on PUPHPET website for default certs.

SSH in and try to start apache, and I get this error:

AH00526: Syntax error on line 34 of /etc/apache2/sites-enabled/10-default_vhost_443.conf:
SSLCertificateKeyFile: file '/etc/ssl/private/ssl-cert-snakeoil.key' does not exist or is empty
Action 'start' failed.
The Apache error log may have more information.

Complete yaml file:

vagrantfile:
    target: local
    vm:
        provider:
            local:
                box: puphpet/debian75-x64
                box_url: puphpet/debian75-x64
                box_version: '0'
                chosen_virtualizer: virtualbox
                virtualizers:
                    virtualbox:
                        modifyvm:
                            natdnshostresolver1: false
                        showgui: 0
                    vmware:
                        numvcpus: 1
                    parallels:
                        use_linked_clone: 0
                        check_guest_tools: 0
                        update_guest_tools: 0
                machines:
                    vflm_sun9qm5z3hh0:
                        id: ryaa
                        hostname: ryaa.dev
                        network:
                            private_network: 192.168.56.101
                            forwarded_port:
                                vflmnfp_tdsnbjnl3vqa:
                                    host: '9338'
                                    guest: '22'
                        memory: '512'
                        cpus: '1'
        provision:
            puppet:
                manifests_path: puphpet/puppet/manifests
                module_path: puphpet/puppet/modules
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
        synced_folder:
            vflsf_2f3i2bo37ega:
                source: /Sites/home
                target: /var/www
                sync_type: default
                smb:
                    smb_host: ''
                    smb_username: ''
                    smb_password: ''
                    mount_options:
                        dir_mode: '0775'
                        file_mode: '0664'
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    exclude:
                        - .vagrant/
                        - .git/
                    auto: 'true'
                owner: www-data
                group: www-data
            vflsf_wemsr82vtvpe:
                source: /Sites/ryaa
                target: /home/ryaa
                sync_type: default
                smb:
                    smb_host: ''
                    smb_username: ''
                    smb_password: ''
                    mount_options:
                        dir_mode: '0775'
                        file_mode: '0664'
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    exclude:
                        - .vagrant/
                        - .git/
                    auto: 'true'
                owner: www-data
                group: www-data
            vflsf_63kv4a83rj8b:
                source: /Sites/nopro
                target: /home/nopro
                sync_type: default
                smb:
                    smb_host: ''
                    smb_username: ''
                    smb_password: ''
                    mount_options:
                        dir_mode: '0775'
                        file_mode: '0664'
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    exclude:
                        - .vagrant/
                        - .git/
                    auto: 'true'
                owner: www-data
                group: www-data
        usable_port_range:
            start: 10200
            stop: 10500
        post_up_message: ''
    ssh:
        host: 'false'
        port: 'false'
        private_key_path: 'false'
        username: vagrant
        guest_port: 'false'
        keep_alive: '1'
        forward_agent: 'false'
        forward_x11: 'false'
        shell: 'bash -l'
        insert_key: 'false'
    vagrant:
        host: detect
    proxy:
        http: ''
        https: ''
        ftp: ''
        no_proxy: ''
server:
    install: '1'
    packages:
        - nano
        - vim
users_groups:
    install: '1'
    groups:
        - ryaa
        - nopro
    users:
        - 'ryaa:ryaa:www-data'
        - 'nopro:nopro:www-data'
locale:
    install: '1'
    settings:
        default_locale: en_US.UTF-8
        locales:
            - en_GB.UTF-8
            - en_US.UTF-8
        timezone: America/Los_Angeles
firewall:
    install: '1'
    rules: {  }
cron:
    install: '1'
    jobs: {  }
nginx:
    install: '0'
    settings:
        default_vhost: 1
        proxy_buffer_size: 128k
        proxy_buffers: '4 256k'
        proxy_connect_timeout: 600s
        proxy_send_timeout: 600s
        proxy_read_timeout: 600s
        names_hash_bucket_size: 128
    upstreams: {  }
    vhosts:
        nxv_ry2ahbv3ksw5:
            server_name: awesome.dev
            server_aliases:
                - www.awesome.dev
            www_root: /var/www/awesome
            listen_port: '80'
            index_files:
                - index.html
                - index.htm
                - index.php
            client_max_body_size: 1m
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_port: '443'
            ssl_protocols: ''
            ssl_ciphers: ''
            rewrite_to_https: '1'
            spdy: '1'
            locations:
                nxvl_iirnz1i9hfly:
                    location: /
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
                    fastcgi: ''
                    fastcgi_index: ''
                    fastcgi_split_path: ''
                    proxy: ''
                    proxy_redirect: ''
                nxvl_2pgmf0ofmpp9:
                    location: '~ \.php$'
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
                    fastcgi: '127.0.0.1:9000'
                    fastcgi_index: index.php
                    fastcgi_split_path: '^(.+\.php)(/.*)$'
                    fast_cgi_params_extra:
                        - 'SCRIPT_FILENAME $request_filename'
                        - 'APP_ENV dev'
                    set:
                        - '$path_info $fastcgi_path_info'
                    proxy: ''
                    proxy_redirect: ''
    proxies: {  }
apache:
    install: '1'
    settings:
        version: 2.4
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - proxy_fcgi
        - rewrite
    vhosts:
        av_vo8c1r6oyhf9:
            servername: ryaa.dev
            docroot: /home/ryaa/public_html
            port: '80'
            setenv:
                - 'APP_ENV dev'
            setenvif:
                - 'Authorization "(.*)" HTTP_AUTHORIZATION=$1'
            custom_fragment: ''
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            ssl_protocol: ''
            ssl_cipher: ''
            directories:
                avd_bp0je2vukr4r:
                    path: /home/ryaa/public_html
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - 'all granted'
                    custom_fragment: ''
                    files_match:
                        avdfm_c6lmmkcbbz0p:
                            path: \.php$
                            sethandler: 'proxy:fcgi://127.0.0.1:9006'
                            custom_fragment: ''
                            provider: filesmatch
                    provider: directory
        av_k0b9e9e3bjg6:
            servername: ryaa.dev
            docroot: /home/ryaa/public_html
            port: '443'
            setenv:
                - 'APP_ENV dev'
            setenvif:
                - 'Authorization "(.*)" HTTP_AUTHORIZATION=$1'
            custom_fragment: ''
            ssl: '1'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            ssl_protocol: ''
            ssl_cipher: ''
            directories:
                avd_glxo0glhovtv:
                    path: /home/ryaa/public_html
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - 'all granted'
                    custom_fragment: ''
                    files_match:
                        avdfm_ar8qc86clgbc:
                            path: \.php$
                            sethandler: 'proxy:fcgi://127.0.0.1:9006'
                            custom_fragment: ''
                            provider: filesmatch
                    provider: directory
        av_azli7zac9r6h:
            servername: home.dev
            docroot: /var/www
            port: '80'
            setenv:
                - 'APP_ENV dev'
            custom_fragment: ''
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            ssl_protocol: ''
            ssl_cipher: ''
            directories:
                avd_zxwg7nhalsgn:
                    path: /var/www
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - 'all granted'
                    custom_fragment: ''
                    files_match:
                        avdfm_f86kma5rsq5c:
                            path: \.php$
                            sethandler: 'proxy:fcgi://127.0.0.1:9006'
                            custom_fragment: ''
                            provider: filesmatch
                    provider: directory
        av_azli7zac9r6g:
            servername: home.dev
            docroot: /var/www
            port: '443'
            setenv:
                - 'APP_ENV dev'
            custom_fragment: ''
            ssl: '1'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            ssl_protocol: ''
            ssl_cipher: ''
            directories:
                avd_zxwg7nhalsgm:
                    path: /var/www
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - 'all granted'
                    custom_fragment: ''
                    files_match:
                        avdfm_f86kma5rsq5b:
                            path: \.php$
                            sethandler: 'proxy:fcgi://127.0.0.1:9006'
                            custom_fragment: ''
                            provider: filesmatch
                    provider: directory
        av_bihy7nn6awm1:
            servername: nopro.dev
            serveraliases:
                - www.nopro.dev
            docroot: /home/nopro/public_html
            port: '80'
            setenv:
                - 'APP_ENV dev'
            custom_fragment: ''
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            ssl_protocol: ''
            ssl_cipher: ''
            directories:
                avd_f2qj028g4buo:
                    path: /home/nopro/public_html
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - 'all granted'
                    custom_fragment: ''
                    files_match:
                        avdfm_ufx4v5vtndjl:
                            path: \.php$
                            sethandler: 'proxy:fcgi://127.0.0.1:9006'
                            custom_fragment: ''
                            provider: filesmatch
                    provider: directory
        av_bihy7nn6awm0:
            servername: nopro.dev
            serveraliases:
                - www.nopro.dev
            docroot: /home/nopro/public_html
            port: '443'
            setenv:
                - 'APP_ENV dev'
            custom_fragment: ''
            ssl: '1'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            ssl_protocol: ''
            ssl_cipher: ''
            directories:
                avd_f2qj028g4bun:
                    path: /home/nopro/public_html
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - 'all granted'
                    custom_fragment: ''
                    files_match:
                        avdfm_ufx4v5vtndjk:
                            path: \.php$
                            sethandler: 'proxy:fcgi://127.0.0.1:9006'
                            custom_fragment: ''
                            provider: filesmatch
                    provider: directory
letsencrypt:
    install: '1'
    settings:
        email: ''
    domains: {  }
php:
    install: '1'
    settings:
        version: '56'
    modules:
        php:
            - cli
            - intl
            - mcrypt
            - imagick
            - curl
            - gd
        pear: {  }
        pecl:
            - pecl_http
            - APCu
    ini:
        display_errors: 'On'
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
        session.gc_maxlifetime: '72000'
        date.timezone=America/Los_Angeles: '0'
        date.time_zone=: America/Los_Angeles
        date.timezone: America/Los_Angeles
        max_execution_time: '60'
        max_input_time: '120'
        memory_limit: 512M
        upload_max_filesize: 512M
        post_max_size: 512M
        display_startup_errors: 'On'
    fpm_ini:
        error_log: /var/log/php-fpm.log
    fpm_pools:
        phpfp_u6ptbjnkbzei:
            ini:
                prefix: www
                security.limit_extensions: .php
                user: www-user
                group: www-data
                listen: '127.0.0.1:9006'
    composer: '1'
    composer_home: ''
xdebug:
    install: '1'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
blackfire:
    install: '0'
    settings:
        server_id: ''
        server_token: ''
        agent:
            http_proxy: ''
            https_proxy: ''
            log_file: stderr
            log_level: '1'
        php:
            agent_timeout: '0.25'
            log_file: ''
            log_level: '1'
xhprof:
    install: '0'
wpcli:
    install: '0'
    version: v0.21.1
drush:
    install: '0'
    version: 8.0.5
ruby:
    install: '1'
    versions:
        rv_trvhy4oyunz9:
            default: '1'
            bundler: '1'
            version: 1.9.3
            gems:
                - deep_merge
                - activesupport
                - vine
python:
    install: '1'
    packages: {  }
    versions: {  }
nodejs:
    install: '0'
    settings:
        version: '5'
    npm_packages: {  }
hhvm:
    install: '0'
    nightly: 0
    composer: '1'
    composer_home: ''
    settings: {  }
    server_ini:
        hhvm.server.host: 127.0.0.1
        hhvm.server.port: '9000'
        hhvm.log.use_log_file: '1'
        hhvm.log.file: /var/log/hhvm/error.log
    php_ini:
        display_errors: 'On'
        error_reporting: '-1'
        date.timezone: UTC
mariadb:
    install: '0'
    settings:
        version: '10.1'
        root_password: '123'
        override_options: {  }
    adminer: 0
    users:
        mariadbnu_ddjf15rdst11:
            name: dbuser
            password: '123'
    databases:
        mariadbnd_14zc20gsa02b:
            name: dbname
            sql: ''
    grants:
        mariadbng_5ij9310qmu6x:
            user: dbuser
            table: '*.*'
            privileges:
                - ALL
mysql:
    install: '1'
    settings:
        version: '5.6'
        root_password: '12345'
        override_options: {  }
    adminer: 0
    users:
        mysqlnu_f8sqpvozl3u7:
            name: ryaa_user
            password: Isaiah
        mysqlnu_aa4o4823449f:
            name: nopro_user
            password: et8Ryp79EeS5KRmf
        mysqlnu_f501sevw6598:
            name: pma
            password: ''
    databases:
        mysqlnd_gz2qp6qkjpi6:
            name: ryaa2
            sql: /home/ryaa/mysql/ryaa2.sql
        mysqlnd_5clot5bkociu:
            name: qcubed
            sql: /var/www/qcubed/vendor/qcubed/framework/assets/php/examples/mysql_innodb.sql
        mysqlnd_eoy7jnclke2g:
            name: nonpro
            sql: /home/nopro/mysql/nonpro.sql
        mysqlnd_zu1tgaj7jlb5:
            name: ryaa_photo
            sql: /home/ryaa/mysql/ryaa_photo.sql
        mysqlnd_8j1o05x4ohj2:
            name: ryaa_data
            sql: /home/ryaa/mysql/ryaa_data.sql
        mysqlnd_6wm2dxma0i26:
            name: epaparrc
            sql: ''
    grants:
        mysqlng_cd79vrfz9d20:
            user: root@localhost
            table: '*.*'
            privileges:
                - ALL
        mysqlng_3i0s9fisnvo4:
            user: pma
            table: '*.*'
            privileges:
                - ALL
        mysqlng_80v5v3x4ok1f:
            user: ryaa_user
            table: '*.*'
            privileges:
                - UPDATE
                - SELECT
                - DELETE
                - INSERT
        mysqlng_gt8pw329zhff:
            user: nonpro_user
            table: 'nonpro.*'
            privileges:
                - UPDATE
                - SELECT
                - DELETE
                - INSERT
postgresql:
    install: '1'
    settings:
        global:
            encoding: UTF8
            version: '9.3'
        server:
            postgres_password: '12345'
    databases:
        postsqlnd_wyzgxawx5mfv:
            dbname: qcubed
            owner: qcubed
    users:
        postsqlnu_b9cmxnopfzc9:
            username: qcubed
            password: qcubed
            superuser: '1'
    grants:
        postsqlng_xtz4sq6zgptu:
            role: qcubed
            db: qcubed
            privilege:
                - ALL
    adminer: 0
mongodb:
    install: '0'
    settings:
        bind_ip: 127.0.0.1
        port: '27017'
    globals:
        version: 2.6.0
    databases: {  }
redis:
    install: '0'
    settings:
        port: '6379'
sqlite:
    install: '0'
    adminer: 0
    databases: {  }
mailhog:
    install: '0'
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '8025'
        path: /usr/local/bin/mailhog
beanstalkd:
    install: '0'
    settings:
        listenaddress: 0.0.0.0
        listenport: '11300'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: 0
rabbitmq:
    install: '0'
    settings:
        port: '5672'
    users: {  }
    vhosts: {  }
    plugins: {  }
elastic_search:
    install: '0'
    settings:
        version: 2.3.1
        java_install: true
    instances:
        esi_uvqnczlc7bx9:
            name: es-01
solr:
    install: '0'
    settings:
        version: 4.10.2
        port: '8984'

**Comment by mdjaman** [comment]
Any solution?

**Comment by jtreminio** [comment]
Fixed in latest release.
