### ISSUE TITLE
repo.puphpet.com 'Moved Permanently'

### ISSUE THREAD

**Issue by Sharkfinger** [puphpet/puphpet#2286]
Upgraded to latest Virtualbox (5.0.18) and vagrant (1.8.1) and started getting the following error when starting up the VM:

=================================

==> default: Notice: /Stage[main]/Main/Exec[dotfiles]/returns: executed successfully
==> default: Notice: /Stage[main]/Main/File[/usr/local/checkmasterws]/ensure: created
==> default: Notice: /Stage[main]/Apt::Backports/Apt::Source[backports]/File[backports.list]/ensure: created
==> default: Info: /Stage[main]/Apt::Backports/Apt::Source[backports]/File[backports.list]: Scheduling refresh of Exec[apt_update]
==> default: Notice: /Stage[main]/Apt::Update/Exec[apt_update]/returns: Get:1 http://ftp.debian.org wheezy-backports Release.gpg [1,554 B]
==> default: Notice: /Stage[main]/Apt::Update/Exec[apt_update]/returns: Get:2 http://security.debian.org wheezy/updates Release.gpg [1,554 B]
==> default: Notice: /Stage[main]/Apt::Update/Exec[apt_update]/returns: Get:3 http://ftp.debian.org wheezy-backports Release [161 kB]
==> default: Notice: /Stage[main]/Apt::Update/Exec[apt_update]/returns: Get:4 http://security.debian.org wheezy/updates Release [102 kB]
==> default: Notice: /Stage[main]/Apt::Update/Exec[apt_update]/returns: Ign http://repo.puphpet.com wheezy Release.gpg
==> default: Notice: /Stage[main]/Apt::Update/Exec[apt_update]/returns: Get:5 http://http.debian.net wheezy-updates Release.gpg [1,554 B]
==> default: Notice: /Stage[main]/Apt::Update/Exec[apt_update]/returns: Get:6 http://http.debian.net wheezy-updates Release [151 kB]
==> default: Notice: /Stage[main]/Apt::Update/Exec[apt_update]/returns: Get:7 http://ftp.debian.org wheezy-backports/main Sources [449 kB]
==> default: Notice: /Stage[main]/Apt::Update/Exec[apt_update]/returns: Get:8 http://http.debian.net wheezy Release.gpg [2,373 B]
==> default: Notice: /Stage[main]/Apt::Update/Exec[apt_update]/returns: Ign http://repo.puphpet.com wheezy Release
==> default: Notice: /Stage[main]/Apt::Update/Exec[apt_update]/returns: Get:9 http://security.debian.org wheezy/updates/main Sources [212 kB]
==> default: Notice: /Stage[main]/Apt::Update/Exec[apt_update]/returns: Get:10 http://ftp.debian.org wheezy-backports/contrib Sources [7,880 B]
==> default: Notice: /Stage[main]/Apt::Update/Exec[apt_update]/returns: Get:11 http://security.debian.org wheezy/updates/main amd64 Packages [347 kB]
==> default: Notice: /Stage[main]/Apt::Update/Exec[apt_update]/returns: Get:12 http://ftp.debian.org wheezy-backports/non-free Sources [8,948 B]
==> default: Notice: /Stage[main]/Apt::Update/Exec[apt_update]/returns: Get:13 http://ftp.debian.org wheezy-backports/main amd64 Packages [606 kB]
==> default: Notice: /Stage[main]/Apt::Update/Exec[apt_update]/returns: Get:14 http://http.debian.net wheezy-updates/main amd64 Packages/DiffIndex [1,996 B]
==> default: Notice: /Stage[main]/Apt::Update/Exec[apt_update]/returns: Get:15 http://http.debian.net wheezy Release [191 kB]
==> default: Notice: /Stage[main]/Apt::Update/Exec[apt_update]/returns: Get:16 http://ftp.debian.org wheezy-backports/contrib amd64 Packages [8,725 B]
==> default: Notice: /Stage[main]/Apt::Update/Exec[apt_update]/returns: Get:17 http://security.debian.org wheezy/updates/main Translation-en [202 kB]
==> default: Notice: /Stage[main]/Apt::Update/Exec[apt_update]/returns: Get:18 http://ftp.debian.org wheezy-backports/non-free amd64 Packages [21.6 kB]
==> default: Notice: /Stage[main]/Apt::Update/Exec[apt_update]/returns: Get:19 http://http.debian.net wheezy-updates/main Translation-en/DiffIndex [736 B]
==> default: Notice: /Stage[main]/Apt::Update/Exec[apt_update]/returns: Get:20 http://http.debian.net wheezy-updates/main Sources [5,507 B]
==> default: Notice: /Stage[main]/Apt::Update/Exec[apt_update]/returns: Get:21 http://ftp.debian.org wheezy-backports/contrib Translation-en [6,350 B]
==> default: Notice: /Stage[main]/Apt::Update/Exec[apt_update]/returns: Get:22 http://ftp.debian.org wheezy-backports/main Translation-en [376 kB]
==> default: Notice: /Stage[main]/Apt::Update/Exec[apt_update]/returns: Get:23 http://http.debian.net wheezy-updates/main amd64 Packages [7,052 B]
==> default: Notice: /Stage[main]/Apt::Update/Exec[apt_update]/returns: Get:24 http://http.debian.net wheezy/main Translation-en [3,846 kB]
==> default: Notice: /Stage[main]/Apt::Update/Exec[apt_update]/returns: Get:25 http://http.debian.net wheezy/main Sources [5,984 kB]
==> default: Notice: /Stage[main]/Apt::Update/Exec[apt_update]/returns: Get:26 http://http.debian.net wheezy/main amd64 Packages [5,838 kB]
==> default: Notice: /Stage[main]/Apt::Update/Exec[apt_update]/returns: Get:27 http://ftp.debian.org wheezy-backports/non-free Translation-en [21.7 kB]
==> default: Notice: /Stage[main]/Apt::Update/Exec[apt_update]/returns: Get:28 http://http.debian.net wheezy-updates/main Translation-en [4,879 B]
==> default: Notice: /Stage[main]/Apt::Update/Exec[apt_update]/returns: Err http://repo.puphpet.com wheezy/all Sources
==> default: Notice: /Stage[main]/Apt::Update/Exec[apt_update]/returns:   301  Moved Permanently [IP: 195.xxx.xxx.xx 8081]
==> default: Notice: /Stage[main]/Apt::Update/Exec[apt_update]/returns: Err http://repo.puphpet.com wheezy/all amd64 Packages
==> default: Notice: /Stage[main]/Apt::Update/Exec[apt_update]/returns:   301  Moved Permanently [IP: 195.xxx.xxx.xx 8081]
==> default: Notice: /Stage[main]/Apt::Update/Exec[apt_update]/returns: Ign http://repo.puphpet.com wheezy/all Translation-en_US
==> default: Notice: /Stage[main]/Apt::Update/Exec[apt_update]/returns: Ign http://repo.puphpet.com wheezy/all Translation-en
==> default: Notice: /Stage[main]/Apt::Update/Exec[apt_update]/returns: Fetched 18.6 MB in 10s (1,796 kB/s)
==> default: Notice: /Stage[main]/Apt::Update/Exec[apt_update]/returns: W: Failed to fetch http://repo.puphpet.com/dotdeb/dists/wheezy/all/source/Sources  301  Moved Permanently [IP: 195.xxx.xxx.xx1 8081]
==> default: Notice: /Stage[main]/Apt::Update/Exec[apt_update]/returns:
==> default: Notice: /Stage[main]/Apt::Update/Exec[apt_update]/returns: W: Failed to fetch http://repo.puphpet.com/dotdeb/dists/wheezy/all/binary-amd64/Packages  301  Moved Permanently [IP: 195.xxx.xxx.xx 8081]

=========================================
195.xxx.xxx.xx is our network proxy. The install goes a bit further, then fails completely. I've attached the full console output. 

I'm on Windows 10 and I've also tried rolling back to the versions that had been previously working (VBox 4.3.34 / vagrant 1.7.2) but still have exactly the same error.

From within the VM, I get the following output:

==============================
$ sudo apt-get update
Hit http://http.debian.net wheezy Release.gpg
Hit http://http.debian.net wheezy-updates Release.gpg
Hit http://security.debian.org wheezy/updates Release.gpg
Hit http://security.debian.org wheezy/updates Release
Ign http://repo.puphpet.com wheezy Release.gpg
Hit http://security.debian.org wheezy/updates/main Sources
Hit http://security.debian.org wheezy/updates/main amd64 Packages
Get:1 http://http.debian.net wheezy Release [191 kB]
Hit http://http.debian.net wheezy-updates Release
Hit http://security.debian.org wheezy/updates/main Translation-en
Get:2 http://http.debian.net wheezy-updates/main Sources [5,507 B]
Ign http://repo.puphpet.com wheezy Release
Hit http://http.debian.net wheezy-updates/main Translation-en/DiffIndex
Get:3 http://http.debian.net wheezy-updates/main amd64 Packages/DiffIndex [1,996 B]
Get:4 http://http.debian.net wheezy/main Sources [5,984 kB]
Get:5 http://http.debian.net wheezy/main amd64 Packages [5,838 kB]
Get:6 http://http.debian.net wheezy/main Translation-en [3,846 kB]
Err http://repo.puphpet.com wheezy/all Sources
  301  Moved Permanently [IP: 195.245.100.11 8081]
Err http://repo.puphpet.com wheezy/all amd64 Packages
  301  Moved Permanently [IP: 195.245.100.11 8081]
Hit http://ftp.debian.org wheezy-backports Release.gpg
Hit http://ftp.debian.org wheezy-backports Release
Ign http://repo.puphpet.com wheezy/all Translation-en_US
Get:7 http://ftp.debian.org wheezy-backports/main Sources/DiffIndex [19.3 kB]
Ign http://repo.puphpet.com wheezy/all Translation-en
Get:8 http://ftp.debian.org wheezy-backports/contrib Sources/DiffIndex [4,180 B]
Get:9 http://ftp.debian.org wheezy-backports/non-free Sources/DiffIndex [2,488 B]
Get:10 http://ftp.debian.org wheezy-backports/main amd64 Packages/DiffIndex [10.1 kB]
Get:11 http://ftp.debian.org wheezy-backports/contrib amd64 Packages/DiffIndex [2,212 B]
Get:12 http://ftp.debian.org wheezy-backports/non-free amd64 Packages/DiffIndex [2,488 B]
Get:13 http://ftp.debian.org wheezy-backports/contrib Translation-en/DiffIndex [1,228 B]
Get:14 http://ftp.debian.org wheezy-backports/main Translation-en/DiffIndex [3,964 B]
Get:15 http://ftp.debian.org wheezy-backports/non-free Translation-en/DiffIndex [1,996 B]
Fetched 15.9 MB in 5s (2,662 kB/s)
W: Failed to fetch http://repo.puphpet.com/dotdeb/dists/wheezy/all/source/Sources  301  Moved Permanently [IP: 195.245.1                                                                     00.11 8081]

W: Failed to fetch http://repo.puphpet.com/dotdeb/dists/wheezy/all/binary-amd64/Packages  301  Moved Permanently [IP: 19                                                                     5.245.100.11 8081]

E: Some index files failed to download. They have been ignored, or old ones used instead.
=====================================

[vagrant_fail.txt](https://github.com/puphpet/puphpet/files/236174/vagrant_fail.txt)

**Comment by Sharkfinger** [comment]
In server.pp, I've changed 
http://repo.puphpet.com/dotdeb/ 
to 
https://repo.puphpet.com/dotdeb/

So the redirect no longer happens but then I get errors like the following:
===============
==> default: Error: /Stage[main]/Apt::Update/Exec[apt_update]: Failed to call refresh: /usr/bin/apt-get update returned 100 instead of one of [0]
==> default: Error: /Stage[main]/Apt::Update/Exec[apt_update]: /usr/bin/apt-get update returned 100 instead of one of [0]
==> default: Error: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install mysql-client' returned 100: Reading package lists...
==> default: Building dependency tree...
==> default: Reading state information...
==> default: The following extra packages will be installed:
==> default:   libdbd-mysql-perl libdbi-perl libmysqlclient18 mysql-client-5.5 mysql-common
==> default: Suggested packages:
==> default:   libterm-readkey-perl
==> default: The following NEW packages will be installed:
==> default:   libdbd-mysql-perl libdbi-perl libmysqlclient18 mysql-client mysql-client-5.5
==> default:   mysql-common
==> default: 0 upgraded, 6 newly installed, 0 to remove and 3 not upgraded.
==> default: Need to get 3746 kB of archives.
==> default: After this operation, 43.8 MB of additional disk space will be used.
==> default: WARNING: The following packages cannot be authenticated!
==> default:   mysql-common libmysqlclient18 libdbi-perl libdbd-mysql-perl mysql-client-5.5
==> default:   mysql-client
==> default: E: There are problems and -y was used without --force-yes
==> default: Error: /Stage[main]/Mysql::Client::Install/Package[mysql_client]/ensure: change from purged to present failed: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install mysql-client' returned 100: Reading package lists...

=============================================

**Comment by websmurf** [comment]
Hi, see #2281 for the same issue and a workaround :-)

**Comment by Sharkfinger** [comment]
Thanks, will try that.

**Comment by Sharkfinger** [comment]
This is a duplicate of that issue.  Can it be marked as such?

**Comment by jtreminio** [comment]
Fixed by https://github.com/puphpet/puphpet/issues/2281#issuecomment-214771844
