### ISSUE TITLE
Vagrant up fails because of the host path

### ISSUE THREAD

**Issue by samuelkhella** [puphpet/puphpet#2289]
I created the folder on my desktop and added the path as follows on puphpet  "./users/samyabdelmalak/desktop/samuelcode " and after hittng vagrant up that error appears " There are errors in the configuration of this machine. Please fix
the following errors and try again:

vm:
* The host path of the shared folder is missing: ./users/samyabdelmalak/desktop/samuelcode "
how should i fix this?

**Comment by jtreminio** [comment]
Remove the initial `.`.
