### ISSUE TITLE
Downloaded archive from site failed to open (windows 10)

### ISSUE THREAD

**Issue by phlisg** [puphpet/puphpet#2296]
Hello!

As a notice, I just wanted to report that the default **Windows (10) archive extractor** marks any downloaded zip as unvalid when double-clicked. By using **7-zip** (right click and `open archive` - the first menu element), I also get an error. But by right-clicking again, selecting **7-zip** and choosing the "`open archive >`"  submenu, and finally clicking on `zip`, I managed to open the archive and extract its contents.

**Comment by vielhuber** [comment]
Same here.

**Comment by jtreminio** [comment]
The archives are generated using the Linux `zip` tool with this command: https://github.com/puphpet/puphpet/blob/master/src/PuphpetBundle/Extension/Archive.php#L8

Is there something I should change?

**Comment by Phlisg** [comment]
Hello Juan!

I tried yesterday with a new archive and this time I had no problems.

The initial problem occurred when puphpet.com had a small reskin to its UI.
Maybe it was my system as everything works fine now.

@vielhuber is it still not working for you?

**Comment by vielhuber** [comment]
Hello!

It's working again. I tried it three times and had no problems now.

But don't know if the error is permanently gone.
