### ISSUE TITLE
Nginx version

### ISSUE THREAD

**Issue by Renkas** [puphpet/puphpet#2304]
Is there a possibility to install nginx 1.9.5 or later with Puphpet? Would like to have HTTP 2 protocol in the dev environment.

**Comment by Renkas** [comment]
Any info?

**Comment by jtreminio** [comment]
You can now do:

    nginx:
        install: '1'
        settings:
            version: '1.4.*'
            default_vhost: 1
            proxy_buffer_size: 128k
            proxy_buffers: '4 256k'
            proxy_connect_timeout: 600s
            proxy_send_timeout: 600s
            proxy_read_timeout: 600s
            names_hash_bucket_size: 128

This may not work in Ubuntu because the repos only seem to hold one version at a time.
