### ISSUE TITLE
Change repositiories

### ISSUE THREAD

**Issue by jpresley23** [puphpet/puphpet#2305]
Ondrej's ppa seems to cause problems with breaking packages in our Ubuntu setup with `vagrant destroy && vagrant up`. Is there a way we can just use Ubuntu's base ppas? Alternatively, is there a way of locking versions so that once we have a working box we don't have to worry about updates to packages breaking?

**Comment by jtreminio** [comment]
> Ondrej's ppa seems to cause problems with breaking packages in our Ubuntu setup with vagrant destroy && vagrant up.

Unfortunately puphpet is built around how specific repos handle things. For PHP, it's how ondrej, dotdeb and remi all do their PHP ini handling.

> Alternatively, is there a way of locking versions so that once we have a working box we don't have to worry about updates to packages breaking?

Not currently for PHP, but should work for most other packages. Simply use the full packagename-version syntax that Ubuntu's apt-get support.

**Comment by jpresley23** [comment]
Thank you. That helps us. We'll experiment with using the full version with the package name.
