### ISSUE TITLE
maildev port 1080

### ISSUE THREAD

**Issue by panterofys** [puphpet/puphpet#2310]
Hello and sorry for my english, 
I installed maildev `sudo npm install -g maildev`.
I type : `maildev -s 1026`, becauce port 1025 is busy by mailhog.
maildev is ok!

But when i type local.dev:1080 in my browser, it's long and ...time out. how to have open port 1080 ?

thanks all.

**Comment by jtreminio** [comment]
Add a firewall rule:

![image](https://cloud.githubusercontent.com/assets/589398/15218623/6748408a-1826-11e6-835c-6a21af41986f.png)

**Comment by panterofys** [comment]
fuck lol i'm stupid ! Thank you !!!
