### ISSUE TITLE
The installation of PHP should use the new ondrej ppa

### ISSUE THREAD

**Issue by stof** [puphpet/puphpet#2312]
Old PPAs are deprecated and will reach end of line on June 30th: https://www.patreon.com/posts/old-php5-ppas-of-5430969

Thus, they provide more uptodate versions of some extensions (XDebug 2.4 for instance, rather than XDebug 2.3, which changes lots of things when collecting code coverage due to a bug in 2.3 affecting performance)

It would be great to switch to them.

**Comment by jtreminio** [comment]
The 5.6 and 7.0 choices use the new repo: https://launchpad.net/~ondrej/+archive/ubuntu/php

We're pointing to the older repos for 5.4/5.5.

I did just notice that 5.5 is now available in the above linked repo though, so I will def. look into refactoring the 5.5 support to use it.

I removed 5.3 support a while back, would you say it's time to remove 5.4 now?

**Comment by stof** [comment]
I would say yes, as 5.4 does not receive security fixes anymore since a few months anyway

**Comment by stof** [comment]
Closing as it is already available in the new ppa (was not the case in the old ppa AFAICT)

**Comment by stof** [comment]
sorry, wrong tab

**Comment by joshuaadickerson** [comment]
Would it be appropriate to request that you do this with an option in config.yaml? It would be nice to config repos via it.

**Comment by jtreminio** [comment]
Thanks @stof, PHP 5.4 dropped, and Ubuntu points to proper Sury repo now:

https://blog.puphpet.com/blog/2016/10/05/ubuntu-1604-centos7-php71-added-debian-dropped/
