### ISSUE TITLE
Error after update of config-file

### ISSUE THREAD

**Issue by jannikrl** [puphpet/puphpet#2313]
I updated my config file using puphpet.com and got this error.

I try to figure out what went wrong. Any thoughts?

Gist with config.yaml and terminal output: 
https://gist.github.com/jannikrl/8a739dab7bd0727a200c31bdb62a4d7a

Errors:
https://www.dropbox.com/s/9opz64wg4xhg3af/Sk%C3%A6rmbillede%202016-05-13%2009.09.55.png?dl=0
https://www.dropbox.com/s/qkrtdudon7v0qhs/Sk%C3%A6rmbillede%202016-05-13%2009.10.14.png?dl=0

**Comment by jtreminio** [comment]
`pecl_http` requires newer version of php. To install older version use, `pecl_http-{version_number}` in the config.yaml
