### ISSUE TITLE
Php: Xdebug: PHPStorm link broken

### ISSUE THREAD

**Issue by Artistan** [puphpet/puphpet#2315]
"Follow instructions here to setup PHPStorm to listen for a CLI connection. Other IDEs should be similar."

this link is not working.

**Comment by adamculp** [comment]
http://devincharge.com/debug-cli-remote-server/ domain has expired.

**Comment by Artistan** [comment]
yep, there is docs on the PHPStorm site for setting up Xdebug, please update to 
https://www.jetbrains.com/help/phpstorm/10.0/configuring-xdebug.html
