### ISSUE TITLE
Xdebug and xdebug.remote_autostart

### ISSUE THREAD

**Issue by adamculp** [puphpet/puphpet#2319]
When attempting to debug via IDE it is necessary to have xdebug.remote_autostart set to 1. Otherwise debugging doesn't work. Therefore perhaps this option should be turned on by default, rather than the current "off" default setting?

**Comment by catalinux** [comment]
You can put your setttings in your config.yaml

```yaml
xdebug:
    install: '1'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '1'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
        xdebug.idekey: vagrant

**Comment by adamculp** [comment]
Agreed, but since it is pretty much required in order to work I was thinking it should be the default setting.

**Comment by jtreminio** [comment]
I believe a cookie that enables it is a better option. If `remote_autostart` is enabled by default, response times slows down dramatically unless a listener (IDE) is found for xdebug to connect to.

Do these bookmarklets do what you want? https://www.jetbrains.com/phpstorm/marklets/

**Comment by adamculp** [comment]
No, the bookmarklets do not make this work (they were already being used). When debugging with PHPStorm in a virtual machine the `remote_autostart` is required. So a user of the IDE cannot debug without it being set to true.

**Comment by jtreminio** [comment]
@adamculp the settings I've been using for years are:

    xdebug:
        install: '1'
        settings:
            xdebug.default_enable: '1'
            xdebug.remote_autostart: '0'
            xdebug.remote_connect_back: '1'
            xdebug.remote_enable: '1'
            xdebug.remote_handler: dbgp
            xdebug.remote_port: '9000'

This has worked for me flawlessly, across multiple host machines. PHPStorm's debug bookmarklets + enabling the listener in the IDE + setting proper path mappings makes this work 100% of the time.

Would you mind detailing the steps you're taking for debugging?
