### ISSUE TITLE
Centos 6.7 yum fails - "Error: Cannot retrieve repository metadata (repomd.xml) for repository: scl. Please verify its path and try again"

### ISSUE THREAD

**Issue by L-L-B** [puphpet/puphpet#2321]
I'm provisioning the centos box, on up it's getting this error:

"Error: Cannot retrieve repository metadata (repomd.xml) for repository: scl. Please verify its path and try again"

Suspect it's related to this issue: https://bugs.centos.org/view.php?id=10925

Anyone know how I can work around it?

**Comment by sadon** [comment]
PuPHPet need to update base box of centos 6.5 to 6.6 or remove scl repository via inline script.

**Comment by sadon** [comment]
as temporary solution you can add the file: (but better is wait for update puppet/centos6-5 base box)

{project}/puphpet/files/exec-preprovision/_update-slc-repo.sh 
`#!/bin/bash`
`#hotfix for CentOS 6.5 repos`
`/usr/bin/yum -y remove centos-release-SCL`
`/usr/bin/yum -y install centos-release-sclo-rh`

**Comment by L-L-B** [comment]
Thanks for your help, I'll wait for the update to the base box

**Comment by bickerstoff** [comment]
When executing the above commands (specifically: /usr/bin/yum -y install centos-release-sclo-rh), I get:
No package centos-release-sclo-rh available.
Error: Nothing to do

**Comment by bickerstoff** [comment]
Any idea when the base box will be updated?

**Comment by hoshsadiq** [comment]
I'm having the same issue, the workaround @sadon said didn't work

**Comment by hoshsadiq** [comment]
So as a workaround this worked for me:
Run vagrant up, and once the puphpet ascii art comes up, cancel it and `vagrant ssh` into the box and run the following two commands:
```bash
sudo /usr/bin/yum -y remove centos-release-SCL
sudo /usr/bin/yum -y install centos-release-scl
```
Then exit and run `vagrant provision`

For some reason having these two in exec-preprovision doesn't work. Not sure why!

**Comment by JosephMaxwell** [comment]
@sadon: your comment fixed the problem for me. Thank you.

**Comment by natenolting** [comment]
> Run vagrant up, and once the puphpet ascii art comes up, cancel it and vagrant ssh into the box

I can't even get to that point with this fresh configuration http://pastebin.com/vpHHm6SE

```
==> machine1: Machine booted and ready!
GuestAdditions versions on your host (5.0.20) and guest (5.0.10) do not match.
Setting up Install Process
http://mirror.centos.org/centos/6/SCL/x86_64/repodata/repomd.xml: [Errno 14] PYCURL ERROR 22 - "The requested URL returned error: 404 Not Found"
Trying other mirror.
Error: Cannot retrieve repository metadata (repomd.xml) for repository: scl. Please verify its path and try again
==> machine1: Checking for guest additions in VM...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

yum install -y kernel-devel-`uname -r` gcc make perl bzip2

Stdout from the command:

Setting up Install Process


Stderr from the command:

http://mirror.centos.org/centos/6/SCL/x86_64/repodata/repomd.xml: [Errno 14] PYCURL ERROR 22 - "The requested URL returned error: 404 Not Found"
Trying other mirror.
Error: Cannot retrieve repository metadata (repomd.xml) for repository: scl. Please verify its path and try again

```

**Comment by drawm** [comment]
@natenolting I had the same problem. You might have a vagrant plugin running before the provision script. If you are using vagrant-vbguest, try uninstalling it.

**Comment by hoshsadiq** [comment]
Yes! My bad, same thing was happening with me. As @drawm said, remove vagrant-vbguest first.

**Comment by natenolting** [comment]
@drawm Uninstalling that plugin (I don't remember ever installing it) and using @hoshsadiq trick made it work. Hopefully soon there's an update to the base box so this can be avoided.

**Comment by jeremiahsmall** [comment]
Thanks to @sadon and @hoshsadiq. The combined tips worked for us. Here's how we setup the shell script:

{project}/puphpet/files/exec-preprovision/_update-slc-repo.sh 
```
 #!/bin/bash
#hotfix for CentOS 6.5 repos
/usr/bin/yum -y remove centos-release-SCL
/usr/bin/yum -y install centos-release-scl
```

**Comment by jorisros** [comment]
Thanks, for me with centos 6 selected the command below here worked for me:

> /usr/bin/yum -y install centos-release-scl

[https://bugs.centos.org/view.php?id=10925]([SOLVED] Yum attempting to Update/Install Packages - 404 Error Returned.)

**Comment by socalheel** [comment]
What plugins are you guys using?
I was running into the same problem and narrowed it down to a plugin being the problem.

It is the vagrant-vbguest plugin.

I uninstalled that and it worked.
