### ISSUE TITLE
Error on installing Elasticsearch

### ISSUE THREAD

**Issue by Vesquen** [puphpet/puphpet#2327]
This is in my config.yaml
```
elastic_search:
    install: '1'
    settings:
        version: 2.3.1
        java_install: true
    instances:
        esi_88v5c2eeuan1:
            name: es-01
```

On vagrant provision I receive following error:
```
==> dev-machine: Error: Could not update: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold --force-yes install elasticsearch=2.3.1' returned 100: Reading package lists...
==> dev-machine: Building dependency tree...
==> dev-machine: Reading state information...
==> dev-machine: E: Unable to locate package elasticsearch
==> dev-machine: Error: /Stage[main]/Elasticsearch::Package/Package[elasticsearch]/ensure: change from purged to 2.3.1 failed: Could not update: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold --force-yes install elasticsearch=2.3.1' returned 100: Reading package lists...
==> dev-machine: Building dependency tree...
==> dev-machine: Reading state information...
==> dev-machine: E: Unable to locate package elasticsearch
```

OS: Debian Wheezy 7 x64

**Comment by tstrijdhorst** [comment]
I have the same problem with ubuntu 14.04

**Comment by brino** [comment]
you probably want to check this issues ...
https://github.com/puphpet/puphpet/issues/2270

Seems like there is a workaround for CentOS but not Ubuntu?

**Comment by vincenzo** [comment]
Getting the same here with all versions of ES.

@jtreminio ?

**Comment by vincenzo** [comment]
Resolution in #2270 works for me.

**Comment by obayesshelton** [comment]
👍 in #2270 works for me as well

**Comment by exchentrix** [comment]
Hey, the hack doesn't seem to work anymore.

`==> emoja: Error: Failed to apply catalog: Found 1 dependency cycle: ==> emoja: (Anchor[apt_key D88E42B4 present] => Apt::Key[Add key: D88E42B4 from Apt::Source elasticsearch] => Apt::Setting[list-elasticsearch] => File[/etc/apt/sources.list.d/elasticsearch.list] => Class[Apt::Update] => Exec[apt_update] => Class[Apt::Update] => Package[iptables] => Firewall[999 drop all] => Class[Puphpet::Firewall::Post] => Class[Elasticsearch] => Anchor[elasticsearch::begin] => Class[Elasticsearch::Repo] => Apt::Source[elasticsearch] => Apt::Setting[list-elasticsearch]) ==> emoja: Try the '--graph' option and opening the resulting '.dot' file in OmniGraffle or GraphViz`

Are there any other possibilities?

**Comment by jtreminio** [comment]
Fixed by https://github.com/puphpet/puppet-puphpet/commit/1ec44ef9035427d776b080ea48abae7bad06df7c
