### ISSUE TITLE
Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by ricpelo** [puphpet/puphpet#2333]
Hi!

This is not an issue, sorry for the noise, but I didn't find any better place to ask this question:

Is there support for Ubuntu 16.04 LTS & PHP 7? If not, is it planned for the near future (1-2 months or so)?

Thank you very much in advance, and sorry again!

**Comment by jtreminio** [comment]
Support is incoming.

**Comment by ricpelo** [comment]
Thank you!

**Comment by msmuenchen** [comment]
Hi, is it planned to introduce Debian Jessie, too?

**Comment by jtreminio** [comment]
I will actually be dropping support for Debian soon.

**Comment by euneuber** [comment]
Please explain why you will drop support for Debian!

**Comment by MatyCZ** [comment]
Any progress?

**Comment by visualfanatic** [comment]
@jtreminio would you accept PR with Ubuntu 16.04 support?

**Comment by PragmatiqueConsulting** [comment]
Is this possible in the meantime by changing the box in the config.yaml file to a 16.04 box, and installing puppet on it, then trying to provision? Unsure if there are any other dependencies on the puphpet boxes themselves.

**Comment by libertamohamed** [comment]
@jtreminio is there any progress for the Ubuntu 16.04 support?

**Comment by jtreminio** [comment]
https://blog.puphpet.com/blog/2016/10/05/ubuntu-1604-centos7-php71-added-debian-dropped/
