### ISSUE TITLE
Unable to access to Virtual Host

### ISSUE THREAD

**Issue by sureshbathala01** [puphpet/puphpet#2341]
I've created a new VM and am able to access the default index.html page with local host and the assigned IP address 192.168.56.101.  However I'm not able to access the page using virtual host URL http://dev.gcmw:8888.   I'm using latest version of vagrant 1.8.4 and virtual box  5.0.20 r106931, can someone help me troubleshoot.

I've updated the hosts file both with host (windows 8.10) and host Ubuntu 14.04 as below:
192.168.56.101 dev.gcmw. Attached is the YAML configuration file.

[config.txt](https://github.com/puphpet/puphpet/files/316197/config.txt)

**Comment by jtreminio** [comment]
The URL would be http://dev.gcmw
