### ISSUE TITLE
Output buffering

### ISSUE THREAD

**Issue by julio6114** [puphpet/puphpet#2342]
Hi everybody,

I would like to use output_buffering on my VM but don't work. 
I believe it's a problem with FastCGI.

I don't see how activate this feature.

I try to print a message in a loop like that : 
```
ob_start();

output("=========================");
for($i=10;$i>=0;$i--) {
    output($i);
    sleep(1);
}
output("=========================");

function output($string) {
    echo $string."<br/>\n";
    echo str_pad('',4096)."\n";
    ob_flush();
    flush();
}

ob_end_flush();

```

**Comment by jtreminio** [comment]
I don't believe this to be a puphpet-specific issue: http://stackoverflow.com/questions/4870697/php-flush-that-works-even-in-nginx
