### ISSUE TITLE
CentOS doesn't support NodeJS 5.x

### ISSUE THREAD

**Issue by Jakobud** [puphpet/puphpet#2343]
I setup a machine that was using CentOS 6.x and I chose to install Node.js 5.x. During the `vagrant up`, I get the following error:

```
Error: Evaluation Error: Error while evaluating a Function Call, You have chosen an unsupported NodeJS version. at /tmp/vagrant-puppet/manifests-75f35e3bc7e32744860c4bb229c88812/NodeJs.pp:50:7 on node machine1.puphpet
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

Looked in the manifest file and I see something like this:

```
if $::osfamily == 'debian' {
    if ! defined('apt-transport-https') {
      package { 'apt-transport-https':
        ensure => present
      }
    }

    $version = $version_num ? {
      '5'     => '5.x',
      '4'     => '4.x',
      '0.12'  => '0.12',
      '0.10'  => '0.10',
      default => "${version_num}.x"
    }

    $url = "https://deb.nodesource.com/setup_${version}"

    $save_to = '/.puphpet-stuff/nodesource'

    exec { 'add nodejs repo':
      command => "wget --quiet --tries=5 --connect-timeout=10 -O '${save_to}' ${url} \
                  && bash ${save_to}",
      creates => $save_to,
      path    => '/usr/bin:/bin',
      require => Package['apt-transport-https'],
    }
    -> package { 'nodejs':
      ensure => present,
    }
  } else {
    $pkg_url = $version_num ? {
      '0.12'  => 'https://rpm.nodesource.com/pub_0.12/el/6/x86_64/nodejs-0.12.9-1nodesource.el6.x86_64.rpm',
      '0.10'  => 'https://rpm.nodesource.com/pub_0.10/el/6/x86_64/nodejs-0.10.41-1nodesource.el6.x86_64.rpm',
      default => false
    }

    if ! $pkg_url {
      fail('You have chosen an unsupported NodeJS version.')
    }

    ...
```

So for non-debian VMs, is Node 0.12 and 0.10 the only available versions to install? This doesn't make a lot of sense, seeing that Node is officially up to v6.x and they have LTS for 4.x. v.12 and v.10 are very old.

**Comment by jtreminio** [comment]
![image](https://cloud.githubusercontent.com/assets/589398/16140906/a1fc85a6-340a-11e6-8b80-650df6214699.png)

**Comment by Jakobud** [comment]
Aha I missed that in the config. Thanks, You should just make it not an option if you select CentOS. Thanks,

**Comment by awalls** [comment]
I had the same issue but I didn't see the warning about CentOS only supporting versions <= 0.12

Distro selection:
![distro-versions](https://cloud.githubusercontent.com/assets/93467/17246494/73769bcc-5584-11e6-9af8-e03350dbbb39.jpeg)

NodeJS options: 
![nodejs-versions](https://cloud.githubusercontent.com/assets/93467/17246495/737f294a-5584-11e6-81f6-543fe4cf2194.jpeg)
