### ISSUE TITLE
auth_cas in Apache installation fails

### ISSUE THREAD

**Issue by ultrablue** [puphpet/puphpet#2345]
Howdy:

Sorry, I'm not all that up on my terminology, but I've just solved a problem with my puphpet install that I thought I would share. It might be a bug.

I created the config.yaml file with an option to include the auth_cas module. However, Apache refused to start. The logs said this:

    MOD_AUTH_CAS: CASCookiePath '/dev/null' is not a directory or does not end in a trailing '/'!
    AH00016: Configuration Failed

After some digging, I realized that while /etc/apache2/mods-enabled/auth_cas.load was linked, /etc/apache2/mods-enabled/auth_cas.conf wasn't. The log entry was referring to the default setting in the module itself.

Once I got that squared away, other, configuration errors appeared:

    MOD_AUTH_CAS: CASLoginURL or CASValidateURL not defined.

I was able to fix those. However, auth_cas.conf did have one line it to start with:
    CASCookiePath

I don't know where that came from, but if it's possible to determine what appears in auth_cas.conf via a VM configuration file, it would be convenient to have CASLoginURL and CASValidateURL appear in it as well (as a hint about what to fix).

Anyway, I think the 'bug' is that the conf file wasn't where it should have been?

Thanks!
Greg

**Comment by ultrablue** [comment]
Just updating this: I reprovisioned the VM and the conf file was missing again.

Thanks!
Greg

**Comment by jtreminio** [comment]
Please try this with the latest release. The puppet-apache module has been updated.

**Comment by ultrablue** [comment]
Hi, Juan:

Yup fixed.

Thank you!!!!!
