### ISSUE TITLE
Add postgres version 9.5

### ISSUE THREAD

**Issue by d-ph** [puphpet/puphpet#2348]
Hello,

Could we have an option to install postgres 9.5, please?

I don't know what's the procedure for upgrading puppet modules, but I checked out the latest [postgres puppet module](https://github.com/puppetlabs/puppetlabs-postgresql) version and it supports installing pg 9.5. At least on Ubuntu 14.04 (I successfully provisioned the machine, although the settings from puphpet's config.yaml weren't applied (most notably, the root password for the database)).

Thanks.

**Comment by jtreminio** [comment]
Latest release has up to 9.6
