### ISSUE TITLE
Php as apache module

### ISSUE THREAD

**Issue by AntonioCS** [puphpet/puphpet#2352]
Hey,

Is it possible to have an option to install php as an apache module instead of php-fpm?

**Comment by chonny** [comment]
i am interested here too

**Comment by jtreminio** [comment]
`mod_php` support was dropped over a year ago, it will not be coming back.

You can, however, work around this by manually setting Apache version to `2.2` and working from there.

**Comment by AntonioCS** [comment]
Any reason why this was removed and why it is not coming back?

**Comment by jtreminio** [comment]
@AntonioCS Having to support Apache's `mod_php`, as well as PHP-FPM on both Apache and Nginx, was far too much work for me to keep up with.

I opted to drop support completely because I do not have enough help or time to try and maintain support for it across all the distros PuPHPet offers.

**Comment by AntonioCS** [comment]
That is really unfortunate. I have run into some performance issues and I believe the root cause is php-fpm.

Oh well, back to the drawing board I guess.

Thanks!
