### ISSUE TITLE
$required_packages is deprecated

### ISSUE THREAD

**Issue by farfromunique** [puphpet/puphpet#2358]
[config.yaml.zip](https://github.com/puphpet/puphpet/files/333186/config.yaml.zip)
When performing an initial `vagrant up`, many packages (including MariaDB) generate lines like this:

    ==> Development-LAMP: Warning: Scope(Apt::Source[mariadb]): $required_packages is deprecated and will be removed in the next major release, please use package resources instead.

you probably already know about this, but didn't see an issue for it.

**Comment by wunc** [comment]
I think a fix for this is suggested in the `puppet/modules/examples/debian_testing.pp`.

So, in the appropriate puppet-puphpet manifests, remove the `required_packages` line and add package resource definitions for `debian-keyring` and `debian-archive-keyring`.

For example, we would change the relevant parts of `puppet/modules/puphpet/manifests/mysql/repo.pp` to

```
if ! defined(Package['debian-keyring']) {
  package { 'debian-keyring':
    ensure => present
  }
}

if ! defined(Package['debian-keyring']) {
  package { 'debian-archive-keyring':
    ensure => present
  }
}

if ! defined(Apt::Source['repo.mysql.com-apt']) {
  apt::source { 'repo.mysql.com-apt':
    location          => "http://repo.mysql.com/apt/${os}",
    release           => $::lsbdistcodename,
    repos             => 'mysql-5.7',
    include           => { 'src' => true },
    require           => Apt::Pin['repo.mysql.com-apt'],
  }
}
```

I did this on my own install and it seemed to work (for MySQL, at least).

**Comment by quangthien27** [comment]
Confirm @wunc 's fix working. Anyway, this is just a warning and should be fixed in case new PuPHPet is released along with latest puppet.

**Comment by jtreminio** [comment]
Fixed in latest release.
