### ISSUE TITLE
failed dependencies

### ISSUE THREAD

**Issue by zalazdi** [puphpet/puphpet#2359]
I've build basic PuPHPet configuration and tried to run it, but i'm getting warnings like

    Warning: /Stage[main]/Puphpet_php/Service[php5.6-fpm]: Skipping because of failed dependencies

I haven't made any changes to config. On website I only checked instalation of Redis, MongoDB and ElasticSearch (it's important to my app).

What can be wrong?

Config: http://pastebin.com/3JjGwWGS
Log: http://pastebin.com/SAyRy1eW

**Comment by exchentrix** [comment]
Seems, that this has something to do with ElasticSearch. Take a look at https://github.com/puphpet/puphpet/issues/2270#issuecomment-215478010 and see, if it helps.

**Comment by zalazdi** [comment]
It helped with ES, but i have still problem with PECL. 
```
==> machine1: Notice: /Stage[main]/Puphpet_mongodb/Puphpet::Php::Pecl[mongo]/Php::Pecl::Module[mongodb]/Exec[pecl-mongodb]/returns: 
==> machine1: Notice: /Stage[main]/Puphpet_mongodb/Puphpet::Php::Pecl[mongo]/Php::Pecl::Module[mongodb]/Exec[pecl-mongodb]/returns: Warning: Invalid argument supplied for foreach() in Command.php on line 249
==> machine1: Notice: /Stage[main]/Puphpet_mongodb/Puphpet::Php::Pecl[mongo]/Php::Pecl::Module[mongodb]/Exec[pecl-mongodb]/returns: PHP Warning:  Invalid argument supplied for foreach() in /usr/share/php/PEAR/Command.php on line 249
==> machine1: Notice: /Stage[main]/Puphpet_mongodb/Puphpet::Php::Pecl[mongo]/Php::Pecl::Module[mongodb]/Exec[pecl-mongodb]/returns: 
```

Log - http://pastebin.com/acK5yTNt

**Comment by exchentrix** [comment]
==> machine1: Notice: /Stage[main]/Puphpet_mongodb/Puphpet::Php::Pecl[mongo]/Php::Pecl::Module[mongodb]/Exec[pecl-mongodb]/returns: **XML Extension not found**

I also noticed in the past, that php5.6-xml is not installed and I had to do a apt-get install php5.6-xml. Anyway, I switched to PHP7 and that worked without problems. Maybe you can do the same?

Futher information on this: https://github.com/puphpet/puphpet/issues/2280#issue-150824066
