### ISSUE TITLE
[README] - Error on activesupport

### ISSUE THREAD

**Issue by jonasmello** [puphpet/puphpet#2361]
After run vagrant up i receive this msg:

![image](https://cloud.githubusercontent.com/assets/1612563/16505794/1176c79e-3ef5-11e6-81e6-570084f424b6.png)

**Comment by masitko** [comment]
same problem here

**Comment by emmio-micke** [comment]
Same here. Config:

http://pastebin.com/JmM7rv2n

**Comment by masitko** [comment]
You can fix it temporarily by removing activesupport from last line of
puphpet/shell/install-puppet.sh

**Comment by emmio-micke** [comment]
Thanks, I'll try that. Also tried to create the very simplest machine I could think of. It doesn't have any web server, no php, no database etc. Still the same problem. Config:

http://pastebin.com/mYt2HiNY

**Comment by jtreminio** [comment]
Welp. ActiveSupport

**Comment by ionas** [comment]
Same here. Thanks for the fix!
