### ISSUE TITLE
Sync folders section of config.yml in in a separate file

### ISSUE THREAD

**Issue by AntonioCS** [puphpet/puphpet#2367]
Hey,

Would it be possible to have the  synced_folder section in a separate file? Like a .dist file.

I ask this because I will be working on a team of developers and while we want the same machine across the team the sync folders will vary depending on the developer (some will be on windows others on mac or linux). So if we can have this each dev would simply need to create the file so that it is not in git.

Would this be possible to add? My knowledge of ruby is pretty low so if there is a way of implementing this already please do advise.

Thanks.

**Comment by samuelpearce** [comment]
You can place any puphet value override in the following file:

puphpet/config-custom.yaml

Just make sure the copy the precise structure and keys to override. This folder should already be in the puphpet .gitignore file

For example: 

```yaml
vagrantfile:
    vm:        
        synced_folder:
            asdfaergR43T9SAE_The_exact_key_of_the_share_to_override:
                source: /custom/path/to/developer/source
                target: /path/to/target
                sync_type: nfs
                smb:
                    smb_host: ''
                    smb_username: ''
                    smb_password: ''
                    mount_options:
                        dir_mode: '0775'
                        file_mode: '0664'
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    exclude:
                        - .vagrant/
                        - .git/
                    auto: 'true'
                owner: www-data
                group: www-data
`

Although in your example, you would only need to include the source value and ignore the rest

**Comment by jtreminio** [comment]
Thanks @samuelpearce

**Comment by AntonioCS** [comment]
@samuelpearce Thanks I will try that.
