### ISSUE TITLE
What is making my puphpet VM perform faster than my other VM?

### ISSUE THREAD

**Issue by scottjs** [puphpet/puphpet#2374]
Hi,

I've been a long time user of puphpet and it's awesome, but I'm trying to learn how to provision VMs and production servers from scratch mainly to avoid relying on puphpet and also to learn how it all works.

My puphpet VM is Centos 6, PHP 5.5 (FPM) with Apache set up with NFS synced folders. 

My custom built VM Centos 7 is PHP 5.6 (FPM) with Apache set up with NFS. Most software is running as it comes out of the box.

The code base is a large Wordpress website and is identical on both VMs. 

The load times on puphpet is around 2-3 seconds, compared with 8-9 seconds on my custom VM.

I'm trying to work out where the bottleneck is and how to investigate what puphpet does to make things quicker but I don't know where to start.

Any advice welcome. 

EDIT: I've ruled out synced folders by copying all the code into the VM and running directly with shared folders disabled. No change to load times.

**Comment by scottjs** [comment]
I've narrowed the problem down to an external MySQL connection, but I still don't know why it hangs for 20 seconds before trying to load the page. If I shift the database local to the VM it's all fine. 

Both VMs are connecting to the same database with the same credentials, the puphpet VM connects with no issue but my custom VM just gets stuck doing nothing for 10-20 seconds. 

I realise this isn't an issue with puphpet itself, but if someone could offer some insight as to what might be incorrectly configured that would be appreciated. 

Thanks,
Scott.

**Comment by jtreminio** [comment]
There's no real way to tell because no one here is familiar with your non-puphpet VM or how it's configured.
