### ISSUE TITLE
Apache config ignores conf-enabled directory

### ISSUE THREAD

**Issue by msmuenchen** [puphpet/puphpet#2378]
Hi,

the /etc/apache2/apache2.conf on Ubuntu does not include the conf-enabled directory. It can be restored by inserting this line:
`IncludeOptional "/etc/apache2/conf-enabled/*.conf"`
directly before the line:
`IncludeOptional "/etc/apache2/sites-enabled/*"`.

**Comment by jtreminio** [comment]
I believe this would be better suited for the puppet-apache git repo, not puphpet.
