### ISSUE TITLE
Web GUI generates invalid zip archive!

### ISSUE THREAD

**Issue by thadudexx** [puphpet/puphpet#2379]
[puphpet.zip](https://github.com/puphpet/puphpet/files/359555/puphpet.zip)

**Comment by thadudexx** [comment]
Generating with WebGUI only works, but uploading existing config doesn´t.

**Comment by Renkas** [comment]
Just tried it and it works ...

**Comment by JCMais** [comment]
Not working for me. I can generate the file, but I cannot upload it again to see the configuration.

**Comment by jtreminio** [comment]
Don't upload the zip... you upload the config.yaml.
