### ISSUE TITLE
ENV['HOME'] in wrong place. Is this a puphpet or vagrant issue?

### ISSUE THREAD

**Issue by Leaveyou** [puphpet/puphpet#2383]
Hello. My company's system administrators have changed the default environment variables on WINDOWS workstations to a samba share called Z:

```
HOMEDRIVE=Z:
HOMEPATH=\
```
Running any vagrant commands such as `vagrant up` or `vagrant ssh` after the initial 'vagrant up' yields the following error:

```
$ vagrant up
Bringing machine 'korm' up with 'virtualbox' provider...
There are errors in the configuration of this machine. Please fix
the following errors and try again:

SSH:
* `private_key_path` file must exist: Z:\/.vagrant.d/insecure_private_key
```

It seems the insecure_private_key is generated in the `C:\Users\liviu.gelea\.vagrant.d` directory
 And i believe this could be caused by the Vagrantfile-local. Am I wrong?

**Comment by jtreminio** [comment]
To make this work you need to update the `VAGRANT_DOTFILE_PATH` variable.

It's used as:

```
vagrant_dot  = (ENV['VAGRANT_DOTFILE_PATH'].to_s.split.join.length > 0) ?
  ENV['VAGRANT_DOTFILE_PATH'] :
  "#{dir}/.vagrant"
```
