### ISSUE TITLE
Is there a way to migrate my Host's public ssh key to my VM?

### ISSUE THREAD

**Issue by gkatsanos** [puphpet/puphpet#2385]
Is there a way to migrate my Host's public ssh key to my VM?
The use case is:

- I have a user who has a public SSH key which has access to a certain repository.
- I am creating a VM that will be distributed to other developers (who have access with their SSH keys to this repository)
- I would like to automate git cloning of the repository so it happens during exec-once BY the VM itself

What should I do that involves as few manual paths as possible?

**Comment by gkatsanos** [comment]
I was told I can provision a file , as such : https://www.vagrantup.com/docs/provisioning/file.html but I don't know how to do this in my config.yaml file.

**Comment by gkatsanos** [comment]
( I know there's the 'dot' directory which I can modify there but I was looking for an automated way to copy over the host files in there )

**Comment by jtreminio** [comment]
@gkatsanos to provision a file you can edit the `vagrant/Vagrantfile-local` and add the call in there. This could be the most automated way.
