### ISSUE TITLE
Composer / Cannot create cache directory 

### ISSUE THREAD

**Issue by ionas** [puphpet/puphpet#2387]
When running composer require, it could not create cache directories.
This happened right after I inited the box.
- Host: OS X 10.11.6
- Virtualbox 5.0.26
- Vagrant 1.8.1
- Plugins:
  - vagrant-bindfs (0.4.9)
  - vagrant-share (1.1.5, system)
  - vagrant-vbguest (0.12.0)

### Solution:
```bash
$ sudo chown -R $USER $HOME/.composer
```
Ref: https://github.com/thomaszbz/native-dockerfiles-typo3/issues/19#issuecomment-144753610

**Comment by jtreminio** [comment]
Can you try this again? I can't seem to replicate it.
