### ISSUE TITLE
Extremely slow resonse time from apache

### ISSUE THREAD

**Issue by webconsult** [puphpet/puphpet#2390]
I experience extremely long response times from apache. Several minutes for a single request. I don't really know how to debug this issue, put please have a look at my config:

https://gist.github.com/webconsult/a84574971a0c4a30e91985b7633e775e

**Comment by georaldc** [comment]
Several minutes sounds odd but are you on a windows machine? Have you tried other Shared Folder Types like NFS? The default option using virtualbox's shared folders can be very slow.

**Comment by jtreminio** [comment]
You've got xdebug installed and enabled by default. Do you have an active listener in your IDE? If not, xdebug can and will slow down your response times unless you have an active listener.

**Comment by sauron918** [comment]
Try add NFS mount_option:
```
config.vm.synced_folder ".", "/var/www",
    :nfs => true,
    :mount_options => ['nolock']
```
From documentation:
> NLM locking **must be disabled** with the **nolock** option when using NFS to mount **/var** because /var contains files used by the NLM implementation on Linux. Using the nolock option is also required when mounting exports on NFS servers that do not support the NLM protocol.
