### ISSUE TITLE
HTML Render from cookbooks

### ISSUE THREAD

**Issue by tomasnorre** [puphpet/puphpet#2391]
Hi,

It would be cool if the static generated HTML file would respect the info given in the creation. 

e.g. 192.168.100.1 awesome.dev www.awesome.dev 

all the information is added as part of the setup steps, so why not use it. It would help the users just a little, its not something big but would be nice.

**Comment by jtreminio** [comment]
Would be nice, but the amount of code is not worth it, imho.

Feel free to submit a PR if you'd like.

**Comment by tomasnorre** [comment]
Ok.. Will consider it :)
