### ISSUE TITLE
Mysql Error create user

### ISSUE THREAD

**Issue by marcware** [puphpet/puphpet#2392]
The service mysqld not is start

==> machine1: Info: Creating state file /opt/puppetlabs/puppet/cache/state/state.yaml
==> machine1: Error: Failed to apply catalog: Execution of '/usr/bin/mysql -NBe SELECT CONCAT(User, '@',Host) AS User FROM mysql.user' returned 1: ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

**Comment by timo002** [comment]
Same issue here, can't get a puPHPet working on Mac.

**Comment by dmromanov** [comment]
Duplicate of #2298

**Comment by marcware** [comment]
Ok, thank's. I'm install mysql 5.5 and run ok. But mysql 5.6 and 5.7 dont work. It's because don't start service httpd.
