### ISSUE TITLE
vagrant provision not updating php packages on AWS

### ISSUE THREAD

**Issue by sfarkas1988** [puphpet/puphpet#2394]
Hey, i use puphpet to create AWS instances. It works so far.
I tried to add another package for php (mcrypt) and wanted to update the ec2 instance via vagrant provision. provision starts properly but it seems it cannot install packages with vagrant provision. I use vagrant provision here because the instance is already running. 
My package was not installed, i had to install it manually. I usually use vagrant provision for my local machine as well and i didn't face out any problems there. But for an aws instance nothing happened. 
Can someone reproduce it? I even couldn't find any description that vagrant provision does not work for aws.

Thank you for your help.
Here my config.yml
https://gist.github.com/sfarkas1988/ce9f852df96d04ec19fe17fa29ec7ea5

**Comment by jtreminio** [comment]
If `vagrant up` works, but `vagrant provision` does not, you should contact the vagrant-aws devs on their issue tracker.
