### ISSUE TITLE
PuPHPet Centos not work php in apache

### ISSUE THREAD

**Issue by marcware** [puphpet/puphpet#2395]
When i go to web, return php.
<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

phpinfo();

**Comment by oddz** [comment]
I think this is an issue with the recent update of apache 2.4.23.

I think these are all related issues.

http://mail-archives.apache.org/mod_mbox/httpd-dev/201607.mbox/%3C57800B30.1070501@gmail.com%3E

http://mail-archives.apache.org/mod_mbox/httpd-bugs/201607.mbox/%3Cbug-59815-7868-nOscsrrU9t@https.bz.apache.org/bugzilla/%3E

**Comment by jtreminio** [comment]
As of [this commit](https://github.com/puphpet/puppet-puphpet/commit/ab9625b18b3ab46c572946f8d093935753062cfe) you can now specify version of Apache to install. Does not work in Ubuntu, but does in CentOS.

**Comment by oddz** [comment]
Has this change been released on puphpet.com?
