### ISSUE TITLE
Imagick not installed correctly

### ISSUE THREAD

**Issue by tetele** [puphpet/puphpet#2396]
So, I've created a new VM with Ubuntu/Virtualbox using [this config](http://pastebin.com/SGU7pWZY).

I'm trying to install Imagick as a PECL module, but when I

    $i = new Imagick('image.jpg');

I get this error

    Fatal error: Class 'Imagick' not found in /var/www/admin/api/web/index.php on line 3

It seems that Imagick is not loaded 

    $ php -m
    [PHP Modules]
    calendar
    Core
    ctype
    curl
    date
    dom
    ereg
    exif
    fileinfo
    filter
    ftp
    gettext
    hash
    iconv
    intl
    json
    libxml
    mhash
    mysql
    mysqli
    mysqlnd
    openssl
    pcntl
    pcre
    PDO
    pdo_mysql
    Phar
    posix
    readline
    Reflection
    session
    shmop
    SimpleXML
    sockets
    SPL
    standard
    sysvmsg
    sysvsem
    sysvshm
    tokenizer
    wddx
    xdebug
    xml
    xmlreader
    xmlwriter
    xsl
    Zend OPcache
    zlib

    [Zend Modules]
    Xdebug
    Zend OPcache

I have found its configuration

    $ sudo grep -Rl magick /etc
    /etc/php5/apache2/conf.d/20-imagick.ini
    /etc/php5/mods-available/imagick.ini
    /etc/php5/cli/conf.d/20-imagick.ini
    /etc/ImageMagick/delegates.xml
    /etc/ImageMagick/coder.xml

The extension library exists

    $ find /usr -name imagick.so
    /usr/lib/php5/20121212/imagick.so

But the library is not loaded because PHP is not configured in `/etc/php5` but rather in `/etc/php/5.6`. Subsequently, the libraries are loaded from `/usr/lib/php` rather than `/usr/lib/php5`

My question is: how do I solve this? Is there something wrong with the config or are the recipes not working as expected?

**Comment by jtreminio** [comment]
Fixed in latest release.
