### ISSUE TITLE
Error - Signature verification in vagrant up

### ISSUE THREAD

**Issue by sandroweb** [puphpet/puphpet#2399]
When running `vagrant up` I receive this message:

![image](https://cloud.githubusercontent.com/assets/260201/17257683/a913f49a-5599-11e6-8bd1-388643f5a32a.png)

**Comment by jonasmello** [comment]
The same problem here.

**Comment by jtreminio** [comment]
This issue was patched a few weeks ago. Please update your archive.

**Comment by sandroweb** [comment]
I downloaded and updated the Vagrant, but it keeps happening.
