### ISSUE TITLE
vagrant up fails

### ISSUE THREAD

**Issue by StagnantIce** [puphpet/puphpet#2403]
DEBUG ssh: Checking key permissions: /home/stagnantice/.vagrant.d/insecure_private_key
 INFO ssh: Attempting SSH connection...
 INFO ssh: Attempting to connect to SSH...
 INFO ssh:   - Host: 127.0.0.1
 INFO ssh:   - Port: 2222
 INFO ssh:   - Username: vagrant
 INFO ssh:   - Password? false
 INFO ssh:   - Key Path: ["/home/stagnantice/.vagrant.d/insecure_private_key"]
DEBUG ssh: == Net-SSH connection debug-level log START ==
DEBUG ssh: D, [2016-08-06T07:39:32.670992 #14662] DEBUG -- net.ssh.transport.session[132660c]: establishing connection to 127.0.0.1:2222
D, [2016-08-06T07:39:32.671480 #14662] DEBUG -- net.ssh.transport.session[132660c]: connection established
I, [2016-08-06T07:39:32.671583 #14662]  INFO -- net.ssh.transport.server_version[1325a04]: negotiating protocol version

DEBUG ssh: == Net-SSH connection debug-level log END ==
ERROR warden: Error occurred: An error occurred in the underlying SSH library that Vagrant uses.
The error message is shown below. In many cases, errors from this
library are caused by ssh-agent issues. Try disabling your SSH
agent or removing some keys and try again.

If the problem persists, please report a bug to the net-ssh project.

Use php-7 with default configuration from https://puphpet.com/

Vagrant 1.8.5
ruby 2.2.4
ubuntu 14.04
virtual box 5.1.2

**Comment by scoutman57** [comment]
Can you post your puphpet config?

**Comment by jtreminio** [comment]
I don't believe this to be a puphpet issue.
