### ISSUE TITLE
Locked out on Vagrant reload

### ISSUE THREAD

**Issue by squaredindex** [puphpet/puphpet#2412]
Hi, not sure if this is the right place to ask about this, but I've just expirenced a strange issue trying to run a vagrant reload where I'm now no longer able to run vagrant up and I apparently no longer have the correct permissions. 

The error I get from running vagrant up now is:

```
The private key to connect to the machine via SSH must be owned
by the user running Vagrant. This is a strict requirement from
SSH itself. Please fix the following key to be owned by the user
running Vagrant:

/Users/lev/dev/sitename/.vagrant/machines/sitename/virtualbox/private_key
```

I really don't know much about vagrant or Linux yet, I'm just using this for some frontend dev, how can I correct this?

**Comment by jtreminio** [comment]
Please regenerate your config and update your boxes. It shouldn't be trying to use that key, but the one that is generated on `vagrant up` by my bash files.

Open a new issue if you're running into problems still.
