### ISSUE TITLE
repomd.xml 404 Not Found after vagrant up

### ISSUE THREAD

**Issue by fab-rkd** [puphpet/puphpet#2419]
I am on windows 10, virtual Box Version 5.0.24 r108355,  and Vagrant 1.8.4.
Getting,  404 Not found for http://mirror.centos.org/centos/6/SCL/x86_64/repodata/repomd.xml after vagrant up.

Have a look at this :
![puphpet_vagrant_up_issue](https://cloud.githubusercontent.com/assets/20355726/18196683/7f5a5210-7110-11e6-86b2-5661ff69c9f2.jpg)

**Comment by janw-oostendorp** [comment]
I'm installing a debian box and I'm also having no succes.
A lot of 404's my main url that gives this problem is `http.debian.net/dists/`
The question that should give a usefull answer is:

**How can we force switching/checking a mirror?**

Yesterday I did not have this problem.

**Comment by pietereggink** [comment]
The same issue here for centos 6.8, vagrant up does no longer work.

**Comment by awalls** [comment]
Same here. 

config.yaml: https://gist.github.com/awalls/a15851fff32ab2a139792a1f7623a569

**Comment by janw-oostendorp** [comment]
After a lot of trying. In my case it was the internet connection which would stutter when downloading these files. Doing the same thing at home never gave problems.

Check if you ever get hickups when doing big file transfers.  
No guarantee this will help anybody else...

**Comment by jtreminio** [comment]
For CentOS, please try again now. Issues seem to be resolved.

@janw-oostendorp you can do the editing in an `exec-preprovision` bash script.
