### ISSUE TITLE
exec-provision-once and exec-provision-always?

### ISSUE THREAD

**Issue by hanoii** [puphpet/puphpet#2429]
I wonder if there's an option to already do this or if it's worth adding it, but I would like to run a script on each provision, but just on `vagrant provision`, not `vagrant up` as per exec-once and exec-always.

For now I am simply running a script that affects, in different ways, .bashrc. However, after running vagrant provision, .bashrc is overwritten from files/dot, losing the changes. I could run it all the time, but then .bashrc would also be recursively modified by `vagrant up`.

**Comment by hanoii** [comment]
I guess this might be exec-preprovision?

**Comment by jtreminio** [comment]
`exec-preprovision` is triggered before provisioning is done via Puppet, not on `vagrant provision`.

I'm unsure if there's a way to hook into Vagrant's `provision` command, but you can do a simple workaround that creates an empty file inside the VM on initial `vagrant up` and doesn't run any other code, but runs code on subsequent `provision`.
