### ISSUE TITLE
 Evaluation Error: Error while evaluating a Function Call, Could not find template 'apache/po                                       rts_header.erb' at /tmp/vagrant-puppet/modules-7f09dc5a4127deb80e6b5371cc184e82/apache/manifests/init.pp:249:16                                        on node oster.puphpet

### ISSUE THREAD

**Issue by RafaelRm23** [puphpet/puphpet#2432]
Evaluation Error: Error while evaluating a Function Call, Could not find template 'apache/po                                       rts_header.erb' at /tmp/vagrant-puppet/modules-7f09dc5a4127deb80e6b5371cc184e82/apache/manifests/init.pp:249:16                                        on node oster.puphpet

**Comment by jtreminio** [comment]
This is fixed with newest release.
