### ISSUE TITLE
How to config VM to allow outward connections on port 8080 for VM to connect to an external machine at that port (connection refused)

### ISSUE THREAD

**Issue by therobyouknow** [puphpet/puphpet#2433]
I'm trying to fetch data (using curl) from another machine at an address with port 8080, however the connection is being refused.

    [04:18 PM]-[vagrant@u1404php56]-[~] 
    $ curl "http://externalsite:8080"
    curl: (7) Failed to connect to externalsite port 8080: Connection refused

(where `externalsite` is the address of the other machine)

ping `externalsite` is successful so it can be reached.

How do I get my machine to allow me to talk to the other machine on port 8080?

What would I need to put in the config.yaml to allow connections to be made from my VM via port 8080?

I would need the solution to work for using curl and I need to use 8080.

Thank you.

**Comment by jtreminio** [comment]
You need to add the port to the firewall section. That's really the only thing needing done.
