### ISSUE TITLE
Memcached Support

### ISSUE THREAD

**Issue by chrisamoore** [puphpet/puphpet#244]

**Comment by boztek** [comment]
Is this feature request still likely to happen as far as a UI option?

**Comment by stuba** [comment]
Currently I'm having problems with php 5.6 and mecached

Transaction Check Error:
  file /usr/lib64/libhashkit.so.2.0.0 conflicts between attempted installs of libmemcached-last-libs-1.0.18-2.el6.remi.x86_64 and libmemcached10-1.0.16-1.ius.centos6.x86_64
  file /usr/lib64/libmemcached.so.11.0.0 conflicts between attempted installs of libmemcached-last-libs-1.0.18-2.el6.remi.x86_64 and libmemcached10-1.0.16-1.ius.centos6.x86_64
  file /usr/lib64/libmemcachedutil.so.2.0.0 conflicts between attempted installs of libmemcached-last-libs-1.0.18-2.el6.remi.x86_64 and libmemcached10-1.0.16-1.ius.centos6.x86_64

Just installed memcached manually by disabling ius repo.
