### ISSUE TITLE
Class[Puphpet::Php::Settings]: expects a value for parameter

### ISSUE THREAD

**Issue by ollie-new** [puphpet/puphpet#2441]
This morning I was experiencing this error with SSL and Ruby - #2440.

Since seeing the fix for that, I created a new server config and now get the following error:

> ==> puphpet: Error: Evaluation Error: Error while evaluating a Function Call, Class[Puphpet::Php::Settings]: expects a value for parameter 'version_string' at /tmp/vagrant-puppet/modules-aebc7fab29c9442cc2d2c8c1cabfab5c/puphpet/manifests/php/xdebug/compile.pp:4:3 on node machine1.puphpet
> The SSH command responded with a non-zero exit status. Vagrant
> assumes that this means the command failed. The output for this command
> should be in the log above. Please read the output to determine what
> went wrong.

Can anybody offer a solution? Thanks!

**Comment by jtreminio** [comment]
Please paste your config.yaml

**Comment by jtreminio** [comment]
Fixed by https://github.com/puphpet/puppet-puphpet/commit/6cae91d7351def1b0dac66b5af4b0898fa411958
