### ISSUE TITLE
The key 'shib2' is declared more than once

### ISSUE THREAD

**Issue by Renkas** [puphpet/puphpet#2442]
With Apache as webserver and up-to-date puphpet package (just downloaded from site).

Propably same problem? https://github.com/puppetlabs/puppetlabs-apache/pull/1458

box: puphpet/ubuntu1604-x64

> Warning: The key 'shib2' is declared more than once at /tmp/vagrant-puppet/modules-9b5156a594c4b67e30f4677700df6d70/apache/manifests/params.pp:251:21

**Comment by jtreminio** [comment]
This is a bug in the puppet-apache module and is fixed, but not tagged yet: https://github.com/puppetlabs/puppetlabs-apache/commit/ece000357b5ac30ae50f355b9f09605826df4c5d

**Comment by Renkas** [comment]
If its only a warning then it's not really a problem. I first thought it had something to do with the other problem -  the one you are already solving :) So this issue may be closed I think.
