### ISSUE TITLE
Box for Parallels updated on 20161004 does not exist?

### ISSUE THREAD

**Issue by jgudan** [puphpet/puphpet#2445]
vagrant box update
==> concept: Checking for updates to 'puphpet/ubuntu1404-x64'
    concept: Latest installed version: 20151201
    concept: Version constraints: 
    concept: Provider: parallels
==> concept: Updating 'puphpet/ubuntu1404-x64' with provider 'parallels' from version
==> concept: '20151201' to '20161004'...
==> concept: Loading metadata for box 'https://atlas.hashicorp.com/puphpet/ubuntu1404-x64'
==> concept: Adding box 'puphpet/ubuntu1404-x64' (v20161004) for provider: parallels
    concept: Downloading: https://atlas.hashicorp.com/puphpet/boxes/ubuntu1404-x64/versions/20161004/providers/parallels.box
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

The requested URL returned error: 404 Not Found

Hope that this is the right place for this problem.
Thank you for all help possible...

**Comment by jtreminio** [comment]
If you click that URL in your browser you'll download the box. I'm unsure why vagrant told you otherwise, but the box exists and that url is correct.

**Comment by jgudan** [comment]
Sorry, but I get 404 any way I try. Please, check again.

**Comment by jtreminio** [comment]
You're absolutely right. For some reason I was getting a correct response but now I see the box was incorrect named.

Weird!

And fixed.

**Comment by jgudan** [comment]
Thanks, m8!!! All works now.
