### ISSUE TITLE
New box gets stuck at SSH login on OS X

### ISSUE THREAD

**Issue by piersroberts** [puphpet/puphpet#2451]
Hi I'm having a problem SSHing to the following boxes since they updated to 20161004

- puphpet/ubuntu1604-x64
- puphpet/centos7-x64
- puphpet/ubuntu1404-x64
- puphpet/centos65-x64

This was tested as brand new user with no existing SSH settings changed

**sw_vers**
ProductName:	Mac OS X
ProductVersion:	10.11.6
BuildVersion:	15G1004

**VBoxManage -v**
5.0.26r108824

**vagrant -v**
Vagrant 1.8.6

I've attached a log of what happens when trying to launch a box and ssh in
> VAGRANT_LOG=DEBUG vagrant init puphpet/centos65-x64; vagrant up --provider virtualbox

[puphpet_debug.txt](https://github.com/puphpet/puphpet/files/516395/puphpet_debug.txt)

**Comment by ECMachado** [comment]
Same here on Ubuntu 16.04 host

**Comment by thischarmingsam8** [comment]
Same here, Ubuntu 14.04 and both 16.04 variants halt at 'Warning: Remote connection disconnect. Retrying...' when attempting vagrant up. Virtualbox GUI shows ubuntu searching for network configuration. Using OSX / Virtualbox.

**Comment by piersroberts** [comment]
Updating to VirtualBox 5.1.6 fixes this for me

**Comment by jtreminio** [comment]
Solution is upgrading to latest VirtualBox 5.1.x version _from the website_, not through the app's auto update.
