### ISSUE TITLE
New boxes can't make it past SSH auth method: private key

### ISSUE THREAD

**Issue by mawint** [puphpet/puphpet#2454]
Using the steps provided after the most recent update (vagrant box remove) and updating the boxes. I no longer can get the boxes to fully provision. Currently they get stuck at authentication and cannot progress, eventually timing out. 

MacOS Sierra 10.12
Virtualbox 5.0.26 r108824
Vagrant 1.8.6

Current [config.yaml](http://pastebin.com/UrH64RTX), downloaded and re-configured today.

Error received during vagrant up:

> Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.

>If you look above, you should be able to see the error(s) that
Vagrant had when attempting to connect to the machine. These errors
are usually good hints as to what may be wrong.

>If you're using a custom box, make sure that networking is properly
working and you're able to connect to the machine. It is a common
problem that networking isn't setup properly in these boxes.
Verify that authentication configurations are also setup properly,
as well.

>If the box appears to be booting properly, you may want to increase
the timeout ("config.vm.boot_timeout") value.

**Comment by jtreminio** [comment]
> Virtualbox 5.0.26 r108824

Upgrade this to 5.1.x

**Comment by mawint** [comment]
Virtualbox shows that it is the newest version directly from the application after doing a check for update. Apparently it lies. 

I'll test it out.

**Comment by mawint** [comment]
Fixed.
