### ISSUE TITLE
Created several brand new ubuntu boxes but none can get past ssh time out.

### ISSUE THREAD

**Issue by red-smeg** [puphpet/puphpet#2460]
$ vagrant up
Bringing machine 'vagrant' up with 'virtualbox' provider...
==> vagrant: Checking if box 'puphpet/ubuntu1604-x64' is up to date...
==> vagrant: Clearing any previously set forwarded ports...
==> vagrant: Clearing any previously set network interfaces...
==> vagrant: Preparing network interfaces based on configuration...
    vagrant: Adapter 1: nat
    vagrant: Adapter 2: hostonly
==> vagrant: Forwarding ports...
    vagrant: 22 (guest) => 2222 (host) (adapter 1)
==> vagrant: Running 'pre-boot' VM customizations...
==> vagrant: Booting VM...
==> vagrant: Waiting for machine to boot. This may take a few minutes...
    vagrant: SSH address: 127.0.0.1:2222
    vagrant: SSH username: vagrant
    vagrant: SSH auth method: private key
Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.

If you look above, you should be able to see the error(s) that
Vagrant had when attempting to connect to the machine. These errors
are usually good hints as to what may be wrong.

If you're using a custom box, make sure that networking is properly
working and you're able to connect to the machine. It is a common
problem that networking isn't setup properly in these boxes.
Verify that authentication configurations are also setup properly,
as well.

If the box appears to be booting properly, you may want to increase
the timeout ("config.vm.boot_timeout") value.

[Vagrantfile.txt](https://github.com/puphpet/puphpet/files/518674/Vagrantfile.txt)

[config.yaml.txt](https://github.com/puphpet/puphpet/files/518675/config.yaml.txt)

**Comment by cslevy** [comment]
I had the same issue. I updated the Virtualbox and Vagrant to the latest version and that fixed the issue on my side

**Comment by tschortsch** [comment]
Same here with a `puphpet/centos65-x64` box. After updating puphpet and the box (`vagrant box remove puphpet/centos65-x64`) I always get a SSH timeout.
I am already running the latest versions of VirtualBox (5.0.26) and Vagrant (1.8.6).

**Comment by sseidelmann** [comment]
Same here. I read a lot about this problem. Might be a Problem described here:
http://askubuntu.com/questions/824376/failed-to-start-raise-network-interfaces-after-upgrading-to-16-04

My networking.service status output shows this:
![bildschirmfoto 2016-10-10 um 09 36 40](https://cloud.githubusercontent.com/assets/1152783/19229348/26b9a87e-8ecd-11e6-8dba-a70a3cfa18e7.png)

The /etc/network/interfaces output shows this:
![bildschirmfoto 2016-10-10 um 09 38 02](https://cloud.githubusercontent.com/assets/1152783/19229378/587ced6c-8ecd-11e6-839c-f2f51ca97e34.png)

**Comment by cslevy** [comment]
VirtualBox 5.1.6 released!

**Comment by tschortsch** [comment]
With VirtualBox 5.1.6 it works! Thanks a lot.

**Comment by sseidelmann** [comment]
Jeah - VB 5.1.6 works fine!

**Comment by red-smeg** [comment]
not working with 5.1.6 for me

**Comment by red-smeg** [comment]
Ok got it working finally.

**Comment by red-smeg** [comment]
Getting this error:

==> vagrant: Warning: The key 'shib2' is declared more than once at /tmp/vagrant-puppet/modules-881fd8f6751b6f13fd60a3212cb57f0d/apache/manifests/params.pp:251:21

**Comment by kevin-barrientos** [comment]
@red-smeg how did you fix it? I already update vagrant and virtual box but it still hangs at ssh auth

**Comment by kevin-barrientos** [comment]
Never mind, I got it working after uploading my config.yaml to [www.puphpet.com](www.puphpet.com) to recreate the archive.
