### ISSUE TITLE
Creating a new box with 16.04 & php 7.1 and xdebug options cause php cli problems

### ISSUE THREAD

**Issue by red-smeg** [puphpet/puphpet#2470]
Getting many warnings of 

 PHP Warning:  Module '  <module name>   ' already loaded in Unknown on line 0 .  

when using php on the command line the following configuration (see attached)

Suspect there is a problem with one of setup routines when the debug option is chosen on puphpet.com. 

[config.yaml.txt](https://github.com/puphpet/puphpet/files/524914/config.yaml.txt)

**Comment by red-smeg** [comment]
looks like a similar problem was raised earlier.  the following modules were specified in the config.yaml 

            - common
            - cli
            - intl
            - mcrypt
            - curl
            - gd
            - mysql
            - mbstring
            - xml

I can see that according to your other post mcyrpt is included but what of the others can i remove also ??

**Comment by red-smeg** [comment]
this is the full output from the failure;

`==> vagrant: cache:clear [--no-warmup] [--no-optional-warmers] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] 
[-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-s|--shell] [--process-isolation] [-e|--env ENV] 
[--no-debug] [--] <command>

==> vagrant: Script Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache handling the 
post-install-cmd event terminated with an exception
==> vagrant:                                                                                                                                                                                                                                                                                         
==> vagrant:   [RuntimeException]                                                                                                                                                                                                                                                                    
==> vagrant:   An error occurred when executing the "'cache:clear --no-warmup'" command:                                                                                                                                                                                                             
==> vagrant:    // Clearing the cache for the dev environment with debug true                                                                                                                                                                                                                        
==> vagrant:   Cannot load Zend OPcache - it was already loaded                                                                                                                                                                                                                                      
==> vagrant:   Cannot load Xdebug - it was already loaded                                                                                                                                                                                                                                            
==> vagrant:   PHP Warning:  Module 'mysqlnd' already loaded in Unknown on line 0                                                                                                                                                                                                                    
==> vagrant:   PHP Warning:  Module 'PDO' already loaded in Unknown on line 0                                                                                                                                                                                                                        
==> vagrant:   PHP Warning:  Module 'xml' already loaded in Unknown on line 0                                                                                                                                                                                                                        
==> vagrant:   PHP Warning:  Module 'calendar' already loaded in Unknown on line 0                                                                                                                                                                                                                   
==> vagrant:   PHP Warning:  Module 'ctype' already loaded in Unknown on line 0                                                                                                                                                                                                                      
==> vagrant:   PHP Warning:  Module 'curl' already loaded in Unknown on line 0                                                                                                                                                                                                                       
==> vagrant:   PHP Warning:  Module 'dom' already loaded in Unknown on line 0                                                                                                                                                                                                                        
==> vagrant:   PHP Warning:  Module 'exif' already loaded in Unknown on line 0                                                                                                                                                                                                                       
==> vagrant:   PHP Warning:  Module 'fileinfo' already loaded in Unknown on line 0                                                                                                                                                                                                                   
==> vagrant:   PHP Warning:  Module 'ftp' already loaded in Unknown on line 0                                                                                                                                                                                                                        
==> vagrant:   PHP Warning:  Module 'gd' already loaded in Unknown on line 0                                                                                                                                                                                                                         
==> vagrant:   PHP Warning:  Module 'gettext' already loaded in Unknown on line 0                                                                                                                                                                                                                    
==> vagrant:   PHP Warning:  Module 'iconv' already loaded in Unknown on line 0                                                                                                                                                                                                                      
==> vagrant:   PHP Warning:  Module 'intl' already loaded in Unknown on line 0                                                                                                                                                                                                                       
==> vagrant:   PHP Warning:  Module 'json' already loaded in Unknown on line 0                                                                                                                                                                                                                       
==> vagrant:   PHP Warning:  Module 'mbstring' already loaded in Unknown on line 0                                                                                                                                                                                                                   
==> vagrant: 
==> vagrant:   PHP Warning:  Module 'mcrypt' already loaded in Unknown on line 0                                                                                                                                                                                                                     
==> vagrant:   PHP Warning:  Module 'mysqli' already loaded in Unknown on line 0                                                                                                                                                                                                                     
==> vagrant:   PHP Warning:  Module 'pdo_mysql' already loaded in Unknown on line 0                                                                                                                                                                                                                  
==> vagrant:   PHP Warning:  Module 'Phar' already loaded in Unknown on line 0                                                                                                                                                                                                                       
==> vagrant:   PHP Warning:  Module 'posix' already loaded in Unknown on line 0                                                                                                                                                                                                                      
==> vagrant:   PHP Warning:  Module 'readline' already loaded in Unknown on line 0                                                                                                                                                                                                                   
==> vagrant:   PHP Warning:  Module 'shmop' already loaded in Unknown on line 0                                                                                                                                                                                                                      
==> vagrant:   PHP Warning:  Module 'SimpleXML' already loaded in Unknown on line 0                                                                                                                                                                                                                  
==> vagrant:   PHP Warning:  Module 'sockets' already loaded in Unknown on line 0                                                                                                                                                                                                                    
==> vagrant:   PHP Warning:  Module 'sysvmsg' already loaded in Unknown on line 0                                                                                                                                                                                                                    
==> vagrant:   PHP Warning:  Module 'sysvsem' already loaded in Unknown on line 0                                                                                                                                                                                                                    
==> vagrant:   PHP Warning:  Module 'sysvshm' already loaded in Unknown on line 0                                                                                                                                                                                                                    
==> vagrant:   PHP Warning:  Module 'tokenizer' already loaded in Unknown on line 0                                                                                                                                                                                                                  
==> vagrant:   PHP Warning:  Module 'wddx' already loaded in Unknown on line 0                                                                                                                                                                                                                       
==> vagrant:   PHP Warning:  Module 'xmlreader' already loaded in Unknown on line 0                                                                                                                                                                                                                  
==> vagrant:   PHP Warning:  Module 'xmlwriter' already loaded in Unknown on line 0                                                                                                                                                                                                                  
==> vagrant:   PHP Warning:  Module 'xsl' already loaded in Unknown on line 0                                                                                                                                                                                                                        
==> vagrant:                                                                                                                                                                                                                                                                                         
==> vagrant:     [Symfony\Component\Filesystem\Exception\IOException]`

**Comment by red-smeg** [comment]
the only puppet error during the build of the vm was

 Warning: The key 'shib2' is declared more than once at /tmp/vagrant-puppet/modules-4b0e4bd4b13ec21d5fd74d328441827b/apache/manifests/params.pp:251:21
==> vagrant:

**Comment by red-smeg** [comment]
looks like it is the addition of the "curl" module to the php section that causes the problem

**Comment by red-smeg** [comment]
the problem shows itself when running composer install

**Comment by red-smeg** [comment]
I have raised an issue on the composer repo as it could be related to composer copying the php.ini into /tmp/vagrant-composer.php.ini

**Comment by red-smeg** [comment]
Looks like the composer group are looking into this problem

**Comment by red-smeg** [comment]
I think this can be closed the composer repo team have it as a bug and are working in it.

**Comment by jtreminio** [comment]
You found the bug, reported it, identified what caused it, submitted another issue and got the team to try to fix it.

Well done!
