### ISSUE TITLE
puphpet/centos7-64 box is missing VMware tools

### ISSUE THREAD

**Issue by terojankkila** [puphpet/puphpet#2472]
Starting Puphpet box Centos7 with VMware Fusion or VMware Workstation fails on creating shared folders. 

On Mac OS error message is missing HGFS Kernel module
`
==> machine: Waiting for HGFS to become available...
HGFS was never found on the running virtual machine. This must be
installed either through VMware tools or Open VM Tools. HGFS is
required for shared folders to work properly. Please install either
the VMware tools or Open VM Tools and try again.
`
OpenVMTools isn't enough though you need VMware tools as Open tools doesn't contain HGFS Kernel module.

**Comment by jtreminio** [comment]
This should be fixed with newest version of boxes uploaded today.
