### ISSUE TITLE
Error running 'requirements_debian_update_system ruby-2.3.0'

### ISSUE THREAD

**Issue by lsiden** [puphpet/puphpet#2478]
I'm using Vagrant version 1.8.6 with the Ubuntu 16.04 64-bit virtual box.  When I run 'vagrant provision' it generates the following error messages: https://gist.github.com/lsiden/11ee113b0798e19a255e5a88d9c984e3

If I open an ssh session in the box and type 'sudo apt-get update' this is the end of the output:

> Reading package lists... Done
> W: The repository 'http://mirror.jmu.edu/pub/mariadb/repo/5.5/ubuntu xenial Release' does not have a Release file.
> N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
> N: See apt-secure(8) manpage for repository creation and user configuration details.
> E: Failed to fetch http://mirror.jmu.edu/pub/mariadb/repo/5.5/ubuntu/dists/xenial/main/source/Sources  404  Not Found
> E: Some index files failed to download. They have been ignored, or old ones used instead.

I don't think that there is a xenial release for mariadb.

**Comment by jtreminio** [comment]
No longer an issue.
