### ISSUE TITLE
phuphet or vagrant up issue 

### ISSUE THREAD

**Issue by sibusisocyril** [puphpet/puphpet#2481]
I seem not to be able to completely vagrant up my machine , can anyone help with regard to this 
 vagrant up
Bringing machine 'local-webo' up with 'virtualbox' provider...
==> local-webo: Checking if box 'puphpet/ubuntu1404-x64' is up to date...
==> local-webo: A newer version of the box 'puphpet/ubuntu1404-x64' is available                                                                                                                           ! You currently
==> local-webo: have version '20151201'. The latest is version '20161004'. Run
==> local-webo: `vagrant box update` to update.
==> local-webo: Clearing any previously set forwarded ports...
==> local-webo: Clearing any previously set network interfaces...
==> local-webo: Preparing network interfaces based on configuration...
    local-webo: Adapter 1: nat
    local-webo: Adapter 2: hostonly
==> local-webo: Forwarding ports...
    local-webo: 22 (guest) => 6398 (host) (adapter 1)
    local-webo: 22 (guest) => 2222 (host) (adapter 1)
==> local-webo: Running 'pre-boot' VM customizations...
==> local-webo: Booting VM...
==> local-webo: Waiting for machine to boot. This may take a few minutes...
    local-webo: SSH address: 127.0.0.1:2222
    local-webo: SSH username: vagrant
    local-webo: SSH auth method: private key
==> local-webo: Machine booted and ready!
[local-webo] GuestAdditions versions on your host (5.1.6) and guest (5.0.24) do                                                                                                                            not match.
Reading package lists...
Building dependency tree...
Reading state information...
dkms is already the newest version.
linux-headers-3.19.0-25-generic is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 123 not upgraded.
Copy iso file C:\Program Files\Oracle\VirtualBox\VBoxGuestAdditions.iso into the                                                                                                                            box /tmp/VBoxGuestAdditions.iso
mount: block device /tmp/VBoxGuestAdditions.iso is write-protected, mounting rea                                                                                                                           d-only
Installing Virtualbox Guest Additions 5.0.24 - guest version is 5.0.24
Verifying archive integrity... All good.
Uncompressing VirtualBox 5.0.24 Guest Additions for Linux............
VirtualBox Guest Additions installer
Removing installed version 5.0.24 of VirtualBox Guest Additions...
Stopping VirtualBox Additions ...fail!
(Cannot unload module vboxguest)
Removing existing VirtualBox DKMS kernel modules ...done.
Removing existing VirtualBox non-DKMS kernel modules ...done.
update-initramfs: Generating /boot/initrd.img-/3.19.0-25-generic
Stopping VirtualBox Guest Addition service  ...done.
Copying additional installer modules ...
Installing additional modules ...
Removing existing VirtualBox DKMS kernel modules ...done.
Removing existing VirtualBox non-DKMS kernel modules ...done.
Building the VirtualBox Guest Additions kernel modules ...done.
Doing non-kernel setup of the Guest Additions ...done.
You should restart your guest to make sure the new modules are actually used

==> local-webo: Checking for guest additions in VM...
    local-webo: The guest additions on this VM do not match the installed versio                                                                                                                           n of
    local-webo: VirtualBox! In most cases this is fine, but in rare cases it can
    local-webo: prevent things such as shared folders from working properly. If                                                                                                                            you see
    local-webo: shared folder errors, please make sure the guest additions withi                                                                                                                           n the
    local-webo: virtual machine match the version of VirtualBox you have install                                                                                                                           ed on
    local-webo: your host and reload your VM.
    local-webo:
    local-webo: Guest Additions Version: 5.0.24
    local-webo: VirtualBox Version: 5.1
==> local-webo: Setting hostname...
==> local-webo: Configuring and enabling network interfaces...
==> local-webo: Mounting shared folders...
    local-webo: /vagrant => C:/Users/User/Documents/git_repos/wealthbot/vagrant
    local-webo: /srv/wealthbot => C:/Users/User/Documents/git_repos/wealthbot
    local-webo: /tmp/vagrant-puppet/modules-2c2c147b5c36592e09d1ab041d4b3f98 =>                                                                                                                            C:/Users/User/Documents/git_repos/wealthbot/vagrant/puphpet/puppet/modules
    local-webo: /tmp/vagrant-puppet/manifests-75f35e3bc7e32744860c4bb229c88812 =                                                                                                                           > C:/Users/User/Documents/git_repos/wealthbot/vagrant/puphpet/puppet/manifests
==> local-webo: Machine already provisioned. Run `vagrant provision` or use the                                                                                                                            `--provision`
==> local-webo: flag to force provisioning. Provisioners marked to run always wi                                                                                                                           ll still run.
==> local-webo: Running provisioner: shell...
    local-webo: Running: C:/Users/User/AppData/Local/Temp/vagrant-shell20161020-                                                                                                                           8684-1pb5crk.sh
==> local-webo: Running files in files/startup-once
==> local-webo: Finished running files in files/startup-once
==> local-webo: To run again, delete hashes you want rerun in /.puphpet-stuff/st                                                                                                                           artup-once-ran or the whole file to rerun all
==> local-webo: Running files in files/startup-always
==> local-webo: Finished running files in files/startup-always
==> local-webo: Running provisioner: shell...
    local-webo: Running: C:/Users/User/AppData/Local/Temp/vagrant-shell20161020-                                                                                                                           8684-1ar7jhq.sh
==> local-webo: Running files in files/startup-once-unprivileged
==> local-webo: Finished running files in files/startup-once-unprivileged
==> local-webo: To run again, delete hashes you want rerun in /.puphpet-stuff/st                                                                                                                           artup-once-unprivileged-ran or the whole file to rerun all
==> local-webo: Running files in files/startup-always-unprivileged
==> local-webo: Finished running files in files/startup-always-unprivileged

**Comment by marcosgdf** [comment]
I think you should update your vagrant box

**Comment by sibusisocyril** [comment]
I have but this is what i still get 
Bringing machine 'local-webo' up with 'virtualbox' provider...
==> local-webo: Checking if box 'puphpet/ubuntu1404-x64' is up to date...
==> local-webo: Clearing any previously set forwarded ports...
==> local-webo: Clearing any previously set network interfaces...
==> local-webo: Preparing network interfaces based on configuration...
    local-webo: Adapter 1: nat
    local-webo: Adapter 2: hostonly
==> local-webo: Forwarding ports...
    local-webo: 22 (guest) => 6398 (host) (adapter 1)
    local-webo: 22 (guest) => 2222 (host) (adapter 1)
==> local-webo: Running 'pre-boot' VM customizations...
==> local-webo: Booting VM...
==> local-webo: Waiting for machine to boot. This may take a few minutes...
    local-webo: SSH address: 127.0.0.1:2222
    local-webo: SSH username: vagrant
    local-webo: SSH auth method: private key
==> local-webo: Machine booted and ready!
[local-webo] GuestAdditions versions on your host (5.1.6) and guest (5.0.24) do                                                                                                                            not match.
Reading package lists...
Building dependency tree...
Reading state information...
dkms is already the newest version.
linux-headers-3.19.0-25-generic is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 123 not upgraded.
Copy iso file C:\Program Files\Oracle\VirtualBox\VBoxGuestAdditions.iso into the                                                                                                                            box /tmp/VBoxGuestAdditions.iso
mount: block device /tmp/VBoxGuestAdditions.iso is write-protected, mounting rea                                                                                                                           d-only
Installing Virtualbox Guest Additions 5.0.24 - guest version is 5.0.24
Verifying archive integrity... All good.
Uncompressing VirtualBox 5.0.24 Guest Additions for Linux............
VirtualBox Guest Additions installer
Removing installed version 5.0.24 of VirtualBox Guest Additions...
Stopping VirtualBox Additions ...fail!
(Cannot unload module vboxguest)
Removing existing VirtualBox DKMS kernel modules ...done.
Removing existing VirtualBox non-DKMS kernel modules ...done.
update-initramfs: Generating /boot/initrd.img-/3.19.0-25-generic
Stopping VirtualBox Guest Addition service  ...done.
Copying additional installer modules ...
Installing additional modules ...
Removing existing VirtualBox DKMS kernel modules ...done.
Removing existing VirtualBox non-DKMS kernel modules ...done.
Building the VirtualBox Guest Additions kernel modules ...done.
Doing non-kernel setup of the Guest Additions ...done.
You should restart your guest to make sure the new modules are actually used

==> local-webo: Checking for guest additions in VM...
    local-webo: The guest additions on this VM do not match the installed versio                                                                                                                           n of
    local-webo: VirtualBox! In most cases this is fine, but in rare cases it can
    local-webo: prevent things such as shared folders from working properly. If                                                                                                                            you see
    local-webo: shared folder errors, please make sure the guest additions withi                                                                                                                           n the
    local-webo: virtual machine match the version of VirtualBox you have install                                                                                                                           ed on
    local-webo: your host and reload your VM.
    local-webo:
    local-webo: Guest Additions Version: 5.0.24
    local-webo: VirtualBox Version: 5.1
==> local-webo: Setting hostname...
==> local-webo: Configuring and enabling network interfaces...
==> local-webo: Mounting shared folders...
    local-webo: /vagrant => C:/Users/User/Documents/git_repos/wealthbot/vagrant
    local-webo: /srv/wealthbot => C:/Users/User/Documents/git_repos/wealthbot
    local-webo: /tmp/vagrant-puppet/modules-2c2c147b5c36592e09d1ab041d4b3f98 =>                                                                                                                            C:/Users/User/Documents/git_repos/wealthbot/vagrant/puphpet/puppet/modules
    local-webo: /tmp/vagrant-puppet/manifests-75f35e3bc7e32744860c4bb229c88812 =                                                                                                                           > C:/Users/User/Documents/git_repos/wealthbot/vagrant/puphpet/puppet/manifests
==> local-webo: Machine already provisioned. Run `vagrant provision` or use the                                                                                                                            `--provision`
==> local-webo: flag to force provisioning. Provisioners marked to run always wi                                                                                                                           ll still run.
==> local-webo: Running provisioner: shell...
    local-webo: Running: C:/Users/User/AppData/Local/Temp/vagrant-shell20161024-                                                                                                                           6016-18wa9uz.sh
==> local-webo: Running files in files/startup-once
==> local-webo: Finished running files in files/startup-once
==> local-webo: To run again, delete hashes you want rerun in /.puphpet-stuff/st                                                                                                                           artup-once-ran or the whole file to rerun all
==> local-webo: Running files in files/startup-always
==> local-webo: Finished running files in files/startup-always
==> local-webo: Running provisioner: shell...
    local-webo: Running: C:/Users/User/AppData/Local/Temp/vagrant-shell20161024-                                                                                                                           6016-gksz0m.sh
==> local-webo: Running files in files/startup-once-unprivileged
==> local-webo: Finished running files in files/startup-once-unprivileged
==> local-webo: To run again, delete hashes you want rerun in /.puphpet-stuff/st                                                                                                                           artup-once-unprivileged-ran or the whole file to rerun all
==> local-webo: Running files in files/startup-always-unprivileged
==> local-webo: Finished running files in files/startup-always-unprivileged

**Comment by sibusisocyril** [comment]
Can anyone help in this regard ? I need assistance

**Comment by gkobilansky** [comment]
Have you tried running `vagrant provision` as per the instructions in your output?

**Comment by sibusisocyril** [comment]
I have and this is the outcome 
 vagrant provision
==> local-webo: Running provisioner: shell...
    local-webo: Running: inline script
==> local-webo: Running provisioner: shell...
    local-webo: Running: C:/Users/User/AppData/Local/Temp/vagrant-shell20161026-2884-j1puen.sh
==> local-webo:
==> local-webo:  ____        ____  _   _ ____      _      generated using
==> local-webo: |  _ \ _   _|  _ \| | | |  _ \ ___| |_   ___ ___  _ __ ___
==> local-webo: | |_) | | | | |_) | |_| | |_) / _ \ __| / __/ _ \| '_ ` _ \
==> local-webo: |  __/| |_| |  __/|  _  |  __/  __/ |_ | (_| (_) | | | | | |
==> local-webo: |_|    \__,_|_|   |_| |_|_|   \___|\__(_)___\___/|_| |_| |_|
==> local-webo: Running provisioner: shell...
    local-webo: Running: C:/Users/User/AppData/Local/Temp/vagrant-shell20161026-2884-wu9zz2.sh
==> local-webo: Pre-existing private key found at 'puphpet/files/dot/ssh/root_id_rsa'
==> local-webo: Pre-existing private key found at 'puphpet/files/dot/ssh/id_rsa'
==> local-webo: Adding generated root key to /root/.ssh/id_rsa
==> local-webo: Adding generated root key to /root/.ssh/id_rsa.pub
==> local-webo: Adding generated root key to /root/.ssh/authorized_keys
==> local-webo: Adding generated key to /home/vagrant/.ssh/id_rsa
==> local-webo: Adding generated key to /home/vagrant/.ssh/id_rsa.pub
==> local-webo: Adding generated key to /home/vagrant/.ssh/authorized_keys
==> local-webo: Running provisioner: shell...
    local-webo: Running: C:/Users/User/AppData/Local/Temp/vagrant-shell20161026-2884-1xz4pcu.sh
==> local-webo: Running provisioner: shell...
    local-webo: Running: C:/Users/User/AppData/Local/Temp/vagrant-shell20161026-2884-1c8z6wi.sh
==> local-webo: ERROR:  Could not find a valid gem 'deep_merge' (= 1.0.1), here is why:
==> local-webo:           Unable to download data from https://rubygems.org/ - SSL_connect returned=1 errno=0 state=error: certificate verify failed (https://api.rubygems.org/specs.4.8.gz)
==> local-webo: ERROR:  Could not find a valid gem 'activesupport' (= 4.2.6), here is why:
==> local-webo:           Unable to download data from https://rubygems.org/ - SSL_connect returned=1 errno=0 state=error: certificate verify failed (https://api.rubygems.org/specs.4.8.gz)
==> local-webo: ERROR:  Could not find a valid gem 'vine' (= 0.2), here is why:
==> local-webo:           Unable to download data from https://rubygems.org/ - SSL_connect returned=1 errno=0 state=error: certificate verify failed (https://api.rubygems.org/specs.4.8.gz)
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what

**Comment by sibusisocyril** [comment]
Here is my config.yaml
vagrantfile:
    target: local
    vm:
        provider:
            local:
                box: puphpet/ubuntu1404-x64
                box_url: puphpet/ubuntu1404-x64
                box_version: '0'
                chosen_virtualizer: virtualbox
                virtualizers:
                    virtualbox:
                        modifyvm:
                            natdnshostresolver1: false
                        showgui: 0
                    vmware:
                        numvcpus: 1
                    parallels:
                        use_linked_clone: 0
                        check_guest_tools: 0
                        update_guest_tools: 0
                machines:
                    vflm_7yomyv1xjdd5:
                        id: local-webo
                        hostname: local-webo
                        network:
                            private_network: 192.168.56.105
                            forwarded_port:
                                vflmnfp_ni8lebu8hbt4:
                                    host: '6398'
                                    guest: '22'
                        memory: '1024'
                        cpus: '2'
        provision:
            puppet:
                manifests_path: puphpet/puppet/manifests
                module_path: puphpet/puppet/modules
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
        synced_folder:
            vflsf_4mbhpvm1lfzr:
                source: ../
                target: /srv/wealthbot
                sync_type: default
                smb:
                    smb_host: ''
                    smb_username: ''
                    smb_password: ''
                    mount_options:
                        dir_mode: '0775'
                        file_mode: '0664'
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    exclude:
                        - .vagrant/
                        - .git/
                    auto: 'true'
                owner: www-data
                group: www-data
        usable_port_range:
            start: 10200
            stop: 10500
        post_up_message: ''
    ssh:
        host: 'false'
        port: 'false'
        private_key_path: 'false'
        username: vagrant
        guest_port: 'false'
        keep_alive: '1'
        forward_agent: 'false'
        forward_x11: 'false'
        shell: 'bash -l'
        insert_key: 'false'
    vagrant:
        host: detect
    proxy:
        http: ''
        https: ''
        ftp: ''
        no_proxy: ''
server:
    install: '1'
    packages:
        - libsasl2-dev

users_groups:
    install: '1'
    groups: {  }
    users: {  }
locale:
    install: '1'
    settings:
        default_locale: en_US.UTF-8
        locales:
            - en_GB.UTF-8
            - en_US.UTF-8
        timezone: UTC
firewall:
    install: '1'
    rules: {  }
cron:
    install: '1'
    jobs: {  }
nginx:
    install: '0'
    settings:
        default_vhost: 1
        proxy_buffer_size: 128k
        proxy_buffers: '4 256k'
        proxy_connect_timeout: 600s
        proxy_send_timeout: 600s
        proxy_read_timeout: 600s
        names_hash_bucket_size: 128
    upstreams: {  }
    vhosts:
        nxv_yr0go8z1mtve:
            server_name: awesome.dev
            server_aliases:
                - www.awesome.dev
            www_root: /var/www/awesome
            listen_port: '80'
            index_files:
                - index.html
                - index.htm
                - index.php
            client_max_body_size: 1m
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_port: '443'
            ssl_protocols: ''
            ssl_ciphers: ''
            rewrite_to_https: '1'
            spdy: '1'
            locations:
                nxvl_k3uzc9xo0yo9:
                    location: /
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
                    fastcgi: ''
                    fastcgi_index: ''
                    fastcgi_split_path: ''
                    proxy: ''
                    proxy_redirect: ''
                nxvl_hraamgw84c8l:
                    location: '~ \.php$'
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
                    fastcgi: '127.0.0.1:9000'
                    fastcgi_index: index.php
                    fastcgi_split_path: '^(.+\.php)(/.*)$'
                    fast_cgi_params_extra:
                        - 'SCRIPT_FILENAME $request_filename'
                        - 'APP_ENV dev'
                    set:
                        - '$path_info $fastcgi_path_info'
                    proxy: ''
                    proxy_redirect: ''
    proxies: {  }
apache:
    install: '1'
    settings:
        version: 2.4
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - proxy_fcgi
        - rewrite
    vhosts:
        av_0of7v63kwayx:
            servername: local.wealthbot.io
            serveraliases:
                - app.wealthbot.io
            docroot: /srv/wealthbot/web
            port: '80'
            setenv:
                - 'APP_ENV dev'
            setenvif:
                - 'Authorization "(.*)" HTTP_AUTHORIZATION=$1'
            custom_fragment: ''
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            ssl_protocol: ''
            ssl_cipher: ''
            directories:
                avd_8ob18d95f4kc:
                    path: /srv/wealthbot/web
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - 'all granted'
                    custom_fragment: ''
                    files_match:
                        avdfm_kawahn69g1qs:
                            path: \.php$
                            sethandler: 'proxy:fcgi://127.0.0.1:9000'
                            custom_fragment: ''
                            provider: filesmatch
                    provider: directory
letsencrypt:
    install: '1'
    settings:
        email: ''
    domains: {  }
php:
    install: '1'
    settings:
        version: '56'
    modules:
        php:
            - cli
            - intl
            - imagick
            - mcrypt
            - fpm
            - xml
            - curl
            - apcu
            - mongo

        pear: {  }
        pecl: {  }
    ini:
        display_errors: 'On'
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
        date.timezone: UTC
    fpm_ini:
        error_log: /var/log/php-fpm.log
    fpm_pools:
        phpfp_bcu2oirpw6my:
            ini:
                prefix: www
                listen: '127.0.0.1:9000'
                security.limit_extensions: .php
                user: www-user
                group: www-data
    composer: '1'
    composer_home: ''
xdebug:
    install: '1'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
blackfire:
    install: '0'
    settings:
        server_id: ''
        server_token: ''
        agent:
            http_proxy: ''
            https_proxy: ''
            log_file: stderr
            log_level: '1'
        php:
            agent_timeout: '0.25'
            log_file: ''
            log_level: '1'
xhprof:
    install: '0'
wpcli:
    install: '0'
    version: v0.21.1
drush:
    install: '0'
    version: 8.0.5
ruby:
    install: '1.9.3'
    versions:
        rv_vo1k5t644t5o:
            default: '1'
            bundler: '1'
            version: 1.9.3
            gems:
                - deep_merge@1.0.1
                - activesupport@4.2.6
                - vine@0.2
python:
    install: '1'
    packages: {  }
    versions: {  }
nodejs:
    install: '0'
    settings:
        version: '5'
    npm_packages: {  }
hhvm:
    install: '0'
    nightly: 0
    composer: '1'
    composer_home: ''
    settings: {  }
    server_ini:
        hhvm.server.host: 127.0.0.1
        hhvm.server.port: '9000'
        hhvm.log.use_log_file: '1'
        hhvm.log.file: /var/log/hhvm/error.log
    php_ini:
        display_errors: 'On'
        error_reporting: '-1'
        date.timezone: UTC
mariadb:
    install: '0'
    settings:
        version: '10.1'
        root_password: '123'
        override_options: {  }
    adminer: 0
    users:
        mariadbnu_w11uqhtrew9c:
            name: dbuser
            password: '123'
    databases:
        mariadbnd_slhvrvlgyy31:
            name: dbname
            sql: ''
    grants:
        mariadbng_qmlbqkfl54di:
            user: dbuser
            table: '*.*'
            privileges:
                - ALL
mysql:
    install: '1'
    settings:
        version: '5.6'
        root_password: password
        override_options: {  }
    adminer: 0
    users:
        mysqlnu_l8ptsb7lwoo5:
            name: webo
            password: password
    databases:
        mysqlnd_e5scxr89myss:
            name: wealthbot
            sql: ''
    grants:
        mysqlng_f4v5lxqmii62:
            user: webo
            table: '*.*'
            privileges:
                - ALL
postgresql:
    install: '0'
    settings:
        global:
            encoding: UTF8
            version: '9.4'
        server:
            postgres_password: '123'
    databases: {  }
    users: {  }
    grants: {  }
    adminer: 0
mongodb:
    install: '1'
    settings:
        bind_ip: 127.0.0.1
        port: '27017'
    globals:
        version: 2.6.0
    databases:
        mongodbnuad_louvsfvja7ij:
            name: wealthbot
            user: webo
            password: password
redis:
    install: '1'
    settings:
        port: '6379'
sqlite:
    install: '1'
    adminer: 0
    databases: {  }
mailhog:
    install: '0'
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '8025'
        path: /usr/local/bin/mailhog
beanstalkd:
    install: '0'
    settings:
        listenaddress: 0.0.0.0
        listenport: '11300'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: 0
rabbitmq:
    install: '0'
    settings:
        port: '5672'
    users: {  }
    vhosts: {  }
    plugins: {  }
elastic_search:
    install: '0'
    settings:
        version: 2.3.1
        java_install: true
    instances:
        esi_2bmiklxvorxy:
            name: es-01
solr:
    install: '0'
    settings:
        version: 4.10.2
        port: '8984'

**Comment by gkobilansky** [comment]
Here are the first 2 links when I googled the errors in your output. 
https://github.com/rubygems/rubygems/issues/665
https://gist.github.com/luislavena/f064211759ee0f806c88

Please do research before blindly putting outputs in issues.

**Comment by sibusisocyril** [comment]
Sorry Gene , no one was blindly putting outputs without researching or troubling shooting ; i have seen both those googled items and nothing seemed to help maybe you should ask first if you have tried everything before blindly making assumptions that people have not done any work on this

**Comment by sibusisocyril** [comment]
In any case i will close the issue because wealthbot/ open source  seems not be something that works well at all .
