### ISSUE TITLE
Puppet locales module is not up-to-date

### ISSUE THREAD

**Issue by joska** [puphpet/puphpet#2486]
Note: this is my first day with Vagrant, so it is possible that the issue is on my side. 

I have configured my CentOS 7 vagrant box on http://puphpet.com. But the _vagrant up_ command return error in puphpet/puppet/modules/locales/manifests/params.pp "Unsupported platform: CentOS".

The locales plugin is locked on version 2.2.2, which is over one year old. CentOS support in this plugin has been added after last stable release. Is it possible to link to latest master commit instead?

https://github.com/saz/puppet-locales/

**Comment by joska** [comment]
According to documentation, following change at mod 'attachmentgenie/locales' should suffice, but I am unable to generate new lockfile:

```
-    :ref => 'v2.2.2'
+    :branch => 'master'
```

**Comment by jtreminio** [comment]
Fixed by https://github.com/puphpet/puppet-puphpet/commit/41673b8258517bdb920bcf992eefce99d2a3544a
