### ISSUE TITLE
MongoDB 3.2 support?

### ISSUE THREAD

**Issue by akeeman** [puphpet/puphpet#2490]
MongoDB 3.x is a nice upgrade compared to the older 2.x series, and [is compatible with all offered distros](https://docs.mongodb.com/manual/installation/). It would be nice if Puphpet could support MongoDB 3.2.

**Comment by rbairwell** [comment]
See also #2461 - MongoDb 3.2 is needed for Ubuntu 16.

**Comment by jtreminio** [comment]
Done!
