### ISSUE TITLE
Evaluation Error: Unsupported platform: CentOS

### ISSUE THREAD

**Issue by mike-source** [puphpet/puphpet#2493]
I've been getting the following issue with my vagrant machine. I had recently (today) synced with the latest version available at http://puphpet.com (re-uploaded my config.yaml and generated a new machine).

I started having this issue: https://github.com/puphpet/puphpet/issues/2408 so I applied this fix manually (by editing the files): https://github.com/puphpet/puppet-yum/pull/1

After applying that fix, I now get this error:

> Error: Evaluation Error: Error while evaluating a Function Call, Unsupported platform: CentOS at /tmp/vagrant-puppet/modules-b2efa14da7944f3e3cfefff95f649730/locales/manifests/params.pp:43:7 on node ******
> The SSH command responded with a non-zero exit status. Vagrant
> assumes that this means the command failed. The output for this command
> should be in the log above. Please read the output to determine what
> went wrong.

I've tried searching this repo for a similar error but can't seem to find anything, it prevents me from provisioning my machine.

**Comment by jtreminio** [comment]
This was fixed ~2 hours ago: https://github.com/puphpet/puppet-puphpet/commit/41673b8258517bdb920bcf992eefce99d2a3544a

You can regenerate your archive or apply the patch above.
