### ISSUE TITLE
Error When Attempting To Start a VM

### ISSUE THREAD

**Issue by HortonX25** [puphpet/puphpet#2497]
I'm new to Puphpet Vagrant and I decided to set up a VM with it.

The following happened

> Bringing machine 'machine1' up with 'virtualbox' provider...
> ==> machine1: Box 'puphpet/ubuntu1604-x64' could not be found. Attempting to find and install...
>     machine1: Box Provider: virtualbox
>     machine1: Box Version: >= 0
> ==> machine1: Loading metadata for box 'puphpet/ubuntu1604-x64'
>     machine1: URL: https://atlas.hashicorp.com/puphpet/ubuntu1604-x64
> ==> machine1: Adding box 'puphpet/ubuntu1604-x64' (v20161004) for provider: virtualbox
>     machine1: Downloading: https://atlas.hashicorp.com/puphpet/boxes/ubuntu1604-x64/versions/20161004/providers/virtualbox.box
> ==> machine1: Successfully added box 'puphpet/ubuntu1604-x64' (v20161004) for 'virtualbox'!
> ==> machine1: Importing base box 'puphpet/ubuntu1604-x64'...
> ==> machine1: Matching MAC address for NAT networking...
> ==> machine1: Checking if box 'puphpet/ubuntu1604-x64' is up to date...
> ==> machine1: Setting the name of the VM: Main_machine1_1477867076292_81997
> ==> machine1: Clearing any previously set network interfaces...
> ==> machine1: Preparing network interfaces based on configuration...
>     machine1: Adapter 1: nat
>     machine1: Adapter 2: hostonly
> ==> machine1: Forwarding ports...
>     machine1: 22 (guest) => 8835 (host) (adapter 1)
>     machine1: 22 (guest) => 2222 (host) (adapter 1)
> ==> machine1: Running 'pre-boot' VM customizations...
> ==> machine1: Booting VM...
> There was an error while executing `VBoxManage`, a CLI used by Vagrant
> for controlling VirtualBox. The command and stderr is shown below.
> 
> Command: ["startvm", "50932160-3c98-465b-bb4e-82345046d695", "--type", "headless"]
> 
> Stderr: VBoxManage: error: The virtual machine 'machine1.puphpet' has terminated unexpectedly during startup with exit code 1 (0x1)
> VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component MachineWrap, interface IMachine

Any fix for this bug?

**Comment by jtreminio** [comment]
This should be fixed with newest version of boxes uploaded today.
