### ISSUE TITLE
"Guest-specific operations were attempted on a machine..."

### ISSUE THREAD

**Issue by Saoirse1916** [puphpet/puphpet#2501]
I received the generic error "Guest-specific operations were attempted on a machine that is not
ready for guest communication. This should not happen and a bug
should be reported."

When I ran vagrant up --debug, I see an error indicating that vagrant can't find my database files, so I ran vagrant ssh, looked at /var/www/mysite.dev/public_html and lo and behold, those directories don't exist.  So for some reason the box is not mapping properly.  I'm running this on VMWare Fusion (Mac) and I tried both NFS and Default for folder type, same error each time.

Here's my most recent config.yaml which uses Default, turns off Adminer (though I still get warnings about that) and doesn't do any MySQL account granting, as I was getting errors there too.

http://pastebin.com/cdDMx8kL

**Comment by jtreminio** [comment]
This should be fixed with newest version of boxes uploaded today.
