### ISSUE TITLE
Error: Evaluation Error: Error while evaluating a Resource Statemen t, Evaluation Error: Error while evaluating a Resource Statement, Duplicate decl aration

### ISSUE THREAD

**Issue by chenzi2015** [puphpet/puphpet#2506]
vagrant up error:

==> PhpDev1: Running provisioner: shell...
    PhpDev1: Running: inline script
==> PhpDev1: Running provisioner: shell...
    PhpDev1: Running: C:/Users/ADMINI~1/AppData/Local/Temp/vagrant-shell20161107
-2520-128m3bn.sh
==> PhpDev1:
==> PhpDev1:  ____        ____  _   _ ____      _      generated using
==> PhpDev1: |  _ \ _   _|  _ \| | | |  _ \ ___| |_   ___ ___  _ __ ___
==> PhpDev1: | |_) | | | | |_) | |_| | |_) / _ \ __| / __/ _ \| '_ ` _ \
==> PhpDev1: |  __/| |_| |  __/|  _  |  __/  __/ |_ | (_| (_) | | | | | |
==> PhpDev1: |_|    \__,_|_|   |_| |_|_|   \___|\__(_)___\___/|_| |_| |_|
==> PhpDev1:
==> PhpDev1: Running provisioner: shell...
    PhpDev1: Running: C:/Users/ADMINI~1/AppData/Local/Temp/vagrant-shell20161107
-2520-xyhkr2.sh
==> PhpDev1: Pre-existing private key found at 'puphpet/files/dot/ssh/root_id_rs
a'
==> PhpDev1: Pre-existing private key found at 'puphpet/files/dot/ssh/id_rsa'
==> PhpDev1: Adding generated root key to /root/.ssh/id_rsa
==> PhpDev1: Adding generated root key to /root/.ssh/id_rsa.pub
==> PhpDev1: Adding generated root key to /root/.ssh/authorized_keys
==> PhpDev1: Adding generated key to /home/vagrant/.ssh/id_rsa
==> PhpDev1: Adding generated key to /home/vagrant/.ssh/id_rsa.pub
==> PhpDev1: Adding generated key to /home/vagrant/.ssh/authorized_keys
==> PhpDev1: Running provisioner: shell...
    PhpDev1: Running: C:/Users/ADMINI~1/AppData/Local/Temp/vagrant-shell20161107
-2520-uxs859.sh
==> PhpDev1: Running provisioner: shell...
    PhpDev1: Running: C:/Users/ADMINI~1/AppData/Local/Temp/vagrant-shell20161107
-2520-1yyk9b0.sh
==> PhpDev1: Running files in files/exec-preprovision
==> PhpDev1: Finished running files in files/exec-preprovision
==> PhpDev1: To run again, delete hashes you want rerun in /.puphpet-stuff/exec-
preprovision-ran or the whole file to rerun all
==> PhpDev1: Running provisioner: puppet...
==> PhpDev1: Running Puppet with ...
==> PhpDev1: Info: Loading facts
==> PhpDev1: Info: Loading facts
==> PhpDev1: Info: Loading facts
==> PhpDev1: Info: Loading facts
==> PhpDev1: Info: Loading facts
==> PhpDev1: Info: Loading facts
==> PhpDev1: Info: Loading facts
==> PhpDev1: Info: Loading facts
==> PhpDev1: Info: Loading facts
==> PhpDev1: Info: Loading facts
==> PhpDev1: Info: Loading facts
==> PhpDev1: Info: Loading facts
==> PhpDev1: Info: Loading facts
==> PhpDev1: Info: Loading facts
==> PhpDev1: Info: Loading facts
==> PhpDev1: Info: Loading facts
==> PhpDev1: Info: Loading facts
==> PhpDev1: Info: Loading facts
==> PhpDev1: Info: Loading facts
==> PhpDev1: Info: Loading facts
==> PhpDev1: Warning: Unknown variable: '::lsbmajdistrelease'. at /tmp/vagrant-p
uppet/modules-a64ac86060e6b77057bf52d41a99c9c1/nginx/manifests/package/redhat.pp
:34:12
==> PhpDev1: Warning: The key 'shib2' is declared more than once at /tmp/vagrant
-puppet/modules-a64ac86060e6b77057bf52d41a99c9c1/apache/manifests/params.pp:251:
21
==> PhpDev1: Error: Evaluation Error: Error while evaluating a Resource Statemen
t, Evaluation Error: Error while evaluating a Resource Statement, Duplicate decl
aration: Puphpet::Php::Ini[pecl] is already declared in file /tmp/vagrant-puppet
/modules-a64ac86060e6b77057bf52d41a99c9c1/puphpet/manifests/php/module/pecl.pp:1
9; cannot redeclare at /tmp/vagrant-puppet/modules-a64ac86060e6b77057bf52d41a99c
9c1/puphpet/manifests/php/module/pecl.pp:19 at /tmp/vagrant-puppet/modules-a64ac
86060e6b77057bf52d41a99c9c1/puphpet/manifests/php/module/pecl.pp:19:7  at /tmp/v
agrant-puppet/modules-a64ac86060e6b77057bf52d41a99c9c1/puphpet/manifests/php/mod
ules.pp:57 on node phpdev1.6lapp
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

**Comment by andreasupftw** [comment]
Please paste the output in back-ticks or click the <> button above the editing area.
`Like this...`  
It's very hard to read console output with non-fixed-width fonts. I'd like to help, if I can.
