### ISSUE TITLE
 Could not e valuate: invalid byte sequence in UTF-8

### ISSUE THREAD

**Issue by chenzi2015** [puphpet/puphpet#2507]
I am installed redis , but run "vagrant provision" get this error:

==> PhpDev: Notice: /Stage[main]/Puphpet::Beanstalkd::Install/Beanstalkd::Config
[beanstalkd]/Service[beanstalkd]/ensure: ensure changed 'stopped' to 'running'
==> PhpDev: Info: /Stage[main]/Puphpet::Beanstalkd::Install/Beanstalkd::Config[b
eanstalkd]/Service[beanstalkd]: Unscheduling refresh on Service[beanstalkd]
==> PhpDev: Error: /Stage[main]/Puphpet::Php::Modules/Puphpet::Php::Module::Pecl
[redis-2.2.8]/Php::Pecl::Module[redis-2.2.8]/Exec[pecl-redis-2.2.8]: Could not e
valuate: invalid byte sequence in UTF-8
==> PhpDev: Notice: /Stage[main]/Puphpet::Php::Install/Service[php-fpm]: Depende
ncy Exec[pecl-redis-2.2.8] has failures: true
==> PhpDev: Warning: /Stage[main]/Puphpet::Php::Install/Service[php-fpm]: Skippi
ng because of failed dependencies
==> PhpDev: Info: Stage[main]: Unscheduling all events on Stage[main]
==> PhpDev: Notice: Applied catalog in 330.86 seconds
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

please help me!!!

**Comment by oussaka** [comment]
The same problem : 
`
 Error: /Stage[main]/Puphpet::Php::Modules/Puphpet::Php::Module::Pecl[redis]/Php::Pecl::Module[redis]/Exec[pecl-redis]: Could not evaluate: invalid byte sequence in UTF-8`

**Comment by SeviSte** [comment]
@oussaka Updating puphpet folder & Vagrantfile fixed this for me.

**Comment by oussaka** [comment]
It works now, @SeviSte 👍

**Comment by jtreminio** [comment]
`php-redis` system package now installed instead of pecl redis package.
