### ISSUE TITLE
Public network support

### ISSUE THREAD

**Issue by Hlsgs** [puphpet/puphpet#2518]
Hello @jtreminio!
First of all thank you for this awesome tool. I'm just getting into Vagrant and this has made things so much easier and more convenint.
Second this in not an issue, but a feature request, but i don't know how to mark it as such.

It would be extremly helpful for me if you added the possibility of setting a public network aside from the local one defined in the Machines section. It should be fairly straight forward, since all i had to do to get this working was to add the following to config.yaml:
```
                            private_network: 192.168.56.101
                            public_network: x.x.x.x
```
The machine joins a public network with IP x.x.x.x and everythign works like a charm(the host only network is still useful for ssh and NFS, which, btw., does work on Windows and I find to be the fastest).
I need this because i prefer to skip virtual hosts entirely in favour of accessing the sites through a local IP. This is convenient since i do almost exclusively Wordpress and in this way i can test with various mobile devices on my local network without having to edit their respective hosts files.

Obviously I'm goind to keep exporting from your site and modifying the yaml, but not having to do this every time woudl be very very helpful.

Thank you again!

**Comment by jtreminio** [comment]
I purposely left this out from the GUI because I don't want to complicate it more than it is.

The way you're doing it is the way I recommend.
