### ISSUE TITLE
 MariaDB won't install and start on CentOS 7 x64 

### ISSUE THREAD

**Issue by jpilchisu** [puphpet/puphpet#2521]
Post-reboot, mariadb will not restart on CentOS 7 x64. Vagrant halt followed by vagrant up seems to somehow delete the /var/run/mariadb folder  This seems to be tied to #2458 (@edhardie described the /var/run/mariadb issue right before the commit that closed the log problem was made).  I'm currently using vagrant 1.8.7 with a stock puphpet.com build (with the exception of apache rather than nginx) that works for initial build, but fails on reboot.

**Comment by OsakaWebbie** [comment]
I had this problem, too (build with nginx, running on Vagrant 1.8.6) - I gave up and used MySQL for now. If a fix comes along, I'll gladly switch to MariaDB.

**Comment by oddz** [comment]
I'm having the same issue on the most recent cent-os 7 box with maria db 5.5 I noticed though you can work around around this issue by provisioning the box once it has been started.
