### ISSUE TITLE
CentOS 7 - private_network not getting IP.

### ISSUE THREAD

**Issue by Artistan** [puphpet/puphpet#2533]
Posted all the files and output here...
https://gist.github.com/Artistan/7e268292f76696e80e6ec63fef6adaad

Basically, new box does not load private network IP address. this is the case for multiple boxes that I have tried.

**Comment by Artistan** [comment]
removed a couple vagrant plugins (bindfs and vbguest) and still have the same issue.

**Comment by Artistan** [comment]
not sure what else i should try. this is a "bare" centos 7 box with php 7 .  nothing special configs or anything!?

**Comment by Artistan** [comment]
tried again with JUST centos7 , no php or anything else installed.

https://gist.github.com/Artistan/c31bbc92f83263b1bcfbf2120833670a

**Comment by Artistan** [comment]
tried again with centos 6.5 and it failed even worse...
https://gist.github.com/Artistan/25d711173702c50b9164e7ac05df139b

**Comment by Artistan** [comment]
centos 6.5 gets the ip but had a ton of other errors.
https://gist.github.com/Artistan/25d711173702c50b9164e7ac05df139b

**Comment by Artistan** [comment]
is working for ubuntu16.04

must be an issue within centos 7

**Comment by Artistan** [comment]
tried installing older VirtualBox 5.1.8, still no IP in CentOS 7

**Comment by Artistan** [comment]
installed older Vagrant 1.8.7, now it works.

**Comment by jeromebriones** [comment]
Pulling my hair for a day because of this issue. I'm gonna try downgrading my vagrant now to see if that fixes it.

**Comment by Torpedr** [comment]
Upgrade to the latest vagrant 1.9.1 kind of helps. At least the guest machine is now in the correct subnet.

**Comment by Artistan** [comment]
again, i had to downgrade Vagrant to 1.8.7 to get it to work again.
1.9.1 did not work for me.

**Comment by geerlingguy** [comment]
1.9.0 should also work, FWIW :)

**Comment by Michal-sk** [comment]
Nope, im working with Vagrant 1.9.1 and cant get it to work

**Comment by jtreminio** [comment]
![image](https://cloud.githubusercontent.com/assets/589398/22563824/ca291d6c-e947-11e6-8d5a-b4e1160b90bd.png)

Downgrade VirtualBox

**Comment by geerlingguy** [comment]
@jtreminio - Just as a general question, as VirtualBox 5.1.x has been out for quite a while (6+ months IIRC), is the plan to update the requirement soon? Other VMs I use often require 5.1.x or later, and so having to juggle different VirtualBox versions might be a deal-breaker.

**Comment by jtreminio** [comment]
Something in virtualbox 5.1.x absolutely breaks centos boxes. I wasted 2 days, a solid 15 hours total, trying to figure out why this was.

The error was similar to this: https://gist.github.com/Artistan/25d711173702c50b9164e7ac05df139b

Basically any repomd.xml has a chance of not downloading fully, very similar to this issue: http://superuser.com/questions/1144782/yum-update-connection-reset-on-centos-virtualbox-vm

5.0.28 has _very_ slow NFS support and is almost unusable. 5.0.26 is the last stable virtualbox version I could find.

**Comment by geerlingguy** [comment]
@jtreminio - I haven't had any issues on Vagrant 1.8.6 or 1.9.0 with CentOS 6 or 7 (at least not with my boxes @ https://atlas.hashicorp.com/boxes/search?utf8=✓&sort=&provider=&q=geerlingguy or with Bento). I _do_ know that both Vagrant 1.8.7 and 1.9.1 were absolutely riddled with weird issues with RHEL... it seems few within Hashicorp use RHEL-derivatives (that's my guess, judging how the Ubuntu/Debian-flavored boxes are often more stable).

**Comment by davidkslack** [comment]
To get this working manually add the IP after vagrant up .
`vagrant ssh` as normal
`sudo ifconfig enp0s8 BOX_IP netmask 255.255.255.0`
