### ISSUE TITLE
Apache not installed (provisioning problem?)

### ISSUE THREAD

**Issue by Torpedr** [puphpet/puphpet#2534]
I encountered a couple of problems using PuPHPet with almost default config.

1. Ubuntu 16.04 machine with Apache does not have apache installed:

My config file: https://codepaste.net/vppkxx

Errors:
```
$ vagrant provision
==> machine1: Running provisioner: shell...
    machine1: Running: inline script
==> machine1: sed: can't read /vagrant/puphpet/shell/*.sh: No such file or directory
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

2. Selected IP is different than the guest machine:
`private_network: 192.168.56.101`

```
$ ifconfig  
enp0s3    Link encap:Ethernet  HWaddr 08:00:27:54:8b:1b  
          inet addr:10.0.2.15  Bcast:10.0.2.255  Mask:255.255.255.0
```

3. MySQL is not installed:
`$ dpkg --get-selections | grep mysql`

**Comment by Artistan** [comment]
i also posted about not getting the right IP
https://github.com/puphpet/puphpet/issues/2533

**Comment by jtreminio** [comment]
Please regenerate your puphpet config.
