### ISSUE TITLE
config.yaml not changed after provision

### ISSUE THREAD

**Issue by malutanpetronel** [puphpet/puphpet#2536]
Hi

  I did provisioned with success an ec2 instance, but I did wanted more, I am trying to customise it by adding for example a new module csf which I added both in modules and manifests folder. I did appended at the end of config.yaml:
...
docsf:
    install: '1'
    rules: {  }
...

  Now tried to customise the site.pp file as I successfully did a while ago.. an year or so with:

$yaml = merge_yaml(
  '/vagrant/puphpet/config.yaml',
  "/vagrant/puphpet/config-${::provisioner_type}.yaml",
  '/vagrant/puphpet/config-custom.yaml'
)

$docsf = $yaml['docsf']

Exec { path => [ '/bin/', '/sbin/', '/usr/bin/', '/usr/sbin/' ] }

include ::puphpet::params

if array_true($docsf, 'install') {
  class { '::puphpet_docsf':
    docsf => $docsf
  }
}

class { '::puphpet':
  extra_config_files => [
    # Define extra config files
  ]
}

Not sure if site.pp is ok, but after I run vagrant provision I looked after ssh in the machine inside /vagrant/puphpet folder in the config.yaml and this file is unchanged... site.pp file the same

What I am doing wrong please ?

**Comment by jtreminio** [comment]
Upgrade your puphpet archive.

Other than that, this may be a vagrant-aws issue, not a puphpet one.
