### ISSUE TITLE
php-fpm dead but subsys locked

### ISSUE THREAD

**Issue by rox84** [puphpet/puphpet#2540]
Upon initial vagrant up, everything was working fine. But after a few days, php-fpm started having problems:
`# service php-fpm status`
`php-fpm dead but subsys locked`

Restarting does not work, because I cannot properly stop php-fpm:
`# service php-fpm restart`
`Stopping php-fpm:                                          [FAILED]`
`Starting php-fpm: [27-Dec-2016 19:20:30] ERROR: unable to bind listening socket for address` `'127.0.0.1:9000': Address already in use (98)`
`[27-Dec-2016 19:20:30] ERROR: FPM initialization failed
                                                           [FAILED]`

I checked the php processes and for locked ones, but found no discrepancies:
`# ps aux | grep php`
`84:root     16843  0.0  0.4 304204  4944 ?        Ss   18:58   0:00 php-fpm: master process (/etc/php-fpm.conf)`
`85:www-user 16844  0.0  0.4 304204  4540 ?        S    18:58   0:00 php-fpm: pool www   `         
`86:www-user 16845  0.0  0.4 304204  4540 ?        S    18:58   0:00 php-fpm: pool www       `     
`87:www-user 16846  0.0  0.4 304204  4540 ?        S    18:58   0:00 php-fpm: pool www         `   
`88:www-user 16847  0.0  0.4 304204  4544 ?        S    18:58   0:00 php-fpm: pool www           ` 
`89:www-user 16848  0.0  0.4 304204  4544 ?        S    18:58   0:00 php-fpm: pool www            `
`103:root     28127  0.0  0.0 103316   996 pts/0    S+   19:21   0:00 grep --color=auto -in php`

`vim /var/run/php-fpm.pid`
Contents of this file, php-fpm.pid, are one line:
 `16843`

`vim /var/lock/subsys/php-fpm`
php-fpm file is empty.

I checked port 9000:
`netstat -tulpn`
`Proto Recv-Q Send-Q Local Address               Foreign Address             State       PID/Program name`
`...`   
`tcp        0      0 127.0.0.1:9000              0.0.0.0:*                   LISTEN      16843/php-fpm `  
`...`    
   
Other things I've tried, but did not resolve the issue either:

Killing all processes and then trying to restart php-fpm, then trying to reload the machine, with the following commands
`# killall -9 php`
`# service php-fpm restart`
`$ vagrant reload --provision`

Deleting the lock file, trying to restart php-fpm, then trying to reload the machine, with the following commands
`# rm /var/lock/subsys/php-fpm`
`# service php-fpm restart`
`$ vagrant reload --provision`

Removing the guest machine, restarting my host, and re-importing the guest machine with no other applications running on my host, with the following commands
`$ vagrant destroy`
(restarting host)
`$ vagrant up`
 
I can't figure out how to get php-fpm working again. config.yaml file is attached.

Thanks!

[config.yaml.txt](https://github.com/puphpet/puphpet/files/675002/config.yaml.txt)

**Comment by jtreminio** [comment]
Sorry, this does not seem to be a puphpet issue.

Please regenerate your archive from puphpet.com to start fresh.
