### ISSUE TITLE
Issues with url rewriting in Apache 

### ISSUE THREAD

**Issue by pf1gura** [puphpet/puphpet#2541]
Hi. It seems to me that rewrite module is enabled by default by PuPHPet but it doesn't work. Did someone have similar problem? I enabled it when configuring new server and double checked if config is okay (directly in the system) and it looks okay (based on my experience and StackOverflow). Any additional steps that shoud have been taken to enable url rewriting?

[config.yaml on pastebin](http://pastebin.com/nQujkTSv)

**Comment by jtreminio** [comment]
Please regenerate your archive. Some Apache fixes were pushed today.
