### ISSUE TITLE
start-always scripts stop execution after the first script

### ISSUE THREAD

**Issue by JeFang** [puphpet/puphpet#2550]
I have multiple scripts in my startup-always and startup-once folders.
But for all of them on "vagrant up" only the first of each folder is executed and tells all scripts executed.
For the startup-once scripts just one entry is done in the startup-once-ran file. 
If I vagrant up again, the next file line will be attached to the startup-once-ran file. So it's nothing about an error in the files itself.
In some of them i get mysql warnings for including passwords, but just a warning. can this stop the execution?
any ideas on this issue?

**Comment by jtreminio** [comment]
If any of your scripts exit with anything other than `0` it'll be considered an error and further scripts will not be executed.

It might help to manually exit with `0`
