### ISSUE TITLE
Sabayon Entropy Support. + Gentoo support. 

### ISSUE THREAD

**Issue by necrose99** [puphpet/puphpet#2552]
https://forge.puppet.com/optiz0r/sabayon automates Entropy equo client much like yum for gentoo binaries from Sabayon  and or mirrors. 

https://forge.puppet.com/gentoo/portage ( Sabayon has most packages pre-built , else compile from src's from Gentoo's tools as Sabayon Linux is pre-conf.. Gentoo with binary repo) 

https://forge.puppet.com/Flameeyes/gentoo

https://forge.puppet.com/modules?utf-8=%E2%9C%93&sort=rank&q=gentoo

**Comment by jtreminio** [comment]
Sorry, I'm not interested in adding support for more than Ubuntu and CentOS.

Creating the base boxes and ensuring all existing packages work on any new distros would take far too much time initially, and for maintenance.

**Comment by necrose99** [comment]
I'm willing to provide some aid, just ruby i haven't a clue. 

most of the packages , i can cross map.   or provide a mapper file . 
debian deps or centos also familiar with. 

Sabayon , has a generic base box , as dose gentoo , vagrants etc...  & packer 
or Generic ROOTFS tarballs. 
most are aleady done , it would just be a plus , to automate , all the rest of the other druge work... 

mainly for Sec Testing , it would be nice to have boxes ready , based on profiles , feed my local server a box to build , ie User package lists , and poof ... 
just the drudge work of building boxes in virtual box , then wanting a few 100 dozen packages , gets old. or for webapps sec testing , likewise... 

Gentoo thankfully builds python pip or rubygems locally , to match ebuild specs. 

Sabayon , much is already pre-configured (Gentoo) . , equo pulls a binary fakes Gentoo portage to finesse it through. , however if Sabayon has it not ,  emerge package name. so best of both. 

Granted make.conf and other build flags , are not as present with gentoo . however much of that can be scripted around...  or Generically set. some packages openssl sasl have circular depends. 
--oneshot both , then likewise remake with USE="sasl ssl"  emerge openssl sasl
however Gentoo is tree based so best to use the tree , ie emerge sys-devel/gcc   unless the package is common. 

I have a lot of security configs/packes to build  to test , I make the perfect victim...
