### ISSUE TITLE
Vagrant share no longer works

### ISSUE THREAD

**Issue by edhardie** [puphpet/puphpet#2559]
Hello, I'm running a Centos7 box on Win10 with Virtualbox 5.0.26 and vagrant 1.8.6 and recently my ability to share my machine with vagrant share has gone. My team members with similar set ups are also seeing this issue. 

The output from `vagrant share --http 80 --https 443` (the flags are required else it errors saying it failed to detect the ports) is as follows:

```
vagrant share --http 80 --https 443
==> 70centos7: Detecting network information for machine...
    70centos7: Local machine address: 127.0.0.1
    70centos7:
    70centos7: Note: With the local address (127.0.0.1), Vagrant Share can only
    70centos7: share any ports you have forwarded. Assign an IP or address to your
    70centos7: machine to expose all TCP ports. Consult the documentation
    70centos7: for your provider ('virtualbox') for more information.
    70centos7:
    70centos7: Local HTTP port: 80
    70centos7: Local HTTPS port: 443
    70centos7: Port: 2222
    70centos7: Port: 7460
==> 70centos7: Checking authentication and authorization...
==> 70centos7: Creating Vagrant Share session...
    70centos7: Share will be at: cheerful-bison-1517
==> 70centos7: Your Vagrant Share is running! Name: cheerful-bison-1517
==> 70centos7: URL: http://cheerful-bison-1517.vagrantshare.com
==> 70centos7:
==> 70centos7: You're sharing your Vagrant machine in "restricted" mode. This
==> 70centos7: means that only the ports listed above will be accessible by
==> 70centos7: other users (either via the web URL or using `vagrant connect`).
```

When it worked before the message about exposing all TCP ports wasn't shown and most importantly I think the local machine ip is wrong (I have 192.168.10.10 configured in my config.yaml)

Is any one able to shed any light on this? Much appriciated.

**Comment by jtreminio** [comment]
Puphpet isn't the place for vagrant share support.

You didn't show me your config.yaml but I'm going to assume that you don't have a vhost listening on `*` (a catch-all). I'd suggest creating a new vhost listening on some random port and `*` address and passing that to vagrant share.

**Comment by edhardie** [comment]
Hey Juan,

Thanks for you help - I appriciate this isn't the place for vagrant share support but I think this is a box networking related issue rather than an issue with my own set up. I'm able to run vagrant share fine on other boxes and it worked before the most recent update to the Centos7 base box. 

I have catch all vhosts set up and I've tried your suggestion of a random port with no luck:

```
<VirtualHost *:6968>
  ServerName gigantic-mandrill-8733.vagrantshare.com
  DocumentRoot "/var/www/testvshare"
  <Directory "/var/www/testvshare">
    Options Indexes FollowSymlinks MultiViews
    AllowOverride All
    Allow from All
    Require all granted
    <FilesMatch "\.php$">
      Require all granted
      SetHandler proxy:fcgi://127.0.0.1:9000
    </FilesMatch>
  </Directory>
  ErrorLog "/var/log/httpd/testvshare_error.log"
  ServerSignature Off
  CustomLog "/var/log/httpd/testvshare_access.log" combined
</VirtualHost>
```

Is anyone else seeing this same behavoiur?

**Comment by jtreminio** [comment]
Set `ServerName` to `*` is what I mean, so any traffic hitting port `6968` will be caught by this vhost.

**Comment by edhardie** [comment]
`ServerName *` is invalid syntax, you can do `ServerAlias *` and have no `ServerName` but it's still the same problem, the above config that specifies the full vagrant share url works on other boxes and used to work on this box before the latest update. 

I'm not trying to bust your balls on this, I fully appreciate everything you've done for this problem, but I'm sure it's not a problem that's down to my set up and I just want to get some discussion going to see if anyone else has an idea about what's going on.
