### ISSUE TITLE
General deployment question

### ISSUE THREAD

**Issue by pedrodevoto** [puphpet/puphpet#2566]
I'm developing a project with local target (actually, I'm using [Magestead](https://www.magestead.com/), which is built with PuPHPet, to develop a Magento app) and I want to deploy it, with the exact same local configuration, to DigitalOcean. As far as I've seen, it is not possible to add multiple targets to PuPHPet, and do `vagrant up [target]`. 

What do you think would be the appropriate way to do it? Should I `git pull` the entire project to the server? If so, how could I run the same _provison_ on the server, to have it configured the same way as my local VM? Is there another way using Vagrant?

**Comment by jtreminio** [comment]
Multiple targets (local/digitalocean/aws) are not supported - too much work.

However, you can adapt my answer here: http://stackoverflow.com/questions/37724663/multiple-vagrant-vms-via-puphpet-with-different-configs/37949586#37949586

Just define different `vagrantfile.vm.provider` blocks in separate config files.

Good luck.
