### ISSUE TITLE
Puppet 4.9.0 issues - heira.yaml deprecated

### ISSUE THREAD

**Issue by wcervin** [puphpet/puphpet#2567]
For the first time, I'm seeing warnings when launching -- and a number of issues as a result:

==> : Warning: The function 'hiera_hash' is deprecated in favor of using 'lookup'. See https://docs.puppet.com/puppet/4.9.0/reference/deprecated_language.html
==> :    (file & line not available)
==> : Warning: /vagrant/puphpet/puppet/hiera.yaml: Use of 'hiera.yaml' version 3 is deprecated. It should be converted to version 5
==> :    (in /vagrant/puphpet/puppet/hiera.yaml)
==> : Warning: The function 'hiera' is deprecated in favor of using 'lookup'. See https://docs.puppet.com/puppet/4.9.0/reference/deprecated_language.html
==> :    (file & line not available)
==> : Warning: Unknown variable: '::lsbmajdistrelease'. at /tmp/vagrant-puppet/modules-4ea36a7830864dd390cb5b4ec31bc7da/nginx/manifests/package/redhat.pp:34:12

I see there is a known issue on Puppet's site (https://tickets.puppetlabs.com/browse/PUP-7170).  Can someone confirm this is the related issue?  Is anyone else experiencing this?

One symptom is that my VMs do not receive their custom IP addresses defined in config.yaml.

Is there a workaround for PuPHPet in the meantime?

**Comment by wcervin** [comment]
Another symptom is improper syncing of folders.

**Comment by jtreminio** [comment]
How did you get Puppet 4.9.x? I've specifically stayed on 4.6.x

**Comment by wcervin** [comment]
Honestly, I don't know.  I didn't change any puphpet files or scripts.  I'm running a minimal install CentOS base box via Parallels.  I did update the Parallel Tools for Linux, but that shouldn't have anything to do with the Puppet version.

**Comment by jtreminio** [comment]
This handles the Puppet installation: https://github.com/puphpet/puphpet/blob/master/archive/puphpet/shell/install-puppet.sh#L20

I can't help with anything else if it's not on an official puphpet box.
