### ISSUE TITLE
Cakephp assets

### ISSUE THREAD

**Issue by delamux** [puphpet/puphpet#2579]
Hello I have installed one machine with and I can´t change the url's and the css and js not load too.

this is the config:

https://gist.github.com/delamux/2fc87f02a592cd8ce81468e1721e4899

The web adminlte in nginx is the problem.

Thank you

**Comment by jtreminio** [comment]
Please regenerate your config, fixed by e676f36e41c27e2d26e491eda0c4ef62bfa5521a
