### ISSUE TITLE
suitable provider for rvm_system_ruby and rvm_gem

### ISSUE THREAD

**Issue by enky00** [puphpet/puphpet#2580]
Hi, 

yesterday everything works perfectly. now i wanna start (vagrant up) and i got this.

´´==> machine: Error: Could not find a suitable provider for rvm_system_ruby
==> machine: Error: Could not find a suitable provider for rvm_gem
==> machine: Info: Creating state file /opt/puppetlabs/puppet/cache/state/state.yaml
==> machine: Notice: Applied catalog in 455.53 seconds
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.``

I just turned my PC off, no Windows (Win10) Updates.

**Comment by kkarkus** [comment]
@enky00 
any news?

**Comment by Winandvdb** [comment]
Did you find a fix for this?

**Comment by bke-daniel** [comment]
+1

**Comment by juanlarra1** [comment]
+1

**Comment by jtreminio** [comment]
No longer an issue!
