### ISSUE TITLE
enabling ssl breaks css

### ISSUE THREAD

**Issue by diesonne** [puphpet/puphpet#2592]
when enabling ssl on apache the styling of the vhost becomes unusable
![image](https://cloud.githubusercontent.com/assets/2689543/23399974/975c37ba-fda2-11e6-96a1-dca408789fa8.png)

screenshot is from chrome, on ff the weird stuff on the right is just hidden

**Comment by Hlsgs** [comment]
I can confirm this. Happens in FF and Chrome.

**Comment by jtreminio** [comment]
Fixed by a complete redesign :)
