### ISSUE TITLE
SEVERE:  Bone-stock puphpet VM will not load a simple index.html file.

### ISSUE THREAD

**Issue by unrivaledcreations** [puphpet/puphpet#2598]
Attempting to access awesome.dev:

> 2017/03/03 02:10:24 [error] 4182#4182: *3 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 192.168.56.1, server: awesome.dev, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "awesome.dev"
2017/03/03 02:10:24 [error] 4182#4182: *3 rewrite or internal redirection cycle while internally redirecting to "/app.php", client: 192.168.56.1, server: awesome.dev, request: "GET /favicon.ico HTTP/1.1", host: "awesome.dev", referrer: "http://awesome.dev/"

Attempting to access awesome.dev/index.html:

> 2017/03/03 02:12:45 [error] 4182#4182: *5 FastCGI sent in stderr: "Access to the script '/var/www/awesome/web/index.html' has been denied (see security.limit_extensions)" while reading response header from upstream, client: 192.168.56.1, server: awesome.dev, request: "GET /index.html HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "awesome.dev"
2017/03/03 02:12:45 [error] 4182#4182: *5 rewrite or internal redirection cycle while internally redirecting to "/app.php", client: 192.168.56.1, server: awesome.dev, request: "GET /favicon.ico HTTP/1.1", host: "awesome.dev", referrer: "http://awesome.dev/index.html"

config.yaml file:  See the [config.yaml gist](https://gist.github.com/unrivaledcreations/765a4ee55cecc9e33a643c6d45698ba5).

**Comment by unrivaledcreations** [comment]
This appears to be a nasty byproduct of a badly misconfigured nginx server, which could be fixed "by hand," but that certainly defeats the purpose of using puphpet for development!

**Comment by Ardakilic** [comment]
You try to run assets over FastCGI. I add two location rewrites for each virtual host to prevent this, one matching the / location, which tries files and sends them to index.php$is_args$args, other matches  \ .php$ , and which sends it FastCGI. You can do it from the puphpet ui from "add a location rewrite".

**Comment by unrivaledcreations** [comment]
Thank-you, @Ardakilic.  I worked around the issue in a similar fashion:  I grabbed the configuration lines from an older puphpet `config.yaml` file, which worked:  See the [config-locations-sample.yaml gist](https://gist.github.com/unrivaledcreations/1259888f881c1460a82ebb67f7910773).

My hope is that the project's source files give us "baked in" serviceability as it was in the past so that modifying obscure settings in the web interface won't be necessary.  If you forget to add the `/ location`, it could cost you quite a bit of time (since you have to provision a box and test it, only to discover that you have to go right back to puphpet and start all over).

**Comment by jtreminio** [comment]
This has been fixed in e676f36e41c27e2d26e491eda0c4ef62bfa5521a
