### ISSUE TITLE
Design issue

### ISSUE THREAD

**Issue by redayoub** [puphpet/puphpet#2600]
I don't know if it's the right place for this, but when I check enable ssl in the apache page, I get this on chrome and safari
<img width="884" alt="capture d ecran 2017-03-06 a 23 11 43" src="https://cloud.githubusercontent.com/assets/5278152/23634558/b96f4c64-02c2-11e7-9255-9c0e02a8d464.png">

**Comment by jtreminio** [comment]
Fixed by a complete redesign :)
