### ISSUE TITLE
Fatal error: Call to undefined function mb_convert_encoding()....

### ISSUE THREAD

**Issue by unrivaledcreations** [puphpet/puphpet#2602]
Many PHP projects (like phpMyAdmin) use the PHP mb_convert_encoding() function, which, in a puphpet PHP 7.1 box (with nginx; apache is probably the same), throws a fatal error.

Workaround:  Log into the guest OS:
`$ vagrant ssh`

...and install the missing package:
`$ sudo apt-get install php7.1-mbstring`

This package should be installed by default with PHP.

**Comment by Ruudt** [comment]
You can add it to the list of "PHP Modules" in the PHP-section on puphpet.com. This wil install mbstring automatically upon provisioning.
