### ISSUE TITLE
500 Internal Server Error when creating the archive

### ISSUE THREAD

**Issue by Zykhatslover** [puphpet/puphpet#2605]
Hi everyone! 

First of all : nice job, the puPHPet UI is really nice now :).

Sadly I can't generate a new archive anymore, it keeps returning an internal server error every time I push the "download" button :x .

Has anyone else suffered from the same problem?

**Comment by jackwilsontotemic** [comment]
Yes, having same issue here too.

**Comment by Zykhatslover** [comment]
It looks like it's only happening when I'm trying to import my own config first.  It works if I re-create it from scratch but I don't really wanna do that :p

**Comment by jtreminio** [comment]
Sorry all, the deploy target was a checkbox vs radio. Should be ok now.

**Comment by Zykhatslover** [comment]
Glad you found a bug ! :p 

I'm still unable to download the file tho.. Still getting an error 500.
