### ISSUE TITLE
box_url false error

### ISSUE THREAD

**Issue by chrisprog** [puphpet/puphpet#2613]
Hi,
My first problem was generating vm on line:
box_url:'false'

[config.yaml.txt](https://github.com/puphpet/puphpet/files/847785/config.yaml.txt)

**Comment by markaduffy** [comment]
I'm seeing the same thing.


[config.yaml.txt](https://github.com/puphpet/puphpet/files/848734/config.yaml.txt)

**Comment by PragmatiqueConsulting** [comment]
Until this is fixed properly, you can do the following: 

- Open up puphpet/config.yaml
- Copy your box property (e.g. puphpet/ubuntu1604-x64)
- Head to https://atlas.hashicorp.com/boxes/search
- Paste your box name into the search, and click on the result that appears (should only be one)
- Copy the URL
- Paste the URL into your config.yaml file's box_url property (should be under box, and should be false)
- Save and rerun vagrant up

Not ideal, but works fine for me.
