### ISSUE TITLE
PHP diss. Really?

### ISSUE THREAD

**Issue by elb98rm** [puphpet/puphpet#2619]
`PHP is a toy language accidentally chosen to power some of the largest websites in the world. You probably want Ruby?`

Really? Haven't you got anything better to do? 
Having a go at PHP is the "immature coder's" equivalent of Godwin's law; it's like spelling Microsoft with a dollar sign.

Bug/change: This should be changed to something less condescending.

**Comment by OsakaWebbie** [comment]
It's clearly a joke, since the whole point of the tool is for PHP developers and has PHP in the name. Relax and laugh a little.

**Comment by jtreminio** [comment]
It's a joke! The frontend is written in SF2 :)
