### ISSUE TITLE
Could not add additional folder in "Shared Folders"

### ISSUE THREAD

**Issue by pjcvijay** [puphpet/puphpet#2623]
Hello!

Today I have been trying to add additional folder under "Shared Folders" in Deploy Target, but I could not. It's throwing JS error. I am using Firefox 45 and  in Ubuntu 14.04.

![screenshot from 2017-03-23 15 02 45](https://cloud.githubusercontent.com/assets/5560749/24241296/5af91906-0fda-11e7-92a6-039a96bb95a2.png)

Thanks,
Vijay

**Comment by quoidautre** [comment]
Hi,

Are you using some FF addons ?; like Ghostery, uBlockOrigin or uMatrix ?
Sometimes, I've some troubles if this extensions are on.


Fabrice

**Comment by jtreminio** [comment]
Your browser is probably blocking some JS.

Up to you to resolve this.
