### ISSUE TITLE
Purpose of "shared folders" when deploying to production in cloud?

### ISSUE THREAD

**Issue by OsakaWebbie** [puphpet/puphpet#2626]
For a development VM on one's local PC, shared folders are great. But can someone help me understand why there is a Shared Folders section in the various "Deploy to..." sections? In my case I'm deploying to Linode, but the question would be valid for any of the cloud servers when intended to be used as the live site. If one sets up a shared server, the site would only work when the developer's PC is connected to the internet, and then very slowly. Is the meaning of Shared Folders different in the Deploy scenario from how it works locally? (E.g. perhaps it does some sort of automatic copying, rather than simply linking back to the local PC...?)

**Comment by jtreminio** [comment]
The folders are "shared" (ie, synced) via rsync and only done on the initial `vagrant up`, or subsequent `vagrant provision`. There is no link, everything is uploaded and the rsync connection is closed.

I would recommend you instead use rsync directly vs vagrant provision, and go further and say not to use Vagrant on a production server but the standalone-puppet.sh command detailed here:

https://puphpet.com/#vagrantfile-none

**Comment by OsakaWebbie** [comment]
Ah! I was not even aware of the no-vagrant option. If that's the recommended method, what is the purpose of the "Deploy to Linode (or Rackspace or Digital Ocean, etc.) options? Do some people use cloud servers for their _development_ VM instead of their own PC? (Seems illogical to me, since it costs money and can't be used offline, but...)

And I have a related question about production deployment in general: I thought the purpose of Puppet (and by extension, PuPHPet) was to be able to use the exact same configuration on development and production (except for the domain names and folder syncing). If we get a PuPHPet ZIP for a local VM, then customize it with `exec-*` scripts, `dot` files, and perhaps other mods, I originally thought production deployment would somehow use that same set of puppet/puphpet files - I didn't know how to do that, but I assumed that's what everyone was doing. But now I've learned that we are apparently to go back to your interface and create a new ZIP each time we deploy to a different place. Not only do we have to then remember what mods we made that are not in the config.yaml, but any changes you make in the meantime to your interface and generation of the setup package could also cause differences. Can you shed any light on that concern, or describe what workflow people are using to ensure consistency?

**Comment by jtreminio** [comment]
The no-vagrant option was only recently added. You can still use Vagrant and provider plugins to create and destroy servers; However, if you are comfortable with a little shell, I would recommend you spin up the server but then manage the it via the no-vagrant option.

The reason being that you can now use CI to run Puppet without Vagrant, using the standalone-puppet.sh script to replicate what Vagrant would do, but without Vagrant.

The only differences between the two options is that the no-vagrant option does not:

* Run any exec-* scripts (exec-once, exec-always, etc)
* Rsync your shared folders (the option does not have any defined)

Replicating the steps in Jenkins or similar is not difficult.

**Comment by OsakaWebbie** [comment]
Is there a way to use the same PuPHPet configuration for both a local VM (with vagrant) and a production server (without vagrant)? For example, can I just use a portion of my local VM config with the standalone-puppet.sh file? Going back to the online interface with a customized config.yaml is causing problems for me - for example, you name the vhosts with random names, but I have a exec-once script that makes mods to them, so I renamed them in config.yaml, but your online interface doesn't keep my names but overwrites them with your random ones again, so unless I rename them every time, my script can't find the file to modify (plus, navigating `/etc/nginx/conf.d` is hard with such unrecognizable filenames). So it would be nice to be able to reuse the same configuration saved on my computer.
