### ISSUE TITLE
Symfony is very slow

### ISSUE THREAD

**Issue by ahmetelcik** [puphpet/puphpet#2636]
Symfony 3.2.7 is very slow why who is know that

[http://imgur.com/02EjRLp](url)
![sf3](https://cloud.githubusercontent.com/assets/6485654/24831221/8c0b94a8-1c9e-11e7-872a-3ed825cc725b.PNG)

**Comment by ahmetelcik** [comment]
solved

**Comment by jtreminio** [comment]
Anything specific you did?

**Comment by ahmetelcik** [comment]
i now do not remember :) but
i added something the vagrant file and it is solved,
i can't find the changing line,
when i remember it, i will to write here
