### ISSUE TITLE
Unable to import MySQL dump file

### ISSUE THREAD

**Issue by yuriybabenko** [puphpet/puphpet#2642]
Config file: https://pastebin.com/VrZ4cBQF

The following errors show up during `vagrant up` operation:

    ==> client-drupal: Notice: /Stage[main]/Puphpet::Mysql::Install/Puphpet::Mysql::Databases[from puphpet::mysql::install]/Mysql_database[project]/ensure: created
    ==> client-drupal: Notice: /Stage[main]/Puphpet::Mysql::Install/Puphpet::Mysql::Databases[from puphpet::mysql::install]/Exec[project-import]/returns: sh: 1: cannot open /var/www/drupal/project/db/project.sql: No such file
    ==> client-drupal: Error: mysql project < /var/www/drupal/project/db/project.sql && touch /opt/puphpet-state/db-import-project returned 2 instead of one of [0]
    ==> client-drupal: Error: /Stage[main]/Puphpet::Mysql::Install/Puphpet::Mysql::Databases[from puphpet::mysql::install]/Exec[project-import]/returns: change from notrun to 0 failed: mysql project < /var/www/drupal/project/db/project.sql && touch /opt/puphpet-state/db-import-project returned 2 instead of one of [0]

I can SSH into the box and re-run the import command (`mysql project < /var/www/drupal/project/db/project.sql && touch /opt/puphpet-state/db-import-project`), which works just fine. Well, I do get this output, but the DB imports fine:

    touch: cannot touch '/opt/puphpet-state/db-import-californium': Permission denied

For whatever reason, this doesn't work during setup. Perhaps the `/var/www` folder is not yet mapped when MySQL import happens? Order of operations problem?

**Comment by yuriybabenko** [comment]
So my database file is located at `/var/www/drupal/project/db/project.sql`, but it looks like at the time of mysql import command execution, `/var/www` does not contain my `drupal` folder, but rather has an `html` folder (Ubuntu default? Created by Apache?). Not sure what that's about.

**Comment by yuriybabenko** [comment]
Tried mapping a separate folder (`/var/projects`) and importing the database file from there - same error.

**Comment by yuriybabenko** [comment]
Ok, so bind mounts are the last thing that happens during provisioning, so the database files cannot be in that location. One option would be to wget them from the host machine or another source, and another would be to re-order the bind mount operation to make it happen earlier in the provisioning process...

**Comment by yuriybabenko** [comment]
Fixed the problem. Pull request above.

**Comment by jtreminio** [comment]
Thanks for the PR! Makes sense :)
