### ISSUE TITLE
* The hostname set for the VM should only contain letters, numbers, hyphens or dots.

### ISSUE THREAD

**Issue by AntonioCS** [puphpet/puphpet#2647]
Hey,

So I got this error msg when I did vagrant up:

* The hostname set for the VM should only contain letters, numbers,
hyphens or dots. It cannot start with a hyphen or dot.

The name I put for the hostname was: name1_name2..puphpet
I understand that I should have not added the underscore but the UI should have not accepted that as a valid hostname.

**Comment by jtreminio** [comment]
Sorry, I try not to add any real validation to the GUI because that's a rabbit hole that I'll never come out of.

**Comment by jtreminio** [comment]
There is this, though:

![image](https://user-images.githubusercontent.com/589398/35601402-6e4bbdd2-05f8-11e8-8c18-5d3d44cefe5d.png)
