### ISSUE TITLE
I have choosen mariadb but not installed , any hint? macOS vagrant 1.9.3 attach ^^^

### ISSUE THREAD

**Issue by lse123** [puphpet/puphpet#2651]
[config.yaml_puphpet.txt](https://github.com/puphpet/puphpet/files/949012/config.yaml_puphpet.txt)

I have choosen mariadb but not installed , any hint? macOS vagrant 1.9.3 attach ^^^

[01:27 PM]-[vagrant@yyyyy]-[~] 
$ sudo systemctl status mysqld
Unit mysqld.service could not be found.

[01:28 PM]-[vagrant@yyyyy]-[~] 
$ sudo systemctl status mariadb
Unit mariadb.service could not be found.

[01:28 PM]-[vagrant@yyyyy]-[~] 
$ sudo systemctl status mariadbd
Unit mariadbd.service could not be found.

[01:28 PM]-[vagrant@yyyyy]-[~] 
$ sudo systemctl status httpd
● httpd.service - The Apache HTTP Server
   Loaded: loaded (/usr/lib/systemd/system/httpd.service; enabled; vendor preset: disabled)
   Active: active (running) since Sat 2017-04-22 13:26:18 UTC; 2min 41s ago
 Main PID: 1063 (httpd)
   Status: "Total requests: 0; Idle/Busy workers 100/0;Requests/sec: 0; Bytes served/sec:   0 B/sec"
   CGroup: /system.slice/httpd.service
           ├─1063 /usr/sbin/httpd -DFOREGROUND
           ├─1214 /usr/sbin/httpd -DFOREGROUND
           ├─1234 /usr/sbin/httpd -DFOREGROUND
           └─1235 /usr/sbin/httpd -DFOREGROUND

Apr 22 13:26:17 leonidass.com systemd[1]: Starting The Apache HTTP Server...
Apr 22 13:26:18 leonidass.com systemd[1]: Started The Apache HTTP Server.

[01:28 PM]-[vagrant@yyyyy]-[~] 
$

**Comment by jtreminio** [comment]
Sorry, this should be working fine now.
