### ISSUE TITLE
Unable to boot Ubuntu 14.04 on VMWare_Workstation (latest -> 12.5.5)

### ISSUE THREAD

**Issue by pascalwacker** [puphpet/puphpet#2652]
I did a update a few days ago and since I'm not able to properly boot any Ubuntu 14.04 puphpet machines. The machine boots and you can access it by `vagrant ssh`, but it fails to connect the shared folders (including `/vagrant`). The issue is both with `nfs` and `default` option. Host is a Ubuntu 16.04.

Error message:
```
==> toasted: Enabling and configuring shared folders...
An error occurred while executing `vmrun`, a utility for controlling
VMware machines. The command and output are below:

Command: ["enableSharedFolders", "/home/pascal/.local/share/Trash/files/toasted/.vagrant/machines/toasted/vmware_workstation/6b97f697-3f95-4455-9fe5-44896825ab97/ubuntu-14.04-amd64.vmx", {:notify=>[:stdout, :stderr]}]

Stdout: Error: There was an error mounting the Shared Folders file system inside the guest operating system

Stderr: 
```

Can anybody confirm this?

**Comment by jtreminio** [comment]
Probably due to bad box generation on my part. No longer an issue since switching to bento boxes.
