### ISSUE TITLE
Options to install vagrant plugins?

### ISSUE THREAD

**Issue by arimourao** [puphpet/puphpet#2656]
I think would be great if the web generator offered options to install vagrant plugins like [landrush](https://github.com/vagrant-landrush/landrush) and [host updater](https://github.com/cogitatio/vagrant-hostsupdater)

**Comment by Hlsgs** [comment]
Hmm, those are global if I'm not mistaken, so seeing as puphpet rolls individual VMs I don't think it's the proper place for it. They could be mentioned in the documentation though, along with WinNFSd for Windows.

**Comment by arimourao** [comment]
Well, honestly, I don't see the problem. If you create a box that you want to share with several other people they will have to manually install the missing plugins.

**Comment by Hlsgs** [comment]
Yeah, you have a point there.

**Comment by jtreminio** [comment]
Can't do this, since Windows will have issues forcing a plugin install from Vagrantfile.

Best to just enforce it elsewhere.
