### ISSUE TITLE
nodejs 7 not supported in manifest

### ISSUE THREAD

**Issue by mgkimsal** [puphpet/puphpet#2664]
For ubuntu, the 7.xx nodejs series isn't listed in the manifest file.

**Comment by mgkimsal** [comment]
I can't find the src to do a pull request, but the generated file here:

puppet/modules/puphpet/manifests/nodejs/params.pp

```
  $version = $puphpet::params::hiera['nodejs']['settings']['version'] ? {
    '6'     => '6.x',
    '5'     => '5.x',
    '4'     => '4.x',
    default => '6.x',
  }
```

should be

```
  $version = $puphpet::params::hiera['nodejs']['settings']['version'] ? {
    '7'     => '7.x',
    '6'     => '6.x',
    '5'     => '5.x',
    '4'     => '4.x',
    default => '6.x',
  }
```

There may be some other knock-on effect from this change, but I did get things to work for me by making that change and reprovisioning a new machine.

**Comment by jtreminio** [comment]
Added!
