### ISSUE TITLE
Custom nginx settings in location section

### ISSUE THREAD

**Issue by laulicus** [puphpet/puphpet#2666]
How can I add custom lines to location section in src/PuphpetBundle/Resources/config/nginx/defaults.yml file? I would like to add this into location / {}:
if (-f $request_filename) { break; }

**Comment by jtreminio** [comment]
Implemented!

![image](https://user-images.githubusercontent.com/589398/35599625-45dda1d4-05ef-11e8-969a-caaac355c657.png)

(Additional Settings).
