### ISSUE TITLE
PHP 7.0.19 breaks Drupal

### ISSUE THREAD

**Issue by vincenzo** [puphpet/puphpet#2668]
@jtreminio I noticed that provisioning PHP 7.0 now means getting 7.0.19 installed. This version [breaks Drupal 7](https://www.drupal.org/node/2877243). Though there's a patch and a patch-based workflow is common with Drupal, not all circumstances allow this to be a feasible option. 

Any chance you would consider going back to 7.0.17 until that patch has gone into an official release?

**Comment by jtreminio** [comment]
Unfortunately puphpet's PHP comes from Ondrej's repo, which does not keep anything but latest version in history.

You can let him know of any issues at https://twitter.com/oerdnj
