### ISSUE TITLE
Cygwin issue with rsync/ssh? 

### ISSUE THREAD

**Issue by SneakyDave** [puphpet/puphpet#2669]
Just curious if this would be an issue with my Cygwin version, or perhaps with the ssh version installed on my machine. Just need help where to look next, or if I can remove this option somehow from the rsync script in puphpet?

Any puphpet machine I create that uses rsync to sync files, during vagrant up, I get this exception:
______________
There was an error when attempting to rsync a synced folder.
Please inspect the error message below for more info.

Host path: /cygdrive/g/vm/box1/var/www/
Guest path: /var/www
Command: "rsync" "--verbose" "--archive" "-z" "--chmod=ugo=rwX" "--no-perms" "--
no-owner" "--no-group" "--rsync-path" "sudo rsync" "-e" "ssh -p 2222 -o LogLevel
=FATAL   -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile
=/dev/null -i 'C:/Users/myname/.vagrant.d/insecure_private_key'" "--exclude" "
.vagrant/" "--exclude" ".git/" "/cygdrive/g/vm/box1/var/www/" "vagrant@127.0.0.1
:/var/www"
Error: error: Invalid command line -o option 'IdentitiesOnly'
_____________

config.yaml:
https://pastebin.com/S6hQtE2M

**Comment by jtreminio** [comment]
Sorry, this would be a vagrant core issue, since puphpet doesn't actually run the rsync commands itself :(

Good luck!
