### ISSUE TITLE
Vagrant SSH with Vagrant 1.9.5

### ISSUE THREAD

**Issue by createadrln** [puphpet/puphpet#2670]
Can no longer connect with `vagrant ssh` with Vagrant 1.9.5 update (on multiple boxes on Windows 10). Virtual Box 5.1.22. An example from one `vagrant ssh-config` output:

```
Host nbaa
HostName 127.0.0.1
User vagrant
Port 2222
UserKnownHostsFile /dev/null
StrictHostKeyChecking no
PasswordAuthentication no
IdentityFile "C:/Users/rmacmurray/Client Sites/nbaa.vm/puphpet/files/dot/ssh/id_rsa"
IdentityFile C:/Users/rmacmurray/.vagrant.d/insecure_private_key
IdentitiesOnly yes
LogLevel FATAL
```

**Comment by createadrln** [comment]
Message when trying to run `vagrant ssh` command:

```
Warning: Identity file C:/Users/rmacmurray/Client not accessible: No such file or directory.
vagrant@127.0.0.1's password:
```

**Comment by createadrln** [comment]
`id_rsa` and `insecure_private_key` files are both present in the paths

**Comment by Bodom78** [comment]
Having the same issue. IdentityFile path breaks at the first space.

**Comment by createadrln** [comment]
Checking on an update for this

**Comment by jtreminio** [comment]
This was fixed in https://github.com/hashicorp/vagrant/pull/8924
