### ISSUE TITLE
Configuring Apache mods?

### ISSUE THREAD

**Issue by ultrablue** [puphpet/puphpet#2673]
Howdy:

I have a question about configuring Apache mods:

How do I do that?

One of the mods I've installed (auth_cas) has a number of settings that it needs. The mod gets installed ok and is running. But, because it's not configured it causes Apache to die. In the past, I've set these myself in the VM. However, I would like to automate the process mainly so that provisioning doesn't clobber them.

I've done some investigating, and I saw that this file might be worth editing:
puphpet/puppet/modules/apache/manifests/mod/auth_cas.pp

But that doesn't seem to do much.

I'm not asking for step-by-step instructions (unless there are some), but rather, pointers on where to start.

Thanks!
Greg

**Comment by jtreminio** [comment]
Outside of writing some simple Puppet to create a file and set its contents, you can simply create an exec-once file to do an echo into your target file.
