### ISSUE TITLE
Could not evaluate: invalid byte sequence in US-ASCII, during provision

### ISSUE THREAD

**Issue by yivi** [puphpet/puphpet#2679]
I've created my box and works normally.

Aftewards, I've added a vhost entry manually in my config.yaml, and run `vagrant provision` to create it.

The new vhost gets created and works perfectly, but the output from the provision command still says:

`The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.`

The only thing above a notice that I get during provision is:

`Error: /Stage[main]/Puphpet::Redis::Install/Puphpet::Php::Module::Pecl[redis]/Php::Pecl::Module[redis]/Exec[pecl-redis]: Could not evaluate: invalid byte sequence in US-ASCII`

So I'm afraid something else is broken in machine, or will be when I want to reprovision the machine with different settings.

Anything I can do to get more information about this error, and how to get around it?

**Comment by mmortek** [comment]
I can confirm this error. It happens only during reprovisioning, to avoid this problem I need to destroy vagrant instance and run vagrant up again.

**Comment by lvillanne** [comment]
Hello, I think it's the same problem than : https://github.com/puphpet/puphpet/issues/2650

Try this solution : https://github.com/puphpet/puphpet/issues/2650#issuecomment-299906927

**Comment by jtreminio** [comment]
The `php-redis` package is now installed for Ubuntu, vs the pecl package.
