### ISSUE TITLE
vagrant insecure_private_key

### ISSUE THREAD

**Issue by ymakkapa** [puphpet/puphpet#2682]
Hello everyone,
I have been using vagrant to spin up virtual machines with virtual box. I currently have 2 ubuntu virtual machines. two folders named ".vagrant" and ".vagrant.d". The private key is present in .vagrant.d as "insecure_private_key". 

Please find the below attachments for the contents of these folders.

I wanted to connect to one of these virtual machines but the ssh connection is refused.
Attached is the screenshot of connection refusal.

<img width="1039" alt="screen shot 2017-06-30 at 4 16 09 pm" src="https://user-images.githubusercontent.com/20130992/27752534-7c84b5bc-5daf-11e7-8ffe-8153cf398bfb.png">

<img width="893" alt="screen shot 2017-06-30 at 4 14 18 pm" src="https://user-images.githubusercontent.com/20130992/27752487-39d9b80c-5daf-11e7-900e-add6e4649ac2.png">

**Comment by jtreminio** [comment]
https://github.com/puphpet/puphpet/blob/master/archive/puphpet/shell/ascii-art/important-notices.txt#L25
