### ISSUE TITLE
Port 80 open on vm but not accessible

### ISSUE THREAD

**Issue by sinzen** [puphpet/puphpet#2694]
Hi,
I installed a vm using PUPHPET. I try to access on my localhost in the same network but other device.
Like my tablet..
I'm using the the ip address of my host machine,
But i can't access to it..
I tried with the ip address of the vm unsuccessful.
I also open the port 80 on my vm..
I'm on ubuntu here are my netstat:

`tcp        0      0 machine1.puphpet:9000   *:*                     LISTEN
tcp        0      0 machine1.puphpet:mysql  *:*                     LISTEN
tcp        0      0 *:ssh                   *:*                     LISTEN
tcp        0      0 10.0.2.15:ssh           10.0.2.2:51890          ESTABLISHED
tcp6       0      0 [::]:https              [::]:*                  LISTEN
tcp6       0      0 machine1.puphpet:9200   [::]:*                  LISTEN
tcp6       0      0 localhost:9200          [::]:*                  LISTEN
tcp6       0      0 [::]:http               [::]:*                  LISTEN
tcp6       0      0 machine1.puphpet:9300   [::]:*                  LISTEN
tcp6       0      0 localhost:9300          [::]:*                  LISTEN
tcp6       0      0 [::]:ssh                [::]:*                  LISTEN
udp        0      0 *:bootpc                *:*
udp        0      0 192.168.56.101:ntp      *:*
udp        0      0 10.0.2.15:ntp           *:*
udp        0      0 machine1.puphpet:ntp    *:*
udp        0      0 *:ntp                   *:*
udp6       0      0 fe80::a00:27ff:fece:ntp [::]:*
udp6       0      0 fe80::a00:27ff:fe54:ntp [::]:*
udp6       0      0 localhost:ntp           [::]:*
udp6       0      0 [::]:ntp                [::]:*
Active UNIX domain sockets (servers and established)`

my vagrant mess:
`machine1: You are trying to forward to privileged ports (ports <= 1024). Most
==> machine1: operating systems restrict this to only privileged process (typically
==> machine1: processes running as an administrative user). This is a warning in case
==> machine1: the port forwarding doesn't work. If any problems occur, please try a
==> machine1: port higher than 1024.`

and my port 80 on virtualbox:

<img width="577" alt="2017-08-02 a 21 34 16" src="https://user-images.githubusercontent.com/11914312/28925302-c0cec896-7864-11e7-85ab-154e18436afa.png">

Thanks for your help.

**Comment by jtreminio** [comment]
On your host machine, you should choose a port greater than 1024 since those are system-reserved (mostly).

For example, forward host's 8080 to vm's 80.
