### ISSUE TITLE
edit labels

### ISSUE THREAD

**Issue by yivi** [puphpet/puphpet#2702]
Would be great being able to edit labels before creating config.yaml, at least for things like the virtualhosts, so logs and configuration files end up with more recognizable names than **"av_ng4blv9rjuqm_"**.

**Comment by jtreminio** [comment]
While I didn't add editable labels, I reworked all labels to be a bit more descriptive for the defaults and any additional tabs added through the GUI.

I also made it so importing a config file keeps your chosen label names.
