### ISSUE TITLE
Failed to install PHP GD library on Nginx/Php7 setup

### ISSUE THREAD

**Issue by iamromeo** [puphpet/puphpet#2705]
**Config file:**
`vagrantfile:
    target: local
    vm:
        provider:
            local:
                box: puphpet/ubuntu1604-x64
                box_url: 'false'
                box_version: '0'
                chosen_virtualizer: virtualbox
                virtualizers:
                    virtualbox:
                        modifyvm:
                            natdnshostresolver1: false
                        showgui: 0
                    vmware:
                        numvcpus: 1
                    parallels:
                        linked_clone: 0
                        check_guest_tools: 0
                        update_guest_tools: 0
                machines:
                    vflm_wd52ajrmdhr3:
                        id: wbappmachine
                        hostname: wbappmachine
                        network:
                            private_network: 192.168.33.66
                            forwarded_port:
                                vflmnfp_ekew78g5u2s6:
                                    host: '9467'
                                    guest: '22'
                        memory: '4096'
                        cpus: '1'
        provision:
            puppet:
                manifests_path: puphpet/puppet/manifests
                module_path:
                    - puphpet/puppet/modules
                    - puphpet/puppet/manifests
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
        synced_folder:
            vflsf_yxb2sy9wc1z3:
                owner: www-data
                group: www-data
                source: ./files
                target: /var/www
                sync_type: nfs
                smb:
                    smb_host: ''
                    smb_username: ''
                    smb_password: ''
                    mount_options:
                        dir_mode: '0775'
                        file_mode: '0664'
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    exclude:
                        - .vagrant/
                        - .git/
                    auto: 'true'
        usable_port_range:
            start: 10200
            stop: 10500
        post_up_message: ''
    ssh:
        host: 'false'
        port: 'false'
        private_key_path: 'false'
        username: vagrant
        guest_port: 'false'
        keep_alive: '1'
        forward_agent: 'false'
        forward_x11: 'false'
        shell: 'bash -l'
        insert_key: 'false'
    vagrant:
        host: detect
    proxy:
        http: ''
        https: ''
        ftp: ''
        no_proxy: ''
server:
    install: '1'
    packages:
        - vim
        - htop
        - zip
        - unzip
users_groups:
    install: '1'
    groups: {  }
    users: {  }
locale:
    install: '1'
    settings:
        default_locale: en_US.UTF-8
        locales:
            - en_GB.UTF-8
            - en_US.UTF-8
        timezone: Europe/London
firewall:
    install: '1'
    rules: {  }
resolv:
    install: '1'
    nameservers:
        - 8.8.8.8
        - 8.8.4.4
    domainname: ''
    searchpath: {  }
cron:
    install: '1'
    jobs: {  }
nginx:
    install: '1'
    settings:
        version: present
        default_vhost: 1
        proxy_buffers: '4 256k'
        proxy_buffer_size: 128k
        proxy_connect_timeout: 600s
        proxy_send_timeout: 600s
        proxy_read_timeout: 600s
        names_hash_bucket_size: 128
    upstreams: {  }
    vhosts:
        nxv_ti6zd07dpuw3:
            server_name: wb.dev
            server_aliases:
                - www.wb.dev
            www_root: /var/www/wb/web
            listen_port: '80'
            client_max_body_size: 1m
            ssl: '0'
            locations:
                nxvl_eiz6k20gz5pc:
                    www_root: /var/www/wb/web
                    location: /
                    autoindex: 'off'
                    internal: 'false'
                    index_files:
                        - index.html
                        - index.php
                        - app.php
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
                        - /app.php$is_args$args
                    fastcgi: ''
                    fastcgi_index: ''
                    fastcgi_split_path: ''
                    proxy: ''
                    proxy_redirect: ''
                nxvl_jpwrdk33e6zz:
                    www_root: /var/www/wb/web
                    location: '~ ^/(app_dev|config)\.php(/|$)'
                    autoindex: 'off'
                    internal: 'false'
                    try_files:
                        - $uri
                        - $uri/
                        - /app_dev.php$is_args$args
                    fastcgi: '127.0.0.1:9000'
                    fastcgi_index: app_dev.php
                    fastcgi_split_path: '^(.+\.php)(/.*)$'
                    fast_cgi_params_extra:
                        - 'SCRIPT_FILENAME $document_root$fastcgi_script_name'
                        - 'APP_ENV dev'
                    set:
                        - '$path_info $fastcgi_path_info'
                    proxy: ''
                    proxy_redirect: ''
                nxvl_6w2n57h7r3pi:
                    www_root: /var/www/wb/web
                    location: '~ ^/index\.php(/|$)'
                    autoindex: 'off'
                    internal: 'false'
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
                    fastcgi: '127.0.0.1:9000'
                    fastcgi_index: index.php
                    fastcgi_split_path: '^(.+\.php)(/.*)$'
                    fast_cgi_params_extra:
                        - 'SCRIPT_FILENAME $document_root$fastcgi_script_name'
                    set:
                        - '$path_info $fastcgi_path_info'
                    proxy: ''
                    proxy_redirect: ''
                nxvl_4sbf5inpotrd:
                    www_root: /var/www/wb/web
                    location: '~ ^/app\.php(/|$)'
                    autoindex: 'off'
                    internal: 'false'
                    try_files:
                        - $uri
                        - $uri/
                        - /app.php$is_args$args
                    fastcgi: '127.0.0.1:9000'
                    fastcgi_index: app.php
                    fastcgi_split_path: '^(.+\.php)(/.*)$'
                    fast_cgi_params_extra:
                        - 'SCRIPT_FILENAME $document_root$fastcgi_script_name'
                        - 'APP_ENV prod'
                    set:
                        - '$path_info $fastcgi_path_info'
                    proxy: ''
                    proxy_redirect: ''
    proxies: {  }
apache:
    install: '0'
    settings:
        version: 2.4
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - proxy_fcgi
        - rewrite
    vhosts:
        av_nyu9mhmngrk4:
            servername: awesome.dev
            serveraliases:
                - www.awesome.dev
            docroot: /var/www/awesome/web
            port: '80'
            setenvif:
                - 'Authorization "(.*)" HTTP_AUTHORIZATION=$1'
            custom_fragment: ''
            ssl: '0'
            ssl_cert: LETSENCRYPT
            ssl_key: LETSENCRYPT
            ssl_chain: LETSENCRYPT
            ssl_certs_dir: LETSENCRYPT
            ssl_protocol: ''
            ssl_cipher: ''
            directories:
                avd_atpkz7sqneot:
                    path: /var/www/awesome/web
                    directoryindex: 'index.php app.dev'
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - 'all granted'
                    custom_fragment: ''
                    provider: directory
            files_match:
                avfm_rptk9re0oh0e:
                    path: (app_dev|config)\.php$
                    sethandler: 'proxy:fcgi://127.0.0.1:9000'
                    setenv:
                        - 'APP_ENV dev'
                    custom_fragment: ''
                    provider: filesmatch
                avfm_zytgcuqdru5k:
                    path: app\.php$
                    sethandler: 'proxy:fcgi://127.0.0.1:9000'
                    setenv:
                        - 'APP_ENV prod'
                    custom_fragment: ''
                    provider: filesmatch
                avfm_efs9ud0o5dk2:
                    path: \.php$
                    sethandler: 'proxy:fcgi://127.0.0.1:9000'
                    custom_fragment: ''
                    provider: filesmatch
letsencrypt:
    install: '1'
    settings:
        email: ''
    domains: {  }
php:
    install: '1'
    settings:
        version: '7.1'
    modules:
        php:
            - cli
            - intl
            - xml
            - mysqlnd
            - curl
            - gd
        pear: {  }
        pecl: {  }
    ini:
        display_errors: 'On'
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
        date.timezone: UTC
    fpm_ini:
        error_log: /var/log/php-fpm.log
    fpm_pools:
        phpfp_zr1taohzmkbo:
            ini:
                prefix: www
                listen: '127.0.0.1:9000'
                security.limit_extensions: .php
                user: www-user
                group: www-data
    composer: '1'
    composer_home: ''
xdebug:
    install: '1'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
blackfire:
    install: '0'
    settings:
        server_id: ''
        server_token: ''
        agent:
            http_proxy: ''
            https_proxy: ''
            log_file: stderr
            log_level: '1'
        php:
            agent_timeout: '0.25'
            log_file: ''
            log_level: '1'
xhprof:
    install: '0'
wpcli:
    install: '0'
    version: v1.1.0
drush:
    install: '0'
    version: 8.0.5
ruby:
    install: '1'
    versions:
        rv_89tn7wdb8pru:
            default: '1'
            bundler: '1'
            version: 2.3.1
            gems:
                - deep_merge@1.0.1
                - activesupport@4.2.6
                - vine@0.2
python:
    install: '1'
    packages: {  }
    versions: {  }
nodejs:
    install: '0'
    settings:
        version: '6'
    npm_packages: {  }
mariadb:
    install: '0'
    settings:
        version: '10.1'
        root_password: 123
        override_options: {  }
    users: {  }
    databases: {  }
    grants: {  }
mysql:
    install: '1'
    settings:
        version: '5.7'
        root_password: '123'
        override_options: {  }
    users:
        mysqlnu_f57ayerb5sgf:
            name: dbuser
            password: dbpassword
    databases:
        mysqlnd_wojccll2mkjq:
            name: dbname
            sql: ''
    grants:
        mysqlng_2x0xynuwif35:
            user: dbuser
            table: '*.*'
            privileges:
                - ALL
postgresql:
    install: '0'
    settings:
        global:
            encoding: UTF8
            version: '9.6'
        server:
            postgres_password: '123'
    databases: {  }
    users: {  }
    grants: {  }
mongodb:
    install: '0'
    settings:
        bind_ip: 127.0.0.1
        port: '27017'
    globals:
        version: 2.6.0
    databases: {  }
redis:
    install: '0'
    settings:
        port: '6379'
sqlite:
    install: '0'
    databases: {  }
mailhog:
    install: '0'
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '8025'
        path: /usr/local/bin/mailhog
beanstalkd:
    install: '0'
    settings:
        listenaddress: 0.0.0.0
        listenport: '11300'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: 0
rabbitmq:
    install: '0'
    settings:
        port: '5672'
    users: {  }
    vhosts: {  }
    plugins: {  }
elastic_search:
    install: '0'
    settings:
        version: 2.3.1
        java_install: true
    instances:
        esi_fs8pfjlzjvnz:
            name: es-01
solr:
    install: '0'
    settings:
        version: 5.5.2
        port: '8984'

`
# **Error:**
`==> wbappmachine: Error: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install php7.1-gd' returned 100: Reading package lists...
==> wbappmachine: Building dependency tree...
==> wbappmachine: Reading state information...
==> wbappmachine: The following additional packages will be installed:
==> wbappmachine:   fontconfig-config fonts-dejavu-core libfontconfig1 libgd3 libjbig0
==> wbappmachine:   libjpeg-turbo8 libjpeg8 libtiff5 libwebp5 libx11-6 libx11-data libxau6
==> wbappmachine:   libxcb1 libxdmcp6 libxpm4
==> wbappmachine: Suggested packages:
==> wbappmachine:   libgd-tools
==> wbappmachine: The following NEW packages will be installed:
==> wbappmachine:   fontconfig-config fonts-dejavu-core libfontconfig1 libgd3 libjbig0
==> wbappmachine:   libjpeg-turbo8 libjpeg8 libtiff5 libwebp5 libx11-6 libx11-data libxau6
==> wbappmachine:   libxcb1 libxdmcp6 libxpm4 php7.1-gd
==> wbappmachine: 0 upgraded, 16 newly installed, 0 to remove and 169 not upgraded.
==> wbappmachine: Need to get 2607 kB of archives.
==> wbappmachine: After this operation, 9229 kB of additional disk space will be used.
==> wbappmachine: Get:1 http://ppa.launchpad.net/ondrej/php/ubuntu xenial/main amd64 libjbig0 amd64 2.1-3.1+deb.sury.org~xenial+1 [26.4 kB]
==> wbappmachine: Get:2 http://ppa.launchpad.net/ondrej/php/ubuntu xenial/main amd64 libwebp5 amd64 0.4.4-1+deb.sury.org~xenial+1 [166 kB]
==> wbappmachine: Get:3 http://ppa.launchpad.net/ondrej/php/ubuntu xenial/main amd64 libgd3 amd64 2.2.3-3+deb.sury.org~xenial+0 [132 kB]
==> wbappmachine: Get:4 http://us.archive.ubuntu.com/ubuntu xenial/main amd64 libxau6 amd64 1:1.0.8-1 [8376 B]
==> wbappmachine: Err:5 http://ppa.launchpad.net/ondrej/php/ubuntu xenial/main amd64 php7.1-gd amd64 7.1.6-1~ubuntu16.04.1+deb.sury.org+1
==> wbappmachine:   404  Not Found
==> wbappmachine: Get:6 http://us.archive.ubuntu.com/ubuntu xenial/main amd64 libjpeg-turbo8 amd64 1.4.2-0ubuntu3 [111 kB]
==> wbappmachine: Get:7 http://us.archive.ubuntu.com/ubuntu xenial/main amd64 libxdmcp6 amd64 1:1.1.2-1.1 [11.0 kB]
==> wbappmachine: Get:8 http://us.archive.ubuntu.com/ubuntu xenial/main amd64 libxcb1 amd64 1.11.1-1ubuntu1 [40.0 kB]
==> wbappmachine: Get:9 http://us.archive.ubuntu.com/ubuntu xenial/main amd64 libx11-data all 2:1.6.3-1ubuntu2 [113 kB]
==> wbappmachine: Get:10 http://us.archive.ubuntu.com/ubuntu xenial/main amd64 libx11-6 amd64 2:1.6.3-1ubuntu2 [571 kB]
==> wbappmachine: Get:11 http://us.archive.ubuntu.com/ubuntu xenial/main amd64 fonts-dejavu-core all 2.35-1 [1039 kB]
==> wbappmachine: Get:12 http://us.archive.ubuntu.com/ubuntu xenial-updates/main amd64 fontconfig-config all 2.11.94-0ubuntu1.1 [49.9 kB]
==> wbappmachine: Get:13 http://us.archive.ubuntu.com/ubuntu xenial-updates/main amd64 libfontconfig1 amd64 2.11.94-0ubuntu1.1 [131 kB]
==> wbappmachine: Get:14 http://us.archive.ubuntu.com/ubuntu xenial/main amd64 libjpeg8 amd64 8c-2ubuntu8 [2194 B]
==> wbappmachine: Get:15 http://us.archive.ubuntu.com/ubuntu xenial-updates/main amd64 libtiff5 amd64 4.0.6-1ubuntu0.2 [146 kB]
==> wbappmachine: Get:16 http://us.archive.ubuntu.com/ubuntu xenial-updates/main amd64 libxpm4 amd64 1:3.5.11-1ubuntu0.16.04.1 [33.8 kB]
==> wbappmachine: Fetched 2580 kB in 1s (2421 kB/s)
==> wbappmachine: E: Failed to fetch http://ppa.launchpad.net/ondrej/php/ubuntu/pool/main/p/php7.1/php7.1-gd_7.1.6-1~ubuntu16.04.1+deb.sury.org+1_amd64.deb  404  Not Found
==> wbappmachine:
==> wbappmachine: E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
==> wbappmachine: Error: /Stage[main]/Puphpet::Php::Modules/Puphpet::Php::Module::Package[gd]/Php::Module[gd]/Package[PhpModule_gd]/ensure: change from purged to present failed: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install php7.1-gd' returned 100: Reading package lists...
==> wbappmachine: Building dependency tree...
==> wbappmachine: Reading state information...
==> wbappmachine: The following additional packages will be installed:
==> wbappmachine:   fontconfig-config fonts-dejavu-core libfontconfig1 libgd3 libjbig0
==> wbappmachine:   libjpeg-turbo8 libjpeg8 libtiff5 libwebp5 libx11-6 libx11-data libxau6
==> wbappmachine:   libxcb1 libxdmcp6 libxpm4
==> wbappmachine: Suggested packages:
==> wbappmachine:   libgd-tools
==> wbappmachine: The following NEW packages will be installed:
==> wbappmachine:   fontconfig-config fonts-dejavu-core libfontconfig1 libgd3 libjbig0
==> wbappmachine:   libjpeg-turbo8 libjpeg8 libtiff5 libwebp5 libx11-6 libx11-data libxau6
==> wbappmachine:   libxcb1 libxdmcp6 libxpm4 php7.1-gd
==> wbappmachine: 0 upgraded, 16 newly installed, 0 to remove and 169 not upgraded.
==> wbappmachine: Need to get 2607 kB of archives.
==> wbappmachine: After this operation, 9229 kB of additional disk space will be used.
==> wbappmachine: Get:1 http://ppa.launchpad.net/ondrej/php/ubuntu xenial/main amd64 libjbig0 amd64 2.1-3.1+deb.sury.org~xenial+1 [26.4 kB]
==> wbappmachine: Get:2 http://ppa.launchpad.net/ondrej/php/ubuntu xenial/main amd64 libwebp5 amd64 0.4.4-1+deb.sury.org~xenial+1 [166 kB]
==> wbappmachine: Get:3 http://ppa.launchpad.net/ondrej/php/ubuntu xenial/main amd64 libgd3 amd64 2.2.3-3+deb.sury.org~xenial+0 [132 kB]
==> wbappmachine: Get:4 http://us.archive.ubuntu.com/ubuntu xenial/main amd64 libxau6 amd64 1:1.0.8-1 [8376 B]
==> wbappmachine: Err:5 http://ppa.launchpad.net/ondrej/php/ubuntu xenial/main amd64 php7.1-gd amd64 7.1.6-1~ubuntu16.04.1+deb.sury.org+1
==> wbappmachine:   404  Not Found
==> wbappmachine: Get:6 http://us.archive.ubuntu.com/ubuntu xenial/main amd64 libjpeg-turbo8 amd64 1.4.2-0ubuntu3 [111 kB]
==> wbappmachine: Get:7 http://us.archive.ubuntu.com/ubuntu xenial/main amd64 libxdmcp6 amd64 1:1.1.2-1.1 [11.0 kB]
==> wbappmachine: Get:8 http://us.archive.ubuntu.com/ubuntu xenial/main amd64 libxcb1 amd64 1.11.1-1ubuntu1 [40.0 kB]
==> wbappmachine: Get:9 http://us.archive.ubuntu.com/ubuntu xenial/main amd64 libx11-data all 2:1.6.3-1ubuntu2 [113 kB]
==> wbappmachine: Get:10 http://us.archive.ubuntu.com/ubuntu xenial/main amd64 libx11-6 amd64 2:1.6.3-1ubuntu2 [571 kB]
==> wbappmachine: Get:11 http://us.archive.ubuntu.com/ubuntu xenial/main amd64 fonts-dejavu-core all 2.35-1 [1039 kB]
==> wbappmachine: Get:12 http://us.archive.ubuntu.com/ubuntu xenial-updates/main amd64 fontconfig-config all 2.11.94-0ubuntu1.1 [49.9 kB]
==> wbappmachine: Get:13 http://us.archive.ubuntu.com/ubuntu xenial-updates/main amd64 libfontconfig1 amd64 2.11.94-0ubuntu1.1 [131 kB]
==> wbappmachine: Get:14 http://us.archive.ubuntu.com/ubuntu xenial/main amd64 libjpeg8 amd64 8c-2ubuntu8 [2194 B]
==> wbappmachine: Get:15 http://us.archive.ubuntu.com/ubuntu xenial-updates/main amd64 libtiff5 amd64 4.0.6-1ubuntu0.2 [146 kB]
==> wbappmachine: Get:16 http://us.archive.ubuntu.com/ubuntu xenial-updates/main amd64 libxpm4 amd64 1:3.5.11-1ubuntu0.16.04.1 [33.8 kB]
==> wbappmachine: Fetched 2580 kB in 1s (2421 kB/s)
==> wbappmachine: E: Failed to fetch http://ppa.launchpad.net/ondrej/php/ubuntu/pool/main/p/php7.1/php7.1-gd_7.1.6-1~ubuntu16.04.1+deb.sury.org+1_amd64.deb  404  Not Found
==> wbappmachine:
==> wbappmachine: E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
==> wbappmachine: Notice: /Stage[main]/Puphpet::Php::Install/Service[php7.1-fpm]: Dependency Package[PhpModule_gd] has failures: true
==> wbappmachine: Info: /Stage[main]/Puphpet::Php::Install/Service[php7.1-fpm]: Unscheduling all events on Service[php7.1-fpm]
==> wbappmachine: Notice: /Stage[main]/Puphpet::Php::Alternatives/Puphpet::Alternatives_update[php]/Exec[check alternatives for php]: Dependency Package[PhpModule_gd] has failures: true
==> wbappmachine: Notice: /Stage[main]/Puphpet::Php::Alternatives/Puphpet::Alternatives_update[php]/Exec[update alternatives for php to 7.1]: Dependency Package[PhpModule_gd] has failures: true
==> wbappmachine:
==> wbappmachine: Warning: /Stage[main]/Puphpet::Php::Install/Service[php7.1-fpm]: Skipping because of failed dependencies
==> wbappmachine: Warning: /Stage[main]/Puphpet::Php::Alternatives/Puphpet::Alternatives_update[php]/Exec[check alternatives for php]: Skipping because of failed dependencies
==> wbappmachine: Warning: /Stage[main]/Puphpet::Php::Alternatives/Puphpet::Alternatives_update[php]/Exec[update alternatives for php to 7.1]: Skipping because of failed dependencies
==> wbappmachine: Info: Computing checksum on file /etc/nginx/sites-available/nxv_ti6zd07dpuw3.conf
==> wbappmachine: Info: /Stage[main]/Puphpet::Nginx::Install/Puphpet::Nginx::Vhosts[from puphpet::nginx::install]/Nginx::Resource::Vhost[nxv_ti6zd07dpuw3]/Concat[/etc/nginx/sites-available/nxv_ti6zd07dpuw3.conf]/File[/etc/nginx/sites-available/nxv_ti6zd07dpuw3.conf]: Filebucketed /etc/nginx/sites-available/nxv_ti6zd07dpuw3.conf to puppet with sum b0557178996eec9fb8427fd5ccfeed0a
==> wbappmachine: Notice: /Stage[main]/Puphpet::Nginx::Install/Puphpet::Nginx::Vhosts[from puphpet::nginx::install]/Nginx::Resource::Vhost[nxv_ti6zd07dpuw3]/Concat[/etc/nginx/sites-available/nxv_ti6zd07dpuw3.conf]/File[/etc/nginx/sites-available/nxv_ti6zd07dpuw3.conf]/content: content changed '{md5}b0557178996eec9fb8427fd5ccfeed0a' to '{md5}8b833d58c96e34bd94c1cd9b94b0dd24'
==> wbappmachine: Info: /Stage[main]/Puphpet::Nginx::Install/Puphpet::Nginx::Vhosts[from puphpet::nginx::install]/Nginx::Resource::Vhost[nxv_ti6zd07dpuw3]/Concat[/etc/nginx/sites-available/nxv_ti6zd07dpuw3.conf]/File[/etc/nginx/sites-available/nxv_ti6zd07dpuw3.conf]: Scheduling refresh of Class[Nginx::Service]
==> wbappmachine: Info: Concat[/etc/nginx/sites-available/nxv_ti6zd07dpuw3.conf]: Scheduling refresh of Class[Nginx::Service]
==> wbappmachine: Info: Class[Nginx::Service]: Scheduling refresh of Service[nginx]
==> wbappmachine: Notice: /Stage[main]/Nginx::Service/Service[nginx]: Triggered 'refresh' from 1 events
==> wbappmachine: Info: Stage[main]: Unscheduling all events on Stage[main]
==> wbappmachine: Notice: Applied catalog in 14.33 seconds
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what`

**Comment by jtreminio** [comment]
Your machine needs to run an `apt-get update` to refresh apt sources.

This should be happening automatically via `anacron`.
