### ISSUE TITLE
What is the default password for users root and/or nginx (on CentOs)?

### ISSUE THREAD

**Issue by eticdev** [puphpet/puphpet#2706]
I have some important logs that are locked for the nginx or root user, how can I access that on my VM? Looks like the vagrant user doesn't have access to those logs via vagrant ssh.

Thanks for your help.

**Comment by eticdev** [comment]
Anyone?

**Comment by catalinux** [comment]
You should login in the machine with vagrant ssh.

From there you could login as root with 

`sudo -s`

**Comment by eticdev** [comment]
Thanks! I should have known that ;)
