### ISSUE TITLE
Possibility of Using Multiple PHP Versions

### ISSUE THREAD

**Issue by jan-obtam** [puphpet/puphpet#2713]
Hi.

Is it possible to configure PuPHPet to use multiple PHP versions, specifically 5.6 and 7.X.X?

I have multiple projects that I plan to put on the same machine that requires different PHP version.

**Comment by mxkh** [comment]
@jan-obtam Nice point!

I think the best way is the add support of http://virtphp.org/ similar to virtualenv in Python and add the ability to set up not only one PHP version from puphpet configuration.

**Comment by jtreminio** [comment]
You _can_, but not natively through puphpet. This project only supports a single version of PHP per VM, because the PHP project doesn't really make multiple versions easy on a single server.

For that I would recommend Docker, or spinning up multiple VMs.

Sorry and good luck.
