### ISSUE TITLE
'Warning: GettextSetup is not available' after running apt-get upgrade

### ISSUE THREAD

**Issue by hugopeek** [puphpet/puphpet#2717]
I'm using the Ubuntu 14.04 box still and I'm getting these warnings during provisioning, after having done an apt-get update + upgrade inside the machine:

```
==> sakhalin: Warning: GettextSetup is not available, skipping GettextSetup initialization for blackfire.
==> sakhalin: Warning: GettextSetup is not available, skipping GettextSetup initialization for swap_file.
==> sakhalin: Warning: GettextSetup is not available, skipping GettextSetup initialization for php.
==> sakhalin: Warning: GettextSetup is not available, skipping GettextSetup initialization for mysql.
==> sakhalin: Warning: GettextSetup is not available, skipping GettextSetup initialization for stdlib.
==> sakhalin: Warning: GettextSetup is not available, skipping GettextSetup initialization for ntp.
and so on...
```

 Was able to fix this by running:

`sudo /opt/puppetlabs/puppet/bin/gem install gettext-setup`

Found this fix here: https://ask.puppet.com/question/31933/gettextsetup-warnings/

Feel free to close as it's already solved.. But thought I'd just post it anyway for anyone else bumping into it.

**Comment by jtreminio** [comment]
This is a Puppet issue, fixed in current version puphpet installs.

**Comment by aphofstede** [comment]
Can this be patched in older codebases? Can't find a diff/PR about it.
