### ISSUE TITLE
strftime() and setlocale() not working

### ISSUE THREAD

**Issue by Hlsgs** [puphpet/puphpet#2718]
strftime() and setlocale() are not working(everything is output in English always) even though I have both the proper system locales and php_intl installed. Any ideas?

**Comment by fyrye** [comment]
@Hlsgs  What arguments are you specifically using with `setlocale()`?
What does `locale -a` output from ssh console?
What version of PHP and Linux Distribution are you using?
`php_intl` is completely separate from `setlocale()` and is not needed to utilize `setlocale()`.
Lastly what is your `/puphpet/config.yml` settings?
