### ISSUE TITLE
Fixnum warning with Vagrant 2.0.1

### ISSUE THREAD

**Issue by ngocphamm** [puphpet/puphpet#2719]
This is not preventing any vagrant functionalities, I think, but probably would be nice to have fixed. I'm sorry that I don't know anything about Ruby to help with it though :(

`...puphpet/ruby/to_bool.rb:9: warning: constant ::Fixnum is deprecated`

P.S: I just built the configuration from the website, assuming it's the latest version.

**Comment by wunc** [comment]
I'm seeing the same deprecation warning.

**Comment by mans202** [comment]
I'm seeing the same deprecation warning.

**Comment by cmichael-de** [comment]
I'm seeing the same deprecation warning.
Vagrant 2.0.1

**Comment by tomasnorre** [comment]
Don't know if this will help with the fix.. Or at least give an idea on how it can be fixed. 

https://bugs.ruby-lang.org/attachments/5945/unify-fixnum-and-bignum.patch

**Comment by devlamine** [comment]
I'm seeing the same deprecation warning.

**Comment by kielerrr** [comment]
Any workaround for this?

**Comment by cadavre** [comment]
This is just a notice so you don't have to worry. Actually commenting out `class Fixnum` from `puphpet/ruby/to_bool.rb:9` will remove it. I did so and no problems noticed.

**Comment by tomasnorre** [comment]
I can confirm the work-around, but as i'm no Ruby developer as was not sure enough of site effects to suggest it.

**Comment by red-smeg** [comment]
I just changed the line in the code to read Integer instead of Fixnum and it worked fine

**Comment by tomasnorre** [comment]
I can confirm that the switch to Integer works out as well.
