### ISSUE TITLE
Puphpet is dead?

### ISSUE THREAD

**Issue by Carsak** [puphpet/puphpet#2721]
Seems like puhpet not maintined since may 2017.
![image](https://user-images.githubusercontent.com/9497934/32687379-02662988-c6e5-11e7-9378-2743cbcac8a8.png)

**Puphpet is dead?**

**Comment by hotgeart** [comment]
[OFF TOPIC] Do you know an alternative ?

**Comment by tomasnorre** [comment]
"I'm rewriting to ansible! Updates coming soon." 

https://twitter.com/juantreminio/status/934774288678256641

**Comment by Carsak** [comment]
Ansible? But Ansible is huge and clumsy tool for big enterprise solution. Is not it?

**Comment by tomasnorre** [comment]
Not necessarily as I know it, but it's not windows friendly..

**Comment by jtreminio** [comment]
@Carsak reasons are many; biggest is that due to Puppet's immutability, it is not very friendly when interacting with random user-provided data.

Simple example: Having to check all packages to ensure they've not been defined elsewhere.

**Comment by jtreminio** [comment]
Not dead. Rewrite to Ansible cancelled. Onward, ho!

**Comment by Ardakilic** [comment]
@jtreminio Hello, any updates on this? There hasn't been a commit for 1.5 years, can we assume project is dead ?

**Comment by Carsak** [comment]
Maybe it is time to switch to Docker?
Generating php dockerfile with all extensions. Generating all services Nginx,MariaDb,Redis in docker compose file. 
DoPHPer?

**Comment by fnagel** [comment]
Yeah, but Docker is shit when it comes to usability for local development. Especially on Windows.

**Comment by Krienas** [comment]
> Yeah, but Docker is shit when it comes to usability for local development. Especially on Windows.

yep still need VM to run properly on Windows.

**Comment by ikari7789** [comment]
@jtreminio If you don't have time to maintain puphpet anymore, is there anyway that maintenance could be passed off to someone who still has a passion to support this project? Or if you have any alternatives which could replace puphpet?

**Comment by Ardakilic** [comment]
I'm planning to migrate to Docker or Laravel Homestead. From PuPHPet, Laravel Homestead looks that can be migrated with with very minimal hassle.

**Comment by fnagel** [comment]
FYI https://twitter.com/juantreminio/status/1199022035588075520
