### ISSUE TITLE
Refused to connect

### ISSUE THREAD

**Issue by msbir** [puphpet/puphpet#2723]
[config.yaml copy.zip](https://github.com/puphpet/puphpet/files/1467620/config.yaml.copy.zip)

I download a new fresh zip file of the configuration from puphpet.com 
the download was good, no errors.

when trying to access the IP (192.168.56.101). the browser gives me error Refused to connect.
(try to add the IP to the hosts file on my mac, still not working)

attaching the whole config.yaml file

Thank you!

**Comment by jtreminio** [comment]
Please try now. Make sure to access a _vhost_ you've created. If you don't install Apache or Nginx then port 80 may not be opened in firewall.
