### ISSUE TITLE
Does not execute PHP files only shows the content

### ISSUE THREAD

**Issue by gditizio** [puphpet/puphpet#2725]
Hello,
I'm new to this vagrant.

After having downloaded vagrant ver. 2.0.1 and having generated with puphpet a machine for VirtualBox 5.2.2 with Ubuntu 16.04, Apache, PHP 7.1 and MySql 5.7.
Up to here everything ok, the localhost runs well.

but when trying to execute scripts file in PHP, it does not run and only shows the content of the script on the screen.

a file as basic as: infophp.php

```
<?php
    phpinfo();
 ?>
```

it does not run. and it only shows the content of the script.

Any ideas of what is left to do?

**Comment by jtreminio** [comment]
Your Nginx/Apache vhost configs are most likely wrong.

Look at the defaults on puphpet.com and see how it works.

**Comment by HetelSan** [comment]
Hello, I have the same problem and I don't know how to fix it. I have a win10 machine with virtualbox, vagrant and same configuration as ghost above and a nginx as webserver
