### ISSUE TITLE
[QUESTION] How do I exit `vagrant up` from a custom script?

### ISSUE THREAD

**Issue by carlfredrikhero** [puphpet/puphpet#2731]
I want to exit `vagrant up` if a file is missing in my setup script. But `vagrant up` won't exit even if my script contains `exit 1`. It just continues.

To replicate:

Create a script in any of the exec-always/once folder with:

`exit 1`

The script will run but i will not exit.

**Comment by jtreminio** [comment]
We're not doing anything special in the Vagrantfile. This may be a question for Vagrant proper. Sorry!
