### ISSUE TITLE
redirect cycle

### ISSUE THREAD

**Issue by steros** [puphpet/puphpet#2735]
2018/01/22 08:49:14 [error] 10124#10124: *8 rewrite or internal redirection cycle while internally redirecting to "/app.php", client: 192.168.56.1, server: publisher.dev, request: "GET / HTTP/1.1", host: "www.publisher.dev"

Lately puphpet.com creates app.php targets but either in nginx or apache this breaks the server for me.
Why is this done?
I'm using a default configuration created by the wizard. No changes (except ip and server names).

**Comment by jtreminio** [comment]
You must configure the vhosts to your project requirements.

What comes as default works well for Symfony2. Your framework/app of choice should have recommendations.
