### ISSUE TITLE
Mounting event, superviro configs depending on mounted sources

### ISSUE THREAD

**Issue by catalinux** [puphpet/puphpet#2738]
I have some scripts that are run by the supervisord. My problem is that supervisord starts before mounting is done (I use NFS).

Is there a way I cand make superviord restart afters mounting of synced dirs is done?

**Comment by jtreminio** [comment]
No, I don't believe you can control this via Puppet or any config open to puphpet.

May want to move whatever config you're using outside of a shared drive and automatically copy over the file if there's a diff.

**Comment by catalinux** [comment]
Tx. I will try something from here

https://coderwall.com/p/1uwfhw/launch-upstart-services-after-vagrant-mount
http://afterdesign.net/2015/11/20/vagrant-nfs-restarting-services-after-mount.html
