### ISSUE TITLE
Permission denied error with custom document root directory

### ISSUE THREAD

**Issue by codeguy** [puphpet/puphpet#276]
When I `vagrant up` with a pretty standard Puphpet configuration, I get a permissions error that prevents the document root directory from being created. This only happens when I specify a custom document root directory (e.g. "/var/www/public") with the NFS mount at "/var/www". If I use the default document root at "/var/www", I still receive the error when Puppet tries to assign the group to the document root, but it still runs upon completion.

You can see my Hieradata, Vagrantfile, and standard output here:

https://gist.github.com/codeguy/7393092

**Comment by chrisciampoli** [comment]
Could add a before/after snippit on the documentation page you created please?
