### ISSUE TITLE
CentOS 7 Box is returning 404

### ISSUE THREAD

**Issue by kelsey9649** [puphpet/puphpet#2763]
Just grabbed a fresh config. Here is what I get:

`vagrant up
Bringing machine 'centos.lodgable' up with 'virtualbox' provider...
==> centos.lodgable: Box 'bento/centos-7' could not be found. Attempting to find and install...
    centos.lodgable: Box Provider: virtualbox
    centos.lodgable: Box Version: >= 0
The box 'bento/centos-7' could not be found or
could not be accessed in the remote catalog. If this is a private
box on HashiCorp's Atlas, please verify you're logged in via
`vagrant login`. Also, please double-check the name. The expanded
URL and error message are shown below:

URL: ["https://atlas.hashicorp.com/bento/centos-7"]
Error: The requested URL returned error: 404 Not Found

Process finished with exit code 1
`

**Comment by jtreminio** [comment]
You probably need to update Vagrant.

Box locations have moved: https://app.vagrantup.com/bento/boxes/centos-7
