### ISSUE TITLE
Does not execute PHP files only ask for saving

### ISSUE THREAD

**Issue by HetelSan** [puphpet/puphpet#2769]
Hi, I'm on a win10 SO and I have a virtualbox, a vagrant and a phpstorm installed. When I trying to execute a php file on a browser I received a window asking to save. I have followed all instructions on creating this environment and I don't know how to fix it. Any ideas? Thank you.

**Comment by marcosgdf** [comment]
It looks like someone already reported it at #2680

**Comment by HetelSan** [comment]
Marcos, you are right. I'll close this issue soon.
