### ISSUE TITLE
Error: Parameter collate failed on Mysql_database[dbname]: Invalid value ""

### ISSUE THREAD

**Issue by sevmardi** [puphpet/puphpet#2798]
Running a ```vagrant provision``` with this [config.yaml](https://gist.github.com/sevmardi/2ba3cf8a98442a4929d627907add16d4), I get the following error:

``` machine1: Error: Parameter collate failed on Mysql_database[dbname]: Invalid value "". Valid values match /^\S+$/. (file: /tmp/vagrant-puppet/modules-e6a14c6805f458fbb6f6d6d535a2335b/puphpet/manifests/mysql/databases.pp, line: 20  ```

Using: 

VirtualBox version 5.2.12
Vagrant version 2.1.1  

Any ideas?

**Comment by crtl** [comment]
Could you please provide your `config.yaml` file?
Maybe you have an empty database username somewhere inside it.

**Comment by sevmardi** [comment]
Not to be rude - is it just me, or I can see the config.yaml gist in my init post?

**Comment by sevmardi** [comment]
never knew what the problem was.. to fix the problem I had a backup somewhere.
