### ISSUE TITLE
WARNING: Unexpected middleware set after the adapter. This won't be supported from Faraday 1.0.

### ISSUE THREAD

**Issue by andresnijder** [puphpet/puphpet#2812]
I'm trying to create a new Digital Ocean Droplet but it keeps failing. Below you can find the output:

`Bringing machine 'do-vps' up with 'digital_ocean' provider...
==> do-vps: Using existing SSH key: blacture
==> do-vps: Creating a new droplet...
==> do-vps: Assigned IP address: 
WARNING: Unexpected middleware set after the adapter. This won't be supported from Faraday 1.0.
==> do-vps: Destroying the droplet...
/Users/.vagrant.d/gems/2.4.4/gems/vagrant-digitalocean-0.9.3/lib/vagrant-digitalocean/actions/create.rb:63:in 'block in call': not ready (RuntimeError)
	from /opt/vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/lib/vagrant/util/retryable.rb:17:in 'retryable'
	from /Users/.vagrant.d/gems/2.4.4/gems/vagrant-digitalocean-0.9.3/lib/vagrant-digitalocean/actions/create.rb:61:in 'call'
	from /opt/vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/lib/vagrant/action/warden.rb:34:in 'call'
	from /Users/.vagrant.d/gems/2.4.4/gems/vagrant-digitalocean-0.9.3/lib/vagrant-digitalocean/actions/setup_key.rb:33:in 'call'
	from /opt/vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/lib/vagrant/action/warden.rb:34:in 'call'
	from /opt/vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/lib/vagrant/action/warden.rb:95:in 'block in finalize_action'
	from /opt/vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/lib/vagrant/action/warden.rb:34:in 'call'
	from /opt/vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/lib/vagrant/action/builder.rb:116:in 'call'
	from /opt/vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/lib/vagrant/action/runner.rb:66:in 'block in run'
	from /opt/vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/lib/vagrant/util/busy.rb:19:in 'busy'
	from /opt/vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/lib/vagrant/action/runner.rb:66:in 'run'
	from /opt/vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/lib/vagrant/action/builtin/call.rb:53:in 'call'
	from /opt/vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/lib/vagrant/action/warden.rb:34:in 'call'
	from /opt/vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/lib/vagrant/action/builtin/config_validate.rb:25:in 'call'
	from /opt/vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/lib/vagrant/action/warden.rb:34:in 'call'
	from /opt/vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/lib/vagrant/action/builder.rb:116:in 'call'
	from /opt/vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/lib/vagrant/action/runner.rb:66:in 'block in run'
	from /opt/vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/lib/vagrant/util/busy.rb:19:in 'busy'
	from /opt/vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/lib/vagrant/action/runner.rb:66:in 'run'
	from /opt/vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/lib/vagrant/machine.rb:239:in 'action_raw'
	from /opt/vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/lib/vagrant/machine.rb:208:in 'block in action'
	from /opt/vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/lib/vagrant/environment.rb:598:in 'lock'
	from /opt/vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/lib/vagrant/machine.rb:194:in 'call'
	from /opt/vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/lib/vagrant/machine.rb:194:in 'action'
	from /opt/vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/lib/vagrant/batch_action.rb:82:in 'block (2 levels) in run'`

**Comment by andresnijder** [comment]
sollution: check your ssh key. needs to be a valid format

**Comment by glmrenard** [comment]
I've the same problem and my ssh key are correct. If I ctrl+c vagrant after I get the IP, I'm able to vagrant ssh successfully.
