### ISSUE TITLE
Apache2, PHP7.2-FPM in Ubuntu 16.04 for Symfony3.x not working

### ISSUE THREAD

**Issue by william-greatcontent** [puphpet/puphpet#2815]
Hello,

I am a very big fan of Puphpet. I am using puphpet for quite a long time. Recently, i started one of my own projects with Symfony3.4 & MySQL. So, i spawn up a virtual machine using puphpet. I choose Apache2, PHP7.2, MySQL in Ubuntu16.04 with Virtualbox. My host machine is Mac. After i up the server, i did setup apache2 vhost for the symfony3.4 project. The problem is, its showing whole PHP code rather than executing them. I tried to google and find a cure to this problem but failed. Never faced this kind of issue before. Am i doing something wrong? Please let me know if you need any input from my end.

**Comment by kbitoon** [comment]
got same issue? any updates?

**Comment by william-greatcontent** [comment]
hi @kbitoon, figured out that it was an issue with Vhost config. I created another machine with Nginx and applied this Vhost config and it solved my problem.
https://stackoverflow.com/questions/25469569/the-php-file-is-download-instead-execute-on-nginx

Let me know if that helped. :)
