### ISSUE TITLE
Request: Add a section for executing custom commands post setup

### ISSUE THREAD

**Issue by awildeep** [puphpet/puphpet#283]
It would be very cool to be able to issue commands after the server is considered finished from the current Puphpet builds.

For instance you may want to grab code from a repository, or run a composer command, or run a server side script.

Ideally a user would be able to add multiple custom commands, and have them ordered.

**Comment by neohunter** [comment]
Why to add a custom line each time? why dont have this line added by default?

why dont create a wiki page with this?

I've searched for this for about 2 hours.
