### ISSUE TITLE
Nginx - suggesting change default buffers size

### ISSUE THREAD

**Issue by lukaszwit** [puphpet/puphpet#290]
I'm suggesting to change default proxy buffers size in /etc/nginx/conf.d/proxy.conf to:
proxy_buffer_size   128k;
proxy_buffers   4 256k;
proxy_busy_buffers_size   256k;

which prevents "upstream sent too big header while reading response header" error

**Comment by Michal-sk** [comment]
Why not added the proxy_busy_buffers_size ? Im getting this error now:
nginx: [emerg] "proxy_busy_buffers_size" must be less than the size of all "proxy_buffers" minus one buffer in /etc/nginx/nginx.conf:39
