### ISSUE TITLE
Apache user and group permissions

### ISSUE THREAD

**Issue by colby-swandale** [puphpet/puphpet#321]
At the moment anything shared to the VM is owned by vagrant:vagrant. Apache is running as www-data:www-data so php can't write to disk unless i change the it from www-data:www-data to vagrant:vagrant.

Would it be suitable to either add vagrant to the www-data group or change apache running as www-data to vagrant in puppet?

**Comment by dvanactka** [comment]
Could someone explain what the status of this currently is?  Can we specify `mount_options` in `config.yaml` as @kostajh does above?  Or does this need to be set in `Vagrantfile`?

**Comment by oflannabhra** [comment]
I'd also like to be able to do this in the `config.yml`

**Comment by AlyssonNeto** [comment]
on my vagrant box, but when i tried to synced the /opt/odoo with my machine i get internal server error.

default config, run odoo whithou any problem and i have the folder /opt/odoo ok
 config.vm.synced_folder "./", "/vagrant", type: "nfs"

change for this not running the aplication and the folder /opt/odoo dosent exist
 config.vm.synced_folder "./", "/opt/odoo", type: "nfs"nt,
