### ISSUE TITLE
root password  Debian Wheezy 7.2 x64 - Virtualbox 4.3 

### ISSUE THREAD

**Issue by szaman0** [puphpet/puphpet#323]
What is root password on Debian Wheezy 7.2 x64 - Virtualbox 4.3 box ?

Thank for help

**Comment by inoas** [comment]
I could not run
$ `sudo echo 1 > /proc/sys/vm/drop_caches`
Still said:
$ `-bash: /proc/sys/vm/drop_caches: Permission denied`

Running just `su` and supplying `vagrant` as password did not work.
Running `sudo su && echo 1 > /proc/sys/vm/drop_caches` worked (keep in mind you are then root, still)
