### ISSUE TITLE
Suggestion: nginx vhost rewrite rules

### ISSUE THREAD

**Issue by Xlator** [puphpet/puphpet#342]
Some frameworks (notably Laravel since the recent upgrade to 4.1) require rewrite rules on the server config level. It would be nice to be able to create these with puphpet. I've added the necessary directive in my fork of the puppet-nginx module.

Xlator/puppet-nginx@9cf83116ec21b9932df7621811f6ae9fe88b771a
Xlator/puppet-nginx@f168cf09f907744cdeccfc4e6ef4bd578e346eae

**Comment by kanariezwart** [comment]
:+1:

**Comment by gsdevme** [comment]
This would be really nice, for now I setup a simple exec_once for Smyfony2. Might be worth just replacing the whole file really but for me its ok for now.

```
#!/bin/sh

# Make sure only root can run our script
if [ "$(id -u)" != "0" ]; then
   echo "This script must be run as root" 1>&2
   exit 1
fi

# Symfony 2 try_files on location /
sed -i -e 's/try_files $uri $uri\/ index.php \/index.php$is_args$args;/try_files $uri \/app_dev.php$is_args$args;/g' /etc/nginx/sites-available/*dev.conf
```

**Comment by donaldallen** [comment]
I modified this to support multiple rewrites: 66de6a8d8600821fbfc91a7f8ab5bd43ad5796da
