### ISSUE TITLE
Multi vms setup

### ISSUE THREAD

**Issue by lorenzomar** [puphpet/puphpet#367]
Could be useful to allow a multi vms setup. In this way it is possible to setup a cluster of server and a cluster of db for example.

**Comment by jeremyzahner** [comment]
Hi Guys!

Any updates here?

**Comment by kanariezwart** [comment]
@jeremyzahner this approach that I started, it worked as a concept (see the above transcript). I think the idea could still be reused. But in all honesty should be given a lot of more time and thought (conflicting ports, host resource assignments). Maybe @jtreminio can help us out a bit?
Although I won't be able to do work on that within the next 2 month or so. :hourglass_flowing_sand:
