### ISSUE TITLE
Add support for custom Vagrant boxes

### ISSUE THREAD

**Issue by jtreminio** [puphpet/puphpet#40]
Currently PuPHPet enforces the use of the official Vagrant Ubuntu-based box files.

Many people may not be too thrilled with idea of using Ubuntu on VM, they may want to enter in their own box URL.

Problem: we currently do not support non-Debian based OS. We can either tackle this easy problem and warn the user first, or tackle the harder problem of making the vagrant code work with either OS.

Related to https://github.com/puphpet/vagrant-puppet-lamp/issues/5

**Comment by NoelDavies** [comment]
@jtreminio, that's all well and good, but the disks are only 20GB by default, nowhere near big enough for large projects.

**Comment by jtreminio** [comment]
@NoelDavies, if you want to set your own box url you can create a `config-custom.yaml` and overwrite it in there.

**Comment by NoelDavies** [comment]
@jtreminio I understand that, but how do you specify a local version of that box?
