### ISSUE TITLE
phpmyadmin - # 1146 – Table ‘phpmyadmin.pma_table_uiprefs’ doesn’t exist

### ISSUE THREAD

**Issue by ricfrank** [puphpet/puphpet#415]
Hi.

After vagrant provisioning, i go to http://IP_ADDR/phpmyadmin, i logged in like root and when i try to access to any table, i've this problem:
#1146 – Table ‘phpmyadmin.pma_table_uiprefs’ doesn’t exist

Phpmyadmin tables come not loaded. The script that contains needed sql code to create these tables doesn't exist in phpmyadmin folder.

Generally: phpmyadmin/example/create_tables.sql or phpmyadmin/scritps/create_tables.sql.

thanks.

ric.

**Comment by steefaan** [comment]
This post is closed for a long time but if someone is still interested in...

Create the file `puphpet/files/exec-once/phpmyadmin.sh` with the following content:

```
#!/bin/bash

export DEBIAN_FRONTEND=noninteractive

echo 'phpmyadmin phpmyadmin/dbconfig-reinstall boolean true' | debconf-set-selections
echo 'phpmyadmin phpmyadmin/mysql/admin-pass password {MYSQL_ROOT_PASSWORD}' | debconf-set-selections
echo 'phpmyadmin phpmyadmin/reconfigure-webserver multiselect apache2' | debconf-set-selections

dpkg-reconfigure phpmyadmin
```

Replace `{MYSQL_ROOT_PASSWORD}` with the password from your `config.yml` file. Is it possible to take the value from `config.yml` as a variable in my .sh file?
