### ISSUE TITLE
manifest.pp - where are the puphpet params defined $puphpet::params::apache_webroot_location

### ISSUE THREAD

**Issue by jackblackCH** [puphpet/puphpet#420]
Can anybody tell me where the data of line 221 -223 comes from?

```
include puphpet::params // I can neither see a file nor anything else
$webroot_location = $puphpet::params::apache_webroot_location
```

`$puphpet::params::apache_webroot_location // where are those puphpet params defined ???`

**Comment by jonnywhite** [comment]
The reference to $puphpet::params::apache_webroot_location no longer exists in 
https://github.com/puphpet/puppet-puphpet/blob/master/manifests/params.pp#L13

Now when I run provision I get:
Error: Parameter path failed on File[undef]: File paths must be fully qualified, not 'undef' at /tmp/vagrant-puppet-3/manifests/manifest.pp:294

Should this line:
$webroot_location = $puphpet::params::apache_webroot_location
now point somewhere else?

**Comment by jtreminio** [comment]
Sorry @jonnywhite you have an extremely old version of puphpet.

Sounds like your manifest is old enough that it's downloading puppet modules on each `$ vagrant provision`, too.

What you want to do is find the file `Puppetfile`, find the line `mod 'puphpet/puphpet',` and change the ref to `5b512861`

**Comment by jonnywhite** [comment]
@jtreminio it seemed to work again when I updated my manifest.pp to 

    include puphpet::params
    include puphpet::apache::params
    $webroot_location = $puphpet::apache::params::default_vhost_dir

The closest line I have in my puppetfile is this:

    mod 'puphpet', :git => 'https://github.com/puphpet/puppet-puphpet.git'

Is that the line you are referring to?

**Comment by jtreminio** [comment]
@jonnywhite it's changed since then hehe.

For the future you can set a reference as:

`mod 'puphpet', :git => 'https://github.com/puphpet/puppet-puphpet.git', :ref => '5b512861 '`

**Comment by jonnywhite** [comment]
@jtreminio Thanks for your help.

I have puppet 3.4.2 and Vagrant 1.6.5. I'm not sure what version of puphpet I'm using (although it has stopped working since I added the ", :ref => '5b512861'" as I guess it's now all out of synch.

Is there any way to stay with the old versions? It all was working well for us, but I don't know how to force new installs to use the old versions of puppet and puphpet. Do you know if this is possible?

**Comment by jonnywhite** [comment]
It looks like I need V1 of this: https://atlas.hashicorp.com/puphpet/boxes/ubuntu1204-x64/versions/1.0
Do you know if this is still available or can I specify a version in my config.yaml?

**Comment by intrepidws** [comment]
Any luck here? I'm having the same problem.
