### ISSUE TITLE
add mount_options ["dmode=777","fmode=666"]

### ISSUE THREAD

**Issue by surenrao** [puphpet/puphpet#443]
Laravel framework has a storage folder which needs proper permission
Can you add mount_options so i dont have to manually add it?

config.vm.synced_folder "#{folder['source']}", "#{folder['target']}", id: "#{folder['id']}", type: nfs,:mount_options => ["dmode=777","fmode=666"]

**Comment by Spriz** [comment]
@jtreminio - is it hardcoded to be 775 and 764 now? :disappointed:

**Comment by vonZnotz** [comment]
Vote for mount_options! I think there are no problems at the moment, but this won't look like in the production environment.

**Comment by nielsvermaut** [comment]
+1

**Comment by karaoak** [comment]
+1

**Comment by gkatsanos** [comment]
Can we add mount_options to nfs sync type and change owner as well as permissions?

**Comment by aalinia** [comment]
+1
