### ISSUE TITLE
Building with CentOS, lots of issues

### ISSUE THREAD

**Issue by fabioneves** [puphpet/puphpet#504]
Hello,

I'll list the issues I have if I choose CentOS Box (which I prefer):
1- httpd won't start after the VM is booted
2- the provision won't finish if you choose SPDY module
3- the provision won't finish if you choose geoip module
4- the provision won't finish if you choose pagespeed module
5- the provision won't finish if you choose mailcatcher module

There's a lot of warnings/errors when you end the vagrant up command. I'm not sure if they interfere with the box setup, but anyway I'm just saying.

Thanks

**Comment by jtreminio** [comment]
Apache has been completely refactored via 8525b77986f7b971c4992b249b2706cc4f0e8fde

Note: `mod_php` support has been completely dropped, but your configs are now infinitely more customizable.
