### ISSUE TITLE
Warning: Could not retrieve fact fqdn

### ISSUE THREAD

**Issue by enrique-ibarra** [puphpet/puphpet#507]
After doing a `vagrant up` this morning using a new configuration, I got stuck with this error:

> Finished installing librarian-puppet
> Running initial librarian-puppet
> Finished running initial librarian-puppet
> Replacing puppetlabs-git module with custom
> Cloning into '/etc/puppet/modules/git'...
> Finished replacing puppetlabs-git module with custom
> [default] Running provisioner: puppet...
> Running Puppet with manifest.pp...
> stdin: is not a tty
> Info: Loading facts in /etc/puppet/modules/rabbitmq/lib/facter/rabbitmq_erlang_cookie.rb
> Info: Loading facts in /etc/puppet/modules/php/lib/facter/php_fact_extension_dir.rb
> Info: Loading facts in /etc/puppet/modules/php/lib/facter/php_fact_version.rb
> Info: Loading facts in /etc/puppet/modules/git/lib/facter/git_exec_path.rb
> Info: Loading facts in /etc/puppet/modules/git/lib/facter/git_version.rb
> Info: Loading facts in /etc/puppet/modules/composer/lib/facter/composer_home.rb
> Info: Loading facts in /etc/puppet/modules/staging/lib/facter/staging_windir.rb
> Info: Loading facts in /etc/puppet/modules/staging/lib/facter/staging_http_get.rb
> Info: Loading facts in /etc/puppet/modules/puppi/lib/facter/puppi_projects.rb
> Info: Loading facts in /etc/puppet/modules/puppi/lib/facter/last_run.rb
> Info: Loading facts in /etc/puppet/modules/concat/lib/facter/concat_basedir.rb
> Info: Loading facts in /etc/puppet/modules/stdlib/lib/facter/pe_version.rb
> Info: Loading facts in /etc/puppet/modules/stdlib/lib/facter/puppet_vardir.rb
> Info: Loading facts in /etc/puppet/modules/stdlib/lib/facter/root_home.rb
> Info: Loading facts in /etc/puppet/modules/stdlib/lib/facter/facter_dot_d.rb
> Warning: Could not retrieve fact fqdn
> Error: No title provided and :package is not a valid resource reference at /tmp/vagrant-puppet-1/manifests/manifest.pp:633 on node precise64
> Wrapped exception:
> No title provided and :package is not a valid resource reference
> Error: No title provided and :package is not a valid resource reference at /tmp/vagrant-puppet-1/manifests/manifest.pp:633 on node precise64
> The following SSH command responded with a non-zero exit status.
> Vagrant assumes that this means the command failed!
> FACTER_ssh_username='vagrant' puppet apply --verbose --hiera_config /vagrant/puphpet/puppet/hiera.yaml --parser future --manifestdir /tmp/vagrant-puppet-1/manifests --detailed-exitcodes /tmp/vagrant-puppet-1/manifests/manifest.pp || [ $? -eq 2 ]

does anyone have the same issue?

**Comment by dvanactka** [comment]
This is 1 of 2 issues for a basic Centos installation at:  https://github.com/puphpet/puphpet/issues/1335
