### ISSUE TITLE
Ubuntu Precise still uses PHP 5.3

### ISSUE THREAD

**Issue by t0xicCode** [puphpet/puphpet#555]
This is a follow up to #398 . Some of us still need to develop against PHP 5.3, and in Ubuntu Precise, only 5.3 is available in the [default repositories](http://packages.ubuntu.com/search?suite=precise&searchon=names&keywords=php5). 
It installs correctly, and it is still supported by canonical.

/cc @jasonwilk

**Comment by LuanComputacao** [comment]
+1
