### ISSUE TITLE
Nginx 502 errors from too-big header

### ISSUE THREAD

**Issue by markjaquith** [puphpet/puphpet#576]
If you have a lot of PHP warnings or notices, Nginx can crap out like so:

```
*48 upstream sent too big header while reading response header from upstream, client: 192.168.82.1, server: example.com, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "example.com"
```

The fix is to add this to the nginx config:

```
fastcgi_buffers 16 16k;
fastcgi_buffer_size 32k;
```

**Comment by darnold** [comment]
Sorry to come back to this old thread but it helped solve my problem. I'm using windows 10, virtualbox, ubuntu1604-x64, niginx, php5.6 or 7. When I create a fresh nginx machine I always have to change proxy_buffers and proxy_buffer_size in proxy.conf to fastcgi_. If I don't change them I get 502 gateway errors when submitting any type of form/POST.  I tried researching it out but I can't see why it only works with fastcgi_ and not proxy_. Any ideas?

**Comment by cobhimself** [comment]
I second @darnold's comment. proxy_* does not seem to work the same as fastcgi_*.

When attempting to modify my config.yaml to be fastcgi_ instead of proxy_, Class[Nginx] barks at me that there are no parameters named fastcgi_buffers and fastcgi_buffer_size.

Is there a way to specify the fastcgi parameters in my config.yaml file?

**Comment by grantlucas** [comment]
For those, like myself, that ended up here since I *really* needed `fastcgi_buffer_size`, I ended up adding a script to `puphpet/files/exec-always/` with the following contents. Name the file whatever you want with a `.sh` file extension.

```
FILE="/etc/nginx/conf.d/fastcgi_buffers.conf"
rm $FILE
touch $FILE
echo "fastcgi_buffers 16 16k;" >> $FILE
echo "fastcgi_buffer_size 32k;" >> $FILE

systemctl restart nginx
```
