### ISSUE TITLE
MySQL SSH Tunnel

### ISSUE THREAD

**Issue by mcampo84** [puphpet/puphpet#604]
I recently installed a Vagrant instance using puphpet and I'm unable to access my database through Navicat. In the SSH connection properties I enter the Vagrant hostname, Port 22, Username (vagrant), and Password (vagrant).

Local database properties are also set up correctly.

When I test the connection, Navicat returns the following error: "Connection failed: Password authentication failed."

What might I be doing wrong?

**Comment by Dobby89** [comment]
@jtreminio I can connect by SSH fine through WinSCP using the private key. But I can't connect to the database using Navicat. Am I missing something?

**Comment by stevieg83** [comment]
@Dobby89 there's an issue with Navicat - I have the same issue. Works fine with Sequel Pro.
