### ISSUE TITLE
PHP5 FPM + Nginx socket issue

### ISSUE THREAD

**Issue by jrdnrc** [puphpet/puphpet#715]
Hi,

I installed a DigitalOcean machine with PHP5 FPM and Nginx. Whenever I try to access the server, I get a '502 bad gateway', and an error message in the Nginx access logs as follows:

```
2014/05/07 09:24:35 [crit] 4991#0: *1 connect() to unix:/var/run/php5-fpm.sock failed (13: Permission denied) while connecting to upstream, client: 37.139.2.9, server: jrdn.dev, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "jrdn.dev"
```

I've worked out that I can solve this issue by editing `/etc/php5/fpm/pool.d/www-data`, and changing `;listen.mode = 0660` to `listen.mode = 0666` and that seems to work. However, I think this should work out of the box, and I can't figure out a way to pass that to the configuration when setting up the box on puphpet.com.

**Comment by juan88** [comment]
Hi, I am having some issues related to this I think and I cannot fix them.

I'm experiencing issues to write files from the webserver (using php-fpm and nginx). I tried what is described here and the framework I'm using cannot create files somehow. I set the permissions manually to those folders but yet nginx cannot write to them somehow. 

Tried tweaking the www.conf in php-fpm uncommenting those lines and changing the permissions of the listen.mode but still I am unable to make it work. 

For the record I had apache2 working in the same project flawlessly. Everything happened after switching to nginx. Any ideas? Thanks!
