### ISSUE TITLE
[feature request] add support for other locales

### ISSUE THREAD

**Issue by mrbase** [puphpet/puphpet#798]
it would be nice to be able to set other locales than en_US

**Comment by jtreminio** [comment]
Closed by 6a4308b0397e3c8cc1d33bd05557339b6c353e7c

Just add a `locales` key to config.yaml

I should look like

    locales:
        default_value: en_US.UTF-8
        available:
            - en_US.UTF-8 UTF-8
            - en_GB.UTF-8 UTF-8
