### ISSUE TITLE
Error: Cannot create /var/www/html; parent directory /var/www does not exist

### ISSUE THREAD

**Issue by surenrao** [puphpet/puphpet#831]
I created a manifest today (Jun/15/2014) and i still get  "parent directory /var/www does not exist" when i use nginx
yaml config: http://pastebin.com/0HFpDh5u

stdin: is not a tty
Warning: Could not retrieve fact fqdn
Error: Cannot create /var/www/html; parent directory /var/www does not exist
Error: /Stage[main]/Main/File[/var/www/html]/ensure: change from absent to directory failed: Cannot create /var/www/html; parent directory /var/www does not exist
Warning: /Stage[main]/Main/File[/var/www/html/beanstalk_console/storage.json]: Skipping because of failed dependencies
Warning: /Stage[main]/Puphpet::Adminer/File[/var/www/html/adminer]: Skipping because of failed dependencies
Warning: /Stage[main]/Puphpet::Adminer/Exec[download adminer to /var/www/html/adminer]: Skipping because of failed dependencies

**Comment by MPParsley** [comment]
Shouldn't this be fixed for Apache as well?

```==> default: Error: Cannot create /var/www/html/adminer; parent directory /var/www/html does not exist
==> default: Error: /Stage[main]/Puphpet::Adminer/File[/var/www/html/adminer]/ensure: change from absent to directory failed: Cannot create /var/www/html/adminer; parent directory /var/www/html does not exist
==> default: Notice: /Stage[main]/Puphpet::Adminer/Exec[download adminer to /var/www/html/adminer]: Dependency File[/var/www/html/adminer] has failures: true
==> default: Warning: /Stage[main]/Puphpet::Adminer/Exec[download adminer to /var/www/html/adminer]: Skipping because of failed dependencies
```
