### ISSUE TITLE
Error: Could not back up files of type socket

### ISSUE THREAD

**Issue by andersonamuller** [puphpet/puphpet#835]
I'm always getting this error when I try to provision a VM already created.

```
/Stage[main]/Main/File[/var/run/mysqld/mysqld.sock]/ensure: change from socket to file failed: Could not back up files of type socket
```

**Comment by yellow1912** [comment]
Same here with MariaDB

**Comment by mrconnerton** [comment]
Ditto for mariaDB

**Comment by lucacri** [comment]
+1 for me too with MariaDB

**Comment by exuperok** [comment]
+ 1 with mariadb as well

**Comment by WebDevTmas** [comment]
+1 for mariaDB here as well, anybody got a work around for now?

**Comment by Greg-Boggs** [comment]
Not yet, but I did flag the attention of the Mariadb team on Twitter to this issue.

**Comment by ikari7789** [comment]
Have you considered either of these puppet modules listed on the [MariaDB website] (https://mariadb.com/kb/en/mariadb/puppet-and-mariadb/)?
https://github.com/KrisBuytaert/puppet-mariadb
https://github.com/rgevaert/puppet-mysql

**Comment by ikari7789** [comment]
I re-added MariaDB back to a newly made PuPHPet download.
CentOS 6 x64
It installed and setup without problem.
Perhaps the problem lies in which OS is used.
I think it was premature to completely remove it.
The puppetlabs-mysql module is supposed to support MariaDB as well, why not open an issue over there?

**Comment by CWSpear** [comment]
@ikari7789 did you try to provision an existing box? That's where the main issue is at. i.e.:

```bash
vagrant up # wait for it succeed...
vagrant provision # <-- this will fail
```

**Comment by ikari7789** [comment]
Oh! I skipped over that. I see now. Either way, this should be brought to the attention of the puppetlabs-mysql repository rather than here in my opinion.

**Comment by CWSpear** [comment]
@ikari7789 [puppetlabs/puppetlabs-mysql](https://github.com/puppetlabs/puppetlabs-mysql/) seems to have opted out of the issue tracker on GitHub. It does not allow you to leave issues against that repo.

You could open one on their JIRA, though: https://jira.puppetlabs.com/browse/MODULES/?selectedTab=com.atlassian.jira.jira-projects-plugin:summary-panel
