### ISSUE TITLE
New option in languages module for PHP - Compile from source

### ISSUE THREAD

**Issue by jeremygiberson** [puphpet/puphpet#840]
Some PHP extensions can only be installed if PHP is build with certain compile options. For example, PECL's pthreads extension requires PHP built with ZTS (thread safe) compile option. 

A compile from source option in the language module would let the user specify compile options (much like how extensions can be specified). These options will drive building PHP from source during provisioning.

**Comment by umbertix** [comment]
Hi @jtreminio,

First of all thanks for this great tool. I was trying to set my environment with a compiled thread safe php, but so far I haven't been able to get it running. Have you got any suggestion about it?

Regards, and thx again for this great job.
