### ISSUE TITLE
Duplicate Declaration: Mysql_user[root@localhost]

### ISSUE THREAD

**Issue by alejandronanez** [puphpet/puphpet#878]
Hello, I'm running `vagrant up` from a just downloaded puphpet.zip file and I'm getting this

`Error: Duplicate declaration: Mysql_user[root@localhost] is already declared in file /tmp/vagrant-puppet-3/modules-0/mysql/manifests/server/root_password.pp:8; cannot redeclare at /tmp/vagrant-puppet-3/modules-0/mysql/manifests/db.pp:35 on node packer-virtualbox-iso.vagrantup.com`

Any ideas about why this is happening?

It's happening with Debian / Ubuntu boxes.

Thanks.

**Comment by Aiglobelam** [comment]
DOH! same mistake...

**Comment by renegaed** [comment]
same mistake : (

**Comment by ahsanatiq** [comment]
same mistake by me too ... *face palm*

**Comment by MLoureiro** [comment]
+1 ¬¬
