### ISSUE TITLE
Parallels/Debian x64 is unusable

### ISSUE THREAD

**Issue by itsthinking** [puphpet/puphpet#905]
I can do the simplest of configurations and it'll always spit out varying errors, the latest is:

Bringing machine 'default' up with 'parallels' provider...
==> default: Box 'puphpet/ubuntu1204-x64' could not be found. Attempting to find and install...
    default: Box Provider: parallels
    default: Box Version: >= 0
==> default: Loading metadata for box 'puphpet/ubuntu1204-x64'
    default: URL: https://vagrantcloud.com/puphpet/ubuntu1204-x64
==> default: Adding box 'puphpet/ubuntu1204-x64' (v1.2) for provider: parallels
    default: Downloading: https://vagrantcloud.com/puphpet/ubuntu1204-x64/version/2/provider/parallels.box
The box you attempted to add doesn't match the provider you specified.

Provider expected: parallels
Provider of box: vmware_desktop

...Que?

With that said, thank you for the continuation of PuPHPet work, a lot of co-workers are now using it. I may have to stick with the VirtualBox configs for now.

**Comment by tkvern** [comment]
I have the same problem.
Who can fix it?
