### ISSUE TITLE
Diferent Vagrant Providers 

### ISSUE THREAD

**Issue by sebathi** [puphpet/puphpet#931]
We use different Vagrant Providers on different environments (virtualbox on windows, vmware workstation on windows, vmware_fusion on osx, etc).

In the current vagrant file the provider is over the config.yaml file and it does not depend on environment of the Host machine. (VAGRANT_DEFAULT_PROVIDER). 

Maybe use config.vm.provider instead of the one in config.yaml?

**Comment by jtreminio** [comment]
Closed by cfa076ddd42f27627e6c94802ae450a14237cc3c
