### ISSUE TITLE
Duplicate SSH key on DigitalOcean

### ISSUE THREAD

**Issue by vlucas** [puphpet/puphpet#934]
I already have my SSH key on DigitalOcean, and I ran into the error:

```
==> default: Creating new SSH key: Vagrant...
There was an issue with the request made to the Digital Ocean
API at:

Path: /v2/account/keys
URI Params: {:name=>"Vagrant", :public_key=>"ssh-rsa blahblahblah..."}

The response status from the API was:

Status: 422
Response: {"id"=>"unprocessable_entity", "message"=>"SSH Key is already in use on your account"}
```

If the SSH key already exists, setup of the vagrant box should continue because it already has the access it requires.

Is there a way to disable the creation of this SSH key until the issue is resolved?

**Comment by agungsijawir** [comment]
If anyone encounter this problem, please delete old SSH keys from this page:
https://cloud.digitalocean.com/settings/security

and re-run the command.

**Comment by PaulKLeasure** [comment]
Using   ##  provider.ssh_key_name   to **match the key name** to the one **existing** in my digitalocean account **worked** for me.

**Comment by richardstobart** [comment]
If you're following the https://www.digitalocean.com/community/tutorials/how-to-use-the-digitalocean-api-v2-with-ansible-2-0-on-ubuntu-16-04, you will need to replace the `name=my_ssh_key` line with `name=[your key name]`

**Comment by dkarter** [comment]
@richardstobart Thanks for posting this, but it didn't work for me. Do I need to say something like:

```yaml
    - name: ensure key exists at DigitalOcean
      digital_ocean: >
        state=present
        command=ssh
        name=id_rsa
        ssh_pub_key={{ lookup('file', '~/.ssh/id_rsa.pub') }}
        api_token={{ do_token }}
      register: my_ssh_key
```

or am I missing something here?

**Comment by richardstobart** [comment]
Dorian,

I have a separate task:
- name: ensure key exists at DigitalOcean
    digital_ocean: >
      state=present
      command=ssh
      name=billy.bob
      ssh_pub_key={{ lookup('file', '~/.ssh/id_rsa.pub') }}
      api_token={{ do_token }}
    register: my_ssh_key

and then

      ssh_key_ids={{ my_ssh_key.ssh_key.id }}
