### ISSUE TITLE
Error: Failed to set group to '33': Operation not permitted - /var/www and Warning: Could not retrieve fact fqdn

### ISSUE THREAD

**Issue by therobyouknow** [puphpet/puphpet#940]
puphpet.com downloaded 2014-08-01 Ubuntu 12.04 LTS, NFS option selected, nothing else selected (i.e. no rabbitmq, no mailcatcher etc) just added an extra local site and database (in addition to the supplied default awesome).

==> default: Error: Failed to set group to '33': Operation not permitted - /var/www
==> default: Error: /Stage[main]/Main/File[/var/www]/group: change from apache to www-data failed: Failed to set group to '33': Operation not permitted - /var/www
==> default: Notice: /Stage[main]/Main/File[/var/www]/mode: mode changed '0755' to '0775'
==> default: Notice: /Stage[main]/Main/File[/var/www/default]: Dependency File[/var/www] has failures: true
==> default: Warning: /Stage[main]/Main/File[/var/www/default]: Skipping because of failed dependencies
==> default: Notice: /Stage[main]/Main/User[www-data]/shell: shell changed '/bin/sh' to '/bin/bash'
==> default: Notice: /Stage[main]/Main/User[www-data]/groups: groups changed '' to 'www-data'
==> default: Notice: /Stage[main]/Main/File[/var/lib/php/session]/owner: owner changed 'root' to 'www-data'
==> default: Notice: /Stage[main]/Main/File[/var/lib/php/session]/group: group changed 'root' to 'www-data'
==> default: Notice: /Stage[main]/Main/Exec[exec mkdir -p /var/www/sodrupal.localvm @ key kXs3BcpVp7SJ]/returns: executed successfully
==> default: Notice: /Stage[main]/Main/File[/var/www/sodrupal.localvm]: Dependency File[/var/www] has failures: true
==> default: Warning: /Stage[main]/Main/File[/var/www/sodrupal.localvm]: Skipping because of failed dependencies
==> default: Notice: /Stage[main]/Main/Apt::Key[4CBEDD5A]/Exec[54dfe9bb2c937fa96f3b08d0dffede45f05e7e7c]/returns: executed successfully
==> default: Notice: /Stage[main]/Main/Exec[exec mkdir -p /var/www/awesome @ key WiTpty6FbDiS]/returns: executed successfully
==> default: Notice: /Stage[main]/Main/File[/var/www/awesome]: Dependency File[/var/www] has failures: true
==> default: Warning: /Stage[main]/Main/File[/var/www/awesome]: Skipping because of failed dependencies
==> default: Notice: /Stage[main]/Main/Group[puppet]/ensure: created
==> default: Notice: /Stage[main]/Main/Apt::Key[4F4EA0AAE5267A6C]/Exec[d613ae0061ccb8f97c6e217d344953b229bb8032]/returns: executed successfully

Notice: /Stage[main]/Main/Puphpet::Php::Ini[cgi.fix_pathinfo]/File[/etc/php5/fpm/conf.d/zzzz_custom.ini]/ensure: created
Notice: /Stage[main]/Main/Puphpet::Php::Ini[cgi.fix_pathinfo]/File[/etc/php5/cli/conf.d/zzzz_custom.ini]/ensure: created
Notice: /Stage[main]/Main/Puphpet::Php::Ini[cgi.fix_pathinfo]/Php::Augeas[CUSTOM/cgi.fix_pathinfo-0]/Augeas[php_ini-CUSTOM/cgi.fix_pathinfo-0]/returns: executed successfully
Info: Php::Augeas[CUSTOM/cgi.fix_pathinfo-0]: Scheduling refresh of Service[php5-fpm]
Info: Php::Augeas[CUSTOM/session.save_path-/var/lib/php/session]: Scheduling refresh of Service[php5-fpm]
Notice: /Stage[main]/Main/Puphpet::Php::Ini[display_errors]/Php::Augeas[CUSTOM/display_errors-true]/Augeas[php_ini-CUSTOM/display_errors-true]/returns: executed successfully
Info: Php::Augeas[CUSTOM/display_errors-true]: Scheduling refresh of Service[php5-fpm]
Notice: /Stage[main]/Php::Devel/Package[php5-dev]/ensure: ensure changed 'purged' to 'present'
Notice: /Stage[main]/Main/Php_pecl_mod[pecl_http]/Puphpet::Php::Pecl[pecl_http]/Php::Pecl::Module[pecl_http]/Exec[pecl-pecl_http]/returns: executed successfully
Notice: /Stage[main]/Main/Php_mod[mcrypt]/Puphpet::Php::Module[mcrypt]/Php::Module[mcrypt]/Package[PhpModule_mcrypt]/ensure: ensure changed 'purged' to 'present'
Info: /Stage[main]/Main/Php_mod[mcrypt]/Puphpet::Php::Module[mcrypt]/Php::Module[mcrypt]/Package[PhpModule_mcrypt]: Scheduling refresh of Service[php5-fpm]
Notice: /Stage[main]/Main/Php::Module[mysqlnd]/Package[PhpModule_mysqlnd]/ensure: ensure changed 'purged' to 'present'
Info: /Stage[main]/Main/Php::Module[mysqlnd]/Package[PhpModule_mysqlnd]: Scheduling refresh of Service[php5-fpm]
Notice: /Stage[main]/Main/Php_mod[intl]/Puphpet::Php::Module[intl]/Php::Module[intl]/Package[PhpModule_intl]/ensure: ensure changed 'purged' to 'present'
Info: /Stage[main]/Main/Php_mod[intl]/Puphpet::Php::Module[intl]/Php::Module[intl]/Package[PhpModule_intl]: Scheduling refresh of Service[php5-fpm]
Notice: /Stage[main]/Main/Service[php5-fpm]: Triggered 'refresh' from 9 events
Notice: /Stage[main]/Apache::Default_mods/Apache::Mod[authz_user]/File[authz_user.load symlink]: Dependency Package[httpd] has failures: true
Notice: /Stage[main]/Apache/File[/etc/apache2/mods-enabled]: Dependency Package[httpd] has failures: true
Notice: /Stage[main]/Main/File[/var/run/apache2/ssl_mutex]: Dependency Package[httpd] has failures: true
Notice: /Stage[main]/Main/File[/var/run/apache2/ssl_mutex]: Dependency File[/var/www] has failures: true
Notice: /Stage[main]/Puphpet::Ssl_cert/Package[ssl-cert]: Dependency Package[httpd] has failures: true
Notice: /Stage[main]/Puphpet::Ssl_cert/Package[ssl-cert]: Dependency File[/var/www] has failures: true
Notice: /Stage[main]/Puphpet::Ssl_cert/Exec[make-ssl-cert generate-default-snakeoil --force-overwrite]: Dependency Package[httpd] has failures: true
Notice: /Stage[main]/Puphpet::Ssl_cert/Exec[make-ssl-cert generate-default-snakeoil --force-overwrite]: Dependency File[/var/www] has failures: true
Notice: /Stage[main]/Apache::Service/Service[httpd]: Dependency Package[httpd] has failures: true
Notice: /Stage[main]/Apache::Service/Service[httpd]: Dependency File[/var/www] has failures: true
Info: Creating state file /var/lib/puppet/state/state.yaml
Notice: Finished catalog run in 171.13 seconds

Stderr from the command:

stdin: is not a tty
Warning: Could not retrieve fact fqdn
Error: Failed to set group to '33': Operation not permitted - /var/www
Error: /Stage[main]/Main/File[/var/www]/group: change from apache to www-data failed: Failed to set group to '33': Operation not permitted - /var/www
Warning: /Stage[main]/Main/File[/var/www/default]: Skipping because of failed dependencies
Warning: /Stage[main]/Main/File[/var/www/sodrupal.localvm]: Skipping because of failed dependencies
Warning: /Stage[main]/Main/File[/var/www/awesome]: Skipping because of failed dependencies
Error: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install apache2' returned 100: Reading package lists...
Building dependency tree...
Reading state information...
The following extra packages will be installed:
  apache2-bin apache2-data libapr1 libaprutil1 libaprutil1-dbd-sqlite3
  libaprutil1-ldap liblua5.1-0 ssl-cert
Suggested packages:
  www-browser apache2-doc apache2-suexec-pristine apache2-suexec-custom
  apache2-utils openssl-blacklist
The following NEW packages will be installed:
  apache2 apache2-bin apache2-data libapr1 libaprutil1 libaprutil1-dbd-sqlite3
  libaprutil1-ldap liblua5.1-0 ssl-cert
0 upgraded, 9 newly installed, 0 to remove and 53 not upgraded.
Need to get 1775 kB of archives.
After this operation, 5948 kB of additional disk space will be used.
Get:1 http://ppa.launchpad.net/ondrej/apache2/ubuntu/ precise/main libapr1 amd64 1.5.1-2+deb.sury.org~precise+1 [106 kB]
Get:2 http://ppa.launchpad.net/ondrej/apache2/ubuntu/ precise/main libaprutil1 amd64 1.5.3-2+deb.sury.org~precise+1 [97.6 kB]
Get:3 http://ppa.launchpad.net/ondrej/apache2/ubuntu/ precise/main libaprutil1-dbd-sqlite3 amd64 1.5.3-2+deb.sury.org~precise+1 [20.5 kB]
Get:4 http://ppa.launchpad.net/ondrej/apache2/ubuntu/ precise/main libaprutil1-ldap amd64 1.5.3-2+deb.sury.org~precise+1 [18.1 kB]
Get:5 http://ppa.launchpad.net/ondrej/apache2/ubuntu/ precise/main apache2-bin amd64 2.4.10-1+deb.sury.org~precise+1 [988 kB]
Get:6 http://us.archive.ubuntu.com/ubuntu/ precise/main liblua5.1-0 amd64 5.1.4-12ubuntu1 [172 kB]
Get:7 http://ppa.launchpad.net/ondrej/apache2/ubuntu/ precise/main apache2-data all 2.4.10-1+deb.sury.org~precise+1 [162 kB]
Get:8 http://ppa.launchpad.net/ondrej/apache2/ubuntu/ precise/main apache2 amd64 2.4.10-1+deb.sury.org~precise+1 [199 kB]
Get:9 http://us.archive.ubuntu.com/ubuntu/ precise-updates/main ssl-cert all 1.0.28ubuntu0.1 [12.3 kB]
Preconfiguring packages ...
Fetched 1775 kB in 0s (2256 kB/s)
Selecting previously unselected package libapr1.
(Reading database ... 60047 files and directories currently installed.)
Unpacking libapr1 (from .../libapr1_1.5.1-2+deb.sury.org~precise+1_amd64.deb) ...
Selecting previously unselected package libaprutil1.
Unpacking libaprutil1 (from .../libaprutil1_1.5.3-2+deb.sury.org~precise+1_amd64.deb) ...
Selecting previously unselected package liblua5.1-0.
Unpacking liblua5.1-0 (from .../liblua5.1-0_5.1.4-12ubuntu1_amd64.deb) ...
Selecting previously unselected package libaprutil1-dbd-sqlite3.
Unpacking libaprutil1-dbd-sqlite3 (from .../libaprutil1-dbd-sqlite3_1.5.3-2+deb.sury.org~precise+1_amd64.deb) ...
Selecting previously unselected package libaprutil1-ldap.
Unpacking libaprutil1-ldap (from .../libaprutil1-ldap_1.5.3-2+deb.sury.org~precise+1_amd64.deb) ...
Selecting previously unselected package apache2-bin.
Unpacking apache2-bin (from .../apache2-bin_2.4.10-1+deb.sury.org~precise+1_amd64.deb) ...
Selecting previously unselected package apache2-data.
Unpacking apache2-data (from .../apache2-data_2.4.10-1+deb.sury.org~precise+1_all.deb) ...
Selecting previously unselected package apache2.
Unpacking apache2 (from .../apache2_2.4.10-1+deb.sury.org~precise+1_amd64.deb) ...
dpkg: error processing /var/cache/apt/archives/apache2_2.4.10-1+deb.sury.org~precise+1_amd64.deb (--unpack):
 error setting ownership of `/var/www/html.dpkg-new': Operation not permitted
dpkg-deb (subprocess): subprocess data was killed by signal (Broken pipe)
dpkg-deb: error: subprocess <decompress> returned error exit status 2
Selecting previously unselected package ssl-cert.
Unpacking ssl-cert (from .../ssl-cert_1.0.28ubuntu0.1_all.deb) ...
Processing triggers for man-db ...
Errors were encountered while processing:
 /var/cache/apt/archives/apache2_2.4.10-1+deb.sury.org~precise+1_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

Error: /Stage[main]/Apache/Package[httpd]/ensure: change from purged to present failed: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install apache2' returned 100: Reading package lists...
Building dependency tree...
Reading state information...
The following extra packages will be installed:
  apache2-bin apache2-data libapr1 libaprutil1 libaprutil1-dbd-sqlite3
  libaprutil1-ldap liblua5.1-0 ssl-cert
Suggested packages:
  www-browser apache2-doc apache2-suexec-pristine apache2-suexec-custom
  apache2-utils openssl-blacklist
The following NEW packages will be installed:
  apache2 apache2-bin apache2-data libapr1 libaprutil1 libaprutil1-dbd-sqlite3
  libaprutil1-ldap liblua5.1-0 ssl-cert
0 upgraded, 9 newly installed, 0 to remove and 53 not upgraded.
Need to get 1775 kB of archives.
After this operation, 5948 kB of additional disk space will be used.
Get:1 http://ppa.launchpad.net/ondrej/apache2/ubuntu/ precise/main libapr1 amd64 1.5.1-2+deb.sury.org~precise+1 [106 kB]
Get:2 http://ppa.launchpad.net/ondrej/apache2/ubuntu/ precise/main libaprutil1 amd64 1.5.3-2+deb.sury.org~precise+1 [97.6 kB]
Get:3 http://ppa.launchpad.net/ondrej/apache2/ubuntu/ precise/main libaprutil1-dbd-sqlite3 amd64 1.5.3-2+deb.sury.org~precise+1 [20.5 kB]
Get:4 http://ppa.launchpad.net/ondrej/apache2/ubuntu/ precise/main libaprutil1-ldap amd64 1.5.3-2+deb.sury.org~precise+1 [18.1 kB]
Get:5 http://ppa.launchpad.net/ondrej/apache2/ubuntu/ precise/main apache2-bin amd64 2.4.10-1+deb.sury.org~precise+1 [988 kB]
Get:6 http://us.archive.ubuntu.com/ubuntu/ precise/main liblua5.1-0 amd64 5.1.4-12ubuntu1 [172 kB]
Get:7 http://ppa.launchpad.net/ondrej/apache2/ubuntu/ precise/main apache2-data all 2.4.10-1+deb.sury.org~precise+1 [162 kB]
Get:8 http://ppa.launchpad.net/ondrej/apache2/ubuntu/ precise/main apache2 amd64 2.4.10-1+deb.sury.org~precise+1 [199 kB]
Get:9 http://us.archive.ubuntu.com/ubuntu/ precise-updates/main ssl-cert all 1.0.28ubuntu0.1 [12.3 kB]
Preconfiguring packages ...
Fetched 1775 kB in 0s (2256 kB/s)
Selecting previously unselected package libapr1.
(Reading database ... 60047 files and directories currently installed.)
Unpacking libapr1 (from .../libapr1_1.5.1-2+deb.sury.org~precise+1_amd64.deb) ...
Selecting previously unselected package libaprutil1.
Unpacking libaprutil1 (from .../libaprutil1_1.5.3-2+deb.sury.org~precise+1_amd64.deb) ...
Selecting previously unselected package liblua5.1-0.
Unpacking liblua5.1-0 (from .../liblua5.1-0_5.1.4-12ubuntu1_amd64.deb) ...
Selecting previously unselected package libaprutil1-dbd-sqlite3.
Unpacking libaprutil1-dbd-sqlite3 (from .../libaprutil1-dbd-sqlite3_1.5.3-2+deb.sury.org~precise+1_amd64.deb) ...
Selecting previously unselected package libaprutil1-ldap.
Unpacking libaprutil1-ldap (from .../libaprutil1-ldap_1.5.3-2+deb.sury.org~precise+1_amd64.deb) ...
Selecting previously unselected package apache2-bin.
Unpacking apache2-bin (from .../apache2-bin_2.4.10-1+deb.sury.org~precise+1_amd64.deb) ...
Selecting previously unselected package apache2-data.
Unpacking apache2-data (from .../apache2-data_2.4.10-1+deb.sury.org~precise+1_all.deb) ...
Selecting previously unselected package apache2.
Unpacking apache2 (from .../apache2_2.4.10-1+deb.sury.org~precise+1_amd64.deb) ...
dpkg: error processing /var/cache/apt/archives/apache2_2.4.10-1+deb.sury.org~precise+1_amd64.deb (--unpack):
 error setting ownership of `/var/www/html.dpkg-new': Operation not permitted
dpkg-deb (subprocess): subprocess data was killed by signal (Broken pipe)
dpkg-deb: error: subprocess <decompress> returned error exit status 2
Selecting previously unselected package ssl-cert.
Unpacking ssl-cert (from .../ssl-cert_1.0.28ubuntu0.1_all.deb) ...
Processing triggers for man-db ...
Errors were encountered while processing:
 /var/cache/apt/archives/apache2_2.4.10-1+deb.sury.org~precise+1_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

Warning: /Stage[main]/Apache/Exec[mkdir /etc/apache2/conf.d]: Skipping because of failed dependencies
Warning: /Stage[main]/Apache/File[/etc/apache2/sites-enabled]: Skipping because of failed dependencies
Warning: /Stage[main]/Apache/File[/etc/apache2/apache2.conf]: Skipping because of failed dependencies
Warning: /Stage[main]/Apache/Exec[mkdir /etc/apache2/mods-enabled]: Skipping because of failed dependencies
Warning: /Stage[main]/Apache/Exec[mkdir /etc/apache2/sites-enabled]: Skipping because of failed dependencies
Warning: /Stage[main]/Apache/File[/etc/apache2/conf.d]: Skipping because of failed dependencies
Warning: /Stage[main]/Apache/Exec[mkdir /etc/apache2/sites-available]: Skipping because of failed dependencies
Warning: /Stage[main]/Apache/Exec[mkdir /etc/apache2/mods-available]: Skipping because of failed dependencies
Warning: /Stage[main]/Apache::Mod::Mime/Apache::Mod[mime]/File[mime.load]: Skipping because of failed dependencies
Warning: /Stage[main]/Apache::Mod::Ssl/File[ssl.conf]: Skipping because of failed dependencies
Warning: /Stage[main]/Apache::Mod::Dav/Apache::Mod[dav]/File[dav.load]: Skipping because of failed dependencies
Warning: /Stage[main]/Apache::Mod::Mime/Apache::Mod[mime]/File[mime.load symlink]: Skipping because of failed dependencies
Warning: /Stage[main]/Apache::Default_mods/Apache::Mod[authz_groupfile]/File[authz_groupfile.load]: Skipping because of failed dependencies
Warning: /Stage[main]/Apache::Mod::Reqtimeout/File[reqtimeout.conf]: Skipping because of failed dependencies
Warning: /Stage[main]/Apache::Default_mods/Apache::Mod[authz_groupfile]/File[authz_groupfile.load symlink]: Skipping because of failed dependencies
Warning: /Stage[main]/Apache::Default_mods/Apache::Mod[authz_user]/File[authz_user.load]: Skipping because of failed dependencies
Warning: /Stage[main]/Apache::Mod::Ssl/Apache::Mod[socache_shmcb]/File[socache_shmcb.load]: Skipping because of failed dependencies
Warning: /Stage[main]/Apache::Mod::Mime/File[mime.conf]: Skipping because of failed dependencies
Warning: /Stage[main]/Apache::Default_mods/Apache::Mod[access_compat]/File[access_compat.load]: Skipping because of failed dependencies
Warning: /Stage[main]/Apache::Default_mods/Apache::Mod[access_compat]/File[access_compat.load symlink]: Skipping because of failed dependencies
Warning: /Stage[main]/Apache::Mod::Setenvif/File[setenvif.conf]: Skipping because of failed dependencies
Warning: /Stage[main]/Puphpet::Apache::Fpm/Apache::Mod[actions]/File[actions.load]: Skipping because of failed dependencies
Warning: /Stage[main]/Apache::Mod::Deflate/File[deflate.conf]: Skipping because of failed dependencies
Warning: /Stage[main]/Apache::Mod::Proxy/Apache::Mod[proxy]/File[proxy.load]: Skipping because of failed dependencies
Warning: /Stage[main]/Apache::Mod::Proxy/Apache::Mod[proxy]/File[proxy.load symlink]: Skipping because of failed dependencies
Warning: /Stage[main]/Apache::Default_mods/Apache::Mod[authz_core]/File[authz_core.load]: Skipping because of failed dependencies
Warning: /Stage[main]/Apache::Mod::Negotiation/File[negotiation.conf]: Skipping because of failed dependencies
Warning: /Stage[main]/Apache::Mod::Negotiation/Apache::Mod[negotiation]/File[negotiation.conf symlink]: Skipping because of failed dependencies
Warning: /Stage[main]/Apache::Mod::Alias/Apache::Mod[alias]/File[alias.load]: Skipping because of failed dependencies
Warning: /Stage[main]/Apache::Mod::Alias/Apache::Mod[alias]/File[alias.load symlink]: Skipping because of failed dependencies
Warning: /Stage[main]/Apache::Mod::Ssl/Apache::Mod[socache_shmcb]/File[socache_shmcb.load symlink]: Skipping because of failed dependencies
Warning: /Stage[main]/Apache::Default_mods/Apache::Mod[env]/File[env.load]: Skipping because of failed dependencies
Warning: /Stage[main]/Apache::Mod::Negotiation/Apache::Mod[negotiation]/File[negotiation.load]: Skipping because of failed dependencies
Warning: /Stage[main]/Apache::Mod::Dir/File[dir.conf]: Skipping because of failed dependencies
Warning: /Stage[main]/Apache::Mod::Dir/Apache::Mod[dir]/File[dir.conf symlink]: Skipping because of failed dependencies
Warning: /Stage[main]/Apache::Mod::Setenvif/Apache::Mod[setenvif]/File[setenvif.load]: Skipping because of failed dependencies
Warning: /Stage[main]/Apache::Mod::Deflate/Apache::Mod[deflate]/File[deflate.conf symlink]: Skipping because of failed dependencies
Warning: /Stage[main]/Apache::Mod::Deflate/Apache::Mod[deflate]/File[deflate.load]: Skipping because of failed dependencies
Warning: /Stage[main]/Apache::Mod::Deflate/Apache::Mod[deflate]/File[deflate.load symlink]: Skipping because of failed dependencies
Warning: /Stage[main]/Apache::Mod::Reqtimeout/Apache::Mod[reqtimeout]/File[reqtimeout.conf symlink]: Skipping because of failed dependencies
Warning: /Stage[main]/Puphpet::Apache::Fpm/Apache::Mod[proxy_fcgi]/File[proxy_fcgi.load]: Skipping because of failed dependencies
Warning: /Stage[main]/Puphpet::Apache::Fpm/Apache::Mod[proxy_fcgi]/File[proxy_fcgi.load symlink]: Skipping because of failed dependencies
Warning: /Stage[main]/Apache::Mod::Setenvif/Apache::Mod[setenvif]/File[setenvif.load symlink]: Skipping because of failed dependencies
Warning: /Stage[main]/Apache::Default_mods/Apache::Mod[auth_basic]/File[auth_basic.load]: Skipping because of failed dependencies
Warning: /Stage[main]/Apache::Default_mods/Apache::Mod[auth_basic]/File[auth_basic.load symlink]: Skipping because of failed dependencies
Warning: /Stage[main]/Apache/Concat[/etc/apache2/ports.conf]/File[/var/lib/puppet/concat/_etc_apache2_ports.conf]: Skipping because of failed dependencies
Warning: /Stage[main]/Apache/Concat[/etc/apache2/ports.conf]/File[/var/lib/puppet/concat/_etc_apache2_ports.conf/fragments.concat.out]: Skipping because of failed dependencies
Warning: /Stage[main]/Apache::Default_mods/Apache::Mod[authn_file]/File[authn_file.load]: Skipping because of failed dependencies
Warning: /Stage[main]/Apache::Default_mods/Apache::Mod[authn_file]/File[authn_file.load symlink]: Skipping because of failed dependencies
Warning: /Stage[main]/Apache/Apache::Vhost[default]/File[/var/log/apache2]: Skipping because of failed dependencies
Warning: /Stage[main]/Apache::Mod::Dav/Apache::Mod[dav]/File[dav.load symlink]: Skipping because of failed dependencies
Warning: /Stage[main]/Apache::Mod::Reqtimeout/Apache::Mod[reqtimeout]/File[reqtimeout.load]: Skipping because of failed dependencies
Warning: /Stage[main]/Apache::Mod::Reqtimeout/Apache::Mod[reqtimeout]/File[reqtimeout.load symlink]: Skipping because of failed dependencies
Warning: /Stage[main]/Apache/Concat[/etc/apache2/ports.conf]/File[/var/lib/puppet/concat/_etc_apache2_ports.conf/fragments.concat]: Skipping because of failed dependencies
Warning: /Stage[main]/Apache::Mod::Dir/Apache::Mod[dir]/File[dir.load]: Skipping because of failed dependencies
Warning: /Stage[main]/Apache::Mod::Dir/Apache::Mod[dir]/File[dir.load symlink]: Skipping because of failed dependencies
Warning: /Stage[main]/Apache::Mod::Mime/Apache::Mod[mime]/File[mime.conf symlink]: Skipping because of failed dependencies
Warning: /Stage[main]/Apache::Mod::Dav_fs/Apache::Mod[dav_fs]/File[dav_fs.load]: Skipping because of failed dependencies
Warning: /Stage[main]/Apache::Mod::Dav_fs/Apache::Mod[dav_fs]/File[dav_fs.load symlink]: Skipping because of failed dependencies
Warning: /Stage[main]/Apache::Mod::Alias/File[alias.conf]: Skipping because of failed dependencies
Warning: /Stage[main]/Apache::Mod::Ssl/Apache::Mod[ssl]/File[ssl.load]: Skipping because of failed dependencies
Warning: /Stage[main]/Apache::Mod::Ssl/Apache::Mod[ssl]/File[ssl.load symlink]: Skipping because of failed dependencies
Warning: /Stage[main]/Apache::Mod::Alias/Apache::Mod[alias]/File[alias.conf symlink]: Skipping because of failed dependencies
Warning: /Stage[main]/Apache::Mod::Ssl/Apache::Mod[ssl]/File[ssl.conf symlink]: Skipping because of failed dependencies
Warning: /Stage[main]/Apache::Default_mods/Apache::Mod[authz_core]/File[authz_core.load symlink]: Skipping because of failed dependencies
Warning: /Stage[main]/Apache::Mod::Negotiation/Apache::Mod[negotiation]/File[negotiation.load symlink]: Skipping because of failed dependencies
Warning: /Stage[main]/Apache/Concat[/etc/apache2/ports.conf]/File[/var/lib/puppet/concat/_etc_apache2_ports.conf/fragments]: Skipping because of failed dependencies
Warning: /Stage[main]/Main/Apache::Vhost[default_vhost_443]/Apache::Listen[443]/Concat::Fragment[Listen 443]/File[/var/lib/puppet/concat/_etc_apache2_ports.conf/fragments/10_Listen 443]: Skipping because of failed dependencies
Warning: /Stage[main]/Apache/Concat::Fragment[Apache ports header]/File[/var/lib/puppet/concat/_etc_apache2_ports.conf/fragments/10_Apache ports header]: Skipping because of failed dependencies
Warning: /Stage[main]/Main/Apache::Vhost[WiTpty6FbDiS]/Apache::Listen[80]/Concat::Fragment[Listen 80]/File[/var/lib/puppet/concat/_etc_apache2_ports.conf/fragments/10_Listen 80]: Skipping because of failed dependencies
Warning: /Stage[main]/Apache/Concat[/etc/apache2/ports.conf]/Exec[concat_/etc/apache2/ports.conf]: Skipping because of failed dependencies
Warning: /Stage[main]/Apache/File[/etc/apache2/sites-available]: Skipping because of failed dependencies
Warning: /Stage[main]/Main/Apache::Vhost[kXs3BcpVp7SJ]/File[25-kXs3BcpVp7SJ.conf]: Skipping because of failed dependencies
Warning: /Stage[main]/Main/Apache::Vhost[kXs3BcpVp7SJ]/File[25-kXs3BcpVp7SJ.conf symlink]: Skipping because of failed dependencies
Warning: /Stage[main]/Main/Apache::Vhost[default_vhost_80]/File[10-default_vhost_80.conf]: Skipping because of failed dependencies
Warning: /Stage[main]/Main/Apache::Vhost[default_vhost_80]/File[10-default_vhost_80.conf symlink]: Skipping because of failed dependencies
Warning: /Stage[main]/Main/Apache::Vhost[default_vhost_443]/File[10-default_vhost_443.conf]: Skipping because of failed dependencies
Warning: /Stage[main]/Main/Apache::Vhost[WiTpty6FbDiS]/File[25-WiTpty6FbDiS.conf]: Skipping because of failed dependencies
Warning: /Stage[main]/Main/Apache::Vhost[WiTpty6FbDiS]/File[25-WiTpty6FbDiS.conf symlink]: Skipping because of failed dependencies
Warning: /Stage[main]/Apache/Apache::Vhost[default]/File[15-default.conf]: Skipping because of failed dependencies
Warning: /Stage[main]/Main/Apache::Vhost[default_vhost_443]/File[10-default_vhost_443.conf symlink]: Skipping because of failed dependencies
Warning: /Stage[main]/Apache/Apache::Vhost[default]/File[15-default.conf symlink]: Skipping because of failed dependencies
Warning: /Stage[main]/Apache/Apache::Vhost[default-ssl]/File[15-default-ssl.conf]: Skipping because of failed dependencies
Warning: /Stage[main]/Apache/Apache::Vhost[default-ssl]/File[15-default-ssl.conf symlink]: Skipping because of failed dependencies
Warning: /Stage[main]/Apache/Concat[/etc/apache2/ports.conf]/File[/etc/apache2/ports.conf]: Skipping because of failed dependencies
Warning: /Stage[main]/Apache::Mod::Setenvif/Apache::Mod[setenvif]/File[setenvif.conf symlink]: Skipping because of failed dependencies
Warning: /Stage[main]/Apache::Mod::Rewrite/Apache::Mod[rewrite]/File[rewrite.load]: Skipping because of failed dependencies
Warning: /Stage[main]/Apache::Mod::Rewrite/Apache::Mod[rewrite]/File[rewrite.load symlink]: Skipping because of failed dependencies
Warning: /Stage[main]/Apache::Mod::Autoindex/Apache::Mod[autoindex]/File[autoindex.load]: Skipping because of failed dependencies
Warning: /Stage[main]/Apache::Mod::Autoindex/Apache::Mod[autoindex]/File[autoindex.load symlink]: Skipping because of failed dependencies
Warning: /Stage[main]/Puphpet::Apache::Fpm/Apache::Mod[actions]/File[actions.load symlink]: Skipping because of failed dependencies
Warning: /Stage[main]/Apache::Mod::Autoindex/File[autoindex.conf]: Skipping because of failed dependencies
Warning: /Stage[main]/Apache::Mod::Autoindex/Apache::Mod[autoindex]/File[autoindex.conf symlink]: Skipping because of failed dependencies
Warning: /Stage[main]/Apache::Mod::Proxy/File[proxy.conf]: Skipping because of failed dependencies
Warning: /Stage[main]/Apache::Default_mods/Apache::Mod[authz_host]/File[authz_host.load]: Skipping because of failed dependencies
Warning: /Stage[main]/Apache::Default_mods/Apache::Mod[authz_host]/File[authz_host.load symlink]: Skipping because of failed dependencies
Warning: /Stage[main]/Apache::Mod::Proxy/Apache::Mod[proxy]/File[proxy.conf symlink]: Skipping because of failed dependencies
Warning: /Stage[main]/Apache::Mod::Proxy_http/Apache::Mod[proxy_http]/File[proxy_http.load]: Skipping because of failed dependencies
Warning: /Stage[main]/Apache::Mod::Proxy_http/Apache::Mod[proxy_http]/File[proxy_http.load symlink]: Skipping because of failed dependencies
Warning: /Stage[main]/Apache::Default_mods/Apache::Mod[filter]/File[filter.load]: Skipping because of failed dependencies
Warning: /Stage[main]/Apache::Default_mods/Apache::Mod[filter]/File[filter.load symlink]: Skipping because of failed dependencies
Warning: /Stage[main]/Apache::Mod::Worker/Apache::Mpm[worker]/File[/etc/apache2/mods-available/worker.load]: Skipping because of failed dependencies
Warning: /Stage[main]/Apache::Mod::Worker/Apache::Mpm[worker]/File[/etc/apache2/mods-enabled/worker.load]: Skipping because of failed dependencies
Warning: /Stage[main]/Apache::Mod::Worker/File[/etc/apache2/mods-available/worker.conf]: Skipping because of failed dependencies
Warning: /Stage[main]/Apache::Mod::Worker/Apache::Mpm[worker]/File[/etc/apache2/mods-enabled/worker.conf]: Skipping because of failed dependencies
Warning: /Stage[main]/Apache::Mod::Cgid/File[cgid.conf]: Skipping because of failed dependencies
Warning: /Stage[main]/Apache::Mod::Cgid/Apache::Mod[cgid]/File[cgid.conf symlink]: Skipping because of failed dependencies
Warning: /Stage[main]/Apache::Mod::Cgid/Apache::Mod[cgid]/File[cgid.load]: Skipping because of failed dependencies
Warning: /Stage[main]/Apache::Mod::Cgid/Apache::Mod[cgid]/File[cgid.load symlink]: Skipping because of failed dependencies
Warning: /Stage[main]/Apache::Default_mods/Apache::Mod[env]/File[env.load symlink]: Skipping because of failed dependencies
Warning: /Stage[main]/Apache::Mod::Dav_fs/File[dav_fs.conf]: Skipping because of failed dependencies
Warning: /Stage[main]/Apache::Mod::Dav_fs/Apache::Mod[dav_fs]/File[dav_fs.conf symlink]: Skipping because of failed dependencies
Warning: /Stage[main]/Apache/File[/etc/apache2/mods-available]: Skipping because of failed dependencies
Warning: /Stage[main]/Apache::Default_mods/Apache::Mod[authz_user]/File[authz_user.load symlink]: Skipping because of failed dependencies
Warning: /Stage[main]/Apache/File[/etc/apache2/mods-enabled]: Skipping because of failed dependencies
Warning: /Stage[main]/Main/File[/var/run/apache2/ssl_mutex]: Skipping because of failed dependencies
Warning: /Stage[main]/Puphpet::Ssl_cert/Package[ssl-cert]: Skipping because of failed dependencies
Warning: /Stage[main]/Puphpet::Ssl_cert/Exec[make-ssl-cert generate-default-snakeoil --force-overwrite]: Skipping because of failed dependencies
Warning: /Stage[main]/Apache::Service/Service[httpd]: Skipping because of failed dependencies

robdaviscommunity@Rob-ThinkPad-X201s:~/work/projects/dev/vms/puphpet$

**Comment by elvismdev** [comment]
Thanks @jtreminio the fix explained on the wiki post worked for me under Ubuntu 14.04

**Comment by kokoon** [comment]
The no_root_squash solution doesn't work for me, I still get the same error. 14.04 both on host and guest.

**Comment by tgroff** [comment]
This solution worked for me:
https://github.com/puphpet/puphpet/wiki/Shared-Folder:-Permission-Denied

From the comment here:
https://github.com/puphpet/puphpet/issues/940#issuecomment-65190004
