### ISSUE TITLE
Error: Could not set 'link' on ensure:

### ISSUE THREAD

**Issue by mariuszgomse** [puphpet/puphpet#946]
Today I updated puphpet and here is what I have after vagrant up:

Error: Command exceeded timeout
Error: /Stage[main]/Puphpet::Adminer/Exec[download adminer to /var/www/default/adminer]/returns: change from notrun to 0 4 failed: Command exceeded timeout
Error: Could not set 'link' on ensure: No such file or directory - /etc/php5/apache2/conf.d at 251:/tmp/vagrant-puppet-3/modules-0/puphpet/manifests/php/ini.pp
Error: Could not set 'link' on ensure: No such file or directory - /etc/php5/apache2/conf.d at 251:/tmp/vagrant-puppet-3/modules-0/puphpet/manifests/php/ini.pp
Wrapped exception:
No such file or directory - /etc/php5/apache2/conf.d
Error: /Stage[main]/Main/Puphpet::Php::Ini[xdebug.default_enable]/File[/etc/php5/apache2/conf.d/zzzz_custom.ini]/ensure: change from absent to link failed: Could not set 'link' on ensure: No such file or dir
ectory - /etc/php5/apache2/conf.d at 251:/tmp/vagrant-puppet-3/modules-0/puphpet/manifests/php/ini.pp

Can you tell me what is wrong ?

**Comment by rationalthinker1** [comment]
I still received this problem:
http://pastebin.com/iUfDy1zy

**Comment by kasn** [comment]
pull request by @mattalexx worked for me.
