### ISSUE TITLE
SSH known_hosts file or settings

### ISSUE THREAD

**Issue by shivapoudel** [puphpet/puphpet#999]
Updated the `ssh-keygen.sh` with [How to make Vagrant and Puppet to clone private github repo](http://rshestakov.wordpress.com/2014/01/26/how-to-make-vagrant-and-puppet-to-clone-private-github-repo/) as PuPHPet is not quiet good enough though this so fix this stage and include `.gitignore` file inside `files/dot/.ssh/` excluding `insecure_private_key` for major security issues.

Tip: ssh -T git@github.com to test and display `Hello, {{username}}.....`

**Comment by franz-josef-kaiser** [comment]
:+1:
